window.examTitle = "25_매산고_2학기_중간_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "집합의 뜻",
      "보기"
    ],
    "wide": false,
    "content": "다음 중 집합인 것만을 있는 대로 고른 것은? [3.7점]<div class=\"note-box\"><div style=\"text-align:center;font-weight:600;margin-bottom:4px;\">&lt;보기&gt;</div>ㄱ. 수학 문제를 잘 푸는 사람들의 모임<br>ㄴ. $\\sqrt2$보다 작은 정수의 모임<br>ㄷ. 마음이 착한 사람들의 모임<br>ㄹ. 제곱하여 음수가 되는 실수의 모임<br>ㅁ. 키가 $190\\mathrm{cm}$ 이상인 사람의 모임</div>",
    "choices": [
      "ㄱ, ㅁ",
      "ㄴ, ㅁ",
      "ㄷ, ㅁ",
      "ㄴ, ㄹ, ㅁ",
      "ㄷ, ㄹ, ㅁ"
    ],
    "answer": "④",
    "solution": "집합인지 아닌지는 어떤 대상이 그 모임에 속하는지 누구나 같은 기준으로 판단할 수 있는지를 보면 된다.\nㄱ. “수학 문제를 잘 푼다”는 기준이 사람마다 달라질 수 있으므로 집합이 아니다.\nㄴ. 어떤 정수가 $\\sqrt2$보다 작은지는 분명하게 판단할 수 있으므로 집합이다.\nㄷ. “마음이 착하다”는 기준이 명확하지 않으므로 집합이 아니다.\nㄹ. 모든 실수 $x$에 대하여 $x^2\\ge0$이므로 제곱하여 음수가 되는 실수는 없다.\n따라서 이 모임은 공집합이고, 공집합도 하나의 집합이다.\nㅁ. 키가 $190\\mathrm{cm}$ 이상인지 여부는 수치로 분명하게 판단할 수 있으므로 집합이다.\n따라서 집합인 것은 ㄴ, ㄹ, ㅁ이므로 정답은 ④이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
                    {
    "id": 2,
    "level": "하",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "직선의 방정식",
      "평행선",
      "도형",
      "직선",
      "평행"
    ],
    "wide": false,
    "content": "좌표평면 위의 점 $(6,4)$를 지나고, 직선 $x-3y+3=0$에 평행한 직선이 존재한다. 이 직선이 점 $(k,-1)$을 지날 때, $k$의 값은? (단, $k$는 실수) [3.8점]",
    "choices": [
      "$-9$",
      "$-6$",
      "$-3$",
      "$3$",
      "$9$"
    ],
    "answer": "①",
    "solution": "평행한 두 직선은 기울기가 같다.\n\n먼저 주어진 직선\n$x-3y+3=0$\n을 $y$에 대하여 정리한다.\n$-3y=-x-3$\n$y=\\dfrac13x+1$이다.\n따라서 기울기는 $\\dfrac13$이다.\n구하는 직선도 기울기가 $\\dfrac13$이고 점 $(6,4)$를 지나므로\n$y-4=\\dfrac13(x-6)$이다.\n양변에 $3$을 곱하면\n$3y-12=x-6$\n$x-3y+6=0$이다.\n이 직선이 점 $(k,-1)$을 지나므로 $x=k$, $y=-1$을 대입한다.\n$k-3(-1)+6=0$\n$k+3+6=0$\n$k+9=0$\n$k=-9$이다.\n따라서 정답은 ①이다.",
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q02-solution.svg",
    "solutionImageAlt": "직선의 방정식 문항 2의 실제 점과 직선 관계를 표시한 해설 도형",
    "solutionImageCaption": "평행 관계 · 주어진 직선 x−3y+3=0 · 두 직선은 평행",
    "solutionImageSize": "full"
  },
  {
    "id": 3,
    "level": "하",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "교집합"
    ],
    "wide": false,
    "content": "전체집합 $U=\\{2,4,6,8,10\\}$의 두 부분집합 $A=\\{2,4\\}$, $B=\\{4,6,8\\}$에 대하여 집합 $A\\cap B$의 모든 원소의 합은? [3.9점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "④",
    "solution": "교집합은 두 집합에 공통으로 들어 있는 원소의 집합이다.\n$A=\\{2,4\\}$,\n$B=\\{4,6,8\\}$이다.\n두 집합에 모두 들어 있는 원소는 $4$뿐이므로\n$A\\cap B=\\{4\\}$이다.\n따라서 $A\\cap B$의 모든 원소의 합은\n$4$이다.\n그러므로 정답은 ④이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 4,
    "level": "하",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "도형의 이동",
      "평행이동",
      "직선"
    ],
    "wide": false,
    "content": "점 $(0,0)$을 점 $(2,-3)$으로 이동시키는 평행이동에 의하여 직선 $3x+2y+8=0$이 이동한 도형이 $ax-by+8=0$일 때, 상수 $a,b$에 대하여 $a-b$의 값은? [4.0점]",
    "choices": [
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "answer": "③",
    "solution": "점 $(0,0)$이 $(2,-3)$으로 이동하므로 $x$축의 방향으로 $2$만큼, $y$축의 방향으로 $-3$만큼 평행이동한다.\n도형을 $(p,q)$만큼 평행이동한 뒤의 방정식은 원래 식에서\n$x$ 대신 $x-p$, $y$ 대신 $y-q$를 넣어 구할 수 있다.\n여기서는 $p=2$, $q=-3$이므로\n$x\\rightarrow x-2$, $y\\rightarrow y+3$으로 바꾼다.\n따라서 직선\n$3x+2y+8=0$\n을 평행이동한 직선은\n$3(x-2)+2(y+3)+8=0$이다.\n전개하면\n$3x-6+2y+6+8=0$\n$3x+2y+8=0$이다.\n이 식을\n$ax-by+8=0$\n과 비교한다.\n$x$의 계수를 비교하면\n$a=3$이고,\n$y$의 계수를 비교하면\n$-b=2$이므로\n$b=-2$이다.\n따라서\n$a-b=3-(-2)=5$이다.\n따라서 정답은 ③이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q04-solution.svg",
    "solutionImageAlt": "도형의 이동 문항 4의 핵심 관계를 표시한 해설 도형",
    "solutionImageSize": "full"
  },
  {
    "id": 5,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "부분집합",
      "경우의 수"
    ],
    "wide": false,
    "content": "전체집합 $U$는 $10$ 이하의 자연수 전체의 집합이다. $U$의 부분집합 $X$에 대하여 $X\\cap\\{2,3,5,7\\}=\\{2,7\\}$을 만족시키는 집합 $X$의 개수는? [4.1점]",
    "choices": [
      "4",
      "8",
      "16",
      "32",
      "64"
    ],
    "answer": "⑤",
    "solution": "교집합 조건에서 반드시 포함해야 하는 원소와\n포함하면 안 되는 원소를 먼저 정한다.\n$X\\cap\\{2,3,5,7\\}=\\{2,7\\}$이므로\n$2,7\\in X$이고,\n$3,5\\notin X$이다.\n전체집합은 $10$ 이하의 자연수 전체이므로\n$U=\\{1,2,3,4,5,6,7,8,9,10\\}$이다.\n따라서 아직 포함 여부를 자유롭게 정할 수 있는 원소는\n$1,4,6,8,9,10$\n의 $6$개이다.\n각 원소마다 $X$에 포함하는 경우와 포함하지 않는 경우의\n두 가지 선택이 가능하므로\n$2^6=64$\n개의 집합 $X$가 있다.\n따라서 정답은 ⑤이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
                    {
    "id": 6,
    "level": "중",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "직선의 방정식",
      "점과 직선 사이의 거리",
      "도형",
      "직선",
      "거리"
    ],
    "wide": false,
    "content": "직선 $y=x$ 위의 점 $P(a,b)$와 직선 $5x+12y-4=0$ 사이의 거리가 $1$일 때, $a+b$의 값은? (단, $a,b$는 정수이다.) [4.2점]",
    "choices": [
      "$-4$",
      "$-2$",
      "0",
      "2",
      "4"
    ],
    "answer": "④",
    "solution": "점 $P(a,b)$가 직선 $y=x$ 위에 있으므로\n$b=a$이다.\n따라서\n$P=(a,a)$로 둘 수 있다.\n점 $(x_1,y_1)$과 직선 $Ax+By+C=0$ 사이의 거리는\n$\\dfrac{|Ax_1+By_1+C|}{\\sqrt{A^2+B^2}}$\n이다.\n점 $(a,a)$와 직선\n$5x+12y-4=0$\n사이의 거리가 $1$이므로\n$\\dfrac{|5a+12a-4|}{\\sqrt{5^2+12^2}}=1$이다.\n분자와 분모를 정리하면\n$\\dfrac{|17a-4|}{13}=1$이다.\n따라서\n$|17a-4|=13$이다.\n절댓값을 두 경우로 나눈다.\n\n첫째,\n$17a-4=13$\n$17a=17$\n$a=1$이다.\n\n둘째,\n$17a-4=-13$\n$17a=-9$\n$a=-\\dfrac9{17}$이다.\n그런데 문제에서 $a,b$는 정수이고 $b=a$이므로\n두 번째 값은 사용할 수 없다.\n따라서\n$a=1$, $b=1$이다.\n그러므로\n$a+b=1+1=2$이다.\n따라서 정답은 ④이다.",
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q06-solution.svg",
    "solutionImageAlt": "직선의 방정식 문항 6의 실제 점과 직선 관계를 표시한 해설 도형",
    "solutionImageCaption": "P=(1,1) · H=(8/13,1/13), 거리=1",
    "solutionImageSize": "full"
  },
  {
    "id": 7,
    "level": "중",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["객관식","원의 방정식","중심","반지름","도형"],
    "wide": false,
    "content": "두 점 $A(5,-1)$, $B(-3,5)$를 지름의 양 끝점으로 하는 원의 방정식을 $x^2+y^2+ax+by+c=0$이라 할 때, $\\dfrac{bc}{a}$의 값은? [4.3점]",
    "choices": [
      "$-39$",
      "$-40$",
      "$-41$",
      "$-42$",
      "$-43$"
    ],
    "answer": "②",
    "solution": "두 점 $A$, $B$가 지름의 양 끝점이므로 원의 중심은 선분 $AB$의 중점이다.\n$A(5,-1)$, $B(-3,5)$의 중점은\n$\\left(\\dfrac{5+(-3)}2,\\dfrac{-1+5}2\\right)$\n$=\\left(\\dfrac22,\\dfrac42\\right)$\n$=(1,2)$이다.\n\n이제 지름 $AB$의 길이를 구한다.\n$AB=\\sqrt{(-3-5)^2+(5-(-1))^2}$\n$=\\sqrt{(-8)^2+6^2}$\n$=\\sqrt{64+36}$\n$=\\sqrt{100}=10$이다.\n반지름은 지름의 절반이므로\n$r=5$이다.\n따라서 원의 방정식은\n$(x-1)^2+(y-2)^2=25$이다.\n전개하면\n$x^2-2x+1+y^2-4y+4=25$\n$x^2+y^2-2x-4y-20=0$이다.\n주어진 식\n$x^2+y^2+ax+by+c=0$\n과 비교하면\n$a=-2$, $b=-4$, $c=-20$이다.\n따라서\n$\\dfrac{bc}{a}$\n$=\\dfrac{(-4)(-20)}{-2}$\n$=\\dfrac{80}{-2}$\n$=-40$이다.\n따라서 정답은 ②이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q07-solution.svg",
    "solutionImageAlt": "지름의 양 끝점 A, B와 중점 C(1,2), 반지름 5인 원을 나타낸 그림",
    "solutionImageCaption": "중점과 거리로 원의 표준형을 만든 뒤 전개해 계수를 비교한다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 8,
    "level": "중",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "도형의 이동",
      "대칭이동",
      "평행이동",
      "직선"
    ],
    "wide": false,
    "content": "직선 $(a-2)x-2y-10=0$을 $x$축에 대하여 대칭이동하고, $y$축 방향으로 $3$만큼 평행이동한 후, 직선 $y=x$에 대하여 대칭이동하였더니 원 $(x-2)^2+(y+2)^2=8$의 넓이를 이등분하였다. 이때 상수 $a$의 값은? [4.4점]",
    "choices": [
      "$-1$",
      "$-2$",
      "$-3$",
      "$-4$",
      "$-5$"
    ],
    "answer": "④",
    "solution": "직선의 이동을 문제에 적힌 순서대로 하나씩 적용한다.\n처음 직선은\n$(a-2)x-2y-10=0$이다.\n\n먼저 $x$축에 대하여 대칭이동한다.\n$x$축 대칭에서는 $(x,y)$가 $(x,-y)$로 바뀌므로 식의 $y$ 대신 $-y$를 넣는다.\n$(a-2)x-2(-y)-10=0$\n따라서\n$(a-2)x+2y-10=0$이다.\n이 직선을 $y$축의 방향으로 $3$만큼, 즉 위로 $3$만큼 평행이동한다.\n위로 $3$만큼 이동한 식은 $y$ 대신 $y-3$을 넣어 구한다.\n$(a-2)x+2(y-3)-10=0$\n$(a-2)x+2y-16=0$이다.\n\n마지막으로 직선 $y=x$에 대하여 대칭이동한다.\n$y=x$ 대칭에서는 $x$와 $y$의 역할이 서로 바뀌므로\n$(a-2)y+2x-16=0$이다.\n즉 최종 직선은\n$2x+(a-2)y-16=0$이다.\n이 직선이 원\n$(x-2)^2+(y+2)^2=8$\n의 넓이를 이등분한다.\n원을 넓이가 같은 두 부분으로 나누는 직선은 원의 중심을 지나므로,\n원의 중심 $(2,-2)$가 이 직선 위에 있다.\n$x=2$, $y=-2$를 대입하면\n$2\\cdot2+(a-2)(-2)-16=0$\n$4-2a+4-16=0$\n$-2a-8=0$\n$a=-4$이다.\n따라서 정답은 ④이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q08-solution.svg",
    "solutionImageAlt": "도형의 이동 문항 8의 핵심 관계를 표시한 해설 도형",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 9,
    "level": "중",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "평면좌표",
      "내분점",
      "수직인 직선",
      "도형"
    ],
    "wide": false,
    "content": "두 점 $A(-2,3)$, $B(6,a)$가 있다. 선분 $AB$를 $1:3$으로 내분하는 점을 지나고, 선분 $AB$에 수직인 직선의 방정식이 $y=2x+k$일 때, $a+k$의 값은? [4.5점]",
    "choices": [
      "$-1$",
      "0",
      "1",
      "2",
      "3"
    ],
    "answer": "③",
    "solution": "직선 $y=2x+k$의 기울기는 $2$이다.\n이 직선이 선분 $AB$에 수직이므로 선분 $AB$가 놓인 직선의 기울기는\n$-\\dfrac12$이다.\n두 점\n$A(-2,3)$, $B(6,a)$를 지나는 직선의 기울기는\n$\\dfrac{a-3}{6-(-2)}$\n$=\\dfrac{a-3}{8}$이다.\n따라서\n$\\dfrac{a-3}{8}=-\\dfrac12$이다.\n양변에 $8$을 곱하면\n$a-3=-4$\n$a=-1$이다.\n\n이제 $B=(6,-1)$이다.\n선분 $AB$를 $1:3$으로 내분하는 점을 $P$라 하자.\n$AP:PB=1:3$이므로 내분점 공식에서 $A$에는 반대쪽 비 $3$, $B$에는 반대쪽 비 $1$을 곱한다.\n따라서\n$P=\\left(\\dfrac{3(-2)+1\\cdot6}{1+3},\\dfrac{3\\cdot3+1\\cdot(-1)}{1+3}\\right)$\n$=\\left(\\dfrac{-6+6}{4},\\dfrac{9-1}{4}\\right)$\n$=(0,2)$이다.\n점 $P(0,2)$가 직선\n$y=2x+k$\n위에 있으므로\n$2=2\\cdot0+k$\n$k=2$이다.\n따라서\n$a+k=-1+2=1$이다.\n따라서 정답은 ③이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q09-solution.svg",
    "solutionImageAlt": "평면좌표 문항 9의 핵심 관계를 표시한 해설 도형",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-01-COORDINATE_METRIC",
    "subUnit": "평면좌표와 거리",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 10,
    "level": "중",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["객관식","원의 방정식","접선","좌표축 접원","중심","반지름","거리","도형"],
    "wide": false,
    "content": "아래 그림은 좌표평면 위에 지구의 중심을 원점으로 하고, 지구를 원 $x^2+y^2=9$로, 인공위성을 점 $A(15,0)$으로 나타낸 것이다. 인공위성이 지구를 관측할 수 있는 영역은 점 $A$에서 지구에 그은 접선의 방정식으로 예측할 수 있다. 이 인공위성에서 지구에 접선을 그었을 때, 두 접선의 기울기의 곱은 $-\\dfrac ba$이다. $a+b$의 값은? (단, $a>0$, $b>0$, $a,b$는 서로소인 자연수) [4.5점]",
    "choices": [
      "23",
      "24",
      "25",
      "26",
      "27"
    ],
    "answer": "③",
    "solution": "점 $A(15,0)$에서 원\n$x^2+y^2=9$\n에 그은 접선의 기울기를 $m$이라 하자.\n점 $A(15,0)$을 지나고 기울기가 $m$인 직선은\n$y=m(x-15)$이다.\n이를 일반형으로 정리하면\n$mx-y-15m=0$이다.\n이 직선이 원에 접하므로 원의 중심 $O(0,0)$에서 직선까지의 거리는 반지름 $3$과 같다.\n따라서\n$\\dfrac{|m\\cdot0-0-15m|}{\\sqrt{m^2+(-1)^2}}=3$이다.\n즉\n$\\dfrac{15|m|}{\\sqrt{m^2+1}}=3$이다.\n양변은 음수가 아니므로 제곱하여 정리한다.\n$\\dfrac{225m^2}{m^2+1}=9$\n$225m^2=9(m^2+1)$\n$225m^2=9m^2+9$\n$216m^2=9$\n$m^2=\\dfrac1{24}$이다.\n점 $A$에서 원에 그은 두 접선은 $x$축에 대하여 서로 대칭이므로 기울기는 부호만 반대이다.\n따라서 두 기울기의 곱은\n$m\\cdot(-m)=-m^2=-\\dfrac1{24}$이다.\n\n문제에서 이 값을\n$-\\dfrac ba$\n로 나타냈고 $a,b$는 서로소인 양의 자연수이므로\n$a=24$, $b=1$이다.\n따라서\n$a+b=24+1=25$이다.\n따라서 정답은 ③이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q10-solution.svg",
    "solutionImageAlt": "지구 원 x²+y²=9와 점 A(15,0)에서 그은 두 접선을 나타낸 그림",
    "solutionImageCaption": "원점에서 접선까지의 거리를 반지름 3과 같게 두어 두 기울기를 구한다.",
    "solutionImageSize": "full",
    "image": "assets/images/25_매산고_2학기_중간_고1_기출/q10.png",
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 11,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "포함배제",
      "활용"
    ],
    "wide": false,
    "content": "우리 학교 어느 학년 학생 $90$명을 대상으로 세 영화 $A$, $B$, $C$의 관람 여부를 조사하였더니 영화 $A$, $B$, $C$를 관람한 학생이 각각 $30$명, $48$명, $52$명이고, 세 영화를 전부 관람한 학생이 $9$명이다. 이때 영화를 두 종류만 감상한 학생 수는? (단, 영화 $A$, $B$, $C$를 하나도 관람하지 않은 학생은 없다.) [4.6점]",
    "choices": [
      "21",
      "22",
      "23",
      "24",
      "25"
    ],
    "answer": "②",
    "solution": "영화를 한 편만 관람한 학생 수를 $x$명,\n두 편만 관람한 학생 수를 $y$명이라 하자.\n세 편을 모두 관람한 학생은 $9$명이고,\n한 편도 관람하지 않은 학생은 없으므로\n$x+y+9=90$이다.\n따라서\n$x+y=81$이다.\n이번에는 전체 관람 횟수를 센다.\n각 영화의 관람 학생 수를 모두 더하면\n$30+48+52=130$이다.\n한 편만 본 학생은 관람 횟수에 $1$번,\n두 편만 본 학생은 $2$번,\n세 편 모두 본 학생은 $3$번씩 포함된다.\n따라서\n$x+2y+3\\cdot9=130$이다.\n정리하면\n$x+2y=103$이다.\n두 식\n$x+y=81$,\n$x+2y=103$\n을 빼면\n$y=22$이다.\n따라서 두 편의 영화만 관람한 학생은\n$22$명이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 12,
    "level": "중",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "도형의 이동",
      "대칭이동",
      "최단거리"
    ],
    "wide": false,
    "content": "점 $A(-5,-3)$을 $x$축에 대하여 대칭이동한 점의 좌표를 $B$라 하고, 점 $B$를 $y$축 방향으로 $-2$만큼 평행이동한 점의 좌표를 $C$라 할 때, 두 점 $B,C$와 직선 $y=x$ 위를 움직이는 점 $P$에 대하여<br>$\\overline{BP}+\\overline{CP}$의 최솟값은? [4.6점]",
    "choices": [
      "10",
      "12",
      "14",
      "16",
      "18"
    ],
    "answer": "①",
    "solution": "먼저 점 $B$, $C$의 좌표를 구한다.\n점 $A(-5,-3)$을 $x$축에 대하여 대칭이동하면 $y$좌표의 부호가 바뀌므로\n$B=(-5,3)$이다.\n점 $B$를 $y$축의 방향으로 $-2$만큼, 즉 아래로 $2$만큼 평행이동하면\n$C=(-5,1)$이다.\n\n이제 점 $P$는 직선 $y=x$ 위를 움직인다.\n꺾인 거리 $BP+CP$의 최솟값을 구하기 위해 점 $B$를 직선 $y=x$에 대하여 대칭이동한다.\n$y=x$ 대칭에서는 두 좌표가 서로 바뀌므로\n$B'=(3,-5)$이다.\n점 $P$가 대칭축 $y=x$ 위에 있으므로\n$BP=B'P$이다.\n따라서\n$BP+CP=B'P+PC$이다.\n두 점 $B'$, $C$ 사이를 점 $P$를 거쳐 가는 길이의 합은 두 점을 바로 잇는 거리보다 작을 수 없으므로\n$B'P+PC\\ge B'C$이다.\n또 선분 $B'C$는 직선 $y=x$와 실제로 만나므로 등호가 성립하는 점 $P$가 존재한다.\n따라서 최솟값은 $B'C$이다.\n$B'(3,-5)$, $C(-5,1)$이므로\n$B'C=\\sqrt{(-5-3)^2+(1-(-5))^2}$\n$=\\sqrt{(-8)^2+6^2}$\n$=\\sqrt{64+36}$\n$=\\sqrt{100}$\n$=10$이다.\n따라서 정답은 ①이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q12-solution.svg",
    "solutionImageAlt": "도형의 이동 문항 12의 핵심 관계를 표시한 해설 도형",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 13,
    "level": "상",
    "category": "행렬",
    "originalCategory": "행렬",
    "standardCourse": "공통수학1",
    "standardUnitKey": "H22-C-09",
    "standardUnit": "행렬과 그 연산",
    "standardUnitOrder": 9,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "행렬",
      "평면좌표",
      "자취",
      "절댓값"
    ],
    "wide": false,
    "content": "두 실수 $x,y$에 대하여 두 행렬 $A=\\begin{pmatrix}2&2\\\\1&|x|\\end{pmatrix}$, $B=\\begin{pmatrix}|y|&2\\\\1&1\\end{pmatrix}$이라 할 때, 집합 $X=\\{(x,y)\\mid A^2-B^2=(A+B)(A-B)\\}$가 나타내는 도형의 둘레의 길이는? [4.7점]",
    "choices": [
      "$11\\sqrt2$",
      "$12\\sqrt2$",
      "$13\\sqrt2$",
      "$14\\sqrt2$",
      "$15\\sqrt2$"
    ],
    "answer": "②",
    "solution": "행렬에서는 곱셈의 순서를 일반적으로 바꿀 수 없으므로 주어진 등식을 먼저 전개한다.\n$(A+B)(A-B)$\n$=A^2-AB+BA-B^2$이다.\n문제에서\n$A^2-B^2=(A+B)(A-B)$\n라고 했으므로\n$A^2-B^2=A^2-AB+BA-B^2$이다.\n양변에서 $A^2-B^2$를 없애면\n$AB=BA$이다.\n계산을 간단히 하기 위해\n$u=|x|$, $v=|y|$\n라고 하자.\n그러면\n$A=\\begin{pmatrix}2&2\\\\1&u\\end{pmatrix}$,\n$B=\\begin{pmatrix}v&2\\\\1&1\\end{pmatrix}$이다.\n행렬곱을 계산하면\n$AB=\\begin{pmatrix}2v+2&6\\\\v+u&2+u\\end{pmatrix}$이고,\n$BA=\\begin{pmatrix}2v+2&2v+2u\\\\3&2+u\\end{pmatrix}$이다.\n두 행렬이 같으므로 대응하는 성분이 같아야 한다.\n오른쪽 위 성분을 비교하면\n$6=2v+2u$\n$u+v=3$이다.\n왼쪽 아래 성분에서도\n$v+u=3$\n을 얻어 같은 조건이 나온다.\n따라서\n$|x|+|y|=3$이다.\n이 식이 나타내는 도형은 좌표축 위의 네 점\n$(3,0)$, $(0,3)$, $(-3,0)$, $(0,-3)$\n을 꼭짓점으로 하는 마름모이다.\n한 변의 길이는 예를 들어 $(3,0)$과 $(0,3)$ 사이의 거리이므로\n$\\sqrt{(3-0)^2+(0-3)^2}$\n$=\\sqrt{9+9}$\n$=3\\sqrt2$이다.\n따라서 둘레의 길이는\n$4\\cdot3\\sqrt2=12\\sqrt2$이다.\n따라서 정답은 ②이다.",
    "subUnitKey": "H22-C-09-MATRIX_OPERATION",
    "subUnit": "행렬의 연산",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 14,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["객관식","원의 방정식","접선","접점","중심","반지름","거리","도형"],
    "wide": false,
    "content": "원 $x^2+y^2+6x+4y+3=0$ 위의 점 $(-2,1)$에서의 접선이 원 $x^2+y^2-6x+8y+k=0$과 접할 때, 실수 $k$의 값은? [4.8점]",
    "choices": [
      "11",
      "12",
      "13",
      "14",
      "15"
    ],
    "answer": "⑤",
    "solution": "먼저 첫 번째 원의 중심과 점 $(-2,1)$에서의 접선을 구한다.\n원\n$x^2+y^2+6x+4y+3=0$\n을 완전제곱식으로 정리하면\n$(x+3)^2+(y+2)^2=10$이다.\n따라서 중심은\n$C_1=(-3,-2)$이다.\n접점을 $T=(-2,1)$이라 하자.\n중심 $C_1$과 접점 $T$를 잇는 반지름의 기울기는\n$\\dfrac{1-(-2)}{-2-(-3)}$\n$=\\dfrac31=3$이다.\n반지름과 접선은 접점에서 서로 수직이므로 접선의 기울기는\n$-\\dfrac13$이다.\n점 $T(-2,1)$을 지나고 기울기가 $-\\dfrac13$인 직선은\n$y-1=-\\dfrac13(x+2)$이다.\n양변에 $3$을 곱하면\n$3y-3=-x-2$\n$x+3y-1=0$이다.\n\n이제 두 번째 원을 살펴본다.\n$x^2+y^2-6x+8y+k=0$\n을 완전제곱식으로 정리하면\n$(x-3)^2+(y+4)^2=25-k$이다.\n따라서 중심은\n$C_2=(3,-4)$이고,\n반지름의 제곱은\n$r^2=25-k$이다.\n이 원이 직선\n$x+3y-1=0$\n에 접하므로 중심에서 직선까지의 거리가 반지름과 같다.\n중심 $(3,-4)$에서 이 직선까지의 거리는\n$\\dfrac{|3+3(-4)-1|}{\\sqrt{1^2+3^2}}$\n$=\\dfrac{|-10|}{\\sqrt{10}}$\n$=\\sqrt{10}$이다.\n따라서 반지름은 $\\sqrt{10}$이고\n$r^2=10$이다.\n그러므로\n$25-k=10$\n$k=15$이다.\n따라서 정답은 ⑤이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q14-solution.svg",
    "solutionImageAlt": "첫 번째 원의 접점 (−2,1)에서의 접선과 두 번째 원의 중심 (3,−4)를 나타낸 그림",
    "solutionImageCaption": "첫 번째 반지름의 방향으로 접선의 법선을 정하고 두 번째 원과의 접선 조건을 확인한다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
                    {
    "id": 15,
    "level": "상",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "직선의 방정식",
      "삼각형의 내심",
      "점과 직선 사이의 거리",
      "도형",
      "직선",
      "거리"
    ],
    "wide": false,
    "content": "세 직선 $x+\\sqrt3y-2=0$, $x-\\sqrt3y+10=0$, $y=2$로 둘러싸인 삼각형의 내심의 좌표를 $(a,b)$라 할 때, $a+b$의 값은? [4.9점]",
    "choices": [
      "$16-10\\sqrt3$",
      "$18-10\\sqrt3$",
      "$20-10\\sqrt3$",
      "$22-10\\sqrt3$",
      "$24-10\\sqrt3$"
    ],
    "answer": "①",
    "solution": "세 직선이 만드는 삼각형의 모양을 먼저 살펴본다.\n두 사선\n$x+\\sqrt3y-2=0$,\n$x-\\sqrt3y+10=0$\n의 교점을 구한다.\n두 식을 더하면\n$2x+8=0$\n$x=-4$이다.\n이를 첫 번째 식에 대입하면\n$-4+\\sqrt3y-2=0$\n$\\sqrt3y=6$\n$y=2\\sqrt3$이다.\n따라서 위쪽 꼭짓점은\n$V=(-4,2\\sqrt3)$이다.\n밑변은 직선 $y=2$ 위에 있고, 두 사선은 직선 $x=-4$을 기준으로 서로 대칭이다.\n따라서 삼각형의 대칭축은 $x=-4$이고 내심도 이 대칭축 위에 있다.\n그러므로\n$a=-4$이다.\n내심을\n$I(-4,b)$\n라 하자.\n내심은 삼각형 내부에 있으므로\n$2<b<2\\sqrt3$이다.\n직선 $y=2$까지의 거리는\n$b-2$이다.\n\n한편 직선\n$x+\\sqrt3y-2=0$\n까지의 거리는\n$\\dfrac{|-4+\\sqrt3b-2|}{\\sqrt{1^2+(\\sqrt3)^2}}$\n$=\\dfrac{|\\sqrt3b-6|}{2}$이다.\n$b<2\\sqrt3$이므로 $\\sqrt3b<6$이다.\n따라서\n$|\\sqrt3b-6|=6-\\sqrt3b$이고,\n이 거리는\n$\\dfrac{6-\\sqrt3b}{2}$이다.\n내심에서 세 변까지의 거리는 같으므로\n$\\dfrac{6-\\sqrt3b}{2}=b-2$이다.\n양변에 $2$를 곱하면\n$6-\\sqrt3b=2b-4$\n$10=(2+\\sqrt3)b$이다.\n따라서\n$b=\\dfrac{10}{2+\\sqrt3}$이다.\n분모를 유리화하면\n$b=\\dfrac{10(2-\\sqrt3)}{(2+\\sqrt3)(2-\\sqrt3)}$\n$=10(2-\\sqrt3)$\n$=20-10\\sqrt3$이다.\n그러므로\n$a+b=-4+(20-10\\sqrt3)$\n$=16-10\\sqrt3$이다.\n따라서 정답은 ①이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q15-solution.svg",
    "solutionImageAlt": "직선의 방정식 문항 15의 실제 점과 직선 관계를 표시한 해설 도형",
    "solutionImageCaption": "거리 · 세 직선으로 만든 삼각형 · y=2와 두 사선의 교점",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 16,
    "level": "하",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "단답형",
      "평면좌표",
      "두 점 사이의 거리"
    ],
    "wide": false,
    "content": "〈단답형1〉<br>좌표평면 위의 두 점 $(4,-2)$, $(-1,3)$ 사이의 거리가 $a\\sqrt b$일 때, 자연수 $a,b$에 대하여 $a+b$의 값을 구하시오. [4점]",
    "choices": [],
    "answer": "$7$",
    "solution": "두 점 사이의 거리는 $x$좌표의 차와 $y$좌표의 차를 이용하여 구한다.\n두 점은\n$(4,-2)$, $(-1,3)$이다.\n$x$좌표의 차는\n$-1-4=-5$이고,\n$y$좌표의 차는\n$3-(-2)=5$이다.\n따라서 두 점 사이의 거리는\n$\\sqrt{(-5)^2+5^2}$\n$=\\sqrt{25+25}$\n$=\\sqrt{50}$\n$=\\sqrt{25\\cdot2}$\n$=5\\sqrt2$이다.\n\n문제에서 이 거리를 $a\\sqrt b$라고 했으므로\n$a=5$, $b=2$이다.\n따라서\n$a+b=5+2=7$이다.\n그러므로 구하는 값은 $7$이다.",
    "subUnitKey": "H22-C2-01-COORDINATE_METRIC",
    "subUnit": "평면좌표와 거리",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 17,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "단답형",
      "집합",
      "부분집합",
      "소수"
    ],
    "wide": false,
    "content": "〈단답형2〉<br>전체집합 $U$는 $2$ 이상 $20$ 이하의 소수 전체의 집합이다. $U$의 공집합이 아닌 부분집합 $X$에 대하여 집합 $X$의 모든 원소의 합을 $S(X)$라 하자. 집합 $X$가 다음 조건을 만족할 때, $S(X)$의 최솟값을 구하시오.<div class=\"note-box\">(가) $3\\in X$이다.<br>(나) $S(X)$는 $5$보다 큰 소수이다.</div>[5점]",
    "choices": [],
    "answer": "$17$",
    "solution": "전체집합은 $2$ 이상 $20$ 이하의 소수 전체이므로\n$U=\\{2,3,5,7,11,13,17,19\\}$이다.\n조건 (가)에서 $3\\in X$이므로 집합 $X$에는 반드시 $3$이 들어간다.\n또 $S(X)$는 $5$보다 큰 소수이고, 그 값을 가장 작게 해야 한다.\n$5$보다 큰 소수를 작은 것부터 살펴보면\n$7,11,13,17,\\ldots$\n이다.\n\n먼저 $S(X)=7$이 되려면 $3$ 이외의 원소의 합이\n$7-3=4$\n이어야 한다.\n하지만 $U$에서 $3$을 제외한 가장 작은 원소는 $2$이고, 그다음 원소는 $5$이므로 서로 다른 원소의 합으로 $4$를 만들 수 없다.\n\n다음으로 $S(X)=11$이 되려면 나머지 원소의 합이\n$11-3=8$\n이어야 한다.\n$8$보다 작거나 같은 원소 $2,5,7$로 만들 수 있는 합을 보면\n$2$, $5$, $7$, $2+5=7$, $2+7=9$\n이므로 $8$은 만들 수 없다.\n$S(X)=13$이 되려면 나머지 원소의 합이\n$13-3=10$\n이어야 한다.\n$2,5,7$로 만들 수 있는 합 중 $10$은 없고,\n$2+7=9$, $5+7=12$이므로 역시 불가능하다.\n\n이제 $S(X)=17$을 확인한다.\n$17-3=14$이고\n$2+5+7=14$이므로\n$X=\\{2,3,5,7\\}$\n로 잡을 수 있다.\n실제로\n$S(X)=2+3+5+7=17$이고,\n$17$은 $5$보다 큰 소수이다.\n따라서 조건을 만족하는 $S(X)$의 최솟값은 $17$이다.\n그러므로 구하는 값은 $17$이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 18,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["단답형","원의 방정식","반지름","넓이","도형"],
    "wide": false,
    "content": "〈단답형3〉<br>좌표평면 위에 제$1$사분면의 점 $A$와 $y$축 위의 $O$가 아닌 점 $B$에 대하여 $\\overline{AB}=\\overline{AO}=2\\sqrt5$인 이등변삼각형 $OAB$가 있다. 점 $A$를 직선 $y=x$에 대하여 대칭이동한 점을 $C$라 하면 $C$는 직선 $y=2x$ 위의 점이다. 선분 $AB$가 두 직선 $y=x$, $y=2x$와 만나는 점을 각각 $D,E$라 할 때, 삼각형 $ODE$의 외접원의 넓이를 $k\\pi$라 하자. $36k$의 값을 구하시오. (단, $O$는 원점이다.) [6점]",
    "choices": [],
    "answer": "$128$",
    "solution": "점 $A$의 좌표부터 구한다.\n점 $A$가 제1사분면에 있으므로\n$A=(p,q)$, $p>0$, $q>0$\n라고 하자.\n점 $A$를 직선 $y=x$에 대하여 대칭이동하면 두 좌표가 서로 바뀌므로\n$C=(q,p)$이다.\n점 $C$가 직선 $y=2x$ 위에 있으므로\n$p=2q$이다.\n또\n$AO=2\\sqrt5$\n이므로\n$p^2+q^2=(2\\sqrt5)^2=20$이다.\n$p=2q$를 대입하면\n$(2q)^2+q^2=20$\n$5q^2=20$\n$q^2=4$이다.\n점 $A$가 제1사분면에 있으므로 $q=2$이고\n$p=4$이다.\n따라서\n$A=(4,2)$이다.\n\n이제 점 $B$를 구한다.\n점 $B$는 $y$축 위에 있으므로\n$B=(0,t)$\n라고 하자.\n$AB=2\\sqrt5$이므로\n$(0-4)^2+(t-2)^2=20$이다.\n$16+(t-2)^2=20$\n$(t-2)^2=4$이다.\n따라서\n$t=0$ 또는 $t=4$이다.\n그런데 $B$는 원점 $O$가 아닌 점이므로\n$B=(0,4)$이다.\n직선 $AB$의 기울기는\n$\\dfrac{4-2}{0-4}$\n$=-\\dfrac12$이고,\n점 $B(0,4)$를 지나므로\n$AB:y=-\\dfrac12x+4$이다.\n점 $D$는 직선 $AB$와 $y=x$의 교점이다.\n$x=-\\dfrac12x+4$\n$\\dfrac32x=4$\n$x=\\dfrac83$이다.\n따라서\n$D=\\left(\\dfrac83,\\dfrac83\\right)$이다.\n점 $E$는 직선 $AB$와 $y=2x$의 교점이다.\n$2x=-\\dfrac12x+4$\n$\\dfrac52x=4$\n$x=\\dfrac85$이다.\n따라서\n$E=\\left(\\dfrac85,\\dfrac{16}{5}\\right)$이다.\n\n이제 삼각형 $ODE$의 외접원을 구한다.\n원점 $O(0,0)$을 지나는 원의 방정식을\n$x^2+y^2+ux+vy=0$\n이라 하자.\n점 $D$를 대입하면\n$\\left(\\dfrac83\\right)^2+\\left(\\dfrac83\\right)^2+\\dfrac83u+\\dfrac83v=0$이다.\n정리하면\n$u+v=-\\dfrac{16}{3}$이다.\n점 $E$를 대입하면\n$\\left(\\dfrac85\\right)^2+\\left(\\dfrac{16}{5}\\right)^2+\\dfrac85u+\\dfrac{16}{5}v=0$이다.\n정리하면\n$u+2v=-8$이다.\n두 식을 빼면\n$v=-\\dfrac83$이고,\n따라서\n$u=-\\dfrac83$이다.\n외접원의 방정식은\n$x^2+y^2-\\dfrac83x-\\dfrac83y=0$이다.\n완전제곱식으로 정리하면\n$\\left(x-\\dfrac43\\right)^2+\\left(y-\\dfrac43\\right)^2=\\dfrac{32}{9}$이다.\n따라서 외접원의 반지름의 제곱은\n$k=\\dfrac{32}{9}$이다.\n그러므로\n$36k=36\\cdot\\dfrac{32}{9}$\n$=4\\cdot32$\n$=128$이다.\n그러므로 구하는 값은 $128$이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q18-solution.svg",
    "solutionImageAlt": "점 A, B와 선분 AB 위의 D, E, 그리고 삼각형 ODE의 외접원을 나타낸 그림",
    "solutionImageCaption": "대칭이동으로 A를 정하고 D,E를 구한 뒤 세 점을 지나는 원의 반지름을 찾는다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 19,
    "level": "상",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형",
      "집합",
      "이차방정식",
      "경우 나누기"
    ],
    "wide": false,
    "content": "〈서술형1〉<br>이차함수 $f(x)=x^2-7x+20$와 실수 $b,c$에 대하여 두 집합 $A,B$를 $A=\\{x\\mid f(x)-x-b=0\\}$, $B=\\{x\\mid f(x)+x-c=0\\}$이라 하자. 두 집합 $A,B$는 공집합이 아니고 $n(A\\cup B)=2$일 때, $bc$의 최댓값과 최솟값을 구하는 과정을 서술하시오. [10점]",
    "choices": [],
    "answer": "최댓값 $55$, 최솟값 $44$",
    "solution": "집합 $A$, $B$의 원소는 각각 이차방정식의 실근이다.\n\n먼저 집합 $A$를 살펴보자.\n$f(x)-x-b=0$에서\n$x^2-8x+20-b=0$이다.\n이 이차방정식의 판별식은\n$D_A=(-8)^2-4(20-b)$\n$=64-80+4b$\n$=4(b-4)$이다.\n집합 $A$가 공집합이 아니므로\n$D_A\\ge0$\n$b\\ge4$이다.\n$b=4$이면 중근 $4$를 가지므로\n$A=\\{4\\}$이다.\n$b>4$이면 $A$는 서로 다른 두 원소를 가지며,\n두 원소의 합은 근과 계수의 관계에 따라\n$8$이다.\n\n이제 집합 $B$를 살펴보자.\n$f(x)+x-c=0$에서\n$x^2-6x+20-c=0$이다.\n판별식은\n$D_B=(-6)^2-4(20-c)$\n$=36-80+4c$\n$=4(c-11)$이다.\n집합 $B$가 공집합이 아니므로\n$D_B\\ge0$\n$c\\ge11$이다.\n$c=11$이면 중근 $3$을 가지므로\n$B=\\{3\\}$이다.\n$c>11$이면 $B$는 서로 다른 두 원소를 가지며,\n두 원소의 합은\n$6$이다.\n\n이제 $n(A\\cup B)=2$가 되는 경우를 나누어 조사한다.\n\n(1) $A$, $B$가 모두 한 개의 원소를 가지는 경우\n$b=4$, $c=11$이고\n$A=\\{4\\}$,\n$B=\\{3\\}$이다.\n따라서\n$bc=4\\cdot11=44$이다.\n\n(2) $A$가 한 개, $B$가 두 개의 원소를 가지는 경우\n$A=\\{4\\}$이다.\n합집합의 원소가 두 개뿐이려면 $4$가 $B$의 원소여야 한다.\n$B$의 두 원소의 합은 $6$이므로\n$B=\\{2,4\\}$이다.\n두 근의 곱은\n$2\\cdot4=8$이고,\n방정식 $x^2-6x+20-c=0$에서 두 근의 곱은 $20-c$이다.\n따라서\n$20-c=8$\n$c=12$이다.\n그러므로\n$bc=4\\cdot12=48$이다.\n\n(3) $A$가 두 개, $B$가 한 개의 원소를 가지는 경우\n$B=\\{3\\}$이다.\n합집합의 원소가 두 개뿐이려면 $3$이 $A$의 원소여야 한다.\n$A$의 두 원소의 합은 $8$이므로\n$A=\\{3,5\\}$이다.\n두 근의 곱은\n$3\\cdot5=15$이고,\n방정식 $x^2-8x+20-b=0$에서 두 근의 곱은 $20-b$이다.\n따라서\n$20-b=15$\n$b=5$이다.\n그러므로\n$bc=5\\cdot11=55$이다.\n\n(4) $A$, $B$가 모두 두 개의 원소를 가지는 경우\n합집합의 원소가 두 개라면 두 집합이 같아야 한다.\n그런데 $A$의 두 원소의 합은 $8$이고,\n$B$의 두 원소의 합은 $6$이므로\n$A=B$\n가 될 수 없다.\n따라서 이 경우는 불가능하다.\n\n가능한 $bc$의 값은\n$44,\\ 48,\\ 55$이다.\n그러므로\n$bc$의 최댓값은 $55$,\n최솟값은 $44$이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 20,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["서술형","원의 방정식","접선","좌표축 접원","접점","중심","반지름","넓이","거리","도형"],
    "wide": false,
    "content": "〈서술형2〉<br>좌표평면 위에 서로 다른 원 $C_1,C_2$가 제$1$사분면에서 직선 $l:5x+12y-6=0$과 $x$축, $y$축에 동시에 접한다. 원 $C_1,C_2$의 중심을 각각 $M_1,M_2$라 하고 원 $C_1,C_2$와 직선 $l$과의 접점을 각각 $P_1,P_2$라 할 때, 사각형 $M_1P_1M_2P_2$의 넓이를 구하는 과정을 서술하시오. (단, $C_1$의 반지름보다 $C_2$의 반지름이 더 크다.) [10점]",
    "choices": [],
    "answer": "$\\dfrac{119}{200}$",
    "solution": "두 원은 제1사분면에서 $x$축과 $y$축에 동시에 접한다.\n반지름이 $r$인 이런 원의 중심은 두 좌표축에서 모두 거리가 $r$이므로\n$M=(r,r)$\n로 나타낼 수 있다.\n또 이 원이 직선\n$l:5x+12y-6=0$\n에도 접하므로 중심에서 직선까지의 거리가 반지름 $r$과 같다.\n따라서\n$\\dfrac{|5r+12r-6|}{\\sqrt{5^2+12^2}}=r$이다.\n분모를 계산하면\n$\\dfrac{|17r-6|}{13}=r$이고,\n$|17r-6|=13r$이다.\n절댓값을 두 경우로 나눈다.\n\n첫째,\n$17r-6=13r$\n$4r=6$\n$r=\\dfrac32$이다.\n\n둘째,\n$17r-6=-13r$\n$30r=6$\n$r=\\dfrac15$이다.\n\n문제에서 $C_1$의 반지름이 더 작다고 했으므로\n$r_1=\\dfrac15$, $r_2=\\dfrac32$이다.\n따라서 중심은\n$M_1=\\left(\\dfrac15,\\dfrac15\\right)$,\n$M_2=\\left(\\dfrac32,\\dfrac32\\right)$이다.\n접점에서는 반지름이 접선에 수직이므로\n$M_1P_1\\perp l$,\n$M_2P_2\\perp l$이다.\n따라서\n$M_1P_1\\parallel M_2P_2$이고\n$M_1P_1=r_1=\\dfrac15$,\n$M_2P_2=r_2=\\dfrac32$이다.\n또 $P_1$, $P_2$는 모두 직선 $l$ 위에 있으므로\n$P_1P_2$는 두 평행한 선분 $M_1P_1$, $M_2P_2$에 수직이다.\n따라서 사각형 $M_1P_1M_2P_2$는 평행한 두 변의 길이가\n$\\dfrac15$, $\\dfrac32$\n인 사다리꼴이고, 높이는 $P_1P_2$이다.\n\n이제 $P_1P_2$를 구한다.\n두 중심 사이의 거리는\n$M_1M_2=\\sqrt{\\left(\\dfrac32-\\dfrac15\\right)^2+\\left(\\dfrac32-\\dfrac15\\right)^2}$이다.\n$\\dfrac32-\\dfrac15=\\dfrac{13}{10}$이므로\n$M_1M_2=\\sqrt{2\\left(\\dfrac{13}{10}\\right)^2}$\n$=\\dfrac{13\\sqrt2}{10}$이다.\n앞에서 절댓값을 나눈 두 경우를 보면\n$r_1=\\dfrac15$일 때는 $17r_1-6<0$이고,\n$r_2=\\dfrac32$일 때는 $17r_2-6>0$이다.\n따라서 두 중심 $M_1$, $M_2$는 직선 $l$의 서로 반대쪽에 있다.\n점 $M_1$을 지나고 직선 $l$과 평행한 직선을 그어 선분 $M_2P_2$와 만나는 점을 $N$이라 하자.\n그러면 $M_1P_1P_2N$은 직사각형이므로\n$M_1N=P_1P_2$이고\n$NP_2=M_1P_1=\\dfrac15$이다.\n또 $M_2$와 $N$은 $P_2$를 사이에 두고 있으므로\n$NM_2=NP_2+P_2M_2$\n$=\\dfrac15+\\dfrac32$\n$=\\dfrac{17}{10}$이다.\n삼각형 $M_1NM_2$는 $N$에서 직각이므로 피타고라스 정리를 적용하면\n$M_1M_2^2=M_1N^2+NM_2^2$이다.\n따라서\n$P_1P_2^2=\\left(\\dfrac{13\\sqrt2}{10}\\right)^2-\\left(\\dfrac{17}{10}\\right)^2$\n$=\\dfrac{338}{100}-\\dfrac{289}{100}$\n$=\\dfrac{49}{100}$이다.\n그러므로\n$P_1P_2=\\dfrac7{10}$이다.\n\n이제 사다리꼴의 넓이를 구하면\n$\\dfrac12\\left(M_1P_1+M_2P_2\\right)\\cdot P_1P_2$\n$=\\dfrac12\\left(\\dfrac15+\\dfrac32\\right)\\cdot\\dfrac7{10}$\n$=\\dfrac12\\cdot\\dfrac{17}{10}\\cdot\\dfrac7{10}$\n$=\\dfrac{119}{200}$이다.\n따라서 사각형 $M_1P_1M_2P_2$의 넓이는 $\\dfrac{119}{200}$이다.",
    "solutionImage": "assets/images/25_매산고_2학기_중간_고1_기출/q20-solution.svg",
    "solutionImageAlt": "두 좌표축과 직선 l에 동시에 접하는 두 원, 중심 M₁,M₂와 접점 P₁,P₂를 나타낸 그림",
    "solutionImageCaption": "중심 (r,r), 직선까지의 거리 조건으로 두 반지름과 접점을 구한 뒤 사각형 넓이를 계산한다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  }
];
