window.examTitle = "25_순천고_2학기_중간_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "원소",
      "약수"
    ],
    "wide": false,
    "content": "집합 $A$를 $15$의 약수 전체의 집합이라 할 때, 집합 $A$의 원소의 개수는? [3.2점]",
    "choices": [
      "$2$",
      "$3$",
      "$4$",
      "$5$",
      "$6$"
    ],
    "answer": "③",
    "solution": "집합 $A$는 $15$의 양의 약수 전체의 집합이다.\n\n$15=3\\times5$이므로 양의 약수는\n$1,3,5,15$이다.\n\n따라서\n$A=\\{1,3,5,15\\}$이고\n\n$n(A)=4$이다.\n\n따라서 정답은 ③이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 2,
    "level": "하",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "부분집합",
      "공집합"
    ],
    "wide": false,
    "content": "집합 $\\{a,b,c\\}$의 부분집합이 아닌 것은? [3.2점]",
    "choices": [
      "$\\varnothing$",
      "$\\{\\varnothing\\}$",
      "$\\{a\\}$",
      "$\\{b,c\\}$",
      "$\\{a,b,c\\}$"
    ],
    "answer": "②",
    "solution": "집합 $A=\\{a,b,c\\}$의 부분집합인지 하나씩 확인하자.\n\n부분집합은 집합의 모든 원소가 $A$에도 들어 있어야 한다.\n\n먼저 공집합 $\\varnothing$은 모든 집합의 부분집합이므로\n\n$\\varnothing\\subseteq A$이다.\n\n또 $a,b,c$는 모두 $A$의 원소이므로\n\n$\\{a\\}$,\n$\\{b,c\\}$,\n$\\{a,b,c\\}$\n\n은 모두 $A$의 부분집합이다.\n\n이제 $\\{\\varnothing\\}$을 보자.\n\n집합 $\\{\\varnothing\\}$의 유일한 원소는 $\\varnothing$이다.\n그런데 $A$의 원소는 $a,b,c$이므로\n\n$\\varnothing\\notin A$이다.\n\n따라서\n\n$\\{\\varnothing\\}\\nsubseteq A$이다.\n\n따라서 정답은 ②이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 3,
    "level": "하",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "평면좌표",
      "평행사변형",
      "좌표",
      "도형"
    ],
    "wide": false,
    "content": "세 점 $A(1,2)$, $B(-1,-1)$, $D(3,0)$과 제$4$사분면 위의 점 $C(a,b)$를 꼭짓점으로 하는 사각형 $ABCD$가 평행사변형일 때, $ab$의 값은? [3.3점]",
    "choices": [
      "$-3$",
      "$-1$",
      "$0$",
      "$1$",
      "$3$"
    ],
    "answer": "①",
    "solution": "평행사변형 $ABCD$에서는 두 대각선의 중점이 같다. 대각선 $BD$의 중점을 $M$이라 하면\n$x_M=\\dfrac{-1+3}{2}=1$, $y_M=-\\dfrac12$이다.\n\n$M$은 대각선 $AC$의 중점이기도 하므로 x좌표와 y좌표를 각각 비교한다.\n$\\dfrac{1+x_C}{2}=1$에서 $x_C=1$이고,\n$\\dfrac{2+y_C}{2}=-\\dfrac12$에서 $y_C=-3$이다.\n\n따라서 $C=(1,-3)$이고, $ab=1\\times(-3)=-3$이므로 정답은 ①이다.",

    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q03-solution.svg",

    "solutionImageAlt": "평면좌표 문항 3의 핵심 관계를 표시한 해설 도형",


    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-01-COORDINATE_METRIC",
    "subUnit": "평면좌표와 거리",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 4,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "교집합",
      "차집합"
    ],
    "wide": false,
    "content": "두 집합 $A=\\{2,6,a-3\\}$, $B=\\{1,4,a+1\\}$에 대하여 $A\\cap B=\\{4\\}$일 때, $B-A$의 모든 원소의 합은? [3.3점]",
    "choices": [
      "$1$",
      "$3$",
      "$5$",
      "$7$",
      "$9$"
    ],
    "answer": "⑤",
    "solution": "$A\\cap B=\\{4\\}$이므로 $4$는 집합 $A$와 $B$에 모두 들어 있어야 한다.\n\n집합\n$A=\\{2,6,a-3\\}$에서 $2$와 $6$은 $4$가 아니므로\n\n$a-3=4$이다.\n\n따라서\n$a=7$이다.\n\n이를 두 집합에 대입하면\n\n$A=\\{2,6,4\\}=\\{2,4,6\\}$,\n\n$B=\\{1,4,8\\}$이다.\n\n실제로 두 집합의 공통 원소는 $4$ 하나뿐이므로 조건을 만족한다.\n\n이제 $B-A$는 $B$의 원소 중 $A$에 들어 있지 않은 원소의 집합이므로\n\n$B-A=\\{1,8\\}$이다.\n\n따라서 모든 원소의 합은\n\n$1+8=9$이다.\n\n따라서 정답은 ⑤이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 5,
    "level": "하",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "부분집합",
      "진부분집합",
      "약수"
    ],
    "wide": false,
    "content": "집합 $A$를 $8$의 약수 전체의 집합이라 할 때, 집합 $A$의 진부분집합의 개수는? [3.5점]",
    "choices": [
      "$1$",
      "$3$",
      "$7$",
      "$15$",
      "$31$"
    ],
    "answer": "④",
    "solution": "$8$의 양의 약수는\n\n$1,2,4,8$이다.\n\n따라서\n$A=\\{1,2,4,8\\}$이고, 집합 $A$의 원소는 $4$개이다.\n\n원소가 $4$개인 집합의 부분집합의 개수는\n\n$2^4=16$개이다.\n\n진부분집합은 자기 자신과 같지 않은 부분집합이므로, 이 $16$개에서 $A$ 자체 한 개를 제외한다.\n\n따라서 진부분집합의 개수는\n\n$16-1=15$이다.\n\n따라서 정답은 ④이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
                    {
    "id": 6,
    "level": "하",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "직선의 방정식",
      "평행선",
      "거리",
      "도형",
      "직선",
      "평행"
    ],
    "wide": false,
    "content": "평행한 두 직선 $x+y+3=0$, $x+y+k=0$ 사이의 거리가 $4\\sqrt2$가 되도록 하는 모든 실수 $k$의 값의 합은? [3.5점]",
    "choices": [
      "$6$",
      "$7$",
      "$8$",
      "$9$",
      "$10$"
    ],
    "answer": "①",
    "solution": "두 직선은 $x$와 $y$의 계수 비가 같으므로 평행하다. 두 평행선\n$x+y+3=0$, $x+y+k=0$ 사이의 거리는\n$\\dfrac{|k-3|}{\\sqrt{1^2+1^2}}=\\dfrac{|k-3|}{\\sqrt2}$이다.\n\n거리가 $4\\sqrt2$이므로\n$\\dfrac{|k-3|}{\\sqrt2}=4\\sqrt2$에서 $|k-3|=8$이다.\n따라서 $k=11$ 또는 $k=-5$이고, 두 값의 합은 $6$이다.\n\n그러므로 정답은 ①이다.",
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q06-solution.svg",
    "solutionImageAlt": "직선의 방정식 문항 6의 실제 점과 직선 관계를 표시한 해설 도형",
    "solutionImageCaption": "평행 관계 · 두 평행선 사이 거리=4√2 · k=11 또는 −5, 합=6",
    "solutionImageSize": "full"
  },
  {
    "id": 7,
    "level": "하",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["객관식","원의 방정식","교점","직선과 원","위치 관계","중심","반지름","거리","도형"],
    "wide": false,
    "content": "원 $(x-1)^2+(y+2)^2=r^2$과 직선 $5x-12y+1=0$이 서로 다른 두 점에서 만나도록 하는 자연수 $r$의 최솟값은? [3.6점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "③",
    "solution": "원\n$(x-1)^2+(y+2)^2=r^2$\n의 중심은 $(1,-2)$이고 반지름은 $r$이다.\n\n원과 직선이 서로 다른 두 점에서 만나려면\n중심에서 직선까지의 거리가 반지름보다 작아야 한다.\n\n중심 $(1,-2)$에서 직선\n$5x-12y+1=0$\n까지의 거리는\n\n$\\dfrac{|5\\cdot1-12(-2)+1|}{\\sqrt{5^2+(-12)^2}}$\n\n$=\\dfrac{|5+24+1|}{13}$\n\n$=\\dfrac{30}{13}$이다.\n\n따라서 서로 다른 두 점에서 만나려면\n\n$r>\\dfrac{30}{13}$\n\n이어야 한다.\n\n$r=\\dfrac{30}{13}$이면 직선이 원에 접하고,\n$r<\\dfrac{30}{13}$이면 만나지 않으므로 제외한다.\n\n$\\dfrac{30}{13}$보다 큰 자연수 중 가장 작은 수는 $3$이다.\n\n따라서 정답은 ③이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q07-solution.svg",
    "solutionImageAlt": "중심 (1,−2)의 원과 직선 5x−12y+1=0, 두 교점 조건을 나타낸 그림",
    "solutionImageCaption": "중심에서 직선까지의 거리 30/13보다 큰 자연수 반지름부터 두 교점이 생긴다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-INTERSECTION",
    "subUnit": "원과 직선·원의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 8,
    "level": "중",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "도형의 이동",
      "평행이동",
      "수직",
      "직선"
    ],
    "wide": false,
    "content": "직선 $y=ax+b$를 $x$축의 방향으로 $1$만큼, $y$축의 방향으로 $-2$만큼 평행이동하면 직선 $x-2y-2=0$과 $x$축에서 수직으로 만난다. $a+b$의 값은? [3.6점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "②",
    "solution": "직선\n$x-2y-2=0$\n을 $y$에 대하여 정리하면\n\n$y=\\dfrac12x-1$이다.\n\n따라서 이 직선의 기울기는 $\\dfrac12$이다.\n\n평행이동한 직선과 이 직선이 서로 수직이므로, 평행이동 전후에 변하지 않는 기울기 $a$는\n\n$a\\cdot\\dfrac12=-1$\n\n을 만족한다.\n\n따라서\n$a=-2$이다.\n\n두 직선은 $x$축 위에서 만난다.\n직선 $x-2y-2=0$에 $y=0$을 대입하면\n\n$x-2=0$\n\n이므로 교점은\n$(2,0)$이다.\n\n이제 원래 직선\n$y=ax+b$\n를 $x$축의 방향으로 $1$만큼, $y$축의 방향으로 $-2$만큼 평행이동한다.\n\n평행이동한 직선은\n\n$y+2=a(x-1)+b$이다.\n\n$a=-2$를 대입하면\n\n$y+2=-2(x-1)+b$\n\n$y+2=-2x+2+b$\n\n$y=-2x+b$이다.\n\n이 직선이 $(2,0)$을 지나므로\n\n$0=-2\\cdot2+b$\n\n$0=-4+b$\n\n$b=4$이다.\n\n따라서\n\n$a+b=-2+4=2$이다.\n\n따라서 정답은 ②이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q08-solution.svg",
    "solutionImageAlt": "도형의 이동 문항 8의 핵심 관계를 표시한 해설 도형",
    "solutionImageSize": "full"
  },
  {
    "id": 9,
    "level": "중",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["객관식","원의 방정식","접선","좌표축 접원","중심","반지름","도형"],
    "wide": false,
    "content": "점 $(2,-1)$을 지나고 $x$축과 $y$축에 동시에 접하는 두 원의 반지름의 합은? [3.9점]",
    "choices": [
      "$4$",
      "$5$",
      "$6$",
      "$7$",
      "$8$"
    ],
    "answer": "③",
    "solution": "두 좌표축에 동시에 접하는 원의 반지름을 $r$이라 하자.\n\n반지름은 양수이므로\n\n$r>0$이다.\n\n두 좌표축까지의 거리가 모두 $r$이어야 하므로 원의 중심은\n\n$(r,r)$,\n$(r,-r)$,\n$(-r,r)$,\n$(-r,-r)$\n\n중 하나이다.\n\n또 원이 점 $(2,-1)$을 지나므로 중심에서 이 점까지의 거리가 $r$이어야 한다.\n\n첫째, 중심이 $(r,r)$인 경우\n\n$(2-r)^2+(-1-r)^2=r^2$\n\n$r^2-2r+5=0$이다.\n\n판별식이\n$(-2)^2-4\\cdot1\\cdot5=-16<0$\n이므로 가능한 $r$이 없다.\n\n둘째, 중심이 $(r,-r)$인 경우\n\n$(2-r)^2+(-1+r)^2=r^2$\n\n$r^2-6r+5=0$\n\n$(r-1)(r-5)=0$이다.\n\n따라서\n$r=1$ 또는 $r=5$이다.\n\n셋째, 중심이 $(-r,r)$인 경우\n\n$(2+r)^2+(-1-r)^2=r^2$\n\n$r^2+6r+5=0$\n\n$(r+1)(r+5)=0$이다.\n\n두 해가 모두 음수이므로 $r>0$과 맞지 않는다.\n\n넷째, 중심이 $(-r,-r)$인 경우\n\n$(2+r)^2+(-1+r)^2=r^2$\n\n$r^2+2r+5=0$이다.\n\n판별식이\n$2^2-4\\cdot1\\cdot5=-16<0$\n이므로 가능한 $r$이 없다.\n\n따라서 두 원의 반지름은 $1$, $5$이고,\n그 합은\n\n$1+5=6$이다.\n\n따라서 정답은 ③이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q09-solution.svg",
    "solutionImageAlt": "점 (2,−1)을 지나고 두 좌표축에 접하는 두 원을 나타낸 그림",
    "solutionImageCaption": "가능한 중심의 사분면을 점검해 반지름 1과 5를 얻는다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 10,
    "level": "중",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["객관식","원의 방정식","교점","직선과 원","위치 관계","중심","반지름","거리","도형"],
    "wide": false,
    "content": "원 $(x-1)^2+y^2=3$과 직선 $y=x+1$이 만나는 서로 다른 두 점 사이의 거리는? [3.9점]",
    "choices": [
      "$1$",
      "$\\sqrt2$",
      "$\\sqrt3$",
      "$2$",
      "$\\sqrt5$"
    ],
    "answer": "④",
    "solution": "원의 중심을 $C$, 직선과 원의 두 교점을 $P,Q$라 하자.\n\n원\n$(x-1)^2+y^2=3$\n의 중심은\n\n$C=(1,0)$\n\n이고 반지름은\n\n$r=\\sqrt3$이다.\n\n직선\n$y=x+1$\n을 일반형으로 나타내면\n\n$x-y+1=0$이다.\n\n중심 $C=(1,0)$에서 이 직선까지의 거리는\n\n$\\dfrac{|1-0+1|}{\\sqrt{1^2+(-1)^2}}$\n\n$=\\dfrac{2}{\\sqrt2}$\n\n$=\\sqrt2$이다.\n\n중심 $C$에서 현 $PQ$에 내린 수선의 발을 $M$이라 하자.\n원의 중심에서 현에 내린 수선은 현을 이등분하므로\n\n$PM=QM$이다.\n\n직각삼각형 $CMP$에서\n\n$CP^2=CM^2+PM^2$이므로\n\n$PM^2=3-2=1$이다.\n\n따라서\n\n$PM=1$이고,\n\n$PQ=2PM=2$이다.\n\n따라서 정답은 ④이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q10-solution.svg",
    "solutionImageAlt": "원 (x−1)²+y²=3과 직선 y=x+1, 현의 중선과 길이를 나타낸 그림",
    "solutionImageCaption": "중심에서 직선까지의 거리와 반지름으로 현의 길이를 계산한다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-INTERSECTION",
    "subUnit": "원과 직선·원의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 11,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "벤다이어그램",
      "도형"
    ],
    "wide": false,
    "content": "다음 벤다이어그램의 색칠한 부분을 나타내는 집합과 항상 같은 집합은? [3.9점]",
    "image": "assets/images/25_순천고_2학기_중간_고1_기출/q11.png",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q11-solution.svg",
    "solutionImageAlt": "A에서 B와 C의 공통 부분을 제외한 영역을 표시한 Venn diagram",
    "solutionImageCaption": "A−(B∩C) = (A−B)∪(A−C)",
    "solutionImageSize": "full",
    "imageSize": "large",
    "choices": [
      "$A\\cap(B\\cup C)$",
      "$A\\cup(B\\cap C)$",
      "$A\\cup(B-C)$",
      "$(A\\cup B)-(A\\cap C)$",
      "$(A-B)\\cup(A-C)$"
    ],
    "answer": "⑤",
    "solution": "색칠한 부분을 먼저 집합식으로 나타내자.\n\n그림에서는 집합 $A$의 영역 중에서 $B$와 $C$에 동시에 속하는 부분만 색칠되어 있지 않다.\n\n따라서 색칠한 부분은\n\n$A-(B\\cap C)$이다.\n\n이를 여집합을 이용해 바꾸면\n\n$A-(B\\cap C)$\n\n$=A\\cap(B\\cap C)^c$\n\n$=A\\cap(B^c\\cup C^c)$이다.\n\n분배법칙을 적용하면\n\n$=(A\\cap B^c)\\cup(A\\cap C^c)$\n\n$=(A-B)\\cup(A-C)$이다.\n\n따라서 보기 ⑤와 같다.\n\n따라서 정답은 ⑤이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
                    {
    "id": 12,
    "level": "상",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "직선의 방정식",
      "점과 직선 사이의 거리",
      "최댓값",
      "넓이",
      "도형",
      "직선",
      "거리",
      "절편"
    ],
    "wide": false,
    "content": "원점 $O$와 직선 $(k+1)x+(k-1)y-k-3=0$ 사이의 거리가 최대인 직선을 $l$이라 하자. 직선 $l$이 $x$축, $y$축과 만나는 점이 각각 $A$, $B$일 때, 삼각형 $AOB$의 넓이는? [4.2점]",
    "choices": [
      "$6$",
      "$\\dfrac{25}{4}$",
      "$\\dfrac{13}{2}$",
      "$\\dfrac{27}{4}$",
      "$\\dfrac{14}{2}$"
    ],
    "answer": "②",
    "solution": "원점 $O$와 직선\n$(k+1)x+(k-1)y-k-3=0$\n사이의 거리를 $D$라 하자.\n\n점과 직선 사이의 거리 공식에 따라\n\n$D=\\dfrac{|k+3|}{\\sqrt{(k+1)^2+(k-1)^2}}$이다.\n\n거리의 최댓값을 구하기 위해 양변을 제곱하면\n\n$D^2=\\dfrac{(k+3)^2}{2(k^2+1)}$이다.\n\n이제 분자의 크기를 비교한다.\n\n$10(k^2+1)-(k+3)^2$\n\n$=10k^2+10-(k^2+6k+9)$\n\n$=9k^2-6k+1$\n\n$=(3k-1)^2\\ge0$이다.\n\n따라서\n\n$(k+3)^2\\le10(k^2+1)$이고,\n\n$D^2\\le\\dfrac{10(k^2+1)}{2(k^2+1)}=5$이다.\n\n등호가 성립하려면\n\n$(3k-1)^2=0$\n\n이어야 하므로\n\n$k=\\dfrac13$이다.\n\n따라서 거리가 최대일 때의 직선 $l$은\n\n$\\dfrac43x-\\dfrac23y-\\dfrac{10}{3}=0$이다.\n\n양변에 $3$을 곱하고 $2$로 나누면\n\n$2x-y-5=0$이다.\n\n이 직선의 $x$절편은\n\n$A=\\left(\\dfrac52,0\\right)$,\n\n$y$절편은\n\n$B=(0,-5)$이다.\n\n따라서 삼각형 $AOB$의 넓이는\n\n$\\dfrac12\\cdot\\left|\\dfrac52\\right|\\cdot|-5|$\n\n$=\\dfrac{25}{4}$이다.\n\n따라서 정답은 ②이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q12-solution.svg",
    "solutionImageAlt": "직선의 방정식 문항 12의 실제 점과 직선 관계를 표시한 해설 도형",
    "solutionImageCaption": "교점 · 절편 · 거리 · 최대 조건 k=1/3 · A=(5/2,0), B=(0,−5)",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 13,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "차집합",
      "집합의 연산"
    ],
    "wide": false,
    "content": "전체집합 $U$의 세 부분집합 $A$, $B$, $C$에 대하여 보기에서 항상 옳은 것만을 있는 대로 고른 것은? [4.2점]<br><br>ㄱ. $A-B=A\\cap B^c$<br>ㄴ. $(A-B)\\cap(A-C)=A-(B\\cap C)$<br>ㄷ. $(A\\cap B)-(A\\cap C)=A\\cap B\\cap C^c$",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "③",
   "solution": "차집합은\n\n$A-B=A\\cap B^c$\n\n로 나타낼 수 있다.\n이 사실을 이용해 ㄱ, ㄴ, ㄷ을 하나씩 확인하자.\n\nㄱ.\n\n$A-B=A\\cap B^c$\n\n는 차집합의 정의이므로 항상 참이다.\n\nㄴ.\n\n왼쪽 식을 정리하면\n\n$(A-B)\\cap(A-C)$\n\n$=(A\\cap B^c)\\cap(A\\cap C^c)$\n\n$=A\\cap B^c\\cap C^c$\n\n$=A\\cap(B\\cup C)^c$\n\n$=A-(B\\cup C)$이다.\n\n그런데 오른쪽은\n\n$A-(B\\cap C)$이다.\n\n두 식은 일반적으로 같지 않다.\n예를 들어\n\n$A=\\{1\\}$, $B=\\{1\\}$, $C=\\varnothing$\n\n이라고 하면 왼쪽은 $\\varnothing$이고,\n오른쪽은 $\\{1\\}$이다.\n\n따라서 ㄴ은 항상 참이 아니다.\n\nㄷ.\n\n$(A\\cap B)-(A\\cap C)$\n\n은 $A\\cap B$에 속하면서 $A\\cap C$에는 속하지 않는 원소의 집합이다.\n\n이 원소는 $A$와 $B$에는 속하고 $C$에는 속하지 않아야 하므로\n\n$(A\\cap B)-(A\\cap C)=A\\cap B\\cap C^c$이다.\n\n따라서 ㄷ은 항상 참이다.\n\n그러므로 항상 옳은 것은 ㄱ, ㄷ이다.\n\n따라서 정답은 ③이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q13-solution.svg",
    "solutionImageAlt": "세 집합의 차집합과 교집합을 영역으로 비교한 해설 도식",
    "solutionImageCaption": "A−B와 교집합의 여집합을 영역으로 읽어 등식의 성립 여부를 확인",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 14,
    "level": "상",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "배수",
      "부분집합",
      "자연수"
    ],
    "wide": false,
    "content": "자연수 $n$의 양의 배수를 원소로 하는 집합을 $A_n$이라 하자. $A_n\\subseteq(A_2\\cap A_5)$, $(A_{20}\\cup A_{40})\\subseteq A_n$을 만족시키는 모든 자연수 $n$의 값의 합은? [4.2점]",
    "choices": [
      "$20$",
      "$30$",
      "$40$",
      "$50$",
      "$60$"
    ],
    "answer": "②",
    "solution": "$A_n$은 자연수 $n$의 양의 배수 전체의 집합이다.\n\n먼저\n\n$A_2\\cap A_5$\n\n는 $2$와 $5$의 공배수, 즉 $10$의 배수 전체의 집합이므로\n\n$A_2\\cap A_5=A_{10}$이다.\n\n조건\n$A_n\\subseteq A_{10}$\n은 $n$의 모든 배수가 $10$의 배수라는 뜻이다.\n\n따라서 $n$은 $10$의 배수여야 한다.\n\n즉, $n$은 $10$의 배수이다.\n\n또 $40$의 배수는 모두 $20$의 배수이므로\n\n$A_{40}\\subseteq A_{20}$이고,\n\n$A_{20}\\cup A_{40}=A_{20}$이다.\n\n따라서 두 번째 조건은\n\n$A_{20}\\subseteq A_n$이다.\n\n이는 $20$의 모든 배수가 $n$의 배수라는 뜻이므로\n\n$n$은 $20$의 약수이다.\n\n결국 $n$은\n$10$의 배수이면서 $20$의 약수여야 한다.\n\n가능한 자연수 $n$은\n\n$10,20$이다.\n\n따라서 모든 $n$의 값의 합은\n\n$10+20=30$이다.\n\n따라서 정답은 ②이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 15,
    "level": "중",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "도형의 이동",
      "원의 평행이동",
      "접선",
      "최솟값"
    ],
    "wide": false,
    "content": "원 $x^2+y^2-6x+4y+12=0$을 $x$축의 방향으로 $a$만큼, $y$축의 방향으로 $b$만큼 평행이동한 원이 $x$축과 직선 $y=x$에 동시에 접하도록 하는 두 실수 $a$, $b$에 대하여 $a+b$의 최솟값을 고르면? [4.5점]",
    "choices": [
      "$-3-\\sqrt2$",
      "$-3+\\sqrt2$",
      "$1-\\sqrt2$",
      "$1+\\sqrt2$",
      "$3+\\sqrt2$"
    ],
    "answer": "①",
    "solution": "먼저 원의 중심과 반지름을 구한다.\n\n$x^2+y^2-6x+4y+12=0$\n\n에서 완전제곱식을 만들면\n\n$(x-3)^2+(y+2)^2=1$이다.\n\n따라서 원의 중심은\n$(3,-2)$이고 반지름은 $1$이다.\n\n이 원을 $x$축의 방향으로 $a$만큼, $y$축의 방향으로 $b$만큼 평행이동하면 중심은\n\n$(3+a,-2+b)$\n\n가 된다.\n\n이동한 원이 $x$축에 접하므로 중심에서 $x$축까지의 거리가 반지름 $1$과 같다.\n\n따라서\n\n$|-2+b|=1$이다.\n\n그러므로\n\n$b=1$ 또는 $b=3$이다.\n\n또 이동한 원이 직선 $y=x$에 접하므로 중심에서 직선\n$x-y=0$\n까지의 거리가 $1$이다.\n\n따라서\n\n$\\dfrac{|(3+a)-(-2+b)|}{\\sqrt{1^2+(-1)^2}}=1$\n\n$\\dfrac{|a-b+5|}{\\sqrt2}=1$\n\n$|a-b+5|=\\sqrt2$이다.\n\n따라서\n\n$a-b+5=\\sqrt2$\n\n또는\n\n$a-b+5=-\\sqrt2$이므로\n\n$a=b-5+\\sqrt2$\n\n또는\n\n$a=b-5-\\sqrt2$이다.\n\n이제 $a+b$를 비교한다.\n\n$b=1$이면\n\n$a+b=-3+\\sqrt2$\n\n또는\n\n$a+b=-3-\\sqrt2$이다.\n\n$b=3$이면\n\n$a+b=1+\\sqrt2$\n\n또는\n\n$a+b=1-\\sqrt2$이다.\n\n따라서 가장 작은 값은\n\n$-3-\\sqrt2$이다.\n\n따라서 정답은 ①이다.",

    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q15-solution.svg",

    "solutionImageAlt": "도형의 이동 문항 15의 핵심 관계를 표시한 해설 도형",


    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 16,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["객관식","원의 방정식","교점","두 원","공통현","중심","반지름","거리","도형"],
    "wide": false,
    "content": "두 점 $O(0,0)$, $A(6,0)$과 원 $C_1:x^2+y^2-6x-8y+16=0$ 위의 점 $P(a,b)$에 대하여 직각삼각형 $APO$의 외접원을 $C_2$라 하자. 두 원 $C_1$과 $C_2$의 두 교점 $P$, $Q$의 거리는? (단, $\\angle APO=90^\\circ$) [4.5점]",
    "choices": [
      "$1$",
      "$\\sqrt3$",
      "$\\sqrt5$",
      "$2\\sqrt3$",
      "$2\\sqrt5$"
    ],
    "answer": "⑤",
    "solution": "먼저 두 원 $C_1$, $C_2$의 중심과 반지름을 구한다.\n\n원 $C_1$의 방정식은\n\n$x^2+y^2-6x-8y+16=0$이다.\n\n완전제곱식을 만들면\n\n$(x-3)^2+(y-4)^2=9$이다.\n\n따라서 $C_1$의 중심은\n\n$(3,4)$\n\n이고 반지름은 $3$이다.\n\n이제 원 $C_2$를 생각하자.\n\n$\\angle APO=90^\\circ$이므로 삼각형 $APO$는 점 $P$에서 직각인 직각삼각형이다.\n직각삼각형의 외접원에서 빗변은 지름이므로\n\n$AO$\n\n가 원 $C_2$의 지름이다.\n\n$A(6,0)$, $O(0,0)$이므로 $AO=6$이다.\n따라서 $C_2$의 중심은 $AO$의 중점인\n\n$(3,0)$\n\n이고 반지름은 $3$이다.\n\n두 원의 중심 사이의 거리는\n\n$\\sqrt{(3-3)^2+(4-0)^2}=4$이다.\n\n두 원의 반지름이 모두 $3$이므로 공통현 $PQ$는 두 중심을 잇는 선분의 수직이등분선 위에 있다.\n\n두 중심을 잇는 선분의 중점을 $M$이라 하면\n\n$C_1M=2$이다.\n\n또 $M$은 공통현 $PQ$의 중점이므로\n\n$PM=QM$이다.\n\n직각삼각형 $C_1MP$에서\n\n$C_1P^2=C_1M^2+MP^2$이므로\n\n$3^2=2^2+MP^2$\n\n$MP^2=5$\n\n$MP=\\sqrt5$이다.\n\n따라서\n\n$PQ=2MP=2\\sqrt5$이다.\n\n따라서 정답은 ⑤이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q16-solution.svg",
    "solutionImageAlt": "중심 (3,4), (3,0), 반지름 3인 두 원과 공통현 PQ를 나타낸 그림",
    "solutionImageCaption": "직각삼각형 APO의 외접원이 지름 AO인 원이 되어 두 원의 공통현을 결정한다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-INTERSECTION",
    "subUnit": "원과 직선·원의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 17,
    "level": "중",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["객관식","원의 방정식","접선","접점현","중심","반지름","도형"],
    "wide": false,
    "content": "점 $A(18,2)$에서 원 $(x-3)^2+(y-2)^2=9$에 접선을 그었을 때, 두 개의 접점 $P$, $Q$가 생긴다. 점 $P$, $Q$의 $x$좌표의 합을 구하면? [4.5점]",
    "choices": [
      "$5$",
      "$\\dfrac{28}{5}$",
      "$\\dfrac{32}{5}$",
      "$\\dfrac{36}{5}$",
      "$8$"
    ],
    "answer": "④",
    "solution": "원의 중심을\n$C=(3,2)$라 하자.\n\n두 접점 중 하나를\n$P(u,v)$라 하겠다.\n\n점 $P$는 원 위에 있으므로\n\n$(u-3)^2+(v-2)^2=9$이다.\n\n또 $AP$는 접선이고 $CP$는 반지름이므로\n\n$AP\\perp CP$이다.\n\n따라서 두 직선의 기울기의 곱이 $-1$이므로\n\n$\\dfrac{v-2}{u-18}\\cdot\\dfrac{v-2}{u-3}=-1$이다.\n\n양변을 정리하면\n\n$(v-2)^2=-(u-18)(u-3)$이다.\n\n이 식을 원의 방정식에 대입하면\n\n$(u-3)^2-(u-18)(u-3)=9$이다.\n\n왼쪽에서 $(u-3)$을 묶으면\n\n$(u-3)\\{(u-3)-(u-18)\\}=9$\n\n$15(u-3)=9$이다.\n\n따라서\n\n$u-3=\\dfrac35$\n\n$u=\\dfrac{18}{5}$이다.\n\n즉 접점 $P$의 $x$좌표는 $\\dfrac{18}{5}$이다.\n\n다른 접점 $Q$도 원 위의 점이면서 $AQ$가 접선이므로 같은 계산이 적용된다.\n\n따라서 $Q$의 $x$좌표도\n\n$\\dfrac{18}{5}$이다.\n\n그러므로 두 접점의 $x$좌표의 합은\n\n$\\dfrac{18}{5}+\\dfrac{18}{5}$\n\n$=\\dfrac{36}{5}$이다.\n\n따라서 정답은 ④이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q17-solution.svg",
    "solutionImageAlt": "점 A(18,2)에서 원에 그은 두 접선과 수직인 접점 현 PQ를 나타낸 그림",
    "solutionImageCaption": "접점 현은 CA에 수직인 수직선 x=18/5이고 두 접점의 x좌표가 같다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
                    {
    "id": 18,
    "level": "중",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "단답형",
      "직선의 방정식",
      "무게중심",
      "점과 직선 사이의 거리",
      "도형",
      "직선",
      "수직",
      "거리"
    ],
    "wide": false,
    "content": "서답형 1. (단답형)<br>삼각형 $ABC$의 무게중심 $G$의 좌표는 $(3,1)$이고, 직선 $BC$의 방정식은 $y=3x-1$이다. 점 $A$에서 변 $BC$에 내린 수선의 발을 $H$라 할 때, 선분 $AH$의 길이는 $\\dfrac{n}{\\sqrt{10}}$이다. 자연수 $n$의 값을 구하시오. [부분 점수 없음, 5점]",
    "image": "assets/images/25_순천고_2학기_중간_고1_기출/q18.png",
    "imageSize": "large",
    "choices": [],
    "answer": "$21$",
    "solution": "변 $BC$의 중점을\n\n$M=(u,v)$\n\n라 하자.\n\n점 $M$은 직선\n$y=3x-1$\n위에 있으므로\n\n$v=3u-1$이다.\n\n삼각형 $ABC$의 무게중심은 $G=(3,1)$이다.\n무게중심 좌표를 $A$와 중점 $M$으로 나타내면\n\n$\\dfrac{x_A+2u}{3}=3$,\n\n$\\dfrac{y_A+2v}{3}=1$이다.\n\n따라서\n\n$x_A=9-2u$,\n\n$y_A=3-2v$이다.\n\n직선 $BC$를 일반형으로 나타내면\n\n$3x-y-1=0$이다.\n\n점 $A$에서 직선 $BC$까지의 거리가 바로 $AH$이므로\n\n$AH=\\dfrac{|3x_A-y_A-1|}{\\sqrt{3^2+(-1)^2}}$이다.\n\n분자를 먼저 계산하면\n\n$3x_A-y_A-1$\n\n$=3(9-2u)-(3-2v)-1$\n\n$=27-6u-3+2v-1$\n\n$=23-6u+2v$이다.\n\n여기서 $v=3u-1$을 대입하면\n\n$23-6u+2(3u-1)$\n\n$=23-6u+6u-2$\n\n$=21$이다.\n\n따라서\n\n$AH=\\dfrac{21}{\\sqrt{10}}$이다.\n\n문제에서\n$AH=\\dfrac{n}{\\sqrt{10}}$\n이라 했으므로\n\n$n=21$이다.\n\n따라서 답은 $21$이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q18-solution.svg",
    "solutionImageAlt": "G와 BC의 중점 M을 좌표별로 비교해 A와 수선의 발 H를 표시한 해설 도형",
    "solutionImageCaption": "무게중심 조건을 좌표별로 적용하고 BC 위의 M과 AH의 거리 관계를 확인한다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 19,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["단답형","원의 방정식","교점","직선과 원","거리","도형"],
    "wide": false,
    "content": "서답형 2. (단답형)<br>원 $x^2+y^2+3px+3qy-16=0$이 직선 $y=mx$와 만나는 두 점을 $P$, $Q$라 할 때, $\\overline{OP}$와 $\\overline{OQ}$의 곱을 구하시오. (단, $p$, $q$, $m$은 실수이고 $O$는 원점이다.) [부분 점수 없음, 5점]",
    "choices": [],
    "answer": "$16$",
    "solution": "직선 $y=mx$와 원의 두 교점을\n\n$P=(x_1,mx_1)$,\n$Q=(x_2,mx_2)$\n\n라 하자.\n\n직선 $y=mx$를 원\n\n$x^2+y^2+3px+3qy-16=0$\n\n에 대입하면\n\n$x^2+m^2x^2+3px+3qmx-16=0$이다.\n\n정리하면\n\n$(1+m^2)x^2+3(p+qm)x-16=0$이다.\n\n$x_1$, $x_2$는 이 이차방정식의 두 근이므로 근과 계수의 관계에 따라\n\n$x_1x_2=\\dfrac{-16}{1+m^2}$이다.\n\n이제 원점에서 두 교점까지의 거리를 구한다.\n\n$OP$\n\n$=\\sqrt{x_1^2+(mx_1)^2}$\n\n$=|x_1|\\sqrt{1+m^2}$이고,\n\n$OQ$\n\n$=\\sqrt{x_2^2+(mx_2)^2}$\n\n$=|x_2|\\sqrt{1+m^2}$이다.\n\n따라서\n\n$OP\\cdot OQ$\n\n$=|x_1x_2|(1+m^2)$\n\n$=\\dfrac{16}{1+m^2}(1+m^2)$\n\n$=16$이다.\n\n따라서 구하는 값은 $16$이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q19-solution.svg",
    "solutionImageAlt": "원과 원점을 지나는 직선의 두 교점 P,Q, 그리고 OP·OQ를 나타낸 그림",
    "solutionImageCaption": "직선 위 점을 (t,mt)로 놓아 두 거리의 곱을 근과 계수로 계산한다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-INTERSECTION",
    "subUnit": "원과 직선·원의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 20,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "단답형",
      "집합",
      "부분집합",
      "약수",
      "경우의 수"
    ],
    "wide": false,
    "content": "서답형 3. (단답형)<br>두 집합 $A$를 $24$의 약수 전체의 집합, $B$를 $18$의 약수 전체의 집합이라 하자. 다음 조건을 만족하는 집합 $X$의 개수를 구하시오. [부분 점수 없음, 5점]<br><br>(가) $A\\cap X=X$<br>(나) $(A\\cap B)\\cup X=X$<br>(다) $X\\ne A$, $X\\ne B$",
    "choices": [],
    "answer": "$15$",
    "solution": "조건 (가)\n\n$A\\cap X=X$\n\n는 $X$의 모든 원소가 $A$에 들어 있다는 뜻이므로\n\n$X\\subseteq A$이다.\n\n조건 (나)\n\n$(A\\cap B)\\cup X=X$\n\n는 $A\\cap B$의 모든 원소가 이미 $X$에 들어 있다는 뜻이므로\n\n$A\\cap B\\subseteq X$이다.\n\n이제 실제 집합을 구한다.\n\n$24$의 양의 약수 전체의 집합은\n\n$A=\\{1,2,3,4,6,8,12,24\\}$이다.\n\n또 $18$의 양의 약수 전체의 집합은\n\n$B=\\{1,2,3,6,9,18\\}$이다.\n\n따라서\n\n$A\\cap B=\\{1,2,3,6\\}$이다.\n\n그러므로 $X$는\n\n$\\{1,2,3,6\\}$을 반드시 포함하고,\n\n$A$의 나머지 원소\n$4,8,12,24$\n는 각각 넣어도 되고 넣지 않아도 된다.\n\n따라서 조건 (가), (나)를 만족하는 $X$의 개수는\n\n$2^4=16$개이다.\n\n이 중 $X=A$인 경우 한 개는 조건 (다)에서 제외된다.\n\n또 $X\\subseteq A$인데 $B$에는 $A$에 없는 원소 $9,18$이 들어 있으므로\n$X=B$인 경우는 애초에 생길 수 없다.\n\n따라서 구하는 집합 $X$의 개수는\n\n$16-1=15$이다.\n\n따라서 답은 $15$이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
                    {
    "id": 21,
    "level": "중",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형",
      "직선의 방정식",
      "수선의 발",
      "점과 직선 사이의 거리",
      "도형",
      "직선",
      "수직",
      "거리"
    ],
    "wide": false,
    "content": "서답형 4. (서술형)<br>점 $A(2,-3)$에서 직선 $l:x-y+2=0$에 내린 수선의 발을 $H(a,b)$, 점 $A$와 직선 $l$ 사이의 거리를 $c$라 할 때, $a+b+c$의 값을 구하는 풀이과정과 답을 서술하시오. (단, $a$, $b$, $c$는 상수이다.) [부분 점수 있음, 6점]",
    "choices": [],
    "answer": "$-1+\\dfrac{7\\sqrt2}{2}$",
    "solution": "직선\n$l:x-y+2=0$\n을 $y$에 대하여 정리하면\n\n$y=x+2$이다.\n\n따라서 직선 $l$의 기울기는 $1$이다.\n\n점 $A(2,-3)$에서 직선 $l$에 내린 수선은 $l$과 수직이므로 기울기는 $-1$이다.\n\n점 $A(2,-3)$을 지나므로 수선의 방정식은\n\n$y+3=-(x-2)$\n\n$y=-x-1$이다.\n\n수선의 발 $H(a,b)$는 두 직선\n\n$y=x+2$,\n$y=-x-1$\n\n의 교점이다.\n\n따라서\n\n$x+2=-x-1$\n\n$2x=-3$\n\n$x=-\\dfrac32$이다.\n\n그러므로\n\n$a=-\\dfrac32$이고,\n\n$b=a+2=-\\dfrac32+2=\\dfrac12$이다.\n\n따라서\n\n$a+b=-1$이다.\n\n이제 점 $A(2,-3)$과 직선\n$x-y+2=0$\n사이의 거리를 구한다.\n\n$c=\\dfrac{|2-(-3)+2|}{\\sqrt{1^2+(-1)^2}}$\n\n$=\\dfrac7{\\sqrt2}$\n\n$=\\dfrac{7\\sqrt2}{2}$이다.\n\n따라서\n\n$a+b+c$\n\n$=-1+\\dfrac{7\\sqrt2}{2}$이다.\n\n그러므로 구하는 값은\n$-1+\\dfrac{7\\sqrt2}{2}$이다.",
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q21-solution.svg",
    "solutionImageAlt": "직선의 방정식 문항 21의 실제 점과 직선 관계를 표시한 해설 도형",
    "solutionImageCaption": "수직 관계 · 교점 · A=(2,−3) · H=(−3/2,1/2), 거리=7/√2",
    "solutionImageSize": "full"
  },
  {
    "id": 22,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["서술형","원의 방정식","접선","중심","반지름","거리","도형"],
    "wide": false,
    "content": "서답형 5. (서술형)<br>점 $(0,6)$에서 원 $(x-2)^2+(y-1)^2=4$에 그은 두 접선을 구하는 과정 중 다음 물음에 답하여라. [부분 점수 있음, 7점]<br><br>(1) ㉠과 ㉡을 옳게 적으시오. [각 1점]<br>주어진 원은 중심의 (㉠)좌표의 절댓값이 반지름과 일치하므로 (㉡)축에 접한다. 따라서 두 접선 중 하나는 (㉡)축이다.<br><br>(2) 기울기가 $m$이고 점 $(0,6)$을 지나는 직선의 방정식을 일반형으로 쓰시오. [2점]<br><br>(3) 원의 중심과 접선 사이의 거리가 원의 반지름의 길이와 같음을 이용하여 $m$을 구하는 과정을 쓰시오. [3점, 부분점수 있음]",
    "choices": [],
    "answer": "㉠ $x$, ㉡ $y$; $mx-y+6=0$; $m=-\\dfrac{21}{20}$",
    "solution": "(1) 원\n$(x-2)^2+(y-1)^2=4$\n의 중심은 $(2,1)$이고 반지름은 $2$이다.\n\n중심의 $x$좌표의 절댓값은\n\n$|2|=2$\n\n로 반지름과 같다.\n\n즉 중심에서 $y$축까지의 거리가 반지름과 같으므로 이 원은 $y$축에 접한다.\n\n따라서\n\n㉠은 $x$,\n\n㉡은 $y$이다.\n\n두 접선 중 하나는 $y$축, 즉 $x=0$이다.\n\n(2) 기울기가 $m$이고 점 $(0,6)$을 지나는 직선은\n\n$y=mx+6$이다.\n\n이를 일반형으로 쓰면\n\n$mx-y+6=0$이다.\n\n(3) 나머지 접선도 원에 접하므로 중심 $(2,1)$에서 직선\n\n$mx-y+6=0$\n\n까지의 거리가 반지름 $2$와 같아야 한다.\n\n따라서\n\n$\\dfrac{|2m-1+6|}{\\sqrt{m^2+(-1)^2}}=2$\n\n$\\dfrac{|2m+5|}{\\sqrt{m^2+1}}=2$이다.\n\n양변을 제곱하면\n\n$(2m+5)^2=4(m^2+1)$이다.\n\n전개하면\n\n$4m^2+20m+25=4m^2+4$\n\n$20m+21=0$이다.\n\n따라서\n\n$m=-\\dfrac{21}{20}$이다.\n\n그러므로\n\n㉠ $x$, ㉡ $y$,\n\n직선의 일반형은 $mx-y+6=0$,\n\n$m=-\\dfrac{21}{20}$이다.",
    "solutionImage": "assets/images/25_순천고_2학기_중간_고1_기출/q22-solution.svg",
    "solutionImageAlt": "점 (0,6)과 중심 (2,1), 반지름 2인 원, y축 및 다른 접선을 나타낸 그림",
    "solutionImageCaption": "원의 y축 접선을 먼저 확인하고 거리 조건으로 나머지 접선의 기울기를 구한다.",
    "solutionImageSize": "full",
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category"
  },
  {
    "id": 23,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형",
      "집합",
      "합집합",
      "교집합",
      "최댓값",
      "최솟값"
    ],
    "wide": false,
    "content": "서답형 6. (서술형)<br>어느 고등학교에서 두 선택 과목 $A$, $B$를 선택한 학생 수를 조사하였다. 조사 결과가 다음과 같을 때, $A$ 또는 $B$를 선택한 학생 수의 최댓값과 최솟값의 합을 구하는 풀이과정과 답을 서술하시오. [부분 점수 있음, 7점]<br><br>(가) $A$를 선택한 학생 수는 $25$명이다.<br>(나) $B$를 선택한 학생 수는 $18$명이다.<br>(다) $A$만 선택하거나 $B$만 선택한 학생 수는 $31$명 이하이다.",
    "choices": [],
    "answer": "$62$",
    "solution": "두 과목을 모두 선택한 학생 수를 $x$명이라 하자.\n\n그러면 $A$만 선택한 학생 수는\n\n$25-x$명,\n\n$B$만 선택한 학생 수는\n\n$18-x$명이다.\n\n조건 (다)에서 한 과목만 선택한 학생 수는 $31$명 이하이므로\n\n$(25-x)+(18-x)\\le31$이다.\n\n따라서\n\n$43-2x\\le31$\n\n$-2x\\le-12$\n\n$x\\ge6$이다.\n\n또 두 과목을 모두 선택한 학생 수는 $B$를 선택한 전체 학생 수 $18$명을 넘을 수 없으므로\n\n$x\\le18$이다.\n\n따라서\n\n$6\\le x\\le18$이다.\n\n$A$ 또는 $B$를 선택한 학생 수는\n\n$n(A\\cup B)=25+18-x$\n\n$=43-x$이다.\n\n이 값은 $x$가 가장 작을 때 최대이므로\n\n$x=6$일 때\n\n$43-6=37$명이다.\n\n또 $x$가 가장 클 때 최소이므로\n\n$x=18$일 때\n\n$43-18=25$명이다.\n\n따라서 최댓값과 최솟값의 합은\n\n$37+25=62$이다.\n\n따라서 답은 $62$이다.",
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  }
];
