window.examTitle = "26_금당고_1학기_중간_고1_기출_content"; 

window.questionBank = [
  {
    id: 1,
    level: "하",
    category: "다항식의 연산",
    originalCategory: "다항식의 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-01",
    standardUnit: "다항식의 연산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 다항식\\n$A=3x^2+4x-2, B=x^2+x+3$\\n에 대하여 $2A+B$를 간단히 하면?",
    choices: ["$7x^2+9x-1$", "$7x^2+9x-3$", "$7x^2+9x-5$", "$7x^2+9x-7$", "$7x^2+9x-9$"],
    answer: "①",
    solution: ""
  },
  {
    id: 2,
    level: "하",
    category: "다항식의 연산",
    originalCategory: "다항식의 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-01",
    standardUnit: "다항식의 연산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x+y=2, x^2+y^2=6$일 때, $x^3+y^3$의 값은?",
    choices: ["12", "14", "16", "18", "20"],
    answer: "②",
    solution: ""
  },
  {
    id: 3,
    level: "중",
    category: "다항식의 연산",
    originalCategory: "다항식의 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-01",
    standardUnit: "다항식의 연산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다항식 $(4x-ay+2)^2$의 전개식에서 $x^2$의 계수와 $y$의 계수가 같을 때, 상수 $a$의 값은?",
    choices: ["$-1$", "$-2$", "$-3$", "$-4$", "$-5$"],
    answer: "④",
    solution: ""
  },
  {
    id: 4,
    level: "하",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 이차방정식 중에서 서로 다른 두 허근을 갖는 것은?",
    choices: ["$x^2-x-1=0$", "$x^2-2x+1=0$", "$x^2-5x+9=0$", "$2x^2+5x-2=0$", "$4x^2+4x+1=0$"],
    answer: "③",
    solution: ""
  },
  {
    id: 5,
    level: "하",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차방정식 $x^2-5x-3=0$의 두 근의 합과 곱을 각각 $a, b$라 할 때, $a+b$의 값은?",
    choices: ["1", "2", "3", "4", "5"],
    answer: "②",
    solution: ""
  },
  {
    id: 6,
    level: "중",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$-1 \\le x \\le 2$에서 이차함수 $y=x^2-6x+4$의 최댓값은?",
    choices: ["7", "8", "9", "10", "11"],
    answer: "⑤",
    solution: ""
  },
  {
    id: 7,
    level: "중",
    category: "항등식과 나머지 정리",
    originalCategory: "항등식과 나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "항등식과 나머지 정리",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "등식\\n$(2x+3)(x-2)+8 = ax(x-2)+b(x-2)+cx$\\n가 $x$에 대한 항등식일 때, $a-b+c$의 값을 구하면? (단, $a, b, c$는 상수이다.)",
    choices: ["7", "8", "9", "10", "11"],
    answer: "①",
    solution: ""
  },
  {
    id: 8,
    level: "중",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "등식 $(a+1)+3i = 7+bi$를 만족시키는 두 실수 $a, b$에 대하여 $a-b$의 값을 구하면? (단, $i=\\sqrt{-1}$이다.)",
    choices: ["1", "2", "3", "4", "5"],
    answer: "③",
    solution: ""
  },
  {
    id: 9,
    level: "중",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $y=2x^2-x+k$의 그래프와 $x$축이 한 점에서 만나도록 하는 실수 $k$의 값은?",
    choices: ["$-\\dfrac{1}{4}$", "$-\\dfrac{1}{8}$", "$\\dfrac{1}{2}$", "$\\dfrac{1}{8}$", "$\\dfrac{1}{4}$"],
    answer: "④",
    solution: ""
  },
  {
    id: 10,
    level: "중",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차방정식 $-2x^2+4x+6=0$의 두 근을 $\\alpha, \\beta$라고 할 때, 두 수 $\\alpha^3, \\beta^3$을 근으로 하고 $x^2$의 계수가 1인 이차방정식은?",
    choices: ["$x^2-26x-27=0$", "$x^2+26x+27=0$", "$x^2-26x+27=0$", "$x^2+13x-27=0$", "$x^2-13x-27=0$"],
    answer: "①",
    solution: ""
  },
  {
    id: 11,
    level: "상",
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-03",
    standardUnit: "인수분해",
    standardUnitOrder: 3,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "일차식 $f(x)$에 대하여 다항식 $x^3+1-f(x)$가 $(x+1)(x+a)^2$으로 인수분해 될 때, $f(11)$의 값은? (단, $a$는 상수이다.)",
    choices: ["1", "3", "5", "7", "9"],
    answer: "⑤",
    solution: ""
  },
  {
    id: 12,
    level: "중",
    category: "항등식과 나머지 정리",
    originalCategory: "항등식과 나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "항등식과 나머지 정리",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다항식 $f(x)$를 $x-1$로 나눈 몫은 $Q(x)$, 나머지는 5이고, $Q(x)$를 $x-2$로 나눈 나머지는 10이다. $f(x)$를 $(x-1)(x-2)$로 나눈 나머지를 $ax+b$라 할 때, 두 상수 $a, b$에 대하여 $2a+b$의 값은?",
    choices: ["11", "13", "15", "17", "19"],
    answer: "③",
    solution: ""
  },
  {
    id: 13,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $y=kx^2+2(k+1)x+k-3$의 그래프와 직선 $y=2ax+b$가 $k$의 값에 관계없이 항상 한 점에서 만날 때, $a+b$의 값은? (단, $a, b$는 상수이다.)",
    choices: ["$-3$", "$-2$", "$-1$", "0", "1"],
    answer: "②",
    solution: ""
  },
{
  id: 14,
  level: "상",
  category: "이차방정식과 이차함수",
  originalCategory: "이차방정식과 이차함수",
  standardCourse: "공통수학1",
  standardUnitKey: "H22-C-05",
  standardUnit: "이차방정식과 이차함수",
  standardUnitOrder: 5,
  questionType: "객관식",
  layoutTag: "grid",
  tags: ["그래프", "도형"],
  wide: false,
  content: "아래 그림과 같이 폭과 높이가 4인 포물선 안에 둘레의 길이가 최대인 직사각형을 그리려고 할 때, 이 직사각형의 둘레의 길이는?",
  image: "assets/images/26_금당고_1학기_중간_고1_기출/q14.png",
  choices: ["6", "7", "8", "9", "10"],
  answer: "③",
  solution: ""
},
  {
    id: 15,
    level: "상",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "실수 $a$에 대하여 복소수 $z$를 $z=a^2-1+(a-1)i$라 하자. $z^2$이 음의 실수일 때,\\n$(\\dfrac{1-i}{\\sqrt{2}})^n = \\dfrac{(z-\\bar{z})i}{4}$\\n가 되도록 하는 300이하의 자연수 $n$의 개수는? (단, $\\bar{z}$는 $z$의 켤레복소수이고, $i=\\sqrt{-1}$이다.)",
    choices: ["37", "38", "39", "40", "41"],
    answer: "④",
    solution: ""
  },
  {
    id: 16,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x^2$의 계수가 1인 이차함수 $y=f(x)$의 그래프와 직선 $y=5x+k$는 서로 다른 두 점에서 만난다. 두 교점의 $x$좌표를 각각 $\\alpha, \\beta$ ($\\alpha < \\beta$)라 할 때, $\\alpha : \\beta = 1 : 2$를 만족시킨다. $f(1)=3$일 때, $k$의 최댓값은? (단, $k$는 상수이다.)",
    choices: ["$-\\dfrac{17}{8}$", "$-2$", "$-\\dfrac{15}{8}$", "$-\\dfrac{7}{4}$", "$\\dfrac{13}{8}$"],
    answer: "⑤",
    solution: ""
  },
  {
    id: 17,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "함수 $f(x)$가 $f(x) = \\begin{cases} -x^2 & (x < 0) \\\\ x^2-x & (x \\ge 0) \\end{cases}$이고, 양수 $a$에 대하여 함수 $g(x)$를 $g(x) = \\begin{cases} ax+a & (x < -1) \\\\ 0 & (-1 \\le x < 1) \\\\ ax-a & (x \\ge 1) \\end{cases}$이라 하자. 함수 $y=f(x)$의 그래프와 함수 $y=g(x)$의 그래프가 서로 다른 세 점에서 만나도록 하는 $a$의 값은?",
    choices: ["1", "2", "3", "4", "5"],
    answer: "④",
    solution: ""
  },
{
  id: 18,
  level: "중",
  category: "항등식과 나머지 정리",
  originalCategory: "항등식과 나머지 정리",
  standardCourse: "공통수학1",
  standardUnitKey: "H22-C-02",
  standardUnit: "항등식과 나머지 정리",
  standardUnitOrder: 2,
  questionType: "서술형",
  layoutTag: "grid",
  tags: ["서술형", "표"],
  wide: false,
  content: "[서·논술형 1]\\n다음은 삼차다항식 $P(x)=ax^3+bx^2+cx+11$을 $x-3$으로 나누었을 때의 몫과 나머지를 조립제법을 이용하여 구하는 과정의 일부를 나타낸 것이다.\\n<div class=\"question-table-wrap\">\\n<table class=\"question-table\" style=\"width:230px; max-width:230px; margin:8px auto; border-collapse:collapse; table-layout:fixed; font-size:9pt; text-align:center;\">\\n<tr>\\n<td style=\"border:none; border-right:1px solid #000; width:34px; padding:3px 5px;\">3</td>\\n<td style=\"border:none; padding:3px 5px;\">$a$</td>\\n<td style=\"border:none; padding:3px 5px;\">$b$</td>\\n<td style=\"border:none; padding:3px 5px;\">$c$</td>\\n<td style=\"border:none; padding:3px 5px;\">11</td>\\n</tr>\\n<tr>\\n<td style=\"border:none; border-right:1px solid #000; padding:3px 5px;\"></td>\\n<td style=\"border:none; padding:3px 5px;\"></td>\\n<td style=\"border:none; padding:3px 5px;\">3</td>\\n<td style=\"border:none; padding:3px 5px;\">3</td>\\n<td style=\"border:none; padding:3px 5px;\">$-6$</td>\\n</tr>\\n<tr>\\n<td style=\"border:none; border-right:1px solid #000; border-top:1px solid #000; padding:3px 5px;\"></td>\\n<td style=\"border:none; border-top:1px solid #000; padding:3px 5px;\">1</td>\\n<td style=\"border:none; border-top:1px solid #000; padding:3px 5px;\">1</td>\\n<td style=\"border:none; border-top:1px solid #000; padding:3px 5px;\">$-2$</td>\\n<td style=\"border:none; border-top:1px solid #000; padding:3px 5px;\">5</td>\\n</tr>\\n</table>\\n</div>\\n$P(x)$를 $x-5$로 나누었을 때의 나머지를 구하는 과정을 풀이와 함께 상세하게 서술하시오.",
  choices: [],
  answer: "11",
  solution: ""
},
{
  id: 19,
  level: "중",
  category: "다항식의 연산",
  originalCategory: "다항식의 연산",
  standardCourse: "공통수학1",
  standardUnitKey: "H22-C-01",
  standardUnit: "다항식의 연산",
  standardUnitOrder: 1,
  questionType: "서술형",
  layoutTag: "grid",
  tags: ["서술형", "도형"],
  wide: false,
  content: "[서·논술형 2]\\n다음 그림과 같이 지름의 길이의 합이 8인 두 구가 서로 외접하고 있다. 두 구의 겉넓이의 합이 $40\\pi$일 때, 이 두 구의 부피의 합을 $a\\pi$라 하자. $8a$의 값을 구하는 과정을 풀이와 함께 상세하게 서술하시오.",
  image: "assets/images/26_금당고_1학기_중간_고1_기출/q19.png",
  choices: [],
  answer: "125",
  solution: ""
},
  {
    id: 20,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "[서·논술형 3]\\n실수 $t$에 대하여 $t \\le x \\le t+2$에서 이차함수 $f(x)=x^2-4x+10$의 최댓값과 최솟값의 차를 $g(t)$라 하자. $t$에 대한 방정식 $g(t)-\\dfrac{1}{2}=0, g(t)-1=0, g(t)-\\dfrac{3}{2}=0$의 서로 다른 실근의 개수를 각각 $a, b, c$라 할 때, $a+b+c$의 값을 풀이과정과 함께 상세하게 서술하시오.",
    choices: [],
    answer: "6",
    solution: ""
  }
];