window.examTitle = "26_팔마고_1학기_중간_고1_기출";

window.questionBank = [
  {
    id: 1,
    level: "하",
    category: "다항식의 연산",
    originalCategory: "다항식의 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-01",
    standardUnit: "다항식의 연산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(2x^2+3x+2)-(x^2+4x-3)=ax^2+bx+c$를 만족할 때, $a+b+c$의 값은? (단, $a, b, c$는 실수)",
    choices: ["1", "2", "3", "4", "5"],
    answer: "④",
    solution: ""
  },
  {
    id: 2,
    level: "중",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(\\sqrt{-7} \\times \\sqrt{7}) - \\left(\\dfrac{\\sqrt{128}}{\\sqrt{-8}}\\right) + (\\sqrt{-3} \\times \\sqrt{-3}) \\times i$의 값은?\\n(단, $i=\\sqrt{-1}$)",
    choices: ["$-12i$", "$-6i$", "$0$", "$8i$", "$20i$"],
    answer: "①",
    solution: ""
  },
  {
    id: 3,
    level: "하",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차방정식 $x^2-3x-6=0$의 두 근을 $\\alpha, \\beta$라 할 때, $(\\alpha-\\beta)^2$의 값은?",
    choices: ["30", "31", "32", "33", "34"],
    answer: "④",
    solution: ""
  },
  {
    id: 4,
    level: "중",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 이차함수 $y=x^2-2x+k-6$의 그래프와 $x$축이 만나지 않도록 하는 정수 $k$의 최솟값은?",
    choices: ["6", "7", "8", "9", "10"],
    answer: "③",
    solution: ""
  },
{
  id: 5,
  level: "중",
  category: "이차방정식과 이차함수",
  originalCategory: "이차방정식과 이차함수",
  standardCourse: "공통수학1",
  standardUnitKey: "H22-C-05",
  standardUnit: "이차방정식과 이차함수",
  standardUnitOrder: 5,
  questionType: "객관식",
  layoutTag: "grid",
  tags: [],
  wide: false,
  content: "이차함수 $y=2x^2+3x-1$의 그래프와 직선 $y=-2x+k$가 한 점에서 만나도록 하는 $k$에 대해 $\\dfrac{8}{11}|k|$의 값은?",
  choices: ["$-3$", "$-2$", "$-1$", "2", "3"],
  answer: "⑤",
  solution: ""
},
  {
    id: 6,
    level: "중",
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-03",
    standardUnit: "인수분해",
    standardUnitOrder: 3,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다항식 $3x^4+5x^3-x^2-5x-2$를 인수분해 하면\\n$3 \\times (x+a)(x+b)(x+c)(x+d)$이다.\\n이때, $a+b+c+d$의 값은? (단, $a, b, c, d$는 실수이다.)",
    choices: ["$-\\dfrac{5}{3}$", "$-\\dfrac{4}{3}$", "$\\dfrac{1}{3}$", "$\\dfrac{4}{3}$", "$\\dfrac{5}{3}$"],
    answer: "⑤",
    solution: ""
  },
  {
    id: 7,
    level: "중",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차방정식 $x^2+5x+1=0$의 두 근을 $\\alpha, \\beta$라 할 때,\\n$x^2$의 계수가 1이고 두 수 $\\dfrac{\\beta+1}{\\alpha}, \\dfrac{\\alpha+1}{\\beta}$를 두 근으로 하는 이차방정식을 $x^2+px+q=0$이라 할 때, $p+q$의 값은?\\n(단, $p, q$는 실수이다.)",
    choices: ["$-25$", "$-24$", "$-23$", "$-21$", "$-20$"],
    answer: "④",
    solution: ""
  },
  {
    id: 8,
    level: "상",
    category: "항등식과 나머지 정리",
    originalCategory: "항등식과 나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "항등식과 나머지 정리",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "최고차항의 계수가 양수인 다항식 $P(x)$가 모든 실수 $x$에 대하여\\n$9\\{P(x)\\}^2=12P(x)+4x^4-12x^3+9x^2-4$를 만족할 때, $P(1)$의 값은?",
    choices: ["$\\dfrac{1}{2}$", "$\\dfrac{1}{3}$", "$\\dfrac{1}{4}$", "$\\dfrac{1}{5}$", "$\\dfrac{1}{6}$"],
    answer: "②",
    solution: ""
  },
{
  id: 9,
  level: "상",
  category: "이차방정식과 이차함수",
  originalCategory: "이차방정식과 이차함수",
  standardCourse: "공통수학1",
  standardUnitKey: "H22-C-05",
  standardUnit: "이차방정식과 이차함수",
  standardUnitOrder: 5,
  questionType: "객관식",
  layoutTag: "grid",
  tags: ["그래프", "도형"],
  wide: false,
  content: "다음 그림과 같이 직사각형 $ABCD$의 두 꼭짓점 $A, B$는 이차함수 $y=-\\dfrac{1}{3}x^2+3$의 그래프 위에 있고, 두 꼭짓점 $C, D$는 이차함수 $y=x^2-9$의 그래프 위에 있다. 이때 직사각형 $ABCD$의 둘레의 길이에 대한 최댓값은?\\n(단, 점 $A$는 제1사분면, 점 $D$는 제4사분면 위의 점이다.)",
  image: "assets/images/26_팔마고_1학기_중간_고1_기출/q9.png",
  choices: ["$\\dfrac{51}{2}$", "$\\dfrac{53}{2}$", "$\\dfrac{55}{2}$", "$\\dfrac{57}{2}$", "$\\dfrac{59}{2}$"],
  answer: "⑤",
  solution: ""
},
  {
    id: 10,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "사차방정식 $(x^2-4x)(x^2-4x+7)+10=0$의 서로 다른 두 실근을 $\\alpha, \\beta$라 할 때, $\\alpha\\beta$의 값은?",
    choices: ["1", "2", "3", "4", "5"],
    answer: "②",
    solution: ""
  },
  {
    id: 11,
    level: "상",
    category: "항등식과 나머지 정리",
    originalCategory: "항등식과 나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "항등식과 나머지 정리",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다항식 $f(x)$를 $x^4+x^3+4x+2$로 나누었을 때, 나머지는 $x^3+2x^2-5x+4$이고, $x^2+2x+1$로 나누었을 때, 몫은 $x^3+3x^2-2x+7$이다. 이때, $f(1)$의 값은?",
    choices: ["41", "42", "43", "44", "45"],
    answer: "③",
    solution: ""
  },
  {
    id: 12,
    level: "상",
    category: "항등식과 나머지 정리",
    originalCategory: "항등식과 나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "항등식과 나머지 정리",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["표"],
    wide: false,
    content: "두 다항식 $f(x), g(x)$가 다음 조건을 만족시킨다.\\n<div class=\"question-table-wrap\">\\n<table class=\"question-table\">\\n<tr><td>(가) 모든 실수 $x$에 대하여 $f(x)=xg(x)$이다.</td></tr>\\n<tr><td>(나) 다항식 $f(x)g(x)$를 $3x+2$로 나눈 나머지는 $-\\dfrac{2}{3}$이다.</td></tr>\\n</table>\\n</div>\\n다항식 $(9x^2+\\dfrac{3}{4}) \\times f(2x-3)$을 $6x-7$로 나눈 나머지의 최솟값은?",
    choices: ["$-\\dfrac{26}{3}$", "$-\\dfrac{13}{3}$", "$-\\dfrac{7}{3}$", "$\\dfrac{13}{3}$", "$\\dfrac{26}{3}$"],
    answer: "①",
    solution: ""
  },
  {
    id: 13,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "길이가 $80\\text{cm}$인 철사를 잘라서 한 변의 길이가 각각 $a\\text{cm}, b\\text{cm}$ ($a>b$)인 두 개의 정사각형을 만들었다. 이 두 정사각형의 넓이의 합이 $218\\text{cm}^2$일 때, $a$의 값은?\\n(단, 철사는 모두 사용하고 굵기는 무시한다.)",
    choices: ["11", "12", "13", "14", "15"],
    answer: "③",
    solution: ""
  },
  {
    id: 14,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "삼차방정식 $x^3=-1$의 한 허근을 $\\omega$라 할 때,\\n$\\omega+2\\omega^2+3\\omega^3+4\\omega^4+5\\omega^5+6\\omega^6+7\\omega^7+8\\omega^8+9\\omega^9=a+b\\omega$\\n를 만족시키는 두 실수 $a, b$에 대하여 $b-a$의 값은?",
    choices: ["0", "5", "10", "15", "20"],
    answer: "④",
    solution: ""
  },
  {
    id: 15,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["표"],
    wide: false,
    content: "최고차항의 계수가 양수인 이차함수 $f(x)$가 다음 조건을 만족시킬 때, $f(3)$의 값은?\\n<div class=\"question-table-wrap\">\\n<table class=\"question-table\">\\n<tr><td>(가) 함수 $y=f(x)$의 그래프와 직선 $y=7$이 만나는 두 점의 $x$좌표는 각각 $-3, 1$이다.</td></tr>\\n<tr><td>(나) $-2 \\le x \\le 2$에서 이차함수 $f(x)$의 최댓값은 22이다.</td></tr>\\n</table>\\n</div>",
    choices: ["41", "42", "43", "44", "45"],
    answer: "⑤",
    solution: ""
  },
  {
    id: 16,
    level: "상",
    category: "복소수와 이차방정식",
    originalCategory: "복소수와 이차방정식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수와 이차방정식",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\left\\{(\\dfrac{1-i}{\\sqrt{2}})^m + (-i)^n\\right\\}^2 = -2i$를 만족하는 100이하의 자연수 $m, n$에 대하여 $m+n$의 최댓값은? (단, $i=\\sqrt{-1}$)",
    choices: ["196", "197", "198", "199", "200"],
    answer: "③",
    solution: ""
  },
  {
    id: 17,
    level: "상",
    category: "항등식과 나머지 정리",
    originalCategory: "항등식과 나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "항등식과 나머지 정리",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["표"],
    wide: false,
    content: "계수가 각각 실수인 삼차다항식 $P(x)$, 일차다항식 $Q(x)$가 아래의 조건을 만족할 때, $\\dfrac{P(0) \\times Q(1)}{a}$의 값은?\\n<div class=\"question-table-wrap\">\\n<table class=\"question-table\">\\n<tr><td>(가) $P(x) \\times Q(x)$는 $(x^2-6x+10)(x-2)$로 나누어 떨어진다.</td></tr>\\n<tr><td>(나) 모든 $x$에 대하여 $x^3-4x^2+ax-a-1 = P(x) + \\{Q(x)\\}^2$</td></tr>\\n<tr><td>(다) $Q(0)>0, Q(1)>0, P(0)<0$</td></tr>\\n</table>\\n</div>",
    choices: ["$-2$", "$-1$", "1", "2", "3"],
    answer: "①",
    solution: ""
  },
  {
    id: 18,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 사차방정식 $x^4-(2m+3)x^2+m^2+2=0$이 서로 다른 네 실근 $a, b, c, d$를 갖고, $ad+bc=-11$의 관계가 성립할 때, 양수 $m$의 값은? (단, $a<b<c<d$이다.)",
    choices: ["2", "4", "6", "8", "10"],
    answer: "③",
    solution: ""
  },
  {
    id: 19,
    level: "중",
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-03",
    standardUnit: "인수분해",
    standardUnitOrder: 3,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "[서답형(서술형) 1]\\n실수 $a, b, c$에 대해서 삼각형 $ABC$가 다음을 만족할 때,\\n$a^3+a^2b-ab^2-b^3-ac^2-bc^2=0$ 삼각형 $ABC$가 무슨 삼각형인지 정확하게 풀이과정과 함께 쓰시오.",
    choices: [],
    answer: "이등변삼각형($a=b$)",
    solution: ""
  },
  {
    id: 20,
    level: "하",
    category: "다항식의 연산",
    originalCategory: "다항식의 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-01",
    standardUnit: "다항식의 연산",
    standardUnitOrder: 1,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "[서답형(서술형) 2]\\n실수 $x, y$에 대하여 $x>y$이고 다음을 만족한다.\\n$x+y=-3$이고 $xy=1$이다.\\n(1) $x-y$의 값을 구하시오.\\n(2) $x^3-y^3$의 값을 구하시오.\\n(3) $x^6-y^6$의 값을 구하시오.",
    choices: [],
    answer: "(1) $\\sqrt{5}$ (2) $8\\sqrt{5}$ (3) $112\\sqrt{5}$",
    solution: ""
  },
  {
    id: 21,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "[서답형(서술형) 3]\\n연립방정식 $\\begin{cases} x-y=3 \\\\ x^2+y^2=17 \\end{cases}$의 해를 $x=\\alpha, y=\\beta$라 할 때, 다음의 물음에 답하시오.\\n(1) $\\alpha, \\beta$의 값을 모두 구하시오. (단, 한 쌍씩 정확하게 쓰시오.)\\n(2) $\\alpha+\\beta$의 최댓값을 구하시오.",
    choices: [],
    answer: "(1) ($4, 1$), ($-1, -4$) (2) 5",
    solution: ""
  },
  {
    id: 22,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "그래프"],
    wide: false,
    content: "[서답형(서술형) 4]\\n두 이차함수 $f(x)=x^2+4x+4, g(x)=-(x+1)^2+5$\\n$h(x) = \\begin{cases} f(x) (x \\le -3 \\text{ 또는 } x \\ge 0) \\\\ g(x) (-3 < x < 0) \\end{cases}$\\n이라 하자. 직선 $y=mx+7$과 $y=h(x)$의 그래프가 서로 다른 세 점에서 만나도록 하는 실수 $m$의 값의 합을 $S$라 할 때, $10S^2$의 값을 구하시오.",
    choices: [],
    answer: "25",
    solution: ""
  }
];