window.examTitle = "비상_공통수학2_원의방정식_중단원학습점검_고1";

window.questionBank = [
  {
    "id": "01",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "다음 원의 방정식을 구하시오.\n(1) 중심이 점 $(3,-2)$이고 반지름의 길이가 $4$인 원\n(2) 두 점 $(-2,6)$, $(4,-2)$를 지름의 양 끝점으로 하는 원",
    "choices": [],
    "image": "",
    "answer": "⑴ $(x-3)^2+(y+2)^2=16$\n⑵ $(x-1)^2+(y-2)^2=25$",
    "solution": "(1) 중심이 $(3,-2)$이고 반지름이 $4$이므로 원의 방정식은 $(x-3)^2+(y+2)^2=4^2=16$이다.\n(2) 지름의 양 끝점 $(-2,6)$, $(4,-2)$의 중점은 $((-2+4)/2,(6+(-2))/2)=(1,2)$이다. 두 끝점 사이의 거리는 $\\sqrt{6^2+(-8)^2}=10$이므로 반지름은 $5$이다.\n따라서 구하는 원의 방정식은 (1) $(x-3)^2+(y+2)^2=16$, (2) $(x-1)^2+(y-2)^2=25$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "02",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "원 $x^2+y^2+4x-6y+12=0$의 중심의 좌표와 반지름의 길이를 구하시오.",
    "choices": [],
    "image": "",
    "answer": "중심의 좌표: $(-2,3)$, 반지름의 길이: $1$",
    "solution": "$x^2+4x+y^2-6y+12=0$에서 완전제곱식을 만들면 $(x+2)^2-4+(y-3)^2-9+12=0$, 즉 $(x+2)^2+(y-3)^2=1$이다.\n따라서 중심의 좌표는 $(-2,3)$이고 반지름의 길이는 $1$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "03",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "다음 보기 중 원과 직선이 만나지 않는 것을 고르시오.\n보기\nㄱ. $x^2+y^2=5$, $2x+y-3=0$\nㄴ. $x^2+y^2=10$, $x+3y-10=0$\nㄷ. $(x-2)^2+(y+1)^2=15$, $y=2x+5$",
    "choices": [],
    "image": "",
    "answer": "ㄷ",
    "solution": "ㄱ의 원은 중심이 $(0,0)$이고 반지름이 $\\sqrt5$이다. 중심과 직선 $2x+y-3=0$ 사이의 거리는 $3/\\sqrt5<\\sqrt5$이므로 두 점에서 만난다.\nㄴ의 원은 중심이 $(0,0)$이고 반지름이 $\\sqrt{10}$이다. 중심과 직선 $x+3y-10=0$ 사이의 거리는 $10/\\sqrt{10}=\\sqrt{10}$이므로 한 점에서 만난다.\nㄷ의 원은 중심이 $(2,-1)$이고 반지름이 $\\sqrt{15}$이다. 직선은 $2x-y+5=0$으로 쓸 수 있고 중심과 직선 사이의 거리는 $|4+1+5|/\\sqrt5=2\\sqrt5$이다. $2\\sqrt5>\\sqrt{15}$이므로 만나지 않는다.\n따라서 만나지 않는 것은 ㄷ이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "04",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "원 $x^2+y^2=36$에 대한 다음 접선의 방정식을 구하시오.\n(1) 기울기가 $-2$인 접선\n(2) 원 위의 점 $(4,-2\\sqrt5)$를 지나는 접선",
    "choices": [],
    "image": "",
    "answer": "⑴ $y=-2x\\pm6\\sqrt5$\n⑵ $2x-\\sqrt5y=18$",
    "solution": "(1) 기울기가 $-2$인 직선을 $y=-2x+b$라고 하면 원점에서 직선까지의 거리가 반지름 $6$과 같아야 한다. 따라서 $|b|/\\sqrt5=6$이고 $b=\\pm6\\sqrt5$이다.\n(2) 원 $x^2+y^2=36$ 위의 점 $(x_1,y_1)$에서의 접선은 $x_1x+y_1y=36$이다. $(4,-2\\sqrt5)$를 대입하면 $4x-2\\sqrt5y=36$, 즉 $2x-\\sqrt5y=18$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "05",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "중심이 직선 $y=x+1$ 위에 있고, 두 점 $(-3,4)$, $(1,-2)$를 지나는 원의 방정식을 구하시오.",
    "choices": [],
    "image": "",
    "answer": "$(x-2)^2+(y-3)^2=26$",
    "solution": "원의 중심을 $(a,a+1)$이라고 하자. 두 점까지의 거리가 같으므로 $(a+3)^2+(a-3)^2=(a-1)^2+(a+3)^2$이다. 두 식에서 공통인 $(a+3)^2$을 없애면 $(a+3)^2+(a-3)^2=(a-1)^2+(a+3)^2$에서 $(a-3)^2=(a-1)^2$이다. 따라서 $a=2$이고 중심은 $(2,3)$이다.\n점 $(-3,4)$까지의 거리의 제곱은 $(-5)^2+1^2=26$이다.\n따라서 구하는 원의 방정식은 $(x-2)^2+(y-3)^2=26$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "06",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "방정식 $x^2+y^2-6kx-4y+5k+4=0$이 나타내는 도형이 원이 되도록 하는 실수 $k$의 값의 범위를 구하시오.",
    "choices": [],
    "image": "",
    "answer": "$k<0$ 또는 $k>\\dfrac59$",
    "solution": "$x^2+y^2-6kx-4y+5k+4=0$을 완전제곱식으로 고치면 $(x-3k)^2+(y-2)^2=9k^2-5k$이다. 원을 나타내려면 반지름의 제곱이 양수이므로 $9k^2-5k>0$이다.\n$k(9k-5)>0$을 풀면 $k<0$ 또는 $k>\\dfrac59$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "07",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "원 $x^2+y^2=25$와 직선 $x+y-k=0$이 서로 다른 두 점 $A$, $B$에서 만난다. $\\overline{AB}=8$일 때, 양수 $k$의 값을 구하시오.",
    "choices": [],
    "image": "",
    "answer": "$3\\sqrt2$",
    "solution": "원의 반지름은 $5$이고 현 $AB$의 길이가 $8$이므로 중심에서 현에 내린 수선은 현을 이등분한다. 직각삼각형에서 중심과 현 사이의 거리는 $\\sqrt{5^2-4^2}=3$이다.\n원점에서 직선 $x+y-k=0$까지의 거리는 $|k|/\\sqrt2$이므로 $|k|/\\sqrt2=3$이다. 양수 $k$는 $3\\sqrt2$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "08",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "원 $(x-1)^2+(y-a)^2=16$과 직선 $4x-3y+5a-2=0$이 만나도록 하는 실수 $a$의 값의 범위를 구하시오.",
    "choices": [],
    "image": "",
    "answer": "$-11\\le a\\le9$",
    "solution": "원의 중심은 $(1,a)$이고 반지름은 $4$이다. 중심과 직선 사이의 거리는 $|4-3a+5a-2|/5=|2a+2|/5$이다. 원과 직선이 만나려면 이 거리가 반지름 이하이므로 $|2a+2|/5\\le4$이다.\n따라서 $|a+1|\\le10$이고 $-11\\le a\\le9$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "09",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "원 $x^2+y^2=8$ 위의 점 $(-2,2)$를 지나는 접선이 $x$축, $y$축과 만나는 점을 각각 $A$, $B$라고 할 때, 삼각형 $OAB$의 넓이를 구하시오.\n(단, $O$는 원점)",
    "choices": [],
    "image": "",
    "answer": "$8$",
    "solution": "원 $x^2+y^2=8$ 위의 점 $(-2,2)$에서의 접선은 $-2x+2y=8$, 즉 $y=x+4$이다. 두 절편은 $A(-4,0)$, $B(0,4)$이다.\n삼각형 $OAB$의 넓이는 $\\dfrac12\\times4\\times4=8$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "10",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "점 $(0,-3)$에서 원 $(x-1)^2+(y-1)^2=4$에 그은 두 접선의 기울기의 곱을 구하시오.",
    "choices": [],
    "image": "",
    "answer": "$-4$",
    "solution": "점 $(0,-3)$을 지나고 기울기가 $m$인 직선은 $y=mx-3$이다. 원에 대입하면 $(m^2+1)x^2-2(1+4m)x+13=0$이다.\n접할 때 판별식이 $0$이므로 $(4m+1)^2-13(m^2+1)=0$이다. 이를 정리하면 $3m^2+8m-12=0$이다. 두 접선의 기울기는 이 방정식의 두 근이므로 곱은 $-12/3=-4$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "11",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "원 $x^2+y^2=4$에 대하여 원과 $x$축의 양의 부분의 교점을 $A$, 제2사분면 위에 있는 원 위의 한 점 $P$를 지나는 접선 $l$과 $x$축의 교점을 $B$라고 하자. 점 $P$에서 $x$축에 내린 수선의 발 $H$가 선분 $AB$의 중점일 때, 접선 $l$의 방정식을 구하시오.",
    "choices": [],
    "image": "",
    "answer": "$-x+\\sqrt3y=4$",
    "solution": "$P=(a,b)$라 하면 $a<0$, $b>0$, $a^2+b^2=4$이다. $A=(2,0)$, $H=(a,0)$이고 $H$가 $AB$의 중점이므로 $B=(2a-2,0)$이다.\n$P$에서의 접선은 $ax+by=4$이며 $B$도 이 직선 위에 있으므로 $a(2a-2)=4$, 즉 $a^2-a-2=0$, $(a-2)(a+1)=0$이다. $a<0$이므로 $a=-1$이다.\n$a^2+b^2=4$와 $b>0$에서 $b=\\sqrt3$이다. 따라서 접선은 $-x+\\sqrt3y=4$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  },
  {
    "id": "12",
    "level": "",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "questionType": "",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "원의 방정식",
      "중단원 학습 점검"
    ],
    "wide": false,
    "content": "두 점 $A(2,0)$, $B(0,2)$와 원 $(x-3)^2+(y-3)^2=2$ 위의 점 $P$에 대하여 삼각형 $APB$의 넓이의 최솟값을 구하시오.",
    "choices": [],
    "image": "",
    "answer": "$2$",
    "solution": "직선 $AB$의 방정식은 $x+y=2$이고 $AB=2\\sqrt2$이다. 원의 중심 $(3,3)$에서 직선 $x+y-2=0$까지의 거리는 $4/\\sqrt2=2\\sqrt2$이며 반지름은 $\\sqrt2$이다.\n중심에서 직선까지의 거리가 반지름보다 크므로 원은 직선의 한쪽에 놓인다. 따라서 원 위의 점에서 직선까지의 최솟값은 $2\\sqrt2-\\sqrt2=\\sqrt2$이다. 따라서 삼각형 $APB$의 넓이의 최솟값은 $\\dfrac12\\times2\\sqrt2\\times\\sqrt2=2$이다.",
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate"
  }
];
