const assert=require("node:assert/strict");
const core=require("../archive/archive2-core.js");
const rpm={sourceStatus:"VERIFIED",taxonomyStatus:"CONFIRMED",foundationTaxonomyStatus:"PROJECTION_PENDING",metadataConflicts:[]};
assert.equal(core.advancedAuthority(rpm),"rpm");
assert.equal(core.advancedEligible(rpm),true);
const mf={...rpm,metaFoundationPackVersion:"1.0.0",problemTypeKey:"PT_X",templateKey:"TPL_X"};
assert.equal(core.advancedAuthority(mf),"mf");
assert.equal(core.advancedEligible(mf),false);
assert.equal(core.advancedEligible({...mf,foundationTaxonomyStatus:"CONFIRMED"}),true);
const basic={questionUid:"qid_v1_"+"a".repeat(64),identityStatus:"VERIFIED",sourceStatus:"VERIFIED",sourceIntegrityStatus:"VERIFIED",courseKey:"M3-1",L1:"이차함수",L2:"그래프",semanticDisposition:"META_CANONICAL_HOLD"};
assert.equal(core.basicEligibility(basic).ok,true);
console.log("Archive2 META_V2 semantic authority PASS");