const { spawnSync } = require('child_process');
const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const crypto = require('crypto');
const exam = 'archive/exams/original/middle/m3/2final/23_순여중_2학기_기말_중3_기출.js';
const evidence = 'archive/data/r3-intake/m3/o63-emergency-closeout.physical-evidence.json';
const source = fs.readFileSync(exam,'utf8');
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(source, ctx);
assert.strictEqual(ctx.window.questionBank.length, 24);
const q = id => ctx.window.questionBank.find(x => x.id === id);
assert(q(4).subUnitKey === 'M3-06-CIRCLE_INSCRIBED_ANGLE');
assert(q(6).content.includes('다음 두 그림에서 각각'));
assert(q(10).content.includes('다음 두 그림에서') && q(10).content.includes('차례로 구하면'));
assert(q(17).solution.includes('16+9+9+0+1+0+4+1=40'));
assert(q(24).content.includes('다섯 명의 편차를 나타낸 것이다'));
const svg = fs.readFileSync('archive/assets/images/23_순여중_2학기_기말_중3_기출/q24-source.svg','utf8');
for (const v of ['>-3<','>1<','>5<']) assert(svg.includes(v));
const ev = JSON.parse(fs.readFileSync(evidence,'utf8'));
assert.strictEqual(ev.examSha256, 'sha256:' + crypto.createHash('sha256').update(source).digest('hex'));
const run = spawnSync(process.execPath,['archive/tools/review-evidence-gate.mjs','--exam',exam,'--evidence',evidence,'--stage','R3'],{encoding:'utf8'});
process.stdout.write(run.stdout || '');
process.stderr.write(run.stderr || '');
assert.strictEqual(run.status,0);
const report=JSON.parse(run.stdout);
assert.strictEqual(report.ok,true);
assert.deepStrictEqual(report.issues,[]);
assert.strictEqual(report.itemHoldCount,0);
console.log('O63_EMERGENCY_CLOSEOUT_TARGET_GATE PASS');
