import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { validateGptMainDoneReceipt } from '../archive/tools/archive-gpt-closeout-v2.mjs';
import { gitBlobSha } from '../archive/tools/archive-stage-validator-compat-v1.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'gpt-closeout-'));
const run=(...a)=>execFileSync('git',['-C',root,...a],{encoding:'utf8'}).trim();
fs.mkdirSync(path.join(root,'archive/exams/original/high/h1/1mid'),{recursive:true});
fs.mkdirSync(path.join(root,'archive/assets/images/test'),{recursive:true});
const js=Buffer.from('window.examTitle="fixture";window.questionBank=[{id:1}];');
const prod='archive/exams/original/high/h1/1mid/24_fixture.js';fs.writeFileSync(path.join(root,prod),js);
const asset=Buffer.from('<svg/>');fs.writeFileSync(path.join(root,'archive/assets/images/test/q1.svg'),asset);
run('init');run('config','user.email','test@example.com');run('config','user.name','test');run('add','.');run('commit','-m','fixture');
const main=run('rev-parse','HEAD');run('update-ref','refs/remotes/origin/main',main);
const r3={ok:true,validatorMode:'R3_V2',artifactSha:gitBlobSha(js),qualityContractVersion:'JS_ARCHIVE_QUALITY_CONTRACT_V2_20261006',executionLine:'GPT_SCHEDULED',campaignId:'H1_GPT2_20261006',stream:'A',artifactContract:{active:true}};
fs.writeFileSync(path.join(root,'r3.json'),JSON.stringify(r3));
const receipt={executionLine:'GPT_SCHEDULED',qualityContractVersion:'JS_ARCHIVE_QUALITY_CONTRACT_V2_20261006',status:'MAIN_DONE',campaignId:'H1_GPT2_20261006',stream:'A',artifactSha:gitBlobSha(js),productionPath:prod,remoteMainSha:main,r3Validation:{path:'r3.json',sha256:hash(Buffer.from(JSON.stringify(r3)))}};
const assets=[{ref:'assets/images/test/q1.svg',sha256:hash(asset)}];
test.after(()=>fs.rmSync(root,{recursive:true,force:true}));
test('GPT MAIN_DONE binds campaign, stream, R3 validation, production blob and assets',()=>assert.equal(validateGptMainDoneReceipt({receipt,root,r3Validation:r3,assets,campaignId:'H1_GPT2_20261006',stream:'A'}).ok,true));
test('GPT MAIN_DONE rejects cross-stream receipt',()=>assert.equal(validateGptMainDoneReceipt({receipt:{...receipt,stream:'B'},root,r3Validation:r3,assets,campaignId:'H1_GPT2_20261006',stream:'A'}).ok,false));
test('GPT MAIN_DONE rejects stale asset SHA',()=>assert.equal(validateGptMainDoneReceipt({receipt,root,r3Validation:r3,assets:[{...assets[0],sha256:'stale'}],campaignId:'H1_GPT2_20261006',stream:'A'}).ok,false));
