import assert from "node:assert/strict";
import { applyRow, courseKey } from "../archive/tools/meta-foundation/materialize-meta-v2-payloads.mjs";
assert.equal(courseKey("M3-04"),"M3-1");
assert.equal(courseKey("M3-05"),"M3-2");
const p={certificationTrack:"MAIN_PRESENT_META_ONLY",canonicalOrdinal:47,reviewedAtKst:"2026-09-30T19:13:52+09:00"};
const cur={questionUid:"qid",courseKey:"M3-1",L3:"old",L4:"old",metaFoundationPackVersion:"9",reviewStatus:"review_required",fieldStatus:{problemType:"manual_review_pending"}};
const r={sourceOrdinal:1,curriculum:"2015",course:"중3 수학",standardUnitKey:"M3-05",subUnitKey:"M3-05-TRIG_RATIO",semanticStatus:"FINAL",rpmRecordId:"M3-RPM-055",rpmPath:{majorUnit:"삼각비",midUnit:"삼각비",l3:"삼각비의 뜻",l4:"sin·cos·tan"},mappingStatus:"DIRECT_ACTIVE",projectionStatus:"PROJECTION_REUSE",problemTypeKey:"PT_TRIG_RATIO",templateKey:"TPL_TRIG_RATIO_BASIC_RELATION",crossConceptKeys:["CC_PYTHAGOREAN"],conditionKeys:[],integrationPattern:"SEQUENTIAL",metadataDisposition:"ACTIVE_CANONICAL_REUSE",difficulty:{difficultyBucket:2,difficultyConfidence:"high",difficultyBoundaryFlag:"NONE",legacyLevelCompatibility:"NORMAL"}};
const n=applyRow(cur,r,p,"payload.json");
assert.equal(n.courseKey,"M3-2");
assert.equal(n.L3,"삼각비의 뜻");
assert.equal(n.foundationTaxonomyStatus,"CONFIRMED");
assert.equal(n.metaFoundationPackVersion,undefined);
assert.equal(n.reviewStatus,"reviewed_pass");
const h=applyRow(n,{...r,semanticStatus:"HOLD",rpmRecordId:null,rpmPath:null,projectionStatus:"NOT_ATTEMPTED",problemTypeKey:null,templateKey:null,holdReason:"MULTI",metadataDisposition:"META_CANONICAL_HOLD"},p,"payload.json");
assert.equal(h.semanticDisposition,"META_CANONICAL_HOLD");
assert.equal(h.reviewStatus,"reviewed_pass");
assert.equal(h.L3,undefined);
assert.equal(h.problemTypeKey,undefined);
assert.equal(h.fieldStatus.difficulty,"approved_review2");
console.log("META_V2 materializer unit PASS");
