window.examTitle = "21_매산여고_1학기_중간_고1_기출";

window.questionBank = [
  {
    "id": 1,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "다항식"
    ],
    "content": "다항식 $x^3+3x^2+4x+2$를 $x^2+x-1$로 나누었을 때 몫을 $Q(x)$, 나머지를 $R(x)$라 할 때, $Q(1)+R(-1)$의 값을 구하시오. [3.9점]",
    "choices": [
      "$3$",
      "$4$",
      "$5$",
      "$6$",
      "$7$"
    ],
    "level": "중",
    "category": "항등식과 나머지정리",
    "originalCategory": "항등식과 나머지정리",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "layoutTag": "grid",
    "wide": false,
    "answer": "②",
    "subUnitKey": "H15-SA-02-REMAINDER_FACTOR",
    "subUnit": "나머지정리와 인수정리",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "먼저 나눗셈의 몫과 나머지를 실제로 구한다.\n$x^3+3x^2+4x+2=(x^2+x-1)(x+2)+(3x+4)$이다.\n곱셈으로 확인하면\n$(x^2+x-1)(x+2)=x^3+3x^2+x-2$이므로\n나머지는 $(x^3+3x^2+4x+2)-(x^3+3x^2+x-2)=3x+4$이다.\n따라서 $Q(x)=x+2$, $R(x)=3x+4$이다.\n$Q(1)=1+2=3$, $R(-1)=3(-1)+4=1$이므로\n$Q(1)+R(-1)=3+1=4$이다.\n따라서 정답은 ②이다.",
    "problemTypeKey": "PT_H1_REMAINDER_THEOREM",
    "templateKey": null,
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 2,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "다항식"
    ],
    "content": "등식 $x^3+4x^2+5x+3=a(x-1)^3+b(x-1)^2+c(x-1)+d$가 $x$값에 관계없이 항상 성립할 때, $a+b-c+d$의 값을 구하시오. [3.9점]",
    "choices": [
      "$-7$",
      "$-3$",
      "$0$",
      "$1$",
      "$5$"
    ],
    "level": "하",
    "category": "항등식과 나머지정리",
    "originalCategory": "항등식과 나머지정리",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "layoutTag": "grid",
    "wide": false,
    "answer": "⑤",
    "subUnitKey": "H15-SA-02-IDENTITY",
    "subUnit": "항등식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "$(x-1)$의 거듭제곱별 계수를 비교하기 위해 $t=x-1$로 둔다.\n그러면 $x=t+1$이므로\n$x^3+4x^2+5x+3=(t+1)^3+4(t+1)^2+5(t+1)+3$이다.\n각 항을 전개하면\n$=t^3+3t^2+3t+1+4t^2+8t+4+5t+5+3$\n$=t^3+7t^2+16t+13$이다.\n따라서 $a=1$, $b=7$, $c=16$, $d=13$이다.\n구하는 값은 $a+b-c+d=1+7-16+13=5$이다.\n따라서 정답은 ⑤이다.",
    "problemTypeKey": "PT_H1_POLY_IDENTITY_COEFFICIENT",
    "templateKey": "TPL_H1_IDENTITY_COEFFICIENT_COMPARE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 3,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "다항식"
    ],
    "content": "$x$에 대한 다항식 $f(x)$를 $x-3$으로 나누었을 때의 나머지는 $9$이고, $(x+1)^2$으로 나누었을 때의 나머지는 $x-2$이다. $f(x)$를 $(x+1)^2(x-3)$으로 나누었을 때의 나머지를 $R(x)$라 할 때, $R(5)$를 구하시오. [5.0점]",
    "choices": [
      "$19$",
      "$21$",
      "$23$",
      "$25$",
      "$27$"
    ],
    "level": "상",
    "category": "항등식과 나머지정리",
    "originalCategory": "항등식과 나머지정리",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "layoutTag": "grid",
    "wide": false,
    "answer": "②",
    "subUnitKey": "H15-SA-02-REMAINDER_FACTOR",
    "subUnit": "나머지정리와 인수정리",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "나누는 식 $(x+1)^2(x-3)$은 삼차식이므로 나머지 $R(x)$의 차수는 $2$ 이하이다.\n$(x+1)^2$으로 나눈 나머지가 $x-2$라는 조건을 먼저 이용한다.\n$R(x)=x-2+k(x+1)^2$로 놓을 수 있다.\n또 $x-3$으로 나눈 나머지가 $9$이므로 $R(3)=f(3)=9$이다.\n$R(3)=3-2+k(3+1)^2=1+16k=9$에서\n$16k=8$, $k=\\dfrac12$이다.\n따라서 $R(5)=5-2+\\dfrac12(5+1)^2$\n$=3+\\dfrac12\\cdot36=3+18=21$이다.\n따라서 정답은 ②이다.",
    "problemTypeKey": "PT_H1_REMAINDER_THEOREM",
    "templateKey": "TPL_H1_REMAINDER_COMPOSITE_DIVISOR",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 5,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 4,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "다항식"
    ],
    "content": "다음 중 다항식 $(x+1)(x+2)(x+3)(x+6)+x^2$의 인수인 것을 고르시오. [4.3점]",
    "choices": [
      "$x^2+6x+6$",
      "$x^2+4x+6$",
      "$x^2+x+2$",
      "$x^2+3x+2$",
      "$x^2+3x+6$"
    ],
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "layoutTag": "grid",
    "wide": false,
    "answer": "①",
    "subUnitKey": "H15-SA-03-FACTORIZATION",
    "subUnit": "인수분해",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "곱의 순서를 바꾸어 두 쌍의 곱을 비교한다.\n$(x+1)(x+6)=x^2+7x+6$이고\n$(x+2)(x+3)=x^2+5x+6$이다.\n두 식의 평균인 $A=x^2+6x+6$으로 쓰면\n$(x+1)(x+6)=A+x$, $(x+2)(x+3)=A-x$이다.\n따라서 주어진 다항식은\n$(A+x)(A-x)+x^2=A^2-x^2+x^2=A^2$\n$=(x^2+6x+6)^2$이다.\n그러므로 인수는 $x^2+6x+6$이다.\n따라서 정답은 ①이다.",
    "problemTypeKey": "PT_H1_POLY_FACTORIZATION",
    "templateKey": "TPL_H1_FACTORIZATION_APPLICATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 5,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "복소수"
    ],
    "content": "실수부분과 허수부분이 모두 $0$이 아닌 복소수 $z$에 대하여 다음에서 실수가 아닌 것을 모두 고르시오. (정답 2개) [3.6점]",
    "choices": [
      "$z+\\overline{z}$",
      "$z\\overline{z}$",
      "$\\dfrac{\\overline{z}}{z}$",
      "$(1+z)(1+\\overline{z})$",
      "$\\overline{z}$"
    ],
    "level": "중",
    "category": "복소수",
    "originalCategory": "복소수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "layoutTag": "grid",
    "wide": false,
    "answer": "③, ⑤",
    "subUnitKey": "H15-SA-04-COMPLEX_OPERATION",
    "subUnit": "복소수의 연산",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "$z=a+bi$로 놓자. 문제의 조건은 $a\\ne0$, $b\\ne0$이다. 각 보기를 따로 판정한다.\n① $z+\\overline z=(a+bi)+(a-bi)=2a$이므로 실수이다.\n② $z\\overline z=(a+bi)(a-bi)=a^2+b^2$이므로 실수이다.\n③ $\\dfrac{\\overline z}{z}=\\dfrac{a-bi}{a+bi}=\\dfrac{(a-bi)^2}{a^2+b^2}$\n$=\\dfrac{a^2-b^2}{a^2+b^2}-\\dfrac{2ab}{a^2+b^2}i$이다.\n$a,b$가 모두 $0$이 아니므로 허수부분 $-\\dfrac{2ab}{a^2+b^2}\\ne0$이다. 따라서 실수가 아니다.\n④ $(1+z)(1+\\overline z)=|1+z|^2=(1+a)^2+b^2$이므로 실수이다.\n⑤ $\\overline z=a-bi$의 허수부분은 $-b\\ne0$이므로 실수가 아니다.\n따라서 실수가 아닌 것은 ③과 ⑤이다.",
    "problemTypeKey": "PT_H1_COMPLEX_OPERATION",
    "templateKey": "TPL_H1_COMPLEX_CONJUGATE_NORM",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NONZERO"
    ],
    "integrationPattern": "CASE_BRANCH",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 6,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "무리수",
      "복소수"
    ],
    "content": "$0$이 아닌 실수 $x$, $y$에 대하여 옳은 것만을 <보기>에서 고르시오. <보기> ㄱ. $xy>0$이면 $\\sqrt{x}\\sqrt{y}=\\sqrt{xy}$이다. ㄴ. $0<x<y$이면 $\\dfrac{\\sqrt{y-x}}{\\sqrt{x-y}}+\\dfrac{\\sqrt{y}}{\\sqrt{-y}}=-2i$이다. ㄷ. $\\dfrac{\\sqrt{x}}{\\sqrt{y}}=-\\sqrt{\\dfrac{x}{y}}$이면 $\\sqrt{x}\\sqrt{x}+\\sqrt{y}$의 켤레복소수는 $x-\\sqrt{y}$이다. [5.1점]",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "level": "상",
    "category": "복소수",
    "originalCategory": "복소수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "layoutTag": "grid",
    "wide": false,
    "answer": "④",
    "subUnitKey": "H15-SA-04-COMPLEX_ROOT",
    "subUnit": "복소수와 제곱근",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "제곱근의 성질은 음수에 적용할 때 부호를 주의해야 한다. ㄱ~ㄷ을 각각 판단한다.\nㄱ. $xy>0$이면 $x,y$가 모두 양수일 수도, 모두 음수일 수도 있다.\n반례로 $x=y=-1$이면 $\\sqrt{x}\\sqrt{y}=i\\cdot i=-1$이지만 $\\sqrt{xy}=\\sqrt1=1$이다. 따라서 거짓이다.\nㄴ. $0<x<y$이므로 $y-x>0$이다.\n$\\sqrt{x-y}=i\\sqrt{y-x}$, $\\sqrt{-y}=i\\sqrt y$이므로\n$\\dfrac{\\sqrt{y-x}}{\\sqrt{x-y}}=\\dfrac1i=-i$이고\n$\\dfrac{\\sqrt y}{\\sqrt{-y}}=\\dfrac1i=-i$이다.\n두 항의 합은 $-i+(-i)=-2i$이므로 참이다.\nㄷ. $\\dfrac{\\sqrt{x}}{\\sqrt{y}}=-\\sqrt{\\dfrac xy}$가 성립하려면 $x>0$, $y<0$이어야 한다.\n실제로 이때 좌변은 $-i\\sqrt{x/(-y)}$이고 우변도 같은 값이다.\n따라서 $\\sqrt{x}\\sqrt{x}=x$는 실수이고 $\\sqrt{y}$는 순허수이다.\n그러므로 $x+\\sqrt y$의 켤레복소수는 $x-\\sqrt y$이다. 참이다.\n옳은 것은 ㄴ, ㄷ이므로 정답은 ④이다.",
    "problemTypeKey": "PT_H1_COMPLEX_OPERATION",
    "templateKey": null,
    "crossConceptKeys": [
      "CC_RADICAL_EXPRESSION"
    ],
    "conditionKeys": [
      "COND_NONZERO",
      "COND_RANGE"
    ],
    "integrationPattern": "CASE_BRANCH",
    "difficultyBucket": 5,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 7,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "이차함수"
    ],
    "content": "$x$에 대한 이차식 $2bx+a(x^2-1)+c(x^2+1)$이 완전제곱식일 때, $a$, $b$, $c$를 세 변의 길이로 하는 삼각형의 넓이를 구하시오. (단, $a$, $b$, $c$는 양수이다.) [4.2점]",
    "choices": [
      "$ac$",
      "$\\dfrac{1}{2}ac$",
      "$ab$",
      "$\\dfrac{1}{2}ab$",
      "$\\dfrac{1}{2}bc$"
    ],
    "level": "중",
    "category": "이차방정식",
    "originalCategory": "이차방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차방정식",
    "standardUnitOrder": 5,
    "layoutTag": "grid",
    "wide": false,
    "answer": "④",
    "subUnitKey": "H15-SA-05-EQUATION_APPLICATION",
    "subUnit": "이차방정식의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "주어진 이차식을 $x$에 관하여 정리한다.\n$2bx+a(x^2-1)+c(x^2+1)=(a+c)x^2+2bx+(c-a)$이다.\n완전제곱식이 되려면 판별식이 $0$이어야 하므로\n$(2b)^2-4(a+c)(c-a)=0$이다.\n$4b^2-4(c^2-a^2)=0$에서\n$a^2+b^2=c^2$을 얻는다.\n$a,b,c$는 삼각형의 양의 변의 길이이므로 피타고라스 정리의 역에 따라 $c$가 빗변인 직각삼각형이다.\n따라서 서로 수직인 두 변 $a,b$를 이용한 넓이는\n$\\dfrac12\\cdot a\\cdot b=\\dfrac12ab$이다.\n따라서 정답은 ④이다.",
    "problemTypeKey": "PT_H1_EQUATION_APPLICATION",
    "templateKey": null,
    "crossConceptKeys": [
      "CC_DISCRIMINANT"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 8,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "이차방정식"
    ],
    "content": "이차방정식 $x^2-3x-3=0$의 두 근을 $\\alpha$, $\\beta$라고 할 때, $(\\alpha+1)(\\beta+1)$의 값을 구하시오. [3.7점]",
    "choices": [
      "$-1$",
      "$1$",
      "$3$",
      "$5$",
      "$7$"
    ],
    "level": "하",
    "category": "이차방정식의 근과 계수",
    "originalCategory": "이차방정식의 근과 계수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-06",
    "standardUnit": "이차방정식의 근과 계수",
    "standardUnitOrder": 6,
    "layoutTag": "grid",
    "wide": false,
    "answer": "②",
    "subUnitKey": "H15-SA-06-ROOT_COEFFICIENT_RELATION",
    "subUnit": "근과 계수의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "두 근을 직접 계산하는 대신 근과 계수의 관계를 이용한다.\n$x^2-3x-3=0$에서 $\\alpha+\\beta=3$, $\\alpha\\beta=-3$이다.\n따라서\n$(\\alpha+1)(\\beta+1)=\\alpha\\beta+(\\alpha+\\beta)+1$\n$=-3+3+1=1$이다.\n따라서 정답은 ②이다.",
    "problemTypeKey": "PT_H1_ROOT_COEFFICIENT_RELATION",
    "templateKey": "TPL_H1_VIETA_SYMMETRIC_VALUE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 9,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "이차방정식"
    ],
    "content": "이차방정식 $x^2-3x+2k-1=0$이 서로 다른 두 실근을 갖도록 하는 자연수 $k$의 개수를 $M$, 이차방정식 $3x^2-x+k+5=0$이 서로 다른 두 허근을 갖도록 하는 정수 $k$의 최솟값을 $m$이라 할 때, $Mm$의 값은? [4.9점]",
    "choices": [
      "$-1$",
      "$-2$",
      "$-3$",
      "$-4$",
      "$-5$"
    ],
    "level": "중",
    "category": "이차방정식",
    "originalCategory": "이차방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차방정식",
    "standardUnitOrder": 5,
    "layoutTag": "grid",
    "wide": false,
    "answer": "④",
    "subUnitKey": "H15-SA-05-EQUATION_APPLICATION",
    "subUnit": "이차방정식의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "첫째 방정식이 서로 다른 두 실근을 갖는 조건은 판별식이 양수인 것이다.\n$D_1=(-3)^2-4(2k-1)=9-8k+4=13-8k$이므로\n$13-8k>0$, 곧 $k<\\dfrac{13}{8}$이다.\n수정된 조건에서 $k$는 자연수이므로 가능한 값은 $k=1$ 하나뿐이다. 따라서 $M=1$이다.\n둘째 방정식이 서로 다른 두 허근을 갖는 조건은 판별식이 음수인 것이다.\n$D_2=(-1)^2-4\\cdot3(k+5)=1-12k-60=-12k-59$이므로\n$-12k-59<0$, 곧 $k>-\\dfrac{59}{12}$이다.\n이를 만족하는 정수의 최솟값은 $m=-4$이다.\n따라서 $Mm=1\\cdot(-4)=-4$이다.\n따라서 정답은 ④이다.",
    "problemTypeKey": "PT_H1_EQUATION_APPLICATION",
    "templateKey": null,
    "crossConceptKeys": [
      "CC_DISCRIMINANT"
    ],
    "conditionKeys": [
      "COND_NATURAL_NUMBER",
      "COND_INTEGER"
    ],
    "integrationPattern": "CASE_BRANCH",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 10,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "이차방정식"
    ],
    "content": "이차방정식 $x^2+ax+14=0$의 두 근의 차가 $5$이고 두 근이 모두 음수일 때, 실수 $a$의 값을 구하시오. [4.1점]",
    "choices": [
      "$5$",
      "$6$",
      "$7$",
      "$8$",
      "$9$"
    ],
    "level": "중",
    "category": "이차방정식의 근과 계수",
    "originalCategory": "이차방정식의 근과 계수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-06",
    "standardUnit": "이차방정식의 근과 계수",
    "standardUnitOrder": 6,
    "layoutTag": "grid",
    "wide": false,
    "answer": "⑤",
    "subUnitKey": "H15-SA-06-ROOT_COEFFICIENT_RELATION",
    "subUnit": "근과 계수의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "이차방정식의 두 근을 $\\alpha,\\beta$라 하자.\n근과 계수의 관계에 의해 $\\alpha\\beta=14$, $\\alpha+\\beta=-a$이다.\n두 근의 차의 절댓값이 $5$이므로\n$(\\alpha-\\beta)^2=25$이다.\n$(\\alpha+\\beta)^2-4\\alpha\\beta=25$에서\n$(-a)^2-4\\cdot14=25$이므로\n$a^2=81$, $a=9$ 또는 $a=-9$이다.\n두 근이 모두 음수이므로 그 합도 음수이다.\n$\\alpha+\\beta=-a<0$에서 $a>0$이므로 $a=9$이다.\n따라서 정답은 ⑤이다.",
    "problemTypeKey": "PT_H1_ROOT_COEFFICIENT_RELATION",
    "templateKey": "TPL_H1_VIETA_SYMMETRIC_VALUE",
    "crossConceptKeys": [
      "CC_DISCRIMINANT"
    ],
    "conditionKeys": [
      "COND_NEGATIVE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 11,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "이차함수"
    ],
    "content": "이차함수 $y=x^2+2x+k$의 그래프가 $x$축과 만나도록 하는 상수 $k$값의 범위를 구하시오. [3.4점]",
    "choices": [
      "$k\\le2$",
      "$k<2$",
      "$k\\le1$",
      "$k<1$",
      "$k\\le-1$"
    ],
    "level": "하",
    "category": "이차함수",
    "originalCategory": "이차함수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차함수",
    "standardUnitOrder": 5,
    "layoutTag": "grid",
    "wide": false,
    "answer": "③",
    "subUnitKey": "H15-SA-05-EQUATION_APPLICATION",
    "subUnit": "이차함수와 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "이차함수의 그래프가 $x$축과 만나려면 대응하는 이차방정식이 실근을 가져야 한다.\n$x^2+2x+k=0$의 판별식은\n$D=2^2-4\\cdot1\\cdot k=4-4k$이다.\n$x$축과 접하는 경우도 포함되므로 $D\\ge0$이다.\n$4-4k\\ge0$에서 $k\\le1$이다.\n따라서 정답은 ③이다.",
    "problemTypeKey": "PT_H1_EQUATION_APPLICATION",
    "templateKey": null,
    "crossConceptKeys": [
      "CC_DISCRIMINANT"
    ],
    "conditionKeys": [
      "COND_RANGE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 12,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "삼각형"
    ],
    "content": "삼각형의 세 변의 길이가 $a$, $b$, $c$일 때, $(b-c)a^2+(2b^2-bc-c^2)a+b^3-bc^2=0$이 성립한다. 이 삼각형은 어떤 삼각형인가? [4.4점]",
    "choices": [
      "$b=c$인 이등변삼각형",
      "$a=b$인 이등변삼각형",
      "정삼각형",
      "빗변의 길이가 $a$인 직각삼각형",
      "빗변의 길이가 $b$인 직각삼각형"
    ],
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "layoutTag": "grid",
    "wide": false,
    "answer": "①",
    "subUnitKey": "H15-SA-03-FACTORIZATION",
    "subUnit": "인수분해",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "주어진 세 변의 관계식을 인수분해한다.\n$(b-c)a^2+(2b^2-bc-c^2)a+b^3-bc^2$\n$=(b-c)\\{a^2+(2b+c)a+b(b+c)\\}$\n$=(b-c)(a+b)(a+b+c)$이다.\n세 변의 길이는 모두 양수이므로\n$a+b>0$, $a+b+c>0$이다.\n따라서 위 곱이 $0$이 되려면 $b-c=0$, 즉 $b=c$여야 한다.\n두 변 $b,c$가 같은 이등변삼각형이므로 정답은 ①이다.",
    "problemTypeKey": "PT_H1_POLY_FACTORIZATION",
    "templateKey": "TPL_H1_FACTORIZATION_APPLICATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 13,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "이차함수",
      "좌표평면"
    ],
    "content": "유리수 $a$, $b$, $c$에 대하여 이차함수 $y=x^2+ax$의 그래프와 직선 $y=bx-c$가 만나는 두 점을 $P$, $Q$라 하자. 직선 $y=bx-c$가 두 점 $(0,-2)$, $(1,0)$을 지나고, 점 $P$, $Q$의 $x$좌표의 합이 $3$일 때, $a+b+c$의 값은? [4.2점]",
    "choices": [
      "$-9$",
      "$-6$",
      "$3$",
      "$9$",
      "$12$"
    ],
    "level": "중",
    "category": "이차방정식의 근과 계수",
    "originalCategory": "이차방정식의 근과 계수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-06",
    "standardUnit": "이차방정식의 근과 계수",
    "standardUnitOrder": 6,
    "layoutTag": "grid",
    "wide": false,
    "answer": "③",
    "subUnitKey": "H15-SA-06-ROOT_COEFFICIENT_RELATION",
    "subUnit": "근과 계수의 관계",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "두 그래프의 교점에서는 $x^2+ax=bx-c$가 성립하므로\n$x^2+(a-b)x+c=0$이다.\n두 교점의 $x$좌표를 근이라고 하면 근과 계수의 관계에 의해\n$x_P+x_Q=b-a$이다.\n수정된 조건에서 직선 $y=bx-c$는 $(0,-2)$와 $(1,0)$을 지나므로\n$(0,-2)$를 대입하면 $-c=-2$, 즉 $c=2$이다.\n$(1,0)$을 대입하면 $b-c=0$이므로 $b=2$이다.\n또 두 교점의 $x$좌표 합이 $3$이므로\n$b-a=3$, $2-a=3$, 따라서 $a=-1$이다.\n그래서 $a+b+c=-1+2+2=3$이다.\n실제로 이때 교점 방정식은 $x^2-3x+2=(x-1)(x-2)=0$으로 서로 다른 두 교점이 존재한다.\n따라서 정답은 ③이다.",
    "problemTypeKey": "PT_H1_ROOT_COEFFICIENT_RELATION",
    "templateKey": "TPL_H1_VIETA_SYMMETRIC_VALUE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 14,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "최적화"
    ],
    "content": "길이가 $10$ cm인 막대 $10$개를 빈틈없이 연결하여 만들 수 있는 직사각형의 최대 넓이를 구하시오. (단, 막대의 모양은 변형할 수 없고, 막대의 두께는 생각하지 않는다.) [4.1점]",
    "choices": [
      "$700$",
      "$675$",
      "$650$",
      "$625$",
      "$600$"
    ],
    "level": "중",
    "category": "이차함수",
    "originalCategory": "이차함수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차함수",
    "standardUnitOrder": 5,
    "layoutTag": "grid",
    "wide": false,
    "answer": "⑤",
    "subUnitKey": "H15-SA-05-EQUATION_APPLICATION",
    "subUnit": "이차함수의 최대최소",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "막대는 길이 $10\\,\\mathrm{cm}$이고 구부릴 수 없으므로 직사각형의 각 변은 $10\\,\\mathrm{cm}$의 정수배로 이루어진다.\n가로에 $m$개, 세로에 $n$개씩 사용하면 둘레의 막대 수는\n$2m+2n=10$, 즉 $m+n=5$이다.\n넓이는 $(10m)(10n)=100mn$이다.\n양의 정수 $m,n$에서 합이 $5$로 일정할 때 곱을 비교하면\n$(m,n)=(1,4)$이면 $mn=4$,\n$(m,n)=(2,3)$이면 $mn=6$이다.\n따라서 최대 넓이는 $100\\cdot6=600\\,\\mathrm{cm}^2$이다.\n따라서 정답은 ⑤이다.",
    "problemTypeKey": "PT_H1_EQUATION_APPLICATION",
    "templateKey": null,
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "CASE_BRANCH",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 15,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "복소수"
    ],
    "content": "방정식 $x^2+x+1=0$의 한 허근을 $\\omega$라 할 때, $1+2\\omega+3\\omega^2+4\\omega^3+5\\omega^4+6\\omega^5+7\\omega^6=a+b\\omega$를 만족시키는 두 실수 $a$, $b$에 대하여 $a+b$의 값을 구하시오. [4.9점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "level": "중",
    "category": "복소수",
    "originalCategory": "복소수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "layoutTag": "grid",
    "wide": false,
    "answer": "①",
    "subUnitKey": "H15-SA-04-COMPLEX_OPERATION",
    "subUnit": "복소수의 연산",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "$\\omega$는 $x^2+x+1=0$의 허근이므로\n$\\omega^2+\\omega+1=0$, 즉 $\\omega^2=-1-\\omega$이다.\n또 $(\\omega-1)(\\omega^2+\\omega+1)=\\omega^3-1=0$이고 $\\omega\\ne1$이므로 $\\omega^3=1$이다.\n따라서 $\\omega^4=\\omega$, $\\omega^5=\\omega^2$, $\\omega^6=1$이다.\n원래 합을 같은 거듭제곱끼리 모으면\n$1+2\\omega+3\\omega^2+4\\omega^3+5\\omega^4+6\\omega^5+7\\omega^6$\n$=(1+4+7)+(2+5)\\omega+(3+6)\\omega^2$\n$=12+7\\omega+9\\omega^2$\n$=12+7\\omega+9(-1-\\omega)$\n$=3-2\\omega$이다.\n따라서 $a=3$, $b=-2$이므로 $a+b=1$이다.\n따라서 정답은 ①이다.",
    "problemTypeKey": "PT_H1_COMPLEX_POWER_ROOT",
    "templateKey": "TPL_H1_COMPLEX_I_PERIOD",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 16,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "이차함수"
    ],
    "content": "$-1\\le x\\le4$일 때, 이차함수 $f(x)=-x^2+4x+k$의 최댓값과 최솟값의 합이 $11$이다. 이때 실수 $k$의 값을 구하시오. [3.7점]",
    "choices": [
      "$2$",
      "$4$",
      "$6$",
      "$8$",
      "$10$"
    ],
    "level": "중",
    "category": "이차함수",
    "originalCategory": "이차함수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차함수",
    "standardUnitOrder": 5,
    "layoutTag": "grid",
    "wide": false,
    "answer": "③",
    "subUnitKey": "H15-SA-05-EQUATION_APPLICATION",
    "subUnit": "이차함수의 최대최소",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "이차함수를 완전제곱식으로 나타낸다.\n$f(x)=-x^2+4x+k=-(x-2)^2+k+4$이다.\n아래로 열린 포물선이고 꼭짓점 $x=2$가 구간 $-1\\le x\\le4$ 안에 있다.\n따라서 최댓값은 $f(2)=k+4$이다.\n최솟값은 양 끝점을 비교하여 정한다.\n$f(-1)=-1-4+k=k-5$,\n$f(4)=-16+16+k=k$이다.\n그러므로 최솟값은 $k-5$이다.\n두 값의 합이 $11$이므로\n$(k+4)+(k-5)=11$,\n$2k-1=11$, $2k=12$, $k=6$이다.\n따라서 정답은 ③이다.",
    "problemTypeKey": "PT_H1_EQUATION_APPLICATION",
    "templateKey": null,
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_RANGE"
    ],
    "integrationPattern": "CASE_BRANCH",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 17,
    "questionType": "객관식",
    "tags": [
      "객관식",
      "사차방정식"
    ],
    "content": "사차방정식 $x^4-2x^2+16x-15=0$은 두 개의 실근과 두 개의 허근을 갖는다. 두 실근의 합을 $a$, 두 허근의 곱을 $b$라 할 때, $a+b$의 값을 구하시오. [4.3점]",
    "choices": [
      "$3$",
      "$5$",
      "$7$",
      "$9$",
      "$11$"
    ],
    "level": "중",
    "category": "여러 가지 방정식",
    "originalCategory": "여러 가지 방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-07",
    "standardUnit": "여러 가지 방정식",
    "standardUnitOrder": 7,
    "layoutTag": "grid",
    "wide": false,
    "answer": "①",
    "subUnitKey": "H15-SA-07-HIGHER_EQUATION",
    "subUnit": "고차방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "실근 두 개와 허근 두 개를 찾기 위해 사차식을 인수분해한다.\n$x^4-2x^2+16x-15$\n$=(x-1)(x+3)(x^2-2x+5)$이다.\n따라서 실근은 $1$과 $-3$이므로 합은\n$a=1+(-3)=-2$이다.\n남은 이차방정식 $x^2-2x+5=0$의 판별식은\n$D=(-2)^2-4\\cdot1\\cdot5=4-20=-16<0$이므로 서로 다른 두 허근을 갖는다.\n근과 계수의 관계에 의해 두 허근의 곱은 $b=5$이다.\n따라서 $a+b=-2+5=3$이다.\n따라서 정답은 ①이다.",
    "problemTypeKey": "PT_H1_EQUATION_APPLICATION",
    "templateKey": null,
    "crossConceptKeys": [
      "CC_ROOTS_COEFFICIENTS"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 18,
    "questionType": "단답형",
    "tags": [
      "단답형",
      "복소수"
    ],
    "content": "$\\left(\\dfrac{1+i}{1-i}\\right)^{2021}$을 간단히 하시오. [4점]",
    "level": "하",
    "category": "복소수",
    "originalCategory": "복소수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "layoutTag": "grid",
    "wide": false,
    "answer": "i",
    "subUnitKey": "H15-SA-04-COMPLEX_OPERATION",
    "subUnit": "복소수의 연산",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "분수의 분모를 유리화한다.\n$\\dfrac{1+i}{1-i}=\\dfrac{(1+i)^2}{(1-i)(1+i)}$\n$=\\dfrac{1+2i+i^2}{1-i^2}$\n$=\\dfrac{2i}{2}=i$이다.\n따라서 주어진 식은 $i^{2021}$이다.\n$i^4=1$이고 $2021=4\\cdot505+1$이므로\n$i^{2021}=(i^4)^{505}\\cdot i=i$이다.\n정답은 $i$이다.",
    "problemTypeKey": "PT_H1_COMPLEX_POWER_ROOT",
    "templateKey": "TPL_H1_COMPLEX_I_PERIOD",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 19,
    "questionType": "단답형",
    "tags": [
      "단답형",
      "다항식"
    ],
    "content": "$\\dfrac{(2023+\\sqrt{2021})^3+(2023-\\sqrt{2021})^3}{2023}$의 값을 $N$이라 할 때, 자연수 $N$의 일의 자리 숫자를 구하시오. [4점]",
    "level": "중",
    "category": "다항식의 연산",
    "originalCategory": "다항식의 연산",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-01",
    "standardUnit": "다항식의 연산",
    "standardUnitOrder": 1,
    "layoutTag": "grid",
    "wide": false,
    "answer": "4",
    "subUnitKey": "H15-SA-01-POLYNOMIAL_BASIC",
    "subUnit": "다항식의 연산",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "세제곱 합에서 무리수항이 서로 소거되는 것을 이용한다.\n$a=2023$, $b=\\sqrt{2021}$로 놓으면\n$(a+b)^3+(a-b)^3$\n$=(a^3+3a^2b+3ab^2+b^3)+(a^3-3a^2b+3ab^2-b^3)$\n$=2a^3+6ab^2$이다.\n따라서 문제의 수 $N$은\n$N=\\dfrac{2a^3+6ab^2}{a}=2a^2+6b^2$\n$=2\\cdot2023^2+6\\cdot2021$이다.\n일의 자리만 보면 $2023^2$의 일의 자리는 $3^2=9$이고, $2021$의 일의 자리는 $1$이다.\n따라서 $N$의 일의 자리는 $(2\\cdot9+6\\cdot1)$의 일의 자리와 같은 $4$이다.\n정답은 $4$이다.",
    "problemTypeKey": "PT_H1_POLY_OPERATION_EXPANSION",
    "templateKey": "TPL_H1_POLY_OPERATION_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 20,
    "questionType": "서술형",
    "tags": [
      "서술형",
      "무리수"
    ],
    "content": "$x=2+\\sqrt{3}$, $y=2-\\sqrt{3}$일 때, 다음 식의 값을 구하고 풀이 과정을 자세히 서술하시오. (1) $x^2+y^2$ (2) $x^3+y^3$ [7점]",
    "level": "하",
    "category": "다항식의 연산",
    "originalCategory": "다항식의 연산",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-01",
    "standardUnit": "다항식의 연산",
    "standardUnitOrder": 1,
    "layoutTag": "grid",
    "wide": false,
    "answer": "(1) 14, (2) 52",
    "subUnitKey": "H15-SA-01-POLYNOMIAL_BASIC",
    "subUnit": "다항식의 연산",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "먼저 두 수의 합과 곱을 구해 여러 거듭제곱 식을 계산한다.\n$x+y=(2+\\sqrt3)+(2-\\sqrt3)=4$이고\n$xy=(2+\\sqrt3)(2-\\sqrt3)=4-3=1$이다.\n(1) 제곱의 합은 $(x+y)^2-2xy$로 계산한다.\n$x^2+y^2=(x+y)^2-2xy$\n$=4^2-2\\cdot1=16-2=14$이다.\n(2) 세제곱의 합은 $(x+y)^3-3xy(x+y)$를 이용한다.\n$x^3+y^3=(x+y)^3-3xy(x+y)$\n$=4^3-3\\cdot1\\cdot4=64-12=52$이다.\n따라서 (1) $14$, (2) $52$이다.",
    "problemTypeKey": "PT_H1_POLY_OPERATION_EXPANSION",
    "templateKey": "TPL_H1_POLY_OPERATION_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 21,
    "questionType": "서술형",
    "tags": [
      "서술형",
      "복소수",
      "이차방정식"
    ],
    "content": "복소수 $z=(n-2+2i)^2$에 대하여 $z^2$이 음의 실수가 된다. 실수 $a$, $b$에 대하여 이차방정식 $x^2+ax+b=0$은 $z$를 한 근으로 갖는다고 하자. $a$, $b$의 값을 구하시오. (단, $n$은 자연수이다.) [7점]",
    "level": "상",
    "category": "복소수",
    "originalCategory": "복소수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "layoutTag": "grid",
    "wide": false,
    "answer": "a=0, b=64",
    "subUnitKey": "H15-SA-04-COMPLEX_OPERATION",
    "subUnit": "복소수의 연산",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "먼저 $z=(n-2+2i)^2$를 실수부분과 허수부분으로 나눈다.\n$z=(n-2)^2+4(n-2)i+(2i)^2$\n$=((n-2)^2-4)+4(n-2)i$이다.\n복소수 $z=u+vi$라 하면 $z^2=(u^2-v^2)+2uv i$이다.\n$z^2$이 음의 실수이므로 $2uv=0$이고 $u^2-v^2<0$이다.\n$u=0$이면 $z^2=-v^2<0$이 가능하지만 $v=0$이면 $z^2=u^2\\ge0$이므로 불가능하다.\n따라서 $u=(n-2)^2-4=0$이고 $v\\ne0$이다.\n$(n-2)^2=4$에서 $n-2=2$ 또는 $-2$이므로 $n=4$ 또는 $0$이다.\n$n$은 자연수이므로 $n=4$이다.\n따라서 $z=(2+2i)^2=8i$이다.\n실수 계수의 이차방정식이 $8i$를 근으로 가지면 켤레근 $-8i$도 근이다.\n그러므로 $(x-8i)(x+8i)=x^2+64=0$이다.\n주어진 $x^2+ax+b=0$과 비교하면 $a=0$, $b=64$이다.",
    "problemTypeKey": "PT_H1_COMPLEX_OPERATION",
    "templateKey": "TPL_H1_COMPLEX_CONJUGATE_NORM",
    "crossConceptKeys": [
      "CC_ROOTS_COEFFICIENTS"
    ],
    "conditionKeys": [
      "COND_NATURAL_NUMBER",
      "COND_NEGATIVE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 5,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  },
  {
    "id": 22,
    "questionType": "서술형",
    "tags": [
      "서술형",
      "이차함수",
      "좌표평면"
    ],
    "content": "오른쪽 그림과 같이 이차함수 $y=2x^2+8x+6$의 그래프가 $x$축과 만나는 두 점을 $A$, $B$, $y$축과 만나는 점을 $C$라 하자. 점 $P(x,y)$가 점 $A$에서 $C$까지 그래프 위를 움직일 때, $-4x+y+3$의 최댓값과 최솟값의 합을 구하시오. (단, 점 $A$의 $x$좌표는 점 $B$의 $x$좌표보다 작다.) [7점]",
    "image": "assets/images/21_매산여고_1학기_중간_고1_기출/q22.png",
    "level": "중",
    "category": "이차함수",
    "originalCategory": "이차함수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차함수",
    "standardUnitOrder": 5,
    "layoutTag": "grid",
    "wide": false,
    "answer": "22",
    "subUnitKey": "H15-SA-05-EQUATION_APPLICATION",
    "subUnit": "이차함수의 최대최소",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "solution": "먼저 그래프에서 점 $P$가 움직이는 $x$의 범위를 구한다.\n$y=2x^2+8x+6=2(x+1)(x+3)$이므로 $x$축과의 교점은 $x=-3,-1$이다.\n$A$가 왼쪽 교점이므로 $A=(-3,0)$이고, $y$축과의 교점은 $C=(0,6)$이다.\n따라서 $P$가 $A$에서 $C$까지 그래프 위를 움직일 때 $-3\\le x\\le0$이다.\n구할 식에 그래프의 방정식 $y=2x^2+8x+6$을 대입한다.\n$-4x+y+3=-4x+(2x^2+8x+6)+3$\n$=2x^2+4x+9=2(x+1)^2+7$이다.\n위로 열린 포물선의 꼭짓점은 $x=-1$이며 이 점이 구간 안에 있다.\n따라서 최솟값은 $2(-1+1)^2+7=7$이다.\n최댓값은 양 끝점의 값을 비교한다.\n$x=-3$이면 $2(-2)^2+7=15$,\n$x=0$이면 $2(1)^2+7=9$이다.\n따라서 최댓값은 $15$이고, 구하는 합은 $15+7=22$이다.",
    "problemTypeKey": "PT_H1_EQUATION_APPLICATION",
    "templateKey": null,
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_RANGE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL"
  }
];