window.examTitle = "25_강남여고_1학기_기말_고1_유사2";

window.questionBank = [
  {
    id: 1,
    level: "중상",
    category: "다항식의 연산",
    originalCategory: "다항식의 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-01",
    standardUnit: "다항식의 연산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(x+y+z)(a+b+c)-(x+y)(a+b)$를 전개하여 동류항을 정리했을 때, 생겨나는 서로 다른 항의 개수는? (단, $x, y, z, a, b, c$는 모두 서로 다른 문자이다.)",
    choices: ["3", "4", "5", "6", "7"],
    answer: "③",
    solution: ""
  },
  {
    id: 2,
    level: "중상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "1학년 학생 2명, 2학년 학생 3명, 3학년 학생 4명 중에서 학년에 관계없이 회장 1명, 부회장 1명, 서기 1명을 뽑는 경우의 수를 $a$, 3학년 학생 중에서만 회장, 부회장, 서기를 뽑는 경우의 수를 $b$라 할 때, $a-b$의 값은?",
    choices: ["420", "450", "480", "510", "540"],
    answer: "③",
    solution: ""
  },
  {
    id: 3,
    level: "중상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "자연수 $n$에 대하여 ${}_nP_3=4 \\times {}_nC_4$가 성립할 때, $n$의 값은?",
    choices: ["7", "8", "9", "10", "11"],
    answer: "③",
    solution: ""
  },
  {
    id: 4,
    level: "중상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "부등식 $x-a<3x+1 \\le x+5$를 만족시키는 정수 $x$의 개수가 3개가 되도록 하는 모든 정수 $a$의 값의 합은?",
    choices: ["1", "2", "3", "4", "5"],
    answer: "①",
    solution: ""
  },
  {
    id: 5,
    level: "중상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $y = x^2 - 2ax + 3a^2 - 8a + 15$의 최솟값을 $m$이라 할 때, $m$이 가질 수 있는 최솟값은? (단, $a$는 실수이다.)",
    choices: ["3", "5", "7", "9", "11"],
    answer: "③",
    solution: ""
  },
  {
    id: 6,
    level: "중상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "부등식 $|x-a| < 2x-4$를 만족시키는 정수 $x$의 최솟값이 5가 되도록 하는 모든 정수 $a$의 값의 합은?",
    choices: ["24", "25", "26", "27", "28"],
    answer: "④",
    solution: ""
  },
  {
    id: 7,
    level: "중상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 행렬 $A=\\begin{pmatrix} 4 & 5 \\\\ 2 & 1 \\end{pmatrix}, B=\\begin{pmatrix} 1 & 2 \\\\ 5 & -2 \\end{pmatrix}$에 대하여 연립방정식 $\\begin{cases} X + Y = A \\\\ X - 2Y = B \\end{cases}$ 를 만족시키는 행렬 $X$의 모든 성분의 합은?",
    choices: ["8", "9", "10", "11", "12"],
    answer: "③",
    solution: ""
  },
  {
    id: 8,
    level: "중상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차항의 계수가 1인 이차함수 $f(x)$에 대하여 부등식 $f(x) \\le 0$의 해가 $-2 \\le x \\le 4$이다. 부등식 $f(\\frac{x-1}{2}) \\le 0$을 만족시키는 정수 $x$의 최댓값과 최솟값의 합은?",
    choices: ["4", "5", "6", "7", "8"],
    answer: "③",
    solution: ""
  },
  {
    id: 9,
    level: "중상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $y=f(x)$의 꼭짓점의 좌표가 $(3, -4)$이고, 이차방정식 $f(x)=0$의 두 실근 $\\alpha, \\beta$에 대하여 $|\\alpha-\\beta|=4$일 때, $f(0)$의 값은?",
    choices: ["3", "4", "5", "6", "7"],
    answer: "③",
    solution: ""
  },
  {
    id: 10,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x, y$에 관한 연립방정식 $\\begin{cases}2x+y=k\\\\x^2+y^2-4x=0\\end{cases}$이 서로 다른 두 쌍의 실근을 갖도록 하는 정수 $k$의 최댓값은?",
    choices: ["6", "7", "8", "9", "10"],
    answer: "③",
    solution: ""
  },
  {
    id: 11,
    level: "상",
    category: "합의 법칙과 곱의 법칙",
    originalCategory: "합의 법칙과 곱의 법칙",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-07",
    standardUnit: "합의 법칙과 곱의 법칙",
    standardUnitOrder: 7,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "그림과 같이 네 지점 A, B, C, D를 연결하는 도로망이 있다. A지점에서 B지점으로 가는 도로는 3개, A지점에서 C지점으로 가는 도로는 2개, B지점에서 D지점으로 가는 도로는 3개, C지점에서 D지점으로 가는 도로는 4개이다. B지점과 C지점을 연결하는 도로를 $x$개 추가하였더니, A지점에서 출발하여 B지점과 C지점을 모두 거쳐 D지점으로 가는 경우의 수가 72가 되었다. 이때 추가된 도로를 포함하여 A지점에서 출발해 D지점으로 가는 전체 경우의 수는? (단, 한 번 지나간 지점은 다시 지나지 않고, 도로는 양방향 통행이 가능하다.)",
    choices: ["85", "87", "89", "91", "93"],
    answer: "③",
    solution: ""
  },
  {
    id: 12,
    level: "상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차 정사각행렬 $A, B$의 $(i, j)$성분을 각각 $a_{ij}=i^2+kj$, $b_{ij}=k \\times a_{ji}$ (단, $k$는 상수)로 정의하자. 행렬 $A+B$의 모든 성분의 합이 112일 때, 양수 $k$의 값은?",
    choices: ["1", "2", "3", "4", "5"],
    answer: "③",
    solution: ""
  },
  {
    id: 13,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a \\le x \\le a+2$에서 이차함수 $y=x^2-2x$의 최댓값과 최솟값의 합이 8이 되도록 하는 모든 실수 $a$의 값의 곱은?",
    choices: ["-6", "-4", "-2", "0", "2"],
    answer: "②",
    solution: ""
  },
  {
    id: 14,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "연립방정식 $\\begin{cases} x^2+y^2=10 \\\\ x+y-xy=5 \\end{cases}$ 를 만족시키는 실수 $x, y$에 대하여 $x^3+y^3$이 가질 수 있는 최댓값은?",
    choices: ["18", "22", "26", "30", "34"],
    answer: "③",
    solution: ""
  },
  {
    id: 15,
    level: "상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "8개의 숫자 1, 2, 3, 4, 5, 6, 7, 8에서 서로 다른 4개의 숫자를 택하여 만든 네 자리의 자연수 중에서, 홀수 번째 자리(첫 번째, 세 번째) 숫자의 합과 짝수 번째 자리(두 번째, 네 번째) 숫자의 합이 모두 짝수인 자연수의 개수는?",
    choices: ["288", "312", "336", "360", "384"],
    answer: "③",
    solution: ""
  },
  {
    id: 16,
    level: "상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차 정사각행렬 $A$에 대하여 $A^2-A+E=O$가 성립한다. 두 행렬 $X = A + A^2 + A^3 + \\dots + A^{20}$, $Y = A^2 + A^4 + A^6 + \\dots + A^{20}$이라 할 때, $X-Y = pA+qE$이다. 두 상수 $p, q$에 대하여 $p^2+q^2$의 값은? (단, $E$는 단위행렬, $O$는 영행렬이다.)",
    choices: ["1", "2", "3", "4", "5"],
    answer: "①",
    solution: ""
  },
  {
    id: 17,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차항의 계수가 1인 이차식 $f(x)$에 대하여 부등식 $|x-k| + |x-3k| \\le 8$의 해가 부등식 $f(x) \\le 0$의 해와 일치한다. 방정식 $f(x)=0$의 두 근의 곱이 $-12$일 때, 양수 $k$의 값은?",
    choices: ["1", "2", "3", "4", "5"],
    answer: "①",
    solution: ""
  },
  {
    id: 18,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $f(x)=x^2-6x$의 그래프와 직선 $y=mx+n$이 만나는 두 점을 A, B라 하자. 점 A를 지나고 $x$축에 평행한 직선이 $y=f(x)$의 그래프와 만나는 점 중 A가 아닌 점을 C, 점 B를 지나고 $x$축에 평행한 직선이 $y=f(x)$의 그래프와 만나는 점 중 B가 아닌 점을 D라 할 때, 삼각형 ABD의 넓이와 삼각형 ABC의 넓이의 비는 1:2이다. 점 A의 $x$좌표가 1일 때, $m+n$의 값은? (단, 점 A의 $x$좌표는 점 B의 $x$좌표보다 작고, $m, n$은 상수이다.)",
    choices: ["-7", "-6", "-5", "-4", "-3"],
    answer: "③",
    solution: ""
  },
  {
    id: 19,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 연립부등식 $\\begin{cases} |x-3| \\le 7 \\\\ x^2 - 3ax + 2a^2 < 0 \\end{cases}$ 을 만족시키는 정수 $x$의 개수가 4개가 되도록 하는 모든 정수 $a$의 값의 합은?",
    choices: ["9", "11", "13", "15", "17"],
    answer: "②",
    solution: ""
  },
  {
    id: 20,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차항의 계수가 -1인 이차함수 $f(x)$의 그래프가 원점을 지나고, 직선 $y=2x$와 만나는 두 점 중 원점이 아닌 점을 A라 하자. 원점 O와 점 A 사이의 실수 $t$ ($0 < t < x_A$)에 대하여 직선 $x=t$가 이차함수 $y=f(x)$의 그래프, 직선 $y=2x$와 만나는 점을 각각 P, Q라 하자. 선분 PQ의 길이의 최댓값이 4일 때, 삼각형 OAP의 넓이의 최댓값은? (단, 점 A의 $x$좌표는 양수이다.)",
    choices: ["4", "6", "8", "10", "12"],
    answer: "③",
    solution: ""
  },
  {
    id: 21,
    level: "상",
    category: "항등식과 나머지 정리",
    originalCategory: "항등식과 나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "항등식과 나머지 정리",
    standardUnitOrder: 2,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "최고차항의 계수가 1인 삼차다항식 $P(x)$가 $P(1)=2$, $P(2)=4$, $P(3)=6$을 만족시킬 때, 방정식 $P(x)=0$의 세 근의 곱을 구하시오.",
    choices: [],
    answer: "6",
    solution: ""
  },
  {
    id: 22,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "연립부등식 $\\begin{cases} x^2 - (k-2)x - 2k < 0 \\\\ x^2 - 4x - 12 \\ge 0 \\end{cases}$ 를 만족시키는 정수 $x$의 개수가 3개가 되도록 하는 모든 정수 $k$의 값의 합을 구하시오.",
    choices: [],
    answer: "3",
    solution: ""
  },
  {
    id: 23,
    level: "상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "어느 디저트 가게에서 빵 4종류, 음료 3종류, 샐러드 3종류를 판매한다. 이 10종류의 메뉴 중에서 빵 2종류, 음료 1종류, 샐러드 1종류를 선택하여 세트 메뉴를 구성하는 방법의 수를 $p$라 하자. 10종류의 메뉴 중 5종류를 선택할 때, 빵, 음료, 샐러드가 각각 적어도 1종류 이상 포함되도록 선택하는 방법의 수를 $q$라 할 때, $p+q$의 값을 구하시오. (단, 같은 종류의 메뉴는 중복해서 선택하지 않는다.)",
    choices: [],
    answer: "258",
    solution: ""
  },
  {
    id: 24,
    level: "상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "이차정사각행렬 $A$가 $A^2 - A + E = O$를 만족시킨다. $A \\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix} = \\begin{pmatrix} 4 \\\\ -3 \\end{pmatrix}$일 때, $(A^{10} + A^5 + E) \\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix} = \\begin{pmatrix} x \\\\ y \\end{pmatrix}$이다. $x+y$의 값을 구하시오. (단, $E$는 단위행렬, $O$는 영행렬이다.)",
    choices: [],
    answer: "4",
    solution: ""
  }
];