window.examTitle = "25_강남여고_1학기_기말_고1_유사1";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "다항식의 연산",
    originalCategory: "다항식의 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-01",
    standardUnit: "다항식의 연산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(x+y)(a+b+c+d)$를 전개할 때, 생성되는 항의 개수는?",
    choices: ["6", "8", "10", "12", "16"],
    answer: "②",
    solution: ""
  },
  {
    id: 2,
    level: "중",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "6명의 육상 선수 중에서 4명을 뽑아 일렬로 세우는 경우의 수는?",
    choices: ["120", "240", "360", "480", "720"],
    answer: "③",
    solution: ""
  },
  {
    id: 3,
    level: "중",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "${}_6C_3+{}_4P_2$의 값을 구하면?",
    choices: ["24", "28", "32", "36", "40"],
    answer: "③",
    solution: ""
  },
  {
    id: 4,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "부등식 $2x-1<x+5 \\le 3x-3$의 해가 $a \\le x<b$일 때, $a+b$의 값은?",
    choices: ["8", "9", "10", "11", "12"],
    answer: "③",
    solution: ""
  },
  {
    id: 5,
    level: "중",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $y=-2x^2+8x-3$의 최댓값은?",
    choices: ["3", "4", "5", "6", "7"],
    answer: "③",
    solution: ""
  },
  {
    id: 6,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "부등식 $|2x-3| < x+3$을 만족시키는 모든 정수 $x$의 개수는?",
    choices: ["3개", "4개", "5개", "6개", "7개"],
    answer: "③",
    solution: ""
  },
  {
    id: 7,
    level: "중",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 행렬 $A=\\begin{pmatrix}1&-1\\\\2&3\\end{pmatrix}$, $B=\\begin{pmatrix}3&1\\\\-2&5\\end{pmatrix}$에 대하여 $X-3A=2B$를 만족시키는 행렬 $X$의 모든 성분의 합은?",
    choices: ["25", "27", "29", "31", "33"],
    answer: "③",
    solution: ""
  },
  {
    id: 8,
    level: "중",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $f(x)=x^2-2x-15$에 대하여 부등식 $f(x-1)<0$을 만족시키는 모든 정수 $x$의 합은?",
    choices: ["10", "12", "14", "16", "18"],
    answer: "③",
    solution: ""
  },
  {
    id: 9,
    level: "중",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $y=ax^2+bx+c$의 그래프가 점 $(0, 5)$를 지나고 꼭짓점의 $x$좌표가 $2$이다. 이차방정식 $ax^2+bx+c=0$의 두 실근의 합은?",
    choices: ["2", "4", "6", "8", "10"],
    answer: "②",
    solution: ""
  },
  {
    id: 10,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x, y$에 관한 연립방정식 $\\begin{cases}x-y=a\\\\x^2+y^2=18\\end{cases}$이 오직 한 쌍의 해를 가질 때, 양수 $a$의 값은?",
    choices: ["2", "3", "4", "5", "6"],
    answer: "⑤",
    solution: ""
  },
  {
    id: 11,
    level: "중",
    category: "합의 법칙과 곱의 법칙",
    originalCategory: "합의 법칙과 곱의 법칙",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-07",
    standardUnit: "합의 법칙과 곱의 법칙",
    standardUnitOrder: 7,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "A, B, C, D 네 지점을 연결하는 도로망이 있다. A지점에서 B지점으로 가는 도로는 3개, A지점에서 C지점으로 가는 도로는 2개, B지점에서 D지점으로 가는 도로는 4개, C지점에서 D지점으로 가는 도로는 3개이다. B지점과 C지점을 연결하는 도로를 $x$개 추가하였더니 A지점에서 출발하여 B 또는 C를 거쳐 D지점으로 가는 전체 경우의 수가 120이 되었다. $x$의 값을 구하시오. (단, 한 번 지나간 지점은 다시 지나지 않고, 추가된 도로는 양방향 통행이 가능하다.)",
    choices: ["4", "5", "6", "7", "8"],
    answer: "③",
    solution: ""
  },
  {
    id: 12,
    level: "중",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차 정사각행렬 $A$의 $(i, j)$성분 $a_{ij}$를 $a_{ij}=i^2-j$로 정의할 때, $b_{ij}=a_{ji}$를 만족시키는 $b_{ij}$를 $(i, j)$성분으로 하는 행렬 $B$를 구하면?",
    choices: [
      "$\\begin{pmatrix} 0 & 3 \\\\ -1 & 2 \\end{pmatrix}$",
      "$\\begin{pmatrix} 0 & -1 \\\\ 3 & 2 \\end{pmatrix}$",
      "$\\begin{pmatrix} 0 & 2 \\\\ -1 & 3 \\end{pmatrix}$",
      "$\\begin{pmatrix} 3 & 0 \\\\ 2 & -1 \\end{pmatrix}$",
      "$\\begin{pmatrix} -1 & 2 \\\\ 0 & 3 \\end{pmatrix}$"
    ],
    answer: "①",
    solution: ""
  },
  {
    id: 13,
    level: "중",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$-1 \\le x \\le 4$에서 이차함수 $y=-x^2+6x+k$의 최댓값과 최솟값의 합이 10이 되도록 하는 상수 $k$의 값은?",
    choices: ["2", "3", "4", "5", "6"],
    answer: "③",
    solution: ""
  },
  {
    id: 14,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "연립방정식 $\\begin{cases} x+y = -3 \\\\ x^2y + xy^2 - xy = 12 \\end{cases}$ 의 해를 $x=\\alpha, y=\\beta$라 할 때, $\\alpha^2+\\beta^2$의 값은?",
    choices: ["11", "13", "15", "17", "19"],
    answer: "③",
    solution: ""
  },
  {
    id: 15,
    level: "중",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "7개의 숫자 1, 2, 3, 4, 5, 6, 7에서 서로 다른 3개의 숫자를 택하여 만든 세 자리의 자연수 중에서 각 자리의 숫자의 합이 홀수인 자연수의 개수는?",
    choices: ["72", "84", "96", "108", "120"],
    answer: "③",
    solution: ""
  },
  {
    id: 16,
    level: "중상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "행렬 $A=\\begin{pmatrix} a & 1 \\\\ -1 & 0 \\end{pmatrix}$에 대하여 $A^2+A+E=0$이 성립한다. $A^{100}=\\begin{pmatrix} p & q \\\\ r & s \\end{pmatrix}$라 할 때, $p-q+r+s$의 값은? (단, $E$는 단위행렬, $0$은 영행렬이다.)",
    choices: ["-3", "-1", "1", "3", "5"],
    answer: "①",
    solution: ""
  },
  {
    id: 17,
    level: "중상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "부등식 $|x-1| + |x+3| \\le 6$의 해와 이차부등식 $x^2+px+q \\le 0$의 해가 같을 때, $p+q$의 값은? (단, $p, q$는 상수이다.)",
    choices: ["-8", "-6", "-4", "-2", "0"],
    answer: "②",
    solution: ""
  },
  {
    id: 18,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $y=x^2-2x$의 그래프와 직선 $y=x+4$가 만나는 두 점을 A, B라 하자. (단, 점 A의 $x$좌표는 점 B의 $x$좌표보다 작다.) 점 A를 지나고 $x$축에 평행한 직선이 $y=x^2-2x$의 그래프와 만나는 점 중 A가 아닌 점을 C, 점 B를 지나고 $x$축에 평행한 직선이 $y=x^2-2x$의 그래프와 만나는 점 중 B가 아닌 점을 D라 할 때, 삼각형 ABD의 넓이를 S, 삼각형 ABC의 넓이를 T라 하자. $S:T=a:b$일 때, $a+b$의 값은? (단, $a, b$는 서로소인 자연수이다.)",
    choices: ["3", "4", "5", "6", "7"],
    answer: "③",
    solution: ""
  },
  {
    id: 19,
    level: "중상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 연립부등식 $\\begin{cases} 4x+3 \\ge 2x+7 \\\\ x-1 < -2x+k \\end{cases}$ 를 만족시키는 모든 정수 $x$의 값의 합이 14가 되도록 하는 정수 $k$의 개수는?",
    choices: ["1", "2", "3", "4", "5"],
    answer: "③",
    solution: ""
  },
  {
    id: 20,
    level: "상",
    category: "이차방정식과 이차함수",
    originalCategory: "이차방정식과 이차함수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-05",
    standardUnit: "이차방정식과 이차함수",
    standardUnitOrder: 5,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차함수 $f(x)=-x^2+6x$의 그래프와 직선 $y=2x$가 만나는 두 점 중 원점이 아닌 점을 A라 하고, 점 A의 $x$좌표를 $\\alpha$라 하자. $0 < t < \\alpha$인 실수 $t$에 대하여 직선 $x=t$가 이차함수 $y=f(x)$의 그래프, 직선 $y=2x$와 만나는 점을 각각 P, Q라 할 때, 선분 PQ의 길이의 최댓값은 $M$이다. $M+\\alpha$의 값은?",
    choices: ["4", "6", "8", "10", "12"],
    answer: "③",
    solution: ""
  },
  {
    id: 21,
    level: "중상",
    category: "항등식과 나머지 정리",
    originalCategory: "항등식과 나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "항등식과 나머지 정리",
    standardUnitOrder: 2,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "$x$의 다항식 $f(x)=x^3+ax+b$는 $x-1$로 나누어 떨어지고, $x+1$로 나누면 나머지가 12라고 한다. $a, b$의 값과 방정식 $f(x)=0$의 세 근의 곱을 구하시오.",
    choices: [],
    answer: "$a=-7,\\ b=6$, 세 근의 곱은 $-6$",
    solution: ""
  },
  {
    id: 22,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "연립부등식 $\\begin{cases} x^2+2x-8 > 0 \\\\ x^2 - (a+4)x + 4a \\le 0 \\end{cases}$ 의 해가 $2 < x \\le 4$가 되도록 하는 실수 $a$의 값의 범위와 그 범위 안에 있는 정수 $a$의 개수를 구하시오.",
    choices: [],
    answer: "$-4 \\le a \\le 2$, 7개",
    solution: ""
  },
  {
    id: 23,
    level: "중상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "어느 상점에 모자 3종류, 셔츠 4종류, 바지 5종류가 있다. 이 중에서 셔츠 2종류와 바지 2종류를 고르는 방법의 수를 $a$, 특정한 모자 1종류를 반드시 포함하여 모자 2종류, 셔츠 2종류, 바지 2종류를 고르는 방법의 수를 $b$라 할 때, $a+b$의 값을 구하시오. (단, 같은 종류의 상품은 1개씩만 고른다.)",
    choices: [],
    answer: "180",
    solution: ""
  },
  {
    id: 24,
    level: "상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "이차정사각행렬 $A$가 $A^2 - A + E = O$를 만족시키고, $A \\begin{pmatrix} -1 \\\\ 2 \\end{pmatrix} = \\begin{pmatrix} 4 \\\\ 5 \\end{pmatrix}$일 때, 행렬 $A^2 \\begin{pmatrix} 2 \\\\ -4 \\end{pmatrix}$의 모든 성분의 합을 구하시오. (단, $E$는 단위행렬, $O$는 영행렬이다.)",
    choices: [],
    answer: "-16",
    solution: ""
  }
];