window.examTitle = "25_팔마고_1학기_기말_고1_유사1";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 연립부등식 $\\begin{cases} 2x+1 \\ge -3 \\\\ x-4 < 0 \\end{cases}$ 을 만족시키는 해가 $a \\le x < b$ 일 때, $a+b$의 값은? (단, $a, b$는 실수이다.)",
    choices: ["-2", "0", "2", "4", "6"],
    answer: "③",
    solution: ""
  },
  {
    id: 2,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 이차부등식 $x^2-9x+14 \\le 0$ 을 만족시키는 정수 $x$의 개수는?",
    choices: ["3", "4", "5", "6", "7"],
    answer: "④",
    solution: ""
  },
  {
    id: 3,
    level: "중",
    category: "합의 법칙과 곱의 법칙",
    originalCategory: "합의 법칙과 곱의 법칙",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-07",
    standardUnit: "합의 법칙과 곱의 법칙",
    standardUnitOrder: 7,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "서로 다른 주사위 두 개를 동시에 던질 때, 두 눈의 차가 $3$ 이하인 경우의 수는?",
    choices: ["24", "26", "28", "30", "32"],
    answer: "④",
    solution: ""
  },
  {
    id: 4,
    level: "중",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "자연수 $n$에 대하여 ${}_nP_3=60$ 을 만족하는 $n$의 값은?",
    choices: ["3", "4", "5", "6", "7"],
    answer: "③",
    solution: ""
  },
  {
    id: 5,
    level: "중",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 이차정사각행렬 $A=\\begin{pmatrix} 2x & 3 \\\\ -1 & y-1 \\end{pmatrix}$, $B=\\begin{pmatrix} 4 & 3 \\\\ -1 & 5 \\end{pmatrix}$에 대하여 $A=B$일 때, $xy$의 값은? (단, $x, y$는 실수이다.)",
    choices: ["6", "8", "10", "12", "14"],
    answer: "④",
    solution: ""
  },
  {
    id: 6,
    level: "중",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$2\\times2$ 행렬 $A=\\begin{pmatrix} 1 & -2 \\\\ 3 & 0 \\end{pmatrix}$에 대하여 행렬 $-3A$의 모든 성분의 합은?",
    choices: ["-10", "-8", "-6", "-4", "-2"],
    answer: "③",
    solution: ""
  },
  {
    id: 7,
    level: "중",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 연립부등식 $\\begin{cases} |x-2| \\le 4 \\\\ x > 0 \\end{cases}$ 을 만족시키는 정수 $x$의 개수는?",
    choices: ["4", "5", "6", "7", "8"],
    answer: "③",
    solution: ""
  },
  {
    id: 8,
    level: "중상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 부등식 $x+a \\le x^2-3x+8 \\le 2x^2+x+b$ 가 모든 실수 $x$에 대하여 성립하도록 하는 $a$의 최댓값과 $b$의 최솟값의 합은? (단, $a, b$는 실수이다.)",
    choices: ["12", "14", "16", "18", "20"],
    answer: "③",
    solution: ""
  },
  {
    id: 9,
    level: "중상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 이차부등식 $x^2+ax+b<0$ 의 해가 $-2<x<4$ 일 때, $x$에 대한 이차부등식 $x^2+bx-4a \\le 0$ 을 만족시키는 정수 $x$의 개수는? (단, $a, b$는 실수이다.)",
    choices: ["3", "4", "5", "6", "7"],
    answer: "③",
    solution: ""
  },
  {
    id: 10,
    level: "중",
    category: "도형의 방정식",
    originalCategory: "삼각형의 변의 길이",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-04",
    standardUnit: "도형의 이동",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "세 변의 길이가 $x, 8, 10$ 인 삼각형이 예각삼각형이 되도록 하는 정수 $x$의 개수는?",
    choices: ["4", "5", "6", "7", "8"],
    answer: "③",
    solution: ""
  },
  {
    id: 11,
    level: "중상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "남학생 $3$명과 여학생 $n$명이 일렬로 설 때, 양 끝에 남학생 $2$명이 서는 경우의 수가 $720$이다. 이때 $n$의 값은?",
    choices: ["2", "3", "4", "5", "6"],
    answer: "③",
    solution: ""
  },
  {
    id: 12,
    level: "중상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$5$개의 문자 $m, a, g, i, c$을 모두 한 번씩 사용하여 사전식으로 $acgim$부터 $mgica$까지 배열할 때, 문자열 $magic$은 몇 번째에 나타나는지 구하시오.",
    choices: ["98", "99", "100", "101", "102"],
    answer: "③",
    solution: ""
  },
  {
    id: 13,
    level: "중상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "자연수 $x$에 대하여 ${}_8C_{2x-1}={}_8C_{x+3}$ 을 만족하는 모든 $x$의 값의 합은?",
    choices: ["5", "6", "7", "8", "9"],
    answer: "②",
    solution: ""
  },
  {
    id: 14,
    level: "중상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 회사에서 생산하는 두 제품 A, B의 제조 원가와 판매가 행렬을 $P=\\begin{pmatrix} 1 & 2 \\\\ 4 & 5 \\end{pmatrix}$ (1행 제조 원가, 2행 판매가. 1열 제품 A, 2열 제품 B)라 하고, 상반기와 하반기의 판매량 행렬을 $Q=\\begin{pmatrix} 10 & 20 \\\\ 15 & 10 \\end{pmatrix}$ (1열 상반기, 2열 하반기)라 하자. $PQ=\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}$ 일 때, 상반기에 판매된 두 제품의 판매 이익금의 합은? (단, 이익금은 판매가에서 제조 원가를 뺀 금액이다.)",
    choices: ["65", "70", "75", "80", "85"],
    answer: "③",
    solution: ""
  },
  {
    id: 15,
    level: "중상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 등식을 만족시키는 실수 $x, y$에 대하여 $2x+y$의 값을 구하시오. (단, $x<y$)<br>$\\begin{pmatrix} 1 & 1 \\\\ x & y \\end{pmatrix}\\begin{pmatrix} x & 3 \\\\ y & 2 \\end{pmatrix}=\\begin{pmatrix} 6 & 5 \\\\ 3 & 2x \\end{pmatrix}+\\begin{pmatrix} -2 & 0 \\\\ 7 & y+4 \\end{pmatrix}$",
    choices: ["1", "3", "5", "7", "9"],
    answer: "③",
    solution: ""
  },
  {
    id: 16,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x$에 대한 연립이차부등식 $\\begin{cases} ax^2+(a+b)x+a+b-2>0 \\\\ (a+b)x^2+(a+b-2)x+a<0 \\end{cases}$ 을 만족시키는 모든 실수 $x$값의 범위가 $x>p$이다. $a=2$일 때, $p$의 값을 구하시오. (단, $a, b, p$는 실수이다.)",
    choices: ["-2", "-1", "0", "1", "2"],
    answer: "④",
    solution: ""
  },
  {
    id: 17,
    level: "중상",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$5$명의 학생이 자리를 바꾸려고 하는데 $1$명은 자기 자리에 그대로 앉고, 다른 $4$명은 기존 자기 자리와 다른 자리에 앉는 경우의 수를 구하시오.",
    choices: ["35", "40", "45", "50", "55"],
    answer: "③",
    solution: ""
  },
  {
    id: 18,
    level: "상",
    category: "순열과 조합",
    originalCategory: "도형의 개수 세기",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["도형"],
    wide: false,
    content: "오른쪽 그림과 같이 한 변의 길이가 $1$인 정사각형 $10$개로 이루어진 도형이 있다. 이 도형의 선으로 만들 수 있는 모든 직사각형의 개수를 구하시오.<br><svg width=\"200\" height=\"200\" viewBox=\"0 0 200 200\" xmlns=\"http://www.w3.org/2000/svg\"><g stroke=\"#000\" stroke-width=\"2\" fill=\"none\"><path d=\"M 20 180 L 180 180 M 20 140 L 180 140 M 20 100 L 140 100 M 20 60 L 100 60 M 20 20 L 60 20\"/><path d=\"M 20 20 L 20 180 M 60 20 L 60 180 M 100 60 L 100 180 M 140 100 L 140 180 M 180 140 L 180 180\"/></g></svg>",
    choices: ["33", "34", "35", "36", "37"],
    answer: "③",
    solution: ""
  },
  {
    id: 19,
    level: "상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 <보기>를 이용하여 물음에 답하시오.<br><br><보기><br>행렬 $M=\\begin{pmatrix} a & -b \\\\ b & a \\end{pmatrix}$, $N=\\begin{pmatrix} c & -d \\\\ d & c \\end{pmatrix}$ 에 대하여 $MN=\\begin{pmatrix} ac-bd & -(ad+bc) \\\\ ad+bc & ac-bd \\end{pmatrix}$ 를 만족한다. 또한 복소수 곱셈 $(a+bi)(c+di)=(ac-bd)+(ad+bc)i$ 임을 참고한다. (단, $a,b,c,d$는 실수이다.)<br><br>위 사실을 이용하여, 행렬 $A=\\begin{pmatrix} \\frac{1}{2} & -\\frac{\\sqrt{3}}{2} \\\\ \\frac{\\sqrt{3}}{2} & \\frac{1}{2} \\end{pmatrix}$ 일 때, 행렬 $A^{60}$의 모든 성분의 합을 구하면?",
    choices: ["0", "1", "2", "3", "4"],
    answer: "③",
    solution: ""
  },
  {
    id: 20,
    level: "상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "서답형",
    layoutTag: "grid",
    tags: ["서답형"],
    wide: false,
    content: "$x$에 대한 이차부등식 $x^2-2kx+3k+4 \\le 0$ 의 해가 단 하나 존재할 때, 양수 $k$의 값을 $a$라 하자. 또한 이차부등식 $-x^2+4x-b<0$ 이 모든 실수 $x$에 대하여 성립하도록 하는 정수 $b$의 최솟값을 $c$라 할 때, $a+c$의 값을 구하시오.",
    choices: [],
    answer: "9",
    solution: ""
  },
  {
    id: 21,
    level: "중상",
    category: "여러 가지 방정식과 부등식",
    originalCategory: "여러 가지 방정식과 부등식",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-06",
    standardUnit: "여러 가지 방정식과 부등식",
    standardUnitOrder: 6,
    questionType: "서답형",
    layoutTag: "grid",
    tags: ["서답형"],
    wide: false,
    content: "부등식 $|x-3|+|2x-1| \\le 8$ 을 만족시키는 모든 정수 $x$의 합을 구하시오.",
    choices: [],
    answer: "9",
    solution: ""
  },
  {
    id: 22,
    level: "중",
    category: "순열과 조합",
    originalCategory: "순열과 조합",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-08",
    standardUnit: "순열과 조합",
    standardUnitOrder: 8,
    questionType: "서답형",
    layoutTag: "grid",
    tags: ["서답형"],
    wide: false,
    content: "서로 다른 번호가 붙은 $5$개의 상자에 서로 같은 공 $3$개를 넣으려고 한다. 한 상자에 많아야 $1$개의 공만 들어갈 수 있다고 할 때, 빈 상자가 생기는 경우의 수를 구하시오.",
    choices: [],
    answer: "10",
    solution: ""
  },
  {
    id: 23,
    level: "상",
    category: "행렬과 그 연산",
    originalCategory: "행렬과 그 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-09",
    standardUnit: "행렬과 그 연산",
    standardUnitOrder: 9,
    questionType: "서답형",
    layoutTag: "grid",
    tags: ["서답형"],
    wide: false,
    content: "$2\\times2$ 행렬 $A=\\begin{pmatrix} 2 & 1 \\\\ 0 & 3 \\end{pmatrix}$ 에 대하여 이차방정식 $x^2-5x+6=0$ 의 해를 통해 $A^2-5A+6E=O$ 가 성립함을 알 수 있다. 이를 이용하여 행렬 $B=A^3-3A^2+A+5E$ 를 $B=aA+bE$ 꼴로 나타낼 때, 두 실수 $a,b$의 곱 $ab$의 값을 구하시오. (단, $E$는 단위행렬, $O$는 영행렬이다.)",
    choices: [],
    answer: "-35",
    solution: ""
  }
];