window.examTitle = "비상_공통수학2_직선의방정식_중단원학습점검_고1";

window.questionBank = [
  {
    "id": 2602,
    "level": "",
    "category": "직선의 방정식",
    "originalCategory": "도형의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["비상교육", "교과서", "고1", "공통수학2", "도형의 방정식", "직선의 방정식", "중단원학습점검"],
    "wide": false,
    "content": "다음 직선의 방정식을 구하시오.\n(1) 점 $(-1,4)$를 지나고 기울기가 $3$인 직선\n(2) 두 점 $(-1,3)$, $(1,7)$을 지나는 직선",
    "choices": [],
    "answer": "(1) $y=3x+7$\n(2) $y=2x+5$",
    "solution": "(1) 기울기가 $3$이고 점 $(-1,4)$를 지나므로 점기울기식을 세우면 $y-4=3(x+1)$이다.\n정리하면 $y=3x+7$이다.\n\n(2) 두 점을 지나는 직선의 기울기는 $\\dfrac{7-3}{1-(-1)}=2$이다.\n점 $(-1,3)$을 지나므로 $y-3=2(x+1)$이다.\n정리하면 $y=2x+5$이다.\n\n따라서 구하는 직선의 방정식은 (1) $y=3x+7$, (2) $y=2x+5$이다."
  },
  {
    "id": 2603,
    "level": "",
    "category": "직선의 방정식",
    "originalCategory": "도형의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["비상교육", "교과서", "고1", "공통수학2", "도형의 방정식", "직선의 방정식", "중단원학습점검"],
    "wide": false,
    "content": "다음 직선의 방정식을 구하시오.\n(1) 직선 $y=2x-3$과 평행하고 점 $(3,1)$을 지나는 직선\n(2) 직선 $x-4y+7=0$과 수직이고 점 $(-1,2)$를 지나는 직선",
    "choices": [],
    "answer": "(1) $y=2x-5$\n(2) $y=-4x-2$",
    "solution": "(1) 구하는 직선은 직선 $y=2x-3$과 평행하므로 기울기는 $2$이다.\n점 $(3,1)$을 지나므로 $y-1=2(x-3)$이다.\n정리하면 $y=2x-5$이다.\n\n(2) 직선 $x-4y+7=0$을 기울기 꼴로 나타내면 $y=\\dfrac{1}{4}x+\\dfrac{7}{4}$이므로 기울기는 $\\dfrac{1}{4}$이다.\n이 직선과 수직인 직선의 기울기는 $-4$이다.\n점 $(-1,2)$를 지나므로 $y-2=-4(x+1)$이다.\n정리하면 $y=-4x-2$이다.\n\n따라서 구하는 직선의 방정식은 (1) $y=2x-5$, (2) $y=-4x-2$이다."
  },
  {
    "id": 2604,
    "level": "",
    "category": "직선의 방정식",
    "originalCategory": "도형의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["비상교육", "교과서", "고1", "공통수학2", "도형의 방정식", "직선의 방정식", "중단원학습점검"],
    "wide": false,
    "content": "점 $(3,-1)$과 직선 $5x-12y-1=0$ 사이의 거리를 구하시오.",
    "choices": [],
    "answer": "$2$",
    "solution": "점 $(x_1,y_1)$과 직선 $ax+by+c=0$ 사이의 거리는 $\\dfrac{|ax_1+by_1+c|}{\\sqrt{a^2+b^2}}$이다.\n따라서 점 $(3,-1)$과 직선 $5x-12y-1=0$ 사이의 거리는 $\\dfrac{|5\\cdot3-12\\cdot(-1)-1|}{\\sqrt{5^2+(-12)^2}}=\\dfrac{26}{13}=2$이다.\n\n따라서 구하는 거리는 $2$이다."
  },
  {
    "id": 2606,
    "level": "",
    "category": "직선의 방정식",
    "originalCategory": "도형의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["비상교육", "교과서", "고1", "공통수학2", "도형의 방정식", "직선의 방정식", "중단원학습점검"],
    "wide": false,
    "content": "직선 $x+2y-4k=0$과 $x$축, $y$축으로 둘러싸인 삼각형의 넓이가 $100$일 때, 양수 $k$의 값을 구하시오.",
    "choices": [],
    "answer": "$5$",
    "solution": "직선 $x+2y-4k=0$의 $x$절편은 $4k$이고 $y$절편은 $2k$이다.\n따라서 이 직선과 두 좌표축으로 둘러싸인 삼각형의 넓이는 $\\dfrac{1}{2}\\cdot4k\\cdot2k=4k^2$이다.\n$4k^2=100$에서 $k^2=25$이므로 $k=\\pm5$이다.\n양수 $k$를 구하므로 $k=5$이다."
  },
  {
    "id": 2607,
    "level": "",
    "category": "직선의 방정식",
    "originalCategory": "도형의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["비상교육", "교과서", "고1", "공통수학2", "도형의 방정식", "직선의 방정식", "중단원학습점검"],
    "wide": false,
    "content": "세 점 $A(5,2)$, $B(2,4)$, $C(-1,-3)$을 꼭짓점으로 하는 삼각형 $ABC$의 무게중심 $G$를 지나면서 직선 $9x-3y+7=0$과 평행한 직선의 방정식을 구하시오.",
    "choices": [],
    "answer": "$y=3x-5$",
    "solution": "삼각형 $ABC$의 무게중심 $G$의 좌표는 $\\left(\\dfrac{5+2-1}{3},\\,\\dfrac{2+4-3}{3}\\right)=(2,1)$이다.\n직선 $9x-3y+7=0$을 기울기 꼴로 나타내면 $y=3x+\\dfrac{7}{3}$이므로 기울기는 $3$이다.\n구하는 직선은 점 $(2,1)$을 지나고 기울기가 $3$이므로 $y-1=3(x-2)$이다.\n정리하면 $y=3x-5$이다."
  },
  {
    "id": 2608,
    "level": "",
    "category": "직선의 방정식",
    "originalCategory": "도형의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["비상교육", "교과서", "고1", "공통수학2", "도형의 방정식", "직선의 방정식", "중단원학습점검"],
    "wide": false,
    "content": "두 점 $A(6,3)$, $B(2,-1)$에 대하여 선분 $AB$를 $3:1$로 내분하는 점 $P$를 지나고 선분 $AB$와 수직인 직선의 방정식이 $y=ax+b$일 때, 실수 $a$, $b$의 값을 구하시오.",
    "choices": [],
    "answer": "$a=-1,\ b=3$",
    "solution": "선분 $AB$의 기울기는 $\\dfrac{-1-3}{2-6}=1$이다.\n선분 $AB$와 수직인 직선의 기울기는 $a=-1$이다.\n점 $P$는 $AB$를 $3:1$로 내분하므로 $P\\left(\\dfrac{6+3\\cdot2}{4},\\,\\dfrac{3+3\\cdot(-1)}{4}\\right)=(3,0)$이다.\n직선 $y=ax+b$가 점 $(3,0)$을 지나고 $a=-1$이므로 $0=-3+b$, 따라서 $b=3$이다.\n\n따라서 $a=-1$, $b=3$이다."
  },
  {
    "id": 2609,
    "level": "",
    "category": "직선의 방정식",
    "originalCategory": "도형의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["비상교육", "교과서", "고1", "공통수학2", "도형의 방정식", "직선의 방정식", "중단원학습점검"],
    "wide": false,
    "content": "오른쪽 그림과 같이 세 점 $O(0,0)$, $A(3,1)$, $B(1,5)$를 꼭짓점으로 하는 삼각형 $OAB$의 넓이를 원점 $O$를 지나는 직선 $l$이 이등분할 때, 직선 $l$의 방정식을 구하시오.",
    "image": "../archive-work/textbooks/visang-common2/middle/geometry/직선의 방정식/assets/비상_공통수학2_직선의방정식_중단원학습점검_고1/q09_diagram.png",
    "choices": [],
    "answer": "$y=\\dfrac{3}{2}x$",
    "solution": "원점 $O$를 지나는 직선이 삼각형 $OAB$의 넓이를 이등분하려면 변 $AB$의 중점을 지나야 한다.\n변 $AB$의 중점은 $\\left(\\dfrac{3+1}{2},\\,\\dfrac{1+5}{2}\\right)=(2,3)$이다.\n따라서 직선 $l$은 $O(0,0)$과 $(2,3)$을 지나므로 기울기는 $\\dfrac{3}{2}$이다.\n\n따라서 직선 $l$의 방정식은 $y=\\dfrac{3}{2}x$이다."
  },
  {
    "id": 2610,
    "level": "",
    "category": "직선의 방정식",
    "originalCategory": "도형의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["비상교육", "교과서", "고1", "공통수학2", "도형의 방정식", "직선의 방정식", "중단원학습점검"],
    "wide": false,
    "content": "직선 $2x+3y+5=0$과 평행하고, 두 직선 $4x-y+6=0$, $x+2y-3=0$의 교점에서 거리 $\\sqrt{13}$인 직선의 방정식을 구하시오.",
    "choices": [],
    "answer": "$2x+3y-17=0$ 또는 $2x+3y+9=0$",
    "solution": "구하는 직선은 직선 $2x+3y+5=0$과 평행하므로 $2x+3y+k=0$ ($k\\ne5$)로 놓을 수 있다.\n두 직선 $4x-y+6=0$, $x+2y-3=0$의 교점은 $(-1,2)$이다.\n점 $(-1,2)$와 직선 $2x+3y+k=0$ 사이의 거리가 $\\sqrt{13}$이므로 $\\dfrac{|-2+6+k|}{\\sqrt{2^2+3^2}}=\\sqrt{13}$이다.\n따라서 $|k+4|=13$이고, $k=9$ 또는 $k=-17$이다. 두 값은 모두 $k\\ne5$를 만족한다.\n\n따라서 구하는 직선의 방정식은 $2x+3y-17=0$ 또는 $2x+3y+9=0$이다."
  }
];
