import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const repo='C:/Users/USER/Desktop/AP------';
const outDir=path.join(repo,'reports','h1-similar-full-audit-loop-20260826');
const targets=[
 ['2mid','25_금당고_2학기_중간_고1_유사.js'],['2mid','25_매산고_2학기_중간_고1_유사.js'],['2mid','25_순천고_2학기_중간_고1_유사.js'],
 ['2final','25_금당고_2학기_기말_고1_유사.js'],['2final','25_순천고_2학기_기말_고1_유사.js'],['2final','25_제일고_2학기_기말_고1_유사.js'],['2final','25_팔마고_2학기_기말_고1_유사.js'],['2final','25_효천고_2학기_기말_고1_유사.js']
];
function load(p){const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync(p,'utf8'),c,{filename:p});return c.window;}
const master=JSON.parse(fs.readFileSync(path.join(repo,'archive','data','master_tables','js_archive_tag_master.json'),'utf8'));
const subs=new Map(master.filter(x=>x.keyType==='subUnitKey').map(x=>[x.key||x.subUnitKey,x]));
const canonical=new Map([
 ['H22-C-09',['행렬과 그 연산',9]],['H22-C2-01',['평면좌표',1]],['H22-C2-02',['직선의 방정식',2]],['H22-C2-03',['원의 방정식',3]],['H22-C2-04',['도형의 이동',4]],['H22-C2-05',['집합',5]],['H22-C2-06',['명제',6]],['H22-C2-07',['함수',7]],['H22-C2-08',['유리함수',8]],['H22-C2-09',['무리함수',9]]
]);
const rows=[];
 for(const [term,name] of targets){const p=path.join(repo,'archive','exams','similar','high','h1',term,name);const qs=load(p).questionBank||[];for(const q of qs){const e=[],w=[];const key=q.standardUnitKey;const canon=canonical.get(key);const sub=subs.get(q.subUnitKey);const allowedCourse=key==='H22-C-09'?'공통수학1':'공통수학2';if(q.standardCourse!==allowedCourse)e.push(`standardCourse not ${allowedCourse}`);if(!canon)e.push(`unknown standardUnitKey ${key}`);else{if(q.standardUnit!==canon[0])e.push('standardUnit label mismatch');if(q.standardUnitOrder!==canon[1])e.push('standardUnitOrder mismatch');}if(!sub)e.push(`subUnitKey not in compiled master ${q.subUnitKey}`);else{if(sub.standardUnitKey!==key)e.push('subUnit parent mismatch');if(q.subUnit!==sub.labelKo)e.push('subUnit label mismatch');}if(!['existing_preserved','candidate_evidence','rule_inferred','category_or_cue_inferred'].includes(q.subUnitConfidence))w.push('subUnitConfidence not recognized');if(!['complete_rule','complete_category','partial','manual_review'].includes(q.subUnitClassificationDepth))w.push('subUnitClassificationDepth not recognized');const choice=Array.isArray(q.choices)&&q.choices.length>0;if(choice&&q.questionType!=='객관식')e.push('choice questionType mismatch');if(!choice&&!['단답형','서술형','주관식'].includes(q.questionType))e.push('empty choices type mismatch');const tags=Array.isArray(q.tags)?q.tags:[];const visual=Boolean(q.image)||/<(?:img|svg|table)\b/i.test(String(q.content));if(q.questionType==='서술형'&&!tags.includes('서술형'))w.push('서술형 tag missing');if(visual&&!tags.some(t=>['도형','그래프','표','이미지','SVG'].includes(t)))w.push('visual tag missing');if(!['하','중','상'].includes(q.level))e.push(`invalid level ${q.level}`);if(q.layoutTag!=='grid'||q.wide!==false)w.push('non-default layout requires explicit approval evidence');rows.push({exam:name,q:q.id,standardCourse:q.standardCourse,standardUnitKey:key,standardUnit:q.standardUnit,subUnitKey:q.subUnitKey,subUnit:q.subUnit,confidence:q.subUnitConfidence,depth:q.subUnitClassificationDepth,questionType:q.questionType,tags,level:q.level,errors:e,warnings:w,levelIndependent:'BLOCKED_NOT_INDEPENDENTLY_REJUDGED',status:e.length?'FAIL':w.length?'WARN':'PASS'});}}
const out={generatedAt:new Date().toISOString(),protocols:['JS아카이브_3차검수_프로토콜.md','무결성검수.md','JS아카이브_표준단원키_마스터테이블.md','archive/data/master_tables/js_archive_tag_master.json'],scope:{questions:rows.length},counts:{fail:rows.filter(r=>r.status==='FAIL').length,warn:rows.filter(r=>r.status==='WARN').length,pass:rows.filter(r=>r.status==='PASS').length,levelIndependentBlocked:rows.length},gates:{standardCourseUnitSubUnit:rows.some(r=>r.errors.some(e=>/standardCourse|standardUnit|subUnit/.test(e)))?'FAIL':'PASS',questionTypeTags:rows.some(r=>r.errors.some(e=>/questionType/.test(e)))?'FAIL':'PASS',levelIndependent:'BLOCKED',overall:'BLOCKED'},rows};
fs.writeFileSync(path.join(outDir,'stage3-metadata.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({counts:out.counts,gates:out.gates,errors:rows.filter(r=>r.errors.length).slice(0,20)},null,2));
