window.examTitle = "22_매산고_2학기_기말_고2_수학II";
window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수",
      "극대"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3-3x+5$의 극댓값은? [3.7점]",
    "choices": [
      "$3$",
      "$5$",
      "$7$",
      "$9$",
      "$11$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_EXTREMA",
    "templateKey": "TPL_EXTREMA_VALUE_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:fcd8c182dd70b25bcf0755ee61df2939d84b8a5500f60edacb1ac5528c29e867"
  },
  {
    "id": 2,
    "level": "하",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "위치함수",
      "속도"
    ],
    "wide": false,
    "content": "수직선 위를 움직이는 점 $P$의 시각 $t$에서의 위치 $x$가 $x=t^2-4t+2$일 때, $t=6$에서의 속도는? [3.8점]",
    "choices": [
      "$4$",
      "$5$",
      "$6$",
      "$7$",
      "$8$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MOTION",
    "templateKey": "TPL_MOTION_COMPOSITE_MODEL",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:13d76e327bd0d7ed7f6167ae6c9105b16ac98a4983d95ee9aae56138ebbd9ab0"
  },
  {
    "id": 3,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 그래프",
      "함수값"
    ],
    "wide": false,
    "content": "삼차함수 $f(x)$의 도함수 $y=f'(x)$의 그래프가 다음 그림과 같다. $f(0)=1$일 때, $f(3)$의 값은? [3.8점]",
    "choices": [
      "$0$",
      "$1$",
      "$2$",
      "$3$",
      "$4$"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/22_매산고_2학기_기말_고2_수학II/q003_visual.png",
    "visualAsset": "assets/images/22_매산고_2학기_기말_고2_수학II/q003_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 1060,
      "y1": 490,
      "x2": 1525,
      "y2": 1005
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.98,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/22_매산고_2학기_기말_고2_수학II/q003_visual.png",
      "assetSha256": "sha256:11c680575f6bb88cd147fd576a19c1be0e8d422db22abe8474467401ff16bd13",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
      "sourceQuestionNo": "3",
      "sourcePageNo": 1,
      "sourcePageEvidence": "pages/page_p001.png",
      "sourcePageEvidencePaths": [
        "pages/page_p001.png"
      ],
      "sourceBBox": {
        "x1": 1060,
        "y1": 490,
        "x2": 1525,
        "y2": 1005
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 465,
      "naturalHeight": 515,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_GRAPH_ANALYSIS",
    "templateKey": "TPL_DERIVATIVE_GRAPH_QUANTITATIVE_RECOVERY",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:cf03f00ac8428a2e6c0773b6fede9c3606e8786c07c0787ef9fdb87580b538a0"
  },
  {
    "id": 4,
    "level": "중",
    "category": "부정적분",
    "originalCategory": "부정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-07",
    "standardUnit": "부정적분",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-M2-07-INDEFINITE_INTEGRAL",
    "subUnit": "부정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "부정적분",
      "다항함수"
    ],
    "wide": false,
    "content": "다항함수 $f(x)$의 한 부정적분을 $F(x)$라고 하면 $F(x)=xf(x)+2x^3-3x^2$이 성립하고 $f(1)=0$일 때, 함수 $f(x)$를 구하면? [3.9점]",
    "choices": [
      "$f(x)=2x^3-3x^2$",
      "$f(x)=-2x^3+3x^2$",
      "$f(x)=6x^2-6x+3$",
      "$f(x)=-6x^2+6x-3$",
      "$f(x)=-3x^2+6x-3$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_07_INDEFINITE_INTEGRAL",
    "problemTypeKey": "PT_INDEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "TPL_INDEFINITE_DIFFERENTIAL_RELATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d9bb7b8ee014ef2c77b9f8bc8def98c15424c6065091883afa07405bc6e4b232"
  },
  {
    "id": 5,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "증가함수",
      "매개변수"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3+ax^2+ax-2$가 구간 $(-\\infty,\\infty)$에서 증가하도록 하는 정수 $a$의 개수는? [4.0점]",
    "choices": [
      "$3$",
      "$4$",
      "$5$",
      "$6$",
      "$7$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|5",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MONOTONICITY",
    "templateKey": "TPL_MONOTONICITY_CONDITION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:cd0b030e6d6af8274dc51aa5aa4b2899019866f5a6d27fc6c8b65d217e81d368"
  },
  {
    "id": 6,
    "level": "중",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분",
      "적분의 성질"
    ],
    "wide": false,
    "content": "$k\\ge 0$인 임의의 정수 $k$에 대하여 다항함수 $f(x)$가 $\\int_k^{k+1} f(x)\\,dx=2k+1$을 만족시킬 때, 정적분 $\\int_0^5 f(x)\\,dx$의 값은? [4.2점]",
    "choices": [
      "$10$",
      "$12$",
      "$20$",
      "$25$",
      "$60$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|6",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "TPL_GLOBAL_INTEGRAL_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ec353d3c91c9aa54fe62c2b4625deb26d1e91a3b6b5c1a29dbb843ee56203089"
  },
  {
    "id": 7,
    "level": "상",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "연속함수",
      "정적분",
      "넓이"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 증가하는 연속함수 $f(x)$가 모든 실수 $x$에 대하여 $f(x)=f(x-4)+5$이고 $\\int_0^8 f(x)\\,dx=0$이다. 함수 $y=f(x)$의 그래프와 $x$축 및 두 직선 $x=12$, $x=16$으로 둘러싸인 부분의 넓이는? [4.2점]",
    "choices": [
      "$20$",
      "$30$",
      "$40$",
      "$50$",
      "$60$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|7",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "PT_AREA_BY_DEFINITE_INTEGRAL",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:06584fba5412a119675ad1c4be9a5f946cfea68a5ec814fa3cc3039801747236"
  },
  {
    "id": 8,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "속도",
      "가속도",
      "이동거리"
    ],
    "wide": false,
    "content": "수직선 위를 움직이는 점 $P$의 시각 $t$ ($t\\ge 0$)에서의 속도 $v(t)$와 가속도 $a(t)$가 다음 조건을 만족시킨다.\n(가) $0\\le t\\le 2$일 때, $v(t)=2t^3-8t$이다.\n(나) $t\\ge 2$일 때, $a(t)=12t+4$이다.\n시각 $t=0$에서 $t=3$까지 점 $P$가 움직인 거리를 구하면? [4.4점]",
    "choices": [
      "$16$",
      "$18$",
      "$20$",
      "$22$",
      "$24$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|8",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MOTION",
    "templateKey": "TPL_MOTION_EVENT_ANALYSIS",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c9f4fffde4ce2232d587c96cec4830c4b39d80880e2c61a34d43013fec9643b6"
  },
  {
    "id": 9,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수",
      "구간별 식",
      "극솟값"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 연속인 함수 $f(x)$의 도함수 $f'(x)$가\n$f'(x)=\\begin{cases}x^3-4x & (|x|>1)\\\\2x+2 & (|x|<1)\\end{cases}$\n이고, 함수 $y=f(x)$의 그래프가 점 $(0,\\frac94)$를 지날 때, 함수 $f(x)$의 모든 극솟값의 곱은? [4.4점]",
    "choices": [
      "$-3$",
      "$-4$",
      "$-5$",
      "$-6$",
      "$-7$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|9",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_EXTREMA",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:823341304a7ac31005bf4da0739baf515a35dc831640b70903f44728c3862b9f"
  },
  {
    "id": 10,
    "level": "중",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분",
      "미분가능",
      "매개변수"
    ],
    "wide": false,
    "content": "미분가능한 함수 $f(x)$가 $\\int_a^x f(t)\\,dt=x^2-4x$를 만족시킬 때, 상수 $a$의 값은? (단, $a>0$) [4.5점]",
    "choices": [
      "$-3$",
      "$-2$",
      "$4$",
      "$8$",
      "$9$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|10",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "TPL_DIFFERENTIATE_INTEGRAL_RELATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:1c36dcd6824861344dcf069b747bf89c6076c90b54cd1133dbc609aae7d4a4aa"
  },
  {
    "id": 11,
    "level": "상",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분",
      "절댓값",
      "함수 관계식"
    ],
    "wide": false,
    "content": "함수 $f(x)$가 모든 실수 $x$에 대하여 $f(x)=x^3-4x\\int_0^1 |f(t)|\\,dt$를 만족시킨다. $f(1)>0$일 때, $f(3)$의 값은? [4.6점]",
    "choices": [
      "$\\frac{45}{2}$",
      "$\\frac{47}{2}$",
      "$\\frac{49}{2}$",
      "$\\frac{51}{2}$",
      "$\\frac{53}{2}$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|11",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "TPL_INTEGRAL_VALUE_SYSTEM_FUNCTION_DETERMINATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7b3ce68b58517661aaa1980c0a75feb91379136e153fd9f7d6a1cf40101546ca"
  },
  {
    "id": 12,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "속도",
      "만나는 시각",
      "매개변수"
    ],
    "wide": false,
    "content": "원점을 동시에 출발하여 수직선 위를 움직이는 두 점 $P$, $Q$의 시각 $t$ ($t\\ge 0$)에서의 속도가 각각\n$v_1(t)=2t(t^2-5t+9)$, $v_2(t)=\\frac54t^2+a$\n이다. 두 점 $P$, $Q$가 출발 후 두 번 만나기 위한 모든 상수 $a$의 값의 합을 $S$라고 할 때, $4S$의 값은? [4.8점]",
    "choices": [
      "$51$",
      "$53$",
      "$55$",
      "$57$",
      "$59$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|12",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MOTION",
    "templateKey": "TPL_MOTION_EVENT_ANALYSIS",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4e4b6acda5e9fb8cde7167b9be74298eb9e92496dd66c7aa48f483206e34a9ef"
  },
  {
    "id": 13,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "절댓값",
      "최솟값",
      "매개변수"
    ],
    "wide": false,
    "content": "삼차함수 $f(x)=\\frac13x^3-x^2+4$와 일차함수 $g(x)=ax-a+\\frac{10}{3}$ ($a<0$)에 대하여 함수 $h(x)$를\n$h(x)=\\frac12\\{f(x)+g(x)+|f(x)-g(x)|\\}$\n라 하자. 함수 $h(x)$의 최솟값이 $\\frac83$이 되도록 하는 실수 $a$의 최댓값은? [4.9점]",
    "choices": [
      "-\\frac23",
      "-\\frac43",
      "$-2$",
      "-\\frac83",
      "-\\frac{10}{3}"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|13",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MAX_MIN",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b31ed54dc1c6865834cf373b20f77e7555167508479bb4fcfd7f989cfb4a4b8f"
  },
  {
    "id": 14,
    "level": "상",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "역함수",
      "정적분",
      "옳은 것 고르기"
    ],
    "wide": false,
    "content": "삼차함수 $f(x)=-4x^3+ax^2-x$의 역함수가 존재하도록 하는 정수 $a$의 최댓값을 $M$이라 하자. $a=M$일 때, 함수 $g(x)$를\n$g(x)=\\begin{cases}f(x)&(x<0)\\\\f^{-1}(x)&(x\\ge 0)\\end{cases}$\n이라 하자. 다음에서 옳은 것만을 있는 대로 고른 것은? [4.9점]\nㄱ. $M=3$\nㄴ. $\\int_0^8 |g(x)|\\,dx=\\frac{13}{2}$\nㄷ. $\\int_{-1}^9 g(x)\\,dx<-4$",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄴ",
      "ㄱ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|14",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_OPERATION",
    "templateKey": "TPL_INVERSE_FUNCTION_INTEGRATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7a1f60082466202fe8259b89c118eca3e9f515192f6550f5d1df454b405afad0"
  },
  {
    "id": 15,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "사차함수",
      "절댓값",
      "정적분",
      "불연속"
    ],
    "wide": false,
    "content": "최고차항의 계수가 양수이고 $f(0)=0$인 사차함수 $f(x)$의 도함수 $f'(x)$가 다음 조건을 만족시킨다.\n(가) 방정식 $f'(x)=0$은 서로 다른 두 실근을 갖는다.\n(나) $f'(0)=0$, $f'(1)f'(-1)=0$\n실수 $t$에 대하여 함수 $|f(x)-t|$가 미분가능하지 않은 점의 개수를 $g(t)$라고 하자. 함수 $g(t)$가 $t=0$과 $t=\\frac7{12}$에서만 불연속일 때, $\\int_0^1 f(x)\\,dx$의 최댓값은 $\\frac qp$이다. $q-p$의 값은? [4.9점]",
    "choices": [
      "$100$",
      "$101$",
      "$102$",
      "$103$",
      "$104$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|15",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_EQUATION_INEQUALITY",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:77e9a7f5d8dd0c1af468488c3256bc801451ca45e05ce875638b5e7c6d9a0cb9"
  },
  {
    "id": 16,
    "level": "중",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "삼차함수",
      "넓이",
      "정적분"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3-3x^2+2x$일 때, $y=f(x)$의 그래프와 $x$축으로 둘러싸인 부분의 넓이를 구하시오. [4점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "단답형1",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 16,
    "displayNo": "단답형1",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|단답형1",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "PT_AREA_BY_DEFINITE_INTEGRAL",
    "templateKey": "TPL_INTERSECTION_SIGN_AREA",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ee050b34174c9ab446aecf72728784bde186409af24ffeccd3149f062d64e99b"
  },
  {
    "id": 17,
    "level": "상",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "이차방정식",
      "정적분",
      "매개변수"
    ],
    "wide": false,
    "content": "$x$에 대한 이차방정식 $x^2+ax+b=0$은 서로 다른 두 실근 $-1$, $\\alpha$를 가지고, $\\int_{-1}^{\\alpha}(x^2+ax+b)\\,dx=\\frac16$일 때, 정적분 $\\int_{-3}^1(x^2+bx-a)\\,dx$의 값을 구하시오. (단, $a$는 상수이다.) [5점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "단답형2",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 17,
    "displayNo": "단답형2",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|단답형2",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_OPERATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d6b8dbcdf91aabfe1d820d72910c979a30d34a980c516d914b65a6d03bbf68d9"
  },
  {
    "id": 18,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "사차함수",
      "극댓값",
      "실근의 개수"
    ],
    "wide": false,
    "content": "최고차항의 계수가 $1$인 사차함수 $f(x)$와 $0$이 아닌 실수 전체의 집합에서 정의된 함수 $g(x)$가 다음 조건을 만족시킨다.\n(가) $f'(0)=f(0)=0$\n(나) 함수 $f(x)$는 $x=2$에서 극댓값 $16$을 갖는다.\n(다) $0$이 아닌 모든 실수 $x$에 대하여 $f(x)=xg(x)+16$이다.\n방정식 $g(x)=k$가 서로 다른 네 실근을 갖도록 하는 모든 정수 $k$의 합을 구하시오. [6점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "단답형3",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 18,
    "displayNo": "단답형3",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|단답형3",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_EQUATION_INEQUALITY",
    "templateKey": "TPL_ROOT_COUNT_BY_EXTREMA",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e3965d126756d8c7f9b8be57e1508a8fb4da9a1dc39578124da29fd313a0e4a9"
  },
  {
    "id": 19,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "원뿔",
      "관련변화율",
      "부피"
    ],
    "wide": false,
    "content": "아래의 그림과 같이 밑면의 반지름의 길이가 12cm, 높이가 9cm인 원뿔 모양의 그릇이 있다. 이 그릇에 수면의 높이가 매초 1cm씩 올라가도록 물을 붓고 있다. 다음 물음에 답하시오.\n(1) $t$초 후 수면의 높이를 $h$cm, 수면의 반지름의 길이를 $r$cm라 할 때, $h$와 $r$을 $t$에 대한 식으로 각각 나타내시오. [2점]\n(2) $t$초 후 그릇에 담긴 물의 부피와 그때의 물의 부피 변화율을 $t$에 대한 식으로 각각 나타내시오. [6점]\n(3) 수면의 높이가 3cm일 때, 물의 부피 변화율을 구하시오. [2점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "assets/images/22_매산고_2학기_기말_고2_수학II/q019_visual.png",
    "visualAsset": "assets/images/22_매산고_2학기_기말_고2_수학II/q019_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 245,
      "y1": 430,
      "x2": 710,
      "y2": 720
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형1",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 19,
    "displayNo": "서술형1",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|서술형1",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 1,
    "visualAssetConfidence": 0.98,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/22_매산고_2학기_기말_고2_수학II/q019_visual.png",
      "assetSha256": "sha256:e7dcf68e324285efea1a4b68e18aa37b3ce19e36dda064eba2a24f3fbb33e63c",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
      "sourceQuestionNo": "서술형1",
      "sourcePageNo": 6,
      "sourcePageEvidence": "pages/page_p006.png",
      "sourcePageEvidencePaths": [
        "pages/page_p006.png"
      ],
      "sourceBBox": {
        "x1": 245,
        "y1": 430,
        "x2": 710,
        "y2": 720
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 465,
      "naturalHeight": 290,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_RATE_RELATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:36cc42e4b3cfbdea844eaa491eeff2eb128ededd579d1d12a563ea9c8cadee36"
  },
  {
    "id": 20,
    "level": "상",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "사차함수",
      "미분가능",
      "극댓값",
      "정적분"
    ],
    "wide": false,
    "content": "최고차항의 계수가 $1$인 사차함수 $f(x)$가 있다. 양수 $p$에 대하여 함수 $g(x)$를\n$g(x)=\\begin{cases}f(x)&(x\\le 0)\\\\f(x+p)-f(p)+f(0)&(x>0)\\end{cases}$\n이라 하자. 함수 $g(x)$는 실수 전체의 집합에서 미분가능하고, 두 함수 $f(x)$, $g(x)$는 다음 조건을 만족시킨다.\n(가) $|f'(0)|=f'(p+1)=\\frac53$\n(나) 두 함수 $f(x)$, $g(x)$는 모두 극댓값을 갖고, 두 함수 $f(x)$, $g(x)$의 극댓값의 차는 $14$이다.\n$f(2)-f(0)$의 값을 구하는 과정을 서술하시오. [10점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_매산고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_매산고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형2",
    "sourceArchiveFile": "original/high/h2/2final/22_매산고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 20,
    "displayNo": "서술형2",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5",
    "sourceIdentityKey": "sha256:07e3221cc7a2cef0a5c0bca8fe76892865e37ff618c2d96d1adb1feab52439c5|서술형2",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_매산고_2학기_기말_고2_수학II\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4e1e9b3554897203ef989abbeece8d8e2a34b2f2a449cdf27e8e5e7259de8469"
  }
];
