window.examTitle = "22_순천고_2학기_기말_고2_수학II";
window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "삼차함수",
      "최솟값"
    ],
    "wide": false,
    "content": "닫힌구간 $[-2,\\,2]$에서 함수 $f(x)=x^3-\\frac32x^2-6x+a$의 최솟값이 $-8$일 때, $a$의 값은? (단, $a$는 상수이다.) [3점]",
    "choices": [
      "$1$",
      "$2$",
      "$4$",
      "$8$",
      "$16$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:56733a817327b4fc94f96a5b6fc4504405bc7943ea9a994991a46034bc330ecc"
  },
  {
    "id": 2,
    "level": "하",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "위치",
      "속도"
    ],
    "wide": false,
    "content": "수직선 위를 움직이는 점 $P$의 시각 $t$ ($t\\ge 0$)에서의 위치 $x$가 $x=t^3-2t^2-2t$이다. 점 $P$의 속도가 $2$가 되는 시각 $t$의 값은? [3점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MOTION",
    "templateKey": "TPL_MOTION_EVENT_ANALYSIS",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:60327e83f12f7c0371a2375def5ed8a57f1f280a2b6da29070bf16d8517967e1"
  },
  {
    "id": 3,
    "level": "하",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "속도",
      "운동 방향"
    ],
    "wide": false,
    "content": "수직선 위를 움직이는 점 $P$의 시각 $t$에서의 속도를 $v(t)$라고 하자. $y=v(t)$의 그래프가 다음 그림과 같을 때, 점 $P$는 운동 방향을 바꾸는 횟수는? (단, $0\\le t\\le 20$) [3점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/22_순천고_2학기_기말_고2_수학II/q003_visual.png",
    "visualAsset": "assets/images/22_순천고_2학기_기말_고2_수학II/q003_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 250,
      "y1": 2215,
      "x2": 1050,
      "y2": 2540
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.96,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/22_순천고_2학기_기말_고2_수학II/q003_visual.png",
      "assetSha256": "sha256:6e177ab280325abdc21f43b109d27cb3b727f23b368c29f5b17d1f6606a4a6fb",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
      "sourceQuestionNo": "3",
      "sourcePageNo": 1,
      "sourcePageEvidence": "pages/page_p001.png",
      "sourcePageEvidencePaths": [
        "pages/page_p001.png"
      ],
      "sourceBBox": {
        "x1": 250,
        "y1": 2215,
        "x2": 1050,
        "y2": 2540
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 800,
      "naturalHeight": 325,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5d17f216e917103762f75b39a1d348602e49020b0e2ab8a9e84cdfa3e42aff31"
  },
  {
    "id": 4,
    "level": "하",
    "category": "부정적분",
    "originalCategory": "부정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-07",
    "standardUnit": "부정적분",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-M2-07-INDEFINITE_INTEGRAL",
    "subUnit": "부정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "부정적분"
    ],
    "wide": false,
    "content": "다음 중 함수 $f(x)=3x^2-4x+2$를 도함수로 가질 수 있는 함수 $F(x)$는? [3점]",
    "choices": [
      "$F(x)=6x-4$",
      "$F(x)=(3x-1)(x-2)$",
      "$F(x)=(x-1)^3$",
      "$F(x)=\\frac13x^3-2x$",
      "$F(x)=x^3-2x^2+2x+10$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_07_INDEFINITE_INTEGRAL",
    "problemTypeKey": "PT_INDEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "TPL_DERIVATIVE_TO_FUNCTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:985f10e657a872861f1480e19dff149cd0ebfb458137250c1719b25bb3392ce2"
  },
  {
    "id": 5,
    "level": "하",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분"
    ],
    "wide": false,
    "content": "다음 정적분 $\\int_{-1}^{2}(x^2+4x+2)\\,dx$의 값은? [3점]",
    "choices": [
      "$9$",
      "$12$",
      "$15$",
      "$18$",
      "$21$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|5",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_OPERATION",
    "templateKey": "TPL_DEFINITE_EVALUATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:0d6d65f8f2a106d629109cb838d2329d0af93747a1a8ec43145cd40ab61e6a52"
  },
  {
    "id": 6,
    "level": "하",
    "category": "부정적분",
    "originalCategory": "부정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-07",
    "standardUnit": "부정적분",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-M2-07-INDEFINITE_INTEGRAL",
    "subUnit": "부정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "부정적분",
      "정적분"
    ],
    "wide": false,
    "content": "함수 $f(x)$가 $f(x)=\\int 5\\,dx+\\int 6x^5\\,dx$를 만족시키고 $f(0)=0$일 때, $f(1)$의 값은? [3.5점]",
    "choices": [
      "$4$",
      "$5$",
      "$6$",
      "$7$",
      "$8$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|6",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_07_INDEFINITE_INTEGRAL",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:188099256b665693ed2b28fddcd603e006a1b0013ddfd5075d9c8896343229a3"
  },
  {
    "id": 7,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "최솟값",
      "부등식"
    ],
    "wide": false,
    "content": "모든 실수 $x$에 대하여 부등식 $3x^4+4x^3+5\\ge a$가 성립하도록 하는 실수 $a$의 최댓값은? [3.5점]",
    "choices": [
      "$5$",
      "$4$",
      "$3$",
      "$2$",
      "$1$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|7",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_EQUATION_INEQUALITY",
    "templateKey": "TPL_GLOBAL_INEQUALITY_BY_DERIVATIVE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:fc92b674e022394bf3f9fd9a4e5c1adbc0fdbaabd0279c9a69dbf1ae56247ac4"
  },
  {
    "id": 8,
    "level": "상",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "극값",
      "정적분"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3-3x^2+a$ ($a$는 상수)의 모든 극값의 곱이 $-4$일 때, $a+\\int_{-2}^{2}f(x)\\,dx$의 값은? [4.4점]",
    "choices": [
      "$-6$",
      "$-3$",
      "$0$",
      "$3$",
      "$6$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|8",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:cba10ece44cb96c7af16323cd85ec6b14de156cb21d75860dd2d0e237d311ea8"
  },
  {
    "id": 9,
    "level": "상",
    "category": "부정적분",
    "originalCategory": "부정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-07",
    "standardUnit": "부정적분",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-M2-07-INDEFINITE_INTEGRAL",
    "subUnit": "부정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "이차함수",
      "부정적분"
    ],
    "wide": false,
    "content": "이차함수 $f(x)$가 모든 실수 $x$에 대하여 $f(x)=f'(x)+2x^2$를 만족시킬 때, $\\frac{d}{dx}\\int f(x)\\,dx$의 최솟값은? [4.4점]",
    "choices": [
      "$-1$",
      "$0$",
      "$1$",
      "$2$",
      "$3$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|9",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_07_INDEFINITE_INTEGRAL",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:220be782150f51bce52bbf5e0379e247a2e90e1092574b59a2b0aa3df792990e"
  },
  {
    "id": 10,
    "level": "중",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "절댓값",
      "정적분"
    ],
    "wide": false,
    "content": "함수 $f(x)=|x+1|+|x|+|x-1|$의 최솟값 $a$에 대하여 정적분 $\\int_{-2}^{a}f(x)\\,dx$의 값은? [4.4점]",
    "choices": [
      "$14$",
      "$15$",
      "$16$",
      "$17$",
      "$18$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|10",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:76b8a540921246ae3ef830bab1c3e2f3ad3a1b6a2f5652925fbbe162bb3c6758"
  },
  {
    "id": 11,
    "level": "중",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "넓이",
      "정적분"
    ],
    "wide": false,
    "content": "곡선 $y=x^2-2x$와 직선 $y=kx$로 둘러싸인 부분의 넓이가 $x$축에 의하여 이등분되도록 하는 상수 $k$의 값에 대하여 $(k+2)^3$의 값은? [4.6점]",
    "choices": [
      "$-1$",
      "$1$",
      "$8$",
      "$16$",
      "$25$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|11",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c501915fed3ac39b1c943758f1e56485d8812d5efc1bf2221aec92bceb684ed8"
  },
  {
    "id": 12,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "삼차함수",
      "실근의 개수"
    ],
    "wide": false,
    "content": "최고차항의 계수가 $1$인 삼차함수 $f(x)$가 다음 조건을 만족시킬 때, 방정식 $f(x)=n$이 서로 다른 $3$개의 실근을 갖도록 하는 모든 자연수 $n$의 개수는? [4.6점]\\n&lt;보기&gt;\\nㄱ. 모든 실수 $x$에 대하여 $f(-x)=-f(x)$이다.\\nㄴ. 곡선 $y=f(x)$와 직선 $y=f(2)$는 서로 다른 두 점에서 만나고, $f(2)&lt;0$이다.",
    "choices": [
      "$15$",
      "$19$",
      "$23$",
      "$27$",
      "$31$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|12",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:88bec99eebdcca53b353f3c84c23cbe0c67675c99586749dea04251d0591e104"
  },
  {
    "id": 13,
    "level": "상",
    "category": "접선의 방정식",
    "originalCategory": "접선의 방정식",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-05",
    "standardUnit": "접선의 방정식",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-M2-05-TANGENT",
    "subUnit": "접선의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "접선",
      "삼차함수"
    ],
    "wide": false,
    "content": "점 $(-1,\\,k)$에서 곡선 $y=x^3-3x$에 서로 다른 세 개의 접선을 그을 수 있을 때, 다음 중 실수 $k$의 값의 범위가 $\\alpha&lt;k&lt;\\beta$일 때, $\\alpha+\\beta$의 값은? [4.6점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|13",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-05-TANGENT",
    "problemTypeKey": "PT_TANGENT_DERIVATIVE",
    "templateKey": "TPL_TANGENT_CONSTRUCTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ea7e9a6e7a2d63b73ae6946171229192db032c66bc70227c861c2a85a6730410"
  },
  {
    "id": 14,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "삼차방정식",
      "극값"
    ],
    "wide": false,
    "content": "$x$에 대한 삼차방정식 $\\frac13x^3-x=k$가 서로 다른 세 실근 $\\alpha,\\,\\beta,\\,\\gamma$를 가진다. 실수 $k$에 대하여 $|\\alpha|+|\\beta|+|\\gamma|$의 최솟값을 $m$이라 할 때, $m^2$의 값은? [5점]",
    "choices": [
      "$9$",
      "$12$",
      "$16$",
      "$27$",
      "$48$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|14",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:62da1b058534558a74c91e4f40fff565ac17f39a90267ce6fe9325eb1946a039"
  },
  {
    "id": 15,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "삼차함수",
      "극값",
      "실근"
    ],
    "wide": false,
    "content": "최고차항의 계수가 양수인 삼차함수 $f(x)$와 서로 다른 두 실수 $a,\\,b$에 대하여 $f'(a)=f'(b)=0$이다. &lt;보기&gt;에서 옳은 것만을 있는 대로 고른 것은? [5.2점]\\n&lt;보기&gt;\\nㄱ. 방정식 $f(x)-\\frac{f(a)+f(b)}{2}=0$은 서로 다른 세 실근을 갖는다.\\nㄴ. 방정식 $|f(x)-f(a)|-|f(a)-f(b)|=0$은 서로 다른 세 실근을 갖는다.\\nㄷ. 함수 $f(|x|)$가 실수 전체의 집합에서 미분가능하면 방정식 $f(|x|)-\\frac{f(a)+f(b)}{2}=0$은 서로 다른 네 실근을 갖는다.",
    "choices": [
      "ㄱ",
      "ㄱ, ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|15",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_MEAN_VALUE_THEOREM",
    "templateKey": "TPL_MVT_ROLLE_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:15606f9a7def5e23567eda90b44d8dfa70cadd0e32ac71a22e825b1a5cc053a9"
  },
  {
    "id": 16,
    "level": "상",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "주기함수",
      "부정적분"
    ],
    "wide": false,
    "content": "함수 $f(x)$가 $f(x)=\\begin{cases}3x(x-2)&(0\\le x&lt;2)\\\\3(x-2)(4-x)&(2\\le x&lt;4)\\end{cases}$이고 모든 실수 $x$에 대하여 $f(x+4)=f(x)$를 만족시킨다. 함수 $f(x)$의 한 부정적분 $F(x)$가 실수 전체의 집합에서 연속이고, $F(3)=-2$일 때, 다음 &lt;보기&gt; 중 항상 옳은 것만을 있는 대로 고른 것은? [5.2점]\\n&lt;보기&gt;\\nㄱ. 모든 실수 $x$에 대하여 $F(x+8)=F(x)$이다.\\nㄴ. 구간 $(0,14)$에서 함수 $F(x)$의 모든 극솟값의 합은 $-12$이다.\\nㄷ. $0&lt;x&lt;20$에서 방정식 $F(x)=-2$의 모든 실근의 합은 $100$이다.",
    "choices": [
      "ㄱ",
      "ㄷ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|16",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5d8a5625cdca71dd0765403bc524f2d16baaf2ce48770632d32d07b36f631ab6"
  },
  {
    "id": 17,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "삼차함수",
      "극값"
    ],
    "wide": false,
    "content": "최고차항의 계수가 양수인 삼차함수 $f(x)$가 다음 조건을 만족시킨다.\\n방정식 $f(x)+xf'(x)=0$이 $\\alpha&lt;\\beta&lt;0&lt;\\gamma$인 세 실근 $\\alpha,\\,\\beta,\\,\\gamma$를 갖고, $f(\\alpha)f(\\beta)f(\\gamma)=0$이다.\\n옳은 것만을 &lt;보기&gt;에서 있는 대로 고른 것은? [5.2점]\\n&lt;보기&gt;\\nㄱ. 함수 $f(x)$는 $x=\\alpha$에서 극댓값을 갖는다.\\nㄴ. $f(\\beta)f(\\gamma)&gt;0$\\nㄷ. 방정식 $f(x)=0$은 실수인 근을 두 개 가진다.",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄴ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|17",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:753475867e93d4f0a0a201c3295e343b36640686a751a187951f3f80d7ff358b"
  },
  {
    "id": 18,
    "level": "상",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분",
      "실근의 개수"
    ],
    "wide": false,
    "content": "최고차항의 계수가 $1$인 삼차함수 $f(x)$와 실수 $t$에 대하여 $x$에 대한 방정식 $\\int_t^x f(s)\\,ds=0$의 서로 다른 실근의 개수를 $g(t)$라 할 때, &lt;보기&gt;에서 옳은 것만을 있는 대로 고른 것은? [5.2점]\\n&lt;보기&gt;\\nㄱ. $f(x)=x^2(x-2)$일 때, $g(1)=1$이다.\\nㄴ. 방정식 $f(x)=0$의 서로 다른 실근의 개수가 $3$이면 $g(a)=3$인 실수 $a$가 존재한다.\\nㄷ. $\\lim_{t\\to b}g(t)+g(b)=6$을 만족시키는 실수 $b$의 값이 $0$과 $1$뿐이면 $f(2)=3$이다.",
    "choices": [
      "ㄱ",
      "ㄱ, ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|18",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "TPL_INTEGRAL_DEFINED_FUNCTION_ANALYSIS",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:2431a017e648fdb730f4d1169d898ed6f2a1a17d074365023e94b49fb75ec8e6"
  },
  {
    "id": 19,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "삼차함수",
      "극대"
    ],
    "wide": false,
    "content": "삼차함수 $f(x)$가 모든 실수 $x$에 대하여\\n$f(x)=\\frac13x^3-ax^2+(a^2-b)x+\\int_{-1}^{1}f(t)\\,dt$\\n를 만족시킨다.\\n$x&gt;1$에서 함수 $f(x)$가 극댓값을 갖도록 하는 $7$보다 작은 두 정수 $a,\\,b$에 대하여 순서쌍 $(a,\\,b)$의 개수는 $m$이고 $a=k$일 때, $f(0)$은 최소이다. $m+k$의 값은? (단, $k$는 상수이다.) [5.2점]",
    "choices": [
      "$24$",
      "$26$",
      "$28$",
      "$30$",
      "$32$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "19",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 19,
    "displayNo": "19",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|19",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d258215de2abe4ca687d4990b7895fe0f638150647f0aaf0a44c6387029f36ef"
  },
  {
    "id": 20,
    "level": "중",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분",
      "함수 관계식"
    ],
    "wide": false,
    "content": "함수 $f(x)$가 다음을 만족시킬 때,\\n$f(x)=8x-\\int_0^1 f(x)\\,dx$\\n$f(x)$를 구하는 풀이 과정과 답을 서술하시오. [6점, 부분점수 있음]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형1",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 20,
    "displayNo": "서술형1",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|서술형1",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "TPL_INTEGRAL_VALUE_SYSTEM_FUNCTION_DETERMINATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:46b59df070dedfaab8f64921fa6df44247d3c9b0258e6fdb268aab8f63516f5b"
  },
  {
    "id": 21,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "사차함수",
      "접선",
      "극댓값"
    ],
    "wide": false,
    "content": "그림과 같이 일차함수 $y=f(x)$의 그래프와 최고차항의 계수가 $1$인 사차함수 $y=g(x)$의 그래프는 $x$좌표가 $-2,\\,1$인 두 점에서 접한다. $h(x)=g(x)-f(x)$라 할 때, $h(x)$의 극댓값을 구하는 풀이 과정과 답을 서술하시오. [7점, 부분점수 있음]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "assets/images/22_순천고_2학기_기말_고2_수학II/q021_visual.png",
    "visualAsset": "assets/images/22_순천고_2학기_기말_고2_수학II/q021_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 190,
      "y1": 1610,
      "x2": 780,
      "y2": 2250
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형2",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 21,
    "displayNo": "서술형2",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|서술형2",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 0.96,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/22_순천고_2학기_기말_고2_수학II/q021_visual.png",
      "assetSha256": "sha256:a4b34cf4bd698884689a282e945d1bd30141187f679075bf41fe3387ce43f70d",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
      "sourceQuestionNo": "서술형2",
      "sourcePageNo": 5,
      "sourcePageEvidence": "pages/page_p005.png",
      "sourcePageEvidencePaths": [
        "pages/page_p005.png"
      ],
      "sourceBBox": {
        "x1": 190,
        "y1": 1610,
        "x2": 780,
        "y2": 2250
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 590,
      "naturalHeight": 640,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:449bf9e7698460fcb5aa4cd059ae68c75d32771245a62bacf8c0b73b160c0ae4"
  },
  {
    "id": 22,
    "level": "상",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "접선",
      "넓이",
      "정적분"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3-x+5$에 대하여 곡선 $y=f(x)$에 접하고 기울기가 $2$인 두 접선을 각각 $l_1,\\,l_2$라 하자. 곡선 $y=f(x)$와 직선 $l_1$로 둘러싸인 도형의 넓이를 $A$, 곡선 $y=f(x)$와 직선 $l_2$로 둘러싸인 도형의 넓이를 $B$, 곡선 $y=f(x)$와 두 직선 $l_1,\\,l_2$가 만나는 모든 점을 꼭짓점으로 하는 도형의 넓이를 $S$라 할 때, $2A+2B-S$의 값을 구하는 풀이 과정과 답을 서술하시오. [7점, 부분점수 있음]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_순천고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_순천고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형3",
    "sourceArchiveFile": "original/high/h2/2final/22_순천고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 22,
    "displayNo": "서술형3",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851",
    "sourceIdentityKey": "sha256:0c470b22688eb20c41e6758b71834066e6e88ae6ae1c7f1672a5bce4490dd851|서술형3",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_순천고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:1275b6af0dbeedd1c5c6892c13ee3918e09cfbdfa1b605c001f5d0e0c63ba1ae"
  }
];
