window.examTitle = "22_팔마고_2학기_기말_고2_수학II";
window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "닫힌구간 $[-2,\\,2]$에서 함수 $f(x)=x^3+3x^2-12$의 최댓값과 최솟값의 합은? [3.5점]",
    "choices": [
      "$-4$",
      "$-3$",
      "$-2$",
      "$-1$",
      "$0"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|1",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4b0c3027643e33ed2e62767e7f1ad79bef7a253e98624872e7c8769ca8b04cb3"
  },
  {
    "id": 2,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "원점을 출발하여 수직선 위를 움직이는 점 $P$의 시각 $t$에서 위치 $x$가 $x=t^3-6t^2+9t$이다. $t=3$일 때, 점 $P$의 속도와 가속도의 합은? [3.6점]",
    "choices": [
      "$2$",
      "$3$",
      "$4$",
      "$5$",
      "$6"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|2",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:1f2aa830f3401d9d688925d3425f14e2ab33ff37d1f34d550db3637e1ca6bf2d"
  },
  {
    "id": 3,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "함수 $f(x)$의 도함수 $y=fprime(x)$의 그래프가 다음 그림과 같을 때, <보기>에서 옳은 것만을 있는 대로 고른 것은? [3.6점]\n<보기>\nㄱ. $f(x)$는 닫힌구간 $[B,D]$에서 증가한다.\nㄴ. $f(x)$는 $x=D$에서 극대이다.\nㄷ. $f(x)$의 극값은 4개이다.\nㄹ. $f(x)$가 극소가 되는 $x$의 값은 $C$와 $G$이다.",
    "choices": [
      "ㄱ, ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄹ",
      "ㄷ, ㄹ",
      "ㄱ, ㄴ, ㄷ, ㄹ"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/22_팔마고_2학기_기말_고2_수학II/q003_visual.png",
    "visualAsset": "assets/images/22_팔마고_2학기_기말_고2_수학II/q003_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 1060,
      "y1": 590,
      "x2": 1510,
      "y2": 820
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|3",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/22_팔마고_2학기_기말_고2_수학II/q003_visual.png",
      "assetSha256": "sha256:5c4613c34a741963d5fbdc6232ab47b7cab57611fa0a638d794d6c8262dc4be8",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
      "sourceQuestionNo": "3",
      "sourcePageNo": 1,
      "sourcePageEvidence": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png",
      "sourcePageEvidencePaths": [
        "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png"
      ],
      "sourceBBox": {
        "x1": 1060,
        "y1": 590,
        "x2": 1510,
        "y2": 820
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 450,
      "naturalHeight": 230,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:18148135a8fc81fa0ea222635f499d070c3f3e688c6feee5d267607a66f9b609"
  },
  {
    "id": 4,
    "level": "중",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분"
    ],
    "wide": false,
    "content": "정적분 $int_0^1dfrac{1}{x+1},dx-int_1^0dfrac{y^3}{y+1},dy$의 값은? [3.7점]",
    "choices": [
      "$dfrac16$",
      "$dfrac56$",
      "$dfrac76$",
      "$dfrac{11}{6}$",
      "$dfrac{13}{6}$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|4",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:9d499580d26d52064ab248723069043492a013fa9b9a7703bc700b785b60ec1e"
  },
  {
    "id": 5,
    "level": "중",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "적분의 활용"
    ],
    "wide": false,
    "content": "곡선 $y=x^2-3x$와 $x$축으로 둘러싸인 도형의 넓이는? [3.8점]",
    "choices": [
      "$dfrac92$",
      "$5$",
      "$dfrac{11}{2}$",
      "$6$",
      "$dfrac{13}{2}$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|5",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:136f663586ff974090fa813cbc33ff7f60795ff56e652043fc2907f6eb695bcd"
  },
  {
    "id": 6,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "다음 <보기> 문장의 참(true), 거짓(false)을 바르게 판단한 것은? [3.9점]\n<보기>\n(가) 극댓값은 항상 극솟값보다 크다.\n(나) 미분가능한 함수 $f(x)$가 열린구간 $(a,b)$에서 $x=c$ $(a<c<b)$일 때 최댓값 또는 최솟값을 가지면 곡선 $y=f(x)$ 위의 점 $(c,f(c))$에서의 접선의 기울기는 0이다.\n(다) 함수 $f(x)$가 $x=a$에서 극값을 갖는다면 $fprime(a)=0$이다.",
    "choices": [
      "(가) 참, (나) 참, (다) 거짓",
      "(가) 참, (나) 거짓, (다) 참",
      "(가) 거짓, (나) 거짓, (다) 참",
      "(가) 거짓, (나) 참, (다) 참",
      "(가) 거짓, (나) 참, (다) 거짓"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|6",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c9d3b4cd8fc1cef53cedf5d8cd057bdeedabc821931486cfaffbe8c5c36ea8d9"
  },
  {
    "id": 7,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3+ax^2-(a^2-8a)x+3$이 다음 조건을 만족시키도록 하는 실수 $a$의 범위에 속하는 정수의 개수는?\n임의의 두 실수 $x_1,x_2$에 대하여 $x_1<x_2$이면 $f(x_1)<f(x_2)$이다. [4점]",
    "choices": [
      "$5$",
      "$6$",
      "$7$",
      "$8$",
      "$9$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|7",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:292b78afdb7d27d745d94f197dbb106dc15f5fe8fa68f95fe24ec07d5829adac"
  },
  {
    "id": 8,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "방정식 $x^3+6x^2+9x-2-a=0$이 서로 다른 세 실근을 갖도록 하는 정수 $a$의 개수는? [4.1점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|8",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:9b6c2b3c0ff78227739d32ccc09c85de23dd18e844a96e66703aee5a4a507be4"
  },
  {
    "id": 9,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "$xge0$일 때, 부등식 $2x^3-3kx^2+8ge0$이 항상 성립하도록 하는 양수 $k$의 최댓값은? [4.2점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$7$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|9",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:db701824ea844102917688f87f8b7ac84c28c47af745a12c4202c8259582eb58"
  },
  {
    "id": 10,
    "level": "중",
    "category": "부정적분",
    "originalCategory": "부정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-07",
    "standardUnit": "부정적분",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-M2-07-INDEFINITE_INTEGRAL",
    "subUnit": "부정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "부정적분"
    ],
    "wide": false,
    "content": "이차함수 $f(x)$와 그 부정적분 $F(x)$ 사이에 $dfrac{d}{dx}int F(x),dx=xf(x)+2x^3-2x^2$인 관계가 성립한다. $f(0)=2$일 때, $f(1)$의 값은? [4.4점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|10",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_07_INDEFINITE_INTEGRAL",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:2d02e240259ce37ee8290635e917693f77d31f56afa00c2190e7783c7f69d79a"
  },
  {
    "id": 11,
    "level": "중",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분"
    ],
    "wide": false,
    "content": "다항함수 $f(x)$가 모든 실수 $x$에 대하여 $int_1^x f(t),dt=x^3-2ax^2+a$ $(단, a는 상수)$를 만족할 때, $fprime(2)$의 값은? [4.3점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|11",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e0e18e1e3ec6e13d1ab81767f7439356204dd03fa42db8e516470cecadd3d0c8"
  },
  {
    "id": 12,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "좌표가 2인 점에서 출발하여 수직선 위를 움직이는 점 $P$의 시각 $t$에서의 속도가 $v(t)=1-2t$일 때, 점 $P$가 원점을 지나는 시각은? [4.3점]",
    "choices": [
      "$dfrac12$",
      "$1$",
      "$dfrac32$",
      "$2$",
      "$dfrac52$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|12",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:199596c74aea4f45c8d8ac82bb00ce80e4c71920090d3d856d7b7ae316c47357"
  },
  {
    "id": 13,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "삼차함수 $f(x)$의 도함수 $y=fprime(x)$의 그래프가 그림과 같다. 함수 $f(x)$의 극댓값이 32, 극솟값이 0일 때, $fprime(1)$의 값은? [4.4점]",
    "choices": [
      "$8$",
      "$7$",
      "$6$",
      "$5$",
      "$4$"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/22_팔마고_2학기_기말_고2_수학II/q013_visual.png",
    "visualAsset": "assets/images/22_팔마고_2학기_기말_고2_수학II/q013_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 300,
      "y1": 330,
      "x2": 690,
      "y2": 820
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|13",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/22_팔마고_2학기_기말_고2_수학II/q013_visual.png",
      "assetSha256": "sha256:ead04ffbba7933b7f3105c19890c2491c3531d9848747c8b8dd1441a4f12be75",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
      "sourceQuestionNo": "13",
      "sourcePageNo": 4,
      "sourcePageEvidence": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 300,
        "y1": 330,
        "x2": 690,
        "y2": 820
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 390,
      "naturalHeight": 490,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5881492a06175220beef48962d1b5b5c5563dda1d82296736b8aea840a1425d0"
  },
  {
    "id": 14,
    "level": "중",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "적분의 활용"
    ],
    "wide": false,
    "content": "곡선 $y=x(x-a)^2$과 직선 $y=x$로 둘러싸인 두 도형의 넓이가 같을 때, 상수 $a$의 값은? $(단, a>0)$ [4.5점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|14",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:539c07db4b97209cf0a5085b2d22a55bdb196dcca46f0bf129d6e9fac51e3f50"
  },
  {
    "id": 15,
    "level": "중",
    "category": "정적분",
    "originalCategory": "정적분",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "정적분"
    ],
    "wide": false,
    "content": "$lim_{n\toinfty}left{2nint_1^{\frac{n+1}{n}}(x^3-2x^2+3x+5),dx\right}$의 값은? [4.6점]",
    "choices": [
      "$10$",
      "$11$",
      "$12$",
      "$13$",
      "$14$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|15",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5472111e340100b022a7430ec84a95fa7807be28a4f99dce70187cc52bb26c58"
  },
  {
    "id": 16,
    "level": "중",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "적분의 활용"
    ],
    "wide": false,
    "content": "곡선 $y=-dfrac12x^2+6x$와 $x$축으로 둘러싸인 도형의 넓이가 직선 $y=mx$에 의하여 이등분될 때, 상수 $m$에 대하여 $(6-m)^3$의 값은? [4.7점]",
    "choices": [
      "$60$",
      "$72$",
      "$84$",
      "$96$",
      "$108$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|16",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e5d851fe3f62f1abcce389fdbadc0b34f1aca1184f008daf7c50555bfd2f39cc"
  },
  {
    "id": 17,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "실수 $a$에 대하여 두 함수 $f(x)=dfrac14x^4-2x^2+x+6$, $g(x)=x+a$의 그래프가 만나는 서로 다른 점의 개수를 $k(a)$라 할 때, $sum_{a=1}^{12}k(a)$의 값은? [4.8점]",
    "choices": [
      "$31$",
      "$29$",
      "$27$",
      "$25$",
      "$24$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|17",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f2b5916337b237012070fe3cbd40b69a14a9d8484b75a28da600f4597f04cd98"
  },
  {
    "id": 18,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "수직선 위를 움직이는 두 점 $A,B$의 시각 $t$에서의 위치를 각각 $f(t),g(t)$라 할 때, 두 함수 $y=f(t),y=g(t)$의 그래프가 다음과 같다. <보기>에서 옳은 것만을 있는 대로 고른 것은?\n(단, $fprime(a)=fprime(d)=0$, $gprime(a)=gprime(e)=0$) [4.8점]\n<보기>\nㄱ. 두 점 $A,B$는 $d<t<e$에서 서로 같은 방향으로 움직인다.\nㄴ. 두 점 $A,B$는 $0<t<10$에서 두 번 만난다.\nㄷ. $t=a$에서 두 점 $A,B$의 가속도는 모두 음의 값을 갖는다.",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/22_팔마고_2학기_기말_고2_수학II/q018_visual.png",
    "visualAsset": "assets/images/22_팔마고_2학기_기말_고2_수학II/q018_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 100,
      "y1": 1328,
      "x2": 810,
      "y2": 1690
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|18",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/22_팔마고_2학기_기말_고2_수학II/q018_visual.png",
      "assetSha256": "sha256:e00b87d463085e2b113df2df7438e67a307483a7ddfb2bf9c9ac4657af4b7bba",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
      "sourceQuestionNo": "18",
      "sourcePageNo": 5,
      "sourcePageEvidence": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png",
      "sourcePageEvidencePaths": [
        "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png"
      ],
      "sourceBBox": {
        "x1": 170,
        "y1": 1380,
        "x2": 800,
        "y2": 1680
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 630,
      "naturalHeight": 300,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5f06e4f881f40219b203f49e5ba2c459875deae62be8ef0ea5162189424d315d"
  },
  {
    "id": 19,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "어느 전망대에 설치된 엘리베이터는 1층에서 출발하여 꼭대기까지 올라가는 동안 출발 후 처음 2초 동안은 속도가 매초 $3,mathrm{m}$씩 증가하고 2초 후부터 10초까지는 등속도로 올라가며, 10초 후부터는 매초 $2,mathrm{m}$씩 감소하게 되어 멈춘다고 한다. 이 엘리베이터가 출발하여 멈출 때까지 움직인 거리는? [4.8점]",
    "choices": [
      "$63,mathrm{m}$",
      "$65,mathrm{m}$",
      "$67,mathrm{m}$",
      "$69,mathrm{m}$",
      "$71,mathrm{m}$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "19",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 19,
    "displayNo": "19",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|19",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:08c1aa268e191670150d172b1a853d0604456ceef13c0bf7a3635b82b3a58b07"
  },
  {
    "id": 20,
    "level": "중",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3+ax^2+ax+1$이 열린구간 $(-2,1)$에서 극댓값과 극솟값을 모두 갖도록 하는 실수 $a$의 값의 범위를 구하고, 그 풀이과정을 서술하시오. [6점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형1",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 20,
    "displayNo": "서술형1",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|서술형1",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:90eb3b97a65513a90e1eafe37cb77e42810b8839578b3b0c674f2aeda5e41054"
  },
  {
    "id": 21,
    "level": "중",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "적분의 활용"
    ],
    "wide": false,
    "content": "$xge a$에서 $f(x)>0$인 연속함수 $f(x)$에 대하여 다음 그림과 같은 영역의 넓이를 $S(x)$라 하자. $f(a)=10$이고, $Fprime(x)=f(x)$일 때, $lim_{x\to a+}dfrac{2S(x)}{x-a}$의 값을 구하고, 그 풀이과정을 서술하시오. [7점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "assets/images/22_팔마고_2학기_기말_고2_수학II/q021_visual.png",
    "visualAsset": "assets/images/22_팔마고_2학기_기말_고2_수학II/q021_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 285,
      "y1": 400,
      "x2": 740,
      "y2": 800
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형2",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 21,
    "displayNo": "서술형2",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|서술형2",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/22_팔마고_2학기_기말_고2_수학II/q021_visual.png",
      "assetSha256": "sha256:0b0b8a54192c182cb366b8409862e7ad7f1b662aab307a689cd7a1f7c9049b28",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
      "sourceQuestionNo": "서술형2",
      "sourcePageNo": 6,
      "sourcePageEvidence": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p006.png",
      "sourcePageEvidencePaths": [
        "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p006.png"
      ],
      "sourceBBox": {
        "x1": 285,
        "y1": 400,
        "x2": 740,
        "y2": 800
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 455,
      "naturalHeight": 400,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:2ece707bdf5caf951f19a95ce9ad4c9c05b825f6f08977874b478490e47ca5bc"
  },
  {
    "id": 22,
    "level": "중",
    "category": "적분의 활용",
    "originalCategory": "적분의 활용",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "적분의 활용"
    ],
    "wide": false,
    "content": "어느 박람회에 원기둥을 직접 만들어 보는 체험관이 있다. 이 체험관에서는 겉넓이가 $k$로 일정하면서 부피가 최대인 원기둥을 만드는 행사를 열었다. 이때, 부피가 최대인 원기둥의 밑면의 반지름의 길이와 높이의 비율 중 가장 작은 자연수의 비로 나타내고, 그 풀이과정을 서술하시오. [7점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "22_팔마고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2022_팔마고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형3",
    "sourceArchiveFile": "original/high/h2/2final/22_팔마고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 22,
    "displayNo": "서술형3",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3",
    "sourceIdentityKey": "sha256:81806e70e69932928eeff5d90706d4c32ee45155133a421670e7c1d57ce929b3|서술형3",
    "sourceEvidencePath": "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "archive-work/evidence/nightly/runs/2026-10-02/source-intake-heartbeat-2026-10-02-0544-kst/22_팔마고_2학기_기말_고2_수학II/pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\22_팔마고_2학기_기말_고2_수학II\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.85,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:081f6785da0128fd5686a11d83a01d9415d25555471721cbdf42d97b07ff74c4"
  }
];
