window.examTitle = "23_강남여고_2학기_기말_고2_수학II";
window.questionBank = [
  {
    "id": 1,
    "level": "",
    "category": "미분계수",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-03",
    "standardUnit": "미분계수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-M2-03-DERIVATIVE",
    "subUnit": "미분",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3+4x^2-2$에 대하여 $f'(-1)$의 값은? [3점]",
    "choices": [
      "$-1$",
      "$-2$",
      "$-3$",
      "$-4$",
      "$-5$"
    ],
    "answer": "⑤",
    "solution": "$f'(x)=3x^2+8x$이므로 $f'(-1)=3-8=-5$이다. 따라서 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-03-DERIVATIVE",
    "problemTypeKey": "PT_DERIVATIVE_DEFINITION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:44c4339fea381e99ba6f5a3734c83e7ba907cb09e4c111ac6a222f97d467f0dd"
  },
  {
    "id": 2,
    "level": "",
    "category": "미분계수",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-03",
    "standardUnit": "미분계수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-M2-03-DERIVATIVE_DEFINITION",
    "subUnit": "미분계수",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "함수 $f(x)$에 대하여 $f'(1)=2$일 때, $\\lim_{h\\to0}\\dfrac{f(1+4h)-f(1)}{h}$의 값은? [3점]",
    "choices": [
      "$\\dfrac{1}{2}$",
      "$2$",
      "$4$",
      "$8$",
      "$10$"
    ],
    "answer": "④",
    "solution": "$u=4h$로 두면 극한은 $4\\lim_{u\\to0}\\dfrac{f(1+u)-f(1)}u=4f'(1)$이다. $f'(1)=2$이므로 값은 $8$, 정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-03-DERIVATIVE_DEFINITION",
    "problemTypeKey": "PT_DERIVATIVE_DEFINITION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7d4081dd420f569f8529c4f640ee8d27b2ae47812a35d434a4f66d2eeadbc146"
  },
  {
    "id": 3,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^2+4x-21$에 대하여 구간 $[-7,3]$에서 롤의 정리를 만족시키는 상수 $c$의 값은? [3점]",
    "choices": [
      "$-2$",
      "$-1$",
      "$0$",
      "$1$",
      "$2$"
    ],
    "answer": "①",
    "solution": "$f(-7)=49-28-21=0$, $f(3)=9+12-21=0$이므로 롤의 정리를 적용할 수 있다. $f'(x)=2x+4$에서 $f'(c)=0$이면 $c=-2$이다. 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_MEAN_VALUE_THEOREM",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:05fe4da95ab861f0e87540cf2f2ddf797dbf3b20f3fe36f27e7da06091776a01"
  },
  {
    "id": 4,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^2+3x$에 대하여 닫힌구간 $[0,2]$에서 평균값 정리를 만족시키는 실수 $c$의 값은? [3.5점]",
    "choices": [
      "$\\dfrac{1}{2}$",
      "$1$",
      "$\\dfrac{3}{2}$",
      "$2$",
      "$\\dfrac{5}{2}$"
    ],
    "answer": "②",
    "solution": "평균변화율은 $\\dfrac{f(2)-f(0)}{2-0}=\\dfrac{10-0}{2}=5$이다. $f'(x)=2x+3$이므로 $2c+3=5$에서 $c=1$이다. 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_MEAN_VALUE_THEOREM",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:98d4e621997f9d3ca50649dae2d521063df5007187b2dc66ccf17fb4c9a6c11d"
  },
  {
    "id": 5,
    "level": "",
    "category": "정적분",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "$\\int_1^5(2x+7)\\,dx$의 값은? [3.5점]",
    "choices": [
      "$50$",
      "$51$",
      "$52$",
      "$53$",
      "$54$"
    ],
    "answer": "③",
    "solution": "원시함수는 $x^2+7x$이다. 따라서 $\\int_1^5(2x+7)dx=[x^2+7x]_1^5=60-8=52$이고, 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|5",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_OPERATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4daf70a9296f0acb4a5712676f012f16e90850b9d53ecb1065976e5b35f530da"
  },
  {
    "id": 6,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "수직선 위를 움직이는 점 $P$의 시각 $t$에서 위치 $x$가 $x=-2t^3+9t^2$일 때, 점 $P$가 운동 방향을 바꾸는 시각은? [3.5점]",
    "choices": [
      "$2$",
      "$3$",
      "$4$",
      "$5$",
      "$6$"
    ],
    "answer": "②",
    "solution": "위치의 도함수는 속도이므로 $x'(t)=-6t^2+18t=-6t(t-3)$이다. $0<t<3$에서는 양수, $t>3$에서는 음수이므로 운동 방향은 $t=3$에서 바뀐다. 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|6",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MOTION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5630ca3ae2f1d1b29d34d9196504b234c2ffbd06fe7af95191c40dadcad55355"
  },
  {
    "id": 7,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "열린구간 $(-3,3)$에서 연속인 함수 $f(x)$의 도함수 $y=f'(x)$의 그래프가 그림과 같다. 함수 $f(x)$가 $x=a$에서 극대이고 $x=b$에서 극소일 때, $a+b$의 값은? (단, $-3<a<3$, $-3<b<3$) [3.5점]",
    "choices": [
      "$1$",
      "$2$",
      "$0$",
      "$-1$",
      "$-2$"
    ],
    "answer": "④",
    "solution": "그림에서 $-3<x<-2$일 때 $f'(x)>0$, $-2<x<1$일 때 $f'(x)<0$이다. $x=0$에서 도함수는 0이지만 부호는 바뀌지 않는다.\n$x=1$에서 도함수는 정의되지 않지만 함수 $f$는 연속이고, 왼쪽에서 감소하다 오른쪽에서 증가하므로 $f$는 $b=1$에서 극소이다. $x=2$에서도 도함수 부호는 양수로 유지된다.\n따라서 $a=-2$, $b=1$이고 $a+b=-1$이다. 정답은 ④이다.",
    "image": "assets/images/23_강남여고_2학기_기말_고2_수학II/q007_visual.png",
    "visualAsset": "assets/images/23_강남여고_2학기_기말_고2_수학II/q007_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 1040,
      "y1": 1070,
      "x2": 1620,
      "y2": 1330
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|7",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.98,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_강남여고_2학기_기말_고2_수학II/q007_visual.png",
      "assetSha256": "sha256:166089d13304cba5dee962e0c67613a04adc6b4b91e01f4e3e640a78156a3900",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
      "sourceQuestionNo": "7",
      "sourcePageNo": 1,
      "sourcePageEvidence": "pages/page_p001.png",
      "sourcePageEvidencePaths": [
        "pages/page_p001.png"
      ],
      "sourceBBox": {
        "x1": 1040,
        "y1": 1070,
        "x2": 1620,
        "y2": 1330
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 580,
      "naturalHeight": 260,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_EXTREMA",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7ae8c5f63022fa758624a1a9e9f20d9e0f195b8806a9482c03635ce9765ed4b6"
  },
  {
    "id": 8,
    "level": "",
    "category": "접선의 방정식",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-05",
    "standardUnit": "접선의 방정식",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-M2-05-TANGENT",
    "subUnit": "접선의 방정식",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "곡선 $y=x^2+ax+b$ 위의 점 $(2,3)$에서 접하는 접선의 기울기가 $6$일 때, 상수 $a$, $b$에 대하여 $a+b$의 값은? [3.5점]",
    "choices": [
      "$-1$",
      "$-2$",
      "$-3$",
      "$-4$",
      "$-5$"
    ],
    "answer": "③",
    "solution": "접선 기울기는 $f'(x)=2x+a$이다. $x=2$에서 $4+a=6$이므로 $a=2$이다. 또 $(2,3)$이 곡선 위에 있으므로 $4+2a+b=3$, 따라서 $b=-5$이다. $a+b=-3$이므로 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|8",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-05-TANGENT",
    "problemTypeKey": "PT_TANGENT_DERIVATIVE",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:6b9ea6747af8d82dcb963b4ebe1893c6117ffafccde2192c96cff0282de99d5b"
  },
  {
    "id": 9,
    "level": "",
    "category": "정적분",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "$\\int_{-a}^{a}(-2x+4)\\,dx=16$을 만족시키는 실수 $a$의 값은? [3.5점]",
    "choices": [
      "$2$",
      "$3$",
      "$4$",
      "$5$",
      "$6$"
    ],
    "answer": "①",
    "solution": "$-2x$는 홀함수이므로 대칭구간에서 적분값은 $0$이다. 따라서 $\\int_{-a}^a(-2x+4)dx=4(2a)=8a=16$이고 $a=2$, 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|9",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_OPERATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:2a67da89e5d768eca2d991a7b834c8e808f5fd7ed1ac14144a8822e4ec4d3bf2"
  },
  {
    "id": 10,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3-3x^2-9x+a$의 극댓값이 $12$일 때, 함수 $f(x)$의 극솟값은? (단, $a$는 상수이다.) [4점]",
    "choices": [
      "$-8$",
      "$-12$",
      "$-16$",
      "$-20$",
      "$-24$"
    ],
    "answer": "④",
    "solution": "$f'(x)=3x^2-6x-9=3(x-3)(x+1)$이므로 극대는 $x=-1$, 극소는 $x=3$에서 생긴다. $f(-1)=5+a=12$에서 $a=7$이다. 그러면 $f(3)=27-27-27+7=-20$이므로 정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|10",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_EXTREMA",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:2f26be3d4152cb01708470a9241b59ff38afceca6b2693c2aae06964e110ef34"
  },
  {
    "id": 11,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 정의된 함수 $f(x)=x^3+x^2-ax+1$이 역함수가 존재하도록 하는 실수 $a$의 최댓값은? [4점]",
    "choices": [
      "$-\\dfrac{1}{2}$",
      "$-\\dfrac{1}{3}$",
      "$-\\dfrac{1}{4}$",
      "$-\\dfrac{1}{5}$",
      "$-\\dfrac{1}{6}$"
    ],
    "answer": "②",
    "solution": "역함수가 존재하려면 이 삼차함수는 단조증가해야 하므로 $f'(x)=3x^2+2x-a\\ge0$이어야 한다. 이 이차식의 판별식은 $4+12a$이므로 $4+12a\\le0$, 즉 $a\\le-\\dfrac13$이다. 등호일 때도 도함수는 한 점에서만 $0$이고 함수는 엄격히 증가하므로 최댓값은 $-\\dfrac13$, 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|11",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MONOTONICITY",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:967f06d98e463a6694c8c32daadf8a16f7ab54cab02f2b4dda57268301a22acd"
  },
  {
    "id": 12,
    "level": "",
    "category": "적분의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "그림과 같이 곡선 $y=f(x)$에 대하여 $A=\\int_{-3}^{1}|f(x)|\\,dx=3$, $B=\\int_{1}^{4}|f(x)|\\,dx=2$일 때, $\\int_{-3}^{4}\\{f(x)+2x\\}\\,dx$의 값은? [4점]",
    "choices": [
      "$5$",
      "$6$",
      "$7$",
      "$8$",
      "$9$"
    ],
    "answer": "②",
    "solution": "그림에서 $f(x)<0$인 $[-3,1]$의 적분은 $-A=-3$이고, $[1,4]$의 적분은 $B=2$이다. 따라서 $\\int_{-3}^4 f(x)dx=-1$이다. 또 $\\int_{-3}^4 2x dx=[x^2]_{-3}^4=16-9=7$이다. 구하는 값은 $-1+7=6$, 정답은 ②이다.",
    "image": "assets/images/23_강남여고_2학기_기말_고2_수학II/q012_visual.png",
    "visualAsset": "assets/images/23_강남여고_2학기_기말_고2_수학II/q012_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 1160,
      "y1": 890,
      "x2": 1515,
      "y2": 1170
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|12",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.98,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_강남여고_2학기_기말_고2_수학II/q012_visual.png",
      "assetSha256": "sha256:401a3a11ea77ae6b24070e89df3054c0faa6decc2a69b7594e6746a16aecf2fb",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
      "sourceQuestionNo": "12",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 1160,
        "y1": 890,
        "x2": 1515,
        "y2": 1170
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 355,
      "naturalHeight": 280,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "PT_AREA_BY_DEFINITE_INTEGRAL",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:491f02b2c39fc1f169f7d926ece4d4dec27afb2f3481e77d0fd33e114ad65f6c"
  },
  {
    "id": 13,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3-12x-1$일 때, 함수 $y=|f(x)|$의 그래프와 직선 $y=a$가 서로 다른 세 점에서만 만날 때의 양수 $a$의 값은? [4점]",
    "choices": [
      "$14$",
      "$15$",
      "$16$",
      "$17$",
      "$18$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|13",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_GRAPH_ANALYSIS",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a32c62996bf515fd0b99133b4fd1041c12a64d781d44fa64994288e568c5e7c7"
  },
  {
    "id": 14,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "그림과 같이 한 변의 길이가 $12\\,\\mathrm{cm}$인 정사각형 모양의 종이의 네 귀퉁이에서 같은 크기의 정사각형을 잘라 내고 남은 부분을 접어서 뚜껑이 없는 직육면체 모양의 상자를 만들려고 한다. 상자의 부피의 최댓값은? [4점]",
    "choices": [
      "$124$",
      "$126$",
      "$128$",
      "$130$",
      "$132$"
    ],
    "answer": "③",
    "solution": "귀퉁이에서 한 변이 $x$인 정사각형을 자르면 상자 밑면은 $(12-2x)\\times(12-2x)$, 높이는 $x$이다. $V(x)=x(12-2x)^2$이고 $0<x<6$이다. $V'(x)=(12-2x)(12-6x)$이므로 $0<x<2$에서 증가하고 $2<x<6$에서 감소한다. 따라서 최댓값은 $V(2)=2\\cdot8^2=128$, 정답은 ③이다.",
    "image": "assets/images/23_강남여고_2학기_기말_고2_수학II/q014_visual.png",
    "visualAsset": "assets/images/23_강남여고_2학기_기말_고2_수학II/q014_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 355,
      "y1": 1880,
      "x2": 620,
      "y2": 2180
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|14",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.97,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_강남여고_2학기_기말_고2_수학II/q014_visual.png",
      "assetSha256": "sha256:c73dad761ff895301631241ef771aed02ac93777640e565999b762287a8de930",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
      "sourceQuestionNo": "14",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 355,
        "y1": 1880,
        "x2": 620,
        "y2": 2180
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 265,
      "naturalHeight": 300,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MAX_MIN",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:6829a0ea5e04d05aad3711e8756533b5a23cef5835d11fdea8c31933e96c5d28"
  },
  {
    "id": 15,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=x^3-x+6$, $g(x)=x^2+a$가 있다. $x\\ge0$인 모든 실수 $x$에 대하여 부등식 $f(x)\\ge g(x)$가 성립할 때, 실수 $a$의 최댓값은? [4점]",
    "choices": [
      "$5$",
      "$6$",
      "$7$",
      "$8$",
      "$9$"
    ],
    "answer": "①",
    "solution": "$f(x)-g(x)=x^3-x^2-x+6-a=\\phi(x)-a$라 두자. $\\phi'(x)=3x^2-2x-1=(3x+1)(x-1)$이므로 $x\\ge0$에서 $\\phi$는 $[0,1]$에서 감소하고 $[1,\\infty)$에서 증가한다. 최솟값은 $\\phi(1)=5$이다. 모든 $x\\ge0$에서 $\\phi(x)-a\\ge0$이려면 $a\\le5$이므로 최댓값은 5, 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|15",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_EQUATION_INEQUALITY",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_RANGE"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:acd3868093a5619ac09dc9a2150535c6fa1657608df5cc024b82f14e033e6383"
  },
  {
    "id": 16,
    "level": "",
    "category": "정적분",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "이차함수 $f(x)=x^2-(a+1)x+a$가 $\\int_1^2(x^2+x)f'(x)\\,dx+\\int_1^2(2x+1)f(x)\\,dx=-12$를 만족시킬 때, $\\int_1^a f(x)\\,dx$의 값은? (단, $a$는 상수이다.) [4점]",
    "choices": [
      "$-\\dfrac{5}{2}$",
      "$-3$",
      "$-\\dfrac{7}{2}$",
      "$-4$",
      "$-\\dfrac{9}{2}$"
    ],
    "answer": "⑤",
    "solution": "두 적분의 합은 곱의 미분법으로 $\\int_1^2\\{(x^2+x)f(x)' +(2x+1)f(x)\\}dx=[(x^2+x)f(x)]_1^2$이다. $f(1)=0$, $f(2)=2-a$이므로 $6(2-a)=-12$, 따라서 $a=4$이다. $f(x)=x^2-5x+4$이고 $\\int_1^4 f(x)dx=[\\frac{x^3}{3}-\\frac{5x^2}{2}+4x]_1^4=-\\frac92$이다. 정답은 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|16",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_OPERATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:6519c08406fbdd8cb82f5dda1896d7342508a6d2ecb1061f51a01919a72f2aa9"
  },
  {
    "id": 17,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "자연수 $n$에 대하여 $x$에 대한 방정식 $x^3-3x+n-2=0$의 서로 다른 실근의 개수를 $a_n$이라 할 때, $\\sum_{n=1}^{10}a_n$의 값은? [4점]",
    "choices": [
      "$17$",
      "$18$",
      "$19$",
      "$20$",
      "$21$"
    ],
    "answer": "①",
    "solution": "$h(x)=x^3-3x$라 두면 $h'(x)=3(x^2-1)$이고 극댓값은 $h(-1)=2$, 극솟값은 $h(1)=-2$이다. 방정식은 $h(x)=2-n$이다.\n$n=1,2,3$이면 $2-n$은 $(-2,2)$에 있으므로 각각 서로 다른 실근이 3개이다.\n$n=4$이면 $2-n=-2$이므로 실근이 2개이다.\n$n=5,\\ldots,10$이면 $2-n<-2$이므로 각각 실근이 1개이다.\n따라서 $\\sum_{n=1}^{10}a_n=3+3+3+2+6=17$이고, 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|17",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_GRAPH_ANALYSIS",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f103878c1bbd34db80d44939a7bf8504df422bd1368fe87ab70239e9d2a929a1"
  },
  {
    "id": 18,
    "level": "",
    "category": "적분의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "그림과 같이 함수 $f(x)=x^3-x$에 대하여 구간 $[0,1]$에서 곡선 $y=f(x)$와 $x$축으로 둘러싸인 부분의 넓이를 $S_1$이라 하고, 구간 $[1,a]$에서 곡선 $y=f(x)$와 $x$축 및 직선 $x=a$로 둘러싸인 부분의 넓이를 $S_2$라 하자. $4S_1=S_2$를 만족시키는 $1$보다 큰 상수 $a$의 값은? [4.5점]",
    "choices": [
      "$\\sqrt{2}$",
      "$\\sqrt{3}$",
      "$2$",
      "$\\sqrt{5}$",
      "$\\sqrt{6}$"
    ],
    "answer": "②",
    "solution": "$0\\le x\\le1$에서 $x^3-x\\le0$이므로 $S_1=\\int_0^1(x-x^3)dx=\\dfrac14$이다. $x\\ge1$에서는 $x^3-x\\ge0$이므로 $S_2=\\int_1^a(x^3-x)dx=\\dfrac{a^4}{4}-\\dfrac{a^2}{2}+\\dfrac14$이다. $S_2=4S_1=1$에서 $a^4-2a^2-3=0$, 즉 $(a^2-3)(a^2+1)=0$이다. $a>1$이므로 $a=\\sqrt3$, 정답은 ②이다.",
    "image": "assets/images/23_강남여고_2학기_기말_고2_수학II/q018_visual.png",
    "visualAsset": "assets/images/23_강남여고_2학기_기말_고2_수학II/q018_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 315,
      "y1": 460,
      "x2": 820,
      "y2": 925
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|18",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.98,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_강남여고_2학기_기말_고2_수학II/q018_visual.png",
      "assetSha256": "sha256:d824938d4c44395d48b03cc907b7d9aba4f4b1fd1c626ef43c47ecc6414ab85f",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
      "sourceQuestionNo": "18",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 315,
        "y1": 460,
        "x2": 820,
        "y2": 925
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 505,
      "naturalHeight": 465,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "PT_AREA_BY_DEFINITE_INTEGRAL",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_RANGE"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d7e491ace2e777c679b66aef7a0e80ce73cbb122f2e18c4e44173588d7973d50"
  },
  {
    "id": 19,
    "level": "",
    "category": "적분의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "함수 $f(x)=\\begin{cases}2x(3-x)&(x<3)\\\\x-3&(x\\ge3)\\end{cases}$에 대하여 함수 $F(x)$를 $F(x)=\\int_1^x f(t)\\,dt$로 정의할 때, 다음 보기 중 항상 옳은 것만을 있는 대로 고른 것은? [4.5점]\n(가) $F(-1)=\\dfrac{4}{3}$\n(나) 함수 $F(x)$의 극솟값은 양수이다.\n(다) $\\int_{-1}^{1}F(x)\\,dx=-\\dfrac{8}{3}$",
    "choices": [
      "(가)",
      "(가), (나)",
      "(가), (다)",
      "(나), (다)",
      "(가), (나), (다)"
    ],
    "answer": "③",
    "solution": "(가) $\\int_{-1}^1(6x-2x^2)dx=-\\dfrac43$이므로 $F(-1)=\\int_1^{-1}f(x)dx=\\dfrac43$이다. 참이다.\n(나) $F'=f$이고 $x<0$에서 $f(x)<0$, $0<x<3$에서 $f(x)>0$이다. 따라서 $F$는 $x=0$에서 극소이고 $F(0)=-\\int_0^1(6x-2x^2)dx=-\\dfrac73<0$이므로 거짓이다.\n(다) $-1\\le x\\le1$에서 $F(x)=3x^2-\\dfrac23x^3-\\dfrac73$이다. 따라서 $\\int_{-1}^1F(x)dx=2-\\dfrac{14}3=-\\dfrac83$이고 (다)는 참이다.\n그러므로 항상 옳은 것은 (가), (다)이며 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "19",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 19,
    "displayNo": "19",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|19",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "PT_AREA_BY_DEFINITE_INTEGRAL",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:11dab3f252f2b6e1bd4a88b09fc85a961ac50731763c29cb8434614683c21818"
  },
  {
    "id": 20,
    "level": "",
    "category": "적분의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-09",
    "standardUnit": "적분의 활용",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-M2-09-INTEGRAL_APPLICATION",
    "subUnit": "적분의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "직선으로 움직이는 두 발사체 $A$, $B$를 발사한 지 $t$초 후의 속도를 각각 초속 $v_A(t)$ km, 초속 $v_B(t)$ km라고 하면 $v_A(t)=\\dfrac{1}{40}t^2$, $v_B(t)=at$ ($a$는 양수)라고 할 때, 다음 조건에 따라 두 발사체 $A$, $B$를 결합하려고 한다.\n<조건>\n(가) $A$를 발사한지 $2$초 후에 같은 지점에서 $B$를 발사한다.\n(나) 충격을 최소화하기 위해 결합하는 순간 $A$, $B$의 속도를 같게 한다.\n두 발사체 $A$, $B$가 결합하는 시간은 발사체 $A$가 발사된 지 $m$초 후일 때, $40(a+m)$의 값은? [4.5점]",
    "choices": [
      "$245$",
      "$246$",
      "$247$",
      "$248$",
      "$249$"
    ],
    "answer": "⑤",
    "solution": "결합 시각을 A가 발사된 뒤 $m$초라 하면 (가)에 따라 B는 발사 후 $m-2$초 움직였다.\nA의 위치는 $\\dfrac{m^3}{120}$, B의 위치는 $\\dfrac{a(m-2)^2}{2}$이다. 결합하므로 두 위치가 같아 $\\dfrac{m^3}{120}=\\dfrac{a(m-2)^2}{2}$이다.\n(나)의 속도 조건은 $\\dfrac{m^2}{40}=a(m-2)$이다. 두 식을 함께 쓰면 $m>2$이고 $\\dfrac{m}{120}=\\dfrac{m-2}{80}$을 얻어 $m=6$이다. 그러면 $a=\\dfrac{m^2}{40(m-2)}=\\dfrac9{40}$이다.\n따라서 $40(a+m)=9+240=249$, 정답은 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "20",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 20,
    "displayNo": "20",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|20",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_M2_09_INTEGRAL_APPLICATION",
    "problemTypeKey": "PT_MOTION_BY_INTEGRAL",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_POSITIVE"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5d31773239d656af488c50cbc3f3f8423948da5339b8b1035491c6c2074cfe75"
  },
  {
    "id": 21,
    "level": "",
    "category": "정적분",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 연속인 함수 $f(x)$가 다음 조건을 만족시킬 때, $\\int_{-3}^{5}\\{4x+f(x)\\}\\,dx$의 값은?\n<조건>\n(가) 모든 실수 $x$에 대하여 $f(x)+f(-x)=0$이다.\n(나) $\\int_{-2}^{3}f(x)\\,dx=6$\n(다) $\\int_{-5}^{-2}f(x)\\,dx=-20$ [4.5점]",
    "choices": [
      "$46$",
      "$47$",
      "$48$",
      "$49$",
      "$50$"
    ],
    "answer": "①",
    "solution": "(가) $f$는 홀함수이므로 $\\int_{-3}^3f(x)dx=0$이다.\n(나) $\\int_{-2}^3f(x)dx=\\int_{-2}^2f(x)dx+\\int_2^3f(x)dx$이고 첫 적분은 0이므로 $\\int_2^3f(x)dx=6$이다.\n(다) 홀함수의 대칭성에서 $\\int_2^5f(x)dx=-\\int_{-5}^{-2}f(x)dx=20$이다. 따라서 $\\int_3^5f(x)dx=20-6=14$이다.\n그러므로 $\\int_{-3}^5f(x)dx=14$이다. 또 $\\int_{-3}^{5}4x\\,dx=[2x^2]_{-3}^5=32$이므로 구하는 값은 $14+32=46$, 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "21",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 21,
    "displayNo": "21",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|21",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_OPERATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b59254093024d558cc4e5b971b2a068c0305bef68f94ab721cf94be5b4abf1a0"
  },
  {
    "id": 22,
    "level": "",
    "category": "정적분",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "임의의 실수 $x$에 대하여 $\\int_a^x f(t)\\,dt=2x^2-8x+6$을 만족시키는 연속함수 $f(x)$에 대하여 $f(4)+a$의 값을 구하시오. (단, $a>1$) [5점]",
    "choices": [],
    "answer": "$11$",
    "solution": "양변을 $x$로 미분하면 $f(x)=4x-8$이다. $x=a$를 대입하면 적분은 $0$이므로 $2a^2-8a+6=0$, 즉 $a=1$ 또는 $a=3$이다. 조건 $a>1$에서 $a=3$이므로 $f(4)+a=8+3=11$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형1",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 22,
    "displayNo": "서술형1",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|서술형1",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_FUNCTION_RELATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_RANGE"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:728b161fdf3e0a708984f6ac157def4afcf9e0da7bdca28b4732b84768f2d0fc"
  },
  {
    "id": 23,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "수직선 위를 움직이는 두 점 $P$, $Q$의 시각 $t$에서의 위치가 각각 $x_P(t)=\\dfrac{5}{3}t^3+\\dfrac{2}{3}$, $x_Q(t)=\\dfrac{9}{2}t^2+2t+1$일 때, 두 점 $P$, $Q$의 속도가 같아지는 순간에 두 점 사이의 거리를 구하시오. [5점]",
    "choices": [],
    "answer": "$9$",
    "solution": "속도를 구하면 $v_P=5t^2$, $v_Q=9t+2$이다. $5t^2=9t+2$에서 $t=2$ 또는 $t=-\\dfrac15$이다. 발사 후 시간이므로 $t=2$를 쓴다. 이때 $x_P=\\dfrac53(2)^3+\\dfrac23=14$, $x_Q=\\dfrac92(2)^2+2(2)+1=23$이므로 두 점 사이의 거리는 9이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형2",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 23,
    "displayNo": "서술형2",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|서술형2",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_MOTION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:26f89a6f9cc981e8f321746b1b2a992a25bf048b8684a400d3f6f0f3668d6821"
  },
  {
    "id": 24,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "subUnit": "도함수의 활용",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "함수 $f(x)=x^3+ax^2+bx+c$의 도함수 $y=f'(x)$의 그래프가 다음 그림과 같다. 함수 $f(x)$의 극댓값이 $5$일 때, 상수 $a$, $b$, $c$의 값과 극솟값을 구하시오. [5점]",
    "choices": [],
    "answer": "$a=-6$, $b=0$, $c=5$, 극솟값 $-27$",
    "solution": "그림에서 $f'(x)$의 영점은 $0,4$이고 포물선은 위로 열린다. 최고차항 계수가 3이므로 $f'(x)=3x(x-4)$이다.\n적분하면 $f(x)=x^3-6x^2+C$이다. $x=0$에서 극댓값이 5이므로 $C=5$이다. 따라서 $a=-6,b=0,c=5$이다.\n$x=4$에서 극소이므로 $f(4)=64-96+5=-27$이다.",
    "image": "assets/images/23_강남여고_2학기_기말_고2_수학II/q024_visual.png",
    "visualAsset": "assets/images/23_강남여고_2학기_기말_고2_수학II/q024_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 220,
      "y1": 1780,
      "x2": 740,
      "y2": 2200
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형3",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 24,
    "displayNo": "서술형3",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|서술형3",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0.98,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_강남여고_2학기_기말_고2_수학II/q024_visual.png",
      "assetSha256": "sha256:21733aec0687e5f2e9c9b462e3a28cd17ec5a7cbefff90e24b300299625c6c58",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
      "sourceQuestionNo": "서술형3",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 220,
        "y1": 1780,
        "x2": 740,
        "y2": 2200
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 520,
      "naturalHeight": 420,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-06-DERIVATIVE_APPLICATION",
    "problemTypeKey": "PT_DERIVATIVE_FUNCTION_DETERMINATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b4195f624dab185a53e510feabfdb31aa2600be843362cc9cff9789296eb2a50"
  },
  {
    "id": 25,
    "level": "",
    "category": "정적분",
    "originalCategory": "",
    "standardCourse": "수학II",
    "standardUnitKey": "H15-M2-08",
    "standardUnit": "정적분",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "subUnit": "정적분",
    "subUnitConfidence": "category_or_cue_inferred",
    "subUnitClassificationDepth": "complete_category",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "다항함수 $f(x)$가 $\\int_{-3}^{1}f(x)\\,dx=5$, $\\int_0^5 f(x)\\,dx=6$, $\\int_1^5 f(x)\\,dx=8$을 만족시킬 때, 정적분 $\\int_{-3}^{0}\\{f(x)-4x\\}\\,dx$를 구하시오. [5점]",
    "choices": [],
    "answer": "$25$",
    "solution": "구간을 나누면 $\\int_{-3}^1f=\\int_{-3}^0f+\\int_0^1f=5$이다. 또한 $\\int_0^5f=\\int_0^1f+\\int_1^5f=6$이므로 $\\int_0^1f=6-8=-2$이다. 따라서 $\\int_{-3}^0f=5-(-2)=7$. 그리고 $\\int_{-3}^{0}4x\\,dx=[2x^2]_{-3}^0=-18$. 구하는 값은 $7-(-18)=25$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_강남여고_2학기_기말_고2_수학II",
    "sourceFile": "D:\\기출\\(4)2기말\\수2\\2023_강남여고2_수2_2기말.pdf",
    "sourceQuestionNo": "서술형4",
    "sourceArchiveFile": "original/high/h2/2final/23_강남여고_2학기_기말_고2_수학II.js",
    "sourceOrdinal": 25,
    "displayNo": "서술형4",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859",
    "sourceIdentityKey": "sha256:d634108ff68b961a5b9c98ecc395f8264d93eaa96b30c5a5d9cd952166e90859|서술형4",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-03\\AP------\\archive-work\\evidence\\23_강남여고_2학기_기말_고2_수학II\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0,
    "choicesConfidence": 0,
    "visualAssetConfidence": 0,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-M2-08-DEFINITE_INTEGRAL",
    "problemTypeKey": "PT_DEFINITE_INTEGRAL_OPERATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:3311ccc9fe37c048966eb2021bbd7287bcc0cc26c7996aa0b376918a3e965de8"
  }
];
