window.examTitle = "23_금당고_2학기_기말_고2_확률과통계";
window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "조건부확률",
    "originalCategory": "조건부확률",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-04",
    "standardUnit": "조건부확률",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-PS-04-INDEPENDENCE",
    "subUnit": "독립사건과 곱셈정리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "두 사건 $A,B$가 서로 독립이고, $P(A)=\\frac{3}{5}$, $P(A\\cap B)=\\frac{3}{10}$일 때, $P(B)$의 값은? (3.1점)",
    "choices": [
      "$\\frac{1}{2}$",
      "$\\frac{2}{3}$",
      "$\\frac{1}{4}$",
      "$\\frac{1}{5}$",
      "$\\frac{2}{5}$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_PS_04_INDEPENDENCE",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:df6407de3aaecdd4073126f711d9e9c74d5b73106ac37d19edc96b3ff0168ab7"
  },
  {
    "id": 2,
    "level": "하",
    "category": "확률분포",
    "originalCategory": "확률분포",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-05",
    "standardUnit": "확률분포",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-PS-05-BINOMIAL_NORMAL",
    "subUnit": "이항분포와 정규분포",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "확률변수 $X$가 이항분포 $B(18,\\frac{2}{3})$을 따를 때, $X$의 평균, 분산의 값은? (3.1점)",
    "choices": [
      "6, 2",
      "8, 4",
      "10, 2",
      "12, 4",
      "16, 6"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-05-BINOMIAL_NORMAL",
    "problemTypeKey": "PT_BINOMIAL_DISTRIBUTION",
    "templateKey": "TPL_BINOMIAL_PARAMETER_MOMENTS",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7689fe654d70056b7075e968f2e30aacbfdcc8ed8aa7f671265ce6290ccc4b43"
  },
  {
    "id": 3,
    "level": "하",
    "category": "확률분포",
    "originalCategory": "확률분포",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-05",
    "standardUnit": "확률분포",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-PS-05-RANDOM_VARIABLE",
    "subUnit": "확률변수와 기댓값",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "다음 확률변수 중 연속확률변수에 해당하는 것은? (3.3점)",
    "choices": [
      "가위바위보를 20번 하는 시행에서 이긴 횟수",
      "주사위 1개를 1번 던지는 시행에서 나오는 눈의 수",
      "2학기 중간고사에서 받을 수 있는 확률과 통계 성적",
      "동전 1개를 10번 던지는 시행에서 나오는 앞면의 횟수",
      "어느 정거장에 정확히 10분 간격으로 도착하는 버스를 기다리는 시행에서 기다리는 시간"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-05-RANDOM_VARIABLE",
    "problemTypeKey": "PT_RANDOM_VARIABLE_DISTRIBUTION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 1,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a4a8c9d590f6b8f7095b8c8809e55ad4a2689825c084f74311085d3cbeb6f9dc"
  },
  {
    "id": 4,
    "level": "중",
    "category": "조건부확률",
    "originalCategory": "조건부확률",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-04",
    "standardUnit": "조건부확률",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-PS-04-TOTAL_BAYES",
    "subUnit": "전확률과 베이즈",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "어느 음식점에서 하루의 매출 목표액을 달성할 확률은 그날 비가 오는 경우 $0.9$, 비가 오지 않는 경우 $0.2$이라고 한다. 오늘 비가 올 확률이 $0.7$일 때, 이 음식점에서 오늘 하루의 매출 목표액을 달성할 확률을 구하시오. (3.5점)",
    "choices": [
      "0.67",
      "0.68",
      "0.69",
      "0.7",
      "0.71"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_PS_04_TOTAL_BAYES",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e082cdd48a68394d3b0505c8d3fb4dfab5242a11eb95f95671dbf61116da9c0f"
  },
  {
    "id": 5,
    "level": "중",
    "category": "확률분포",
    "originalCategory": "확률분포",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-05",
    "standardUnit": "확률분포",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-PS-05-BINOMIAL_NORMAL",
    "subUnit": "이항분포와 정규분포",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "순천금당고등학교 학생들을 대상으로 학교생활에 대한 만족도를 조사하였더니 전체 학생 중에서 $80\\%$가 만족한다고 응답하였다. 이 학교 학생 $100$명을 임의로 택하였을 때, 학교생활에 만족한다고 응답한 학생이 $76$명 이상 $80$명 이하일 확률을 구하시오. (단, $P(0\\le Z\\le 1)=0.34$로 계산한다.) (3.6점)",
    "choices": [
      "0.34",
      "0.38",
      "0.66",
      "0.68",
      "0.7"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|5",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-05-BINOMIAL_NORMAL",
    "problemTypeKey": "PT_NORMAL_DISTRIBUTION",
    "templateKey": "TPL_BINOMIAL_NORMAL_RELATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a26037a4c648c84de1019c65ac360e2a43d097ec07198f639af9843a317be038"
  },
  {
    "id": 6,
    "level": "중",
    "category": "조건부확률",
    "originalCategory": "조건부확률",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-04",
    "standardUnit": "조건부확률",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-PS-04-INDEPENDENCE",
    "subUnit": "독립사건과 곱셈정리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "승부차기 성공률이 각각 $80\\%,70\\%$인 현수와 정윤이가 차례로 승부차기를 한 번씩만 할 때, 두 명 모두 승부차기에 성공할 확률을 구하시오. (단, 현수와 정윤이가 각각 승부차기에서 성공하는 사건은 서로 독립이다.) (3.6점)",
    "choices": [
      "0.06",
      "0.08",
      "0.1",
      "0.54",
      "0.56"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|6",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_PS_04_INDEPENDENCE",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:52f78ff2d6cbeb7f17a689231a568c017fbadbb3c6057868e8eb54552fdfa664"
  },
  {
    "id": 7,
    "level": "중",
    "category": "확률분포",
    "originalCategory": "확률분포",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-05",
    "standardUnit": "확률분포",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-PS-05-BINOMIAL_NORMAL",
    "subUnit": "이항분포와 정규분포",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "발아율이 $80\\%$인 어떤 씨앗을 $100$개 심었을 때, $k$개 이상이 발아할 확률은 $95\\%$ 이상이라고 한다. $k$의 최댓값을 구하여라. (단, $P(0\\le Z\\le 1.65)=0.45$) (3.6점)",
    "choices": [
      "72",
      "73",
      "74",
      "75",
      "76"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|7",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-05-BINOMIAL_NORMAL",
    "problemTypeKey": "PT_NORMAL_DISTRIBUTION",
    "templateKey": "TPL_BINOMIAL_NORMAL_RELATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:51b2606d3fc88c81c80ff089d20c67e758d8fba076514722f1d1012d2690f48a"
  },
  {
    "id": 8,
    "level": "중",
    "category": "확률분포",
    "originalCategory": "확률분포",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-05",
    "standardUnit": "확률분포",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-PS-05-BINOMIAL_NORMAL",
    "subUnit": "이항분포와 정규분포",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "다음 그림은 표준정규분포 $N(0,1)$을 따르는 확률변수 $Z$의 확률밀도함수의 그래프이다. 정규분포 $N(40,9)$를 따르는 확률변수 $X$에 대하여 $P(a\\le X\\le 43)$이 색칠한 부분의 넓이와 같을 때, 상수 $a$의 값을 구하여라. (3.7점)",
    "choices": [
      "30",
      "31",
      "32",
      "33",
      "34"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q008_visual.png",
    "visualAsset": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q008_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 350,
      "y1": 3200,
      "x2": 2450,
      "y2": 4300
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|8",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q008_visual.png",
      "assetSha256": "sha256:8377b7588dbe5d117ee9f1a1a634a7a0b0f2108e1769212f4539255c684abdea",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
      "sourceQuestionNo": "8",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 350,
        "y1": 3200,
        "x2": 2450,
        "y2": 4300
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 2100,
      "naturalHeight": 1100,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-05-BINOMIAL_NORMAL",
    "problemTypeKey": "PT_NORMAL_DISTRIBUTION",
    "templateKey": "TPL_NORMAL_STANDARDIZATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:86368e908df27d1489e924331125cfea3f5f662943324da687ffa084a6b48c38"
  },
  {
    "id": 9,
    "level": "중",
    "category": "조건부확률",
    "originalCategory": "조건부확률",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-04",
    "standardUnit": "조건부확률",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-PS-04-INDEPENDENCE",
    "subUnit": "독립사건과 곱셈정리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "두 사건 $A,B$에 대하여 $P(A)>0$, $P(B)>0$을 만족할 때, <보기>에서 옳은 것만을 있는 대로 고른 것은? (3.7점)\r\n<보기>\r\nㄱ. 두 사건 $A,B$가 독립이라면 $P(B|A)=P(B)$, $P(A|B)=P(A)$를 항상 만족한다.\r\nㄴ. 두 사건 $A,B$가 독립이라면 $A,B$는 서로 배반사건이다.\r\nㄷ. 두 사건 $A,B$가 서로 배반사건이면 $A,B$는 서로 종속이다.",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄷ",
      "ㄱ, ㄴ",
      "ㄱ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|9",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_PS_04_INDEPENDENCE",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:0d65fcf3bedf39195cbcb43aaaa00029dd56b1e7538bb79f28bbbadb03f6f9bb"
  },
  {
    "id": 10,
    "level": "중",
    "category": "확률분포",
    "originalCategory": "확률분포",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-05",
    "standardUnit": "확률분포",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-PS-05-RANDOM_VARIABLE",
    "subUnit": "확률변수와 기댓값",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "다음은 확률변수 $X$의 확률분포를 표로 나타낸 것이다. $X$의 분산이 최대가 되도록 하는 상수 $a,b$의 값은? (3.9점)",
    "choices": [
      "$\\frac{1}{2},\\frac{1}{2}$",
      "$\\frac{1}{3},\\frac{1}{3}$",
      "$\\frac{1}{4},\\frac{1}{4}$",
      "$\\frac{3}{4},\\frac{3}{4}$",
      "$\\frac{2}{3},\\frac{4}{5}$"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q010_visual.png",
    "visualAsset": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q010_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "table",
    "visualAssetBBoxOnPage": {
      "x1": 2910,
      "y1": 1320,
      "x2": 5200,
      "y2": 1850
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|10",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q010_visual.png",
      "assetSha256": "sha256:ad6022ecff4cafea4a9133e2c57e3bac6e7739170437ed360f6f0a659757c653",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
      "sourceQuestionNo": "10",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 2910,
        "y1": 1320,
        "x2": 5200,
        "y2": 1850
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 2290,
      "naturalHeight": 530,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-05-RANDOM_VARIABLE",
    "problemTypeKey": "PT_EXPECTATION_VARIANCE",
    "templateKey": "TPL_VARIANCE_STANDARD_DEVIATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:877e4662d15ee9efa1f09a87c65e94e47432af636931450889f8631f3a02c5ad"
  },
  {
    "id": 11,
    "level": "중",
    "category": "통계적 추정",
    "originalCategory": "통계적 추정",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-06",
    "standardUnit": "통계적 추정",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-PS-06-CONFIDENCE_INTERVAL",
    "subUnit": "신뢰구간",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "어느 고등학교에서 $100$명의 학생을 임의추출하여 수학 점수를 조사하였더니 표준편차가 $15$점이었다. 전체 학생들의 평균 수학 점수 $m$을 신뢰도 $99\\%$, $95\\%$로 각각 추정할 때, 두 신뢰구간의 길이의 차는? (단, $P(|Z|\\le 2)=0.95$, $P(|Z|\\le 3)=0.99$) (4.0점)",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|11",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_PS_06_CONFIDENCE_INTERVAL",
    "problemTypeKey": "PT_STATISTICAL_ESTIMATION",
    "templateKey": "TPL_CONFIDENCE_INTERVAL_SAMPLE_SIZE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5275419375fa52f232b543de2222536968d6695aba4d1f4a058df4a5869f20c8"
  },
  {
    "id": 12,
    "level": "상",
    "category": "통계적 추정",
    "originalCategory": "통계적 추정",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-06",
    "standardUnit": "통계적 추정",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-PS-06-CONFIDENCE_INTERVAL",
    "subUnit": "신뢰구간",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "정규분포 $N(m,\\sigma^2)$을 따르는 모집단에서 크기가 $n_1,n_2$인 표본을 임의추출하여 신뢰도 $95\\%$로 추정한 모평균 $m$의 신뢰구간의 길이가 각각 $l,4l$이라고 한다. $\\frac{n_1}{n_2}$의 값은? (단, $P(|Z|\\le 1.96)=0.95$로 계산한다.) [4점]",
    "choices": [
      "1",
      "4",
      "8",
      "12",
      "16"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|12",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_PS_06_CONFIDENCE_INTERVAL",
    "problemTypeKey": "PT_STATISTICAL_ESTIMATION",
    "templateKey": "TPL_CONFIDENCE_INTERVAL_SAMPLE_SIZE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:af8b04900e4f8497dce064b8351a6e4045b538d695afb770ab1d24dd03a279b2"
  },
  {
    "id": 13,
    "level": "상",
    "category": "통계적 추정",
    "originalCategory": "통계적 추정",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-06",
    "standardUnit": "통계적 추정",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-PS-06-ESTIMATION_BASIC",
    "subUnit": "통계적 추정",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "정규분포 $N(m,\\sigma^2)$을 따르는 모집단에서 크기가 $25,400$인 표본을 임의추출하여 그 표본평균을 각각 $\\bar{X},\\bar{Y}$라 할 때,\r\n$P(m-\\frac{\\sigma}{5}\\le\\bar{X}\\le m+\\frac{\\sigma}{5})=P(m-\\frac{k\\sigma}{5}\\le\\bar{Y}\\le m+\\frac{k\\sigma}{5})$\r\n를 만족시키는 상수 $k$의 값은? (4.3점)",
    "choices": [
      "$\\frac{1}{6}$",
      "$\\frac{1}{4}$",
      "$\\frac{1}{2}$",
      "2",
      "3"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|13",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_PS_06_ESTIMATION_BASIC",
    "problemTypeKey": "PT_SAMPLE_MEAN_DISTRIBUTION",
    "templateKey": "TPL_SAMPLE_MEAN_DISTRIBUTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4de6dfda69cb0a1aa5e49901d2f57895c5ff843eeeb46b6c65c07c9e1f2ed490"
  },
  {
    "id": 14,
    "level": "중",
    "category": "확률의 뜻과 활용",
    "originalCategory": "확률의 뜻과 활용",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-03",
    "standardUnit": "확률의 뜻과 활용",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-PS-03-PROBABILITY_APPLICATION",
    "subUnit": "확률의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "한 개의 주사위를 계속 던져서 처음으로 $3$ 또는 $6$의 눈이 나오면 던지기를 중단하기로 할 때, 던지는 횟수가 $10$ 이하일 확률은? (4.3점)",
    "choices": [
      "$1-(\\frac{1}{3})^9$",
      "$1-(\\frac{1}{3})^{10}$",
      "$1-(\\frac{2}{3})^9$",
      "$1-(\\frac{2}{3})^{10}$",
      "$1-(\\frac{2}{3})^{11}$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|14",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-03-PROBABILITY_APPLICATION",
    "problemTypeKey": "PT_PROBABILITY_REPEATED_TRIALS",
    "templateKey": "TPL_INDEPENDENT_TRIAL_PROBABILITY",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:850b3ae204d8623d0d51eca780db6e0df314621eb197f0f63e0f7f1845c84fc0"
  },
  {
    "id": 15,
    "level": "상",
    "category": "통계적 추정",
    "originalCategory": "통계적 추정",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-06",
    "standardUnit": "통계적 추정",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-PS-06-ESTIMATION_BASIC",
    "subUnit": "통계적 추정",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "어느 공장에서 생산하는 휴대폰 부품 $A$의 무게는 평균이 $20$, 표준편차가 $1.2$인 정규분포를 따른다고 한다. 이 공장에서 생산한 휴대폰 부품 $A$ 중에서 임의추출한 $n$개의 무게의 평균을 $\\bar{X}$라 할 때, $|\\bar{X}-20|\\ge 1$이면 생산 과정에 이상이 있는 것으로 판단하고 공장을 중지한다. 이 공장이 생산 과정의 이상으로 공장을 중지할 확률이 $1.24\\%$일 때, $n$의 값을 오른쪽 표준정규분포표를 이용하여 구하시오. (단, 무게의 단위는 $\\mathrm{g}$이다.) (4.3점)",
    "choices": [
      "1",
      "4",
      "9",
      "16",
      "25"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q015_visual.png",
    "visualAsset": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q015_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "table",
    "visualAssetBBoxOnPage": {
      "x1": 3530,
      "y1": 1900,
      "x2": 4600,
      "y2": 3050
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|15",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q015_visual.png",
      "assetSha256": "sha256:4cdc7e8093e06fcf92b7cb238ade927395b62d41b4c8fba023f55eb22608d4c6",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
      "sourceQuestionNo": "15",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 3530,
        "y1": 1900,
        "x2": 4600,
        "y2": 3050
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 1070,
      "naturalHeight": 1150,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15_PS_06_ESTIMATION_BASIC",
    "problemTypeKey": "PT_SAMPLE_MEAN_DISTRIBUTION",
    "templateKey": "TPL_SAMPLE_MEAN_DISTRIBUTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a89b79a00355e150cede86be5bc48d0ac747871dfc5fce570d40eae77acc0039"
  },
  {
    "id": 16,
    "level": "중",
    "category": "조건부확률",
    "originalCategory": "조건부확률",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-04",
    "standardUnit": "조건부확률",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-PS-04-CONDITIONAL_PROBABILITY",
    "subUnit": "조건부확률",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "성빈이를 포함한 $5$명이 다음 그림과 같은 대진표에 따라 테니스 경기를 한다. 성빈이가 우승했을 때, 두 번 시합했을 확률은? (단, 비기는 경우는 없고, 모든 시합에 이길 확률과 질 확률은 같다.) (4.3점)",
    "choices": [
      "$\\frac{3}{5}$",
      "$\\frac{2}{5}$",
      "$\\frac{1}{5}$",
      "$\\frac{3}{4}$",
      "$\\frac{1}{4}$"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q016_visual.png",
    "visualAsset": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q016_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 3150,
      "y1": 5240,
      "x2": 4700,
      "y2": 6110
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|16",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q016_visual.png",
      "assetSha256": "sha256:ea61a7e048fe13193a24eab0e869b6eecc8b1b8980c9020d5771baf1fe366ab0",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
      "sourceQuestionNo": "16",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 3150,
        "y1": 5240,
        "x2": 4700,
        "y2": 6110
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 1550,
      "naturalHeight": 870,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-04-CONDITIONAL_PROBABILITY",
    "problemTypeKey": "PT_CONDITIONAL_PROBABILITY",
    "templateKey": "TPL_CONDITIONAL_PROBABILITY_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:69683f96ac568bd09f839fb462c4096421d762746016d9fd06cfa545cb33c583"
  },
  {
    "id": 17,
    "level": "상",
    "category": "확률분포",
    "originalCategory": "확률분포",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-05",
    "standardUnit": "확률분포",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-PS-05-RANDOM_VARIABLE",
    "subUnit": "확률변수와 기댓값",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "한 변의 길이가 $2$인 정육각형 $A_1A_2A_3A_4A_5A_6$이 있다. 한 개의 주사위를 $3$번 던져 나오는 눈의 수를 순서대로 $i,j,k$라 할 때, 확률변수 $X$가 다음과 같다.\r\n$X=\\begin{cases}0&((i-j)(j-k)(k-i)=0)\\\\(\\triangle A_iA_jA_k\\text{의 넓이의 제곱})&((i-j)(j-k)(k-i)\\ne0)\\end{cases}$\r\n$E(3X+2)$의 값을 구하시오. (4.8점)",
    "choices": [
      "17",
      "19",
      "20",
      "23",
      "26"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q017_visual.png",
    "visualAsset": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q017_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "figure",
    "visualAssetBBoxOnPage": {
      "x1": 900,
      "y1": 2150,
      "x2": 2100,
      "y2": 3300
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|17",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q017_visual.png",
      "assetSha256": "sha256:63b24e0e24c9fe1cf4e17c0d79a19330d983a072b1c5e66c2c05e428344adf38",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
      "sourceQuestionNo": "17",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 900,
        "y1": 2150,
        "x2": 2100,
        "y2": 3300
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 1200,
      "naturalHeight": 1150,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-05-RANDOM_VARIABLE",
    "problemTypeKey": "PT_EXPECTATION_VARIANCE",
    "templateKey": "TPL_EXPECTATION_TRANSFORM",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b2f24c7a3b2fadea3c11c2a18b7638888113590def1530798fdc76d62b8f778c"
  },
  {
    "id": 18,
    "level": "상",
    "category": "확률분포",
    "originalCategory": "확률분포",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-05",
    "standardUnit": "확률분포",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-PS-05-BINOMIAL_NORMAL",
    "subUnit": "이항분포와 정규분포",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "그림과 같이 정사각형 모양의 도로망이 있는 지역에서 택시운행을 하는 두 택시기사 갑, 을이 있다. 갑은 $P$지점에서 $Q$지점까지 최단거리로 주행하고, 을은 $Q$지점에서 $P$지점까지 최단거리로 주행한 $3520$번 중에 두 택시가 $1045$번 이상 만날 확률을 오른쪽 표준정규분포표를 이용하여 구한 것은? (단, 두 택시가 이동하는 속력은 같고, 갈림길에서 방향을 선택할 확률은 모두 $\\frac{1}{2}$이다.) (4.8점)\r\n| $z$ | $P(0\\le Z\\le z)$ |\r\n|:--:|:--:|\r\n| 0.5 | 0.1915 |\r\n| 1.0 | 0.3413 |\r\n| 1.5 | 0.4332 |\r\n| 2.0 | 0.4772 |",
    "choices": [
      "0.0228",
      "0.0668",
      "0.8413",
      "0.9332",
      "0.9772"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q018_visual.png",
    "visualAsset": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q018_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 3500,
      "y1": 1250,
      "x2": 4750,
      "y2": 2240
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|18",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_금당고_2학기_기말_고2_확률과통계/q018_visual.png",
      "assetSha256": "sha256:539590ac94461331bb607d2686d7b6ab718b8c5b76d5eaa84d03c6c5a2f6341c",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
      "sourceQuestionNo": "18",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 3500,
        "y1": 1250,
        "x2": 4750,
        "y2": 2240
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 1250,
      "naturalHeight": 990,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-05-BINOMIAL_NORMAL",
    "problemTypeKey": "PT_NORMAL_DISTRIBUTION",
    "templateKey": "TPL_BINOMIAL_NORMAL_RELATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:234248d508ffa3177eb847d816fe9558062f28ee19fb4b6e495e56c8fcd6fa25"
  },
  {
    "id": 19,
    "level": "상",
    "category": "확률의 뜻과 활용",
    "originalCategory": "확률의 뜻과 활용",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-03",
    "standardUnit": "확률의 뜻과 활용",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-PS-03-PROBABILITY_APPLICATION",
    "subUnit": "확률의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "주머니 속에 흰 공 $3$개, 검은 공 $7$개가 들어 있다. 이 중에서 갑이 $2$개 꺼내고 나머지 $8$개 중에서 을이 $3$개 꺼낼 때, 흰 공을 많이 꺼낸 쪽이 이기는 것으로 하자. 갑이 이길 확률, 을이 이길 확률을 차례로 구한 것은? (단, 꺼낸 흰 공의 개수가 같으면 비긴 것으로 한다.) (10점)",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "단답형 1",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 19,
    "displayNo": "단답형 1",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|단답형 1",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-03-PROBABILITY_APPLICATION",
    "problemTypeKey": "PT_PROBABILITY_PROPERTIES_APPLICATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:214e952802e147a19405eb21ecf20652fc51856c487d889cf8ad2c1794165755"
  },
  {
    "id": 20,
    "level": "상",
    "category": "조건부확률",
    "originalCategory": "조건부확률",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-04",
    "standardUnit": "조건부확률",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-PS-04-CONDITIONAL_PROBABILITY",
    "subUnit": "조건부확률",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "하나의 주머니와 두 상자 $A,B$가 있다. 주머니에는 숫자 $1,2,3,4$가 하나씩 적힌 $4$장의 카드가 들어 있고, 상자 $A$에는 흰 공과 검은 공이 각각 $8$개 이상 들어 있고, 상자 $B$는 비어 있다. 이 주머니와 두 상자 $A,B$를 사용하여 다음 시행을 한다.\r\n주머니에서 임의로 한 장의 카드를 꺼내어 카드에 적힌 수를 확인한 후 다시 주머니에 넣는다.\r\n확인한 수가 $1$이면 상자 $A$에 있는 흰 공 $1$개를 상자 $B$에 넣고,\r\n확인한 수가 $2$ 또는 $3$이면 상자 $A$에 있는 흰 공 $1$개와 검은 공 $1$개를 상자 $B$에 넣고,\r\n확인한 수가 $4$이면 상자 $A$에 있는 흰 공 $2$개와 검은 공 $1$개를 상자 $B$에 넣는다.\r\n이 시행을 $5$번 반복한 후 상자 $B$에 들어 있는 공의 개수가 $11$일 때, 상자 $B$에 들어 있는 검은 공의 개수가 $4$일 확률은? (5점)",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "단답형 2",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 20,
    "displayNo": "단답형 2",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|단답형 2",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-04-CONDITIONAL_PROBABILITY",
    "problemTypeKey": "PT_CONDITIONAL_PROBABILITY",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:84365301db78d278e4d6e80942bf28ecc47cf46ca44283b1a52f3e134ca947d9"
  },
  {
    "id": 21,
    "level": "상",
    "category": "확률의 뜻과 활용",
    "originalCategory": "확률의 뜻과 활용",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-03",
    "standardUnit": "확률의 뜻과 활용",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-PS-03-PROBABILITY_APPLICATION",
    "subUnit": "확률의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "주머니 속에 흰 공 $3$개, 검은 공 $7$개가 들어 있다. 이 중에서 갑이 $2$개 꺼내고 나머지 $8$개 중에서 을이 $3$개 꺼낼 때, 흰 공을 많이 꺼낸 쪽이 이기는 것으로 하자. 갑이 이길 확률, 을이 이길 확률을 차례로 구하시오. (단, 꺼낸 흰 공의 개수가 같으면 비긴 것으로 한다.) (10점)",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "서술형 1",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 21,
    "displayNo": "서술형 1",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|서술형 1",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-03-PROBABILITY_APPLICATION",
    "problemTypeKey": "PT_PROBABILITY_PROPERTIES_APPLICATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c5fb7439fb79c30599534342ac55674f2383222088eca9ab6cc18b4130853fc4"
  },
  {
    "id": 22,
    "level": "상",
    "category": "확률의 뜻과 활용",
    "originalCategory": "확률의 뜻과 활용",
    "standardCourse": "확률과 통계",
    "standardUnitKey": "H15-PS-03",
    "standardUnit": "확률의 뜻과 활용",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-PS-03-PROBABILITY_APPLICATION",
    "subUnit": "확률의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "좌표평면 위의 점 $P$는 한 번 이동할 때마다 다음 네 가지 방법 중 한 가지를 임의로 선택하여 이동한다.\r\n(방법 A) $x$축의 방향으로 $1$만큼 평행이동한다.\r\n(방법 B) $x$축의 방향으로 $-1$만큼 평행이동한다.\r\n(방법 C) $y$축의 방향으로 $1$만큼 평행이동한다.\r\n(방법 D) $y$축의 방향으로 $-1$만큼 평행이동한다.\r\n원점 $O$에서 출발한 점 $P$가 $7$번 이동하여 점 $(3,2)$에 도착하였을 때, 이 점에 처음으로 도착하지 않았을 확률은? (10점)",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_금당고_2학기_기말_고2_확률과통계",
    "sourceFile": "D:\\기출\\(4)2기말\\확률과 통계\\2023_금당고2_확통_2기말.pdf",
    "sourceQuestionNo": "서술형 2",
    "sourceArchiveFile": "original/high/h2/2final/23_금당고_2학기_기말_고2_확률과통계.js",
    "sourceOrdinal": 22,
    "displayNo": "서술형 2",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5",
    "sourceIdentityKey": "sha256:a53831a367177568b570dca99b14ee33754fdd77d8f1307ed8aa4f0cef0d93b5|서술형 2",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\23_금당고_2학기_기말_고2_확률과통계\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.99,
    "choicesConfidence": 0.99,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-PS-03-PROBABILITY_APPLICATION",
    "problemTypeKey": "PT_PROBABILITY_PROPERTIES_APPLICATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:22f681c95fe876e297e3be17da4cbad8c39fe641b3a9f73283c48766f9c444d7"
  }
];
