window.examTitle = "23_매산고_2학기_기말_고2_기하";
window.questionBank = [
  {
    "id": 1,
    "level": "",
    "category": "벡터의 연산",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-05",
    "standardUnit": "벡터의 연산",
    "standardUnitOrder": 5,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "두 점 $A$, $B$, $C$의 위치벡터를 각각 $\\vec{a}$, $\\vec{b}$, $2\\vec{a}+\\vec{b}$라고 할 때, 벡터 $\\overrightarrow{AC}-\\overrightarrow{CB}$를 $\\vec{a}$, $\\vec{b}$로 나타낸 것은? [3.7점]",
    "choices": [
      "$2\\vec{a}+\\vec{b}$",
      "$3\\vec{a}+\\vec{b}$",
      "$3\\vec{a}+2\\vec{b}$",
      "$4\\vec{a}+\\vec{b}$",
      "$4\\vec{a}+2\\vec{b}$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7526e6a9913a52368fdf9de551fb834b9b693c1a7b18ad86525b5b4ddcc63423"
  },
  {
    "id": 2,
    "level": "",
    "category": "평면벡터의 성분과 내적",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-06",
    "standardUnit": "평면벡터의 성분과 내적",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "세 벡터 $\\vec{a}=(1,4)$, $\\vec{b}=(3,-1)$, $\\vec{c}=(x,y)$에 대하여 벡터 $\\vec{c}$와 $3\\vec{a}+2\\vec{b}$가 평행할 때, $\\frac{x}{y}$의 값은? (단, $x$, $y$는 0이 아닌 실수) [3.8점]",
    "choices": [
      "$\\frac{4}{5}$",
      "$\\frac{9}{10}$",
      "$1$",
      "$\\frac{11}{10}$",
      "$\\frac{6}{5}$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:249aeb6267395ad43bbc991405e06308e02eb164527f649276a8575c4d43a929"
  },
  {
    "id": 3,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "두 평면 $\\alpha$, $\\beta$가 이루는 각의 크기가 $30^\\circ$이고 평면 $\\alpha$ 위에 반지름이 5인 원이 있다. 이 원의 평면 $\\beta$ 위로의 정사영의 넓이는? [3.9점]",
    "choices": [
      "$25\\pi$",
      "$\\frac{25}{2}\\pi$",
      "$\\frac{25\\sqrt{2}}{2}\\pi$",
      "$\\frac{25\\sqrt{3}}{2}\\pi$",
      "$50\\pi$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:bbb6935c1206db6b1bd0304f1f7e8dc5f2a7cb21581dbfdc95e3016120b120c3"
  },
  {
    "id": 4,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "다음 그림과 같은 정육면체에서 $\\overline{AG}$와 꼬인위치에 있는 모서리의 개수를 $a$, 평면 $AEHD$와 평행한 모서리의 개수를 $b$라고 할 때, $ab$의 값은? [4.0점]",
    "choices": [
      "$12$",
      "$16$",
      "$20$",
      "$24$",
      "$28$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "assets/images/23_매산고_2학기_기말_고2_기하/q004_visual.png",
    "visualAsset": "assets/images/23_매산고_2학기_기말_고2_기하/q004_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1280,
      "y1": 1770,
      "x2": 1960,
      "y2": 2300
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.82,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_매산고_2학기_기말_고2_기하/q004_visual.png",
      "assetSha256": "sha256:43c5437cd61639a7c4de93c17dc60aff9fc60cda9c743cf61fd27d44af65ae0e",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
      "sourceQuestionNo": "4",
      "sourcePageNo": 1,
      "sourcePageEvidence": "pages/page_p001.png",
      "sourcePageEvidencePaths": [
        "pages/page_p001.png"
      ],
      "sourceBBox": {
        "x1": 1280,
        "y1": 1770,
        "x2": 1960,
        "y2": 2300
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 680,
      "naturalHeight": 530,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c90856a49a6d9df522d6a152d1593ad475cceb55c4969873cd600283c8ba9e35"
  },
  {
    "id": 5,
    "level": "",
    "category": "공간좌표",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-09",
    "standardUnit": "공간좌표",
    "standardUnitOrder": 9,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "좌표공간의 점 $P(2,10,-5)$를 $x$축에 대하여 대칭이동시킨 점을 $Q$라 하자. 선분 $\\overline{PQ}$를 $3:2$로 내분하는 점을 $R$라 할 때, 선분 $\\overline{OR}$의 길이는? (단, $O$는 원점이다.) [4.1점]",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|5",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:0e6c328fbf81218eb4c21c5f08cd14c6b9c0180ffbe3026c83aef9b6c3fc32d6"
  },
  {
    "id": 6,
    "level": "",
    "category": "평면벡터의 성분과 내적",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-06",
    "standardUnit": "평면벡터의 성분과 내적",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "좌표평면 위의 두 점 $A(4,-2)$, $B(-2,6)$에 대하여 $\\overrightarrow{AP}\\cdot\\overrightarrow{BP}=0$을 만족시키는 점 $P$가 그리는 도형의 넓이는? [4.2점]",
    "choices": [
      "$5\\pi$",
      "$10\\pi$",
      "$15\\pi$",
      "$20\\pi$",
      "$25\\pi$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|6",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:bc76310edb3b934f35931265bf31d83388d775b900574bcb36a52456a935c3fc"
  },
  {
    "id": 7,
    "level": "",
    "category": "직선과 원의 방정식",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-07",
    "standardUnit": "직선과 원의 방정식",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "좌표평면 위 두 직선 $l$, $m$이 다음의 조건을 만족시킨다.\n(가) 직선 $l$은 $(0,2)$를 지나고 법선벡터가 $\\vec{n}=(1,1)$이다.\n(나) 직선 $m$의 방정식은 $2x-y+3=0$이다.\n두 직선 $l$, $m$이 이루는 각 $\\theta$에 대하여 $\\sin^2\\theta$의 값은? [4.3점]",
    "choices": [
      "$\\frac{3}{5}$",
      "$\\frac{7}{10}$",
      "$\\frac{4}{5}$",
      "$\\frac{9}{10}$",
      "$1$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|7",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:37feafffc747d718564a3f719d2741538ed63175c43f2d678e61578eb2c9f0d8"
  },
  {
    "id": 8,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "아래 그림과 같이 세 모서리 $\\overline{OA}$, $\\overline{OB}$, $\\overline{OC}$가 서로 수직이고 $\\overline{OA}=1$, $\\overline{OB}=2$, $\\overline{OC}=3$인 사면체가 있다. 꼭짓점 $C$에서 선분 $AB$에 내린 수선의 발을 $H$라고 할 때, 선분 $CH$의 길이를 $p$라고 하자. $p^2$의 값은? [4.3점]",
    "choices": [
      "$\\frac{47}{5}$",
      "$\\frac{48}{5}$",
      "$\\frac{49}{5}$",
      "$10$",
      "$\\frac{51}{5}$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "assets/images/23_매산고_2학기_기말_고2_기하/q008_visual.png",
    "visualAsset": "assets/images/23_매산고_2학기_기말_고2_기하/q008_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1350,
      "y1": 1640,
      "x2": 1910,
      "y2": 2180
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|8",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.8,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_매산고_2학기_기말_고2_기하/q008_visual.png",
      "assetSha256": "sha256:0fc4882c6400cd39e619076b8d526b1cab6cf9143214f2a8e50e50d3bf6d3d4f",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
      "sourceQuestionNo": "8",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 1350,
        "y1": 1640,
        "x2": 1910,
        "y2": 2180
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 560,
      "naturalHeight": 540,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:783067588468dd5890d65ecf6292f990e06414539ec4515d5702eec55bf2a0af"
  },
  {
    "id": 9,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "서로 다른 세 직선 $l$, $m$, $n$과 서로 다른 세 평면 $\\alpha$, $\\beta$, $\\gamma$에 대하여 <보기>에서 옳은 것만의 개수를 구하면? [4.4점]\n<보기>\nㄱ. $l\\parallel\\alpha$이고 $m\\parallel\\alpha$이면 $l\\parallel m$이다.\nㄴ. $l\\parallel\\alpha$이고 $m\\perp\\alpha$이면 $l\\perp m$이다.\nㄷ. $\\alpha\\parallel\\beta$이고 $\\beta\\parallel\\gamma$이면 $\\alpha\\parallel\\gamma$이다.\nㄹ. $l\\perp m$이고 $l\\perp n$이면 $m\\perp n$이다.\nㅁ. $l\\perp\\alpha$이고 $l\\parallel\\beta$이면 $\\alpha\\perp\\beta$이다.",
    "choices": [
      "$1$",
      "$2$",
      "$3$",
      "$4$",
      "$5$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|9",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:45ff266833d6a333b1c572334f7eb232e03627b070623fbc1193770469861e63"
  },
  {
    "id": 10,
    "level": "",
    "category": "공간좌표",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-09",
    "standardUnit": "공간좌표",
    "standardUnitOrder": 9,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "좌표공간에서 점 $(-3,0,2)$를 중심으로 하고 $yz$평면에 접하는 구의 방정식은 $x^2+y^2+z^2+ax+by+cz+d=0$이다. $a+b+c+d$의 값은? (단, $a$, $b$, $c$, $d$는 상수이다.) [4.5점]",
    "choices": [
      "$6$",
      "$7$",
      "$8$",
      "$9$",
      "$10$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|10",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a2b757fa0eca362049fb9f82a8d1a1a40ab21cb94be8be26eb97f49eeea867fb"
  },
  {
    "id": 11,
    "level": "",
    "category": "공간좌표",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-09",
    "standardUnit": "공간좌표",
    "standardUnitOrder": 9,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "좌표공간에서 구 $(x-a)^2+(y-a+1)^2+(z-a+2)^2=49$와 $zx$평면이 만나서 생기는 원의 넓이가 $24\\pi$일 때, 양수 $a$의 값은? [4.6점]",
    "choices": [
      "$4$",
      "$5$",
      "$6$",
      "$7$",
      "$8$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|11",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5b2a885bbcec453342b633b6ae8f735e6086f28259a1a59b243d15d3b6224601"
  },
  {
    "id": 12,
    "level": "",
    "category": "평면벡터의 성분과 내적",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-06",
    "standardUnit": "평면벡터의 성분과 내적",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "좌표평면 위 세 점 $A(2,1)$, $B$, $P$가 다음 조건을 만족시킨다.\n(가) $|\\overrightarrow{OB}|=1$\n(나) $\\overrightarrow{OA}+\\overrightarrow{OB}\\parallel(1,1)$\n(다) $|\\overrightarrow{AP}-\\overrightarrow{OB}|=k$ ($k$는 상수)\n점 $P$가 그리는 도형이 원점을 지날 때, 이 도형의 둘레의 길이의 최댓값을 $m$, 최솟값을 $n$이라 하자. $m^2+n^2$의 값은? (단, $O$는 원점이다.) [4.7점]",
    "choices": [
      "$20\\pi^2$",
      "$25\\pi^2$",
      "$30\\pi^2$",
      "$35\\pi^2$",
      "$40\\pi^2$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|12",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:815d45896d23bc2f99cfba984c77022ef2a54a9cb8bf55e58e42a4b0e7be7f81"
  },
  {
    "id": 13,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "아래 그림과 같이 밑면이 정사각형이고 옆면이 정삼각형인 사각뿔에서 네 옆면의 내접원의 밑면 $ABCD$로의 정사영을 각각 $S_1$, $S_2$, $S_3$, $S_4$라 하자. $\\overline{AB}=4$일 때, 그림과 같이 네 도형 $S_1$, $S_2$, $S_3$, $S_4$로 둘러싸인 빗금친 부분의 넓이를 $A$, 네 도형 $S_1$, $S_2$, $S_3$, $S_4$의 넓이의 합을 $B$라고 하자. $A+B$의 값은? [4.8점]",
    "choices": [
      "$\\frac{16}{3}+\\frac{32\\sqrt{3}}{27}\\pi$",
      "$\\frac{16}{3}+\\frac{4\\sqrt{3}}{3}\\pi$",
      "$\\frac{16}{3}+\\frac{40\\sqrt{3}}{27}\\pi$",
      "$\\frac{16}{3}+\\frac{44\\sqrt{3}}{27}\\pi$",
      "$\\frac{16}{3}+\\frac{16\\sqrt{3}}{9}\\pi$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "assets/images/23_매산고_2학기_기말_고2_기하/q013_visual.png",
    "visualAsset": "assets/images/23_매산고_2학기_기말_고2_기하/q013_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "figure",
    "visualAssetBBoxOnPage": {
      "x1": 300,
      "y1": 520,
      "x2": 900,
      "y2": 1140
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|13",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 0.76,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_매산고_2학기_기말_고2_기하/q013_visual.png",
      "assetSha256": "sha256:da4585bbcbccdc0fc7c8f6673a25357780201573ace2f69a2d7c97de1cc7f955",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
      "sourceQuestionNo": "13",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 300,
        "y1": 520,
        "x2": 900,
        "y2": 1140
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 600,
      "naturalHeight": 620,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:df8555d75349879c0268ae89ca102d27dc143dfde0f6b3dc56f6725952b75778"
  },
  {
    "id": 14,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "아래 그림과 같이 $\\overline{AB}=4$, $\\angle ABC=\\angle ABD=\\angle DBC=\\frac{\\pi}{3}$, $\\angle BCD=\\frac{\\pi}{2}$인 사면체 $ABCD$의 꼭짓점 $A$에서 평면 $BCD$에 내린 수선의 발을 $H$라 하자. 점 $H$가 선분 $CD$ 위의 점일 때, $\\cos(\\angle ABH)$의 값을 $q$라고 하자. $q^2$의 값은? [4.8점]",
    "choices": [
      "$\\frac{1}{3}$",
      "$\\frac{2}{3}$",
      "$\\frac{4}{3}$",
      "$\\frac{8}{3}$",
      "$\\frac{16}{3}$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "assets/images/23_매산고_2학기_기말_고2_기하/q014_visual.png",
    "visualAsset": "assets/images/23_매산고_2학기_기말_고2_기하/q014_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1370,
      "y1": 610,
      "x2": 1910,
      "y2": 1090
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|14",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.81,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_매산고_2학기_기말_고2_기하/q014_visual.png",
      "assetSha256": "sha256:ff98fc50f116cbb38777d843da21eacb8ccb130b4ce99d723b0ac47a0b1702ac",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
      "sourceQuestionNo": "14",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 1370,
        "y1": 610,
        "x2": 1910,
        "y2": 1090
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 540,
      "naturalHeight": 480,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:1d623b51098021edc9f5ded32ab3fce2c960bafc02d1d0c5f365f23c2d7d97a7"
  },
  {
    "id": 15,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "아래 그림과 같이 한 모서리의 길이가 3인 정육면체의 내부에 밑면이 정육면체의 한 면과 합동이고 옆면의 모양이 정삼각형인 사각뿔이 들어있다. 평면 $OEH$와 평면 $AEHD$가 이루는 각의 크기를 $\\theta$라고 할 때, $\\cos\\theta$의 값은? [4.9점]",
    "choices": [
      "$\\frac{\\sqrt{2}}{3}$",
      "$\\frac{\\sqrt{3}}{3}$",
      "$\\frac{2}{3}$",
      "$\\frac{\\sqrt{5}}{3}$",
      "$\\frac{\\sqrt{6}}{3}$"
    ],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "assets/images/23_매산고_2학기_기말_고2_기하/q015_visual.png",
    "visualAsset": "assets/images/23_매산고_2학기_기말_고2_기하/q015_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 360,
      "y1": 460,
      "x2": 860,
      "y2": 850
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|15",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.78,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_매산고_2학기_기말_고2_기하/q015_visual.png",
      "assetSha256": "sha256:e6ca6a10ec64b99e33ef3986a8f07a7e6dcec5fc1f983d70f62b50ab2e6abbb1",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
      "sourceQuestionNo": "15",
      "sourcePageNo": 5,
      "sourcePageEvidence": "pages/page_p005.png",
      "sourcePageEvidencePaths": [
        "pages/page_p005.png"
      ],
      "sourceBBox": {
        "x1": 360,
        "y1": 460,
        "x2": 860,
        "y2": 850
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 500,
      "naturalHeight": 390,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:6817176f89c6596ee656651ba625d71cf30aed545e09f148945c9c40000b6b2a"
  },
  {
    "id": 16,
    "level": "",
    "category": "공간좌표",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-09",
    "standardUnit": "공간좌표",
    "standardUnitOrder": 9,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "<단답형1> 좌표공간 위의 두 점 $A(1,2,4)$, $B(2,7,3)$와 $yz$평면 위의 점 $P$에 대하여 $\\overline{AP}+\\overline{BP}$의 최솟값을 구하시오. [4점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|16",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5e7deaf7ce0e8b054d15fddc2cd1e1fb613308944f40dc9134ee6d17cd378c22"
  },
  {
    "id": 17,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "<단답형2> 좌표공간에 평면 $\\alpha$가 있다. 평면 $\\alpha$ 위에 있지 않은 서로 다른 두 점 $A$, $B$의 평면 $\\alpha$ 위로의 정사영을 각각 $A'$, $B'$이라 할 때, $\\overline{AB}=\\overline{A'B'}=8$이다. 선분 $\\overline{AB}$의 중점 $M$의 평면 $\\alpha$ 위로의 정사영을 $M'$이라 할 때, $\\overline{PM'}\\perp\\overline{A'B'}$, $\\overline{PM'}=8$이 되도록 $\\alpha$ 위에 점 $P$를 잡는다. 삼각형 $A'B'P$의 평면 $ABP$ 위로의 정사영의 넓이가 $\\frac{16}{3}$일 때, 선분 $PM$의 길이를 구하시오. [5점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|17",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:3acdb0cccdb2c3401f90939deac935c31a9508a3a5b2f7482ebfee8c3073234a"
  },
  {
    "id": 18,
    "level": "",
    "category": "벡터의 연산",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-05",
    "standardUnit": "벡터의 연산",
    "standardUnitOrder": 5,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "<단답형3> 삼각형 $ABC$의 내부의 한 점 $D$에 대하여 $3\\overrightarrow{DA}+3\\overrightarrow{DB}+2\\overrightarrow{DC}=\\vec{0}$이다. 삼각형 $ADB$의 넓이가 15일 때, 삼각형 $DBC$의 넓이를 구하시오. [6점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|18",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e56141ed747d858c56b18672bd37ec37eb93eab945596f893cbb2e4b16e40ad2"
  },
  {
    "id": 19,
    "level": "",
    "category": "평면벡터의 성분과 내적",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-06",
    "standardUnit": "평면벡터의 성분과 내적",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "※ 서술형 문제는 답만 기재할 경우 0점 처리합니다. <서술형1> 아래 그림과 같이 원점을 중심으로 하고 반지름의 길이가 1인 원이 있다. 두 점 $A(-3,0)$, $B(2,0)$와 원 위의 점 $P(a,b)$에 대하여 $b\\ge0$일 때, $\\overrightarrow{AP}\\cdot\\overrightarrow{PB}$의 최댓값을 $m$, 최솟값을 $n$이라 하자. $m+n$의 값을 구하는 과정을 서술하시오. [10점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "assets/images/23_매산고_2학기_기말_고2_기하/q019_visual.png",
    "visualAsset": "assets/images/23_매산고_2학기_기말_고2_기하/q019_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 250,
      "y1": 590,
      "x2": 850,
      "y2": 1040
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "19",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 19,
    "displayNo": "19",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|19",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 1,
    "visualAssetConfidence": 0.82,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_매산고_2학기_기말_고2_기하/q019_visual.png",
      "assetSha256": "sha256:9761a4062c42c4019f10852242a7e5aac8295b3f99bcb8e96aa9756f6c0fdd84",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
      "sourceQuestionNo": "19",
      "sourcePageNo": 6,
      "sourcePageEvidence": "pages/page_p006.png",
      "sourcePageEvidencePaths": [
        "pages/page_p006.png"
      ],
      "sourceBBox": {
        "x1": 250,
        "y1": 590,
        "x2": 850,
        "y2": 1040
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 600,
      "naturalHeight": 450,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:9dc64b0837f7d826e16aba323fa4e847d5b7d87830db5adb41facc5e880d3ee1"
  },
  {
    "id": 20,
    "level": "",
    "category": "공간도형",
    "originalCategory": "",
    "standardCourse": "기하와 벡터",
    "standardUnitKey": "H15-GV-08",
    "standardUnit": "공간도형",
    "standardUnitOrder": 8,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출"
    ],
    "wide": false,
    "content": "※ 서술형 문제는 답만 기재할 경우 0점 처리합니다. <서술형2> 아래 그림과 같이 점 $O$가 중심이고 반지름 $OA$의 길이가 3인 원 $C$를 밑면으로 하고 높이 $AB$의 길이가 12인 원기둥이 있다. $\\angle AOP$가 예각이 되도록 하는 원 $C$ 위의 점 $P$와 세 점 $O$, $A$, $B$의 평면 $\\alpha$ 위로의 정사영을 각각 $P'$, $O'$, $A'$, $B'$이라 하고, 점 $P'$에서 직선 $O'A'$에 내린 수선의 발을 $H$라 할 때, $\\overline{OA}\\parallel\\overline{O'A'}$, $\\overline{P'H}=\\frac{\\sqrt{3}}{2}$, $\\overline{A'B'}=8\\sqrt{2}$이다. 평면 $PAB$와 평면 $\\alpha$가 이루는 예각의 크기를 $\\theta$라 할 때, $\\cos^2\\theta=\\frac{q}{p}$이다. $|p-q|$의 값을 구하시오. (단, $p$와 $q$는 서로소인 자연수이다.) [10점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "solutionImage": "",
    "image": "assets/images/23_매산고_2학기_기말_고2_기하/q020_visual.png",
    "visualAsset": "assets/images/23_매산고_2학기_기말_고2_기하/q020_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1200,
      "y1": 900,
      "x2": 1980,
      "y2": 1980
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "23_매산고_2학기_기말_고2_기하",
    "sourceFile": "D:\\기출\\(4)2기말\\기하\\2023_매산고2_기하_2기말.pdf",
    "sourceQuestionNo": "20",
    "sourceArchiveFile": "original/high/h2/2final/23_매산고_2학기_기말_고2_기하.js",
    "sourceOrdinal": 20,
    "displayNo": "20",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
    "sourceIdentityKey": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de|20",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-02\\AP------\\archive-work\\evidence\\23_매산고_2학기_기말_고2_기하\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.92,
    "choicesConfidence": 1,
    "visualAssetConfidence": 0.72,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/23_매산고_2학기_기말_고2_기하/q020_visual.png",
      "assetSha256": "sha256:6df8ee3e48607860a9b3d3f1ff88d8e58cc96b7f0e95ea625be529bf422b3a42",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:a91ae7d2dbaf4b22d702a036aa4fdc21b73c86199661596d449e71f3a74122de",
      "sourceQuestionNo": "20",
      "sourcePageNo": 6,
      "sourcePageEvidence": "pages/page_p006.png",
      "sourcePageEvidencePaths": [
        "pages/page_p006.png"
      ],
      "sourceBBox": {
        "x1": 1200,
        "y1": 900,
        "x2": 1980,
        "y2": 1980
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 780,
      "naturalHeight": 1080,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:053096fd2c32054d328b2679011dcd2683f2a2b40dd0e887df565de30bba5681"
  }
];
