window.examTitle = "25_금당고_2학기_기말_고2_미적분";
window.questionBank = [
  {
    "id": 1,
    "level": "",
    "category": "여러 가지 미분법",
    "originalCategory": "여러 가지 미분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-05",
    "standardUnit": "여러 가지 미분법",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "subUnit": "여러 가지 미분법",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 미분법"
    ],
    "wide": false,
    "content": "다음은 함수를 미분한 것이다. 옳은 것은? [3.8점]",
    "choices": [
      "$y=\\sin(2-3x)\\Rightarrow y'=3\\cos(2-3x)$",
      "$y=3^{5x-1}\\Rightarrow y'=5\\times3^{5x-1}$",
      "$y=x\\ln|x-1|\\Rightarrow y'=\\ln|x-1|+\\dfrac{1}{x-1}$",
      "$x=e^y+2y\\Rightarrow y'=\\dfrac{1}{e^y+2}$",
      "$y=\\sin(\\cos x)\\Rightarrow y'=-\\sin x\\cos(\\sin x)$"
    ],
    "answer": "④",
    "solution": "각 식을 미분해 확인한다.\n① 연쇄법칙으로 $y'=-3\\cos(2-3x)$이다.\n② $y'=5\\ln3\\cdot3^{5x-1}$이다.\n③ 곱의 미분법으로 $y'=\\ln|x-1|+\\dfrac{x}{x-1}$이다.\n④ $x=e^y+2y$를 미분하면 $1=(e^y+2)y'$이므로 $y'=\\dfrac1{e^y+2}$이다.\n⑤ $y'=-\\sin x\\cos(\\cos x)$이다.\n따라서 옳은 것은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:223971bc24b77ab6a3f5b200555d846562cec7c84b1a9a6af50ed8f8424959e7"
  },
  {
    "id": 2,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "곡선 $y=3+\\ln x$에 접하고 기울기가 1인 접선의 방정식은? [3.8점]",
    "choices": [
      "$y=x+2$",
      "$y=x-2$",
      "$y=x$",
      "$y=x+1$",
      "$y=x-1$"
    ],
    "answer": "①",
    "solution": "곡선의 기울기는 $y'=\\dfrac1x$이다. 기울기가 1이면 $x=1$이고 곡선 위의 점은 $(1,3)$이다. 접선은 $y-3=x-1$, 즉 $y=x+2$이므로 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:9df71faff85166550c2944fedce319569535cecf21882a7e083d6bb68d9e273b"
  },
  {
    "id": 3,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "좌표평면 위를 움직이는 점 $P$의 시각 $t$에서의 위치가 $(x,y)$이고, $x=t^3-2t^2$, $y=t^2+2t$일 때, 다음 중 설명이 틀린 것은? [3.8점]",
    "choices": [
      "$t=1$에서 점 $P$의 속도는 $(-1,4)$이다.",
      "$t=1$에서 점 $P$의 속력은 $\\sqrt{17}$이다.",
      "$t=1$에서 점 $P$의 가속도는 $(-2,2)$이다.",
      "$t=1$에서 점 $P$의 가속도의 크기는 $2\\sqrt{2}$이다.",
      "$t=1$에서 점 $P$의 위치는 $(-1,3)$이다."
    ],
    "answer": "③",
    "solution": "$x'=3t^2-4t$, $y'=2t+2$이므로 $t=1$에서 속도는 $(-1,4)$, 속력은 $\\sqrt{17}$이다. $x''=6t-4$, $y''=2$이므로 가속도는 $(2,2)$, 크기는 $2\\sqrt2$이다. 위치는 $(-1,3)$이다. 가속도를 $(-2,2)$라고 한 ③이 틀리다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4fd29e688324821cdab8aa3672fca7255bc305e50cd01e4e60d5b1b02c4e413f"
  },
  {
    "id": 4,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "닫힌구간 $[-3,1]$에서 함수 $f(x)=e^x-x$의 최댓값과 최솟값이 올바르게 짝지어진 것은? [3.8점]",
    "choices": [
      "최댓값: $1$, 최솟값: $-3$",
      "최댓값: $1$, 최솟값: $\\dfrac{1}{e^3}-3$",
      "최댓값: $1$, 최솟값: $\\dfrac{1}{e^3}-1$",
      "최댓값: $\\dfrac{1}{e^3}$, 최솟값: $1$",
      "최댓값: $\\dfrac{1}{e^3}+3$, 최솟값: $1$"
    ],
    "answer": "⑤",
    "solution": "$f'(x)=e^x-1$이므로 $[-3,0]$에서 감소하고 $[0,1]$에서 증가한다. 따라서 최솟값은 $f(0)=1$이다. 끝점에서 $f(-3)=e^{-3}+3$, $f(1)=e-1$이고 $e<3$이므로 $f(-3)>f(1)$. 최댓값은 $e^{-3}+3$이어서 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:de46c2af61c7e6cca42eb253daece93f80229bd6904fd310bb1124eecd986b76"
  },
  {
    "id": 5,
    "level": "",
    "category": "여러 가지 적분법",
    "originalCategory": "여러 가지 적분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-07",
    "standardUnit": "여러 가지 적분법",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 적분법"
    ],
    "wide": false,
    "content": "다음 부정적분 중 계산이 틀린 것은? (단, $C$는 적분상수이다.) [4.2점]",
    "choices": [
      "$\\int\\dfrac{3x^4-x+1}{x^2}\\,dx=x^3-\\ln|x|-\\dfrac{1}{x}+C$",
      "$\\int\\dfrac{3x^2}{x^3+3}\\,dx=\\ln|x^3+3|+C$",
      "$\\int\\tan^2x\\,dx=\\tan x+x+C$",
      "$\\int\\dfrac{1}{x(x+1)}\\,dx=\\ln\\left|\\dfrac{x}{x+1}\\right|+C$",
      "$\\int\\ln x\\,dx=x\\ln x-x+C$"
    ],
    "answer": "③",
    "solution": "①은 $3x^2-\\dfrac1x+\\dfrac1{x^2}$를 적분한 결과로 맞다. ②는 치환적분, ④는 $\\dfrac1x-\\dfrac1{x+1}$로 나눈 결과, ⑤는 부분적분 결과로 맞다. 그런데 $\\tan^2x=\\sec^2x-1$이므로 $\\int\\tan^2x\\,dx=\\tan x-x+C$이다. 부호가 다른 ③이 틀리다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|5",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:0df3e83fc567f7a3c0b5a6fef04babaf9932974842f24e1764a3396a300b63c9"
  },
  {
    "id": 6,
    "level": "",
    "category": "여러 가지 적분법",
    "originalCategory": "여러 가지 적분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-07",
    "standardUnit": "여러 가지 적분법",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 적분법"
    ],
    "wide": false,
    "content": "다음 정적분 $\\int_0^2 xe^{x^2}\\,dx$의 값은? [4.2점]",
    "choices": [
      "$\\dfrac{3}{2}(e^4-1)$",
      "$\\dfrac{1}{2}(e^4-1)$",
      "$e-1$",
      "$e^4-1$",
      "$\\dfrac{1}{2}e^4$"
    ],
    "answer": "②",
    "solution": "$u=x^2$로 두면 $du=2x\\,dx$이고 적분 구간은 $0$에서 $4$로 바뀐다. 따라서 $\\int_0^2xe^{x^2}dx=\\dfrac12\\int_0^4e^u du=\\dfrac{e^4-1}{2}$이므로 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|6",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:bdf35d4f5b0e6d74ef22f1618fd5b7094df55fa3b61fa877f087586170d8178a"
  },
  {
    "id": 7,
    "level": "",
    "category": "여러 가지 적분법",
    "originalCategory": "여러 가지 적분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-07",
    "standardUnit": "여러 가지 적분법",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 적분법"
    ],
    "wide": false,
    "content": "함수 $f(x)$에 대하여 $f'(x)=(4x+1)\\ln x$이고 $f(1)=2$일 때, $f(e)$의 값은? [4.2점]",
    "choices": [
      "$e^2+1$",
      "$e^2+2$",
      "$e^2+3$",
      "$e^2+4$",
      "$e^2+5$"
    ],
    "answer": "④",
    "solution": "$f(e)-f(1)=\\int_1^e(4x+1)\\ln x\\,dx$이다. 부분적분하면 한 원시함수는 $F(x)=2x^2\\ln x-x^2+x\\ln x-x$이다. $F(e)=e^2$, $F(1)=-2$이므로 $f(e)=2+F(e)-F(1)=e^2+4$이다. 정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|7",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:6f364c4fb5d6a08cbbe5e830592634ef9f60374662392935d614483d98c4857f"
  },
  {
    "id": 8,
    "level": "",
    "category": "정적분",
    "originalCategory": "여러 가지 적분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-07",
    "standardUnit": "여러 가지 적분법",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "정적분의 활용"
    ],
    "wide": false,
    "content": "정적분과 급수의 합 사이의 관계를 이용하여 극한값 $\\lim_{n\\to\\infty}\\dfrac{1}{n}\\left\\{\\left(\\dfrac{1}{n}\\right)^4+\\left(\\dfrac{2}{n}\\right)^4+\\left(\\dfrac{3}{n}\\right)^4+\\cdots+\\left(\\dfrac{n}{n}\\right)^4\\right\\}$의 값은? [4.2점]",
    "choices": [
      "$\\dfrac{1}{5}$",
      "$\\dfrac{2}{5}$",
      "$\\dfrac{3}{5}$",
      "$\\dfrac{4}{5}$",
      "$1$"
    ],
    "answer": "①",
    "solution": "주어진 합은 $[0,1]$에서 $x^4$의 오른쪽 끝점 리만 합이다. 따라서 극한은 $\\int_0^1x^4dx=\\left[\\dfrac{x^5}{5}\\right]_0^1=\\dfrac15$이고 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|8",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c081a10bf08b441224d2c03cfab5ffa446b3d1ff6b3d28e15a3ad46258262c60"
  },
  {
    "id": 9,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "점 $(-2,0)$에서 곡선 $y=\\dfrac{1}{x}$에 그은 접선의 방정식을 구하면? [4.4점]",
    "choices": [
      "$y=-x+2$",
      "$y=-x-2$",
      "$y=x-1$",
      "$y=x+1$",
      "$y=-x+1$"
    ],
    "answer": "②",
    "solution": "접점의 $x$좌표를 $a$라 하면 접점은 $(a,1/a)$, 접선 기울기는 $-1/a^2$이다. $(-2,0)$을 지나므로 $-1/a=(-2-a)(-1/a^2)$, 즉 $-a=2+a$이고 $a=-1$이다. 접선은 $y+1=-(x+1)$이므로 $y=-x-2$, 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|9",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a1cf962710e9938c35f321ab27ed572fbff320ec5d45a3e766894635a121fa86"
  },
  {
    "id": 10,
    "level": "",
    "category": "여러 가지 미분법",
    "originalCategory": "여러 가지 미분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-05",
    "standardUnit": "여러 가지 미분법",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "subUnit": "여러 가지 미분법",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 미분법"
    ],
    "wide": false,
    "content": "함수 $f(x)$가 $f(x)=-\\dfrac{1}{x}-\\dfrac{1}{x^2}-\\dfrac{1}{x^3}-\\cdots-\\dfrac{1}{x^{10}}$일 때, $f'(-1)$의 값을 구하면? [4.5점]",
    "choices": [
      "$-10$",
      "$-5$",
      "$0$",
      "$5$",
      "$10$"
    ],
    "answer": "②",
    "solution": "$f'(x)=\\sum_{k=1}^{10}kx^{-k-1}$이다. $x=-1$을 대입하면 $1-2+3-4+\\cdots+9-10=(1-2)+(3-4)+(5-6)+(7-8)+(9-10)=-5$이다. 따라서 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|10",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e67499c323fff366cb4ccf2cb6ebb89f6275108cede0a2d528c8a4c8637ddb08"
  },
  {
    "id": 11,
    "level": "",
    "category": "여러 가지 미분법",
    "originalCategory": "여러 가지 미분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-05",
    "standardUnit": "여러 가지 미분법",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "subUnit": "여러 가지 미분법",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 미분법"
    ],
    "wide": false,
    "content": "미분 가능한 함수 $f(x)$가 $\\lim_{x\\to6}\\dfrac{f(x)-3}{x-6}=\\dfrac{1}{3}$을 만족시키고, 함수 $f(x)$의 역함수 $g(x)$가 미분가능할 때, $g(3)+g'(3)$의 값을 구하면? [4.7점]",
    "choices": [
      "$7$",
      "$9$",
      "$11$",
      "$13$",
      "$15$"
    ],
    "answer": "②",
    "solution": "극한 조건에서 $f(6)=3$, $f'(6)=\\dfrac13$이다. 역함수에 대해 $g(3)=6$, $g'(3)=\\dfrac1{f'(6)}=3$이므로 $g(3)+g'(3)=9$, 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|11",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:8387a09108b0786bfd4f35b4603542ebeac15ad1b42c27d05fc50948cf6b2f72"
  },
  {
    "id": 12,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "곡선 $y=xe^{-x}$의 변곡점을 $A$라 하고, 점 $A$에서 접하는 접선이 $x$축, $y$축과 만나는 점을 각각 $B$, $C$라고 할 때, 삼각형 $OBC$의 넓이를 구하면? (단, $O$는 원점) [4.7점]",
    "choices": [
      "$\\dfrac{2}{e^2}$",
      "$\\dfrac{4}{e^2}$",
      "$\\dfrac{6}{e^2}$",
      "$\\dfrac{8}{e^2}$",
      "$\\dfrac{10}{e^2}$"
    ],
    "answer": "④",
    "solution": "$y=xe^{-x}$이면 $y'=e^{-x}(1-x)$, $y''=e^{-x}(x-2)$이다. 변곡점은 $A=(2,2/e^2)$이고 접선 기울기는 $-1/e^2$이다. 접선은 $y=(4-x)/e^2$이므로 $B=(4,0)$, $C=(0,4/e^2)$이다. 넓이는 $\\dfrac12\\cdot4\\cdot\\dfrac4{e^2}=\\dfrac8{e^2}$이어서 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|12",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d0fea099281c393abe38c6b81e430d82e9d1334d6f59fea8d1ced46fa50fd1bd"
  },
  {
    "id": 13,
    "level": "",
    "category": "여러 가지 적분법",
    "originalCategory": "여러 가지 적분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-07",
    "standardUnit": "여러 가지 적분법",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 적분법"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 미분가능한 함수 $f(x)$에 대하여 $\\lim_{h\\to0}\\dfrac{f(x+h)-f(x)}{h}=\\cos x$일 때, $f\\left(\\dfrac{\\pi}{3}\\right)-f\\left(\\dfrac{\\pi}{6}\\right)$의 값은? [4.8점]",
    "choices": [
      "$\\dfrac{1-\\sqrt{3}}{2}$",
      "$\\dfrac{\\sqrt{3}}{2}$",
      "$\\dfrac{\\sqrt{3}-1}{2}$",
      "$1$",
      "$\\dfrac{\\sqrt{3}+1}{2}$"
    ],
    "answer": "③",
    "solution": "극한 조건은 $f'(x)=\\cos x$를 뜻한다. 따라서 $f(\\pi/3)-f(\\pi/6)=\\int_{\\pi/6}^{\\pi/3}\\cos x\\,dx=\\sin\\dfrac\\pi3-\\sin\\dfrac\\pi6=\\dfrac{\\sqrt3-1}{2}$이다. 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|13",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b729cf099706cc0e71dcda48a20292fe60b6b42e00f6d1057b874ed1a781e3b8"
  },
  {
    "id": 14,
    "level": "",
    "category": "여러 가지 적분법",
    "originalCategory": "여러 가지 적분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-07",
    "standardUnit": "여러 가지 적분법",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 적분법"
    ],
    "wide": false,
    "content": "함수 $y=f(x)$의 그래프 위의 임의의 점 $(x,f(x))$에서의 접선의 기울기가 $\\dfrac{1}{x\\sqrt{\\ln x+10}}$이다. 함수 $y=f(x)$의 그래프가 점 $\\left(\\dfrac{1}{e},10\\right)$을 지날 때, $f(e^6)$의 값은? [4.9점]",
    "choices": [
      "$10$",
      "$11$",
      "$12$",
      "$13$",
      "$14$"
    ],
    "answer": "③",
    "solution": "$f(e^6)-f(1/e)=\\int_{1/e}^{e^6}\\dfrac{dx}{x\\sqrt{\\ln x+10}}$이다. $u=\\ln x+10$으로 두면 구간은 $9$에서 $16$이므로 차는 $\\int_9^{16}\\dfrac{du}{\\sqrt u}=2\\sqrt u\\big|_9^{16}=2$이다. $f(1/e)=10$이므로 $f(e^6)=12$, 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|14",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5577ddfd319bc436d9b74f57fdaeaa0d23672802098e97881e8bcb339eb11d3c"
  },
  {
    "id": 15,
    "level": "",
    "category": "여러 가지 적분법",
    "originalCategory": "여러 가지 적분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-07",
    "standardUnit": "여러 가지 적분법",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 적분법"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 미분가능한 함수 $f(x)$가 다음 조건을 만족시킨다.\n(가) $f(1)=0$\n(나) $0$이 아닌 모든 실수 $x$에 대하여 $\\dfrac{xf'(x)-f(x)}{x^2}=3xe^{x^2}$이다.\n$f(2)$의 값은? [5점]",
    "choices": [
      "$e^2$",
      "$2e^2$",
      "$4e^2$",
      "$6e^2$",
      "$8e^2$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|15",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ffdf9a16656dee62f60f2d6a27b28302ee858c38747c5bb7b79f375540e82630"
  },
  {
    "id": 16,
    "level": "",
    "category": "도함수의 활용",
    "originalCategory": "도함수의 활용",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-06",
    "standardUnit": "도함수의 활용",
    "standardUnitOrder": 6,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "도함수의 활용"
    ],
    "wide": false,
    "content": "수직선 위를 움직이는 두 점 $P$, $Q$의 시각 $t$에서의 위치가 각각 $f(t)=t^2-at$, $g(t)=\\ln(t^2-2t+2)$이다. 두 점 $P$, $Q$가 서로 반대 방향으로 움직이는 시각 $t$의 값의 범위가 $\\dfrac{1}{4}<t<1$일 때, 상수 $a$의 값을 구하면? (단, $a<2$) [5점]",
    "choices": [
      "$\\dfrac{1}{2}$",
      "$\\dfrac{1}{3}$",
      "$\\dfrac{1}{4}$",
      "$\\dfrac{1}{5}$",
      "$\\dfrac{1}{6}$"
    ],
    "answer": "①",
    "solution": "$P$의 속도는 $f'(t)=2t-a$이다. $Q$의 속도는 $g'(t)=\\dfrac{2(t-1)}{(t-1)^2+1}$이므로 $t<1$에서 음수이다. 반대 방향인 구간이 정확히 $1/4<t<1$이 되려면 $P$의 속도는 $t>1/4$에서 양수이고 경계에서 $2(1/4)-a=0$이다. 따라서 $a=1/2$, 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|16",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e8d660df724cb50977e6f79464a19f027fcd86d57073455bb4f51b38631528e7"
  },
  {
    "id": 17,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "미적분",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분"
    ],
    "wide": false,
    "content": "극한값 $\\lim_{x\\to0}\\dfrac{2}{x}\\ln\\dfrac{e^x+e^{2x}+e^{3x}+\\cdots+e^{10x}}{10}$의 값을 구하여라. [5점]",
    "choices": [],
    "answer": "$11$",
    "solution": "$S(x)=\\dfrac{e^x+e^{2x}+\\cdots+e^{10x}}{10}$이라 두면 $S(0)=1$이다. 극한은 $2\\lim_{x\\to0}\\dfrac{\\ln S(x)-\\ln S(0)}x=2(\\ln S)'(0)$이다. $(\\ln S)'(0)=S'(0)/S(0)=(1+2+\\cdots+10)/10=11/2$이므로 값은 11이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "단답형 1",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 17,
    "displayNo": "단답형 1",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|단답형 1",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ab0dc97f996440618425ef82e39fe23bb2573f46bd1fe04dbbda9a3b451b30ec"
  },
  {
    "id": 18,
    "level": "",
    "category": "여러 가지 미분법",
    "originalCategory": "여러 가지 미분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-05",
    "standardUnit": "여러 가지 미분법",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "subUnit": "여러 가지 미분법",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 미분법"
    ],
    "wide": false,
    "content": "매개변수 $\\theta$로 나타내어진 함수 $x=\\sin\\theta$, $y=2\\cos\\theta$에 대하여 $\\theta=\\dfrac{\\pi}{3}$일 때, $\\dfrac{d^2y}{dx^2}$의 값을 구하시오. [5점]",
    "choices": [],
    "answer": "$-16$",
    "solution": "$\\dfrac{dy}{dx}=\\dfrac{dy/d\\theta}{dx/d\\theta}=-2\\tan\\theta$이다. 따라서 $\\dfrac{d^2y}{dx^2}=\\dfrac{d(-2\\tan\\theta)/d\\theta}{dx/d\\theta}=-2\\sec^3\\theta$이다. $\\theta=\\pi/3$에서 $-2\\cdot2^3=-16$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "단답형 2",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 18,
    "displayNo": "단답형 2",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|단답형 2",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "high",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f51e2b7f384181ec342f28c7e9f75071ebf78868d1868d179244c529e17437af"
  },
  {
    "id": 19,
    "level": "",
    "category": "여러 가지 적분법",
    "originalCategory": "여러 가지 적분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-07",
    "standardUnit": "여러 가지 적분법",
    "standardUnitOrder": 7,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 적분법"
    ],
    "wide": false,
    "content": "모든 실수 $x$에 대하여 미분가능한 함수 $f(x)$가 $\\int_0^x f(t)\\,dt-e^4x=\\int_0^x (x-t)f(t)\\,dt$를 만족시킬 때, $f(-2)$의 값을 구하는 과정을 서술하시오. [5점]",
    "choices": [],
    "answer": "$e^2$",
    "solution": "양변을 $x$에 대하여 미분하면 $f(x)-e^4=\\int_0^xf(t)dt$이다. $x=0$에서 $f(0)=e^4$이다. 이 식을 다시 미분하면 $f'(x)=f(x)$이므로 $(e^{-x}f(x))'=0$이다. 따라서 $e^{-x}f(x)$는 상수이고, $f(0)=e^4$에서 $f(x)=e^{x+4}$이다. 그러므로 $f(-2)=e^2$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "서·논술형 1",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 19,
    "displayNo": "서·논술형 1",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|서·논술형 1",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.92,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:daf4ca34e2a1fd072c21307c36af7cf057e06bb76c3c3d57cc81187a7138fb12"
  },
  {
    "id": 20,
    "level": "",
    "category": "급수",
    "originalCategory": "급수",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-02",
    "standardUnit": "급수",
    "standardUnitOrder": 2,
    "subUnitKey": "H15-CALC-02-SERIES",
    "subUnit": "급수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "급수"
    ],
    "wide": false,
    "content": "자연수 $n$에 대하여 $a_n=\\int_e^1\\dfrac{(\\ln x)^n}{x}\\,dx$일 때, $\\sum_{n=1}^{\\infty}a_na_{n+1}$의 값을 구하는 과정을 서술하시오. [7점]",
    "choices": [],
    "answer": "$\\dfrac{1}{2}$",
    "solution": "$u=\\ln x$로 치환하면 $a_n=\\int_1^0u^n du=-\\dfrac1{n+1}$이다. 그러므로 $a_na_{n+1}=\\dfrac1{(n+1)(n+2)}=\\dfrac1{n+1}-\\dfrac1{n+2}$이다. 부분합은 $\\dfrac12-\\dfrac1{N+2}$이므로 $N\\to\\infty$일 때 합은 $1/2$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "서·논술형 2",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 20,
    "displayNo": "서·논술형 2",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|서·논술형 2",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.92,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-CALC-02-SERIES",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:48da818c0008eba34c943d7c0354227603b061fd3ce2198ebf24653ac1c70604"
  },
  {
    "id": 21,
    "level": "",
    "category": "여러 가지 미분법",
    "originalCategory": "여러 가지 미분법",
    "standardCourse": "미적분",
    "standardUnitKey": "H15-CALC-05",
    "standardUnit": "여러 가지 미분법",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "subUnit": "여러 가지 미분법",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고2",
      "미적분",
      "여러 가지 미분법"
    ],
    "wide": false,
    "content": "함수 $f(x)=(x^2+ax+b)e^x$와 함수 $g(x)$가 다음 조건을 만족시킨다.\n(가) $f(1)=e$, $f'(1)=e$\n(나) 모든 실수 $x$에 대하여 $g(f(x))=f'(x)$이다.\n함수 $h(x)=f^{-1}(x)g(x)$에 대하여 $h'(e)$의 값을 구하는 과정을 서술하시오. (단, $a$, $b$는 상수이다.) [8점]",
    "choices": [],
    "answer": "$4$",
    "solution": "조건 (가)의 $f(1)=e$에서 $a+b=0$이다.\n$f'(x)=(x^2+(a+2)x+a+b)e^x$이고 $f'(1)=e$에서 $2a+b=-2$이다. 두 식을 풀면 $a=-2,b=2$이므로 $f(x)=(x^2-2x+2)e^x=((x-1)^2+1)e^x$이고 $f'(x)=x^2e^x$이다. $f'(x)>0$ ($x\\ne0$)이므로 $f$는 엄격히 증가한다. 또한 $x\\to-\\infty$에서 $f(x)\\to0$, $x\\to\\infty$에서 $f(x)\\to\\infty$이므로 $f$의 치역은 $(0,\\infty)$이고 역함수가 존재한다.\n조건 (나)와 $f(1)=e$에서 $f^{-1}(e)=1$, $g(e)=f'(1)=e$이다. $g(f(x))=f'(x)$를 미분하면 $g'(f(x))f'(x)=f''(x)$이다. $f''(x)=(x^2+2x)e^x$이므로 $g'(e)=3$이다. 또 $(f^{-1})'(e)=1/f'(1)=1/e$이다.\n따라서 $h'(e)=(f^{-1})'(e)g(e)+f^{-1}(e)g'(e)=1+3=4$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "25_금당고_2학기_기말_고2_미적분",
    "sourceFile": "D:\\기출\\(4)2기말\\미적분\\2025_금당고2_미적분_2기말.pdf",
    "sourceQuestionNo": "서·논술형 3",
    "sourceArchiveFile": "original/high/h2/2final/25_금당고_2학기_기말_고2_미적분.js",
    "sourceOrdinal": 21,
    "displayNo": "서·논술형 3",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020",
    "sourceIdentityKey": "sha256:0b4a3e6e1fb32fe42fa43949e26ebc73b42514edaa6bc0e20d23c6d4027cd020|서·논술형 3",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\source-pilot-20260928-01\\AP------\\archive-work\\evidence\\25_금당고_2학기_기말_고2_미적분\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.92,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-CALC-05-OTHER_DIFFERENTIATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e3b869fcdf1e5a0081f3d660ed3d16156b01165296ad944f85a1079eafa67362"
  }
];
