// Generated by archive/tools/intelligence/build-approved-question-metadata-v1.mjs
(function(){
  const state = { data: null, byUid: new Map(), bySource: new Map() };
  function sourceFile(value) { return String(value || '').replace(/\\/g, '/').replace(/^\.?\/?archive\/exams\//, '').replace(/^\.?\/?exams\//, '').replace(/^\/+/, '').replace(/[?#].*$/, '').trim(); }
  function get(questionUidInput, sourceFileInput, ordinal) {
    const questionUid = String(questionUidInput || '').trim();
    if (questionUid && state.byUid.has(questionUid)) return state.byUid.get(questionUid);
    const file = sourceFile(sourceFileInput);
    const n = Number(ordinal);
    if (file && Number.isInteger(n) && n > 0) return state.bySource.get(file + '#' + n) || null;
    return null;
  }
  window.getArchiveQuestionMetadata = function(ref) {
    const value = ref || {};
    return get(value.questionUid || value.sourceQuestionUid, value.sourceArchiveFile || value.sourceFile, value.sourceOrdinal || value.sourceQuestionOrdinal);
  };
  window.mergeArchiveQuestionMetadata = function(question, ref) {
    const q = question || {};
    const meta = window.getArchiveQuestionMetadata(ref);
    if (!meta) return q;
    const merged = { ...q };
    const conflicts = {};
    for (const field of ['standardCourse','standardUnitKey','standardUnit','subUnitKey','subUnit','conceptClusterKey','problemTypeKey','templateKey','difficultyBucket','tagConfidence','tagStatus','metadataStatus','metadataRevision']) {
      const sourceValue = merged[field];
      const metadataValue = meta[field];
      const sourceText = sourceValue === undefined || sourceValue === null ? '' : String(sourceValue).trim();
      const metadataText = metadataValue === undefined || metadataValue === null ? '' : String(metadataValue).trim();
      if (!sourceText && metadataText) merged[field] = metadataValue;
      else if (sourceText && metadataText && sourceText !== metadataText) conflicts[field] = { source: sourceValue, metadata: metadataValue };
    }
    merged._archiveMetadata = meta;
    if (Object.keys(conflicts).length) {
      merged._archiveMetadataConflicts = conflicts;
      merged._archiveMetadataMergeStatus = 'SOURCE_CONFLICT_HOLD';
    }
    return merged;
  };
  window.__ARCHIVE_METADATA_READY__ = fetch(new URL('data/question_metadata.json', document.baseURI))
    .then(response => { if (!response.ok) throw new Error('metadata sidecar HTTP ' + response.status); return response.json(); })
    .then(data => {
      state.data = data;
      for (const record of data.records || []) {
        state.byUid.set(record.questionUid, record);
        state.bySource.set(record.sourceArchiveFile + '#' + record.sourceOrdinal, record);
      }
      window.ARCHIVE_QUESTION_METADATA = data;
      return data;
    })
    .catch(error => { console.warn('[metadata] approved sidecar load failed:', error); return null; });
})();
