window.examTitle = "19_연향중2_1학기_중간_중2";

window.questionBank = [
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
},
    {
    id: "",
    content: "",
    choices: [],
    answer: "",
    category: "",
    originalCategory: "",
    standardCourse: "",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    solution: ""
}
];
