window.examTitle = "26_AP수학_1학기_중간_중1_중간평가_확인";

window.questionBank = [
  {
    id: 1,
    level: "하",
    category: "소인수분해",
    originalCategory: "소인수분해",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 소수를 고르시오. [3점]",
    choices: [
      "1",
      "9",
      "11",
      "21",
      "27"
    ],
    answer: "③",
    solution: ""
  },
  {
    id: 2,
    level: "중",
    category: "소인수분해",
    originalCategory: "소인수분해",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "소수와 합성수에 대한 설명으로 옳은 것을 고르시오. [4점]",
    choices: [
      "1은 가장 작은 소수이다.",
      "2는 가장 작은 소수이다.",
      "모든 홀수는 소수이다.",
      "소수의 약수는 자기 자신뿐이다.",
      "합성수는 약수가 항상 3개이다."
    ],
    answer: "②",
    solution: ""
  },
  {
    id: 3,
    level: "하",
    category: "소인수분해",
    originalCategory: "소인수분해",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$3^3$은 $a$를 $b$번 곱한 것이므로 $c$이다. $a+b+c$의 값을 고르시오. [3점]",
    choices: [
      "9",
      "18",
      "27",
      "30",
      "33"
    ],
    answer: "⑤",
    solution: ""
  },
  {
    id: 4,
    level: "하",
    category: "소인수분해",
    originalCategory: "소인수분해",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "42를 소인수분해한 것으로 옳은 것을 고르시오. [3점]",
    choices: [
      "$2 \\times 21$",
      "$3 \\times 14$",
      "$6 \\times 7$",
      "$2 \\times 3 \\times 7$",
      "$1 \\times 42$"
    ],
    answer: "④",
    solution: ""
  },
  {
    id: 5,
    level: "중",
    category: "소인수분해",
    originalCategory: "소인수분해",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "180과 소인수가 모두 같은 수를 고르시오. [4점]",
    choices: [
      "72",
      "75",
      "$2^2 \\times 3^2 \\times 7$",
      "420",
      "270"
    ],
    answer: "⑤",
    solution: ""
  },
  {
    id: 6,
    level: "중",
    category: "소인수분해",
    originalCategory: "소인수분해",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["표"],
    wide: false,
    content: "ㄱ~ㅂ 중 $2 \\times 3^2 \\times 5$의 약수와 배수를 옳게 짝지은 것을 고르시오. [4점]<div class=\"question-table-wrap\"><table><tr><td>ㄱ. $3^2$<br>ㄴ. $2 \\times 5$<br>ㄷ. $2^2 \\times 3$<br>ㄹ. $2 \\times 3^2 \\times 5^2$<br>ㅁ. $2 \\times 3 \\times 5$<br>ㅂ. $2 \\times 3 \\times 5 \\times 7$</td></tr></table></div>",
    choices: [
      "약수: ㄱ, ㄴ, 배수: ㄹ",
      "약수: ㄱ, ㄴ, ㅁ, 배수: ㄹ",
      "약수: ㄴ, ㅁ, 배수: ㄹ, ㅂ",
      "약수: ㄱ, ㄴ, ㅁ, 배수: ㅂ",
      "약수: ㄷ, ㅁ, 배수: ㄹ"
    ],
    answer: "②",
    solution: ""
  },
  {
    id: 7,
    level: "상",
    category: "소인수분해",
    originalCategory: "소인수분해",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 나타낸 수의 약수의 개수가 가장 많은 것을 고르시오. [4.5점]",
    choices: [
      "256",
      "$2^2 \\times 3 \\times 5$",
      "$3^4 \\times 4$",
      "90",
      "$2^5 \\times 3$"
    ],
    answer: "③",
    solution: ""
  },
  {
    id: 8,
    level: "중",
    category: "소인수분해",
    originalCategory: "최대공약수와 최소공배수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 자리 자연수 중에서 21과 서로소인 자연수는 모두 몇 개인지 고르시오. [4점]",
    choices: [
      "42",
      "46",
      "48",
      "50",
      "52"
    ],
    answer: "③",
    solution: ""
  },
  {
    id: 9,
    level: "상",
    category: "소인수분해",
    originalCategory: "최대공약수와 최소공배수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "서로 다른 세 자연수 18, 30, □ 의 최대공약수가 6, 최소공배수가 90이다. $\\square$가 될 수 있는 수가 몇 개인지 고르시오. [5점]",
    choices: [
      "1개",
      "2개",
      "3개",
      "4개",
      "6개"
    ],
    answer: "②",
    solution: ""
  },
  {
    id: 10,
    level: "하",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "15000원 용돈 받은 것을 +15000원이라고 나타낼 때, 간식비로 4500원을 쓴 것을 옳게 나타낸 것을 고르시오. [3점]",
    choices: [
      "+4500원",
      "+10500원",
      "-4500원",
      "-10500원",
      "-15000원"
    ],
    answer: "③",
    solution: ""
  },
  {
    id: 11,
    level: "하",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "정수와 유리수에 대한 설명으로 옳은 것을 고르시오. [3점]",
    choices: [
      "$\\frac{9}{3}$은 정수가 아닌 유리수다.",
      "-5는 자연수다.",
      "0은 양수이다.",
      "$-2.5$는 정수가 아닌 유리수다.",
      "모든 유리수는 정수이다."
    ],
    answer: "④",
    solution: ""
  },
  {
    id: 12,
    level: "중",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["도형"],
    wide: false,
    content: "ㄱ~ㅁ에 대응하는 수로 옳지 않은 것을 고르시오. [4점]<br><svg width=\"360\" height=\"105\" viewBox=\"0 0 360 105\" xmlns=\"http://www.w3.org/2000/svg\"><line x1=\"20\" y1=\"52\" x2=\"340\" y2=\"52\" stroke=\"black\" stroke-width=\"1.2\"/><path d=\"M340 52 l-7 -4 v8 z\" fill=\"black\"/><path d=\"M20 52 l7 -4 v8 z\" fill=\"black\"/><line x1=\"20\" y1=\"45\" x2=\"20\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"20\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">-5</text><line x1=\"52\" y1=\"45\" x2=\"52\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"52\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">-4</text><line x1=\"84\" y1=\"45\" x2=\"84\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"84\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">-3</text><line x1=\"116\" y1=\"45\" x2=\"116\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"116\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">-2</text><line x1=\"148\" y1=\"45\" x2=\"148\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"148\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">-1</text><line x1=\"180\" y1=\"43\" x2=\"180\" y2=\"61\" stroke=\"black\" stroke-width=\"1.4\"/><text x=\"180\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\" font-weight=\"bold\">0</text><line x1=\"212\" y1=\"45\" x2=\"212\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"212\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">1</text><line x1=\"244\" y1=\"45\" x2=\"244\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"244\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">2</text><line x1=\"276\" y1=\"45\" x2=\"276\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"276\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">3</text><line x1=\"308\" y1=\"45\" x2=\"308\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"308\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">4</text><line x1=\"340\" y1=\"45\" x2=\"340\" y2=\"59\" stroke=\"black\" stroke-width=\"1\"/><text x=\"340\" y=\"76\" font-size=\"8\" font-family=\"serif\" text-anchor=\"middle\">5</text><line x1=\"60\" y1=\"48\" x2=\"60\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><line x1=\"68\" y1=\"48\" x2=\"68\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><line x1=\"76\" y1=\"48\" x2=\"76\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><text x=\"68\" y=\"91\" font-size=\"7\" font-family=\"serif\" text-anchor=\"middle\">4등분</text><line x1=\"126.667\" y1=\"48\" x2=\"126.667\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><line x1=\"137.333\" y1=\"48\" x2=\"137.333\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><text x=\"132\" y=\"91\" font-size=\"7\" font-family=\"serif\" text-anchor=\"middle\">3등분</text><line x1=\"188\" y1=\"48\" x2=\"188\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><line x1=\"196\" y1=\"48\" x2=\"196\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><line x1=\"204\" y1=\"48\" x2=\"204\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><text x=\"196\" y=\"91\" font-size=\"7\" font-family=\"serif\" text-anchor=\"middle\">4등분</text><line x1=\"254.667\" y1=\"48\" x2=\"254.667\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><line x1=\"265.333\" y1=\"48\" x2=\"265.333\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><text x=\"260\" y=\"91\" font-size=\"7\" font-family=\"serif\" text-anchor=\"middle\">3등분</text><line x1=\"316\" y1=\"48\" x2=\"316\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><line x1=\"324\" y1=\"48\" x2=\"324\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><line x1=\"332\" y1=\"48\" x2=\"332\" y2=\"56\" stroke=\"black\" stroke-width=\"0.7\"/><text x=\"324\" y=\"91\" font-size=\"7\" font-family=\"serif\" text-anchor=\"middle\">4등분</text><circle cx=\"76\" cy=\"52\" r=\"2.4\" fill=\"black\"/><text x=\"76\" y=\"38\" font-size=\"10\" font-family=\"serif\" text-anchor=\"middle\" font-weight=\"bold\">ㄱ</text><circle cx=\"126.667\" cy=\"52\" r=\"2.4\" fill=\"black\"/><text x=\"126.667\" y=\"38\" font-size=\"10\" font-family=\"serif\" text-anchor=\"middle\" font-weight=\"bold\">ㄴ</text><circle cx=\"204\" cy=\"52\" r=\"2.4\" fill=\"black\"/><text x=\"204\" y=\"38\" font-size=\"10\" font-family=\"serif\" text-anchor=\"middle\" font-weight=\"bold\">ㄷ</text><circle cx=\"254.667\" cy=\"52\" r=\"2.4\" fill=\"black\"/><text x=\"254.667\" y=\"38\" font-size=\"10\" font-family=\"serif\" text-anchor=\"middle\" font-weight=\"bold\">ㄹ</text><circle cx=\"316\" cy=\"52\" r=\"2.4\" fill=\"black\"/><text x=\"316\" y=\"38\" font-size=\"10\" font-family=\"serif\" text-anchor=\"middle\" font-weight=\"bold\">ㅁ</text></svg>",
    choices: [
      "ㄱ : $-\\frac{13}{4}$",
      "ㄴ : $-\\frac{5}{3}$",
      "ㄷ : $+\\frac{3}{4}$",
      "ㄹ : $+\\frac{7}{3}$",
      "ㅁ : $+\\frac{9}{2}$"
    ],
    answer: "⑤",
    solution: ""
  },
  {
    id: 13,
    level: "하",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "절댓값이 같고 부호가 다른 두 수가 있다. 두 수에 대응하는 점을 수직선 위에 나타내면 그 사이의 거리가 14이다. 이때 두 수를 구하시오. [3점]",
    choices: [
      "-14, 14",
      "-7, 7",
      "-6, 8",
      "0, 14",
      "-4, 10"
    ],
    answer: "②",
    solution: ""
  },
  {
    id: 14,
    level: "하",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 수의 대소관계가 옳지 않은 것을 고르시오. [3점]",
    choices: [
      "$-5 \\lt -2$",
      "$-3 \\gt 0$",
      "$1 \\lt 4$",
      "$-8 \\lt -1$",
      "$0 \\lt 6$"
    ],
    answer: "②",
    solution: ""
  },
  {
    id: 15,
    level: "중",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 수의 덧셈과 뺄셈의 결과로 옳지 않은 것을 고르시오. [4점]",
    choices: [
      "$(-8)-(-3)=-11$",
      "$(-7)+(+12)=+5$",
      "$(+6)-(+10)=-4$",
      "$(-5)-(+8)=-13$",
      "$(-3)+(-4)=-7$"
    ],
    answer: "①",
    solution: ""
  },
  {
    id: 16,
    level: "하",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$-7-18$을 계산한 값을 고르시오. [4점]",
    choices: [
      "-25",
      "25",
      "11",
      "-11",
      "-1"
    ],
    answer: "①",
    solution: ""
  },
  {
    id: 17,
    level: "중",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "8에 -5를 더한 수를 $a$, 4에서 +6을 뺀 수를 $b$라고 할 때, $a-b$의 값을 구하시오. [4점]",
    choices: [
      "-5",
      "-3",
      "1",
      "5",
      "7"
    ],
    answer: "④",
    solution: ""
  },
  {
    id: 18,
    level: "중",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["표"],
    wide: false,
    content: "다음 이야기를 통해 알 수 있는 것으로 옳은 것을 고르시오. [4점]<div class=\"question-table-wrap\"><table><tr><td>[저금통 이야기]<br>저금통에 빚 기록표 4장을 없애면 돈이 4칸 늘어난 것과 같은 효과가 나타난다. 반대로 저금 기록표 4장을 없애면 돈이 4칸 줄어든 것과 같은 효과가 나타난다. 즉, 어떤 양을 빼는 것은 그 양과 부호가 반대인 수를 더하는 것과 같은 효과가 나타난다.</td></tr></table></div>",
    choices: [
      "부호가 같은 두 수의 덧셈은 절댓값의 합에 공통인 부호를 붙인다.",
      "부호가 다른 두 수의 덧셈은 절댓값의 차에 절댓값이 더 큰 수의 부호를 붙인다.",
      "부호가 같은 두 수의 곱셈은 절댓값의 곱에 양의 부호를 붙인다.",
      "두 수의 나눗셈은 나누는 수의 역수를 곱한다.",
      "두 수의 뺄셈은 빼는 수의 부호를 바꾸어 더하는 것과 같다."
    ],
    answer: "⑤",
    solution: ""
  },
  {
    id: 19,
    level: "중",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 수의 곱셈과 나눗셈의 결과로 옳지 않은 것을 고르시오. [4점]",
    choices: [
      "$(-6)\\times(-4)=+24$",
      "$(-18)\\div(+3)=-6$",
      "$(+7)\\times(-5)=-35$",
      "$(-24)\\div(-6)=-4$",
      "$(-30)\\div(+5)=-6$"
    ],
    answer: "④",
    solution: ""
  },
  {
    id: 20,
    level: "상",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["표"],
    wide: false,
    content: "다음 네 개의 유리수 중에서 서로 다른 두 수를 골라서 곱한다. 이때 곱한 값 중에서 가장 작은 수를 고르시오. [4.5점]<div class=\"question-table-wrap\"><table><tr><td>$0.75$ &nbsp;&nbsp;&nbsp; $-3$ &nbsp;&nbsp;&nbsp; $-\\frac{1}{2}$ &nbsp;&nbsp;&nbsp; $+4$</td></tr></table></div>",
    choices: [
      "3",
      "$\\frac{3}{2}$",
      "$-\\frac{3}{8}$",
      "$-12$",
      "$-36$"
    ],
    answer: "④",
    solution: ""
  },
  {
    id: 21,
    level: "상",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$-2+\\left\\{(-6)\\div3-(-3)^2\\right\\}\\times\\left(-\\frac{1}{4}\\right)$ 의 계산한 값을 고르시오. [5점]",
    choices: [
      "$-\\frac{19}{4}$",
      "$-\\frac{3}{4}$",
      "$\\frac{1}{4}$",
      "$\\frac{3}{4}$",
      "$\\frac{11}{4}$"
    ],
    answer: "④",
    solution: ""
  },
  {
    id: 22,
    level: "상",
    category: "소인수분해",
    originalCategory: "소인수분해",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-01",
    standardUnit: "소인수분해",
    standardUnitOrder: 1,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "$a, b$가 자연수이고 $12\\times a=b^2$이라고 한다. 이 조건을 만족하는 가장 작은 세 자리 자연수 $a$와 그때의 자연수 $b$를 구하는 과정을 서술하시오. [6점]",
    choices: [],
    answer: "$a=108$, $b=36$",
    solution: ""
  },
  {
    id: 23,
    level: "상",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "어떤 수에 $-\\frac{3}{4}$를 더해야 할 것을 잘못하여 뺐더니 $\\frac{5}{12}$가 되었다. 어떤 수와 바르게 계산한 값을 구하는 과정을 각각 서술하시오. [7점]",
    choices: [],
    answer: "어떤 수: $-\\frac{1}{3}$, 바르게 계산한 값: $-\\frac{13}{12}$",
    solution: ""
  },
  {
    id: 24,
    level: "상",
    category: "정수와 유리수",
    originalCategory: "정수와 유리수",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-02",
    standardUnit: "정수와 유리수",
    standardUnitOrder: 2,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "세 수 $a, b, c$에 대하여 $a-b<0$, $a\\times c<0$, $b\\times c>0$일 때 $a, b, c$의 부호를 각각 판단하고 그 이유를 서술하시오. [7점]",
    choices: [],
    answer: "$a<0$, $b>0$, $c>0$",
    solution: ""
  }
];