window.examTitle = "21_금당중_1학기_중간_중3_기출";

window.questionBank = [
    {
        id: "1",
        content: "다음 중 옳은 것은? [3점]",
        choices: ["$\\sqrt{25}=\\pm5$이다.", "제곱근 $3$은 $9$이다.", "$0$의 제곱근은 없다.", "$-4$의 제곱근은 $-2$이다.", "$3$의 제곱근은 $\\pm\\sqrt{3}$이다."],
        answer: "⑤",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "2",
        content: "$\\sqrt{16}$의 제곱근은? [4점]",
        choices: ["$2$", "$\\pm2$", "$\\pm\\sqrt{2}$", "$4$", "$\\pm4$"],
        answer: "②",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "3",
        content: "다음 조건을 만족하는 자연수 $x, y$에 대하여 $x+y$의 최솟값은? [4점]<div class='box'>[조건1] $\\sqrt{50x}$는 자연수이다.<br>[조건2] $\\sqrt{45y}$는 자연수이다.</div>",
        choices: ["", "", "", "", ""],
        answer: "②",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "4",
        content: "두 수의 대소관계가 옳은 것은? [3점]",
        choices: ["$4 < \\sqrt{10}$", "$\\frac{1}{2} > \\sqrt{\\frac{1}{2}}$", "$2+\\sqrt{5} > 5$", "$-3 > -\\sqrt{3}$", "$5-\\sqrt{3} > 3$"],
        answer: "⑤",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "5",
        content: "$\\sqrt{90-n}$이 정수가 되도록 하는 자연수 $n$의 값은 몇 개인가? [4점]",
        choices: ["개", "개", "개", "개", "개"],
        answer: "③",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "6",
        content: "[보기]에 주어진 수에서 무리수는 모두 몇 개인가? [4점]<div class='box'>[보기]<br>$\\sqrt{49}$, $0.4\\dot{1}$, $-\\sqrt{21}$, $\\sqrt{(-3.14)^2}$, $\\sqrt{2}+3$, $\\pi$</div>",
        choices: ["개", "개", "개", "개", "개"],
        answer: "③",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "7",
        content: "아래 주어진 표는 $x$값에 따른 $x^2$의 값을 구해 놓은 것이다. $\\sqrt{5}$의 소수점 첫째자리 수는 $a$이고, $\\sqrt{6}$의 소수점 첫째자리 수는 $b$이다. $a+b$의 값은? [4점]<br><table style='border:1px solid black; border-collapse:collapse; text-align:center;'><tr><td style='border:1px solid black; padding:5px;'>$x$</td><td style='border:1px solid black; padding:5px;'>2.1</td><td style='border:1px solid black; padding:5px;'>2.2</td><td style='border:1px solid black; padding:5px;'>2.3</td><td style='border:1px solid black; padding:5px;'>2.4</td><td style='border:1px solid black; padding:5px;'>2.5</td></tr><tr><td style='border:1px solid black; padding:5px;'>$x^2$</td><td style='border:1px solid black; padding:5px;'>4.41</td><td style='border:1px solid black; padding:5px;'>4.84</td><td style='border:1px solid black; padding:5px;'>5.29</td><td style='border:1px solid black; padding:5px;'>5.76</td><td style='border:1px solid black; padding:5px;'>6.25</td></tr></table>",
        choices: ["", "", "", "", ""],
        answer: "②",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "8",
        content: "다음 중 옳은 것은? [4점]",
        choices: ["무한소수는 무리수이다.", "모든 수의 제곱근은 2개이다.", "정수가 아닌 수는 무리수이다.", "$0$은 유리수도 무리수도 아니다.", "(유리수)+(무리수)는 항상 무리수이다."],
        answer: "⑤",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "9",
        content: "아래 그림과 같이 컴퍼스를 사용하여 원점 $O$를 중심으로 하고 $\\overline{OA}$의 길이를 반지름으로 하는 원을 그려 수직선과 만나는 점을 $P$라 하였다. 직각삼각형 $OBP$에서 $\\overline{BP}=1$이고, $\\overline{OB}=\\overline{OQ}$일 때, 점 $Q$가 나타내는 수는? (단, $\\overline{OA}$는 한 변의 길이가 $1$인 정사각형의 대각선이다.) [4점]<br><Figure src='image_e1c229.png' />",
        choices: ["$\\sqrt{2}$", "$\\sqrt{3}$", "", "$\\sqrt{5}$", "$\\sqrt{6}$"],
        answer: "②",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "10",
        content: "다음 중 옳은 것은? [3점]",
        choices: ["$\\sqrt{8} \\div \\sqrt{2} = 4$", "$\\sqrt{5} \\times \\sqrt{2} = 10$", "$\\sqrt{(-5)^2} = -5$", "$\\sqrt{3} + \\sqrt{3} = \\sqrt{6}$", "$2\\sqrt{2} - \\sqrt{2} = \\sqrt{2}$"],
        answer: "⑤",
        category: "근호를 포함한 식의 계산",
        originalCategory: "근호를 포함한 식의 계산",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "11",
        content: "$3\\sqrt{24} - \\frac{2\\sqrt{3}}{\\sqrt{2}}$를 간단히 하면 $a\\sqrt{6}$이 된다. 유리수 $a$의 값은? [4점]",
        choices: ["", "", "", "", ""],
        answer: "①",
        category: "근호를 포함한 식의 계산",
        originalCategory: "근호를 포함한 식의 계산",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "12",
        content: "다음 중 가장 작은 수는? [5점]",
        choices: ["$\\sqrt{18}$", "$\\frac{8-\\sqrt{6}}{\\sqrt{2}}$", "$\\sqrt{3}+\\sqrt{8}$", "$\\frac{6+\\sqrt{6}}{\\sqrt{3}}$", "$2\\sqrt{7}-\\sqrt{2}$"],
        answer: "②",
        category: "근호를 포함한 식의 계산",
        originalCategory: "근호를 포함한 식의 계산",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "13",
        content: "다음 그림과 같이 네 개의 정사각형 $A, B, C, D$를 이어 붙여서 새로운 도형을 만들었다. 이 도형의 둘레의 길이는? (단, $A$의 넓이는 $B$의 넓이의 $2$배, $B$는 $C$의 $2$배, $C$는 $D$의 $2$배이며 $A$의 넓이는 $8$이다.) [5점]<br><svg width='160' height='120' viewBox='0 0 160 120'><rect x='10' y='50' width='40' height='40' fill='none' stroke='black'/><rect x='50' y='61.7' width='28.3' height='28.3' fill='none' stroke='black'/><rect x='78.3' y='70' width='20' height='20' fill='none' stroke='black'/><rect x='98.3' y='75.9' width='14.1' height='14.1' fill='none' stroke='black'/><text x='25' y='75' font-size='12'>A</text><text x='60' y='80' font-size='10'>B</text><text x='85' y='85' font-size='8'>C</text><text x='102' y='88' font-size='6'>D</text></svg>",
        choices: ["$4\\sqrt{2}+8$", "$6\\sqrt{2}+6$", "$8\\sqrt{2}+4$", "$10\\sqrt{2}+6$", "$12\\sqrt{2}+4$"],
        answer: "④",
        category: "근호를 포함한 식의 계산",
        originalCategory: "근호를 포함한 식의 계산",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "14",
        content: "다음 중 주어진 식을 바르게 전개한 것은? [4점]",
        choices: ["$(a+b)^2 = a^2+b^2$", "$(a+5)(a-5) = -25a$", "$(a-3)^2 = a^2-6a+9$", "$(a+3)(a-5) = a^2-15$", "$(2a+1)(2a-3) = 4a^2-2a-3$"],
        answer: "③",
        category: "다항식의 곱셈",
        originalCategory: "다항식의 곱셈",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-02",
        standardUnit: "다항식의 곱셈",
        standardUnitOrder: 2,
        solution: ""
    },
    {
        id: "15",
        content: "아래 그림과 같이 합동인 두 사다리꼴을 이어 붙여 만든 직사각형의 넓이는? (단, 사다리꼴의 윗변은 $a$, 아랫변은 $b$, 높이는 $a-b$이다.) [4점]<br><svg width='160' height='120' viewBox='0 0 160 120'><rect x='20' y='30' width='120' height='60' fill='none' stroke='black' stroke-dasharray='4'/><line x1='70' y1='30' x2='90' y2='90' stroke='black'/><text x='45' y='25' font-size='10'>a</text><text x='105' y='25' font-size='10'>b</text><text x='145' y='65' font-size='10'>a-b</text></svg>",
        choices: ["$2ab$", "$a^2+b^2$", "$a^2-b^2$", "$a^2+2ab+b^2$", "$a^2-2ab+b^2$"],
        answer: "③",
        category: "다항식의 곱셈",
        originalCategory: "다항식의 곱셈",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-02",
        standardUnit: "다항식의 곱셈",
        standardUnitOrder: 2,
        solution: ""
    },
    {
        id: "16",
        content: "그림과 같이 한 변의 길이가 각각 $x, y$인 두 정사각형이 있다. $x+y=8, xy=14$일 때, 두 정사각형의 넓이의 합은? [5점]<br><svg width='160' height='120' viewBox='0 0 160 120'><rect x='20' y='40' width='50' height='50' fill='none' stroke='black'/><rect x='70' y='60' width='30' height='30' fill='none' stroke='black'/><text x='40' y='35' font-size='12'>x</text><text x='80' y='55' font-size='12'>y</text></svg>",
        choices: ["", "", "", "", ""],
        answer: "①",
        category: "다항식의 곱셈",
        originalCategory: "다항식의 곱셈",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-02",
        standardUnit: "다항식의 곱셈",
        standardUnitOrder: 2,
        solution: ""
    },
    {
        id: "17",
        content: "$\\frac{3+\\sqrt{6}}{3-\\sqrt{6}}$을 간단히 하면 $a+b\\sqrt{6}$이 된다. $a, b$가 유리수일 때, $a+b$의 값은? [4점]",
        choices: ["", "", "", "", ""],
        answer: "③",
        category: "근호를 포함한 식의 계산",
        originalCategory: "근호를 포함한 식의 계산",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "18",
        content: "다음 두 다항식에 공통으로 들어있는 인수는? [4점]<div class='box'>$9x^2-1$, $3x(x+2)-(x+2)$</div>",
        choices: ["$a-b$", "$x+2$", "$x+3$", "$3x+1$", "$3x-1$"],
        answer: "⑤",
        category: "인수분해",
        originalCategory: "인수분해",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-03",
        standardUnit: "인수분해",
        standardUnitOrder: 3,
        solution: ""
    },
    {
        id: "19",
        content: "다항식 $3x^2+x-10$을 바르게 인수분해한 것은? [4점]",
        choices: ["$x(3x+1)-10$", "$(x+2)(3x-5)$", "$(x+2)(3x+5)$", "$(x-2)(3x+5)$", "$(x-2)(3x-5)$"],
        answer: "②",
        category: "인수분해",
        originalCategory: "인수분해",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-03",
        standardUnit: "인수분해",
        standardUnitOrder: 3,
        solution: ""
    },
    {
        id: "20",
        content: "두 다항식 $x^2-12x+a$와 $4x^2+12x+b$를 완전제곱식이 되도록 하는 수 $a, b$에 대하여 $a+b$의 값은? [4점]",
        choices: ["", "", "", "", ""],
        answer: "②",
        category: "인수분해",
        originalCategory: "인수분해",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-03",
        standardUnit: "인수분해",
        standardUnitOrder: 3,
        solution: ""
    },
    {
        id: "21",
        content: "[서술형1] 다음 그림은 한 눈금의 길이가 $1$인 모눈종이에 두 선분 $AB$와 $CD$를 그린 후, $\\overline{AB}=\\overline{AP}$, $\\overline{CD}=\\overline{CQ}$가 되도록 수직선 위에 두 점 $P$와 $Q$를 정한 것이다. $PQ$의 길이를 구하시오. [6점]<br><Figure src='image_e1c264.png' />",
        choices: [" "],
        answer: "$6-\\sqrt{5}$",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    },
    {
        id: "22",
        content: "[서술형2] $x=2+\\sqrt{3}$일 때, $x^2-4x-5$의 값을 구하시오. [6점]",
        choices: [" "],
        answer: "-6",
        category: "다항식의 곱셈과 인수분해",
        originalCategory: "다항식의 곱셈과 인수분해",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-02",
        standardUnit: "다항식의 곱셈",
        standardUnitOrder: 2,
        solution: ""
    },
    {
        id: "23",
        content: "[서술형3] 다음 제곱근표를 이용하여 주어진 제곱근의 값을 구하시오. [8점]<br>(1) $\\sqrt{5.53}$<br>(2) $\\sqrt{0.553}$<br><Figure src='image_e1c288.jpg' />",
        choices: [" "],
        answer: "(1) 2.352, (2) 0.7436",
        category: "제곱근과 실수",
        originalCategory: "제곱근과 실수",
        standardCourse: "중3 수학",
        standardUnitKey: "M3-01",
        standardUnit: "제곱근과 실수",
        standardUnitOrder: 1,
        solution: ""
    }
];
