window.examTitle = "22_풍덕중_1학기_중간_중3_기출";

window.questionBank = [
  {
    "id": 1,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 보기 중에서 옳은 것은?",
    "choices": [
      "25는 5의 양의 제곱근이다.",
      "양수 $a$의 제곱근은 $\\sqrt{a}$이다.",
      "$\\sqrt{(-3)^2}$은 3이다.",
      "$\\sqrt{36}$의 제곱근은 $\\pm 6$이다.",
      "제곱근 7은 7이다."
    ],
    "answer": "3",
    "solution": "1. 25는 5의 제곱임 (5의 양의 제곱근은 $\\sqrt{5}$) \\\\ 2. 양수 $a$의 제곱근은 $\\pm \\sqrt{a}$ \\\\ 3. $\\sqrt{(-3)^2} = |-3| = 3$ (참) \\\\ 4. $\\sqrt{36}=6 \\implies 6$의 제곱근은 $\\pm \\sqrt{6}$ \\\\ 5. 제곱근 7 = $\\sqrt{7}$ \\\\ $\\therefore$ 3",
    "level": "중"
  },
  {
    "id": 2,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 보기의 두 수를 대소 비교하여 $\\Box$ 안에 부등호를 넣을 때, 부등호 방향이 다른 하나는?",
    "choices": [
      "$\\sqrt{7} \\Box \\sqrt{8}$",
      "$\\sqrt{3} \\Box 4$",
      "$\\sqrt{\\frac{1}{2}} \\Box \\sqrt{\\frac{1}{3}}$",
      "$-\\sqrt{40} \\Box -6$",
      "$5-\\sqrt{2} \\Box 4$"
    ],
    "answer": "3",
    "solution": "1. $7 < 8 \\implies \\sqrt{7}<\\sqrt{8}$ \\\\ 2. $\\sqrt{3}<\\sqrt{16}=4$ \\\\ 3. $\\frac{1}{2} > \\frac{1}{3} \\implies \\sqrt{\\frac{1}{2}}>\\sqrt{\\frac{1}{3}}$ \\\\ 4. $\\sqrt{40}>\\sqrt{36}$이므로 $-\\sqrt{40}<-6$ \\\\ 5. $5-\\sqrt{2}\\approx 3.586<4$ \\\\ 따라서 부등호 방향이 다른 것은 3이다.",
    "level": "중"
  },
  {
    "id": 3,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "식 $(\\sqrt{3})^2 + \\sqrt{5^2}$을 계산한 값은?",
    "choices": [
      "4",
      "25",
      "36",
      "7",
      "8"
    ],
    "answer": "5",
    "solution": "$(\\sqrt{3})^2 = 3 \\\\ \\sqrt{5^2} = 5 \\\\ \\implies 3+5=8 \\\\ \\therefore 5",
    "level": "하"
  },
  {
    "id": 4,
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\sqrt{20}$을 $a\\sqrt{b}$의 꼴로 나타낼 때 정수 $a, b$에 해당하는 수가 순서대로 옳은 것은?",
    "choices": [
      "4, 5",
      "2, 3",
      "2, 5",
      "3, 4",
      "4, 3"
    ],
    "answer": "3",
    "solution": "\\sqrt{20} = \\sqrt{4 \\times 5} = 2\\sqrt{5} \\\\ \\implies a=2, b=5 \\\\ \\therefore 3",
    "level": "하"
  },
  {
    "id": 5,
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다항식 $(x-1)(x+3)$을 바르게 전개한 것은?",
    "choices": [
      "$x^2-3$",
      "$x^2-2x+3$",
      "$x^2-2x-3$",
      "$x^2+2x-3$",
      "$x^2+2x+3$"
    ],
    "answer": "4",
    "solution": "(x-1)(x+3) = x^2 + 3x - x - 3 = x^2+2x-3 \\\\ \\therefore 4",
    "level": "하"
  },
  {
    "id": 6,
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$2xy-8y$에서 두 항 $2xy, -8y$의 공통인 인수는 $2y$이므로 $2xy-8y=2y(\\Box)$이다. $\\Box$에 알맞은 식은?",
    "choices": [
      "$x-4$",
      "$x-4y$",
      "$2x-4y$",
      "$x-2$",
      "$x+4$"
    ],
    "answer": "1",
    "solution": "2xy-8y = 2y \\times x - 2y \\times 4 = 2y(x-4) \\\\ \\therefore 1",
    "level": "하"
  },
  {
    "id": 7,
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["수식박스"],
    "wide": false,
    "content": "다음 식의 빈칸에 들어갈 값을 순서대로 바르게 적은 것은?<div class='box'>$(x-6)^2 = x^2 - \\Box x + \\triangle$ <br> $x^2-36 = (x+\\bigcirc)(x-\\bigcirc)$</div>",
    "choices": [
      "12, 36, 6",
      "12, 35, 6",
      "35, 36, 6",
      "34, 35, 36",
      "36, 12, 12"
    ],
    "answer": "1",
    "solution": "(x-6)^2 = x^2-12x+36 \\implies \\Box=12, \\triangle=36 \\\\ x^2-36 = (x+6)(x-6) \\implies \\bigcirc=6 \\\\ \\therefore 1",
    "level": "하"
  },
  {
    "id": 8,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$0 < a < 3$일 때, $\\sqrt{(3-a)^2} + \\sqrt{a^2}$을 간단히 하면?",
    "choices": [
      "2a+3",
      "2a",
      "3",
      "3-a",
      "3-2a"
    ],
    "answer": "3",
    "solution": "0 < a < 3 \\implies 3-a > 0, a > 0 \\\\ \\implies |3-a| + |a| = (3-a) + a = 3 \\\\ \\therefore 3",
    "level": "중"
  },
  {
    "id": 9,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["수식박스"],
    "wide": false,
    "content": "다음 수의 대소를 비교하여 크기가 작은 수부터 차례로 나열할 때, 3번째로 오는 수는?<div class='box'>$\\sqrt{2}, 1, \\frac{1}{2}, 1-\\sqrt{2}, 5-\\sqrt{2}$</div>",
    "choices": [
      "$\\sqrt{2}$",
      "1",
      "$1-\\sqrt{2}$",
      "$\\frac{1}{2}$",
      "$5-\\sqrt{2}$"
    ],
    "answer": "2",
    "solution": "값 근사: \\sqrt{2} \\approx 1.414, 1, 0.5, 1-1.414 = -0.414, 5-1.414 = 3.586 \\\\ 나열: 1-\\sqrt{2} < \\frac{1}{2} < 1 < \\sqrt{2} < 5-\\sqrt{2} \\\\ \\therefore 3번째는 1",
    "level": "중"
  },
  {
    "id": 10,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["표"],
    "wide": false,
    "content": "다음 보기의 값 중 아래 제곱근표를 보고 구할 수 있는 값이 아닌 것은?<div class='question-table-wrap'><table class='question-table'><tr><th>수</th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th></tr><tr><td>4.5</td><td>2.121</td><td>2.124</td><td>2.126</td><td>2.128</td><td>2.131</td><td>2.133</td></tr><tr><td>4.6</td><td>2.145</td><td>2.147</td><td>2.149</td><td>2.152</td><td>2.154</td><td>2.156</td></tr><tr><td>4.7</td><td>2.168</td><td>2.170</td><td>2.173</td><td>2.175</td><td>2.177</td><td>2.179</td></tr><tr><td>4.8</td><td>2.191</td><td>2.193</td><td>2.195</td><td>2.198</td><td>2.200</td><td>2.202</td></tr><tr><td>4.9</td><td>2.214</td><td>2.216</td><td>2.218</td><td>2.221</td><td>2.223</td><td>2.225</td></tr></table></div><div class='box'>ㄱ. $\\sqrt{4.52}$ ㄴ. $\\sqrt{484}$ ㄷ. $\\sqrt{0.475}$ ㄹ. $\\sqrt{46200}$ ㅁ. $\\sqrt{0.0493}$</div>",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄷ",
      "ㄹ",
      "ㅁ"
    ],
    "answer": "3",
    "solution": "표 범위: 4.50~4.95 \\\\ ㄱ. \\sqrt{4.52} (직접 확인 가능) \\\\ ㄴ. \\sqrt{4.84 \\times 100} = 10\\sqrt{4.84} (가능) \\\\ ㄷ. \\sqrt{0.475} = \\sqrt{\\frac{47.5}{100}} (표에 47.5 없음, 불가능) \\\\ ㄹ. \\sqrt{4.62 \\times 10000} = 100\\sqrt{4.62} (가능) \\\\ ㅁ. \\sqrt{4.93 \\div 100} = \\frac{\\sqrt{4.93}}{10} (가능) \\\\ \\therefore 3",
    "level": "중"
  },
  {
    "id": 11,
    "category": "제곱근과 실수",
    "content": "$\\sqrt{1.3} \\approx a, \\sqrt{2.9} \\approx b$일 때, $\\sqrt{13000} - \\sqrt{0.029}$를 $a, b$를 사용하여 나타내면?",
    "choices": [
      "$100a - \\frac{b}{10}$",
      "$\\frac{a}{10} - 10b$",
      "$100a - \\frac{b}{100}$",
      "$10a - 100b$",
      "$10a - \\frac{b}{10}$"
    ],
    "answer": "1",
    "solution": "\\sqrt{13000} = \\sqrt{1.3 \\times 10000} = 100\\sqrt{1.3} = 100a \\\\ \\sqrt{0.029} = \\sqrt{\\frac{2.9}{100}} = \\frac{\\sqrt{2.9}}{10} = \\frac{b}{10} \\\\ \\therefore 100a - \\frac{b}{10}",
    "level": "중",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 12,
    "category": "근호를 포함한 식의 계산",
    "content": "한 직육면체의 각 변의 길이가 $\\sqrt{2}, \\sqrt{5}, 3+\\sqrt{10}$일 때, 겉넓이를 구하면?",
    "choices": [
      "$13+6\\sqrt{10}$",
      "$14+6\\sqrt{10}$",
      "$15+8\\sqrt{10}$",
      "$2\\sqrt{10}+16\\sqrt{2}+10\\sqrt{5}$",
      "$18+6\\sqrt{10}$"
    ],
    "answer": "4",
    "solution": "겉넓이 = 2 \\times (\\sqrt{2} \\times \\sqrt{5} + \\sqrt{5}(3+\\sqrt{10}) + \\sqrt{2}(3+\\sqrt{10})) \\\\ = 2 \\times (\\sqrt{10} + 3\\sqrt{5} + 5\\sqrt{2} + 3\\sqrt{2} + 2\\sqrt{5}) \\\\ = 2 \\times (\\sqrt{10} + 5\\sqrt{5} + 8\\sqrt{2}) \\\\ = 2\\sqrt{10}+10\\sqrt{5}+16\\sqrt{2} \\\\ \\therefore 4",
    "level": "중",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 13,
    "category": "근호를 포함한 식의 계산",
    "content": "다음 계산식 중 옳지 않은 것은?",
    "choices": [
      "$2\\sqrt{3} \\times 3\\sqrt{3} = 18$",
      "$\\sqrt{12} \\div \\sqrt{3} = \\sqrt{2}$",
      "$(-\\sqrt{2}) \\times (-\\sqrt{5}) = \\sqrt{10}$",
      "$\\sqrt{2} \\div \\sqrt{\\frac{1}{5}} = \\sqrt{10}$",
      "$-\\sqrt{24} \\times \\sqrt{\\frac{1}{6}} = -2$"
    ],
    "answer": "2",
    "solution": "2. $\\sqrt{12} \\div \\sqrt{3} = \\sqrt{4} = 2 \\ne \\sqrt{2}$ \\\\ \\therefore 2",
    "level": "중",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 14,
    "category": "다항식의 곱셈",
    "content": "다음 식 중에서 바르게 전개되지 않은 것은?",
    "choices": [
      "$(2a+b)^2 = 4a^2+4ab+b^2$",
      "$(-a+2b)^2 = a^2-4ab+4b^2$",
      "$(-a+2b)(-a-2b) = a^2-4b^2$",
      "$(x+4)(x-5) = x^2+x-20$",
      "$(2x-1)(3x-1) = 6x^2-5x+1$"
    ],
    "answer": "4",
    "solution": "4. $(x+4)(x-5) = x^2-x-20$이므로 보기의 $x^2+x-20$은 바르게 전개되지 않았다. \\\\ \\therefore 4",
    "level": "하",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 15,
    "category": "인수분해",
    "content": "$x-2$가 이차식 $x^2-ax-6$의 인수일 때, 상수 $a$의 값을 구하면?",
    "choices": [
      "3",
      "-3",
      "-1",
      "-5",
      "5"
    ],
    "answer": "3",
    "solution": "x=2 대입 시 0 \\implies 2^2 - 2a - 6 = 0 \\implies -2 - 2a = 0 \\implies a = -1 \\\\ \\therefore 3",
    "level": "하",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 16,
    "category": "인수분해",
    "content": "$(x+4)(x-2)+k$가 완전제곱식이 되기 위한 양수 $k$의 값을 구하면?",
    "choices": [
      "1",
      "3",
      "5",
      "7",
      "9"
    ],
    "answer": "5",
    "solution": "x^2+2x-8+k \\implies (\\frac{2}{2})^2 = -8+k \\implies 1 = -8+k \\implies k=9 \\\\ \\therefore 5",
    "level": "중",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 17,
    "category": "다항식의 곱셈",
    "content": "$x = \\sqrt{3}-2, y = \\sqrt{3}+2$일 때, $\\frac{y}{x} + \\frac{x}{y}$의 값을 구하면?",
    "choices": [
      "-14",
      "-11",
      "-7",
      "11",
      "14"
    ],
    "answer": "1",
    "solution": "\\frac{x^2+y^2}{xy} = \\frac{(\\sqrt{3}-2)^2 + (\\sqrt{3}+2)^2}{(\\sqrt{3}-2)(\\sqrt{3}+2)} = \\frac{(3-4\\sqrt{3}+4) + (3+4\\sqrt{3}+4)}{3-4} = \\frac{14}{-1} = -14 \\\\ \\therefore 1",
    "level": "중",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 18,
    "category": "다항식의 곱셈",
    "content": "식 $2120 \\times 2124 + 4$는 어떤 자연수의 제곱과 같다고 할 때, 이 자연수를 구하면?",
    "choices": [
      "1022",
      "2012",
      "2102",
      "2122",
      "2202"
    ],
    "answer": "4",
    "solution": "2122 = x 치환 \\implies (x-2)(x+2)+4 = x^2-4+4 = x^2 \\\\ \\therefore 2122",
    "level": "하",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 19,
    "category": "인수분해",
    "content": "$x^2$의 계수가 2인 어떤 이차식을 민준이는 상수항을 잘못 보고 $(x-2)(2x-3)$으로 인수분해 하였고, 민서는 일차항의 계수를 잘못 보고 $(x+3)(2x+1)$로 인수분해 하였다. 처음 이차식을 바르게 인수분해 한 것은?",
    "choices": [
      "$(x-3)(2x-1)",
      "$(x+3)(2x-1)",
      "$(x+3)(2x+1)",
      "$(x-3)(2x+1)",
      "$(x+3)(2x-2)"
    ],
    "answer": "1",
    "solution": "민준: $(x-2)(2x-3) = 2x^2-7x+6$ \\implies 일차항 $-7x$ 채택 \\\\ 민서: $(x+3)(2x+1) = 2x^2+7x+3$ \\implies 상수항 3 채택 \\\\ 처음 식: $2x^2-7x+3 = (2x-1)(x-3)$ \\\\ \\therefore 1",
    "level": "중",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false
  },
  {
    "id": 20,
    "category": "제곱근과 실수",
    "content": "다음 그림과 같이 가로의 길이가 $24cm$, 세로의 길이가 $xcm$인 직사각형 $ABCD$와 넓이가 같은 정사각형이 있다. 직사각형과 정사각형의 각 변의 길이는 모두 자연수일 때, 넓이가 가장 작은 정사각형의 한 변의 길이를 구하면?<div style=\"text-align:center; margin:12px 0;\"><svg width=\"300\" height=\"120\" viewBox=\"0 0 300 120\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"20\" y=\"30\" width=\"120\" height=\"60\" fill=\"none\" stroke=\"#000\" stroke-width=\"1.5\"/><text x=\"80\" y=\"105\" text-anchor=\"middle\" font-size=\"12\">24cm</text><text x=\"10\" y=\"63\" text-anchor=\"middle\" font-size=\"12\">xcm</text><text x=\"80\" y=\"25\" text-anchor=\"middle\" font-size=\"12\">직사각형 ABCD</text><rect x=\"200\" y=\"30\" width=\"60\" height=\"60\" fill=\"none\" stroke=\"#000\" stroke-width=\"1.5\"/><text x=\"230\" y=\"105\" text-anchor=\"middle\" font-size=\"12\">한 변</text><text x=\"230\" y=\"25\" text-anchor=\"middle\" font-size=\"12\">정사각형</text></svg></div>",
    "choices": [
      "12",
      "10",
      "9",
      "8",
      "6"
    ],
    "answer": "1",
    "solution": "정사각형 한 변 = \\sqrt{24x} = \\sqrt{2^3 \\times 3 \\times x} \\\\ 자연수가 되기 위한 최소 x = 2 \\times 3 = 6 \\\\ 한 변의 길이 = \\sqrt{24 \\times 6} = \\sqrt{144} = 12 \\\\ \\therefore 1",
    "level": "중",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["도형"],
    "wide": false
  }
];