window.examTitle = "22_팔마중_1학기_중간_중3_기출";

window.questionBank = [
  {
    "id": 1,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["개념"],
    "wide": false,
    "level": "중",
    "content": "제곱근에 대한 설명으로 옳은 것은?",
    "choices": ["0의 제곱근은 없다.", "제곱근 25는 5이다.", "7은 $\\sqrt{7}$의 양의 제곱근이다.", "$(-3)^2$의 제곱근은 $\\pm \\sqrt{3}$이다.", "-4는 -16의 음의 제곱근이다."],
    "answer": "2",
    "solution": "1. 0의 제곱근은 0이다. \\\\ 2. 제곱근 25는 $\\sqrt{25}=5$ 이다. (참) \\\\ 3. 7은 49의 양의 제곱근이다. \\\\ 4. $(-3)^2=9$ 이므로 제곱근은 $\\pm 3$ 이다. \\\\ 5. 음수의 제곱근은 실수 범위에 없다. \\\\ \\therefore 2"
  },
  {
    "id": 2,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "중",
    "content": "다음 중 계산한 결과가 다른 하나를 고르면?",
    "choices": ["$\\sqrt{\\left(-\\frac{4}{3}\\right)^2}+\\sqrt{\\left(\\frac{5}{3}\\right)^2}$", "$\\sqrt{81}\\div(-\\sqrt{3})^2$", "$\\sqrt{0.09}\\div\\sqrt{\\frac{1}{100}}$", "$\\sqrt{36}-(-\\sqrt{3})^2$", "$-\\sqrt{(-6)^2}\\times\\sqrt{\\left(\\frac{1}{2}\\right)^2}$"],
    "answer": "5",
    "solution": "1. $\\frac{4}{3}+\\frac{5}{3}=3$ \\\\ 2. $9\\div 3=3$ \\\\ 3. $0.3\\div 0.1=3$ \\\\ 4. $6-3=3$ \\\\ 5. $-6\\times \\frac{1}{2}=-3$ \\\\ \\therefore 5"
  },
  {
    "id": 3,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "중",
    "content": "다음 수 중 제곱근을 근호를 사용하지 않고 나타낼 수 있는 것의 개수는?<div class='box'>$1.\\dot{7}$, 2, 4.9, $(-8)^2$, $\\sqrt{\\frac{1}{36}}$, 900</div>",
    "choices": ["1개", "2개", "3개", "4개", "5개"],
    "answer": "3",
    "solution": "$1.\\dot{7}=\\frac{16}{9}$ 이므로 제곱근은 $\\pm\\frac{4}{3}$ 이다. \\\\ 2, 4.9는 제곱근을 근호 없이 나타낼 수 없다. \\\\ $(-8)^2=64$ 이므로 제곱근은 $\\pm 8$ 이다. \\\\ $\\sqrt{\\frac{1}{36}}=\\frac{1}{6}$ 이므로 그 제곱근은 $\\pm\\sqrt{\\frac{1}{6}}$ 이다. \\\\ 900의 제곱근은 $\\pm 30$ 이다. \\\\ 따라서 가능한 것은 $1.\\dot{7}, (-8)^2, 900$의 3개이다. \\\\ \\therefore 3"
  },
  {
    "id": 4,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "상",
    "content": "$\\sqrt{29-x}$가 정수가 되도록 하는 자연수 $x$의 값 중에서 가장 큰 값을 $M$, 가장 작은 값을 $m$이라고 할 때, $M-m$의 값을 구하면?",
    "choices": ["24", "25", "28", "32", "33"],
    "answer": "2",
    "solution": "$29-x$가 0, 1, 4, 9, 16, 25일 때 정수이다. \\\\ 가장 큰 자연수 $x$는 $29-x=0$ 일 때의 $x=29$ 이고, 가장 작은 자연수 $x$는 $29-x=25$ 일 때의 $x=4$ 이다. \\\\ 따라서 $M-m=29-4=25$ \\\\ \\therefore 2"
  },
  {
    "id": 5,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "중",
    "content": "두 실수의 대소 관계가 옳은 것은?",
    "choices": ["$3<\\sqrt{3}+1$", "$\\sqrt{8}-1>2$", "$\\sqrt{3}+3>\\sqrt{5}+3$", "$-\\sqrt{12}+2<2-\\sqrt{13}$", "$\\sqrt{11}-\\sqrt{15}>\\sqrt{11}-4$"],
    "answer": "5",
    "solution": "1. $3<\\sqrt{3}+1$ 은 $2<\\sqrt{3}$ 과 같으므로 거짓 \\\\ 2. $\\sqrt{8}-1>2$ 는 $\\sqrt{8}>3$ 과 같으므로 거짓 \\\\ 3. $\\sqrt{3}>\\sqrt{5}$ 가 아니므로 거짓 \\\\ 4. $-\\sqrt{12}< -\\sqrt{13}$ 는 거짓 \\\\ 5. $-\\sqrt{15}>-4$ 이므로 참 \\\\ \\therefore 5"
  },
  {
    "id": 6,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["도형"],
    "wide": false,
    "level": "상",
    "content": "그림은 수직선 위의 두 점 $A(1)$과 $B(2)$에 대하여 $AB$를 한 변으로 하는 정사각형 $ABCD$를 그린 것이다. $\\overline{AC}=\\overline{AP}=\\overline{AQ}$일 때, 두 점 $P(a)$와 $Q(b)$에 대하여 $\\frac{P(a)}{Q(b)}$의 값을 구하면?",
    "choices": ["$-3+2\\sqrt{2}$", "$3+2\\sqrt{2}$", "$3-2\\sqrt{2}$", "$-3-2\\sqrt{2}$", "$2\\sqrt{2}$"],
    "answer": "1",
    "solution": "$AB=1$ 이므로 대각선의 길이 $AC=\\sqrt{2}$ \\\\ 따라서 $P(a)=1-\\sqrt{2},\\ Q(b)=1+\\sqrt{2}$ \\\\ $\\frac{P(a)}{Q(b)}=\\frac{1-\\sqrt{2}}{1+\\sqrt{2}}=\\frac{(1-\\sqrt{2})^2}{1-2}=\\frac{3-2\\sqrt{2}}{-1}=-3+2\\sqrt{2}$ \\\\ \\therefore 1"
  },
  {
    "id": 7,
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "하",
    "content": "$\\sqrt{12}-\\sqrt{27}+\\frac{6}{\\sqrt{3}}$을 간단히 한 것은?",
    "choices": ["$\\sqrt{3}$", "$2\\sqrt{3}$", "$3\\sqrt{3}$", "$4\\sqrt{3}$", "$5\\sqrt{3}$"],
    "answer": "1",
    "solution": "$\\sqrt{12}-\\sqrt{27}+\\frac{6}{\\sqrt{3}}=2\\sqrt{3}-3\\sqrt{3}+2\\sqrt{3}=\\sqrt{3}$ \\\\ \\therefore 1"
  },
  {
    "id": 8,
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "중",
    "content": "$\\sqrt{\\frac{15}{27}}=a\\sqrt{5},\\ \\frac{\\sqrt{3}}{2}=\\sqrt{b}$일 때, 두 유리수 $a,\\ b$에 대하여 $\\sqrt{ab}$의 값은?",
    "choices": ["$\\frac{1}{6}$", "$\\frac{1}{5}$", "$\\frac{1}{4}$", "$\\frac{1}{3}$", "$\\frac{1}{2}$"],
    "answer": "5",
    "solution": "$\\sqrt{\\frac{15}{27}}=\\sqrt{\\frac{5}{9}}=\\frac{1}{3}\\sqrt{5}$ 이므로 $a=\\frac{1}{3}$ \\\\ $\\frac{\\sqrt{3}}{2}=\\sqrt{\\frac{3}{4}}$ 이므로 $b=\\frac{3}{4}$ \\\\ 따라서 $\\sqrt{ab}=\\sqrt{\\frac{1}{3}\\cdot\\frac{3}{4}}=\\sqrt{\\frac{1}{4}}=\\frac{1}{2}$ \\\\ \\therefore 5"
  },
  {
    "id": 9,
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "중",
    "content": "$\\sqrt{72}-|2\\sqrt{24}|-\\sqrt{2}\\left(2+\\frac{6}{\\sqrt{12}}\\right)=m\\sqrt{2}+n\\sqrt{6}$일 때, 유리수 $m,\\ n$에 대하여 $\\sqrt{m-n}$의 값을 구하면?",
    "choices": ["1", "2", "3", "$\\sqrt{2}$", "$\\sqrt{5}$"],
    "answer": "3",
    "solution": "$\\sqrt{72}=6\\sqrt{2},\\ |2\\sqrt{24}|=4\\sqrt{6},\\ \\sqrt{2}\\left(2+\\frac{6}{\\sqrt{12}}\\right)=2\\sqrt{2}+\\sqrt{6}$ \\\\ 따라서 $6\\sqrt{2}-4\\sqrt{6}-2\\sqrt{2}-\\sqrt{6}=4\\sqrt{2}-5\\sqrt{6}$ \\\\ 그러므로 $m=4,\\ n=-5$ 이고 $\\sqrt{m-n}=\\sqrt{4-(-5)}=\\sqrt{9}=3$ \\\\ \\therefore 3"
  },
  {
    "id": 10,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "중",
    "content": "$\\sqrt{5}$의 소수 부분을 $a$라 할 때, $4-\\sqrt{5}$의 소수 부분을 $a$에 대한 식으로 나타내면?",
    "choices": ["$2-a$", "$1-a$", "$a$", "$a-1$", "$a-2$"],
    "answer": "2",
    "solution": "$\\sqrt{5}=2.236\\cdots$ 이므로 $a=\\sqrt{5}-2$ \\\\ $4-\\sqrt{5}=1.763\\cdots$ 이므로 소수 부분은 $(4-\\sqrt{5})-1=3-\\sqrt{5}$ \\\\ 여기에 $\\sqrt{5}=a+2$ 를 대입하면 $3-(a+2)=1-a$ \\\\ \\therefore 2"
  },
  {
    "id": 11,
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "상",
    "content": "$\\sqrt{2}(3\\sqrt{2}+\\frac{1}{2})-\\frac{a(1-\\sqrt{2})}{2\\sqrt{2}}$가 유리수일 때, 유리수 $a$의 값을 구하면?",
    "choices": ["-2", "-1", "0", "1", "2"],
    "answer": "5",
    "solution": "$\\sqrt{2}(3\\sqrt{2}+\\frac{1}{2})-\\frac{a(1-\\sqrt{2})}{2\\sqrt{2}}=6+\\frac{\\sqrt{2}}{2}-\\frac{a}{2\\sqrt{2}}+\\frac{a}{2}$ \\\\ $=6+\\frac{a}{2}+\\left(\\frac{1}{2}-\\frac{a}{4}\\right)\\sqrt{2}$ \\\\ 유리수가 되려면 $\\frac{1}{2}-\\frac{a}{4}=0$ 이어야 하므로 $a=2$ \\\\ \\therefore 5"
  },
  {
    "id": 12,
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["개념"],
    "wide": false,
    "level": "하",
    "content": "다음 식을 전개한 것이 옳은 것은?",
    "choices": ["$(3x+3y)^2=3x^2+6xy+3y^2$", "$(2a+3b)^2=4a^2-12ab+9b^2$", "$(a-4)(a-13)=a^2-17a+52$", "$(2x+7y)(2x-7y)=16x^2-49y^2$", "$(x+10)(2x-1)=2x^2-19x-10$"],
    "answer": "3",
    "solution": "1. $(3x+3y)^2=9x^2+18xy+9y^2$ \\\\ 2. $(2a+3b)^2=4a^2+12ab+9b^2$ \\\\ 3. $(a-4)(a-13)=a^2-17a+52$ \\\\ 4. $(2x+7y)(2x-7y)=4x^2-49y^2$ \\\\ 5. $(x+10)(2x-1)=2x^2+19x-10$ \\\\ \\therefore 3"
  },
  {
    "id": 13,
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["도형"],
    "wide": false,
    "level": "중",
    "content": "그림에서 설명하는 곱셈 공식으로 옳은 것은?",
    "choices": ["$(a+b)^2=a^2+2ab+b^2$", "$(a+b)(a-b)=a^2-b^2$", "$(a-b)^2=a^2-2ab+b^2$", "$(a+b)(a-b)=a^2+b^2$", "$(x+a)(x+b)=x^2+(a+b)x+ab$"],
    "answer": "3",
    "solution": "그림은 한 변의 길이가 $a$인 정사각형에서 가로와 세로로 각각 $b$만큼 뺀 정사각형의 넓이를 설명한다. \\\\ 따라서 $(a-b)^2=a^2-2ab+b^2$ \\\\ \\therefore 3"
  },
  {
    "id": 14,
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "하",
    "content": "$(2x-5)^2$의 전개식에서 $x^2$의 계수를 $a$, $x$의 계수를 $b$라 할 때, $a-b$의 값은? (4점)",
    "choices": ["12", "16", "20", "24", "28"],
    "answer": "4",
    "solution": "$(2x-5)^2=4x^2-20x+25$ 이므로 $a=4,\\ b=-20$ \\\\ 따라서 $a-b=4-(-20)=24$ \\\\ \\therefore 4"
  },
  {
    "id": 15,
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": ["도형"],
    "wide": false,
    "level": "중",
    "content": "그림과 같이 넓이가 각각 $x^2$, $x$, $1$인 직사각형 6개를 빈틈없이 겹치지 않게 이어 붙여 하나의 직사각형을 만들려고 한다. 이 직사각형의 둘레의 길이는? (4점)",
    "choices": ["$2x+1$", "$3x+2$", "$4x+2$", "$6x+2$", "$6x+4$"],
    "answer": "5",
    "solution": "직사각형 6개의 넓이의 합은 $2x^2+3x+1$ 이다. \\\\ 이를 인수분해하면 $2x^2+3x+1=(2x+1)(x+1)$ \\\\ 따라서 전체 직사각형의 가로, 세로는 각각 $2x+1,\\ x+1$ 이므로 둘레의 길이는 $2\\{(2x+1)+(x+1)\\}=6x+4$ \\\\ \\therefore 5"
  },
  {
    "id": 16,
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "중",
    "content": "두 다항식을 각각 인수분해할 때, 공통으로 들어 있는 인수는? (4점) <div class='box'>$x^2-5x-14$, $3x^2+x-10$</div>",
    "choices": ["$x-7$", "$x+2$", "$3x-5$", "$x+7$", "$x-2$"],
    "answer": "2",
    "solution": "$x^2-5x-14=(x-7)(x+2)$ \\\\ $3x^2+x-10=(3x-5)(x+2)$ \\\\ 공통인 인수는 $x+2$ \\\\ \\therefore 2"
  },
  {
    "id": 17,
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "하",
    "content": "다항식 $3a^2-12ab+12b^2$의 인수인 것은? (4점)",
    "choices": ["$a-2b$", "$a+2b$", "$a-6b$", "$3a-2b$", "$3a+2b$"],
    "answer": "1",
    "solution": "$3a^2-12ab+12b^2=3(a^2-4ab+4b^2)=3(a-2b)^2$ \\\\ 따라서 인수는 $a-2b$ 이다. \\\\ \\therefore 1"
  },
  {
    "id": 18,
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "상",
    "content": "$x=\\frac{1}{\\sqrt{10}+3},\\ y=\\frac{1}{\\sqrt{10}-3}$일 때, $\\frac{y}{x}+\\frac{x}{y}$의 값은? (4점)",
    "choices": ["42", "40", "38", "36", "34"],
    "answer": "3",
    "solution": "$x=\\frac{1}{\\sqrt{10}+3}=\\sqrt{10}-3,\\ y=\\frac{1}{\\sqrt{10}-3}=\\sqrt{10}+3$ \\\\ 따라서 $xy=1,\\ x+y=2\\sqrt{10}$ \\\\ $\\frac{y}{x}+\\frac{x}{y}=\\frac{x^2+y^2}{xy}=x^2+y^2=(x+y)^2-2xy=40-2=38$ \\\\ \\therefore 3"
  },
  {
    "id": 19,
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "중",
    "content": "다음 식이 $x^2-12x+a$, $4x^2+bxy+9y^2$ 완전제곱식이 되도록 하는 상수 $a, b$에 대하여 $a+b$의 값은? (단, $b<0$) (4점)",
    "choices": ["12", "18", "24", "36", "48"],
    "answer": "3",
    "solution": "$x^2-12x+a=(x-6)^2$ 이므로 $a=36$ \\\\ $4x^2+bxy+9y^2=(2x-3y)^2$ 이므로 $b=-12$ \\\\ 따라서 $a+b=36-12=24$ \\\\ \\therefore 3"
  },
  {
    "id": 20,
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "상",
    "content": "$x$에 대한 이차식 $x^2+kx-6$이 $(x+a)(x+b)$로 인수분해될 때, 수 $k$가 될 수 있는 가장 큰 값을 $M$, 가장 작은 값을 $m$이라고 할 때, $M-m$을 구하면? (단, $a, b$는 정수) (4점)",
    "choices": ["0", "4", "6", "10", "12"],
    "answer": "4",
    "solution": "$ab=-6,\\ a+b=k$ 이므로 가능한 정수쌍은 $(1,-6),(2,-3),(-1,6),(-2,3)$ 이다. \\\\ 따라서 $k$의 최댓값은 $5$, 최솟값은 $-5$ 이므로 $M-m=5-(-5)=10$ \\\\ \\therefore 4"
  },
  {
    "id": 21,
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "level": "상",
    "content": "자연수 $a$에 대하여 $-a^2+10a+24$가 소수가 될 때, 이 소수는? (4점)",
    "choices": ["5", "7", "11", "13", "17"],
    "answer": "4",
    "solution": "$-a^2+10a+24=49-(a-5)^2=(12-a)(a+2)$ \\\\ 소수가 되려면 한 인수가 1이어야 하므로 $12-a=1$ 이어야 한다. \\\\ 따라서 $a=11$ 이고, 이때 값은 $-11^2+10\\cdot 11+24=13$ 이다. \\\\ \\therefore 4"
  },
  {
    "id": 22,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["서술형", "도형"],
    "wide": false,
    "level": "중",
    "content": "[서술형 1] 그림과 같이 넓이의 비가 $9:4:1$인 세 정사각형 $A, B, C$를 겹치지 않게 이어붙인 도형의 넓이가 $84cm^2$일 때, 다음 물음에 답하시오. (8점)\\n(1) 세 정사각형 $A, B, C$의 넓이와 한 변의 길이를 각각 구하시오. (6점)\\n(2) 이 도형의 전체 둘레의 길이를 구하시오. (2점)",
    "choices": [],
    "answer": "(1) A: 54, 3\\sqrt{6} / B: 24, 2\\sqrt{6} / C: 6, \\sqrt{6} (2) 18\\sqrt{6}",
    "solution": "(1) 넓이의 비가 $9:4:1$ 이므로 각각의 넓이를 $9k,4k,k$ 라고 하면 $9k+4k+k=84$ \\\\ $14k=84 \\implies k=6$ \\\\ 따라서 넓이는 $A=54,\\ B=24,\\ C=6$ 이고 한 변의 길이는 각각 $3\\sqrt{6},\\ 2\\sqrt{6},\\ \\sqrt{6}$ 이다. \\\\ (2) 아래변의 길이는 $3\\sqrt{6}+2\\sqrt{6}+\\sqrt{6}=6\\sqrt{6}$ \\\\ 위변의 길이도 $6\\sqrt{6}$ \\\\ 세로 부분의 길이의 합은 $3\\sqrt{6}+(3\\sqrt{6}-2\\sqrt{6})+(2\\sqrt{6}-\\sqrt{6})+\\sqrt{6}=6\\sqrt{6}$ \\\\ 따라서 전체 둘레의 길이는 $6\\sqrt{6}+6\\sqrt{6}+6\\sqrt{6}=18\\sqrt{6}$ \\\\ \\therefore $18\\sqrt{6}$"
  },
  {
    "id": 23,
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["서술형"],
    "wide": false,
    "level": "중",
    "content": "[서술형 2] 자연수 $x$에 대하여 $\\sqrt{x}$보다 작은 자연수의 개수를 $f(x)$라 할 때, $f(1)+f(2)+f(3)+\\cdots+f(11)$의 값을 구하시오. (2점)",
    "choices": [],
    "answer": "19",
    "solution": "$f(1)=0$ \\\\ $f(2)=1,\\ f(3)=1,\\ f(4)=1$ \\\\ $f(5)=2,\\ f(6)=2,\\ f(7)=2,\\ f(8)=2,\\ f(9)=2$ \\\\ $f(10)=3,\\ f(11)=3$ \\\\ 따라서 합은 $0+1+1+1+2+2+2+2+2+3+3=19$ \\\\ \\therefore 19"
  },
  {
    "id": 24,
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["서술형"],
    "wide": false,
    "level": "중",
    "content": "[서술형 3] $-\\frac{1}{5}<x<3$일 때, $\\sqrt{9-6x+x^2}-\\sqrt{25x^2+10x+1}$을 간단히 하시오. (4점)",
    "choices": [],
    "answer": "2-6x",
    "solution": "$\\sqrt{9-6x+x^2}-\\sqrt{25x^2+10x+1}=\\sqrt{(3-x)^2}-\\sqrt{(5x+1)^2}=|3-x|-|5x+1|$ \\\\ $-\\frac{1}{5}<x<3$ 이므로 $3-x>0,\\ 5x+1>0$ \\\\ 따라서 $|3-x|=3-x,\\ |5x+1|=5x+1$ 이다. \\\\ 그러므로 $(3-x)-(5x+1)=2-6x$ \\\\ \\therefore 2-6x"
  },
  {
    "id": 25,
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": ["서술형"],
    "wide": false,
    "level": "중",
    "content": "[서술형 4] 반지름의 길이가 각각 $52.52cm, 47.48cm$인 원 모양의 피자를 다음 그림과 같이 8등분 하였다. 큰 피자 한 조각의 넓이는 작은 피자 한 조각의 넓이보다 얼마만큼 더 큰지 인수분해를 이용하여 계산하시오. (단, 두께는 일정하다.) (6점)",
    "choices": [],
    "answer": "63\\pi cm^2",
    "solution": "큰 피자 한 조각과 작은 피자 한 조각의 넓이 차는 $\\frac{1}{8}\\pi(52.52^2-47.48^2)$ 이다. \\\\ 인수분해 공식을 이용하면 $\\frac{1}{8}\\pi(52.52+47.48)(52.52-47.48)$ \\\\ $=\\frac{1}{8}\\pi(100)(5.04)=\\frac{504\\pi}{8}=63\\pi$ \\\\ \\therefore $63\\pi cm^2$"
  }
];