window.examTitle = "23_왕운중_1학기_중간_중3_유사2";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 계산이 옳지 않은 것은?",
    choices: [
      "$\\sqrt{45}=3\\sqrt{5}$",
      "$\\sqrt{72}=6\\sqrt{2}$",
      "$5\\sqrt{3}=\\sqrt{75}$",
      "$-\\sqrt{48}=-4\\sqrt{3}$",
      "$\\sqrt{28}=4\\sqrt{7}$"
    ],
    answer: "⑤",
    solution: "[키포인트] 제곱근의 성질을 이용하여 근호 안의 수를 가장 작은 자연수로 변환한다.\\n조건 정리: 각 보기에 주어진 무리수를 $a\\sqrt{b}$ 형태로 변환하여 비교한다.\\n풀이 방향: 근호 안의 수를 소인수분해하여 제곱수를 밖으로 꺼낸다.\\n정석 풀이: ① $\\sqrt{45}=\\sqrt{3^{2}\\times 5}=3\\sqrt{5}$ (옳음)\\n② $\\sqrt{72}=\\sqrt{6^{2}\\times 2}=6\\sqrt{2}$ (옳음)\\n③ $5\\sqrt{3}=\\sqrt{5^{2}\\times 3}=\\sqrt{75}$ (옳음)\\n④ $-\\sqrt{48}=-\\sqrt{4^{2}\\times 3}=-4\\sqrt{3}$ (옳음)\\n⑤ $\\sqrt{28}=\\sqrt{2^{2}\\times 7}=2\\sqrt{7}$이므로 $4\\sqrt{7}$이 아니다. (옳지 않음)\\n따라서 정답은 ⑤이다."
  },
  {
    id: 2,
    level: "중",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다항식 $(2x-3)(x+5)$를 전개하였을 때, $x^2$의 계수를 $A$, $x$의 계수를 $B$라 하자. $A-B$의 값은?",
    choices: ["-5", "-2", "3", "5", "9"],
    answer: "①",
    solution: "[키포인트] 다항식의 곱셈을 전개하여 각 항의 계수를 구한다.\\n조건 정리: $(2x-3)(x+5)$를 전개하여 $x^{2}$의 계수 $A$와 $x$의 계수 $B$를 구한다.\\n풀이 방향: 분배법칙을 이용하여 식을 전개한 후 동류항끼리 묶어 정리한다.\\n정석 풀이: $(2x-3)(x+5) = 2x^{2} + 10x - 3x - 15 = 2x^{2} + 7x - 15$이다.\\n따라서 $x^{2}$의 계수는 $A=2$이고, $x$의 계수는 $B=7$이다.\\n구하는 값은 $A-B = 2 - 7 = -5$이다.\\n따라서 정답은 ①이다."
  },
  {
    id: 3,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 수 중에서 무리수의 개수는?<br>$\\sqrt{25},\\quad \\sqrt{0.4},\\quad \\pi,\\quad 3-\\sqrt{4},\\quad 0.\\dot{5},\\quad \\sqrt{\\frac{9}{16}}$",
    choices: ["1개", "2개", "3개", "4개", "5개"],
    answer: "②",
    solution: "[키포인트] 무리수는 순환하지 않는 무한소수이며, 근호가 벗겨지지 않는 수와 $\\pi$ 등이 포함된다.\\n조건 정리: 주어진 수들을 간단히 정리하여 무리수인지 유리수인지 판별한다.\\n풀이 방향: 근호 안이 어떤 수의 제곱이면 유리수이고, 그렇지 않으면 무리수이다.\\n정석 풀이: $\\sqrt{25}=5$ (유리수)\\n$\\sqrt{0.4}$는 $\\sqrt{\\frac{4}{10}}=\\frac{2}{\\sqrt{10}}$이므로 근호가 완전히 벗겨지지 않아 무리수이다.\\n$\\pi$는 대표적인 무리수이다.\\n$3-\\sqrt{4}=3-2=1$ (유리수)\\n$0.\\dot{5}=\\frac{5}{9}$ (유리수)\\n$\\sqrt{\\frac{9}{16}}=\\frac{3}{4}$ (유리수)\\n따라서 무리수는 $\\sqrt{0.4}, \\pi$의 2개이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 4,
    level: "중",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 이차식 $x^2-10x+a$와 $4x^2+bx+9$가 각각 완전제곱식이 되도록 하는 양수 $a, b$에 대하여 $a+b$의 값은?",
    choices: ["33", "35", "37", "39", "41"],
    answer: "③",
    solution: "[키포인트] 이차식이 완전제곱식이 되려면 식을 정리했을 때 $(x\\pm p)^{2}$ 꼴이 되어야 한다.\\n조건 정리: 두 이차식 $x^{2}-10x+a$와 $4x^{2}+bx+9$가 완전제곱식이며 $a, b$는 양수이다.\\n풀이 방향: 완전제곱식 $(x \\pm p)^{2}$, $(mx \\pm n)^{2}$의 전개 형태와 계수를 비교한다.\\n정석 풀이: $x^{2}-10x+a$가 완전제곱식이 되려면 $a = (\\frac{-10}{2})^{2} = (-5)^{2} = 25$이다.\\n$4x^{2}+bx+9 = (2x)^{2}+bx+3^{2}$이므로 이는 $(2x \\pm 3)^{2}$ 형태이다.\\n이를 전개하면 $4x^{2} \\pm 12x + 9$가 되며, $b \\gt 0$이므로 $b = 12$이다.\\n따라서 $a+b = 25 + 12 = 37$이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 5,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["표"],
    wide: false,
    content: "주어진 제곱근표를 이용하여 $\\sqrt{3.22}+\\sqrt{33.3}$의 값을 구하면?<table class='question-table'><tr><th>수</th><th>0</th><th>1</th><th>2</th><th>3</th></tr><tr><td>3.2</td><td>1.789</td><td>1.792</td><td>1.794</td><td>1.797</td></tr><tr><td>3.3</td><td>1.817</td><td>1.819</td><td>1.822</td><td>1.825</td></tr><tr><td>33</td><td>5.745</td><td>5.753</td><td>5.762</td><td>5.771</td></tr></table>",
    choices: ["7.556", "7.565", "7.584", "7.601", "7.612"],
    answer: "②",
    solution: "[키포인트] 제곱근표에서 근호 안의 수에 대응하는 값을 찾아 더한다.\\n조건 정리: $\\sqrt{3.22}$와 $\\sqrt{33.3}$의 값을 각각 찾는다.\\n풀이 방향: 수의 앞 두 자리를 왼쪽 열에서, 셋째 자리를 위쪽 행에서 찾아 교차하는 값을 읽는다.\\n정석 풀이: 표에서 $3.2$의 가로줄과 $2$의 세로줄이 만나는 값은 $1.794$이므로 $\\sqrt{3.22} = 1.794$이다.\\n표에서 $33$의 가로줄과 $3$의 세로줄이 만나는 값은 $5.771$이므로 $\\sqrt{33.3} = 5.771$이다.\\n두 값의 합은 $1.794 + 5.771 = 7.565$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 6,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["표"],
    wide: false,
    content: "주어진 제곱근표를 이용하여 $\\sqrt{323}$의 값을 구하면?<table class='question-table'><tr><th>수</th><th>3</th><th>4</th><th>5</th></tr><tr><td>3.2</td><td>1.797</td><td>1.800</td><td>1.803</td></tr><tr><td>33</td><td>5.771</td><td>5.779</td><td>5.788</td></tr></table>",
    choices: ["17.97", "18.00", "57.71", "57.79", "179.7"],
    answer: "①",
    solution: "[키포인트] 주어진 표의 범위를 벗어나는 수는 근호 밖으로 $10$이나 $\\frac{1}{10}$을 꺼내어 변형한 후 구한다.\\n조건 정리: 표에 $\\sqrt{323}$이 없으므로 값을 변형해야 한다.\\n풀이 방향: $\\sqrt{323} = \\sqrt{3.23 \\times 100}$으로 변형한 후 표를 이용한다.\\n정석 풀이: 표에서 $3.2$의 가로줄과 $3$의 세로줄이 만나는 값은 $1.797$이므로 $\\sqrt{3.23} = 1.797$이다.\\n$\\sqrt{323} = \\sqrt{3.23 \\times 100} = \\sqrt{3.23} \\times 10 = 1.797 \\times 10 = 17.97$이다.\\n따라서 정답은 ①이다."
  },
  {
    id: 7,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 두 실수의 대소 관계가 옳은 것은?",
    choices: [
      "$3\\sqrt{3}>4\\sqrt{2}$",
      "$\\sqrt{15}>4$",
      "$2+\\sqrt{5}<\\sqrt{5}+\\sqrt{3}$",
      "$5-\\sqrt{2}<5-\\sqrt{3}$",
      "$\\sqrt{10}-1>2$"
    ],
    answer: "⑤",
    solution: "[키포인트] 무리수의 대소를 비교할 때는 근호 안의 수로 통일하거나 식을 이항하여 정리한 뒤 비교한다.\\n조건 정리: 5개의 보기 중 실수의 대소 관계가 옳은 것을 찾는다.\\n풀이 방향: 무리수를 제곱근 형태로 통일하거나 이항하여 크기를 판별한다.\\n정석 풀이: ① $3\\sqrt{3}=\\sqrt{27}$, $4\\sqrt{2}=\\sqrt{32}$이므로 $3\\sqrt{3} \\lt 4\\sqrt{2}$이다. (틀림)\\n② $4=\\sqrt{16}$이므로 $\\sqrt{15} \\lt 4$이다. (틀림)\\n③ 양변에서 $\\sqrt{5}$를 빼면 $2 \\lt \\sqrt{3}$이다. $2=\\sqrt{4}$이므로 성립하지 않는다. (틀림)\\n④ $\\sqrt{2} \\lt \\sqrt{3}$이므로 $-\\sqrt{2} \\gt -\\sqrt{3}$이다. 양변에 $5$를 더하면 $5-\\sqrt{2} \\gt 5-\\sqrt{3}$이다. (틀림)\\n⑤ $\\sqrt{10}-1 \\gt 2$에서 $-1$을 우변으로 이항하면 $\\sqrt{10} \\gt 3$이다. $3=\\sqrt{9}$이므로 $\\sqrt{10} \\gt \\sqrt{9}$는 참이다. (옳음)\\n따라서 정답은 ⑤이다."
  },
  {
    id: 8,
    level: "중",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$55^2-45^2$을 인수분해 공식을 이용하여 계산한 값은?",
    choices: ["500", "1000", "1500", "2000", "2500"],
    answer: "②",
    solution: "[키포인트] 제곱의 차는 합차 공식을 이용하면 쉽게 계산할 수 있다.\\n조건 정리: $55^{2}-45^{2}$을 인수분해 공식 $a^{2}-b^{2}=(a+b)(a-b)$를 이용하여 전개한다.\\n풀이 방향: $a=55, b=45$를 식에 대입하여 계산한다.\\n정석 풀이: $55^{2}-45^{2} = (55+45)(55-45)$로 인수분해된다.\\n두 괄호를 각각 계산하면 $100 \\times 10 = 1000$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 9,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "수직선 위의 점 $A(3)$에서 출발하여 양의 방향으로 밑변의 길이가 $1$, 높이가 $2$인 직각삼각형의 빗변의 길이만큼 이동한 점을 $P$라 할 때, 점 $P$에 대응하는 수는?",
    choices: ["$3+\\sqrt{3}$", "$3+\\sqrt{5}$", "$4+\\sqrt{2}$", "$4+\\sqrt{3}$", "$5$"],
    answer: "②",
    solution: "[키포인트] 피타고라스 정리를 이용하여 직각삼각형의 빗변 길이를 구한 뒤 수직선에서 좌표를 이동한다.\\n조건 정리: 이동 거리는 밑변 $1$, 높이 $2$인 직각삼각형의 빗변 길이이다.\\n풀이 방향: 빗변 길이를 구한 뒤, 시작점 좌표 $3$에서 양의 방향으로 더해준다.\\n정석 풀이: 밑변이 $1$, 높이가 $2$인 직각삼각형의 빗변의 길이는 피타고라스 정리에 의해 $\\sqrt{1^{2}+2^{2}} = \\sqrt{5}$이다.\\n수직선 위의 좌표 $3$에서 양의 방향으로 $\\sqrt{5}$만큼 이동했으므로 점 $P$에 대응하는 수는 $3+\\sqrt{5}$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 10,
    level: "중",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다항식 $2x^2+7x+3$을 인수분해하였을 때, 일차식인 두 인수의 합을 구하면?",
    choices: ["$3x+2$", "$3x+4$", "$4x+2$", "$4x+4$", "$5x+2$"],
    answer: "②",
    solution: "[키포인트] $x^{2}$의 계수가 $1$이 아닌 이차식은 계수들의 곱의 조합을 찾아 십자형으로 인수분해한다.\\n조건 정리: $2x^{2}+7x+3$을 인수분해한 후 얻은 두 일차식을 더한다.\\n풀이 방향: 곱해서 $2x^{2}$이 되는 두 항과 곱해서 $3$이 되는 상수를 교차하여 합이 $7x$가 되도록 짝지어준다.\\n정석 풀이: $2x^{2}+7x+3 = (2x+1)(x+3)$으로 인수분해된다.\\n이때 두 인수는 $2x+1$과 $x+3$이다.\\n두 인수의 합을 구하면 $(2x+1) + (x+3) = 3x+4$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 11,
    level: "중",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 완전제곱식인 것은?",
    choices: [
      "$x^2-4x-4$",
      "$a^2+6ab+9b$",
      "$x^2-x+\\frac{1}{4}$",
      "$4x^2-12x+16$",
      "$x^2+10x+20$"
    ],
    answer: "③",
    solution: "[키포인트] 완전제곱식은 $(ax \\pm b)^{2}=a^{2}x^{2} \\pm 2abx+b^{2}$의 형태를 띤다.\\n조건 정리: 각 보기를 확인하여 상수항과 일차항의 관계가 완전제곱식의 조건에 맞는지 확인한다.\\n풀이 방향: $x^{2}$의 계수가 $1$일 때, (일차항 계수의 절반)$^{2}$이 상수항과 일치하는지 확인한다.\\n정석 풀이: ① $(-4/2)^{2} = 4 \\neq -4$이므로 완전제곱식이 아니다.\\n② $(a+3b)^{2} = a^{2}+6ab+9b^{2}$이어야 하므로 다르다.\\n③ $(-1/2)^{2} = 1/4$이므로 $(x-1/2)^{2}$인 완전제곱식이다.\\n④ $4x^{2}-12x+16 = 4(x^{2}-3x+4)$에서 $(-3/2)^{2} \\neq 4$이다.\\n⑤ $(10/2)^{2} = 25 \\neq 20$이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 12,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$2\\sqrt{15}\\div 3\\sqrt{5}\\times 6\\sqrt{3}$을 간단히 하면?",
    choices: ["$10$", "$12$", "$15$", "$4\\sqrt{3}$", "$6\\sqrt{5}$"],
    answer: "②",
    solution: "[키포인트] 근호가 있는 수의 곱셈과 나눗셈은 근호 안의 수끼리, 근호 밖의 수끼리 계산한다.\\n조건 정리: 식 $2\\sqrt{15}\\div 3\\sqrt{5}\\times 6\\sqrt{3}$을 순서대로 계산한다.\\n풀이 방향: 나눗셈을 분수로 바꾸고 약분을 진행한 뒤 뒤의 항을 곱한다.\\n정석 풀이: 먼저 나눗셈을 분수 꼴로 나타내면 $\\frac{2\\sqrt{15}}{3\\sqrt{5}} \\times 6\\sqrt{3}$이다.\\n앞부분을 계산하면 $\\frac{\\sqrt{15}}{\\sqrt{5}} = \\sqrt{3}$이므로 $\\frac{2}{3}\\sqrt{3}$이 된다.\\n이를 뒤의 항과 곱하면 $\\frac{2}{3}\\sqrt{3} \\times 6\\sqrt{3} = (\\frac{2}{3} \\times 6) \\times (\\sqrt{3} \\times \\sqrt{3}) = 4 \\times 3 = 12$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 13,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 옳지 않은 것은?",
    choices: [
      "순환소수는 모두 유리수이다.",
      "유리수이면서 무리수인 수는 없다.",
      "근호를 사용하여 나타낸 수는 모두 무리수이다.",
      "무한소수 중에는 무리수인 것도 있다.",
      "실수는 유리수와 무리수로 이루어져 있다."
    ],
    answer: "③",
    solution: "[키포인트] 유리수와 무리수의 정의를 정확히 이해하고 실수의 체계를 분류한다.\\n조건 정리: 유리수와 무리수에 대한 성질 중 틀린 설명을 찾는다.\\n풀이 방향: 무리수는 순환하지 않는 무한소수이며, 근호 안이 어떤 유리수의 제곱이 될 때는 유리수임을 이용한다.\\n정석 풀이: ① 순환소수는 분수 형태로 나타낼 수 있으므로 유리수이다. (옳음)\\n② 실수 체계에서 유리수와 무리수의 교집합은 존재하지 않는다. (옳음)\\n③ $\\sqrt{4}$와 같이 근호를 사용하였더라도 그 값이 $2$이므로 유리수인 경우가 있다. 따라서 근호를 썼다고 모두 무리수는 아니다. (옳지 않음)\\n④ 무한소수 중 순환하지 않는 무한소수가 바로 무리수이다. (옳음)\\n⑤ 실수는 유리수와 무리수의 합집합이다. (옳음)\\n따라서 정답은 ③이다."
  },
  {
    id: 14,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x=\\frac{1}{\\sqrt{3}-\\sqrt{2}},\\ y=\\frac{1}{\\sqrt{3}+\\sqrt{2}}$ 일 때, $x^2-y^2$의 값은?",
    choices: ["$2\\sqrt{2}$", "$2\\sqrt{3}$", "$2\\sqrt{6}$", "$4\\sqrt{3}$", "$4\\sqrt{6}$"],
    answer: "⑤",
    solution: "[키포인트] 분모를 유리화한 후 합차 공식을 이용해 식의 값을 간단하게 구한다.\\n조건 정리: $x, y$를 각각 유리화한 다음 구하고자 하는 식 $x^{2}-y^{2}$에 대입한다.\\n풀이 방향: $x^{2}-y^{2}=(x+y)(x-y)$로 인수분해하여 대입하면 계산이 훨씬 빠르다.\\n정석 풀이: 각 분모를 유리화하면,\\n$x = \\frac{\\sqrt{3}+\\sqrt{2}}{(\\sqrt{3}-\\sqrt{2})(\\sqrt{3}+\\sqrt{2})} = \\sqrt{3}+\\sqrt{2}$이다.\\n$y = \\frac{\\sqrt{3}-\\sqrt{2}}{(\\sqrt{3}+\\sqrt{2})(\\sqrt{3}-\\sqrt{2})} = \\sqrt{3}-\\sqrt{2}$이다.\\n두 수의 합 $x+y = (\\sqrt{3}+\\sqrt{2}) + (\\sqrt{3}-\\sqrt{2}) = 2\\sqrt{3}$이다.\\n두 수의 차 $x-y = (\\sqrt{3}+\\sqrt{2}) - (\\sqrt{3}-\\sqrt{2}) = 2\\sqrt{2}$이다.\\n따라서 $x^{2}-y^{2} = (x+y)(x-y) = 2\\sqrt{3} \\times 2\\sqrt{2} = 4\\sqrt{6}$이다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 15,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어떤 자동차의 제동거리를 $d\\text{m}$라 할 때, 제동이 걸릴 때의 속력은 $v=\\sqrt{100d}\\text{km/h}$라고 한다. 제동거리가 $36\\text{m}$일 때, 제동이 걸릴 때의 속력은?",
    choices: ["$50\\text{km/h}$", "$55\\text{km/h}$", "$60\\text{km/h}$", "$65\\text{km/h}$", "$70\\text{km/h}$"],
    answer: "③",
    solution: "[키포인트] 주어진 관계식에 값을 대입하여 근호를 풀어낸다.\\n조건 정리: 제동거리 $d=36$일 때 식을 만족하는 $v$를 계산한다.\\n풀이 방향: $v=\\sqrt{100d}$에 $d=36$을 대입하고 그 수가 어떤 수의 제곱인지 확인한다.\\n정석 풀이: 식에 $d=36$을 대입하면 $v = \\sqrt{100 \\times 36} = \\sqrt{3600}$이다.\\n$3600$은 $60^{2}$이므로 근호를 풀면 $v = 60$이다.\\n따라서 제동이 걸릴 때의 속력은 $60\\text{km/h}$이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 16,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 식을 계산하면?<br>$\\sqrt{\\frac{3}{2}}\\times \\sqrt{\\frac{4}{3}}\\times \\sqrt{\\frac{5}{4}}\\times \\cdots \\times \\sqrt{\\frac{50}{49}}$",
    choices: ["$3$", "$4$", "$5$", "$6$", "$7$"],
    answer: "③",
    solution: "[키포인트] 여러 무리수의 곱셈은 하나의 큰 근호 안으로 합쳐서 연쇄적으로 약분한다.\\n조건 정리: 분모와 분자의 숫자가 규칙적으로 커지는 분수들의 곱을 계산한다.\\n풀이 방향: 근호를 하나로 씌워 연속적으로 지워지는 규칙을 관찰한다.\\n정석 풀이: 주어진 식을 하나의 근호로 합치면 $\\sqrt{\\frac{3}{2} \\times \\frac{4}{3} \\times \\frac{5}{4} \\times \\dots \\times \\frac{50}{49}}$이다.\\n이웃한 분수의 분모와 분자가 차례대로 약분되어 지워진다.\\n남는 것은 처음 분수의 분모 $2$와 마지막 분수의 분자 $50$이다.\\n따라서 식은 $\\sqrt{\\frac{50}{2}} = \\sqrt{25} = 5$가 된다.\\n따라서 정답은 ③이다."
  },
  {
    id: 17,
    level: "중",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "방정식 $2\\sqrt{x-3}=\\sqrt{20}$과 $\\frac{\\sqrt{y+2}}{\\sqrt{2}}=3$을 동시에 만족시키는 자연수 $x, y$에 대하여 $x+y$의 값은?",
    choices: ["20", "22", "24", "26", "28"],
    answer: "③",
    solution: "[키포인트] 무리방정식은 양변을 제곱하여 근호를 제거한 후 해를 찾는다.\\n조건 정리: 각각의 방정식에서 양변을 제곱하여 $x$와 $y$의 값을 구한다.\\n풀이 방향: 제곱할 때 식 밖의 계수도 함께 제곱됨을 주의하여 식을 전개한다.\\n정석 풀이: 첫 번째 식 $2\\sqrt{x-3}=\\sqrt{20}$의 양변을 제곱하면 $4(x-3) = 20$이다.\\n양변을 $4$로 나누면 $x-3 = 5$이므로 $x = 8$이다.\\n두 번째 식 $\\frac{\\sqrt{y+2}}{\\sqrt{2}}=3$의 양변을 제곱하면 $\\frac{y+2}{2} = 9$이다.\\n$y+2 = 18$이므로 $y = 16$이다.\\n따라서 구하는 값은 $x+y = 8 + 16 = 24$이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 18,
    level: "상",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차식 $x^2+kx-12$가 $(x+a)(x+b)$로 인수분해될 때, 양수 $k$의 값들의 합은? (단, $a, b$는 정수이다.)",
    choices: ["11", "14", "16", "18", "20"],
    answer: "③",
    solution: "[키포인트] 곱이 음수인 두 정수의 합을 통해 이차식의 일차항의 계수를 구한다.\\n조건 정리: $x^{2}+kx-12=(x+a)(x+b)$에서 $ab=-12$, $a+b=k$이며 $k \\gt 0$이다.\\n풀이 방향: 곱해서 $-12$가 되는 두 정수쌍을 찾고, 그 합인 $k$가 양수인 경우를 추려 모두 더한다.\\n정석 풀이: 곱해서 $-12$가 되는 두 정수쌍 $(a, b)$는 $(-1, 12), (-2, 6), (-3, 4), (-4, 3), (-6, 2), (-12, 1)$이다.\\n이때 두 수의 합 $k=a+b$를 구하면 각각 $11, 4, 1, -1, -4, -11$이다.\\n$k$가 양수인 경우는 $11, 4, 1$이다.\\n따라서 가능한 양수 $k$의 값들의 합은 $11+4+1=16$이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 19,
    level: "상",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "자연수 $n$에 대하여 다항식 $n^2+2n-35$의 값이 소수가 되도록 하는 자연수 $n$의 값과 그 소수를 차례대로 바르게 나열한 것은?",
    choices: ["$5, 11$", "$6, 13$", "$7, 17$", "$8, 19$", "$9, 23$"],
    answer: "②",
    solution: "[키포인트] 어떤 수가 소수이려면 두 정수의 곱으로 나타냈을 때 작은 인수가 반드시 $1$이어야 한다.\\n조건 정리: $n^{2}+2n-35$를 인수분해하고, 식이 소수가 되는 $n$의 조건을 구한다.\\n풀이 방향: 식을 분해하여 얻은 인수에 대해 (작은 인수) $= 1$ 방정식을 풀어 $n$을 찾고 값을 확인한다.\\n정석 풀이: $n^{2}+2n-35$를 인수분해하면 $(n+7)(n-5)$이다.\\n이 값이 소수이려면 두 인수 중 더 작은 쪽이 $1$이 되어야 한다.\\n$n \\gt 0$이므로 $n+7 \\gt n-5$이며, 따라서 $n-5 = 1$이어야 한다.\\n$n-5 = 1$에서 $n = 6$이다.\\n$n=6$을 식에 대입하면 식의 값은 $(6+7) \\times 1 = 13 \\times 1 = 13$이다.\\n이때 $13$은 소수이므로 조건을 만족한다.\\n따라서 자연수 $n=6$, 소수는 $13$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 20,
    level: "상",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x^2+ax+15$가 $(x+b)(x+c)$로 인수분해될 때, 양의 정수 $a$가 가질 수 있는 최솟값은? (단, $b, c$는 정수이다.)",
    choices: ["6", "8", "10", "14", "16"],
    answer: "②",
    solution: "[키포인트] 상수항이 양수인 이차식의 인수분해에서 일차항 계수는 상수항을 이루는 두 인수의 합과 같다.\\n조건 정리: $x^{2}+ax+15=(x+b)(x+c)$에서 $bc=15$, $b+c=a$이다.\\n풀이 방향: $bc=15$를 만족하는 정수쌍을 구하고 그 합인 $a$ 중 양수이면서 가장 작은 값을 선택한다.\\n정석 풀이: $b, c$는 정수이므로 $bc=15$를 만족하는 정수쌍 $(b, c)$는 $(1, 15), (3, 5), (-1, -15), (-3, -5)$이다.\\n각 경우에 대해 합 $a = b+c$를 구하면 $16, 8, -16, -8$이다.\\n$a$는 양의 정수이므로 가능한 값은 $8, 16$이다.\\n따라서 $a$의 최솟값은 $8$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 21,
    level: "상",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "서답형",
    layoutTag: "grid",
    tags: ["서답형"],
    wide: false,
    content: "$\\sqrt{10}$의 정수부분을 $x$, 소수부분을 $y$라 할 때, $\\frac{x}{y}$의 값을 구하시오.",
    choices: [],
    answer: "$3\\sqrt{10}+9$",
    solution: "[키포인트] 무리수의 범위를 통해 정수부분을 구하고 (무리수 $-$ 정수부분)으로 소수부분을 구한다.\\n조건 정리: $3 \\lt \\sqrt{10} \\lt 4$임을 이용하여 $x$와 $y$를 찾는다.\\n풀이 방향: $x, y$를 분수 $\\frac{x}{y}$에 대입한 후 분모를 유리화한다.\\n정석 풀이: $3^{2}=9$이고 $4^{2}=16$이므로 $\\sqrt{9} \\lt \\sqrt{10} \\lt \\sqrt{16}$, 즉 $3 \\lt \\sqrt{10} \\lt 4$이다.\\n따라서 $\\sqrt{10}$의 정수부분 $x=3$이고, 소수부분 $y=\\sqrt{10}-3$이다.\\n$\\frac{x}{y} = \\frac{3}{\\sqrt{10}-3}$이며, 분모를 유리화하기 위해 분모와 분자에 $(\\sqrt{10}+3)$을 곱한다.\\n$\\frac{3(\\sqrt{10}+3)}{(\\sqrt{10}-3)(\\sqrt{10}+3)} = \\frac{3\\sqrt{10}+9}{10-9} = 3\\sqrt{10}+9$이다.\\n따라서 구하는 값은 $3\\sqrt{10}+9$이다."
  },
  {
    id: 22,
    level: "상",
    category: "다항식의 곱셈과 인수분해",
    originalCategory: "다항식의 곱셈과 인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    questionType: "서답형",
    layoutTag: "grid",
    tags: ["서답형"],
    wide: false,
    content: "지민이는 $x$의 계수를 잘못 보아 어떤 이차식을 $(x+1)(x+8)$로 인수분해하였고, 민수는 상수항을 잘못 보아 같은 이차식을 $(x-1)(x-5)$로 인수분해하였다. 처음 이차식을 바르게 인수분해하시오.",
    choices: [],
    answer: "$(x-2)(x-4)$",
    solution: "[키포인트] 계수를 잘못 보았을 경우 바르게 본 항을 찾아 원래 식을 완성한다.\\n조건 정리: 지민이는 상수항을 바르게 보았고 민수는 $x$의 계수를 바르게 보았다.\\n풀이 방향: 두 사람이 전개한 식에서 올바른 부분만 추출하여 원래 이차식을 구한 뒤 인수분해한다.\\n정석 풀이: 지민이의 식을 전개하면 $(x+1)(x+8) = x^{2}+9x+8$이다.\\n$x$의 계수를 잘못 보았으므로 원래 식의 올바른 상수항은 $8$이다.\\n민수의 식을 전개하면 $(x-1)(x-5) = x^{2}-6x+5$이다.\\n상수항을 잘못 보았으므로 원래 식의 올바른 $x$의 계수는 $-6$이다.\\n이를 종합하면 원래의 이차식은 $x^{2}-6x+8$이다.\\n이 식을 바르게 인수분해하면 $(x-2)(x-4)$가 된다.\\n따라서 구하는 값은 $(x-2)(x-4)$이다."
  },
  {
    id: 23,
    level: "상",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "서답형",
    layoutTag: "grid",
    tags: ["서답형"],
    wide: false,
    content: "가로의 길이가 $\\sqrt{72}$, 세로의 길이가 $\\sqrt{18}$인 직사각형이 있다. 이 직사각형의 넓이를 $a$, 둘레의 길이를 $b$라 할 때, $a+b$의 값을 구하시오.",
    choices: [],
    answer: "$36+18\\sqrt{2}$",
    solution: "[키포인트] 직사각형의 넓이와 둘레 공식을 활용하기 위해 근호를 밖으로 꺼내 계산을 용이하게 한다.\\n조건 정리: 가로 길이는 $6\\sqrt{2}$, 세로 길이는 $3\\sqrt{2}$이다.\\n풀이 방향: 넓이 $a$와 둘레 $b$를 구한 후 합한다.\\n정석 풀이: 가로 길이는 $\\sqrt{72} = \\sqrt{36 \\times 2} = 6\\sqrt{2}$이다.\\n세로 길이는 $\\sqrt{18} = \\sqrt{9 \\times 2} = 3\\sqrt{2}$이다.\\n넓이 $a = 6\\sqrt{2} \\times 3\\sqrt{2} = 18 \\times 2 = 36$이다.\\n둘레의 길이 $b = 2(6\\sqrt{2}+3\\sqrt{2}) = 2(9\\sqrt{2}) = 18\\sqrt{2}$이다.\\n구하는 값은 $a+b = 36+18\\sqrt{2}$이다.\\n따라서 구하는 값은 $36+18\\sqrt{2}$이다."
  },
  {
    id: 24,
    level: "상",
    category: "실수와 그 계산",
    originalCategory: "실수와 그 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    questionType: "서답형",
    layoutTag: "grid",
    tags: ["서답형"],
    wide: false,
    content: "함수 $f(x)=\\sqrt{x+1}+\\sqrt{x}$에 대하여, $\\frac{1}{f(1)}+\\frac{1}{f(2)}+\\dots+\\frac{1}{f(48)}$의 값을 구하시오.",
    choices: [],
    answer: "$6$",
    solution: "[키포인트] 분모에 무리수 합이 있는 항들의 덧셈은 유리화하면 연속적으로 소거되는 규칙이 나타난다.\\n조건 정리: $\\frac{1}{f(x)} = \\frac{1}{\\sqrt{x+1}+\\sqrt{x}}$를 유리화하여 연쇄 소거 꼴로 만든다.\\n풀이 방향: 유리화하면 $\\sqrt{x+1}-\\sqrt{x}$가 되며, $x=1$부터 $48$까지 대입하여 더한다.\\n정석 풀이: 주어진 항의 일반항 $\\frac{1}{f(x)}$를 변형하면,\\n$\\frac{1}{\\sqrt{x+1}+\\sqrt{x}} = \\frac{\\sqrt{x+1}-\\sqrt{x}}{(\\sqrt{x+1}+\\sqrt{x})(\\sqrt{x+1}-\\sqrt{x})} = \\sqrt{x+1}-\\sqrt{x}$이다.\\n주어진 식에 차례대로 대입하여 나열하면 다음과 같다.\\n$\\frac{1}{f(1)} = \\sqrt{2}-\\sqrt{1}$\\n$\\frac{1}{f(2)} = \\sqrt{3}-\\sqrt{2}$\\n$\\frac{1}{f(3)} = \\sqrt{4}-\\sqrt{3}$\\n$\\dots$\\n$\\frac{1}{f(48)} = \\sqrt{49}-\\sqrt{48}$\\n위 식들을 모두 더하면 이웃한 항끼리 소거되어 마지막 남는 항은 $\\sqrt{49}-\\sqrt{1}$이다.\\n$\\sqrt{49}-1 = 7-1 = 6$이다.\\n따라서 구하는 값은 $6$이다."
  }
];