window.examTitle = "23_풍덕중_1학기_중간_중3_유사2";

window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 제곱근에 대한 설명 중 옳은 것은?",
    "choices": [
      "음수의 제곱근은 1개이다.",
      "$\\sqrt{81}$의 음의 제곱근은 $-9$이다.",
      "모든 유리수의 제곱근은 2개이다.",
      "양수 $a$의 제곱근을 서로 곱하면 항상 $-a$가 된다.",
      "$(-5)^2$의 제곱근은 $-5$이다."
    ],
    "answer": "④",
    "solution": "[키포인트] 제곱근의 정의와 성질을 정확히 이해한다.\\n조건 정리: 양수, 음수, 0의 제곱근의 개수와 성질을 파악한다.\\n풀이 방향: 각 보기의 진위 여부를 정의에 근거하여 판단한다.\\n정석 풀이:\\n① 음수의 제곱근은 실수 범위에서 존재하지 않는다.\\n② $\\sqrt{81} = 9$이므로, 9의 음의 제곱근은 $-3$이다.\\n③ 유리수 중 0의 제곱근은 0으로 1개이고, 음수 유리수의 제곱근은 없다.\\n④ 양수 $a$의 제곱근은 $\\sqrt{a}$와 $-\\sqrt{a}$이다. 두 수를 곱하면 $\\sqrt{a} \\times (-\\sqrt{a}) = -(\\sqrt{a})^2 = -a$가 된다.\\n⑤ $(-5)^2 = 25$이므로, 25의 제곱근은 $5$와 $-5$이다.\\n따라서 정답은 ④이다."
  },
  {
    "id": 2,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 중 실수에 대한 설명으로 틀린 것을 고르시오.",
    "choices": [
      "순환소수는 모두 유리수이다.",
      "유리수이면서 동시에 무리수인 수는 없다.",
      "$\\sqrt{1.44}$는 유리수이다.",
      "$\\sqrt{(-5)^2}$의 양의 제곱근은 $\\sqrt{5}$이다.",
      "수직선은 유리수에 대응하는 점들로 완전히 메울 수 있다."
    ],
    "answer": "⑤",
    "solution": "[키포인트] 실수의 분류와 수직선의 연속성을 이해한다.\\n조건 정리: 유리수와 무리수의 정의 및 수직선의 구성을 확인한다.\\n풀이 방향: 각 보기의 실수의 성질을 검토한다.\\n정석 풀이:\\n① 순환소수는 분수로 나타낼 수 있으므로 모두 유리수이다.\\n② 실수는 유리수와 무리수로 명확히 구분되며, 동시에 속하는 수는 없다.\\n③ $\\sqrt{1.44} = \\sqrt{(1.2)^2} = 1.2$이므로 유리수이다.\\n④ $\\sqrt{(-5)^2} = \\sqrt{25} = 5$이다. 5의 양의 제곱근은 $\\sqrt{5}$이므로 옳다.\\n⑤ 수직선은 유리수와 무리수, 즉 실수에 대응하는 점들로 완전히 메워진다. 유리수만으로는 빈틈이 생겨 완전히 메울 수 없다.\\n따라서 정답은 ⑤이다."
  },
  {
    "id": 3,
    "level": "중",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 중 식을 잘못 계산한 것은?",
    "choices": [
      "$\\sqrt{14} \\times \\sqrt{2} = 2\\sqrt{7}$",
      "$\\sqrt{20} \\div \\sqrt{5} = 2$",
      "$2\\sqrt{3} \\times 3\\sqrt{5} = 6\\sqrt{15}$",
      "$4\\sqrt{6} \\div \\frac{2}{\\sqrt{3}} = 6\\sqrt{2}$",
      "$\\sqrt{18} \\div \\sqrt{3} \\times \\sqrt{6} = 3$"
    ],
    "answer": "⑤",
    "solution": "[키포인트] 근호를 포함한 식의 곱셈과 나눗셈 법칙을 적용한다.\\n조건 정리: 각 계산식의 좌변을 정리하여 우변과 비교한다.\\n풀이 방향: $\\sqrt{a} \\times \\sqrt{b} = \\sqrt{ab}$, $\\sqrt{a} \\div \\sqrt{b} = \\sqrt{a/b}$를 이용한다.\\n정석 풀이:\\n① $\\sqrt{14} \\times \\sqrt{2} = \\sqrt{28} = 2\\sqrt{7}$\\n② $\\sqrt{20} \\div \\sqrt{5} = \\sqrt{4} = 2$\\n③ $(2 \\times 3) \\times (\\sqrt{3} \\times \\sqrt{5}) = 6\\sqrt{15}$\\n④ $4\\sqrt{6} \\times \\frac{\\sqrt{3}}{2} = 2\\sqrt{18} = 6\\sqrt{2}$\\n⑤ $\\sqrt{18} \\div \\sqrt{3} \\times \\sqrt{6} = \\sqrt{6} \\times \\sqrt{6} = 6$이다. 3이 아니므로 잘못되었다.\\n따라서 정답은 ⑤이다."
  },
  {
    "id": 4,
    "level": "중",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 계산 중 틀린 것은?",
    "choices": [
      "$\\sqrt{3} \\times \\sqrt{6} - \\sqrt{18} = 0$",
      "$\\sqrt{32} - \\sqrt{2}(\\sqrt{8}-1) = 3\\sqrt{2} - 4$",
      "$(2\\sqrt{3}-\\sqrt{5})\\sqrt{3} = 6-\\sqrt{15}$",
      "$\\frac{\\sqrt{12}-\\sqrt{6}}{\\sqrt{3}} = 2-\\sqrt{2}$",
      "$\\sqrt{75} \\div \\sqrt{3} + 4\\sqrt{2} \\times \\sqrt{2} = 13$"
    ],
    "answer": "②",
    "solution": "[키포인트] 근호가 있는 식의 덧셈, 뺄셈 및 분배법칙을 활용한다.\\n조건 정리: 각 항을 $a\\sqrt{b}$ 꼴로 단순화하여 계산한다.\\n풀이 방향: 곱셈과 나눗셈을 먼저 수행하고 유리화 및 분배법칙을 적용한다.\\n정석 풀이:\\n① $\\sqrt{18} - \\sqrt{18} = 0$\\n② $\\sqrt{32} - \\sqrt{2}(\\sqrt{8}-1) = 4\\sqrt{2} - (\\sqrt{16}-\\sqrt{2}) = 4\\sqrt{2} - 4 + \\sqrt{2} = 5\\sqrt{2} - 4$이다. $3\\sqrt{2}-4$가 아니므로 틀렸다.\\n③ $2\\sqrt{3} \\times \\sqrt{3} - \\sqrt{5} \\times \\sqrt{3} = 2 \\times 3 - \\sqrt{15} = 6 - \\sqrt{15}$\\n④ $\\frac{\\sqrt{12}}{\\sqrt{3}} - \\frac{\\sqrt{6}}{\\sqrt{3}} = \\sqrt{4} - \\sqrt{2} = 2 - \\sqrt{2}$\\n⑤ $\\sqrt{25} + 4 \\times 2 = 5 + 8 = 13$\\n따라서 정답은 ②이다."
  },
  {
    "id": 5,
    "level": "하",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다항식 $(3x-1)(2x+5)$를 전개한 결과로 옳은 것은?",
    "choices": [
      "$6x^2 + 13x - 5$",
      "$6x^2 + 17x - 5$",
      "$6x^2 - 13x - 5$",
      "$6x^2 - 17x - 5$",
      "$6x^2 + 13x + 5$"
    ],
    "answer": "①",
    "solution": "[키포인트] 다항식의 전개 원리인 분배법칙을 적용한다.\\n조건 정리: 일차식들의 곱을 전개하여 동류항을 정리한다.\\n풀이 방향: $(ax+b)(cx+d) = acx^2 + (ad+bc)x + bd$ 공식을 사용한다.\\n정석 풀이:\\n$(3x-1)(2x+5)$를 분배법칙으로 전개하면,\\n$3x \\times 2x + 3x \\times 5 + (-1) \\times 2x + (-1) \\times 5$\\n$= 6x^2 + 15x - 2x - 5$\\n동류항인 $x$항을 계산하면 $6x^2 + 13x - 5$가 된다.\\n따라서 정답은 ①이다."
  },
  {
    "id": 6,
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다항식 $2x^2 + 5x - 3$의 인수가 아닌 것은?",
    "choices": [
      "$x+3$",
      "$2x-1$",
      "1",
      "$x-3$",
      "$(x+3)(2x-1)$"
    ],
    "answer": "④",
    "solution": "[키포인트] 다항식을 인수분해하여 곱의 형태를 확인한다.\\n조건 정리: 대각선 곱셈법을 이용하여 이차식을 인수분해한다.\\n풀이 방향: 곱해서 -3이 되고 더해서 5가 되는 조합을 찾는다.\\n정석 풀이:\\n$2x^2 + 5x - 3$을 인수분해하면,\\n$2x^2 + 5x - 3 = (2x-1)(x+3)$이다.\\n인수는 1, $(2x-1)$, $(x+3)$, $(2x-1)(x+3)$이다.\\n따라서 보기 중 인수가 아닌 것은 ④ $x-3$이다.\\n따라서 정답은 ④이다."
  },
  {
    "id": 7,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\sqrt{32-x}$가 정수가 되도록 하는 자연수 $x$의 개수는?",
    "choices": [
      "4개",
      "5개",
      "6개",
      "7개",
      "8개"
    ],
    "answer": "③",
    "solution": "[키포인트] 근호 안의 수가 0 또는 제곱수여야 정수가 된다.\\n조건 정리: $32-x = k^2$ ($k$는 0 이상의 정수)를 만족하는 자연수 $x$를 찾는다.\\n풀이 방향: $x$가 자연수이므로 $32-x$는 32보다 작은 0 이상의 정수가 되어야 한다.\\n정석 풀이:\\n$32-x$가 될 수 있는 제곱수는 $0, 1, 4, 9, 16, 25$이다. (36 이상은 $x$가 음수가 되므로 제외)\\n1) $32-x=0 \\Rightarrow x=32$\\n2) $32-x=1 \\Rightarrow x=31$\\n3) $32-x=4 \\Rightarrow x=28$\\n4) $32-x=9 \\Rightarrow x=23$\\n5) $32-x=16 \\Rightarrow x=16$\\n6) $32-x=25 \\Rightarrow x=7$\\n위 $x$값들은 모두 자연수이므로 조건에 만족하는 $x$의 개수는 6개이다.\\n따라서 정답은 ③이다."
  },
  {
    "id": 8,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "네 수 $a = 3-\\sqrt{2}$, $b = 1+\\sqrt{3}$, $c = 2$, $d = \\sqrt{10}-1$의 대소 관계를 바르게 나타낸 것은?",
    "choices": [
      "$c \\lt a \\lt b \\lt d$",
      "$a \\lt c \\lt b \\lt d$",
      "$a \\lt c \\lt d \\lt b$",
      "$c \\lt a \\lt d \\lt b$",
      "$a \\lt b \\lt c \\lt d$"
    ],
    "answer": "③",
    "solution": "[키포인트] 실수의 근삿값 또는 제곱근의 성질을 이용하여 크기를 비교한다.\\n조건 정리: $\\sqrt{2} \\approx 1.414, \\sqrt{3} \\approx 1.732, \\sqrt{10} \\approx 3.162$를 활용한다.\\n풀이 방향: 각 수의 근삿값을 계산하여 크기를 순서대로 정렬한다.\\n정석 풀이:\\n$a = 3 - 1.414 = 1.586$\\n$b = 1 + 1.732 = 2.732$\\n$c = 2$\\n$d = 3.162 - 1 = 2.162$\\n수치들을 비교하면 $1.586 \\lt 2 \\lt 2.162 \\lt 2.732$이므로,\\n대소 관계는 $a \\lt c \\lt d \\lt b$이다.\\n따라서 정답은 ③이다."
  },
  {
    "id": 9,
    "level": "중",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\sqrt{54} \\times \\sqrt{20} \\div \\sqrt{15} = a\\sqrt{b}$일 때, $a+b$의 값은? (단, $b$는 가능한 작은 자연수)",
    "choices": [
      "5",
      "6",
      "8",
      "9",
      "10"
    ],
    "answer": "③",
    "solution": "[키포인트] 제곱근의 곱셈과 나눗셈 성질 $\\sqrt{a}\\sqrt{b}=\\sqrt{ab}$ 및 $\\sqrt{a}\\div\\sqrt{b}=\\sqrt{a/b}$를 이용한다.\\n조건 정리: 주어진 식을 계산하여 $a\\sqrt{b}$ 형태로 변환한다.\\n풀이 방향: 근호 안의 수를 먼저 계산하거나, 각각을 $a\\sqrt{b}$ 꼴로 고친 후 계산한다.\\n정석 풀이:\\n$\\sqrt{54} \\times \\sqrt{20} \\div \\sqrt{15} = \\sqrt{\\frac{54 \\times 20}{15}}$\\n$= \\sqrt{\\frac{1080}{15}} = \\sqrt{72}$\\n$\\sqrt{72} = \\sqrt{36 \\times 2} = 6\\sqrt{2}$\\n따라서 $a=6, b=2$이므로 $a+b = 6+2 = 8$이다.\\n따라서 정답은 ③이다."
  },
  {
    "id": 10,
    "level": "중",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\frac{3+\\sqrt{5}}{3-\\sqrt{5}} - \\frac{3-\\sqrt{5}}{3+\\sqrt{5}} = a\\sqrt{5}$일 때, 유리수 $a$의 값은?",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "③",
    "solution": "[키포인트] 분모의 유리화 또는 통분을 통해 식을 정리한다.\\n조건 정리: 두 분수의 차를 계산하여 유리수 $a$를 구한다.\\n풀이 방향: 공통분모 $(3-\\sqrt{5})(3+\\sqrt{5})$로 통분하여 분자를 계산한다.\\n정석 풀이:\\n$\\frac{(3+\\sqrt{5})^2 - (3-\\sqrt{5})^2}{(3-\\sqrt{5})(3+\\sqrt{5})} = \\frac{(9+5+6\\sqrt{5}) - (9+5-6\\sqrt{5})}{9-5}$\\n$= \\frac{14+6\\sqrt{5} - 14+6\\sqrt{5}}{4} = \\frac{12\\sqrt{5}}{4} = 3\\sqrt{5}$\\n따라서 $a=3$이다.\\n따라서 정답은 ③이다."
  },
  {
    "id": 11,
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 다항식 $(x-2)(x^2-x-12)$와 $(x+3)(3x^2-12x+12)$의 공통인수로 적절한 것은?",
    "choices": [
      "$x-4$",
      "$x-2$",
      "$x-3$",
      "$x+4$",
      "$x+1$"
    ],
    "answer": "②",
    "solution": "[키포인트] 각 다항식을 완전히 인수분해하여 공통된 인수를 찾는다.\\n조건 정리: 이차식 부분을 추가로 인수분해한다.\\n풀이 방향: $x^2+ax+b$ 꼴과 $a(x-p)^2$ 꼴의 인수분해를 적용한다.\\n정석 풀이:\\n1) $(x-2)(x^2-x-12) = (x-2)(x-4)(x+3)$\\n2) $(x+3)(3x^2-12x+12) = 3(x+3)(x^2-4x+4) = 3(x+3)(x-2)^2$\\n두 식의 공통인수는 $(x-2)$와 $(x+3)$이다.\\n보기 중 공통인수는 $x-2$이다.\\n따라서 정답은 ②이다."
  },
  {
    "id": 12,
    "level": "중",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$(\\sqrt{5}-2)^6(\\sqrt{5}+2)^6$의 값은?",
    "choices": [
      "$1$",
      "$2$",
      "$4$",
      "$8$",
      "$16$"
    ],
    "answer": "①",
    "solution": "[키포인트] 지수법칙 $a^n b^n = (ab)^n$과 합차 공식을 이용한다.\\n조건 정리: 같은 지수를 가진 두 수의 곱을 먼저 계산한다.\\n풀이 방향: $(\\sqrt{5}-2)$와 $(\\sqrt{5}+2)$를 먼저 곱한 후 6제곱한다.\\n정석 풀이:\\n$(\\sqrt{5}-2)^6(\\sqrt{5}+2)^6 = \\{(\\sqrt{5}-2)(\\sqrt{5}+2)\\}^6$\\n$= \\{(\\sqrt{5})^2 - 2^2\\}^6$\\n$= (5-4)^6 = 1^6 = 1$\\n따라서 정답은 ①이다."
  },
  {
    "id": 13,
    "level": "중",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 중 $\\Box$ 안의 수가 가장 작은 것은?",
    "choices": [
      "$(x+4)^2 = x^2 + \\Box x + 16$",
      "$(2x-3)^2 = 4x^2 + \\Box x + 9$",
      "$(x+5)(x-5) = x^2 + \\Box$",
      "$(3x+1)(x+2) = 3x^2 + \\Box x + 2$",
      "$(x-4)(2x+3) = 2x^2 - 5x + \\Box$"
    ],
    "answer": "③",
    "solution": "[키포인트] 곱셈 공식을 사용하여 식을 전개하고 계수를 비교한다.\\n조건 정리: 각 보기의 $\\Box$에 들어갈 값을 구한다.\\n풀이 방향: 완전제곱식, 합차 공식, 일차식의 곱 전개식을 적용한다.\\n정석 풀이:\\n① $(x+4)^2 = x^2 + 8x + 16 \\Rightarrow \\Box = 8$\\n② $(2x-3)^2 = 4x^2 - 12x + 9 \\Rightarrow \\Box = -12$\\n③ $(x+5)(x-5) = x^2 - 25 \\Rightarrow \\Box = -25$\\n④ $(3x+1)(x+2) = 3x^2 + 7x + 2 \\Rightarrow \\Box = 7$\\n⑤ $(x-4)(2x+3) = 2x^2 - 5x - 12 \\Rightarrow \\Box = -12$\\n가장 작은 수는 -25이다.\\n따라서 정답은 ③이다."
  },
  {
    "id": 14,
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 중 완전제곱식인 것은?",
    "choices": [
      "$x^2 - 10x + 20$",
      "$4a^2 - 12ab + 9b^2$",
      "$16x^2 + 8xy - y^2$",
      "$x^2 + 14x - 49$",
      "$25x^2 - 20x + 16$"
    ],
    "answer": "②",
    "solution": "[키포인트] 다항식이 $(A \\pm B)^2$ 형태로 인수분해되는지 확인한다.\\n조건 정리: 각 보기의 식이 완전제곱식의 조건을 만족하는지 검토한다.\\n풀이 방향: 상수항이나 일차항의 계수가 $(2 \\times A \\times B)$ 구조를 가지는지 확인한다.\\n정석 풀이:\\n① $x^2 - 10x + 25$여야 완전제곱식이다.\\n② $(2a)^2 - 2(2a)(3b) + (3b)^2 = (2a-3b)^2$ (완전제곱식)\\n③ $y^2$의 부호가 +여야 하며 중간항이 일치하지 않는다.\\n④ 상수항이 +49여야 한다.\\n⑤ 중간항이 $-2(5x)(4) = -40x$여야 한다.\\n따라서 정답은 ②이다."
  },
  {
    "id": 15,
    "level": "중",
    "category": "곱셈 공식의 활용",
    "originalCategory": "곱셈 공식의 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$x-y=4, x^2+y^2=26$일 때, $xy$의 값은?",
    "choices": [
      "$2$",
      "$3$",
      "$4$",
      "$5$",
      "$6$"
    ],
    "answer": "④",
    "solution": "[키포인트] 곱셈 공식의 변형 $x^2+y^2 = (x-y)^2 + 2xy$를 이용한다.\\n조건 정리: 주어진 두 식의 값을 변형 공식에 대입한다.\\n풀이 방향: $xy$에 대한 일차방정식을 풀어 값을 구한다.\\n정석 풀이:\\n$x^2+y^2 = (x-y)^2 + 2xy$\\n$26 = 4^2 + 2xy$\\n$26 = 16 + 2xy$\\n$10 = 2xy \\Rightarrow xy = 5$\\n따라서 정답은 ④이다."
  },
  {
    "id": 16,
    "level": "중",
    "category": "곱셈 공식의 활용",
    "originalCategory": "곱셈 공식의 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$x-\\frac{1}{x} = 3$일 때, $x^2 + \\frac{1}{x^2}$의 값은?",
    "choices": [
      "$7$",
      "$9$",
      "$11$",
      "$13$",
      "$15$"
    ],
    "answer": "③",
    "solution": "[키포인트] 곱셈 공식의 변형 $x^2 + \\frac{1}{x^2} = (x-\\frac{1}{x})^2 + 2$를 이용한다.\\n조건 정리: 차가 주어진 경우의 제곱의 합 구하기이다.\\n풀이 방향: 주어진 값 3을 공식에 대입한다.\\n정석 풀이:\\n$x^2 + \\frac{1}{x^2} = (x-\\frac{1}{x})^2 + 2$\\n$= 3^2 + 2 = 9 + 2 = 11$\\n따라서 정답은 ③이다."
  },
  {
    "id": 17,
    "level": "상",
    "category": "곱셈 공식의 활용",
    "originalCategory": "곱셈 공식의 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$(3-1)(3+1)(3^2+1)(3^4+1) = 3^k - 1$이 성립할 때, 자연수 $k$의 값은?",
    "choices": [
      "$2$",
      "$4$",
      "$6$",
      "$8$",
      "$10$"
    ],
    "answer": "④",
    "solution": "[키포인트] 합차 공식 $(a-b)(a+b) = a^2-b^2$을 연속적으로 적용한다.\\n조건 정리: 주어진 식의 좌변을 합차 공식을 이용해 간단히 정리한다.\\n풀이 방향: 앞에서부터 차례대로 두 항씩 묶어 합차 공식을 적용하여 지수를 높여간다.\\n정석 풀이:\\n1) $(3-1)(3+1) = 3^2 - 1$\\n2) $(3^2-1)(3^2+1) = (3^2)^2 - 1 = 3^4 - 1$\\n3) $(3^4-1)(3^4+1) = (3^4)^2 - 1 = 3^8 - 1$\\n따라서 $3^8 - 1 = 3^k - 1$이므로 $k=8$이다.\\n따라서 정답은 ④이다."
  },
  {
    "id": 18,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$-1 \\lt x \\lt 2$일 때, $\\sqrt{(x+1)^2} + \\sqrt{(x-2)^2}$을 간단히 나타내면?",
    "choices": [
      "1",
      "3",
      "$2x-1$",
      "$-2x+1$",
      "$-3$"
    ],
    "answer": "②",
    "solution": "[키포인트] $\\sqrt{A^2} = |A|$ 성질을 이용하여 절댓값 기호 안의 식의 부호를 판단한다.\\n조건 정리: 주어진 범위 $-1 \\lt x \\lt 2$에서 각 식의 부호를 확인한다.\\n풀이 방향: $x+1$과 $x-2$의 부호에 따라 절댓값을 벗기고 식을 정리한다.\\n정석 풀이:\\n$-1 \\lt x \\lt 2$일 때,\\n1) $x+1 \\gt 0$ 이므로 $\\sqrt{(x+1)^2} = x+1$\\n2) $x-2 \\lt 0$ 이므로 $\\sqrt{(x-2)^2} = -(x-2) = -x+2$\\n따라서 $(x+1) + (-x+2) = 3$이다.\\n따라서 정답은 ②이다."
  },
  {
    "id": 19,
    "level": "중",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$x = \\frac{1}{\\sqrt{3}-\\sqrt{2}}, y = \\frac{1}{\\sqrt{3}+\\sqrt{2}}$일 때, $x^2 - xy + y^2$의 값은?",
    "choices": [
      "7",
      "8",
      "9",
      "10",
      "11"
    ],
    "answer": "③",
    "solution": "[키포인트] 분모를 유리화한 후 곱셈 공식의 변형 $x^2-xy+y^2 = (x+y)^2 - 3xy$를 이용한다.\\n조건 정리: $x, y$를 유리화하여 합($x+y$)과 곱($xy$)을 구한다.\\n풀이 방향: 유리화된 값을 변형 공식에 대입하여 계산을 간소화한다.\\n정석 풀이:\\n$x = \\frac{\\sqrt{3}+\\sqrt{2}}{3-2} = \\sqrt{3}+\\sqrt{2}$\\n$y = \\frac{\\sqrt{3}-\\sqrt{2}}{3-2} = \\sqrt{3}-\\sqrt{2}$\\n$x+y = 2\\sqrt{3}$, $xy = (\\sqrt{3}+\\sqrt{2})(\\sqrt{3}-\\sqrt{2}) = 3-2 = 1$\\n$x^2-xy+y^2 = (x+y)^2 - 3xy = (2\\sqrt{3})^2 - 3(1) = 12 - 3 = 9$\\n따라서 정답은 ③이다."
  },
  {
    "id": 20,
    "level": "상",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다항식 $(x-1)(x-2)(x+3)(x+4) - 24$를 인수분해한 결과로 적절한 것은?",
    "choices": [
      "$x(x-2)(x^2+2x-11)$",
      "$x(x+2)(x^2+2x-11)$",
      "$(x-1)(x+2)(x^2-2x-11)$",
      "$(x+1)(x+2)(x^2-2x-11)$",
      "$x(x+1)(x^2+2x-11)$"
    ],
    "answer": "②",
    "solution": "[키포인트] 공통부분이 생기도록 항을 적절히 묶어 전개한 후 치환하여 인수분해한다.\\n조건 정리: 상수항의 합이 같아지는 조합인 $(x-1)(x+2)$와 $(x-2)(x+3)$을 묶는다.\\n풀이 방향: $x^2+2x = t$로 치환하여 이차식의 인수분해를 수행한다.\\n정석 풀이:\\n$\\{(x-1)(x+3)\\}\\{(x-2)(x+4)\\} - 24$\\n$= (x^2+2x-3)(x^2+2x-8) - 24$\\n$x^2+2x = t$라 하면, $(t-3)(t-8) - 24 = t^2-11t+24-24 = t^2-11t$\\n$= t(t-11)$\\n$t$를 환원하면, $(x^2+2x)(x^2+2x-11) = x(x+2)(x^2+2x-11)$\\n따라서 정답은 ②이다."
  },
  {
    "id": 21,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "주관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "세 실수 $A = 3-\\sqrt{5}$, $B = \\frac{1}{2}$, $C = \\sqrt{3}-1$의 대소 관계를 부등호로 바르게 나타내시오.",
    "choices": [],
    "answer": "$B \\lt C \\lt A$",
    "solution": "[키포인트] 무리수의 근삿값($\\sqrt{3} \\approx 1.732, \\sqrt{5} \\approx 2.236$)을 이용하여 수치적으로 비교한다.\\n조건 정리: 각 식을 소수로 근사하여 크기를 판단한다.\\n풀이 방향: $A, B, C$를 각각 계산하여 수직선상의 위치를 파악한다.\\n정석 풀이:\\n$A = 3 - 2.236 = 0.764$\\n$B = 0.5$\\n$C = 1.732 - 1 = 0.732$\\n따라서 $0.5 \\lt 0.732 \\lt 0.764$ 이므로 대소 관계는 $B \\lt C \\lt A$ 이다.\\n따라서 구하는 값은 $B \\lt C \\lt A$이다."
  },
  {
    "id": 22,
    "level": "상",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "주관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다항식 $2x^2 + 3xy - 2y^2 + x + 7y - 3$을 두 일차식의 곱으로 인수분해하시오.",
    "choices": [],
    "answer": "$(x+2y-1)(2x-y+3)$",
    "solution": "[키포인트] 여러 개의 문자를 포함한 식은 차수가 낮은 한 문자에 대하여 내림차순으로 정리하여 인수분해한다.\\n조건 정리: $x$에 대한 내림차순으로 식을 정리한다.\\n풀이 방향: $x$의 이차식으로 보고 상수항($y$의 식)을 먼저 인수분해한 후 전체를 인수분해한다.\\n정석 풀이:\\n$2x^2 + (3y+1)x - (2y^2-7y+3)$\\n$= 2x^2 + (3y+1)x - (2y-1)(y-3)$\\n계수를 맞추기 위해 $(x+2y-1)(2x-y+3)$으로 조합하면,\\n$x(3-y) + 2x(2y-1) = -xy+3x + 4xy-2x = 3xy+x = (3y+1)x$가 되어 성립한다.\\n따라서 $(x+2y-1)(2x-y+3)$이다.\\n따라서 구하는 값은 $(x+2y-1)(2x-y+3)$이다."
  },
  {
    "id": 23,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "주관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$x=2, y=-\\sqrt{3}$일 때, $\\sqrt{x^2-6xy+9y^2} + \\sqrt{9y^2}$을 간단히 하여 그 값을 구하시오.",
    "choices": [],
    "answer": "$2+6\\sqrt{3}$",
    "solution": "[키포인트] 완전제곱식 인수분해와 $\\sqrt{A^2} = |A|$ 성질을 이용한다.\\n조건 정리: 근호 안의 식을 정리하고 $x, y$를 대입하여 부호를 판별한다.\\n풀이 방향: $|x-3y| + |3y|$ 형태로 만든 후 수치를 대입한다.\\n정석 풀이:\\n$\\sqrt{(x-3y)^2} + \\sqrt{(3y)^2} = |x-3y| + |3y|$\\n$x=2, y=-\\sqrt{3}$을 대입하면,\\n$|2 - 3(-\\sqrt{3})| + |3(-\\sqrt{3})| = |2+3\\sqrt{3}| + |-3\\sqrt{3}|$\\n$2+3\\sqrt{3} \\gt 0$ 이므로 그대로 나오고, $-3\\sqrt{3} \\lt 0$ 이므로 부호를 바꾸어 나온다.\\n$(2+3\\sqrt{3}) + 3\\sqrt{3} = 2+6\\sqrt{3}$\\n따라서 구하는 값은 $2+6\\sqrt{3}$이다."
  },
  {
    "id": 24,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "주관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\sqrt{\\frac{12}{x}}$가 자연수가 되도록 하는 모든 자연수 $x$의 값의 합을 구하시오.",
    "choices": [],
    "answer": "15",
    "solution": "[키포인트] $\\sqrt{\\text{식}}$이 자연수가 되려면 근호 안의 분수 $\\frac{12}{x}$가 어떤 자연수의 제곱(제곱수)이 되어야 한다.\\n조건 정리: $12 = 2^2 \\times 3$ 임을 이용하여 $x$가 지수를 짝수로 만드는 약수임을 확인한다.\\n풀이 방향: $\\frac{12}{x}$가 $1, 4, 9, \\dots$ 등이 되는 자연수 $x$를 찾는다.\\n정석 풀이:\\n1) $\\frac{12}{x} = 1 \\Rightarrow x=12$\\n2) $\\frac{12}{x} = 4 \\Rightarrow x=3$\\n3) $\\frac{12}{x} = 9 \\Rightarrow x=12/9$ (자연수 아님)\\n따라서 가능한 자연수 $x$는 3, 12이다.\\n모든 $x$의 합은 $3+12 = 15$이다.\\n따라서 구하는 값은 15이다."
  }
];