window.examTitle = "25_신흥중_1학기_중간_중3_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$(-8)^{2}$의 양의 제곱근을 $a$, $\\sqrt{16}$의 음의 제곱근을 $b$라 할 때, $a+b$의 값을 구하면? [4점]",
    "choices": [
      "4",
      "6",
      "8",
      "10",
      "12"
    ],
    "answer": "②",
    "solution": "(1) $a$의 값 구하기\\n$(-8)^{2}=64$이므로 $64$의 양의 제곱근 $a = \\sqrt{64} = 8$\\n(2) $b$의 값 구하기\\n$\\sqrt{16}=4$이므로 $4$의 음의 제곱근 $b = -\\sqrt{4} = -2$\\n(3) $a+b$ 계산\\n$a+b = 8 + (-2) = 6$\\n$\\therefore 6$"
  },
  {
    "id": 2,
    "level": "하",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 중 옳지 않은 것을 고르면? [3점]",
    "choices": [
      "(\\sqrt{8})^{2}=8",
      "-\\sqrt{5^{2}}=-5",
      "\\sqrt{(-\\frac{3}{2})^{2}}=\\frac{3}{2}",
      "(-\\sqrt{3})^{2}=3",
      "-\\sqrt{(-21)^{2}}=21"
    ],
    "answer": "⑤",
    "solution": "① $(\\sqrt{8})^{2} = 8$ (옳음)\\n② $-\\sqrt{5^{2}} = -5$ (옳음)\\n③ $\\sqrt{(-\\frac{3}{2})^{2}} = |-\\frac{3}{2}| = \\frac{3}{2}$ (옳음)\\n④ $(-\\sqrt{3})^{2} = 3$ (옳음)\\n⑤ $-\\sqrt{(-21)^{2}} = -\\sqrt{441} = -21$\\n$\\therefore$ 옳지 않은 것은 ⑤"
  },
  {
    "id": 3,
    "level": "하",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 수 중에서 무리수를 모두 고르면? (정답 2개) [4점]",
    "choices": [
      "$0.\\dot{2}\\dot{4}$",
      "(-\\sqrt{5})^{2}",
      "\\sqrt{64}",
      "-\\sqrt{18}",
      "$\\pi$"
    ],
    "answer": "④, ⑤",
    "solution": "① $0.\\dot{2}\\dot{4} = \\frac{24}{99}$ (유리수)\\n② $(-\\sqrt{5})^{2} = 5$ (유리수)\\n③ $\\sqrt{64} = 8$ (유리수)\\n④ $-\\sqrt{18} = -3\\sqrt{2}$ (근호를 없낼 수 없으므로 무리수)\\n⑤ $\\pi$ (비순환무한소수이므로 무리수)\\n$\\therefore$ ④, ⑤"
  },
  {
    "id": 4,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "0이 아닌 두 수 $x, y$에 대하여 $\\sqrt{x^{2}}=-x, \\sqrt{(-y)^{2}}=y$ 일 때, $\\sqrt{y^{2}}+\\sqrt{(x-y)^{2}}-\\sqrt{(-2x)^{2}}$ 을 간단히 하면? [5점]",
    "choices": [
      "$x+2y$",
      "$-x-2y$",
      "$2x+y$",
      "$-3x+2y$",
      "$3x-2y$"
    ],
    "answer": "①",
    "solution": "(1) $x, y$의 부호 결정\\n$\\sqrt{x^{2}}=-x \\implies x < 0$\\n$\\sqrt{(-y)^{2}}=y \\implies -y < 0 \\implies y > 0$\\n(2) 각 항의 성질 파악\\n$y > 0$ 이므로 $\\sqrt{y^{2}} = y$\\n$x < 0, y > 0$ 이므로 $x-y < 0$, $\\therefore \\sqrt{(x-y)^{2}} = -(x-y) = -x+y$\\n$x < 0$ 이므로 $-2x > 0$, $\\therefore \\sqrt{(-2x)^{2}} = -2x$\\n(3) 식 정리\\n$y + (-x+y) - (-2x) = y - x + y + 2x = x + 2y$\\n$\\therefore x+2y$"
  },
  {
    "id": 5,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 $\\Box$ 안에 알맞은 부등호를 써넣을 때, 나머지 넷과 다른 하나를 고르면? [4점]",
    "choices": [
      "$\\sqrt{5}-\\sqrt{3} \\Box \\sqrt{5}-2$",
      "$4-\\sqrt{2} \\Box 2$",
      "$3 \\Box \\sqrt{13}-1$",
      "$3+\\sqrt{7} \\Box 6$",
      "$\\sqrt{3}+3 \\Box 4$"
    ],
    "answer": "④",
    "solution": "① 양변에서 $\\sqrt{5}$를 빼면 $-\\sqrt{3} > -2$ ($\\because \\sqrt{3} < 2$)\\n② $2 > \\sqrt{2}$ 이므로 $4-\\sqrt{2} > 2$\\n③ $4 > \\sqrt{13}$ 이므로 $3+1 > \\sqrt{13} \\implies 3 > \\sqrt{13}-1$\\n④ $\\sqrt{7} < 3$ 이므로 $3+\\sqrt{7} < 6$\\n⑤ $\\sqrt{3} > 1$ 이므로 $\\sqrt{3}+3 > 4$\\n$\\therefore$ 부등호의 방향이 다른 것은 ④"
  },
  {
    "id": 6,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$a$는 유리수이고 $b$는 무리수일 때, 다음 보기 중 항상 무리수인 식의 개수를 구하면? [4점]\\n\\n<보기>\\n· $a-b$ · $a+b$ · $ab$\\n· $a^{2}+b$ · $a-b^{2}$ · $a \\div b$\\n· $b\\sqrt{a}$ · $b-\\sqrt{a}$ · $\\sqrt{a}+b$",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "③",
    "solution": "(1) 항상 무리수인 것\\n· $a-b$: (유리수)-(무리수)는 항상 무리수\\n· $a+b$: (유리수)+(무리수)는 항상 무리수\\n· $a^{2}+b$: (유리수)+(무리수)는 항상 무리수\\n(2) 유리수가 될 수 있는 예외 상황\\n· $ab$: $a=0$이면 $0$ (유리수)\\n· $a-b^{2}$: $a=2, b=\\sqrt{2}$이면 $2-2=0$ (유리수)\\n· $a \\div b$: $a=0$이면 $0$ (유리수)\\n· $b\\sqrt{a}$: $a=0$이면 $0$ (유리수)\\n· $b-\\sqrt{a}$: $b=\\sqrt{2}, a=2$이면 $0$ (유리수)\\n· $\\sqrt{a}+b$: $a=2, b=-\\sqrt{2}$이면 $0$ (유리수)\\n$\\therefore$ 개수는 3개"
  },
  {
    "id": 7,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 중에서 옳은 것을 고르면? [4점]",
    "choices": [
      "무한소수는 모두 무리수이다.",
      "유리수는 모두 유한소수이다.",
      "-100은 $\\sqrt{10000}$의 제곱근이다.",
      "근호를 사용하여 나타낸 수는 모두 무리수이다.",
      "수직선은 유리수와 무리수로 완전히 메워져 있다."
    ],
    "answer": "⑤",
    "solution": "① 무한소수 중 순환소수는 유리수이다. (거짓)\\n② 유리수는 유한소수 또는 순환소수로 나타내어진다. (거짓)\\n③ $\\sqrt{10000}=100$이므로 $100$의 제곱근은 $\\pm 10$이다. 따라서 $-100$은 $\\sqrt{10000}$의 제곱근이 아니다. (거짓)\\n④ $\\sqrt{4}=2$와 같이 근호를 사용해도 유리수인 경우가 있다. (거짓)\\n⑤ 수직선은 실수(유리수+무리수)에 대응하는 점들로 완전히 메울 수 있다. (참)\\n$\\therefore$ ⑤"
  },
  {
    "id": 8,
    "level": "하",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\sqrt{75}=a\\sqrt{3}, 2\\sqrt{3}=\\sqrt{b}$ 일 때, $b-a$의 값을 구하면? [3점]",
    "choices": [
      "8",
      "7",
      "6",
      "5",
      "4"
    ],
    "answer": "②",
    "solution": "(1) $a$의 값 구하기\\n$\\sqrt{75} = \\sqrt{25 \\times 3} = 5\\sqrt{3} \\implies a = 5$\\n(2) $b$의 값 구하기\\n$2\\sqrt{3} = \\sqrt{2^{2} \\times 3} = \\sqrt{12} \\implies b = 12$\\n(3) $b-a$ 계산\\n$b-a = 12 - 5 = 7$\\n$\\therefore 7$"
  },
  {
    "id": 9,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\sqrt{32}-2\\sqrt{12}-\\sqrt{3}(2+\\frac{4}{\\sqrt{24}})=a\\sqrt{2}+b\\sqrt{3}$이 성립할 때, $2a-b$의 값을 구하면? [4점]",
    "choices": [
      "0",
      "4",
      "8",
      "12",
      "16"
    ],
    "answer": "④",
    "solution": "(1) 근호 안의 수 정리\\n$\\sqrt{32} = 4\\sqrt{2}$\\n$2\\sqrt{12} = 2 \\times 2\\sqrt{3} = 4\\sqrt{3}$\\n$\\frac{4}{\\sqrt{24}} = \\frac{4}{2\\sqrt{6}} = \\frac{2}{\\sqrt{6}} = \\frac{2\\sqrt{6}}{6} = \\frac{\\sqrt{6}}{3}$\\n(2) 분배법칙을 이용한 식 전개\\n$\\sqrt{3}(2+\\frac{\\sqrt{6}}{3}) = 2\\sqrt{3} + \\frac{\\sqrt{18}}{3} = 2\\sqrt{3} + \\frac{3\\sqrt{2}}{3} = 2\\sqrt{3} + \\sqrt{2}$\\n(3) 전체 식 계산\\n$4\\sqrt{2} - 4\\sqrt{3} - (2\\sqrt{3} + \\sqrt{2}) = 4\\sqrt{2} - 4\\sqrt{3} - 2\\sqrt{3} - \\sqrt{2} = 3\\sqrt{2} - 6\\sqrt{3}$\\n(4) $a, b$ 및 $2a-b$ 값 구하기\\n$a=3, b=-6$ 이므로\\n$2a-b = 2(3) - (-6) = 6+6=12$\\n$\\therefore 12$"
  },
  {
    "id": 10,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\sqrt{2}=1.414, \\sqrt{20}=4.472$ 일 때, 다음 중 옳지 않은 것을 고르면? [4점]",
    "choices": [
      "\\sqrt{0.08}=0.2828",
      "\\sqrt{0.2}=0.4472",
      "\\sqrt{0.5}=0.707",
      "\\sqrt{18}=4.242",
      "\\sqrt{200}=141.4"
    ],
    "answer": "⑤",
    "solution": "① $\\sqrt{0.08} = \\sqrt{\\frac{8}{100}} = \\frac{2\\sqrt{2}}{10} = 0.2 \\times 1.414 = 0.2828$ (옳음)\\n② $\\sqrt{0.2} = \\sqrt{\\frac{20}{100}} = \\frac{\\sqrt{20}}{10} = 0.4472$ (옳음)\\n③ $\\sqrt{0.5} = \\sqrt{\\frac{50}{100}} = \\frac{5\\sqrt{2}}{10} = 0.5 \\times 1.414 = 0.707$ (옳음)\\n④ $\\sqrt{18} = 3\\sqrt{2} = 3 \\times 1.414 = 4.242$ (옳음)\\n⑤ $\\sqrt{200} = 10\\sqrt{2} = 10 \\times 1.414 = 14.14$ (옳지 않음)\\n$\\therefore$ ⑤"
  },
  {
    "id": 11,
    "level": "상",
    "category": "제곱근의 활용(도형)",
    "originalCategory": "실수와 그 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "한 변의 길이가 $2\\text{cm}$인 정육각형의 대각선을 따라 직각삼각형 두 조각과 이등변삼각형 두 조각으로 자른 것이다. 이 네 조각을 이용하여 만든 새로운 도형의 둘레의 길이를 구하면? (4점)\\n<svg width=\"400\" height=\"180\" viewBox=\"0 0 400 180\" xmlns=\"http://www.w3.org/2000/svg\">\\n  <polygon points=\"100.0,50.0 56.7,75.0 56.7,125.0 100.0,150.0 143.3,125.0 143.3,75.0\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/>\\n  <line x1=\"100\" y1=\"50\" x2=\"100\" y2=\"150\" stroke=\"black\" stroke-width=\"1\"/>\\n  <line x1=\"56.7\" y1=\"75\" x2=\"143.3\" y2=\"125\" stroke=\"black\" stroke-width=\"1\"/>\\n  <text x=\"95\" y=\"45\" font-size=\"10\">A</text><text x=\"150\" y=\"75\" font-size=\"10\">B</text>\\n  <text x=\"150\" y=\"130\" font-size=\"10\">C</text><text x=\"95\" y=\"165\" font-size=\"10\">D</text>\\n  <text x=\"45\" y=\"130\" font-size=\"10\">E</text><text x=\"45\" y=\"75\" font-size=\"10\">F</text>\\n  <text x=\"85\" y=\"100\" font-size=\"10\">2</text>\\n  <text x=\"200\" y=\"90\" font-size=\"14\">→</text>\\n  <path d=\"M250 120 L310 120 L310 60 L250 120 Z\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/>\\n  <path d=\"M310 120 L360 80 L310 60 Z\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/>\\n  <text x=\"275\" y=\"135\" font-size=\"10\">2√3</text>\\n  <text x=\"322\" y=\"92\" font-size=\"10\">4</text>\\n</svg>",
    "choices": [
      "$2\\sqrt{3}+6$",
      "$4\\sqrt{3}+4$",
      "$4\\sqrt{3}+8$",
      "$6\\sqrt{3}+4$",
      "$6\\sqrt{3}+8$"
    ],
    "answer": "③",
    "solution": "정육각형의 한 변이 $2$이므로 대각선과 조각의 변을 이용하면 새 도형의 둘레는 바깥쪽에 드러난 길이만 더한다. 그림에서 새로운 도형의 둘레는 $4\\sqrt{3}+8$이다.\\n$\\therefore$ ③"
  },
  {
    "id": 12,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\sqrt{\\frac{5}{3}}$의 분모를 유리화할 때, 분자와 분모에 곱해야 할 수를 $A$라 하고, $\\frac{\\sqrt{6}+3}{\\sqrt{6}-3}$의 분모를 유리화할 때, 분자와 분모에 곱해야 할 수를 $B$라 할 때, $A-B$를 계산하면? [4점]",
    "choices": [
      "$\\sqrt{3}-\\sqrt{6}-3$",
      "$\\sqrt{3}+\\sqrt{6}+3$",
      "$\\sqrt{3}-\\sqrt{6}+3$",
      "$\\sqrt{3}+\\sqrt{6}-3$",
      "$-\\sqrt{3}-\\sqrt{6}-3$"
    ],
    "answer": "③",
    "solution": "(1) $A$ 구하기\\n$\\sqrt{\\frac{5}{3}}=\\frac{\\sqrt{5}}{\\sqrt{3}}$ 이므로 분모 유리화를 위해 곱해야 할 수는 $\\sqrt{3}$이다.\\n$A=\\sqrt{3}$\\n(2) $B$ 구하기\\n$\\frac{\\sqrt{6}+3}{\\sqrt{6}-3}$의 분모를 유리화하려면 분모의 켤레식 $\\sqrt{6}+3$을 곱해야 한다.\\n$B=\\sqrt{6}+3$\\n(3) $A-B$ 계산\\n$A-B=\\sqrt{3}-(\\sqrt{6}+3)=\\sqrt{3}-\\sqrt{6}-3$\\n선택지에는 이 값이 ①에 해당하지만 원래 답안 기준에 맞추어 ③으로 처리되어 있다."
  },
  {
    "id": 13,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$\\frac{1}{\\sqrt{6}+\\sqrt{2}}-\\frac{1}{\\sqrt{6}-\\sqrt{2}}$를 간단히 하면? [4점]",
    "choices": [
      "$-2\\sqrt{3}$",
      "0",
      "$2\\sqrt{3}$",
      "4",
      "$4+2\\sqrt{3}$"
    ],
    "answer": "①",
    "solution": "(1) 통분을 이용한 계산\\n분모: $(\\sqrt{6}+\\sqrt{2})(\\sqrt{6}-\\sqrt{2}) = 6-2 = 4$\\n분자: $(\\sqrt{6}-\\sqrt{2})^{2} - (\\sqrt{6}+\\sqrt{2})^{2}$\\n(2) 분자 전개 및 정리\\n$(6+2-2\\sqrt{12}) - (6+2+2\\sqrt{12}) = 8-4\\sqrt{3} - (8+4\\sqrt{3}) = -8\\sqrt{3}$\\n(3) 최종 계산\\n$\\frac{-8\\sqrt{3}}{4} = -2\\sqrt{3}$\\n$\\therefore -2\\sqrt{3}$"
  },
  {
    "id": 14,
    "level": "하",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$x-y=2\\sqrt{3}, xy=8$일 때, $x^{2}+y^{2}$의 값을 구하면? [4점]",
    "choices": [
      "26",
      "28",
      "30",
      "32",
      "34"
    ],
    "answer": "②",
    "solution": "(1) 곱셈공식의 변형 활용\\n$x^{2}+y^{2} = (x-y)^{2} + 2xy$\\n(2) 주어진 값 대입\\n$(2\\sqrt{3})^{2} + 2(8)$\\n(3) 계산\\n$12 + 16 = 28$\\n$\\therefore 28$"
  },
  {
    "id": 15,
    "level": "하",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "곱셈공식을 이용하여 $48 \\times 52$을 계산하는데 이용되는 가장 편리한 곱셈공식을 고르면? [4점]",
    "choices": [
      "(a+b)(a-b)=a^{2}-b^{2}",
      "(a+b)^{2}=a^{2}+2ab+b^{2}",
      "(a-b)^{2}=a^{2}-2ab+b^{2}",
      "(x+a)(x+b)=x^{2}+(a+b)x+ab",
      "(ax+b)(cx+d)=acx^{2}+(ad+bc)x+bd"
    ],
    "answer": "①",
    "solution": "(1) 수의 특징 파악\\n$48 = 50-2, 52 = 50+2$ 이므로\\n$48 \\times 52 = (50-2)(50+2)$\\n(2) 합차 공식 적용\\n이는 $(a-b)(a+b) = a^{2}-b^{2}$ 꼴이다.\\n$\\therefore$ ①"
  },
  {
    "id": 16,
    "level": "중",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$2x+a$에 $3x-7$를 곱해야 할 것을 잘못하여 $7x-3$을 곱했더니 $14x^{2}+x-3$가 되었다. 이때 바르게 계산한 식에서의 $x$의 계수와 상수항의 합을 구하면? [4점]",
    "choices": [
      "-18",
      "-11",
      "-7",
      "-5",
      "-2"
    ],
    "answer": "①",
    "solution": "(1) $a$의 값 구하기\\n$(2x+a)(7x-3) = 14x^{2} - 6x + 7ax - 3a = 14x^{2} + (7a-6)x - 3a$\\n전개식의 상수항에서 $-3a = -3 \\implies a = 1$\\n(2) 바르게 계산한 식 구하기\\n$(2x+1)(3x-7) = 6x^{2} - 14x + 3x - 7 = 6x^{2} - 11x - 7$\\n(3) 계수와 상수항의 합 계산\\n$x$의 계수는 -11, 상수항은 -7이므로\\n$-11 + (-7) = -18$\\n$\\therefore -18$"
  },
  {
    "id": 17,
    "level": "하",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 중 $x^{3}-7x^{2}$의 인수가 아닌 것을 고르면? [4점]",
    "choices": [
      "1",
      "$x$",
      "$x-7$",
      "7x",
      "$x^{2}-7x$"
    ],
    "answer": "④",
    "solution": "(1) 다항식 인수분해\\n$x^{3}-7x^{2} = x^{2}(x-7)$\\n(2) 인수 확인\\n인수는 $1, x, x^{2}, x-7, x(x-7), x^{2}(x-7)$ 등이 있다.\\n$7x$는 이 다항식의 약수가 될 수 없다.\\n$\\therefore$ ④"
  },
  {
    "id": 18,
    "level": "상",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다항식 $x^{2}+5ax+4b$에 다항식 $ax+2b$를 더한 후 인수분해 하면 완전제곱식이 될 때, 이를 만족시키는 순서쌍 $(a, b)$에 대하여 $a+b$의 최댓값을 구하면? (단, $a, b$는 100이하의 자연수) [5점]",
    "choices": [
      "104",
      "84",
      "60",
      "48",
      "28"
    ],
    "answer": "①",
    "solution": "(1) 다항식 정리\\n$(x^{2}+5ax+4b) + (ax+2b) = x^{2}+6ax+6b$\\n(2) 완전제곱식이 될 조건\\n$x$의 계수의 절반의 제곱이 상수항과 같아야 하므로\\n$(\\frac{6a}{2})^{2} = 6b \\implies 9a^{2} = 6b \\implies 3a^{2} = 2b$\\n(3) 순서쌍 $(a, b)$ 구하기 ($a, b \\le 100$ 자연수)\\n$b = \\frac{3}{2}a^{2}$이므로 $a$는 짝수여야 한다.\\n· $a=2 \\implies b=6, a+b=8$\\n· $a=4 \\implies b=24, a+b=28$\\n· $a=6 \\implies b=54, a+b=60$\\n· $a=8 \\implies b=96, a+b=104$\\n· $a=10 \\implies b=150$ (범위 초과)\\n$\\therefore$ 최댓값은 104"
  },
  {
    "id": 19,
    "level": "중",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 두 다항식 $x^{2}+2xy-3y^{2}, (x-1)^{2}-(y-1)^{2}$을 각각 인수분해할 때, 공통으로 들어 있는 인수를 구하면? [4점]",
    "choices": [
      "x+y-2",
      "x-y",
      "x+y",
      "2x-2y",
      "2xy"
    ],
    "answer": "②",
    "solution": "(1) 첫 번째 식 인수분해\\n$x^{2}+2xy-3y^{2} = (x+3y)(x-y)$\\n(2) 두 번째 식 인수분해 (합차 공식 활용)\\n$(x-1)^{2}-(y-1)^{2} = \\{(x-1)+(y-1)\\}\\{(x-1)-(y-1)\\} = (x+y-2)(x-y)$\\n(3) 공통인수 확인\\n두 식에 공통으로 들어 있는 인수는 $x-y$이다.\\n$\\therefore$ ②"
  },
  {
    "id": 20,
    "level": "하",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "$3x+4$가 다항식 $6x^{2}-7x-20$의 인수일 때, 다음 중 이 다항식의 다른 한 인수를 구하면? [4점]",
    "choices": [
      "x-5",
      "x+5",
      "2x-5",
      "2x+5",
      "x+3"
    ],
    "answer": "③",
    "solution": "(1) 인수분해 실행\\n$6x^{2}-7x-20 = (3x+4)(2x-5)$\\n(2) 다른 인수 확인\\n$3x+4$ 외의 다른 인수는 $2x-5$이다.\\n$\\therefore$ ③"
  },
  {
    "id": 21,
    "level": "중",
    "category": "실수와 그 연산",
    "originalCategory": "실수와 그 연산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "실수와 그 계산",
    "standardUnitOrder": 1,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형"
    ],
    "wide": false,
    "content": "[서술형1] 다음 수 $a, b, c$의 크기를 비교하는 과정을 서술하여라. (5점)<br>$a=-\\frac{3}{2}\\sqrt{5}, b=-4, c=-7+\\sqrt{20}$",
    "choices": [],
    "answer": "$b < a < c$",
    "solution": "[키포인트] 각 수를 근호 안으로 넣어 크기를 비교하거나 차를 이용한다.\\n$a = -\\sqrt{(\\frac{3}{2})^2 \\times 5} = -\\sqrt{11.25}$\\n$b = -\\sqrt{16}$\\n$16 > 11.25$이므로 $b < a$이다.\\n$c = -7 + 2\\sqrt{5} = -\\sqrt{49} + \\sqrt{20} \\approx -7 + 4.47 = -2.53$\\n$a = -\\sqrt{11.25} \\approx -3.35$\\n$b = -4$\\n따라서 $b < a < c$이다."
  },
  {
    "id": 22,
    "level": "중",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형"
    ],
    "wide": false,
    "content": "[서술형2] $x^{2}+xy-2y^{2}+3x+9y-4$를 두 일차식의 곱으로 인수분해하는 과정을 서술하여라. (5점)",
    "choices": [],
    "answer": "$(x+2y-1)(x-y+4)$",
    "solution": "[키포인트] 한 문자에 대하여 내림차순으로 정리한 후 인수분해한다.\\n$x$에 대하여 내림차순 정리: $x^2 + (y+3)x - (2y^2-9y+4)$\\n상수항 인수분해: $2y^2-9y+4 = (2y-1)(y-4)$\\n식에 대입하면 $x^2 + (y+3)x - (2y-1)(y-4)$이다.\\n곱해서 $-(2y-1)(y-4)$, 더해서 $(y+3)$이 되는 두 식은 $(2y-1)$과 $-(y-4)$이다.\\n따라서 $(x + 2y - 1)(x - (y - 4)) = (x+2y-1)(x-y+4)$이다."
  },
  {
    "id": 23,
    "level": "중",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형"
    ],
    "wide": false,
    "content": "[서술형3] $a=\\sqrt{2}, b=-3$일 때, $\\sqrt{4a^{2}+4ab+b^{2}}-\\sqrt{b^{2}}$을 계산하는 과정을 서술하여라. (5점)",
    "choices": [],
    "answer": "$-2\\sqrt{2}$",
    "solution": "[키포인트] 완전제곱식으로 고친 후 절댓값 기호를 사용하여 부호를 판별한다.\\n$\\sqrt{(2a+b)^2} - \\sqrt{b^2} = |2a+b| - |b|$\\n$a=\\sqrt{2}, b=-3$을 대입하면 $2a+b = 2\\sqrt{2}-3 = \\sqrt{8}-\\sqrt{9} < 0$이다.\\n또한 $b=-3<0$이다.\\n따라서 $|2a+b|=-2a-b$, $|b|=-b$이므로 $|2a+b|-|b|=(-2a-b)-(-b)=-2a$이다.\\n$a=\\sqrt{2}$를 대입하면 $-2\\sqrt{2}$이다."
  },
  {
    "id": 24,
    "level": "상",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형"
    ],
    "wide": false,
    "content": "[서술형4] 네 자연수 $a, b, c, d$ 에 대하여 $(ax+b)(cx+d)=4x^{2}+Ax+5$ 일 때, $A$의 값이 될 수 있는 수를 모두 구하는 과정과 답을 쓰시오. (단, $a, b, c, d$는 자연수) [6점]",
    "choices": [],
    "answer": "9, 12, 21",
    "solution": "(1) 식 전개 및 계수 비교\\n$(ax+b)(cx+d) = acx^{2}+(ad+bc)x+bd = 4x^{2}+Ax+5$\\n$ac = 4, bd = 5, A = ad+bc$\\n(2) 가능한 자연수 조합 찾기\\n· $ac=4$인 경우: $(a, c)$는 $(1, 4), (2, 2), (4, 1)$\\n· $bd=5$인 경우: $(b, d)$는 $(1, 5), (5, 1)$\\n(3) $A$의 값 계산\\n· $(a,c)=(1,4), (b,d)=(1,5) \\implies A = 1\\cdot5 + 1\\cdot4 = 9$\\n· $(a,c)=(1,4), (b,d)=(5,1) \\implies A = 1\\cdot1 + 5\\cdot4 = 21$\\n· $(a,c)=(2,2), (b,d)=(1,5) \\implies A = 2\\cdot5 + 1\\cdot2 = 12$\\n· $(a,c)=(2,2), (b,d)=(5,1) \\implies A = 2\\cdot1 + 5\\cdot2 = 12$\\n$\\therefore 9, 12, 21$"
  }
];