window.examTitle = "23_풍덕중_1학기_중간_중3_유사1"

window.questionBank = [
  {
    id: 1,
    category: "제곱근과 실수",
    originalCategory: "제곱근과 실수",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "제곱근에 대한 설명으로 옳은 것을 고르시오. (3점)",
    choices: [
      "0의 제곱근은 존재하지 않는다.",
      "양수의 제곱근은 항상 2개이고 그 합은 0이다.",
      "음수의 제곱근은 양수이다.",
      "16의 제곱근은 4이다.",
      "제곱근 25는 $\\pm 5$이다."
    ],
    answer: "②",
    solution: "[키포인트] 제곱근의 정의와 성질을 이해한다.\\n① $0$의 제곱근은 $0$이다. $\\rightarrow$ 거짓\\n② 양수 $a$의 제곱근은 $\\sqrt{a}$와 $-\\sqrt{a}$이므로 항상 $2$개이며 합은 $0$이다. $\\rightarrow$ 참\\n③ 실수 범위에서 음수의 제곱근은 존재하지 않는다. $\\rightarrow$ 거짓\\n④ $16$의 제곱근은 $4$와 $-4$이다. $\\rightarrow$ 거짓\\n⑤ 제곱근 $25$는 $\\sqrt{25}=5$이다. $\\rightarrow$ 거짓\\n따라서 정답은 ②이다."
  },
  {
    id: 2,
    category: "제곱근과 실수",
    originalCategory: "제곱근과 실수",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "실수와 그 성질에 대한 설명으로 틀린 것은? (3점)",
    choices: [
      "$\\sqrt{4}$는 유리수이다.",
      "무한소수 중에는 유리수인 것도 있다.",
      "$\\sqrt{0.4}$는 무리수이다.",
      "$-\\sqrt{(-5)^{2}}$은 $5$의 음의 제곱근이다.",
      "$\\sqrt{1.\\dot{7}}$은 유리수이다."
    ],
    answer: "④",
    solution: "[키포인트] 유·무리수의 정의와 순환소수의 성질을 파악한다.\\n① $\\sqrt{4}=2$이므로 유리수이다. $\\rightarrow$ 참\\n② 순환하는 무한소수는 유리수이다. $\\rightarrow$ 참\\n③ $\\sqrt{0.4}=\\sqrt{\\frac{4}{10}}=\\frac{2}{\\sqrt{10}}$이므로 무리수이다. $\\rightarrow$ 참\\n④ $-\\sqrt{(-5)^{2}}=-\\sqrt{25}=-5$이다. $5$의 음의 제곱근은 $-\\sqrt{5}$이므로 두 값은 서로 다르다. $\\rightarrow$ 거짓\\n⑤ $\\sqrt{1.\\dot{7}}=\\sqrt{\\frac{16}{9}}=\\frac{4}{3}$이므로 유리수이다. $\\rightarrow$ 참\\n따라서 정답은 ④이다."
  },
  {
    id: 3,
    category: "근호를 포함한 식의 계산",
    originalCategory: "근호를 포함한 식의 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 계산이 옳지 않은 것은? (3점)",
    choices: [
      "$\\sqrt{3}\\times\\sqrt{15}=3\\sqrt{5}$",
      "$\\sqrt{\\frac{24}{3}}\\times\\sqrt{2}=4$",
      "$\\frac{10}{2\\sqrt{5}}=\\sqrt{5}$",
      "$\\frac{\\sqrt{14}}{3}\\div\\frac{\\sqrt{7}}{6}=2\\sqrt{2}$",
      "$\\sqrt{3}\\div\\frac{3}{\\sqrt{6}}=\\frac{\\sqrt{2}}{2}$"
    ],
    answer: "⑤",
    solution: "[키포인트] 제곱근의 곱셈과 나눗셈을 정확히 계산한다.\\n① $\\sqrt{3} \\times \\sqrt{15} = \\sqrt{45} = 3\\sqrt{5}$ $\\rightarrow$ 참\\n② $\\sqrt{\\frac{24}{3}} \\times \\sqrt{2} = \\sqrt{8} \\times \\sqrt{2} = \\sqrt{16} = 4$ $\\rightarrow$ 참\\n③ $\\frac{10}{2\\sqrt{5}} = \\frac{5}{\\sqrt{5}} = \\sqrt{5}$ $\\rightarrow$ 참\\n④ $\\frac{\\sqrt{14}}{3} \\div \\frac{\\sqrt{7}}{6} = \\frac{\\sqrt{14}}{3} \\times \\frac{6}{\\sqrt{7}} = 2\\sqrt{2}$ $\\rightarrow$ 참\\n⑤ $\\sqrt{3} \\div \\frac{3}{\\sqrt{6}} = \\sqrt{3} \\times \\frac{\\sqrt{6}}{3} = \\frac{\\sqrt{18}}{3} = \\frac{3\\sqrt{2}}{3} = \\sqrt{2}$이다. $\\rightarrow$ 거짓\\n따라서 정답은 ⑤이다."
  },
  {
    id: 4,
    category: "근호를 포함한 식의 계산",
    originalCategory: "근호를 포함한 식의 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 계산 중 옳지 않은 것은? (3점)",
    choices: [
      "$6\\div\\sqrt{3}\\times\\sqrt{3}=3$",
      "$(\\sqrt{3}-\\sqrt{24})\\sqrt{6}=3\\sqrt{2}-12$",
      "$\\frac{\\sqrt{7}-2}{\\sqrt{2}}=\\frac{\\sqrt{14}-2\\sqrt{2}}{2}$",
      "$\\sqrt{32}-3\\sqrt{2}=\\sqrt{2}$",
      "$\\frac{2-\\sqrt{8}}{\\sqrt{2}}-4\\div\\sqrt{2}=-2-\\sqrt{2}$"
    ],
    answer: "①",
    solution: "[키포인트] 사칙연산의 순서와 분모의 유리화를 이용한다.\\n① $6 \\div \\sqrt{3} \\times \\sqrt{3} = 6 \\times \\frac{1}{\\sqrt{3}} \\times \\sqrt{3} = 6$이다. $\\rightarrow$ 거짓\\n② $(\\sqrt{3}-\\sqrt{24})\\sqrt{6} = \\sqrt{18} - \\sqrt{144} = 3\\sqrt{2} - 12$ $\\rightarrow$ 참\\n③ $\\frac{\\sqrt{7}-2}{\\sqrt{2}} = \\frac{(\\sqrt{7}-2)\\sqrt{2}}{2} = \\frac{\\sqrt{14}-2\\sqrt{2}}{2}$ $\\rightarrow$ 참\\n④ $\\sqrt{32} - 3\\sqrt{2} = 4\\sqrt{2} - 3\\sqrt{2} = \\sqrt{2}$ $\\rightarrow$ 참\\n⑤ $\\frac{2-\\sqrt{8}}{\\sqrt{2}} - 4 \\div \\sqrt{2} = \\frac{2-2\\sqrt{2}}{\\sqrt{2}} - 2\\sqrt{2} = \\sqrt{2} - 2 - 2\\sqrt{2} = -2 - \\sqrt{2}$ $\\rightarrow$ 참\\n따라서 정답은 ①이다."
  },
  {
    id: 5,
    category: "다항식의 곱셈",
    originalCategory: "다항식의 곱셈",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(x-\\frac{1}{3})(3x+6)$를 전개한 결과로 적절한 것은? (3점)",
    choices: [
      "$3x^{2}+5x+2$",
      "$3x^{2}-5x-2$",
      "$3x^{2}+5x-2$",
      "$-3x^{2}+5x-2$",
      "$3x^{2}-7x-2$"
    ],
    answer: "③",
    solution: "[키포인트] 분배법칙을 사용하여 다항식을 전개한다.\\n$(x-\\frac{1}{3})(3x+6) = 3x^2 + 6x - x - 2 = 3x^2 + 5x - 2$\\n따라서 정답은 ③이다."
  },
  {
    id: 6,
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x^{2}-x-6$의 인수로 적절하지 않은 것은? (3점)",
    choices: [
      "$x+3$",
      "$x-3$",
      "$x+2$",
      "$1$",
      "$x^{2}-x-6$"
    ],
    answer: "①",
    solution: "[키포인트] 다항식을 인수분해하여 개별 인수를 확인한다.\\n$x^2 - x - 6$을 인수분해하면 $(x-3)(x+2)$이다.\\n다항식의 인수는 $1$, $x-3$, $x+2$, $(x-3)(x+2)$이다.\\n주어진 보기 중 $x+3$은 인수가 될 수 없다.\\n따라서 정답은 ①이다."
  },
  {
    id: 7,
    category: "제곱근과 실수",
    originalCategory: "제곱근과 실수",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\sqrt{41-x}$가 정수가 되도록 하는 자연수 $x$의 개수는? (4점)",
    choices: [
      "$4$개",
      "$5$개",
      "$6$개",
      "$7$개",
      "$8$개"
    ],
    answer: "④",
    solution: "[키포인트] 근호 안의 수가 $0$ 또는 완전제곱수가 되어야 함을 이용한다.\\n$\\sqrt{41-x}$가 정수가 되려면 $41-x = k^2$ ($k$는 $0$ 이상의 정수) 꼴이어야 한다.\\n$x$가 자연수이므로 $41-x$는 $0$ 이상 $41$ 미만의 정수이다.\\n$41$보다 작은 $k^2$ 꼴의 정수는 $36, 25, 16, 9, 4, 1, 0$이다.\\n$41-x = 36 \\implies x=5$\\n$41-x = 25 \\implies x=16$\\n$41-x = 16 \\implies x=25$\\n$41-x = 9 \\implies x=32$\\n$41-x = 4 \\implies x=37$\\n$41-x = 1 \\implies x=40$\\n$41-x = 0 \\implies x=41$이다.\\n따라서 조건을 만족하는 자연수 $x$는 $5, 16, 25, 32, 37, 40, 41$로 총 $7$개이다.\\n따라서 정답은 ④이다."
  },
  {
    id: 8,
    category: "제곱근과 실수",
    originalCategory: "제곱근과 실수",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$A=\\sqrt{5}-2, B=1-\\sqrt{5}, C=\\sqrt{3}, D=4-\\sqrt{3}$ 중 가장 작은 수와 큰 수를 차례로 짝지은 것은? (4점)",
    choices: [
      "$A, B$",
      "$D, B$",
      "$B, D$",
      "$A, D$",
      "$B, C$"
    ],
    answer: "③",
    solution: "[키포인트] 제곱근의 근사값을 이용하여 실수의 대소를 비교한다.\\n각 수의 대략적인 값을 비교한다. $\\sqrt{3} \\approx 1.732$, $\\sqrt{5} \\approx 2.236$이다.\\n$A = \\sqrt{5} - 2 \\approx 2.236 - 2 = 0.236$\\n$B = 1 - \\sqrt{5} \\approx 1 - 2.236 = -1.236$\\n$C = \\sqrt{3} \\approx 1.732$\\n$D = 4 - \\sqrt{3} \\approx 4 - 1.732 = 2.268$\\n대소 관계를 비교하면 $B < A < C < D$이다.\\n가장 작은 수는 $B$, 가장 큰 수는 $D$이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 9,
    category: "근호를 포함한 식의 계산",
    originalCategory: "근호를 포함한 식의 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\sqrt{50}\\div\\sqrt{18}\\times\\sqrt{3}=a$일 때 $a$값으로 적절한 것은? (4점)",
    choices: [
      "$\\frac{5\\sqrt{3}}{3}$",
      "$\\frac{5\\sqrt{2}}{3}$",
      "$\\frac{25}{9}$",
      "$\\frac{5}{3\\sqrt{3}}$",
      "$3\\sqrt{3}$"
    ],
    answer: "①",
    solution: "[키포인트] 근호 밖으로 꺼낼 수 있는 수를 먼저 정리한 후 계산한다.\\n좌변을 계산하면 다음과 같다.\\n$\\sqrt{50} \\div \\sqrt{18} \\times \\sqrt{3} = 5\\sqrt{2} \\div 3\\sqrt{2} \\times \\sqrt{3} = \\frac{5\\sqrt{2}}{3\\sqrt{2}} \\times \\sqrt{3} = \\frac{5}{3}\\sqrt{3} = \\frac{5\\sqrt{3}}{3}$\\n따라서 $a = \\frac{5\\sqrt{3}}{3}$이다.\\n따라서 정답은 ①이다."
  },
  {
    id: 10,
    category: "근호를 포함한 식의 계산",
    originalCategory: "근호를 포함한 식의 계산",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\frac{\\sqrt{5}+2}{\\sqrt{5}-2}-\\frac{\\sqrt{5}-2}{\\sqrt{5}+2}=a+b\\sqrt{5}$일 때, 유리수 $a+b$의 값으로 적절한 것은? (4점)",
    choices: [
      "$4$",
      "$8$",
      "$-8$",
      "$16$",
      "$0$"
    ],
    answer: "②",
    solution: "[키포인트] 통분 또는 각각의 유리화를 통해 식을 정리한다.\\n주어진 식을 통분하여 계산한다.\\n$\\frac{(\\sqrt{5}+2)^2 - (\\sqrt{5}-2)^2}{(\\sqrt{5}-2)(\\sqrt{5}+2)}$\\n$= \\frac{(9 + 4\\sqrt{5}) - (9 - 4\\sqrt{5})}{5 - 4} = \\frac{8\\sqrt{5}}{1} = 8\\sqrt{5}$\\n따라서 $a = 0, b = 8$이다.\\n$a + b = 0 + 8 = 8$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 11,
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 두 다항식의 공통인수가 아닌 것은? (4점)<br>$(x-2)(x^{2}-x-12)$와 $(x-4)(3x^{2}+3x-18)$",
    choices: [
      "$x-2$",
      "$x-4$",
      "$x+3$",
      "$x^{2}-x-12$",
      "$x+4$"
    ],
    answer: "⑤",
    solution: "[키포인트] 각각의 다항식을 완전히 인수분해하여 인수를 비교한다.\\n첫 번째 식:\\n$(x-2)(x^2-x-12) = (x-2)(x-4)(x+3)$\\n두 번째 식:\\n$(x-4)(3x^2+3x-18) = 3(x-4)(x^2+x-6) = 3(x-4)(x+3)(x-2)$\\n두 다항식의 공통인수는 $1, x-2, x-4, x+3$ 및 이들의 곱이다.\\n④ $x^2-x-12=(x-4)(x+3)$이므로 공통인수이다.\\n보기 중 $x+4$는 공통인수가 아니다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 12,
    category: "다항식의 곱셈",
    originalCategory: "다항식의 곱셈",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(\\sqrt{10}-3)^{5}(\\sqrt{10}+3)^{5}$의 값으로 적절한 것은? (4점)",
    choices: [
      "$-1$",
      "$1$",
      "$5$",
      "$10$",
      "$-5$"
    ],
    answer: "②",
    solution: "[키포인트] 지수법칙과 합차 공식을 이용한다.\\n지수법칙 $a^n b^n = (ab)^n$을 이용한다.\\n$(\\sqrt{10}-3)^{5}(\\sqrt{10}+3)^{5}=((\\sqrt{10}-3)(\\sqrt{10}+3))^5$\\n합차 공식을 적용하면,\\n$= ((\\sqrt{10})^2 - 3^2)^5 = (10 - 9)^5 = 1^5 = 1$\\n따라서 정답은 ②이다."
  },
  {
    id: 13,
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 $\\Box$ 안의 수가 가장 큰 것은? (4점)",
    choices: [
      "$(3x+2)^{2}=\\Box x^{2}+12x+4$",
      "$(x-3)^{2}=x^{2}+\\Box x+9$",
      "$(x+4)(x-4)=x^{2}+\\Box$",
      "$(3x+2)(x+1)=3x^{2}+\\Box x+2$",
      "$(2x-3)(4x+5)=8x^{2}-2x-\\Box$"
    ],
    answer: "⑤",
    solution: "[키포인트] 곱셈공식을 이용하여 각 식을 전개하고 계수를 비교한다.\\n① $(3x+2)^2 = 9x^2+12x+4 \\rightarrow \\Box = 9$\\n② $(x-3)^2 = x^2-6x+9 \\rightarrow \\Box = -6$\\n③ $(x+4)(x-4) = x^2-16 \\rightarrow \\Box = -16$\\n④ $(3x+2)(x+1) = 3x^2+5x+2 \\rightarrow \\Box = 5$\\n⑤ $(2x-3)(4x+5) = 8x^2-2x-15 \\rightarrow \\Box = 15$이다.\\n따라서 $\\Box$ 안의 수가 가장 큰 것은 $15$인 ⑤이다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 14,
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "완전제곱식이 아닌 것은? (4점)",
    choices: [
      "$16a^{2}-24ax+9x^{2}$",
      "$x^{2}-10x+25$",
      "$4x^{2}-12x+16$",
      "$2a^{2}+8a+8$",
      "$x^{2}-6x+9$"
    ],
    answer: "③",
    solution: "[키포인트] $(A \\pm B)^2$ 꼴로 인수분해되는지 확인한다.\\n① $16a^2-24ax+9x^2 = (4a-3x)^2$이므로 완전제곱식이다.\\n② $x^2-10x+25 = (x-5)^2$이므로 완전제곱식이다.\\n③ $4x^2-12x+16$은 $4x^2=(2x)^2$, $16=4^2$이지만 가운데 항은 $\\pm 2\\cdot 2x\\cdot 4=\\pm16x$이어야 한다. 실제 가운데 항은 $-12x$이므로 완전제곱식이 아니다.\\n④ $2a^2+8a+8 = 2(a^2+4a+4) = 2(a+2)^2$이므로 완전제곱식의 상수배 형태이다.\\n⑤ $x^2-6x+9=(x-3)^2$이므로 완전제곱식이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 15,
    category: "다항식의 곱셈",
    originalCategory: "다항식의 곱셈",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a+b=4, a^{2}+b^{2}=10$일 때 $a-b$의 값으로 적절한 것은? (5점)",
    choices: [
      "$\\pm 1$",
      "$-2$",
      "$\\pm 2$",
      "$\\pm \\sqrt{2}$",
      "$2$"
    ],
    answer: "③",
    solution: "[키포인트] 곱셈공식의 변형 $(a-b)^2 = (a+b)^2 - 4ab$를 이용한다.\\n$a^2+b^2 = (a+b)^2 - 2ab$이므로\\n$10 = 4^2 - 2ab \\implies 10 = 16 - 2ab \\implies 2ab = 6 \\implies ab = 3$\\n$(a-b)^2 = (a+b)^2 - 4ab = 4^2 - 4(3) = 16 - 12 = 4$\\n따라서 $a-b = \\pm 2$이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 16,
    category: "다항식의 곱셈",
    originalCategory: "다항식의 곱셈",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x+\\frac{1}{x}=6$이고 $0<x<1$일 때 $x-\\frac{1}{x}$의 값은? (5점)",
    choices: [
      "$\\pm 4\\sqrt{2}$",
      "$4\\sqrt{2}$",
      "$-4\\sqrt{2}$",
      "$-4\\sqrt{3}$",
      "$\\pm 4\\sqrt{3}$"
    ],
    answer: "③",
    solution: "[키포인트] $(x-\\frac{1}{x})^2 = (x+\\frac{1}{x})^2 - 4$ 공식을 이용한다.\\n$(x-\\frac{1}{x})^2 = (x+\\frac{1}{x})^2 - 4 = 6^2 - 4 = 32$\\n따라서 $x - \\frac{1}{x} = \\pm \\sqrt{32} = \\pm 4\\sqrt{2}$이다.\\n조건에서 $0 < x < 1$이므로, $\\frac{1}{x} > 1$이고 $x < \\frac{1}{x}$이다.\\n즉, $x - \\frac{1}{x} < 0$이어야 한다.\\n따라서 $x - \\frac{1}{x} = -4\\sqrt{2}$이다.\\n따라서 정답은 ③이다."
  },
  {
    id: 17,
    category: "다항식의 곱셈",
    originalCategory: "다항식의 곱셈",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(2+1)(2^{2}+1)(2^{4}+1)=a$일 때 $\\frac{a}{17}$의 값으로 적절한 것은? (5점)",
    choices: [
      "$14$",
      "$15$",
      "$16$",
      "$17$",
      "$31$"
    ],
    answer: "②",
    solution: "[키포인트] $(2-1)$을 곱하여 합차 공식을 연속적으로 적용한다.\\n$(2-1)(2+1)(2^2+1)(2^4+1) = a \\times (2-1) = a$\\n$(2^2-1)(2^2+1)(2^4+1) = a$\\n$(2^4-1)(2^4+1) = a \\implies 2^8 - 1 = a$\\n$\\frac{a}{17} = \\frac{2^8-1}{17} = \\frac{(2^4-1)(2^4+1)}{17} = \\frac{15 \\times 17}{17} = 15$\\n따라서 정답은 ②이다."
  },
  {
    id: 18,
    category: "제곱근과 실수",
    originalCategory: "제곱근과 실수",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$1 < x < 2$일 때, $\\sqrt{x^{2}}+\\sqrt{(x-1)^{2}}-\\sqrt{(x-2)^{2}}-\\sqrt{(x-3)^{2}}$을 간단히 나타낸 식으로 적절한 것은? (5점)",
    choices: [
      "$2x-4$",
      "$4x-6$",
      "$4x-4$",
      "$-2x+4$",
      "$2x+4$"
    ],
    answer: "②",
    solution: "[키포인트] $\\sqrt{A^2} = |A|$임을 이용하여 근호 안의 식의 부호를 판별한다.\\n$1 < x < 2$이므로:\\n$x > 0 \\implies \\sqrt{x^2} = x$\\n$x - 1 > 0 \\implies \\sqrt{(x-1)^2} = x-1$\\n$x - 2 < 0 \\implies \\sqrt{(x-2)^2} = -(x-2) = -x+2$\\n$x - 3 < 0 \\implies \\sqrt{(x-3)^2} = -(x-3) = -x+3$\\n식에 대입하면 $x + (x-1) - (-x+2) - (-x+3) = x + x - 1 + x - 2 + x - 3 = 4x - 6$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 19,
    category: "다항식의 곱셈",
    originalCategory: "다항식의 곱셈",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a=\\frac{3}{\\sqrt{12}+3}, b=\\frac{3}{\\sqrt{12}-3}$일 때 $a^{2}-4ab+b^{2}$의 값으로 적절한 것은? (5점)",
    choices: [
      "$24$",
      "$28$",
      "$30$",
      "$32$",
      "$36$"
    ],
    answer: "③",
    solution: "[키포인트] $a, b$를 유리화한 후 곱셈공식의 변형을 이용한다.\\n$a = \\frac{3(2\\sqrt{3}-3)}{12-9} = 2\\sqrt{3}-3$\\n$b = \\frac{3(2\\sqrt{3}+3)}{12-9} = 2\\sqrt{3}+3$\\n$a+b = 4\\sqrt{3}, ab = (2\\sqrt{3})^2 - 3^2 = 12-9=3$\\n$a^2 - 4ab + b^2 = (a+b)^2 - 6ab = (4\\sqrt{3})^2 - 6(3) = 48 - 18 = 30$\\n따라서 정답은 ③이다."
  },
  {
    id: 20,
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$A=(x-2)(x)(x+2)(x+4)-9$일 때 다항식 $A$의 인수로 적절하지 않은 것은? (5점)",
    choices: [
      "$1$",
      "$x+1$",
      "$x-3$",
      "$x^{2}+2x-9$",
      "$(x+1)^{2}$"
    ],
    answer: "③",
    solution: "[키포인트] 공통부분이 생기도록 두 개씩 짝지어 전개한 후 치환하여 인수분해한다.\\n$A = \\{(x-2)(x+4)\\} \\times \\{x(x+2)\\} - 9 = (x^2+2x-8)(x^2+2x) - 9$\\n$x^2+2x = t$로 치환하면, $(t-8)t - 9 = t^2 - 8t - 9 = (t-9)(t+1)$이다.\\n원래 식을 대입하면 $(x^2+2x-9)(x^2+2x+1) = (x^2+2x-9)(x+1)^2$이다.\\n인수는 $1, x+1, (x+1)^2, x^2+2x-9$ 등이다. $x-3$은 인수가 아니다.\\n따라서 정답은 ③이다."
  },
  {
    id: 21,
    category: "제곱근과 실수",
    originalCategory: "제곱근과 실수",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "[서술형1] 다음 수 $a, b, c$의 크기를 비교하는 과정을 서술하여라. (5점)<br>$a=-\\frac{3}{2}\\sqrt{5}, b=-4, c=-7+\\sqrt{20}$",
    choices: [],
    answer: "$b < a < c$",
    solution: "[키포인트] 각 수를 근호 안으로 넣어 크기를 비교하거나 차를 이용한다.\\n$a = -\\sqrt{(\\frac{3}{2})^2 \\times 5} = -\\sqrt{11.25}$\\n$b = -\\sqrt{16}$\\n$16 > 11.25$이므로 $b < a$이다.\\n$c = -7 + 2\\sqrt{5} = -\\sqrt{49} + \\sqrt{20} \\approx -7 + 4.47 = -2.53$\\n$a = -\\sqrt{11.25} \\approx -3.35$\\n$b = -4$\\n따라서 $b < a < c$이다."
  },
  {
    id: 22,
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "[서술형2] $x^{2}+xy-2y^{2}+3x+9y-4$를 두 일차식의 곱으로 인수분해하는 과정을 서술하여라. (5점)",
    choices: [],
    answer: "$(x+2y-1)(x-y+4)$",
    solution: "[키포인트] 한 문자에 대하여 내림차순으로 정리한 후 인수분해한다.\\n$x$에 대하여 내림차순 정리: $x^2 + (y+3)x - (2y^2-9y+4)$\\n상수항 인수분해: $2y^2-9y+4 = (2y-1)(y-4)$\\n식에 대입하면 $x^2 + (y+3)x - (2y-1)(y-4)$이다.\\n곱해서 $-(2y-1)(y-4)$, 더해서 $(y+3)$이 되는 두 식은 $(2y-1)$과 $-(y-4)$이다.\\n따라서 $(x + 2y - 1)(x - (y - 4)) = (x+2y-1)(x-y+4)$이다."
  },
  {
    id: 23,
    category: "다항식의 곱셈",
    originalCategory: "다항식의 곱셈",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-02",
    standardUnit: "다항식의 곱셈과 인수분해",
    standardUnitOrder: 2,
    level: "중",
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "[서술형3] $a=\\sqrt{2}, b=-3$일 때, $\\sqrt{4a^{2}+4ab+b^{2}}-\\sqrt{b^{2}}$을 계산하는 과정을 서술하여라. (5점)",
    choices: [],
    answer: "$-2\\sqrt{2}$",
    solution: "[키포인트] 완전제곱식으로 고친 후 절댓값 기호를 사용하여 부호를 판별한다.\\n$\\sqrt{(2a+b)^2} - \\sqrt{b^2} = |2a+b| - |b|$\\n$a=\\sqrt{2}, b=-3$을 대입하면 $2a+b = 2\\sqrt{2}-3 = \\sqrt{8}-\\sqrt{9} < 0$이다.\\n또한 $b=-3<0$이다.\\n따라서 $|2a+b|=-2a-b$, $|b|=-b$이므로 $|2a+b|-|b|=(-2a-b)-(-b)=-2a$이다.\\n$a=\\sqrt{2}$를 대입하면 $-2\\sqrt{2}$이다."
  },
  {
    id: 24,
    category: "제곱근과 실수",
    originalCategory: "제곱근과 실수",
    standardCourse: "중3 수학",
    standardUnitKey: "M3-01",
    standardUnit: "실수와 그 계산",
    standardUnitOrder: 1,
    level: "중",
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "[서술형4] $\\sqrt{\\frac{2}{7}x}$가 자연수가 되는 가장 작은 자연수 $x$값을 $a$, $8$번째로 작은 자연수 $x$값을 $b$라고 할 때, $a, b$의 값을 구하는 과정을 서술하여라. (5점)",
    choices: [],
    answer: "$a=14, b=896$",
    solution: "[키포인트] 근호 안의 수가 (자연수)$^2$ 꼴이 되도록 하는 $x$를 찾는다.\\n$\\frac{2}{7}x = k^2$ ($k$는 자연수) 꼴이어야 하므로 $x = \\frac{7k^2}{2}$이다.\\n$x$가 자연수가 되려면 $k$는 짝수여야 하므로 $k=2m$ ($m$은 자연수)으로 둔다.\\n그러면 $x=\\frac{7(2m)^2}{2}=14m^2$이다.\\n가장 작은 자연수 $a$는 $m=1$일 때이므로 $a = 14 \\times 1^2 = 14$이다.\\n$8$번째로 작은 자연수 $b$는 $m=8$일 때이므로 $b = 14 \\times 8^2 = 14 \\times 64 = 896$이다.\\n따라서 $a=14, b=896$이다."
  }
];