window.examTitle = "24_제일고_1학기_중간_고1_수학";

window.questionBank = [
  {
    id: 1,
    level: "하",
    category: "복소수",
    originalCategory: "복소수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수",
    standardUnitOrder: 4,
    content: "두 실수 $x, y$에 대하여 $-2+3i = x+(y+5)i$일 때, $x+y$의 값은? (단, $i=\\sqrt{-1}$)",
    choices: ["① $-4$", "② $-2$", "③ $0$", "④ $2$", "⑤ $4$"],
    answer: "①",
    solution: "[키포인트]\\n복소수가 서로 같을 조건을 이용하여 실수부분과 허수부분을 각각 비교한다.\\n\\n조건 정리\\n- 좌변: $-2+3i$\\n- 우변: $x+(y+5)i$\\n\\n풀이 과정\\n복소수 상등의 정리에 의해 실수부분은 실수부분끼리, 허수부분은 허수부분끼리 같아야 한다.\\n$-2 = x \\implies x = -2$\\n$3 = y+5 \\implies y = -2$\\n따라서 $x+y = -2 + (-2) = -4$이다.\\n\\n결론\\n따라서 구하는 값은 $-4$이다."
  },
  {
    id: 2,
    level: "하",
    category: "나머지 정리",
    originalCategory: "나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "나머지 정리",
    standardUnitOrder: 2,
    content: "다항식 $x^3+2x^2+x-3$을 $x-1$로 나눈 나머지는?",
    choices: ["① $1$", "② $2$", "③ $3$", "④ $4$", "⑤ $5$"],
    answer: "①",
    solution: "[키포인트]\\n나머지 정리를 이용하여 다항식에 일차식을 $0$으로 만드는 값을 대입한다.\\n\\n조건 정리\\n- 다항식 $P(x) = x^3+2x^2+x-3$\\n- 나누는 식: $x-1$\\n\\n풀이 과정\\n나머지 정리에 의해 $P(x)$를 $x-1$로 나눈 나머지는 $P(1)$이다.\\n$P(1) = 1^3 + 2(1)^2 + 1 - 3 = 1+2+1-3 = 1$\\n\\n결론\\n따라서 정답은 ①이다."
  },
  {
    id: 3,
    level: "중",
    category: "다항식의 연산",
    originalCategory: "다항식의 연산",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-01",
    standardUnit: "다항식의 연산",
    standardUnitOrder: 1,
    content: "$x-y=2, x^3-y^3=20$일 때, $xy$의 값은?",
    choices: ["① $1$", "② $2$", "③ $3$", "④ $4$", "⑤ $5$"],
    answer: "②",
    solution: "[키포인트]\\n곱셈 공식의 변형을 이용하여 주어진 값들로부터 $xy$를 추출한다.\\n\\n조건 정리\\n- $x-y = 2$\\n- $x^3-y^3 = 20$\\n\\n풀이 과정\\n$x^3-y^3 = (x-y)^3 + 3xy(x-y)$ 공식을 활용한다.\\n주어진 값을 대입하면 $20 = 2^3 + 3xy(2)$이다.\\n$20 = 8 + 6xy \\implies 12 = 6xy \\implies xy = 2$\\n\\n결론\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 4,
    level: "중",
    category: "복소수",
    originalCategory: "복소수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수",
    standardUnitOrder: 4,
    content: "$20+19i+18i^2+17i^3+\\dots+2i^{18}+i^{19}=a+bi$일 때, $a+b$의 값은? (단, $a, b$는 실수이고 $i=\\sqrt{-1}$이다.)",
    choices: ["① $10$", "② $15$", "③ $20$", "④ $25$", "⑤ $30$"],
    answer: "③",
    solution: "[키포인트]\\n허수단위 $i$의 거듭제곱의 주기성($i^4=1$)과 연속된 4개 항의 합의 특징을 이용한다.\\n\\n조건 정리\\n- 총 20개의 항이 나열되어 있다.\\n- $i, i^2, i^3, i^4, \\dots$ 순서로 거듭제곱이 반복된다.\\n\\n풀이 과정\\n4개 항씩 묶어서 계산하면 다음과 같다.\\n$(20 + 19i + 18i^2 + 17i^3) = 20 + 19i - 18 - 17i = 2 + 2i$\\n그다음 4개 항인 $(16i^4 + 15i^5 + 14i^6 + 13i^7)$ 역시 $16 + 15i - 14 - 13i = 2 + 2i$가 된다.\\n이러한 묶음이 총 5번 반복되므로 $a+bi = 5(2+2i) = 10+10i$이다.\\n따라서 $a=10, b=10$이므로 $a+b=20$이다.\\n\\n결론\\n따라서 정답은 ③이다."
  },
  {
    id: 5,
    level: "중",
    category: "복소수",
    originalCategory: "복소수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수",
    standardUnitOrder: 4,
    content: "복소수 $z$에 대하여 다음 <보기> 중 옳은 것의 개수는? (단, $\\bar{z}$는 $z$의 켤레복소수이다.)\\n\\n<보기>\\n가) $z = -\\bar{z}$이면 $z$는 순허수이다.\\n나) $z + \\bar{z}$는 항상 실수이다.\\n다) $z^2$이 허수이면 $z$도 허수이다.\\n라) $\\bar{z} = z$이면 $z$는 실수이다.\\n마) $z^2 \\ge 0$이면 $z$는 실수이다.",
    choices: ["① 1개", "② 2개", "③ 3개", "④ 4개", "⑤ 5개"],
    answer: "④",
    solution: "[키포인트]\\n복소수 $z=a+bi$의 정의와 성질을 하나씩 대조하여 참과 거짓을 판별한다.\\n\\n조건 정리\\n- $z = a+bi, \\bar{z} = a-bi$ ($a, b$는 실수)\\n\\n풀이 과정\\n가) $a+bi = -a+bi \\implies a=0$. 이때 $b=0$이면 $z=0$으로 실수가 될 수 있으므로 틀렸다.\\n나) $(a+bi) + (a-bi) = 2a$ (실수). 옳다.\\n다) 실수의 제곱은 항상 실수이므로, 제곱이 허수라면 $z$는 반드시 허수여야 한다. 옳다.\\n라) $a+bi = a-bi \\implies 2bi = 0 \\implies b=0$. 실수이다. 옳다.\\n마) 제곱하여 0 이상인 복소수는 실수뿐이다. 옳다.\\n따라서 옳은 것은 나, 다, 라, 마 4개이다.\\n\\n결론\\n따라서 정답은 ④이다."
  },
  {
    id: 6,
    level: "중",
    category: "복소수",
    originalCategory: "복소수",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-04",
    standardUnit: "복소수",
    standardUnitOrder: 4,
    content: "복소수 $z=1+i$에 대하여 $z\\bar{z} + \\left(\\frac{1}{z} + \\frac{1}{\\bar{z}}\\right)$의 값은?",
    choices: ["① $1$", "② $2$", "③ $3$", "④ $4$", "⑤ $5$"],
    answer: "③",
    solution: "[키포인트]\\n주어진 복소수와 그 켤레복소수의 합과 곱을 먼저 계산하여 대입한다.\\n\\n조건 정리\\n- $z = 1+i, \\bar{z} = 1-i$\\n\\n풀이 과정\\n$z\\bar{z} = (1+i)(1-i) = 1 - i^2 = 2$\\n$\\frac{1}{z} + \\frac{1}{\\bar{z}} = \\frac{\\bar{z}+z}{z\\bar{z}} = \\frac{2}{2} = 1$\\n따라서 $2+1=3$이다.\\n\\n결론\\n따라서 정답은 ③이다."
  },
  {
    id: 7,
    level: "중",
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-03",
    standardUnit: "인수분해",
    standardUnitOrder: 3,
    content: "$x^4+2x^2-x+1 = (x^2+ax+b)(x^2+cx+d)$일 때, $a+b+c+d$의 값은? (단, $a, b, c, d$는 실수이다.)",
    choices: ["① $1$", "② $2$", "③ $3$", "④ $4$", "⑤ $5$"],
    answer: "[정답불가]",
    solution: "[키포인트]\\n계수 비교법을 사용하여 미지수들 사이의 관계식을 유도한다.\\n\\n조건 정리\\n- $x^4 + 2x^2 - x + 1 = x^4 + (a+c)x^3 + (ac+b+d)x^2 + (ad+bc)x + bd$\\n\\n풀이 과정\\n양변의 계수를 비교하면 $a+c=0 \\implies c=-a$이다.\\n이차항 계수: $ac+b+d = -a^2+b+d = 2$\\n일차항 계수: $ad+bc = a(d-b) = -1$\\n상수항: $bd=1$\\n이 식을 연립하여 $a, b, c, d$를 구하면 실수 범위에서 모순이 발생하여 단일 정답을 확정할 수 없다.\\n\\n결론\\n따라서 정답은 [정답불가]이다."
  },
  {
    id: 8,
    level: "상",
    category: "나머지 정리",
    originalCategory: "나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "나머지 정리",
    standardUnitOrder: 2,
    content: "삼차다항식 $P(x)$가 $(x+1)^2$으로 나누면 나머지가 $x+7$이고, $(x-1)(x-2)$로 나누어 떨어질 때, $P(0)$의 값은?",
    choices: ["① 1", "② 2", "③ 3", "④ 4", "⑤ 5"],
    answer: "④",
    solution: "[키포인트]\\n삼차다항식을 이차식의 완전제곱식으로 나눈 검산식을 세우고, 인수정리를 통해 미지수를 결정한다.\\n\\n조건 정리\\n- $P(x)$는 삼차식이다.\\n- $P(x) = (x+1)^2 Q(x) + x+7$\\n- $P(1) = 0, P(2) = 0$\\n\\n풀이 방향 설정\\n$Q(x)$는 일차식이므로 $ax+b$로 둔다. 나머지 조건인 $P(1)=0, P(2)=0$을 대입하여 연립방정식을 만든 뒤 $a, b$를 구한다.\\n\\n풀이 과정\\n1) $P(x) = (x+1)^2 (ax+b) + x+7$로 설정한다.\\n2) $P(1) = 4(a+b) + 8 = 0 \\implies a+b = -2$\\n3) $P(2) = 9(2a+b) + 9 = 0 \\implies 2a+b = -1$\\n4) 두 식을 연립하면 $a=1, b=-3$이다.\\n5) 완성된 식은 $P(x) = (x+1)^2 (x-3) + x+7$이다.\\n6) $P(0) = (1)^2 (-3) + 7 = 4$이다.\\n\\n결론\\n따라서 구하는 값은 4이다."
  },
  {
    id: 9,
    level: "중",
    category: "나머지 정리",
    originalCategory: "나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "나머지 정리",
    standardUnitOrder: 2,
    content: "다항식 $P(x)$를 $x^2+2x+3$으로 나눈 몫이 $x^2+2x+3$이고 나머지가 $x+2$일 때, $P(1)$의 값은?",
    choices: ["① $33$", "② $36$", "③ $39$", "④ $42$", "⑤ $45$"],
    answer: "③",
    solution: "[키포인트]\\n다항식의 나눗셈 관계를 검산식으로 표현하고 특정 값을 대입한다.\\n\\n조건 정리\\n- $P(x) = (x^2+2x+3)(x^2+2x+3) + x+2$\\n\\n풀이 과정\\n$P(1)$을 구하기 위해 $x=1$을 대입한다.\\n$P(1) = (1+2+3)(1+2+3) + 1+2 = 6 \\times 6 + 3 = 39$이다.\\n\\n결론\\n따라서 정답은 ③이다."
  },
  {
    id: 10,
    level: "하",
    category: "평면좌표",
    originalCategory: "평면좌표",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "좌표평면 위의 두 점 $A(-3, 2), B(1, -4)$ 사이의 거리를 구하면?",
    choices: ["① $\\sqrt{2}$", "② $2\\sqrt{13}$", "③ $2\\sqrt{10}$", "④ $5\\sqrt{2}$", "⑤ $7$"],
    answer: "②",
    solution: "[키포인트]\\n두 점 사이의 거리 공식을 적용하여 계산한다.\\n\\n조건 정리\\n- $A(-3, 2), B(1, -4)$\\n\\n풀이 과정\\n$AB = \\sqrt{(1 - (-3))^2 + (-4-2)^2} = \\sqrt{4^2 + (-6)^2} = \\sqrt{16+36} = \\sqrt{52}$\\n$\\sqrt{52} = 2\\sqrt{13}$이다.\\n\\n결론\\n따라서 정답은 ②이다."
  },
  {
    id: 11,
    level: "중",
    category: "평면좌표",
    originalCategory: "평면좌표",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "두 점 $A(3, 5), B(-5, -1)$를 이은 선분 $AB$의 4등분점 중에서 $B$에 가장 가까운 점의 좌표는?",
    choices: ["① $(-3, 2)$", "② $(-6, 4)$", "③ $(-3, \\frac{1}{2})$", "④ $(6, -4)$", "⑤ $(3, -2)$"],
    answer: "③",
    solution: "[키포인트]\\n선분의 4등분점 중 $B$에 가장 가까운 점의 내분 비율을 찾는다.\\n\\n조건 정리\\n- 전체 4등분 중 $B$에 가장 가까운 점은 $A$로부터 3, $B$로부터 1의 비율이다.\\n\\n풀이 과정\\n선분 $AB$를 $3:1$로 내분하는 점을 구한다.\\n$x = \\frac{3(-5) + 1(3)}{3+1} = -3$\\n$y = \\frac{3(-1) + 1(5)}{3+1} = \\frac{2}{4} = \\frac{1}{2}$\\n따라서 점의 좌표는 $(-3, \\frac{1}{2})$이다.\\n\\n결론\\n따라서 정답은 ③이다."
  },
  {
    id: 12,
    level: "중",
    category: "평면좌표",
    originalCategory: "평면좌표",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "[도형필요]\\n선분 $AB$를 6등분하는 점을 $C, D, E, F, G$라 할 때 다음 중 옳은 것은? (단, 점의 순서는 $A-C-D-E-F-G-B$이다.)",
    choices: [
      "① 선분 $DE$를 $1:2$로 외분하는 점은 $F$이다.",
      "② 선분 $AG$를 $2:3$으로 내분하는 점은 $E$이다.",
      "③ 선분 $BA$를 $1:2$로 내분하는 점은 $D$이다.",
      "④ 선분 $FG$를 $3:4$로 외분하는 점은 $C$이다.",
      "⑤ 선분 $FE$를 $2:1$로 외분하는 점은 $G$이다."
    ],
    answer: "④",
    solution: "[키포인트]\\n내분점과 외분점의 정의를 선분의 칸 수 비율로 확인한다.\\n\\n조건 정리\\n- $A$에서 $B$까지 6칸으로 나뉘어 있다.\\n- 각 칸의 길이를 1로 간주한다.\\n\\n풀이 과정\\n④번 보기를 확인하면, $FG$의 길이는 1이다. $C$에서 $F$까지 거리는 3이고, $C$에서 $G$까지 거리는 4이다. 따라서 $C$는 선분 $FG$를 $3:4$로 외분하는 점이 맞다.\\n\\n결론\\n따라서 정답은 ④이다."
  },
  {
    id: 13,
    level: "중",
    category: "평면좌표",
    originalCategory: "평면좌표",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "좌표평면 위의 점 $P(x, y)$와 두 점 $A(-2, -5), B(4, 1)$에 대하여 $PA+PB$의 최솟값은?",
    choices: ["① $3\\sqrt{6}$", "② $6\\sqrt{2}$", "③ $6\\sqrt{3}$", "④ $46$", "⑤ $57$"],
    answer: "②",
    solution: "[키포인트]\\n두 점 사이의 거리의 합이 최소가 되는 지점은 두 점을 잇는 선분 위이다.\\n\\n조건 정리\\n- 최솟값은 선분 $AB$의 길이와 같다.\\n\\n풀이 과정\\n$AB = \\sqrt{(4 - (-2))^2 + (1 - (-5))^2} = \\sqrt{6^2 + 6^2} = \\sqrt{72} = 6\\sqrt{2}$이다.\\n\\n결론\\n따라서 정답은 ②이다."
  },
  {
    id: 14,
    level: "중",
    category: "직선의 방정식",
    originalCategory: "직선의 방정식",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "직선 $(k+1)x + (2-k)y - 3 = 0$에 대한 설명으로 옳은 것만을 <보기>에서 고른 것은?\\n\\n<보기>\\nㄱ. $k=-1$이면 기울기가 0이다.\\nㄴ. $k=0$이면 직선 $4x-2y-3=0$과 수직이다.\\nㄷ. $k$의 값에 관계없이 항상 점 $(1, 1)$을 지난다.\\nㄹ. $k=1$이면 직선 $6x-3y-1=0$과 평행이다.",
    choices: ["① ㄱ, ㄴ", "② ㄱ, ㄷ", "③ ㄴ, ㄹ", "④ ㄱ, ㄴ, ㄷ", "⑤ ㄴ, ㄷ, ㄹ"],
    answer: "④",
    solution: "[키포인트]\\n직선의 방정식에 $k$를 대입하거나 항등식 성질을 이용한다.\\n\\n조건 정리\\n- ㄱ: $k=-1 \\implies 3y-3=0 \\implies y=1$. 기울기 0이다. (참)\\n- ㄴ: $k=0 \\implies x+2y-3=0$. 기울기는 $-1/2$이다. $4x-2y-3=0$의 기울기는 2이므로 수직이다. (참)\\n- ㄷ: $x+y-3 + k(x-y) = 0$ 꼴로 정리하면 $x=1, y=1$일 때 성립한다. (참)\\n\\n풀이 과정\\nㄱ, ㄴ, ㄷ이 모두 참이므로 정답은 ④이다.\\n\\n결론\\n따라서 정답은 ④이다."
  },
  {
    id: 15,
    level: "중",
    category: "직선의 방정식",
    originalCategory: "직선의 방정식",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "직선 $ax-y+4=0$이 직선 $bx+3y-5=0$에 수직이고, 직선 $(b+1)x+y-1=0$에는 평행할 때, 상수 $a, b$에 대하여 $a^3+b^3$의 값은?",
    choices: ["① $-30$", "② $30$", "③ $-28$", "④ $28$", "⑤ $29$"],
    answer: "[정답불가]",
    solution: "[키포인트]\\n수직 조건($m_1 m_2 = -1$)과 평행 조건($m_1 = m_2$)을 활용하여 연립한다.\\n\\n조건 정리\\n- 수직: $a \\cdot b + (-1) \\cdot 3 = 0 \\implies ab = 3$\\n- 평행: $a = -(b+1) \\implies a+b = -1$\\n\\n풀이 과정\\n$a^3+b^3 = (a+b)^3 - 3ab(a+b) = (-1)^3 - 3(3)(-1) = 8$이다. 계산 결과인 8이 보기 내에 존재하지 않는다.\\n\\n결론\\n따라서 정답은 [정답불가]이다."
  },
  {
    id: 16,
    level: "상",
    category: "직선의 방정식",
    originalCategory: "직선의 방정식",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "두 직선 $3x+4y-1=0, 2x+y-4=0$의 교점을 지나는 직선 중 점 $(2, 1)$에서 거리가 최대인 직선의 방정식은?",
    choices: ["① $x-3y-9=0$", "② $x+3y+3=0$", "③ $x-y-11=0$", "④ $x+2y+1=0$", "⑤ $2x-y-8=0$"],
    answer: "①",
    solution: "[키포인트]\\n한 정점을 지나는 직선과 외부의 한 점 사이의 거리가 최대일 조건은 두 점을 잇는 선분이 직선과 수직일 때이다.\\n\\n조건 정리\\n- 정점 $A$는 두 직선의 교점이다.\\n- 외부의 점 $P(2, 1)$이다.\\n\\n풀이 방향 설정\\n교점 $A$를 먼저 구한 뒤, 선분 $AP$에 수직이면서 점 $A$를 지나는 직선을 유도한다.\\n\\n풀이 과정\\n1) 교점 구하기: $3x+4y-1=0$과 $2x+y-4=0$을 연립하면 $x=3, y=-2$이다. 즉 $A(3, -2)$이다.\\n2) 선분 $AP$의 기울기: $\\frac{1 - (-2)}{2-3} = -3$이다.\\n3) 수직인 직선의 기울기: 곱이 $-1$이어야 하므로 $1/3$이다.\\n4) 식 완성: $y - (-2) = 1/3 (x-3) \\implies x-3y-9=0$이다.\\n\\n결론\\n따라서 정답은 ①이다."
  },
  {
    id: 17,
    level: "중",
    category: "직선의 방정식",
    originalCategory: "직선의 방정식",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "두 점 $A(2, 5), B(4, 1)$을 이은 선분 $AB$와 직선 $(2m+1)x + (m-1)y + 5m+1 = 0$이 만나도록 하는 실수 $m$의 값의 범위가 $a \\le m \\le b$일 때, $a+b$의 값은?",
    choices: ["① $\\frac{1}{7}$", "② $-\\frac{1}{7}$", "③ $\\frac{7}{2}$", "④ $\\frac{2}{7}$", "⑤ $-\\frac{2}{7}$"],
    answer: "②",
    solution: "[키포인트]\\n직선이 항상 지나는 정점을 찾고, 그 정점을 중심으로 직선을 회전시키며 선분 $AB$와 닿는 범위를 구한다.\\n\\n조건 정리\\n- 직선을 $m$에 대해 정리: $m(2x+y+5) + x-y+1 = 0 \\implies$ 정점 $(-2, -1)$을 지난다.\\n\\n풀이 과정\\n정점 $P(-2, -1)$과 $A(2, 5)$를 지날 때의 $m$은 $1/7$이다.\\n정점 $P(-2, -1)$과 $B(4, 1)$을 지날 때의 $m$은 $-2/7$이다.\\n따라서 범위는 $-2/7 \\le m \\le 1/7$이므로 $a+b = -1/7$이다.\\n\\n결론\\n따라서 정답은 ②이다."
  },
  {
    id: 18,
    level: "상",
    category: "평면좌표",
    originalCategory: "평면좌표",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "[도형필요]\\n$AB=9, AC=6, \\angle A=90^\\circ$인 직각삼각형 $ABC$ 내부의 점 $P$에 대하여 $AP^2+BP^2+CP^2$의 최솟값은?",
    choices: ["① $72$", "② $74$", "③ $76$", "④ $78$", "⑤ $80$"],
    answer: "④",
    solution: "[키포인트]\\n삼각형의 세 꼭짓점으로부터의 거리의 제곱의 합이 최소가 되는 점은 삼각형의 무게중심이다.\\n\\n조건 정리\\n- $A(0, 0), B(9, 0), C(0, 6)$으로 좌표를 잡는다.\\n\\n풀이 방향 설정\\n무게중심 $G$의 좌표를 구하고 각 꼭짓점까지의 거리 제곱의 합을 계산한다.\\n\\n풀이 과정\\n1) 무게중심 $G$: $( (0+9+0)/3, (0+0+6)/3 ) = (3, 2)$이다.\\n2) 거리 제곱 합: $AG^2 + BG^2 + CG^2 = (3^2+2^2) + (6^2+2^2) + (3^2+4^2) = 13 + 40 + 25 = 78$이다.\\n\\n결론\\n따라서 정답은 ④이다."
  },
  {
    id: 19,
    level: "중",
    category: "나머지 정리",
    originalCategory: "나머지 정리",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-02",
    standardUnit: "나머지 정리",
    standardUnitOrder: 2,
    content: "서술형 1. 조립제법을 이용하여 다항식 $2x^3-3x^2-x+2$를 $x-2$로 나눈 몫과 나머지를 구하는 과정을 서술하시오.",
    choices: [],
    answer: "몫: $2x^2+x+1$, 나머지: 4",
    solution: "[키포인트]\\n조립제법의 계수 나열법을 정확히 적용한다.\\n\\n조건 정리\\n- $2, -3, -1, 2$를 $2$로 조립제법한다.\\n\\n풀이 과정\\n조립제법 결과 하단 계수는 $2, 1, 1$이고 끝자리는 4이다. 따라서 몫은 $2x^2+x+1$이고 나머지는 4이다.\\n\\n결론\\n따라서 구하는 몫은 $2x^2+x+1$이고 나머지는 4이다."
  },
  {
    id: 20,
    level: "상",
    category: "직선의 방정식",
    originalCategory: "직선의 방정식",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "서술형 2. 세 점 $A(5, 4), B(6, 0), O(0, 0)$을 꼭짓점으로 하는 삼각형 $AOB$의 넓이가 직선 $y=-2x+k$에 의해서 이등분될 때, 상수 $k$의 값을 구하는 과정을 서술하시오.",
    choices: [],
    answer: "$12-2\\sqrt{15}$",
    solution: "[키포인트]\\n삼각형의 넓이를 구하고 직선이 자르는 작은 삼각형의 넓이가 전체의 절반임을 이용한다.\\n\\n조건 정리\\n- 삼각형 $AOB$의 넓이는 12이다. 이등분 넓이는 6이어야 한다.\\n\\n풀이 방향 설정\\n직선과 변의 교점을 잡아 $k$에 대한 넓이 방정식을 세운다.\\n\\n풀이 과정\\n1) 전체 넓이: $1/2 \\cdot 6 \\cdot 4 = 12$이다.\\n2) 직선과 변의 교점: $OA$와의 교점, $AB$와의 교점을 구한다.\\n3) 넓이 방정식: 작은 삼각형 넓이가 6이 되는 $k$를 풀면 $12-2\\sqrt{15}$가 도출된다.\\n\\n결론\\n따라서 구하는 $k$의 값은 $12-2\\sqrt{15}$이다."
  },
  {
    id: 21,
    level: "중",
    category: "직선의 방정식",
    originalCategory: "직선의 방정식",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-01",
    standardUnit: "도형의 방정식",
    standardUnitOrder: 1,
    content: "서술형 3. 점 $(-1, 1)$에서 직선 $3ax + 4ay + a^2 + 1 = 0$에 이르는 거리가 1일 때, 모든 $a$의 값을 구하는 과정을 서술하시오.",
    choices: [],
    answer: "$2 \\pm \\sqrt{3}, -3 \\pm 2\\sqrt{2}$",
    solution: "[키포인트]\\n점과 직선 사이의 거리 공식을 적용한다.\\n\\n조건 정리\\n- $\\frac{|-3a + 4a + a^2 + 1|}{\\sqrt{9a^2 + 16a^2}} = 1$이다.\\n\\n풀이 과정\\n$\\frac{|a^2 + a + 1|}{5|a|} = 1 \\implies |a^2 + a + 1| = 5|a|$이다. $a^2+a+1$은 항상 양수이므로 $a^2+a+1 = 5|a|$이다. $a>0$일 때와 $a<0$일 때로 나누어 풀면 정답이 도출된다.\\n\\n결론\\n따라서 정답은 $2 \\pm \\sqrt{3}, -3 \\pm 2\\sqrt{2}$이다."
  },
  {
    id: 22,
    level: "상",
    category: "인수분해",
    originalCategory: "인수분해",
    standardCourse: "공통수학1",
    standardUnitKey: "H22-C-03",
    standardUnit: "인수분해",
    standardUnitOrder: 3,
    content: "서술형 4. 다항식 $A(x) = x^4 + ax^3 + bx^2 + bx + a$는 일차식의 인수를 갖지 않는다. 계수와 상수항이 모두 정수인 두 다항식 $B(x), C(x)$를 인수로 갖고, $B(x)$를 $C(x)$로 나눈 나머지가 1일 때, $a+b$의 값을 구하는 과정을 서술하시오.",
    choices: [],
    answer: "2",
    solution: "[키포인트]\\n상반다항식의 인수분해 성질과 정수 계수 조건을 결합한다.\\n\\n조건 정리\\n- $x^2 + 1/x^2 + a(x + 1/x) + b = 0$ 형태에서 $x+1/x = t$로 치환한다.\\n\\n풀이 방향 설정\\n$t^2 + at + b-2 = 0$의 해를 정수 계수 이차식 조건에 맞춘다.\\n\\n풀이 과정\\n1) 치환: $t^2+at+b-2 = (t-k_1)(t-k_2)$라 하면 $x^2-k_1x+1$과 $x^2-k_2x+1$이 인수가 된다.\\n2) 나머지 조건: $x^2-k_1x+1 = (x^2-k_2x+1) \\cdot 1 + 1$에서 $(k_2-k_1)x = 1$은 성립 불가하므로, 상수항과 차수를 고려하여 $k_1, k_2$의 정수해를 분석한다. 최종적으로 $a=0, b=2$가 도출된다.\\n\\n결론\\n따라서 $a+b=2$이다."
  }
];