window.examTitle = "25_금당중_1학기_중간_중3_기출";

window.questionBank = [
    {
        id: "1",
        content: "",
        choices: [
      String.raw`$64$의 제곱근은 $8$이다.`,
      String.raw`$\sqrt{(-3)^2} = -3$`,
      String.raw`제곱근 $6$은 $\sqrt{6}$이다.`,
      String.raw`$\sqrt{25}$의 제곱근은 $\pm 5$이다.`,
      String.raw`$(-6)^2$의 제곱근은 $\pm \sqrt{6}$이다.`
    ],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "2",
        content: "",
        choices: [
      String.raw`$\sqrt{5^2} = 5$`,
      String.raw`$-(\sqrt{11})^2 = -11$`,
      String.raw`$\sqrt{(-7)^2} = 7$`,
      String.raw`$(-\sqrt{6})^2 = -6$`,
      String.raw`$\sqrt{16} = 4$`
    ],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "3",
        content: "",
        choices: [String.raw`2`, String.raw`3`, String.raw`4`, String.raw`5`, String.raw`6`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "4",
        content: "",
        choices: [String.raw`23`, String.raw`24`, String.raw`25`, String.raw`26`, String.raw`27`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "5",
        content: "",
        choices: [String.raw`$-4\sqrt{2}$`, String.raw`0`, String.raw`$2\sqrt{2}$`, String.raw`4`, String.raw`$4\sqrt{2}$`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "6",
        content: "",
        choices: [
      String.raw`$\sqrt{2}+1 < \sqrt{3}+1$`,
      String.raw`$5-\sqrt{6} < 2-\sqrt{6}$`,
      String.raw`$\sqrt{11}-1 > 2$`,
      String.raw`$\sqrt{7}-3 < \sqrt{8}-3$`,
      String.raw`$\sqrt{2}+\sqrt{3} < \sqrt{3}+\sqrt{5}$`
    ],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "7",
        content: "",
        choices: [
      String.raw`$\frac{1}{\sqrt{3}} = \frac{\sqrt{3}}{3}$`,
      String.raw`$\frac{3}{\sqrt{8}} = \frac{3\sqrt{2}}{4}$`,
      String.raw`$\frac{\sqrt{2}}{5\sqrt{3}} = \frac{\sqrt{6}}{15}$`,
      String.raw`$\frac{6}{\sqrt{24}} = \frac{\sqrt{6}}{2}$`,
      String.raw`$\frac{4}{\sqrt{2}} = 2\sqrt{2}$`
    ],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "8",
        content: "",
        choices: [
      String.raw`$\sqrt{2} \times \sqrt{5}$`,
      String.raw`$\sqrt{42} \div \sqrt{7}$`,
      String.raw`$4\sqrt{5} \div \sqrt{10}$`,
      String.raw`$\sqrt{3} \div \sqrt{6} \times \sqrt{12}$`,
      String.raw`$\sqrt{3} \times \frac{3}{\sqrt{3}}$`
    ],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "9",
        content: "",
        choices: [String.raw`$\sqrt{2}$`, String.raw`$\sqrt{5}$`, String.raw`$2\sqrt{2}$`, String.raw`$2\sqrt{3}$`, String.raw`$3\sqrt{3}$`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "10",
        content: "",
        choices: [String.raw`38`, String.raw`39`, String.raw`40`, String.raw`41`, String.raw`42`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "11",
        content: "",
        choices: [String.raw`$\sqrt{2}+3\sqrt{6}$`, String.raw`$2\sqrt{3}$`, String.raw`$2\sqrt{6}$`, String.raw`$3\sqrt{3}+\sqrt{6}$`, String.raw`$2\sqrt{2}+5\sqrt{3}$`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "12",
        content: "",
        choices: [String.raw`$\sqrt{15}-3\sqrt{3}$`, String.raw`$-\sqrt{15}+9\sqrt{3}$`, String.raw`$-3\sqrt{15}-\sqrt{3}$`, String.raw`$-3\sqrt{15}+\sqrt{3}$`, String.raw`$-\sqrt{15}-9\sqrt{3}$`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "13",
        content: "",
        choices: [String.raw`-2`, String.raw`-1`, String.raw`0`, String.raw`1`, String.raw`2`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "14",
        content: "",
        choices: [String.raw`12`, String.raw`14`, String.raw`16`, String.raw`18`, String.raw`20`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "15",
        content: "",
        choices: [
      String.raw`$(x+3)(x-7) = x^2 - 4x - 21$`,
      String.raw`$(2x+y)^2 = 4x^2 + 4xy + y^2$`,
      String.raw`$(x+5)^2 = x^2 + 10x + 25$`,
      String.raw`$(x+5)(x-5) = x^2 - 25$`,
      String.raw`$(x+3)(3x-4) = 3x^2 + 5x - 12$`
    ],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "16",
        content: "",
        choices: [String.raw`$-\frac{35}{4}$`, String.raw`-8`, String.raw`$-\frac{13}{2}$`, String.raw`$-\frac{9}{2}$`, String.raw`$-\frac{15}{4}$`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "17",
        content: "",
        choices: [String.raw`3`, String.raw`4`, String.raw`5`, String.raw`6`, String.raw`7`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "18",
        content: "",
        choices: [
      String.raw`$x^2-2x$`,
      String.raw`$x^2-4x+4$`,
      String.raw`$x^2+x-2$`,
      String.raw`$x^2+x-6$`,
      String.raw`$x^2-4$`
    ],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "19",
        content: "",
        choices: [String.raw`$-2x-3$`, String.raw`$-2x+3$`, String.raw`$4x+1$`, String.raw`$5x-1$`, String.raw`$5x+1$`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    },
    {
        id: "20",
        content: "",
        choices: [String.raw`2`, String.raw`3`, String.raw`4`, String.raw`5`, String.raw`6`],
        answer: "",
        category: "",
        originalCategory: "",
        standardCourse: "",
        standardUnitKey: "",
        standardUnit: "",
        standardUnitOrder: 0,
        solution: ""
    }
];
