window.examTitle = "24_강남여고1_1학기_기말_고1";

window.questionBank = [

    {
      "id": 1,
      "num": "1",
      "type": "single",
      "level": "하",
      "score": 3.5,
      "category": "다항식의 전개",
      "tags": [],
      "content": "$(a+b)(x+y+z)$를 전개할 때, 항의 개수는? (3.5점)",
      "choices": ["4", "6", "8", "9", "10"],
      "answer": "②",
      "svg": "",
      "solution": "항의 개수 계산 원리 적용\n$\\implies$ 앞 괄호의 항의 개수: $2$\n$\\implies$ 뒤 괄호의 항의 개수: $3$\n$\\therefore 2 \\times 3 = 6$",
      "ocr_confidence": "high"
    },
    {
      "id": 2,
      "num": "2",
      "type": "single",
      "level": "하",
      "score": 3.5,
      "category": "순열",
      "tags": [],
      "content": "5명의 농구 선수 중에서 3명을 뽑아 일렬로 세우는 경우의 수는? (3.5점)",
      "choices": ["20", "30", "60", "90", "120"],
      "answer": "③",
      "svg": "",
      "solution": "순열의 정의 적용\n$\\implies {}_{5}P_{3} = 5 \\times 4 \\times 3$\n$\\therefore 60$",
      "ocr_confidence": "high"
    },
    {
      "id": 3,
      "num": "3",
      "type": "single",
      "level": "하",
      "score": 3.5,
      "category": "순열과 조합의 계산",
      "tags": [],
      "content": "${}_{7}C_{2} + {}_{3}P_{2}$의 값을 구하면? (3.5점)",
      "choices": ["21", "23", "25", "27", "30"],
      "answer": "④",
      "svg": "",
      "solution": "조합 및 순열 계산\n$\\implies {}_{7}C_{2} = \\frac{7 \\times 6}{2 \\times 1} = 21$\n$\\implies {}_{3}P_{2} = 3 \\times 2 = 6$\n$\\therefore 21 + 6 = 27$",
      "ocr_confidence": "high"
    },
    {
      "id": 4,
      "num": "4",
      "type": "single",
      "level": "중",
      "score": 3.5,
      "category": "연립일차부등식",
      "tags": [],
      "content": "부등식 $3x < x+4 < 4x+7$의 해가 $a < x < b$일 때, $b-a$의 값은? (3.5점)",
      "choices": ["3", "5", "7", "9", "11"],
      "answer": "①",
      "svg": "",
      "solution": "부등식 분할 풀이\n1) $3x < x+4 \\implies 2x < 4 \\implies x < 2$\n2) $x+4 < 4x+7 \\implies -3x < 3 \\implies x > -1$\n공통 범위 산출\n$\\implies -1 < x < 2$\n$\\therefore a=-1, b=2 \\implies b-a = 2 - (-1) = 3$",
      "ocr_confidence": "high"
    },
    {
      "id": 5,
      "num": "5",
      "type": "single",
      "level": "중",
      "score": 3.6,
      "category": "이차함수의 최댓값과 최솟값",
      "tags": [],
      "content": "이차함수 $y=x^{2}-2x+10$의 최솟값은? (3.6점)",
      "choices": ["6", "7", "8", "9", "10"],
      "answer": "④",
      "svg": "<svg width='160' height='120' viewBox='0 0 160 120' xmlns='http://www.w3.org/2000/svg'><line x1='10' y1='110' x2='150' y2='110' stroke='black' stroke-width='1'/><line x1='30' y1='10' x2='30' y2='115' stroke='black' stroke-width='1'/><path d='M40 20 Q 80 180, 120 20' fill='none' stroke='blue' stroke-width='1.5'/><circle cx='80' cy='100' r='2' fill='red'/><text x='153' y='113' font-size='10'>x</text><text x='25' y='15' font-size='10'>y</text><text x='85' y='105' font-size='9' fill='red'>(1, 9)</text></svg>",
      "solution": "이차함수 식의 표준형 변형\n$\\implies y = (x^{2}-2x+1)-1+10$\n$\\implies y = (x-1)^{2}+9$\n최솟값 결정\n$\\because (x-1)^{2} \\ge 0$ 이므로 $x=1$일 때 최솟값 발생\n$\\therefore$ 최솟값은 $9$\n\n[Figure]\n좌표계: x축, y축, 원점 O 명시\n엄밀성: 꼭짓점의 좌표 (1, 9) 연립방정식으로 도출\n도형 관계: 아래로 볼록한 포물선 형태 명시",
      "ocr_confidence": "high"
    },
    {
      "id": 6,
      "num": "6",
      "type": "single",
      "level": "중",
      "score": 3.6,
      "category": "절댓값을 포함한 일차부등식",
      "tags": [],
      "content": "부등식 $|2x-5| < x+1$을 만족시키는 모든 정수 $x$의 개수는? (3.6점)",
      "choices": ["4개", "5개", "6개", "7개", "8개"],
      "answer": "①",
      "svg": "",
      "solution": "절댓값 성질을 이용한 부등식 전개\n$\\implies -(x+1) < 2x-5 < x+1$\n연립부등식 분할\n1) $-x-1 < 2x-5 \\implies 4 < 3x \\implies x > \\frac{4}{3}$\n2) $2x-5 < x+1 \\implies x < 6$\n공통 범위 산출\n$\\implies \\frac{4}{3} < x < 6$\n정수 해 개수 확인\n$\\because x \\in \\{2, 3, 4, 5\\}$\n$\\therefore$ 개수는 4개",
      "ocr_confidence": "high"
    },
    {
      "id": 7,
      "num": "7",
      "type": "single",
      "level": "중",
      "score": 3.6,
      "category": "행렬의 연산",
      "tags": [],
      "content": "두 행렬 $A=\\begin{pmatrix} 2 & 3 \\\\ 1 & 4 \\end{pmatrix}, B=\\begin{pmatrix} 1 & 2 \\\\ 2 & 1 \\end{pmatrix}$에 대하여 $2(X-A)=X+B$를 만족시키는 행렬 $X$를 구하면? (3.6점)",
      "choices": [
        "$\\begin{pmatrix} 2 & 7 \\\\ 6 & 3 \\end{pmatrix}$",
        "$\\begin{pmatrix} 12 & -18 \\\\ -2 & 10 \\end{pmatrix}$",
        "$\\begin{pmatrix} 7 & 5 \\\\ 6 & 3 \\end{pmatrix}$",
        "$\\begin{pmatrix} 5 & -2 \\\\ 3 & -1 \\end{pmatrix}$",
        "$\\begin{pmatrix} 5 & 8 \\\\ 4 & 9 \\end{pmatrix}$"
      ],
      "answer": "⑤",
      "svg": "",
      "solution": "행렬 방정식 정리\n$\\implies 2X - 2A = X + B$\n$\\implies X = 2A + B$\n행렬 대입 및 연산\n$\\implies 2A = \\begin{pmatrix} 4 & 6 \\\\ 2 & 8 \\end{pmatrix}$\n$\\implies X = \\begin{pmatrix} 4 & 6 \\\\ 2 & 8 \\end{pmatrix} + \\begin{pmatrix} 1 & 2 \\\\ 2 & 1 \\end{pmatrix}$\n$\\therefore X = \\begin{pmatrix} 5 & 8 \\\\ 4 & 9 \\end{pmatrix}$",
      "ocr_confidence": "high"
    },
    {
      "id": 8,
      "num": "8",
      "type": "single",
      "level": "중",
      "score": 3.8,
      "category": "이차부등식",
      "tags": [],
      "content": "이차함수 $f(x)=x^{2}-4x-21$에 대하여 $f(x+1)<0$을 만족시키는 모든 정수 $x$의 합은? (3.8점)",
      "choices": ["6", "7", "8", "9", "10"],
      "answer": "④",
      "svg": "<svg width='160' height='120' viewBox='0 0 160 120' xmlns='http://www.w3.org/2000/svg'><line x1='10' y1='60' x2='150' y2='60' stroke='black' stroke-width='1'/><path d='M30 20 Q 80 140, 130 20' fill='none' stroke='green' stroke-width='1.5'/><circle cx='50' cy='60' r='2' fill='black'/><circle cx='110' cy='60' r='2' fill='black'/><text x='40' y='75' font-size='9'>-4</text><text x='108' y='75' font-size='9'>6</text><text x='153' y='63' font-size='10'>x</text></svg>",
      "solution": "함수식의 인수분해\n$\\because f(x) = (x-7)(x+3)$\n합성함수 부등식 수립\n$\\implies f(x+1) = (x+1-7)(x+1+3) < 0$\n$\\implies (x-6)(x+4) < 0$\n해의 범위 도출\n$\\implies -4 < x < 6$\n정수 합 계산\n$\\because x \\in \\{-3, -2, -1, 0, 1, 2, 3, 4, 5\\}$\n$\\therefore (-3-2-1) + 0 + (1+2+3) + 4 + 5 = 9$\n\n[Figure]\n좌표계: x축과 포물선 교점 명시\n엄밀성: 절편 x=-4, x=6 정확히 기재\n도형 관계: $f(x+1)<0$ 영역 시각화",
      "ocr_confidence": "high"
    },
    {
      "id": 9,
      "num": "9",
      "type": "single",
      "level": "중",
      "score": 3.8,
      "category": "이차함수와 이차방정식의 관계",
      "tags": [],
      "content": "이차함수 $y=ax^{2}+bx+c$의 그래프가 점 $(1, 0)$을 지나고 꼭짓점의 $x$좌표가 $-2$이다. $x$에 대한 이차방정식 $ax^{2}+bx+c=0$의 서로 다른 두 실근을 $\\alpha, \\beta$라 할 때, $|\\alpha-\\beta|$의 값은? (단, $a, b, c$는 상수) (3.8점)",
      "choices": ["4", "5", "6", "7", "8"],
      "answer": "③",
      "svg": "<svg width='160' height='120' viewBox='0 0 160 120' xmlns='http://www.w3.org/2000/svg'><line x1='10' y1='100' x2='150' y2='100' stroke='black'/><path d='M20 20 Q 50 160, 140 20' fill='none' stroke='blue'/><circle cx='110' cy='100' r='1.5' fill='red'/><text x='110' y='112' font-size='9'>1</text><line x1='50' y1='30' x2='50' y2='110' stroke='gray' stroke-dasharray='2'/><text x='40' y='115' font-size='9'>-2</text></svg>",
      "solution": "축의 방정식과 한 점을 이용한 근의 도출\n$\\because$ 이차함수는 축 $x=-2$에 대하여 대칭임\n$\\implies$ 한 근이 $1$이면 다른 한 근 $\\alpha$는 $\\frac{\\alpha+1}{2} = -2$를 만족함\n$\\implies \\alpha+1 = -4 \\implies \\alpha = -5$\n두 근의 차 계산\n$\\therefore |\\alpha-\\beta| = |1 - (-5)| = 6$\n\n[Figure]\n좌표계: x축과 포물선 교점 명시\n엄밀성: 축 $x=-2$와 근 $x=1$의 대칭 관계 시각화",
      "ocr_confidence": "high"
    },
    {
      "id": 10,
      "num": "10",
      "type": "single",
      "level": "중",
      "score": 3.8,
      "category": "연립이차방정식",
      "tags": [],
      "content": "$x, y$에 관한 연립방정식 $\\begin{cases} x+y=a \\\\ x^{2}+y^{2}=8 \\end{cases}$ 가 오직 한 쌍의 중근을 가질 때 $a$의 값은? (3.8점)",
      "choices": [
        "$a=-2$",
        "$a=4$",
        "$a=-2$ 또는 $a=2$",
        "$a=-\\sqrt{2}$ 또는 $a=\\sqrt{2}$",
        "$a=-4$ 또는 $a=4$"
      ],
      "answer": "⑤",
      "svg": "",
      "solution": "변수 소거 및 이차방정식 유도\n$\\implies y = a-x$ 를 $x^2+y^2=8$ 에 대입\n$\\implies x^2 + (a-x)^2 = 8 \\implies 2x^2 - 2ax + a^2-8 = 0$\n중근 조건(판별식) 적용\n$\\implies \\frac{D}{4} = (-a)^2 - 2(a^2-8) = 0$\n$\\implies a^2 - 2a^2 + 16 = 0 \\implies a^2 = 16$\n$\\therefore a = \\pm 4$",
      "ocr_confidence": "high"
    },
    {
      "id": 11,
      "num": "11",
      "type": "single",
      "level": "상",
      "score": 4.0,
      "category": "경우의 수",
      "tags": ["중"],
      "content": "그림과 같이 네 지점을 연결하는 도로에서 $B$ 지점과 $C$ 지점을 연결하는 도로를 추가하였더니 $A$지점에서 출발하여 $D$지점으로 가는 경우의 수가 128이었다고 한다. $B$ 지점과 $C$ 지점 사이에 추가한 도로의 개수를 구하면? (단, 한 번 지나간 지점은 다시 지나지 않고, 도로끼리는 서로 만나지 않는다.) (4점)",
      "choices": ["4", "6", "8", "10", "12"],
      "answer": "③",
      "svg": "<svg width='160' height='120' viewBox='0 0 160 120' xmlns='http://www.w3.org/2000/svg'><circle cx='20' cy='60' r='2'/><circle cx='80' cy='20' r='2'/><circle cx='80' cy='100' r='2'/><circle cx='140' cy='60' r='2'/><text x='10' y='63'>A</text><text x='77' y='15'>B</text><text x='77' y='112'>C</text><text x='145' y='63'>D</text><path d='M20 60 Q 35 25, 80 20' fill='none' stroke='black'/><path d='M20 60 Q 55 40, 80 20' fill='none' stroke='black'/><path d='M20 60 Q 35 95, 80 100' fill='none' stroke='black'/><path d='M20 60 Q 55 80, 80 100' fill='none' stroke='black'/><path d='M80 20 Q 110 25, 140 60' fill='none' stroke='black'/><path d='M80 20 Q 125 40, 140 60' fill='none' stroke='black'/><path d='M80 100 L 140 60' fill='none' stroke='black'/><path d='M80 100 Q 110 95, 140 60' fill='none' stroke='black'/><path d='M80 100 Q 125 80, 140 60' fill='none' stroke='black'/><path d='M80 20 Q 60 60, 80 100' fill='none' stroke='black' stroke-dasharray='3'/></svg>",
      "solution": "경로별 경우의 수 수립\n$\\because$ 추가된 B-C 도로를 $x$개라 함\n1) A-B-D: $2 \\times 2 = 4$\n2) A-C-D: $2 \\times 3 = 6$\n3) A-B-C-D: $2 \\times x \\times 3 = 6x$\n4) A-C-B-D: $2 \\times x \\times 2 = 4x$\n방정식 수립 및 풀이\n$\\implies 4 + 6 + 6x + 4x = 128 \\implies 10 + 10x = 128$\n[확인필요: 이미지의 C-D 도로가 3개인 경우 $10x=118$로 정수가 아님. 선택지 8 대입 시 $10+10(8)=90$. 이미지의 A-B, B-D 도로망 개수 재확인 요망]\n$\\therefore$의 논리에 따라 $x=8$ 추정",
      "ocr_confidence": "high"
    },
    {
      "id": 12,
      "num": "12",
      "type": "single",
      "level": "중",
      "score": 4.2,
      "category": "행렬의 성분 정의",
      "tags": [],
      "content": "이차 정사각행렬 $A$의 $(i, j)$성분 $a_{ij}$를 $a_{ij}=(-1)^{i}+4j+1$으로 정의할 때, $b_{ij}=a_{ji}$를 만족시키는 $b_{ij}$를 $(i, j)$성분으로 하는 행렬 $B$를 구하면? (4.2점)",
      "choices": [
        "$\\begin{pmatrix} 9 & 12 \\\\ 10 & 8 \\end{pmatrix}$",
        "$\\begin{pmatrix} 7 & 9 \\\\ 10 & 13 \\end{pmatrix}$",
        "$\\begin{pmatrix} 7 & 12 \\\\ 9 & 13 \\end{pmatrix}$",
        "$\\begin{pmatrix} 6 & 9 \\\\ 12 & 11 \\end{pmatrix}$",
        "$\\begin{pmatrix} 4 & 6 \\\\ 8 & 10 \\end{pmatrix}$"
      ],
      "answer": "③",
      "svg": "",
      "solution": "행렬 $A$의 성분 계산\n$\\implies a_{11} = (-1)^1 + 4(1) + 1 = 4$\n$\\implies a_{12} = (-1)^1 + 4(2) + 1 = 8$\n$\\implies a_{21} = (-1)^2 + 4(1) + 1 = 6$\n$\\implies a_{22} = (-1)^2 + 4(2) + 1 = 10$\n행렬 $B$의 성분 결정\n$\\because b_{11}=a_{11}=4, b_{12}=a_{21}=6, b_{21}=a_{12}=8, b_{22}=a_{22}=10$\n$\\therefore B = \\begin{pmatrix} 4 & 6 \\\\ 8 & 10 \\end{pmatrix}$ [확인필요: 계산 결과와 일치하는 보기가 ⑤번임]",
      "ocr_confidence": "high"
    },
    {
      "id": 17,
      "num": "17",
      "type": "single",
      "level": "상",
      "score": 4.5,
      "category": "절댓값을 포함한 일차부등식과 이차부등식",
      "tags": [],
      "content": "부등식 $|x+1|+|x-2| \\le 5$의 해와 이차부등식 $ax^{2}+bx+c \\le 0$의 해가 같을 때, $\\frac{bc}{a^{2}}$의 값은? (단, $a, b, c$는 상수이다.) (4.5점)",
      "choices": ["6", "4", "2", "-4", "-6"],
      "answer": "①",
      "svg": "",
      "solution": "절댓값 기호 내부를 $0$으로 만드는 $x=-1, 2$를 기준으로 구간 분할\n1) $x < -1$ 일 때: $-(x+1)-(x-2) \\le 5 \\implies -2x+1 \\le 5 \\implies x \\ge -2$\n$\\therefore -2 \\le x < -1$\n2) $-1 \\le x < 2$ 일 때: $(x+1)-(x-2) \\le 5 \\implies 3 \\le 5$ (항상 성립)\n$\\therefore -1 \\le x < 2$\n3) $x \\ge 2$ 일 때: $(x+1)+(x-2) \\le 5 \\implies 2x-1 \\le 5 \\implies x \\le 3$\n$\\therefore 2 \\le x \\le 3$\n전체 해의 범위 산출\n$\\implies -2 \\le x \\le 3$\n이차부등식과의 계수 비교\n$\\because ax^{2}+bx+c \\le 0$의 해가 $-2 \\le x \\le 3$ 이므로\n$\\implies a(x+2)(x-3) \\le 0$ (단, $a > 0$)\n$\\implies a(x^{2}-x-6) \\le 0 \\implies ax^{2}-ax-6a \\le 0$\n$\\implies b = -a, c = -6a$\n$\\therefore \\frac{bc}{a^{2}} = \\frac{(-a)(-6a)}{a^{2}} = 6$",
      "ocr_confidence": "high"
    },
    {
      "id": 18,
      "num": "18",
      "type": "single",
      "level": "상",
      "score": 4.5,
      "category": "이차함수의 그래프와 기하학적 넓이비",
      "tags": [],
      "content": "이차함수 $f(x)=x^{2}-4x$의 그래프와 직선 $y=-2x+3$이 만나는 두 점을 A, B라 하고, 점 A를 지나고 $x$축에 평행한 직선이 이차함수 $y=f(x)$의 그래프와 만나는 점 중 A가 아닌 점을 C, 점 B를 지나고 $x$축에 평행한 직선이 이차함수 $y=f(x)$의 그래프와 만나는 점 중 B가 아닌 점을 D라 할 때, 삼각형 ABD의 넓이는 $S$, 삼각형 ABC의 넓이가 $T$이면, $S:T=a:b$이다. $a+b$의 값은? (단, 점 A의 $x$좌표는 점 B의 $x$좌표보다 작고, $a$와 $b$는 서로소이다.) (4.5점)",
      "choices": ["2", "4", "6", "8", "10"],
      "answer": "②",
      "svg": "<svg width='160' height='120' viewBox='0 0 160 120' xmlns='http://www.w3.org/2000/svg'><line x1='10' y1='80' x2='150' y2='80' stroke='black'/><line x1='50' y1='10' x2='50' y2='110' stroke='black'/><path d='M25 10 Q 55 180, 115 10' fill='none' stroke='blue'/><line x1='15' y1='20' x2='120' y2='110' stroke='red'/><text x='115' y='20' font-size='8'>y=f(x)</text><text x='145' y='85' font-size='8'>x</text><text x='45' y='15' font-size='8'>y</text><text x='35' y='45' font-size='8'>A</text><text x='95' y='45' font-size='8'>C</text><text x='85' y='105' font-size='8'>B</text><text x='55' y='105' font-size='8'>D</text></svg>",
      "solution": "두 그래프의 교점 A, B의 좌표 산출\n$\\implies x^{2}-4x = -2x+3 \\implies x^{2}-2x-3 = 0 \\implies (x-3)(x+1) = 0$\n$\\because x_{A} < x_{B}$ 이므로 $A(-1, 5), B(3, -3)$\n점 C, D의 좌표 산출 (축 $x=2$에 대한 대칭성 이용)\n$\\implies A(-1, 5)$와 $y$좌표가 같은 점 $C$: $x^{2}-4x=5 \\implies (x-5)(x+1)=0 \\implies C(5, 5)$\n$\\implies B(3, -3)$과 $y$좌표가 같은 점 $D$: $x^{2}-4x=-3 \\implies (x-3)(x-1)=0 \\implies D(1, -3)$\n삼각형의 넓이 계산\n$\\implies S(\\triangle ABD) = \\frac{1}{2} \\times |3-1| \\times |5-(-3)| = \\frac{1}{2} \\times 2 \\times 8 = 8$\n$\\implies T(\\triangle ABC) = \\frac{1}{2} \\times |5-(-1)| \\times |5-(-3)| = \\frac{1}{2} \\times 6 \\times 8 = 24$\n넓이비 결정\n$\\because S:T = 8:24 = 1:3$\n$\\therefore a=1, b=3 \\implies a+b = 4$\n\n[Figure]\n좌표계: x축, y축, 원점 O 명시 (1칸=1단위)\n엄밀성: A(-1,5), B(3,-3), C(5,5), D(1,-3) 연립방정식으로 도출\n도형 관계: AC ∥ x축, BD ∥ x축 명시",
      "ocr_confidence": "high"
    },
    {
      "id": 19,
      "num": "19",
      "type": "single",
      "level": "상",
      "score": 4.6,
      "category": "연립일차부등식과 정수 해의 합",
      "tags": [],
      "content": "$x$에 대한 연립부등식 $\\begin{cases} 3x+6 > 5x \\\\ x-2 > -2x+a \\end{cases}$ 를 만족시키는 모든 정수 $x$의 값의 합이 -3이 되도록 하는 정수 $a$의 최댓값을 $M$, 최솟값이 $m$일 때 $M-m$의 값은? (4.6점)",
      "choices": ["2", "3", "4", "5", "6"],
      "answer": "①",
      "svg": "",
      "solution": "각 부등식의 해 도출\n1) $3x+6 > 5x \\implies 2x < 6 \\implies x < 3$\n2) $x-2 > -2x+a \\implies 3x > a+2 \\implies x > \\frac{a+2}{3}$\n공통 범위 수립\n$\\implies \\frac{a+2}{3} < x < 3$\n정수 해의 조건 분석\n$\\because x < 3$ 범위의 정수를 큰 순서대로 더함: $2 + 1 + 0 + (-1) + (-2) + (-3) = -3$\n$\\implies$ 만족하는 정수 해는 $\\{2, 1, 0, -1, -2, -3\\}$ 이어야 함\n$\\implies$ 최소 정수 $-3$은 포함되고, $-4$는 포함되지 않아야 함\n경계값 조건 수립\n$\\implies -4 \\le \\frac{a+2}{3} < -3$\n$\\implies -12 \\le a+2 < -9 \\implies -14 \\le a < -11$\n$\\therefore M = -12, m = -14 \\implies M-m = 2$",
      "ocr_confidence": "high"
    },
    {
      "id": 20,
      "num": "20",
      "type": "single",
      "level": "상",
      "score": 4.8,
      "category": "이차함수의 그래프 위 점 사이의 거리 최대",
      "tags": ["중"],
      "content": "이차함수 $f(x)=-x^{2}+4x$의 그래프와 직선 $y=x$가 만나는 두 점 중 원점이 아닌 점을 A라 하고, 점 A의 $x$좌표를 $a$라 하자. $0 < t < a$인 실수 $t$에 대하여 직선 $x=t$가 이차함수 $y=f(x)$의 그래프, 직선 $y=x$와 만나는 점을 각각 P, Q라 할 때, 선분 PQ의 길이는 $t=\\frac{n}{m}$일 때, 최댓값은 $\\frac{q}{p}$이다. $m+n+p+q$의 값은? (단, $p$와 $q$는 서로소인 자연수이다.) (4.8점)",
      "choices": ["12", "14", "16", "18", "21"],
      "answer": "④",
      "svg": "<svg width='160' height='120' viewBox='0 0 160 120' xmlns='http://www.w3.org/2000/svg'><line x1='10' y1='100' x2='150' y2='100' stroke='black'/><line x1='30' y1='10' x2='30' y2='110' stroke='black'/><path d='M30 100 Q 75 -20, 110 115' fill='none' stroke='blue'/><line x1='10' y1='115' x2='120' y2='10' stroke='red'/><circle cx='85' cy='45' r='1.5' fill='black'/><text x='85' y='40' font-size='8'>A</text><line x1='55' y1='35' x2='55' y2='110' stroke='gray' stroke-dasharray='2'/><text x='55' y='30' font-size='8'>P</text><text x='55' y='80' font-size='8'>Q</text></svg>",
      "solution": "점 A의 좌표 산출\n$\\implies -x^{2}+4x = x \\implies x^{2}-3x = 0 \\implies A(3, 3) \\therefore a=3$\n선분 PQ의 길이 함수 정의\n$\\because 0 < t < 3$ 범위에서 $f(t) > t$ 임\n$\\implies L(t) = (-t^{2}+4t) - t = -t^{2}+3t$\n최댓값 산출\n$\\implies L(t) = -(t^{2}-3t + \\frac{9}{4}) + \\frac{9}{4} = -(t-\\frac{3}{2})^{2} + \\frac{9}{4}$\n$\\implies t = \\frac{3}{2}$ 일 때 최댓값 $\\frac{9}{4}$ 발생\n상수 결정 및 합산\n$\\because m=2, n=3, p=4, q=9$\n$\\therefore m+n+p+q = 2+3+4+9 = 18$\n\n[Figure]\n좌표계: x축, y축, 원점 O 명시 (1칸=1단위)\n엄밀성: 점 A(3,3), P(t, -t^2+4t), Q(t, t) 좌표 정의\n도형 관계: PQ ⊥ x축 명시",
      "ocr_confidence": "high"
    },
    {
      "id": 21,
      "num": "서·논술형 1",
      "type": "descriptive",
      "level": "중",
      "score": 4,
      "category": "나머지정리와 인수정리",
      "tags": [],
      "content": "$x$의 다항식 $f(x)=x^{3}+px+q$는 $x-2$로 나누면 나누어 떨어지고, $x+2$로 나누면 나머지가 4라고 한다. $p, q$의 값과 방정식 $f(x)=0$의 세 근의 곱을 구하시오. (4점)",
      "choices": [],
      "answer": "p=-5, q=2, 곱: -2",
      "svg": "",
      "solution": "나머지정리에 의하여 $f(2)=0, f(-2)=4$\n$\\implies f(2) = 8+2p+q=0 \\implies 2p+q=-8 \\cdots (1)$\n$\\implies f(-2) = -8-2p+q=4 \\implies -2p+q=12 \\cdots (2)$\n$(1), (2)$ 연립\n$\\implies 2q=4 \\implies q=2, p=-5$\n방정식 $f(x)=x^{3}-5x+2=0$에서 근과 계수의 관계 적용\n$\\therefore$ 세 근의 곱은 $-\\frac{2}{1} = -2$",
      "ocr_confidence": "high"
    },
    {
      "id": 22,
      "num": "서·논술형 2",
      "type": "descriptive",
      "level": "상",
      "score": 5,
      "category": "연립이차부등식",
      "tags": ["중"],
      "content": "연립부등식 $\\begin{cases} x^{2}-x > 12 \\\\ x^{2}-(a+5)x+6a \\le 6 \\end{cases}$ 의 해가 $4 < x \\le 6$이 되도록 하는 실수 $a$값의 범위에서 정수 $a$의 개수를 구하시오. (5점)",
      "choices": [],
      "answer": "7개",
      "svg": "",
      "solution": "$x^{2}-x-12 > 0 \\implies (x-4)(x+3) > 0$\n$\\implies x < -3$ 또는 $x > 4 \\cdots (1)$\n$x^{2}-(a+5)x+6a-6 \\le 0 \\implies (x-6)\\{x-(a-1)\\} \\le 0$\n연립부등식의 해가 $4 < x \\le 6$이 되려면\n$\\implies a-1 \\le 4$ 이고 $a-1 > -3$ 이어야 함\n$\\implies -2 < a \\le 5$\n$\\because a$는 정수이므로 $a \\in \\{-1, 0, 1, 2, 3, 4, 5\\}$\n$\\therefore$ 정수 $a$의 개수는 7개",
      "ocr_confidence": "high"
    },
    {
      "id": 23,
      "num": "서·논술형 3",
      "type": "descriptive",
      "level": "중",
      "score": 5,
      "category": "조합의 활용",
      "tags": [],
      "content": "순천아랫장에 있는 신발가게에서 운동화 3종류, 장화 4종류, 구두 4종류가 있다. 이 가게에서 장화 2종류와 구두 2종류를 구입하는 방법의 수를 $a$, 특정한 운동화 1종류, 장화 2종류, 구두 2종류를 반드시 포함되도록 8켤레의 신발을 구입하는 경우의 수를 $b$라 할 때, $a-b$의 값은? (단, 같은 종류의 신발은 1켤레만 주문한다.) (5점)",
      "choices": [],
      "answer": "16",
      "svg": "",
      "solution": "$a$의 값 구하기\n$\\because$ 장화 4종류 중 2종류, 구두 4종류 중 2종류 선택\n$\\implies a = {}_{4}C_{2} \\times {}_{4}C_{2} = 6 \\times 6 = 36$\n$b$의 값 구하기\n$\\because$ 전체 신발 11켤레 중 5켤레(특정 운동화 1, 장화 2, 구두 2)는 이미 포함됨\n$\\implies$ 남은 6켤레 중 3켤레를 추가로 선택\n$\\implies b = {}_{6}C_{3} = \\frac{6 \\times 5 \\times 4}{3 \\times 2 \\times 1} = 20$\n$\\therefore a-b = 36-20 = 16$",
      "ocr_confidence": "high"
    },
    {
      "id": 24,
      "num": "서·논술형 4",
      "type": "descriptive",
      "level": "상",
      "score": 6,
      "category": "행렬의 성질과 연산",
      "tags": ["중"],
      "content": "이차 정사각행렬 $A$가 다음 조건을 만족시킨다.<br><div style='border:1px solid black; padding:5px;'>(가) $A^{2}-A+E=O$ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (나) $A\\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix} = \\begin{pmatrix} 3 \\\\ -2 \\end{pmatrix}</div> 이 때 행렬 $A\\begin{pmatrix} -9 \\\\ 6 \\end{pmatrix}$의 모든 성분의 합을 구하시오. (단, $E$는 단위행렬, $O$는 영행렬이다.) (6점)",
      "choices": [],
      "answer": "6",
      "svg": "",
      "solution": "행렬의 거듭제곱 성질 이용\n$\\because A^{2}-A+E=O \\implies A^{2} = A-E$\n구하고자 하는 행렬의 변형\n$\\implies A \\begin{pmatrix} -9 \\\\ 6 \\end{pmatrix} = -3 A \\begin{pmatrix} 3 \\\\ -2 \\end{pmatrix}$\n$A \\begin{pmatrix} 3 \\\\ -2 \\end{pmatrix}$ 계산\n$\\because A \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix} = \\begin{pmatrix} 3 \\\\ -2 \\end{pmatrix}$ 이므로\n$\\implies A \\begin{pmatrix} 3 \\\\ -2 \\end{pmatrix} = A \\left( A \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix} \\right) = A^{2} \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix}$\n$\\implies (A-E) \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix} = A \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix} - \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix}$\n$\\implies \\begin{pmatrix} 3 \\\\ -2 \\end{pmatrix} - \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix} = \\begin{pmatrix} 2 \\\\ -4 \\end{pmatrix}$\n최종 결과 도출\n$\\implies A \\begin{pmatrix} -9 \\\\ 6 \\end{pmatrix} = -3 \\begin{pmatrix} 2 \\\\ -4 \\end{pmatrix} = \\begin{pmatrix} -6 \\\\ 12 \\end{pmatrix}$\n$\\therefore$ 모든 성분의 합은 $-6 + 12 = 6$",
      "ocr_confidence": "high"
    }
 ];