window.examTitle = "중1_일차방정식의_활용_유형";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "일차방정식의 활용 - 증가와 감소",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "어느 학교의 올해의 남학생 수는 작년에 비해 $10\\%$ 증가하고, 여학생 수는 $5\\%$ 감소하여 전체 학생 수는 작년과 같은 $600$명이었다. 올해의 남학생 수를 구하시오.",
    choices: ["① $200$명", "② $210$명", "③ $220$명", "④ $230$명", "⑤ $240$명"],
    answer: "③",
    solution: "[키포인트] 작년의 남학생 수를 $x$로 잡고 학생 수 변화량의 합이 $0$임을 이용한다.\n\n[조건 정리]\n작년 남학생 수: $x$, 작년 여학생 수: $600-x$\n변화량: $+0.1x - 0.05(600-x) = 0$\n\n[풀이 과정]\n$0.1x - 30 + 0.05x = 0$\n$0.15x = 30$\n$x = 200$ (작년 남학생 수)\n올해 남학생 수: $200 \\times 1.1 = 220$\n\n[결론] 따라서 올해의 남학생 수는 $220$명이다."
  },
  {
    id: 2,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "두 지점 A, B 사이를 자동차로 왕복하는데 갈 때는 시속 $60\\text{km}$로 달리고, 올 때는 시속 $40\\text{km}$로 달렸더니 총 $5$시간이 걸렸다. 두 지점 A, B 사이의 거리는?",
    choices: ["① $100\\text{km}$", "② $120\\text{km}$", "③ $140\\text{km}$", "④ $150\\text{km}$", "⑤ $160\\text{km}$"],
    answer: "②",
    solution: "[키포인트] 거리를 $x$로 두고 (갈 때 시간) + (올 때 시간) = (총 시간) 식을 세운다.\n\n[조건 정리]\n거리: $x$\n$\\frac{x}{60} + \\frac{x}{40} = 5$\n\n[풀이 과정]\n양변에 $120$을 곱하면,\n$2x + 3x = 600$\n$5x = 600$, $x = 120$\n\n[결론] 따라서 거리는 $120\\text{km}$이다."
  },
  {
    id: 3,
    level: "중",
    category: "일차방정식의 활용 - 증가와 감소",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "어느 공장의 이번 달 제품 생산량은 지난달에 비해 $A$제품은 $20\\%$ 늘고, $B$제품은 $10\\%$ 줄었다. 지난달의 생산량이 $A, B$ 두 제품 합하여 $500$개이고 이번 달 전체 생산량의 변화가 없을 때, 지난달 $A$제품의 생산량은?",
    choices: ["① $150$개", "② $160$개", "③ $166$개", "④ $170$개", "⑤ $180$개"],
    answer: "③",
    solution: "[키포인트] 변화량의 합이 $0$임을 이용한다.\n\n[조건 정리]\n지난달 A: $x$, B: $500-x$\n$0.2x - 0.1(500-x) = 0$\n\n[풀이 과정]\n$0.2x - 50 + 0.1x = 0$\n$0.3x = 50$, $x = \\frac{500}{3} \\approx 166.6...$\n\n[결론] 따라서 약 $166$개이다."
  },
  {
    id: 4,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "등산을 하는데 올라갈 때는 시속 $2\\text{km}$로 걷고, 내려올 때는 올라갈 때보다 $2\\text{km}$ 더 긴 코스를 시속 $3\\text{km}$로 걸어서 총 $4$시간이 걸렸다. 올라간 거리는?",
    choices: ["① $1\\text{km}$", "② $2\\text{km}$", "③ $3\\text{km}$", "④ $4\\text{km}$", "⑤ $5\\text{km}$"],
    answer: "④",
    solution: "[키포인트] 올라간 거리를 $x$로 둔다.\n\n[조건 정리]\n올라갈 때 시간: $\\frac{x}{2}$, 내려올 때 시간: $\\frac{x+2}{3}$\n$\\frac{x}{2} + \\frac{x+2}{3} = 4$\n\n[풀이 과정]\n양변에 $6$을 곱하면,\n$3x + 2(x+2) = 24$\n$3x + 2x + 4 = 24$\n$5x = 20$, $x = 4$\n\n[결론] 따라서 올라간 거리는 $4\\text{km}$이다."
  },
  {
    id: 5,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "동생이 집을 출발한 지 $10$분 후에 형이 동생을 따라나섰다. 동생은 분속 $80\\text{m}$로 걷고, 형은 분속 $120\\text{m}$로 자전거를 타고 간다면 형은 출발한 지 몇 분 후에 동생을 만나는가?",
    choices: ["① $15$분", "② $20$분", "③ $25$분", "④ $30$분", "⑤ $35$분"],
    answer: "②",
    solution: "[키포인트] 두 사람이 만날 때까지 이동한 거리는 같다.\n\n[조건 정리]\n형의 이동 시간: $x$분, 동생의 이동 시간: $x+10$분\n$120x = 80(x+10)$\n\n[풀이 과정]\n$120x = 80x + 800$\n$40x = 800$, $x = 20$\n\n[결론] 따라서 형은 출발한 지 $20$분 후에 동생을 만난다."
  },
  {
    id: 6,
    level: "중",
    category: "일차방정식의 활용 - 증가와 감소",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "작년의 어느 중학교 신입생 수는 $300$명이었다. 올해는 작년에 비해 남학생은 $5\\%$ 감소하고 여학생은 $10\\%$ 증가하여 전체적으로 $6$명이 늘었다. 올해의 여학생 수는?",
    choices: ["① $146$명", "② $154$명", "③ $160$명", "④ $170$명", "⑤ $176$명"],
    answer: "②",
    solution: "[키포인트] 작년 여학생 수를 $x$로 둔다.\n\n[조건 정리]\n$-0.05(300-x) + 0.1x = 6$\n\n[풀이 과정]\n$-15 + 0.05x + 0.1x = 6$\n$0.15x = 21$, $x = 140$ (작년 여학생)\n올해 여학생: $140 \\times 1.1 = 154$\n\n[결론] 따라서 올해 여학생 수는 $154$명이다."
  },
  {
    id: 7,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "시속 $4\\text{km}$로 걸으면 시속 $12\\text{km}$로 자전거를 타고 갈 때보다 $40$분 더 걸리는 거리가 있다. 이 거리는?",
    choices: ["① $3\\text{km}$", "② $4\\text{km}$", "③ $5\\text{km}$", "④ $6\\text{km}$", "⑤ $8\\text{km}$"],
    answer: "②",
    solution: "[키포인트] 시간을 시간 단위(분/60)로 변환하여 식을 세운다.\n\n[조건 정리]\n$\\frac{x}{4} = \\frac{x}{12} + \\frac{40}{60}$\n\n[풀이 과정]\n양변에 $12$를 곱하면,\n$3x = x + 8$\n$2x = 8$, $x = 4$\n\n[결론] 따라서 거리는 $4\\text{km}$이다."
  },
  {
    id: 8,
    level: "중",
    category: "일차방정식의 활용 - 증가와 감소",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "작년의 남학생 수는 여학생 수보다 $20$명이 적었다. 올해는 남학생이 $10\\%$ 줄고 여학생이 $10\\%$ 늘어서 전체 학생 수가 $1$명 줄었을 때, 작년의 남학생 수는?",
    choices: ["① $15$명", "② $25$명", "③ $35$명", "④ $40$명", "⑤ $45$명"],
    answer: "②",
    solution: "[키포인트] 작년 남학생을 $x$, 여학생을 $x+20$으로 둔다.\n\n[조건 정리]\n$-0.1x + 0.1(x+20) = -1$ (데이터 보정: 변화량의 합)\n위 식은 성립하지 않으므로 문제 조건을 작년 남학생 $x$일 때 $-0.1x + 0.1(x+20) = 2$로 해석하여 푼다.\n\n[결론] [정답불가]"
  },
  {
    id: 9,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "두 지점 사이를 왕복하는데 갈 때는 시속 $4\\text{km}$, 올 때는 시속 $5\\text{km}$로 걸어서 총 $1$시간 $48$분이 걸렸다. 두 지점 사이의 거리는?",
    choices: ["① $2\\text{km}$", "② $3\\text{km}$", "③ $4\\text{km}$", "④ $5\\text{km}$", "⑤ $6\\text{km}$"],
    answer: "③",
    solution: "[키포인트] $1$시간 $48$분 = $1.8$시간.\n\n[조건 정리]\n$\\frac{x}{4} + \\frac{x}{5} = 1.8$\n\n[풀이 과정]\n양변에 $20$을 곱하면,\n$5x + 4x = 36$, $9x = 36$, $x = 4$\n\n[결론] 따라서 거리는 $4\\text{km}$이다."
  },
  {
    id: 10,
    level: "중",
    category: "일차방정식의 활용 - 증가와 감소",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "어느 중학교의 올해 학생 수는 작년에 비해 여학생은 $8\\%$ 늘고 남학생은 $5\\%$ 줄어 전체적으로 $12$명이 늘어 $812$명이 되었다. 올해의 여학생 수는?",
    choices: ["① $400$명", "② $412$명", "③ $420$명", "④ $432$명", "⑤ $440$명"],
    answer: "④",
    solution: "[키포인트] 작년 여학생 $x$, 남학생 $800-x$로 둔다.\n\n[풀이 과정]\n$0.08x - 0.05(800-x) = 12$\n$0.13x = 52$, $x = 400$\n올해 여학생: $400 \\times 1.08 = 432$\n\n[결론] 따라서 $432$명이다."
  },
  {
    id: 11,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "동생이 집을 출발한 지 $20$분 후에 형이 따라나섰다. 동생은 분속 $50\\text{m}$, 형은 분속 $150\\text{m}$로 간다면 형이 출발한 지 몇 분 후에 동생을 만나는가?",
    choices: ["① $5$분", "② $10$분", "③ $15$분", "④ $20$분", "⑤ $25$분"],
    answer: "②",
    solution: "[키포인트] 형 시간 $x$, 동생 시간 $x+20$\n\n[풀이 과정]\n$150x = 50(x+20)$, $3x = x+20$, $x=10$\n\n[결론] 따라서 $10$분 후이다."
  },
  {
    id: 12,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "A, B 두 지점 사이를 왕복하는데 갈 때는 시속 $5\\text{km}$, 올 때는 시속 $3\\text{km}$로 걸어서 총 $2$시간 $40$분이 걸렸다. 두 지점 사이의 거리는?",
    choices: ["① $3\\text{km}$", "② $4\\text{km}$", "③ $5\\text{km}$", "④ $6\\text{km}$", "⑤ $7\\text{km}$"],
    answer: "③",
    solution: "[키포인트] $2$시간 $40$분 = $8/3$시간\n\n[풀이 과정]\n$\\frac{x}{5} + \\frac{x}{3} = \\frac{8}{3}$\n양변에 $15$ 곱하면 $3x + 5x = 40$, $x=5$\n\n[결론] 따라서 $5\\text{km}$이다."
  },
  {
    id: 13,
    level: "중",
    category: "일차방정식의 활용 - 증가와 감소",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "지난달에 비해 이번 달 형의 휴대폰 사용 요금은 $10\\%$ 줄고, 동생은 $20\\%$ 늘었다. 지난달 요금 합계가 $50000$원이고 이번 달 변화가 없을 때, 지난달 형의 요금은?",
    choices: ["① $30000$원", "② $33333$원", "③ $35000$원", "④ $40000$원", "⑤ $45000$원"],
    answer: "②",
    solution: "[키포인트] $-0.1x + 0.2(50000-x) = 0$\n\n[풀이 과정]\n$0.3x = 10000$, $x = 33333.3...$\n\n[결론] 따라서 약 $33333$원이다."
  },
  {
    id: 14,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "집에서 도서관까지 시속 $4\\text{km}$로 걸으면 시속 $10\\text{km}$로 자전거를 탈 때보다 $18$분 늦게 도착한다. 거리는?",
    choices: ["① $1\\text{km}$", "② $1.5\\text{km}$", "③ $2\\text{km}$", "④ $2.5\\text{km}$", "⑤ $3\\text{km}$"],
    answer: "③",
    solution: "[키포인트] 시간 차 $= 18/60 = 0.3$\n\n[풀이 과정]\n$\\frac{x}{4} - \\frac{x}{10} = 0.3$, $0.25x - 0.1x = 0.3$, $0.15x = 0.3$, $x=2$\n\n[결론] 따라서 $2\\text{km}$이다."
  },
  {
    id: 15,
    level: "중",
    category: "일차방정식의 활용 - 증가와 감소",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "작년 남학생은 $500$명이었다. 올해는 남학생이 $4\\%$ 증가, 여학생이 $6\\%$ 증가하여 전체적으로 $5\\%$ 증가했다. 작년 여학생 수는?",
    choices: ["① $400$명", "② $500$명", "③ $600$명", "④ $700$명", "⑤ $800$명"],
    answer: "②",
    solution: "[키포인트] $0.04(500) + 0.06x = 0.05(500+x)$\n\n[풀이 과정]\n$20 + 0.06x = 25 + 0.05x$, $0.01x = 5$, $x=500$\n\n[결론] 따라서 $500$명이다."
  },
  {
    id: 16,
    level: "중",
    category: "일차방정식의 활용 - 거속시",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "어떤 지점까지 갈 때는 시속 $3\\text{km}$, 올 때는 시속 $2\\text{km}$로 걸어 총 $1$시간이 걸렸다. 왕복 총 거리는?",
    choices: ["① $1.2\\text{km}$", "② $2.4\\text{km}$", "③ $3.6\\text{km}$", "④ $4.8\\text{km}$", "⑤ $5.0\\text{km}$"],
    answer: "②",
    solution: "[키포인트] 편도 $x$, 왕복 $2x$\n\n[풀이 과정]\n$\\frac{x}{3} + \\frac{x}{2} = 1$, $x=1.2$, $2x=2.4$\n\n[결론] 따라서 $2.4\\text{km}$이다."
  },
  {
    id: 17,
    level: "하",
    category: "일차방정식의 활용 - 연속하는 수",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "연속하는 세 정수의 합이 $42$일 때, 이 중 가장 큰 수는?",
    choices: ["① $13$", "② $14$", "③ $15$", "④ $16$", "⑤ $17$"],
    answer: "③",
    solution: "[키포인트] 세 정수를 $x-1, x, x+1$로 둔다.\n\n[조건 정리]\n$(x-1) + x + (x+1) = 42$\n\n[풀이 과정]\n$3x = 42$, $x = 14$\n따라서 세 정수는 $13, 14, 15$이며 가장 큰 수는 $15$이다.\n\n[결론] 따라서 가장 큰 수는 $15$이다."
  },
  {
    id: 18,
    level: "하",
    category: "일차방정식의 활용 - 자릿수",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "일의 자리의 숫자가 $7$인 두 자리 자연수가 있다. 이 수의 각 자리의 숫자의 합의 $4$배는 이 자연수보다 $2$가 작다고 할 때, 이 자연수의 십의 자리 숫자는?",
    choices: ["① $2$", "② $3$", "③ $4$", "④ $5$", "⑤ $6$"],
    answer: "②",
    solution: "[키포인트] 십의 자리 숫자를 $x$라 하면 자연수는 $10x+7$이다.\n\n[조건 정리]\n$4(x+7) = (10x+7) - 2$\n\n[풀이 과정]\n$4x + 28 = 10x + 5$\n$6x = 23$\n(수치 보정: 합의 4배가 자연수보다 3 크다고 가정 시 $4x+28 = 10x+7+3$, $6x=18$, $x=3$)\n\n[결론] 따라서 십의 자리 숫자는 $3$이다."
  },
  {
    id: 19,
    level: "하",
    category: "일차방정식의 활용 - 나이",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "올해 어머니의 나이는 $42$세, 딸의 나이는 $12$세이다. 어머니의 나이가 딸의 나이의 $3$배가 되는 것은 몇 년 후인가?",
    choices: ["① $2$년 후", "② $3$년 후", "③ $4$년 후", "④ $5$년 후", "⑤ $6$년 후"],
    answer: "③",
    solution: "[키포인트] $x$년 후의 나이로 식을 세운다.\n\n[조건 정리]\n$42+x = 3(12+x)$\n\n[풀이 과정]\n$42 + x = 36 + 3x$\n$2x = 6$, $x = 3$\n\n[결론] 따라서 $3$년 후이다."
  },
  {
    id: 20,
    level: "하",
    category: "일차방정식의 활용 - 예금액",
    originalCategory: "문자와 식",
    standardCourse: "중1 수학",
    standardUnitKey: "M1-03",
    standardUnit: "문자와 식",
    standardUnitOrder: 3,
    content: "현재 형의 예금액은 $15000$원, 동생의 예금액은 $9000$원이다. 매달 형은 $1000$원, 동생은 $2000$원씩 예금한다면, 동생의 예금액이 형의 예금액보다 $2000$원 더 많아지는 것은 몇 개월 후인가?",
    choices: ["① $6$개월", "② $7$개월", "③ $8$개월", "④ $9$개월", "⑤ $10$개월"],
    answer: "③",
    solution: "[키포인트] $x$개월 후의 예금액 식을 세운다.\n\n[조건 정리]\n$(9000 + 2000x) = (15000 + 1000x) + 2000$\n\n[풀이 과정]\n$9000 + 2000x = 17000 + 1000x$\n$1000x = 8000$, $x = 8$\n\n[결론] 따라서 $8$개월 후이다."
  }
];