window.examTitle = "단항식의계산_중2_유형1";

window.questionBank = [
  {
    id: 1,
    level: "하",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$3^2 \\\\times 3^a \\\\times 3^3 = 729$일 때, 자연수 $a$의 값은?",
    choices: ["2", "5", "4", "3", "1"],
    answer: "⑤",
    solution: "[키포인트] 밑이 같은 거듭제곱의 곱셈은 지수의 합과 같음을 이용한다. [cite: 57, 89]\\n$3^2 \\\\times 3^a \\\\times 3^3 = 3^{2+a+3} = 3^{a+5}$\\n$729$를 소인수분해하면 $729 = 3^6$이다.\\n$3^{a+5} = 3^6$에서 $a+5=6$이므로 $a=1$이다.\\n$\\\\therefore$ ⑤"
  },
  {
    id: 2,
    level: "하",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x^2 \\\\times y^4 \\\\times x \\\\times y^3$을 간단히 하면?",
    choices: ["$x^3 y^{12}$", "$x^2 y^7$", "$x^3 y^7$", "$x^2 y^{12}$", "$x^3 y^4$"],
    answer: "③",
    solution: "[키포인트] 같은 문자끼리 지수법칙을 적용하여 정리한다. [cite: 57, 89]\\n$x^2 \\\\times y^4 \\\\times x \\\\times y^3 = (x^2 \\\\times x) \\\\times (y^4 \\\\times y^3) = x^{2+1} \\\\times y^{4+3} = x^3 y^7$\\n$\\\\therefore x^3 y^7$"
  },
  {
    id: 3,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "자연수 $x, y$에 대하여 $x+y=6$이고 $A=2^x, B=2^y$일 때, $AB$의 값을 구하시오.",
    choices: [],
    answer: "64",
    solution: "[키포인트] 두 수의 곱을 지수의 합으로 나타낸 후 조건을 대입한다. [cite: 57, 89]\\n$AB = 2^x \\\\times 2^y = 2^{x+y}$\\n주어진 조건에서 $x+y=6$이므로\\n$AB = 2^6 = 64$\\n$\\\\therefore 64$"
  },
  {
    id: 4,
    level: "하",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$3^x \\\\times (3^2)^4 = 3^{12}$일 때, 자연수 $x$의 값을 구하시오.",
    choices: [],
    answer: "4",
    solution: "[키포인트] 거듭제곱의 거듭제곱은 지수의 곱임을 이용한다. [cite: 57, 89]\\n$3^x \\\\times 3^{2 \\\\times 4} = 3^x \\\\times 3^8 = 3^{x+8}$\\n$3^{x+8} = 3^{12}$에서 $x+8=12$이므로 $x=4$이다.\\n$\\\\therefore 4$"
  },
  {
    id: 5,
    level: "상",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$8^{x+1} = 2^{2x+7}$일 때, 자연수 $x$의 값을 구하시오.",
    choices: [],
    answer: "4",
    solution: "[키포인트] 밑을 $2$로 통일하여 지수방정식을 풀이한다. [cite: 57, 89]\\n$8 = 2^3$이므로 주어진 식은\\n$(2^3)^{x+1} = 2^{2x+7}$\\n$2^{3(x+1)} = 2^{2x+7}$\\n지수를 비교하면 $3x+3 = 2x+7$\\n$x = 4$\\n$\\\\therefore 4$"
  },
  {
    id: 6,
    level: "하",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 옳은 것은?",
    choices: ["$x^8 \\\\div x^4 = x^2$", "$(x^2)^5 \\\\div x^3 = x^8$", "$x^6 \\\\div x^6 = 0$", "$x^5 \\\\div x \\\\div x^2 = x^2$", "$x^3 \\\\div x^9 = x^6$"],
    answer: "④",
    solution: "[키포인트] 나눗셈의 지수법칙($x^m \\\\div x^n$)을 정확히 적용한다. [cite: 57, 89]\\n① $x^8 \\\\div x^4 = x^{8-4} = x^4$ (옳지 않음)\\n② $(x^2)^5 \\\\div x^3 = x^{10} \\\\div x^3 = x^{10-3} = x^7$ (옳지 않음) [cite: 128]\\n③ $x^6 \\\\div x^6 = 1$ (옳지 않음)\\n④ $x^5 \\\\div x \\\\div x^2 = x^{5-1-2} = x^2$ (옳음)\\n⑤ $x^3 \\\\div x^9 = \\\\frac{1}{x^{9-3}} = \\\\frac{1}{x^6}$ (옳지 않음)\\n따라서 옳은 것은 ④이다.\\n$\\\\therefore$ ④"
  },
  {
    id: 7,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x^{12} \\\\div x^{\\\\Box} \\\\div (x^2)^4 = x^2$일 때, $\\\\Box$ 안에 알맞은 수를 구하시오.",
    choices: [],
    answer: "2",
    solution: "[키포인트] 지수법칙의 차를 이용하여 미지수 $\\\\Box$를 구한다. [cite: 57, 89]\\n$x^{12} \\\\div x^{\\\\Box} \\\\div x^8 = x^2$\\n좌변을 정리하면 $x^{12 - \\\\Box - 8} = x^{4 - \\\\Box}$\\n$x^{4 - \\\\Box} = x^2$이므로 $4 - \\\\Box = 2$\\n$\\\\therefore \\\\Box = 2$"
  },
  {
    id: 8,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(-2x^a y^2)^b = -8x^9 y^c$일 때, 자연수 $a, b, c$에 대하여 $a+b+c$의 값은?",
    choices: ["12", "9", "14", "10", "8"],
    answer: "①",
    solution: "[키포인트] 단항식의 거듭제곱에서 계수와 문자별 지수를 각각 비교한다. [cite: 57, 89, 137]\\n$(-2x^a y^2)^b = (-2)^b x^{ab} y^{2b} = -8x^9 y^c$\\n$(-2)^b = -8$에서 $b=3$이다.\\n$x^{ab} = x^{3a} = x^9$에서 $3a=9$이므로 $a=3$이다.\\n$y^{2b} = y^{2 \\\\times 3} = y^6 = y^c$에서 $c=6$이다.\\n$\\\\therefore a+b+c = 3+3+6 = 12$ [cite: 128]\\n$\\\\therefore$ ①"
  },
  {
    id: 9,
    level: "하",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 옳지 않은 것은?",
    choices: ["$(2a^3 b)^2 = 4a^6 b^2$", "$(\\\\frac{1}{3}xy^2)^3 = \\\\frac{1}{9}x^3 y^6$", "$(-x^3 y^2)^4 = x^{12} y^8$", "$(-3a^2)^3 = -27a^6$", "$(-x^2 y z^3)^5 = -x^{10} y^5 z^{15}$"],
    answer: "②",
    solution: "[키포인트] 지수의 분배법칙을 적용할 때 계수의 거듭제곱을 누락하지 않도록 주의한다. [cite: 57, 89]\\n① $(2a^3 b)^2 = 2^2 a^{3 \\\\times 2} b^2 = 4a^6 b^2$ (옳음)\\n② $(\\\\frac{1}{3}xy^2)^3 = (\\\\frac{1}{3})^3 x^3 y^{2 \\\\times 3} = \\\\frac{1}{27}x^3 y^6$ (옳지 않음, $\\\\frac{1}{9}$ 아님)\\n③ $(-x^3 y^2)^4 = (-1)^4 x^{12} y^8 = x^{12} y^8$ (옳음)\\n④ $(-3a^2)^3 = (-3)^3 a^6 = -27a^6$ (옳음)\\n⑤ $(-x^2 y z^3)^5 = (-1)^5 x^{10} y^5 z^{15} = -x^{10} y^5 z^{15}$ (옳음)\\n따라서 옳지 않은 것은 ②이다.\\n$\\\\therefore$ ②"
  },
  {
    id: 10,
    level: "상",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$1000^2 = (2^x \\\\times 5^y)^2 = 2^a \\\\times 5^b$일 때, 자연수 $x, y$에 대하여 $x+y$의 값을 구하시오.",
    choices: [],
    answer: "6",
    solution: "[키포인트] $1000$을 소인수분해하여 지수법칙을 적용한다. [cite: 57, 89]\\n$1000 = 10^3 = (2 \\\\times 5)^3 = 2^3 \\\\times 5^3$이다.\\n따라서 $1000^2 = (2^3 \\\\times 5^3)^2 = 2^6 \\\\times 5^6$\\n$(2^x \\\\times 5^y)^2 = 2^{2x} \\\\times 5^{2y}$이므로\\n$2x = 6, 2y = 6$에서 $x=3, y=3$이다.\\n$\\\\therefore x+y = 3+3 = 6$"
  },
  {
    id: 11,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$ \\\\left( \\\\frac{3x^a}{y^2} \\\\right)^3 = \\\\frac{bx^9}{y^c} $일 때, 자연수 $a, b, c$에 대하여 $a+b-c$의 값은?",
    choices: ["24", "30", "18", "12", "36"],
    answer: "①",
    solution: "[키포인트] 분수 형태의 단항식 거듭제곱을 전개하여 계수와 지수를 비교한다. [cite: 57, 89]\\n$ \\\\left( \\\\frac{3x^a}{y^2} \\\\right)^3 = \\\\frac{3^3 x^{3a}}{y^{2 \\\\times 3}} = \\\\frac{27x^{3a}}{y^6} $\\n이를 $ \\\\frac{bx^9}{y^c} $와 비교하면\\n$ b = 27 $\\n$ 3a = 9 \\\\implies a = 3 $\\n$ c = 6 $\\n$\\\\therefore a+b-c = 3+27-6 = 24$\\n$\\\\therefore$ ①"
  },
  {
    id: 12,
    level: "하",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 옳은 것은?",
    choices: ["$ (ab^2)^4 = ab^8 $", "$ (-5x)^2 = -25x^2 $", "$ \\\\left( \\\\frac{x^2}{y} \\\\right)^3 = \\\\frac{x^6}{y^3} $", "$ \\\\left( -\\\\frac{a}{3} \\\\right)^2 = -\\\\frac{a^2}{9} $", "$ \\\\left( -\\\\frac{b^2}{2a} \\\\right)^3 = \\\\frac{b^6}{8a^3} $"],
    answer: "③",
    solution: "[키포인트] 음수 부호와 분모의 지수법칙 적용 여부를 확인한다. [cite: 57, 89]\\n① $ (ab^2)^4 = a^4 b^8 $ (옳지 않음)\\n② $ (-5x)^2 = 25x^2 $ (옳지 않음)\\n③ $ \\\\left( \\\\frac{x^2}{y} \\\\right)^3 = \\\\frac{x^6}{y^3} $ (옳음)\\n④ $ \\\\left( -\\\\frac{a}{3} \\\\right)^2 = \\\\frac{a^2}{9} $ (옳지 않음)\\n⑤ $ \\\\left( -\\\\frac{b^2}{2a} \\\\right)^3 = -\\\\frac{b^6}{8a^3} $ (옳지 않음)\\n따라서 옳은 것은 ③이다.\\n$\\\\therefore$ ③"
  },
  {
    id: 13,
    level: "하",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$ 3^{15} + 3^{15} + 3^{15} $를 간단히 하면?",
    choices: ["$ 3^{16} $", "$ 3^{18} $", "$ 3^{45} $", "$ 9^{15} $", "$ 3^{14} $"],
    answer: "①",
    solution: "[키포인트] 같은 수의 합을 곱셈으로 나타낸 후 지수법칙을 적용한다. [cite: 57, 89]\\n$ 3^{15} + 3^{15} + 3^{15} = 3 \\\\times 3^{15} = 3^{1+15} = 3^{16} $\\n$\\\\therefore 3^{16} $"
  },
  {
    id: 14,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$ 4^3 \\\\times 4^3 \\\\times 4^3 \\\\times 4^3 = 4^a, \\\\quad 6^4 + 6^4 + 6^4 + 6^4 + 6^4 + 6^4 = 6^b $일 때, 자연수 $a, b$에 대하여 $a+b$의 값을 구하시오.",
    choices: [],
    answer: "17",
    solution: "[키포인트] 거듭제곱의 곱셈과 덧셈을 구분하여 지수법칙을 적용한다. [cite: 57, 89]\\n① $ 4^3 \\\\times 4^3 \\\\times 4^3 \\\\times 4^3 = 4^{3+3+3+3} = 4^{12} $ 이므로 $ a=12 $\\n② $ 6^4 + 6^4 + 6^4 + 6^4 + 6^4 + 6^4 = 6 \\\\times 6^4 = 6^5 $ 이므로 $ b=5 $\\n$\\\\therefore a+b = 12+5 = 17$"
  },
  {
    id: 15,
    level: "상",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$ \\\\frac{5^8 + 5^8 + 5^8 + 5^8 + 5^8}{3^6 + 3^6 + 3^6} \\\\times \\\\frac{3^7 + 3^7 + 3^7}{5^9} $를 간단히 하면?",
    choices: ["$ 1 $", "$ 3 $", "$ 5 $", "$ \\\\frac{1}{3} $", "$ \\\\frac{1}{5} $"],
    answer: "②",
    solution: "[키포인트] 분자와 분모의 덧셈을 곱셈으로 바꾼 후 약분하여 정리한다. [cite: 57, 89]\\n$ \\\\frac{5 \\\\times 5^8}{3 \\\\times 3^6} \\\\times \\\\frac{3 \\\\times 3^7}{5^9} = \\\\frac{5^9}{3^7} \\\\times \\\\frac{3^8}{5^9} = \\\\frac{3^8}{3^7} = 3 $\\n$\\\\therefore$ ②"
  },
  {
    id: 16,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$A=2^{x+2}$일 때, $16^x$을 $A$를 사용하여 나타내면?",
    choices: ["$ \\\\frac{A^4}{256} $", "$ 16A^4 $", "$ \\\\frac{A^4}{16} $", "$ \\\\frac{A^4}{64} $", "$ 256A^4 $"],
    answer: "①",
    solution: "[키포인트] 주어진 식을 $2^x$에 관하여 정리한 후 대입한다. [cite: 57, 89]\\n$A = 2^{x+2} = 2^x \\\\times 2^2 = 4 \\\\times 2^x$이므로 $2^x = \\\\frac{A}{4}$이다.\\n$16^x = (2^4)^x = (2^x)^4$이므로\\n$16^x = \\\\left( \\\\frac{A}{4} \\\\right)^4 = \\\\frac{A^4}{256}$\\n$\\\\therefore \\\\frac{A^4}{256}$"
  },
  {
    id: 17,
    level: "상",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$3^x=A, 5^x=B$일 때, $45^x$를 $A, B$를 사용하여 나타내면?",
    choices: ["$ A^2B^4 $", "$ A^4B^2 $", "$ AB^2 $", "$ A^2B $", "$ A^4B^4 $"],
    answer: "④",
    solution: "[키포인트] $45$를 소인수분해하여 $3^x$와 $5^x$ 꼴로 변형한다. [cite: 57, 89]\\n$45 = 3^2 \\\\times 5$이므로\\n$45^x = (3^2 \\\\times 5)^x = 3^{2x} \\\\times 5^x = (3^x)^2 \\\\times 5^x$\\n$3^x=A, 5^x=B$를 대입하면 $A^2 B$가 된다. [cite: 128]\\n$\\\\therefore A^2 B$"
  },
  {
    id: 18,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$5^8 \\\\times 2^{11}$이 $n$자리 자연수일 때, $n$의 값은?",
    choices: ["8", "10", "11", "9", "12"],
    answer: "④",
    solution: "[키포인트] $2^m \\\\times 5^m = 10^m$ 꼴을 만들어 자릿수를 계산한다. [cite: 57, 89]\\n$5^8 \\\\times 2^{11} = 5^8 \\\\times 2^8 \\\\times 2^3 = (5 \\\\times 2)^8 \\\\times 8 = 8 \\\\times 10^8$\\n$8 \\\\times 10^8$은 $8$ 뒤에 $0$이 $8$개 붙는 수이므로 $1+8=9$자리 자연수이다.\\n$\\\\therefore$ ④"
  },
  {
    id: 19,
    level: "상",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$2^7 \\\\times 9^2 \\\\times 5^6$은 몇 자리 자연수인지 구하시오.",
    choices: [],
    answer: "9",
    solution: "[키포인트] $10$의 거듭제곱을 묶어내고 남은 수의 자릿수를 더한다. [cite: 57, 89]\\n$2^7 \\\\times 9^2 \\\\times 5^6 = (2^6 \\\\times 5^6) \\\\times 2^1 \\\\times 81 = 10^6 \\\\times 162$\\n$162$는 $3$자리 수이고 뒤에 $0$이 $6$개 붙으므로 $3+6=9$자리 자연수이다.\\n$\\\\therefore 9$"
  },
  {
    id: 20,
    level: "상",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$ \\\\frac{2^{12} \\\\times 15^7}{12^6} $이 $n$자리 자연수일 때, $n$의 값을 구하시오.",
    choices: [],
    answer: "6",
    solution: "[키포인트] 분수 식을 소인수분해하여 지수법칙으로 약분한 후 자릿수를 구한다. [cite: 57, 89]\\n$ \\\\frac{2^{12} \\\\times (3 \\\\times 5)^7}{(2^2 \\\\times 3)^6} = \\\\frac{2^{12} \\\\times 3^7 \\\\times 5^7}{2^{12} \\\\times 3^6} = 3^{7-6} \\\\times 5^7 = 3 \\\\times 5^7$\\n$3 \\\\times 5^7 = 3 \\\\times 78125 = 234375$이므로 $6$자리 자연수이다.\\n$\\\\therefore 6$"
  },
  {
    id: 21,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어떤 박테리아는 $1$시간마다 그 수가 $2$배씩 증가한다. 이 박테리아 $8$마리가 $n$시간 후에 $2^{10}$마리가 된다고 할 때, 자연수 $n$의 값은?",
    choices: ["8", "5", "9", "7", "6"],
    answer: "④",
    solution: "[키포인트] 시간에 따른 변화량을 지수법칙을 활용한 식으로 세운다. [cite: 57, 89]\\n$n$시간 후에는 처음 수의 $2^n$배가 된다.\\n처음 박테리아 수가 $8$마리이므로 $n$시간 후의 마리 수는 $8 \\\\times 2^n = 2^{3+n}$이다.\\n$2^{3+n} = 2^{10}$에서 $3+n=10$이므로 $n=7$이다.\\n$\\\\therefore$ ④"
  },
  {
    id: 22,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "종이 한 장을 반으로 접으면 그 두께는 처음의 $2$배가 된다. 두께가 $0.5$ mm인 종이 한 장을 반으로 $8$번 접었을 때 종이의 두께는 $(0.5 \\\\times 2^a)$ mm이다. 이때 자연수 $a$의 값을 구하시오.",
    choices: [],
    answer: "8",
    solution: "[키포인트] 반으로 접는 횟수를 지수로 나타내어 식을 구성한다. [cite: 57, 89]\\n반으로 $n$번 접으면 두께는 $2^n$배가 된다.\\n$8$번 접었으므로 두께는 처음 두께의 $2^8$배이다.\\n따라서 $0.5 \\\\times 2^8$이므로 $a=8$이다.\\n$\\\\therefore 8$"
  },
  {
    id: 23,
    level: "상",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "용량이 $4$ GB인 메모리 카드에 용량이 $16$ MB인 동영상을 최대 몇 개까지 저장할 수 있는가? (단, 아래 단위 표를 참고하시오.)\\n\\n<table class=\\\"question-table\\\">\\n<thead>\\n<tr>\\n<th>단위</th>\\n<th>용량</th>\\n</tr>\\n</thead>\\n<tbody>\\n<tr>\\n<td>KB(킬로바이트)</td>\\n<td>$2^{10}$ B</td>\\n</tr>\\n<tr>\\n<td>MB(메가바이트)</td>\\n<td>$2^{20}$ B</td>\\n</tr>\\n<tr>\\n<td>GB(기가바이트)</td>\\n<td>$2^{30}$ B</td>\\n</tr>\\n</tbody>\\n</table>",
    choices: ["$2^8$개", "$2^{10}$개", "$2^6$개", "$2^7$개", "$2^9$개"],
    answer: "①",
    solution: "[키포인트] 전체 용량을 개별 용량으로 나눌 때 밑이 $2$인 지수법칙을 사용한다. [cite: 57, 89]\\n$4\\\\text{ GB} = 2^2 \\\\times 2^{30}\\\\text{ B} = 2^{32}\\\\text{ B}$\\n$16\\\\text{ MB} = 2^4 \\\\times 2^{20}\\\\text{ B} = 2^{24}\\\\text{ B}$\\n저장 가능한 개수는 $2^{32} \\\\div 2^{24} = 2^{32-24} = 2^8$(개)이다. [cite: 195, 233]\\n$\\\\therefore$ ①"
  },
  {
    id: 24,
    level: "중",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$(2x^2y)^3 \\\\times \\\\left( -\\\\frac{1}{2}xy^2 \\\\right)^2 \\\\times (-x^3y)^2$을 계산하면?",
    choices: ["$4x^{14}y^9$", "$-2x^8y^7$", "$2x^{14}y^9$", "$-4x^{11}y^5$", "$2x^{12}y^8$"],
    answer: "③",
    solution: "[키포인트] 각 항의 거듭제곱을 먼저 계산한 후 전체 식을 곱한다. [cite: 57, 89]\\n$(2x^2y)^3 = 8x^6y^3$, $\\\\left( -\\\\frac{1}{2}xy^2 \\\\right)^2 = \\\\frac{1}{4}x^2y^4$, $(-x^3y)^2 = x^6y^2$이므로\\n$8x^6y^3 \\\\times \\\\frac{1}{4}x^2y^4 \\\\times x^6y^2 = 2x^{14}y^9$\\n$\\\\therefore$ ③"
  },
  {
    id: 25,
    level: "상",
    category: "수와 식",
    originalCategory: "수학 > 중등 2-1 > 식의 계산",
    standardCourse: "중2 수학",
    standardUnitKey: "M2-01",
    standardUnit: "수와 식",
    standardUnitOrder: 1,
    questionType: "주관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$4x^2y \\\\times (-x^3y^2)^3 \\\\times \\\\left( -\\\\frac{1}{2}xy \\\\right)^2 = ax^by^c$일 때, 상수 $a, b, c$에 대하여 $a+b+c$의 값을 구하시오.",
    choices: [],
    answer: "21",
    solution: "[키포인트] 혼합 계산에서 부호와 계수, 문자의 지수를 차례로 정리한다. [cite: 57, 89]\\n$4x^2y \\\\times (-x^9y^6) \\\\times \\\\frac{1}{4}x^2y^2 = (4 \\\\times -1 \\\\times \\\\frac{1}{4}) \\\\times x^{2+9+2}y^{1+6+2} = -1x^{13}y^9$\\n따라서 $a=-1, b=13, c=9$이므로 $a+b+c = -1+13+9 = 21$이다.\\n$\\\\therefore 21$"
  }
];