window.examTitle = "비상대수지수로그익힘책_고2_유형심화";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$64$의 여섯제곱근 중에서 실수인 것의 개수를 $a$, $-32$의 다섯제곱근 중에서 실수인 것의 개수를 $b$, $0$의 세제곱근 중에서 실수인 것의 개수를 $c$라고 할 때, $a+2b+c$의 값을 구하시오.",
    choices: [],
    answer: "$5$",
    solution: "[키포인트] 양수의 짝수제곱근, 음수의 홀수제곱근, $0$의 거듭제곱근의 실수 개수를 각각 구분한다.\\n조건 정리: $64$는 양수이고 여섯제곱근을 묻고 있으므로 짝수제곱근이다. $-32$는 음수이고 다섯제곱근을 묻고 있으므로 홀수제곱근이다. $0$의 세제곱근도 실수로 존재한다.\\n풀이 방향: 각 거듭제곱근 중 실수인 것의 개수를 구한 뒤 식 $a+2b+c$에 대입한다.\\n정석 풀이: 양수의 짝수제곱근은 양수와 음수 2개의 실수값을 가지므로 $a=2$이다. 음수의 홀수제곱근은 실수 1개를 가지므로 $b=1$이다. 또한 $0$의 세제곱근은 $0$ 하나뿐이므로 $c=1$이다. 따라서 $a+2b+c=2+2\\times1+1=5$이다.\\n따라서 구하는 값은 $5$이다."
  },
  {
    id: 2,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\sqrt[4]{(-2)^4}+\\sqrt[3]{(-6)^3}-\\sqrt{(-7)^2}$의 값을 구하시오.",
    choices: [],
    answer: "$-11$",
    solution: "[키포인트] 짝수제곱근의 주값은 양수이고, 홀수제곱근은 부호까지 그대로 따라간다.\\n조건 정리: $\\sqrt[4]{(-2)^4}$와 $\\sqrt{(-7)^2}$는 짝수제곱근의 주값이고, $\\sqrt[3]{(-6)^3}$은 홀수제곱근이다.\\n풀이 방향: 각 항의 값을 먼저 정확히 구한 뒤 덧셈과 뺄셈을 계산한다.\\n정석 풀이: $\\sqrt[4]{(-2)^4}=2$이고, $\\sqrt[3]{(-6)^3}=-6$이다. 또한 $\\sqrt{(-7)^2}=7$이다. 따라서 주어진 식의 값은 $2+(-6)-7=-11$이다.\\n따라서 구하는 값은 $-11$이다."
  },
  {
    id: 3,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log_2\\dfrac{1}{16}+\\log_2 12-\\log_2 3+3\\log_2\\sqrt{2}$를 간단히 하시오.",
    choices: [],
    answer: "$-\\dfrac{1}{2}$",
    solution: "[키포인트] 로그의 차는 몫의 로그로 정리하고, 거듭제곱 꼴은 지수로 계산한다.\\n조건 정리: $\\dfrac{1}{16}=2^{-4}$, $\\sqrt{2}=2^{\\frac{1}{2}}$이다. 또한 $\\log_2 12-\\log_2 3=\\log_2 4$이다.\\n풀이 방향: 각 부분을 간단히 계산한 뒤 모두 더한다.\\n정석 풀이: $\\log_2\\dfrac{1}{16}=\\log_2 2^{-4}=-4$이다. 또 $\\log_2 12-\\log_2 3=\\log_2\\dfrac{12}{3}=\\log_2 4=2$이다. 마지막으로 $3\\log_2\\sqrt{2}=3\\log_2 2^{\\frac{1}{2}}=3\\times\\dfrac{1}{2}=\\dfrac{3}{2}$이다. 따라서 전체 값은 $-4+2+\\dfrac{3}{2}=-\\dfrac{1}{2}$이다.\\n따라서 구하는 값은 $-\\dfrac{1}{2}$이다."
  },
  {
    id: 4,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log 2=a$, $\\log 3=b$, $\\log 5=c$일 때, $\\log\\dfrac{45}{8}+\\log\\dfrac{12}{5}$를 $a,b,c$에 대한 식으로 나타내시오.",
    choices: [],
    answer: "$3b-a$",
    solution: "[키포인트] 로그의 합을 하나로 합치거나 각각 분해하여 주어진 문자로 나타낸다.\\n조건 정리: $45=3^2\\times5$, $8=2^3$, $12=2^2\\times3$이다.\\n풀이 방향: 두 로그를 각각 $a,b,c$로 나타낸 뒤 더한다.\\n정석 풀이: $\\log\\dfrac{45}{8}=\\log45-\log8=(2\\log3+\log5)-3\\log2=2b+c-3a$이다. 또 $\\log\\dfrac{12}{5}=\\log12-\log5=(2\\log2+\log3)-\log5=2a+b-c$이다. 따라서 두 식의 합은 $(2b+c-3a)+(2a+b-c)=3b-a$이다.\\n따라서 구하는 값은 $3b-a$이다."
  },
  {
    id: 5,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a>1$일 때, 다음을 만족시키는 자연수 $k$의 값을 구하시오.\\n\\n$\\dfrac{\\sqrt[4]{a^3}\\times\\sqrt[k]{a^3}}{\\sqrt{a}}=\\sqrt[8]{a^5}$",
    choices: [],
    answer: "$8$",
    solution: "[키포인트] 근호를 모두 유리수 지수로 바꾸고, 곱셈과 나눗셈은 지수의 덧셈과 뺄셈으로 처리한다.\\n조건 정리: $a>1$이므로 양변을 같은 밑 $a$의 거듭제곱으로 나타내면 지수를 비교할 수 있다.\\n풀이 방향: 좌변과 우변을 각각 $a$의 지수 형태로 바꾸어 $k$에 대한 방정식을 세운다.\\n정석 풀이: $\\sqrt[4]{a^3}=a^{\\frac{3}{4}}$, $\\sqrt[k]{a^3}=a^{\\frac{3}{k}}$, $\\sqrt{a}=a^{\\frac{1}{2}}$, $\\sqrt[8]{a^5}=a^{\\frac{5}{8}}$이다. 따라서 좌변은 $\\dfrac{a^{\\frac{3}{4}}\\times a^{\\frac{3}{k}}}{a^{\\frac{1}{2}}}=a^{\\frac{3}{4}+\\frac{3}{k}-\\frac{1}{2}}=a^{\\frac{1}{4}+\\frac{3}{k}}$이다. 양변의 지수를 비교하면 $\\dfrac{1}{4}+\\dfrac{3}{k}=\\dfrac{5}{8}$이다. 따라서 $\\dfrac{3}{k}=\\dfrac{5}{8}-\\dfrac{2}{8}=\\dfrac{3}{8}$이므로 $k=8$이다.\\n따라서 구하는 값은 $8$이다."
  },
  {
    id: 6,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x=\\sqrt[3]{5}-\\dfrac{1}{\\sqrt[3]{5}}$일 때, $x^3+3x$의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{24}{5}$",
    solution: "[키포인트] $x=t-\\dfrac{1}{t}$ 꼴에서는 $x^3+3x=t^3-\\dfrac{1}{t^3}$으로 정리된다.\\n조건 정리: $t=\\sqrt[3]{5}$라고 두면 $x=t-\\dfrac{1}{t}$이다.\\n풀이 방향: 세제곱 공식을 이용하여 $x^3+3x$를 $t^3$과 $\\dfrac{1}{t^3}$만 남도록 정리한다.\\n정석 풀이: $x=t-\\dfrac{1}{t}$이면 $x^3=\\left(t-\\dfrac{1}{t}\\right)^3=t^3-3t+\\dfrac{3}{t}-\\dfrac{1}{t^3}$이다. 여기에 $3x=3t-\\dfrac{3}{t}$를 더하면 중간항이 소거되어 $x^3+3x=t^3-\\dfrac{1}{t^3}$이다. $t^3=5$이므로 $\\dfrac{1}{t^3}=\\dfrac{1}{5}$이다. 따라서 $x^3+3x=5-\\dfrac{1}{5}=\\dfrac{24}{5}$이다.\\n따라서 구하는 값은 $\\dfrac{24}{5}$이다."
  },
  {
    id: 7,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "실수 $x,y$에 대하여 $(\\sqrt{2})^x=16$, $9^y=3$일 때, $\\dfrac{3}{x}+\\dfrac{1}{y}$의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{19}{8}$",
    solution: "[키포인트] 밑을 소수의 거듭제곱으로 통일하여 지수를 비교한다.\\n조건 정리: $\\sqrt{2}=2^{\\frac{1}{2}}$, $16=2^4$, $9=3^2$이다.\\n풀이 방향: $x,y$를 각각 구한 뒤 주어진 식에 대입한다.\\n정석 풀이: $(\\sqrt{2})^x=(2^{\\frac{1}{2}})^x=2^{\\frac{x}{2}}$이고 $16=2^4$이므로 $\\dfrac{x}{2}=4$, 즉 $x=8$이다. 또 $9^y=(3^2)^y=3^{2y}$이고 $3=3^1$이므로 $2y=1$, 즉 $y=\\dfrac{1}{2}$이다. 따라서 $\\dfrac{3}{x}+\\dfrac{1}{y}=\\dfrac{3}{8}+2=\\dfrac{19}{8}$이다.\\n따라서 구하는 값은 $\\dfrac{19}{8}$이다."
  },
  {
    id: 8,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\dfrac{2^{x+1}+2^{-x}}{2^x+2^{-x}}=\\dfrac{5}{3}$일 때, $2^{2x}$의 값을 구하시오.",
    choices: [],
    answer: "$2$",
    solution: "[키포인트] $2^x$를 문자로 치환하면 $2^{2x}$에 대한 일차식으로 정리된다.\\n조건 정리: $2^x=t$라고 두면 $2^{-x}=\\dfrac{1}{t}$이고, 구하는 값은 $2^{2x}=t^2$이다.\\n풀이 방향: 분자와 분모에 $t$를 곱하여 $t^2$에 대한 방정식을 만든다.\\n정석 풀이: $2^{x+1}=2\\cdot2^x=2t$이므로 주어진 식은 $\\dfrac{2t+\\frac{1}{t}}{t+\\frac{1}{t}}=\\dfrac{5}{3}$이다. 분자와 분모에 $t$를 곱하면 $\\dfrac{2t^2+1}{t^2+1}=\\dfrac{5}{3}$이다. 양변을 정리하면 $3(2t^2+1)=5(t^2+1)$이므로 $6t^2+3=5t^2+5$이다. 따라서 $t^2=2$이다. 그러므로 $2^{2x}=t^2=2$이다.\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 9,
    level: "상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "모든 실수 $x$에 대하여 $\\log_{p+2}(x^2-2px+3p)$이 정의되도록 하는 정수 $p$를 모두 구하시오.",
    choices: [],
    answer: "$1,\\ 2$",
    solution: "[키포인트] 로그가 모든 실수 $x$에 대하여 정의되려면 밑 조건과 진수의 항상 양수 조건을 동시에 만족해야 한다.\\n조건 정리: 로그의 밑은 $p+2$이고 진수는 $x^2-2px+3p$이다. 로그의 밑 조건은 $p+2\\gt0$, $p+2\\ne1$이다. 또한 진수는 모든 실수 $x$에 대하여 양수이어야 한다.\\n풀이 방향: 먼저 밑 조건을 정리한 뒤, 이차식 $x^2-2px+3p$가 모든 실수에서 양수가 되는 조건을 판별식으로 구한다. 마지막으로 정수 $p$만 고른다.\\n정석 풀이: 밑 조건에서 $p+2\\gt0$이므로 $p\\gt-2$이고, $p+2\\ne1$이므로 $p\\ne-1$이다. 이제 진수 $x^2-2px+3p$가 모든 실수 $x$에 대하여 양수이어야 한다. 최고차항 계수가 $1\\gt0$이므로 이차식이 항상 양수이려면 판별식이 음수이어야 한다. 판별식을 $D$라 하면 $D=(-2p)^2-4\\cdot1\\cdot3p=4p^2-12p=4p(p-3)$이다. 따라서 $D\\lt0$이므로 $p(p-3)\\lt0$이고, $0\\lt p\\lt3$이다. 이 범위 안의 정수는 $p=1,2$이다. 이 두 값은 밑 조건 $p\\gt-2$, $p\\ne-1$도 모두 만족한다.\\n핵심 확인: 모든 실수 $x$에 대하여 로그가 정의되어야 하므로 특정 $x$에서만 진수가 양수인 조건이 아니라, 진수가 항상 양수인 조건을 사용해야 한다.\\n따라서 구하는 값은 $1,\\ 2$이다."
  },
  {
    id: 10,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 실수 $a,b$가 $2^a=7$, $7^b=5$를 만족시킬 때, $\\log_5\\dfrac{28}{25}$를 $a,b$에 대한 식으로 나타내시오.",
    choices: [],
    answer: "$\\dfrac{a+2}{ab}-2$",
    solution: "[키포인트] 주어진 지수 관계를 로그 관계로 바꾸고, 밑변환을 이용하여 모두 $a,b$로 표현한다.\\n조건 정리: $2^a=7$이므로 $a=\\log_2 7$이고, $7^b=5$이므로 $b=\\log_7 5$이다.\\n풀이 방향: $\\log_5\\dfrac{28}{25}=\\log_5 28-\log_5 25$로 나누어 계산한다.\\n정석 풀이: $\\log_5 25=2$이다. 또한 $28=4\\times7=2^2\\times7$이므로 $\\log_5 28=\log_5 2^2+\log_5 7=2\log_5 2+\log_5 7$이다. $\\log_5 7=\\dfrac{1}{\\log_7 5}=\\dfrac{1}{b}$이다. 또 $5=7^b=(2^a)^b=2^{ab}$이므로 $\\log_2 5=ab$이고, 따라서 $\\log_5 2=\\dfrac{1}{ab}$이다. 그러므로 $\\log_5 28=\\dfrac{2}{ab}+\\dfrac{1}{b}=\\dfrac{2+a}{ab}$이다. 따라서 $\\log_5\\dfrac{28}{25}=\\dfrac{a+2}{ab}-2$이다.\\n따라서 구하는 값은 $\\dfrac{a+2}{ab}-2$이다."
  },
  {
    id: 11,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$A=\\log_2(\\log_3 81)+\\log_3(\\log_2 512)$일 때, $A^2$의 값을 구하시오.",
    choices: [],
    answer: "$16$",
    solution: "[키포인트] 괄호 안의 로그를 먼저 계산한 뒤 바깥 로그값을 구한다.\\n조건 정리: $81=3^4$, $512=2^9$이다.\\n풀이 방향: $A$의 값을 먼저 구하고, 마지막에 제곱한다.\\n정석 풀이: $\\log_3 81=4$이므로 $\\log_2(\\log_3 81)=\\log_2 4=2$이다. 또 $\\log_2 512=9$이므로 $\\log_3(\\log_2 512)=\\log_3 9=2$이다. 따라서 $A=2+2=4$이고, $A^2=4^2=16$이다.\\n따라서 구하는 값은 $16$이다."
  },
  {
    id: 12,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$10<x<100$이고 $\\log x^5$와 $\\log x^2$의 차가 정수일 때, 가능한 모든 $\\log x$의 값의 합을 구하시오.",
    choices: [],
    answer: "$3$",
    solution: "[키포인트] $\\log x$를 하나의 문자로 두고 범위 조건과 정수 조건을 동시에 적용한다.\\n조건 정리: $10\\lt x\\lt100$이므로 $1\\lt\\log x\\lt2$이다.\\n풀이 방향: $\\log x^5$와 $\\log x^2$의 차를 $\\log x$로 나타낸 뒤 가능한 정수값을 찾는다.\\n정석 풀이: $\\log x^5=5\\log x$이고 $\\log x^2=2\\log x$이다. 따라서 두 값의 차는 $5\\log x-2\\log x=3\\log x$이다. $1\\lt\\log x\\lt2$이므로 $3\\lt3\\log x\\lt6$이다. 이 값이 정수이므로 가능한 값은 $4,5$이다. 따라서 $3\\log x=4$이면 $\\log x=\\dfrac{4}{3}$이고, $3\\log x=5$이면 $\\log x=\\dfrac{5}{3}$이다. 가능한 모든 $\\log x$의 값의 합은 $\\dfrac{4}{3}+\\dfrac{5}{3}=3$이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 13,
    level: "중",
    category: "집합",
    originalCategory: "집합",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-05",
    standardUnit: "집합",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 집합 $A=\\{1,2,3,4\\}$, $B=\\{-2,-1,0,1,2\\}$에 대하여 집합 $S$를 $S=\\{(a,b)\\mid a+b\\text{는 짝수},\\ ab\\le 2,\\ a\\in A,\\ b\\in B\\}$와 같이 정의하자. 다음 보기 중 옳은 것을 모두 고르시오.\\n\\n보기:\\nㄱ. $(2,-2)\\in S$\\nㄴ. $b=0$일 때, $(a,b)\\in S$를 만족시키는 $a$의 개수는 $2$이다.\\nㄷ. $n(S)=8$",
    choices: [],
    answer: "ㄱ, ㄴ",
    solution: "[키포인트] 조건 $a+b$가 짝수라는 것은 $a,b$의 홀짝성이 같다는 뜻이고, 여기에 $ab\\le2$ 조건을 함께 확인해야 한다.\\n조건 정리: $A=\\{1,2,3,4\\}$, $B=\\{-2,-1,0,1,2\\}$이다. $a+b$가 짝수이려면 $a,b$가 모두 홀수이거나 모두 짝수이어야 한다.\\n풀이 방향: 각 보기를 직접 확인하고, 전체 원소 개수는 $a$값별로 가능한 $b$를 세어 판단한다.\\n정석 풀이: ㄱ에서 $(2,-2)$는 $2+(-2)=0$으로 짝수이고, $2\\times(-2)=-4\\le2$이므로 $(2,-2)\\in S$이다. ㄴ에서 $b=0$일 때 $a+0$이 짝수이려면 $a$는 짝수이어야 한다. $A$의 짝수는 $2,4$이고, 이때 $ab=0\\le2$이므로 가능한 $a$의 개수는 $2$이다. ㄷ을 확인하기 위해 전체 원소 개수를 세면, $a=1$일 때 가능한 $b$는 $-1,1$로 $2$개, $a=2$일 때 가능한 $b$는 $-2,0$으로 $2$개, $a=3$일 때 가능한 $b$는 $-1$로 $1$개, $a=4$일 때 가능한 $b$는 $-2,0$으로 $2$개이다. 따라서 $n(S)=2+2+1+2=7$이므로 ㄷ은 옳지 않다.\\n따라서 구하는 것은 ㄱ, ㄴ이다."
  },
  {
    id: 14,
    level: "상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$12$ 이하의 두 자연수 $m,n$에 대하여 $2\\log_2 m-\\log_2 n$이 자연수가 되도록 하는 순서쌍 $(m,n)$의 개수를 구하시오.",
    choices: [],
    answer: "$12$",
    solution: "[키포인트] 로그식을 하나로 합쳐 $\\log_2\\dfrac{m^2}{n}$으로 만들고, 이 값이 자연수가 되는 조건을 순서쌍으로 센다.\\n조건 정리: $m,n$은 $12$ 이하의 자연수이고, $2\\log_2 m-\\log_2 n=\\log_2 m^2-\log_2 n=\\log_2\\dfrac{m^2}{n}$이다. 이 값이 자연수이려면 $\\dfrac{m^2}{n}=2^k$인 자연수 $k$가 존재해야 한다.\\n풀이 방향: $\\dfrac{m^2}{n}$이 $2$의 양의 정수 거듭제곱이 되어야 하므로, $m^2$에 포함된 홀수 인수는 $n$이 정확히 없애야 한다. $m=1$부터 $12$까지 가능한 $n$을 직접 세되, $n\\le12$ 조건과 로그값이 자연수라는 조건을 함께 확인한다.\\n정석 풀이: $m=1$이면 $m^2=1$이므로 $\\dfrac{m^2}{n}$이 $2$ 이상의 $2$의 거듭제곱이 될 수 없다. $m=2$이면 $m^2=4$이고 가능한 $n$은 $1,2$로 $2$개이다. $m=3$이면 $m^2=9$이고 홀수 인수 $9$를 없애려면 $n=9$가 필요하지만 값이 $1$이 되어 자연수가 아니므로 불가능하다. $m=4$이면 $m^2=16$이고 가능한 $n$은 $1,2,4,8$로 $4$개이다. $m=5$이면 $m^2=25$이고 $n\\le12$에서 홀수 인수 $25$를 없앨 수 없으므로 불가능하다. $m=6$이면 $m^2=36=2^2\\times9$이고 $n=9$일 때 $\\dfrac{36}{9}=4$이므로 $1$개이다. $m=7$이면 $49$의 홀수 인수 $49$를 $n\\le12$에서 없앨 수 없으므로 불가능하다. $m=8$이면 $m^2=64$이고 가능한 $n$은 $1,2,4,8$로 $4$개이다. $m=9$이면 $81$의 홀수 인수 $81$을 $n\\le12$에서 없앨 수 없으므로 불가능하다. $m=10$이면 $100=2^2\\times25$이고 $25$를 $n\\le12$에서 없앨 수 없으므로 불가능하다. $m=11$이면 $121$의 홀수 인수 $121$을 $n\\le12$에서 없앨 수 없으므로 불가능하다. $m=12$이면 $144=2^4\\times9$이고 $n=9$일 때 $\\dfrac{144}{9}=16$이므로 $1$개이다. 따라서 전체 순서쌍의 개수는 $2+4+1+4+1=12$개이다.\\n핵심 확인: $\\log_2\\dfrac{m^2}{n}$이 자연수이므로 $\\dfrac{m^2}{n}=1$인 경우는 제외해야 한다.\\n따라서 구하는 값은 $12$이다."
  },
  {
    id: 15,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 상품의 수요량 $D$와 판매 가격 $P$ 사이에는 $\\log D=k-\\dfrac{2}{3}\\log P$인 관계가 성립한다고 한다. 수요량이 처음의 $\\dfrac{1}{4}$배가 되려면 판매 가격은 처음의 몇 배가 되어야 하는지 구하시오.",
    choices: [],
    answer: "$8$배",
    solution: "[키포인트] 로그식을 지수 관계로 바꾸면 수요량은 가격의 $-\\dfrac{2}{3}$제곱에 비례한다.\\n조건 정리: $\\log D=k-\\dfrac{2}{3}\\log P$이고, 수요량이 처음의 $\\dfrac{1}{4}$배가 되는 가격의 배수를 구해야 한다.\\n풀이 방향: 먼저 $D$와 $P$의 관계를 비례식으로 바꾼 뒤, 가격이 처음의 $r$배가 된다고 놓고 $r$을 구한다.\\n정석 풀이: $k=\\log C$인 상수 $C$를 생각하면 $\\log D=\\log C+\\log P^{-\\frac{2}{3}}=\\log(CP^{-\\frac{2}{3}})$이다. 따라서 $D=CP^{-\\frac{2}{3}}$이다. 판매 가격이 처음의 $r$배가 되면 수요량은 처음의 $r^{-\\frac{2}{3}}$배가 된다. 이 값이 $\\dfrac{1}{4}$이어야 하므로 $r^{-\\frac{2}{3}}=\\dfrac{1}{4}$이다. 즉 $r^{\\frac{2}{3}}=4$이고, 양변을 $\\dfrac{3}{2}$제곱하면 $r=4^{\\frac{3}{2}}=(\\sqrt{4})^3=2^3=8$이다.\\n따라서 구하는 값은 $8$배이다."
  }
];