window.examTitle = "비상대수지수로그익힘책_고2_유형변형";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$-125$의 세제곱근 중에서 실수인 것의 개수를 $a$, $81$의 네제곱근 중에서 실수인 것의 개수를 $b$라고 할 때, $a+b$의 값을 구하시오.",
    choices: [],
    answer: "$3$",
    solution: "[키포인트] 음수의 홀수제곱근은 실수 1개, 양수의 짝수제곱근은 실수 2개이다.\\n조건 정리: $-125$는 음수이고 세제곱근을 묻고 있으므로 홀수제곱근이다. $81$은 양수이고 네제곱근을 묻고 있으므로 짝수제곱근이다.\\n풀이 방향: 각각의 거듭제곱근 중 실수인 것의 개수를 구한 뒤 더한다.\\n정석 풀이: 음수의 홀수제곱근은 항상 실수 1개이므로 $a=1$이다. 양수의 짝수제곱근은 양수와 음수 2개의 실수값을 가지므로 $b=2$이다. 따라서 $a+b=1+2=3$이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 2,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\sqrt[4]{(-3)^4}+\\sqrt{(-5)^2}-\\dfrac{\\sqrt[3]{-64}}{\\sqrt{16}}$을 간단히 하시오.",
    choices: [],
    answer: "$9$",
    solution: "[키포인트] 짝수제곱근의 주값은 음수가 아니라 양수로 계산한다.\\n조건 정리: $\\sqrt[4]{(-3)^4}$, $\\sqrt{(-5)^2}$는 모두 짝수제곱근의 주값이고, $\\sqrt[3]{-64}$는 홀수제곱근이다.\\n풀이 방향: 각 근호의 값을 먼저 구한 뒤 분수식을 계산한다.\\n정석 풀이: $\\sqrt[4]{(-3)^4}=3$, $\\sqrt{(-5)^2}=5$이다. 또한 $\\sqrt[3]{-64}=-4$, $\\sqrt{16}=4$이므로 $\\dfrac{\\sqrt[3]{-64}}{\\sqrt{16}}=\\dfrac{-4}{4}=-1$이다. 따라서 주어진 식의 값은 $3+5-(-1)=9$이다.\\n따라서 구하는 값은 $9$이다."
  },
  {
    id: 3,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log_4\\dfrac{1}{8}-\\log_4 2+2\\log_4 4$를 간단히 하시오.",
    choices: [],
    answer: "$0$",
    solution: "[키포인트] 로그의 값을 밑 $4$에 대한 지수로 바꾸어 계산한다.\\n조건 정리: $\\dfrac{1}{8}=2^{-3}$, $4=2^2$이므로 밑 $4$와 밑 $2$의 관계를 이용할 수 있다.\\n풀이 방향: 각 로그값을 계산한 뒤 더하고 뺀다.\\n정석 풀이: $4=2^2$이므로 $\\log_4 \\dfrac{1}{8}=\\log_{2^2}2^{-3}=-\\dfrac{3}{2}$이다. 또 $\\log_4 2=\\dfrac{1}{2}$, $\\log_4 4=1$이다. 따라서 $\\log_4\\dfrac{1}{8}-\\log_4 2+2\\log_4 4=-\\dfrac{3}{2}-\\dfrac{1}{2}+2=0$이다.\\n따라서 구하는 값은 $0$이다."
  },
  {
    id: 4,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log 2=a$, $\\log 3=b$, $\\log 7=c$일 때, $\\log\\dfrac{63}{20}$을 $a,b,c$에 대한 식으로 나타내시오.",
    choices: [],
    answer: "$2b+c-a-1$",
    solution: "[키포인트] 곱과 몫의 로그 성질을 이용하여 주어진 로그값으로 분해한다.\\n조건 정리: $63=3^2\\times 7$, $20=2\\times 10$이고 상용로그에서 $\\log 10=1$이다.\\n풀이 방향: $\\log\\dfrac{63}{20}=\\log 63-\\log 20$으로 나누어 계산한다.\\n정석 풀이: $\\log 63=\\log(3^2\\times 7)=2\\log 3+\\log 7=2b+c$이다. 또 $\\log 20=\\log(2\\times 10)=\\log 2+\log 10=a+1$이다. 따라서 $\\log\\dfrac{63}{20}=(2b+c)-(a+1)=2b+c-a-1$이다.\\n따라서 구하는 값은 $2b+c-a-1$이다."
  },
  {
    id: 5,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a>1$일 때, 다음을 만족시키는 자연수 $k$의 값을 구하시오.\\n\\n$\\sqrt[3]{a^2}\\times\\sqrt[k]{a}=\\sqrt[6]{a^7}$",
    choices: [],
    answer: "$2$",
    solution: "[키포인트] 거듭제곱근을 유리수 지수로 바꾸어 지수를 비교한다.\\n조건 정리: $a>1$이므로 양변의 밑 $a$가 같을 때 지수가 같아야 한다.\\n풀이 방향: 모든 근호를 $a$의 유리수 지수 형태로 고친다.\\n정석 풀이: $\\sqrt[3]{a^2}=a^{\\frac{2}{3}}$, $\\sqrt[k]{a}=a^{\\frac{1}{k}}$, $\\sqrt[6]{a^7}=a^{\\frac{7}{6}}$이다. 따라서 $a^{\\frac{2}{3}}\\times a^{\\frac{1}{k}}=a^{\\frac{7}{6}}$이므로 $\\dfrac{2}{3}+\\dfrac{1}{k}=\\dfrac{7}{6}$이다. $\\dfrac{2}{3}=\\dfrac{4}{6}$이므로 $\\dfrac{1}{k}=\\dfrac{7}{6}-\\dfrac{4}{6}=\\dfrac{1}{2}$이다. 따라서 $k=2$이다.\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 6,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x=\\sqrt[3]{2}+\\dfrac{1}{\\sqrt[3]{2}}$일 때, $x^3-3x$의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{5}{2}$",
    solution: "[키포인트] $x=t+\\dfrac{1}{t}$ 꼴에서는 $x^3-3x=t^3+\\dfrac{1}{t^3}$을 이용한다.\\n조건 정리: $t=\\sqrt[3]{2}$라고 두면 $x=t+\\dfrac{1}{t}$이다.\\n풀이 방향: 세제곱 공식을 이용하여 $x^3-3x$를 단순화한다.\\n정석 풀이: $x=t+\\dfrac{1}{t}$이면 $x^3=\\left(t+\\dfrac{1}{t}\\right)^3=t^3+3t+\\dfrac{3}{t}+\\dfrac{1}{t^3}$이다. 따라서 $x^3-3x=t^3+\\dfrac{1}{t^3}$이다. $t^3=2$이고 $\\dfrac{1}{t^3}=\\dfrac{1}{2}$이므로 $x^3-3x=2+\\dfrac{1}{2}=\\dfrac{5}{2}$이다.\\n따라서 구하는 값은 $\\dfrac{5}{2}$이다."
  },
  {
    id: 7,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "실수 $x,y$에 대하여 $2^x=8$, $3^y=\\dfrac{1}{9}$일 때, $\\dfrac{1}{x}-\\dfrac{2}{y}$의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{4}{3}$",
    solution: "[키포인트] 양변의 밑을 같게 만들어 지수를 비교한다.\\n조건 정리: $8=2^3$, $\\dfrac{1}{9}=3^{-2}$이다.\\n풀이 방향: $x,y$의 값을 각각 구한 뒤 식에 대입한다.\\n정석 풀이: $2^x=8=2^3$이므로 $x=3$이다. 또 $3^y=\\dfrac{1}{9}=3^{-2}$이므로 $y=-2$이다. 따라서 $\\dfrac{1}{x}-\\dfrac{2}{y}=\\dfrac{1}{3}-\\dfrac{2}{-2}=\\dfrac{1}{3}+1=\\dfrac{4}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{4}{3}$이다."
  },
  {
    id: 8,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\dfrac{3^x-3^{-x}}{3^x+3^{-x}}=\\dfrac{1}{2}$일 때, $3^{2x}$의 값을 구하시오.",
    choices: [],
    answer: "$3$",
    solution: "[키포인트] $3^x$를 하나의 문자로 치환하면 분수식이 이차식으로 정리된다.\\n조건 정리: $3^x=t$라고 두면 $3^{-x}=\\dfrac{1}{t}$이고, 구하는 값은 $3^{2x}=t^2$이다.\\n풀이 방향: 분수식의 분모와 분자에 $t$를 곱해 $t^2$에 대한 식을 만든다.\\n정석 풀이: $3^x=t$라고 하면 $\\dfrac{3^x-3^{-x}}{3^x+3^{-x}}=\\dfrac{t-\\frac{1}{t}}{t+\\frac{1}{t}}=\\dfrac{t^2-1}{t^2+1}$이다. 따라서 $\\dfrac{t^2-1}{t^2+1}=\\dfrac{1}{2}$이다. 양변을 정리하면 $2(t^2-1)=t^2+1$이고, $2t^2-2=t^2+1$이므로 $t^2=3$이다. 따라서 $3^{2x}=t^2=3$이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 9,
    level: "상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "모든 실수 $x$에 대하여 $\\log_{p+1}(x^2-2px+p+3)$이 정의되기 위한 실수 $p$의 값의 범위를 구하시오.",
    choices: [],
    answer: "$-1<p<\\dfrac{1+\\sqrt{13}}{2},\\ p\\ne 0$",
    solution: "[키포인트] 로그가 모든 실수 $x$에 대하여 정의되려면 밑 조건과 진수의 항상 양수 조건을 동시에 만족해야 한다.\\n조건 정리: 로그 $\\log_{p+1}(x^2-2px+p+3)$에서 밑은 $p+1$이고 진수는 $x^2-2px+p+3$이다. 로그의 밑 조건은 $p+1\\gt0$, $p+1\\ne1$이다.\\n풀이 방향: 먼저 밑 조건을 구한 뒤, 이차식 $x^2-2px+p+3$이 모든 실수 $x$에 대하여 양수가 되는 조건을 판별식으로 구한다.\\n정석 풀이: 밑 조건에서 $p+1\\gt0$이므로 $p\\gt-1$이고, $p+1\\ne1$이므로 $p\\ne0$이다. 이제 진수 $x^2-2px+p+3$이 모든 실수 $x$에 대하여 양수이어야 한다. 이 이차식의 최고차항 계수는 $1\\gt0$이므로 모든 실수 $x$에 대하여 양수가 되려면 판별식이 음수이어야 한다. 판별식을 $D$라 하면 $D=(-2p)^2-4(p+3)=4p^2-4p-12=4(p^2-p-3)$이다. 따라서 $D\\lt0$에서 $p^2-p-3\\lt0$이다. 이 부등식의 해는 $\\dfrac{1-\\sqrt{13}}{2}\\lt p\\lt\\dfrac{1+\\sqrt{13}}{2}$이다. 여기에 밑 조건 $p\\gt-1$, $p\\ne0$을 함께 적용한다. $\\dfrac{1-\\sqrt{13}}{2}\\lt -1$이므로 최종 범위는 $-1\\lt p\\lt\\dfrac{1+\\sqrt{13}}{2}$이고 $p\\ne0$이다.\\n핵심 확인: 진수 조건만 보면 $p$의 하한이 $\\dfrac{1-\\sqrt{13}}{2}$이지만, 로그의 밑 조건 때문에 $p\\gt-1$이 더 강한 조건이 된다.\\n따라서 구하는 범위는 $-1<p<\\dfrac{1+\\sqrt{13}}{2},\\ p\\ne 0$이다."
  },
  {
    id: 10,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 실수 $a,b$가 $3^a=5$, $2^b=3$을 만족시킬 때, $\\log_5 18$을 $a,b$에 대한 식으로 나타내시오.",
    choices: [],
    answer: "$\\dfrac{1+2b}{ab}$",
    solution: "[키포인트] 주어진 지수식을 로그 관계로 바꾸고 밑을 통일한다.\\n조건 정리: $3^a=5$이므로 $a=\\log_3 5$이고, $2^b=3$이므로 $b=\\log_2 3$이다.\\n풀이 방향: $\\log_5 18$을 밑 $3$의 로그로 바꾸어 $a,b$로 표현한다.\\n정석 풀이: 밑변환을 이용하면 $\\log_5 18=\\dfrac{\\log_3 18}{\\log_3 5}$이다. 여기서 $\\log_3 5=a$이다. 또 $18=2\\times 3^2$이므로 $\\log_3 18=\\log_3 2+2$이다. $b=\\log_2 3$이므로 $\\log_3 2=\\dfrac{1}{b}$이다. 따라서 $\\log_5 18=\\dfrac{\\frac{1}{b}+2}{a}=\\dfrac{1+2b}{ab}$이다.\\n따라서 구하는 값은 $\\dfrac{1+2b}{ab}$이다."
  },
  {
    id: 11,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 식의 값을 구하시오.\\n\\n$\\log_2(\\log_3 9)+\\log_3(\\log_2 512)+\\log_4(\\log_5 625)$",
    choices: [],
    answer: "$4$",
    solution: "[키포인트] 괄호 안의 로그값을 먼저 계산한 뒤 바깥 로그를 계산한다.\\n조건 정리: $9=3^2$, $512=2^9$, $625=5^4$이다.\\n풀이 방향: 안쪽 로그값을 각각 구하고, 그 결과를 바깥 로그의 진수로 대입한다.\\n정석 풀이: $\\log_3 9=2$이므로 $\\log_2(\\log_3 9)=\\log_2 2=1$이다. 또 $\\log_2 512=9$이므로 $\\log_3(\\log_2 512)=\\log_3 9=2$이다. 마지막으로 $\\log_5 625=4$이므로 $\\log_4(\\log_5 625)=\\log_4 4=1$이다. 따라서 전체 값은 $1+2+1=4$이다.\\n따라서 구하는 값은 $4$이다."
  },
  {
    id: 12,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$1<x<10$이고 $\\log x^4$와 $\\log x$의 차가 정수일 때, $\\log x$의 값을 모두 구하시오.",
    choices: [],
    answer: "$\\dfrac{1}{3},\\ \\dfrac{2}{3}$",
    solution: "[키포인트] $\\log x$를 하나의 문자로 두고 범위 조건과 정수 조건을 함께 적용한다.\\n조건 정리: $1\\lt x\\lt10$이므로 $0\\lt \\log x\\lt1$이다.\\n풀이 방향: $\\log x^4-\\log x$를 $\\log x$로 정리한 뒤 정수가 되는 경우를 찾는다.\\n정석 풀이: $\\log x^4=4\\log x$이므로 $\\log x^4$와 $\\log x$의 차는 $4\\log x-\\log x=3\\log x$이다. 이 값이 정수이고 $0\\lt \\log x\\lt1$이므로 $0\\lt 3\\log x\\lt3$이다. 따라서 가능한 정수값은 $1,2$이다. $3\\log x=1$이면 $\\log x=\\dfrac{1}{3}$이고, $3\\log x=2$이면 $\\log x=\\dfrac{2}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{1}{3},\\ \\dfrac{2}{3}$이다."
  },
  {
    id: 13,
    level: "중",
    category: "집합",
    originalCategory: "집합",
    standardCourse: "공통수학2",
    standardUnitKey: "H22-C2-05",
    standardUnit: "집합",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 집합 $A=\\{1,2,3\\}$, $B=\\{-1,0,1\\}$에 대하여 집합 $S$를 $S=\\{(a,b)\\mid a+b\\text{는 짝수},\\ a\\in A,\\ b\\in B\\}$와 같이 정의하자. 다음 보기 중 옳은 것을 모두 고르시오.\\n\\n보기:\\nㄱ. $(2,0)\\in S$\\nㄴ. $b=-1$일 때, $(a,b)\\in S$를 만족시키는 $a$의 개수는 $2$이다.\\nㄷ. $n(S)=5$",
    choices: [],
    answer: "ㄱ, ㄴ, ㄷ",
    solution: "[키포인트] $a+b$가 짝수가 되려면 $a,b$의 홀짝성이 같아야 한다.\\n조건 정리: $A=\\{1,2,3\\}$에서 홀수는 $1,3$이고 짝수는 $2$이다. $B=\\{-1,0,1\\}$에서 홀수는 $-1,1$이고 짝수는 $0$이다.\\n풀이 방향: 각 보기의 조건을 직접 확인하고, 전체 원소 개수를 센다.\\n정석 풀이: ㄱ에서 $(2,0)$은 $2+0=2$로 짝수이므로 $(2,0)\\in S$이다. ㄴ에서 $b=-1$이면 $a+(-1)$이 짝수여야 하므로 $a$는 홀수이어야 한다. $A$의 홀수는 $1,3$이므로 가능한 $a$의 개수는 $2$이다. ㄷ에서 $a+b$가 짝수인 경우는 홀수끼리 더하거나 짝수끼리 더하는 경우이다. 홀수끼리의 순서쌍은 $2\\times2=4$개, 짝수끼리의 순서쌍은 $1\\times1=1$개이므로 $n(S)=5$이다. 따라서 ㄱ, ㄴ, ㄷ이 모두 옳다.\\n따라서 구하는 것은 ㄱ, ㄴ, ㄷ이다."
  },
  {
    id: 14,
    level: "상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$10$ 이하의 두 자연수 $m,n$에 대하여 $\\log_2 m-\\log_2 n$이 자연수가 되도록 하는 순서쌍 $(m,n)$의 개수를 구하시오.",
    choices: [],
    answer: "$8$",
    solution: "[키포인트] 로그의 차를 하나의 로그로 합치고, 그 값이 자연수가 되려면 진수가 $2$의 양의 정수 거듭제곱이어야 한다.\\n조건 정리: $m,n$은 $10$ 이하의 자연수이고, $\\log_2 m-\\log_2 n=\\log_2\\dfrac{m}{n}$이다. 이 값이 자연수이려면 $\\dfrac{m}{n}=2^k$인 자연수 $k$가 존재해야 한다.\\n풀이 방향: $m=n\\cdot 2^k$로 두고 $m\\le10$이 되도록 하는 순서쌍을 센다.\\n정석 풀이: $k$는 자연수이므로 $k\\ge1$이다. $m=n\\cdot2^k\\le10$이어야 한다. $k=1$이면 $m=2n\\le10$이므로 $n\\le5$이고 가능한 $n$은 $1,2,3,4,5$로 $5$개이다. $k=2$이면 $m=4n\\le10$이므로 $n\\le2$이고 가능한 경우는 $2$개이다. $k=3$이면 $m=8n\\le10$이므로 $n=1$만 가능하여 $1$개이다. $k=4$이면 $m=16n\\gt10$이므로 불가능하다. 따라서 전체 순서쌍의 개수는 $5+2+1=8$개이다.\\n핵심 확인: 로그값이 자연수이므로 $k=0$인 경우, 즉 $m=n$은 포함하지 않는다.\\n따라서 구하는 값은 $8$이다."
  },
  {
    id: 15,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 상품의 수요량 $D$와 판매 가격 $P$ 사이에는 $\\log D=k-\\dfrac{1}{2}\\log P$인 관계가 성립한다고 한다. 이 상품의 판매 가격이 처음 판매 가격에 비하여 $9$배로 폭등한다고 할 때, 수요량은 처음의 몇 배가 되는지 구하시오.",
    choices: [],
    answer: "$\\dfrac{1}{3}$배",
    solution: "[키포인트] 로그식을 지수 관계로 바꾸면 수요량은 가격의 $-\\dfrac{1}{2}$제곱에 비례한다.\\n조건 정리: $\\log D=k-\\dfrac{1}{2}\\log P$이고, 판매 가격은 처음의 $9$배가 된다.\\n풀이 방향: 로그식을 정리하여 $D$와 $P$의 비례 관계를 구한 뒤 가격 변화에 따른 수요량의 배수를 계산한다.\\n정석 풀이: $\\log D=k-\\dfrac{1}{2}\\log P$에서 $k=\\log C$인 상수 $C$를 생각하면 $\\log D=\\log C+\\log P^{-\\frac{1}{2}}=\\log(CP^{-\\frac{1}{2}})$이다. 따라서 $D=CP^{-\\frac{1}{2}}$이다. 판매 가격이 처음의 $9$배가 되면 수요량의 배수는 $9^{-\\frac{1}{2}}=\\dfrac{1}{\\sqrt{9}}=\\dfrac{1}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{1}{3}$배이다."
  }
];