window.examTitle = "비상대수삼각함수익힘책_고2_유형변형";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "일반각과 호도법",
    originalCategory: "일반각과 호도법",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-01",
    standardUnit: "일반각과 호도법",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["부채꼴"],
    wide: false,
    content: "반지름의 길이가 6이고 호의 길이가 $4\\pi$인 부채꼴의 중심각의 크기는?",
    choices: ["$\\dfrac{\\pi}{3}$", "$\\dfrac{\\pi}{2}$", "$\\dfrac{2\\pi}{3}$", "$\\dfrac{3\\pi}{4}$", "$\\dfrac{5\\pi}{6}$"],
    answer: "③",
    solution: "[키포인트] 부채꼴의 호의 길이 $l$은 $l = r\\theta$ ($r$은 반지름, $\\theta$는 중심각의 크기)이다.\\n조건 정리: 부채꼴의 반지름의 길이는 $r=6$이고, 호의 길이는 $l=4\\pi$이다.\\n풀이 방향: 부채꼴의 호의 길이 공식에 대입하여 중심각 $\\theta$를 구한다.\\n정석 풀이: $l = r\\theta$에 $r=6, l=4\\pi$를 대입하면\\n$4\\pi = 6\\theta$\\n$\\theta = \\dfrac{4\\pi}{6} = \\dfrac{2\\pi}{3}$\\n따라서 정답은 ③이다."
  },
  {
    id: 2,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-02",
    standardUnit: "삼각함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "각 $\\theta$가 제3사분면의 각이고 $\\cos \\theta = -\\dfrac{4}{5}$일 때, $\\sin \\theta$의 값을 구하시오.",
    choices: [],
    answer: "-\\dfrac{3}{5}",
    solution: "[키포인트] $\\sin^2 \\theta + \\cos^2 \\theta = 1$이고, 제3사분면에서 사인함수의 부호는 음수이다.\\n조건 정리: 각 $\\theta$는 제3사분면의 각이고, $\\cos \\theta = -\\dfrac{4}{5}$이다.\\n풀이 방향: 삼각함수 사이의 관계식을 이용하여 $\\sin^2 \\theta$의 값을 구한 후, 사분면을 고려하여 부호를 결정한다.\\n정석 풀이: $\\sin^2 \\theta = 1 - \\cos^2 \\theta$이므로\\n$\\sin^2 \\theta = 1 - \\left(-\\dfrac{4}{5}\\right)^2 = 1 - \\dfrac{16}{25} = \\dfrac{9}{25}$\\n$\\theta$가 제3사분면의 각이므로 $\\sin \\theta < 0$이다.\\n$\\sin \\theta = -\\sqrt{\\dfrac{9}{25}} = -\\dfrac{3}{5}$\\n따라서 구하는 값은 $-\\dfrac{3}{5}$이다."
  },
  {
    id: 3,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-02",
    standardUnit: "삼각함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["각변환"],
    wide: false,
    content: "다음 식을 간단히 하시오.\\n$\\cos \\left( \\dfrac{\\pi}{2} + \\theta \\right) - \\sin (\\pi - \\theta) + \\sin (\\pi + \\theta)$",
    choices: [],
    answer: "-3\\sin \\theta",
    solution: "[키포인트] 각의 크기가 $\\dfrac{\\pi}{2} \\pm \\theta$, $\\pi \\pm \\theta$인 삼각함수는 변환 공식을 통해 간단히 할 수 있다.\\n조건 정리: 주어진 식은 $\\cos \\left( \\dfrac{\\pi}{2} + \\theta \\right) - \\sin (\\pi - \\theta) + \\sin (\\pi + \\theta)$이다.\\n풀이 방향: 각 항의 삼각함수를 $\\theta$에 대한 삼각함수로 변환하여 계산한다.\\n정석 풀이: 각 항을 변환하면 다음과 같다.\\n$\\cos \\left( \\dfrac{\\pi}{2} + \\theta \\right) = -\\sin \\theta$\\n$\\sin (\\pi - \\theta) = \\sin \\theta$\\n$\\sin (\\pi + \\theta) = -\\sin \\theta$\\n이를 주어진 식에 대입하면\\n$(-\\sin \\theta) - \\sin \\theta + (-\\sin \\theta) = -3\\sin \\theta$\\n따라서 구하는 값은 $-3\\sin \\theta$이다."
  },
  {
    id: 4,
    level: "중",
    category: "삼각함수의 그래프",
    originalCategory: "삼각함수의 그래프",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-03",
    standardUnit: "삼각함수의 그래프",
    standardUnitOrder: 3,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["주기"],
    wide: false,
    content: "다음 함수 중 주기가 나머지 넷과 다른 하나는?",
    choices: ["$y = \\sin 2x$", "$y = \\cos 2x$", "$y = \\tan x$", "$y = 3\\sin 2x$", "$y = \\tan \\dfrac{x}{2}$"],
    answer: "⑤",
    solution: "[키포인트] 함수 $y = a\\sin(bx)+c, y = a\\cos(bx)+c$의 주기는 $\\dfrac{2\\pi}{|b|}$이고, $y = a\\tan(bx)+c$의 주기는 $\\dfrac{\\pi}{|b|}$이다.\\n조건 정리: 5개의 삼각함수 식이 주어져 있다.\\n풀이 방향: 각 함수의 주기를 공식을 이용하여 구하고 비교한다.\\n정석 풀이:\\n① $y = \\sin 2x$의 주기: $\\dfrac{2\\pi}{2} = \\pi$\\n② $y = \\cos 2x$의 주기: $\\dfrac{2\\pi}{2} = \\pi$\\n③ $y = \\tan x$의 주기: $\\dfrac{\\pi}{1} = \\pi$\\n④ $y = 3\\sin 2x$의 주기: $\\dfrac{2\\pi}{2} = \\pi$\\n⑤ $y = \\tan \\dfrac{x}{2}$의 주기: $\\dfrac{\\pi}{\\frac{1}{2}} = 2\\pi$\\n나머지 넷과 주기가 다른 함수는 ⑤이다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 5,
    level: "중",
    category: "일반각과 호도법",
    originalCategory: "일반각과 호도법",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-01",
    standardUnit: "일반각과 호도법",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["동경의위치관계"],
    wide: false,
    content: "$0 < \\theta < \\dfrac{\\pi}{2}$이고 각 $\\theta$와 각 $4\\theta$를 나타내는 동경이 $x$축에 대하여 대칭일 때, 각 $\\theta$의 크기를 구하시오.",
    choices: [],
    answer: "\\dfrac{2\\pi}{5}",
    solution: "[키포인트] 두 동경이 $x$축에 대하여 대칭이면 두 각의 합은 $2n\\pi$ ($n$은 정수)이다.\\n조건 정리: $0 < \\theta < \\dfrac{\\pi}{2}$이고, $\\theta$와 $4\\theta$를 나타내는 동경이 $x$축에 대하여 대칭이다.\\n풀이 방향: 대칭성에 의한 관계식을 세우고, 주어진 $\\theta$의 범위에 맞는 정수 $n$을 찾는다.\\n정석 풀이: 두 동경이 $x$축에 대하여 대칭이므로\\n$\\theta + 4\\theta = 2n\\pi$ ($n$은 정수)\\n$5\\theta = 2n\\pi$\\n$\\theta = \\dfrac{2n\\pi}{5}$\\n이때 $0 < \\theta < \\dfrac{\\pi}{2}$이므로\\n$0 < \\dfrac{2n\\pi}{5} < \\dfrac{\\pi}{2}$\\n$0 < n < \\dfrac{5}{4}$\\n이를 만족하는 정수 $n$은 $1$뿐이다.\\n따라서 $n=1$을 대입하면 $\\theta = \\dfrac{2\\pi}{5}$이다.\\n따라서 구하는 값은 $\\dfrac{2\\pi}{5}$이다."
  },
  {
    id: 6,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-02",
    standardUnit: "삼각함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["근과계수의관계"],
    wide: false,
    content: "이차방정식 $2x^2 + x + a = 0$의 두 근이 $\\sin \\theta, \\cos \\theta$일 때, 실수 $a$의 값을 구하시오.",
    choices: [],
    answer: "-\\dfrac{3}{4}",
    solution: "[키포인트] 이차방정식의 근과 계수의 관계 및 $\\sin^2 \\theta + \\cos^2 \\theta = 1$을 이용한다.\\n조건 정리: 이차방정식 $2x^2 + x + a = 0$의 두 근이 $\\sin \\theta, \\cos \\theta$이다.\\n풀이 방향: 두 근의 합과 곱을 계수로 나타내고, 두 근의 합을 제곱하여 $a$의 값을 구한다.\\n정석 풀이: 이차방정식의 근과 계수의 관계에 의하여\\n$\\sin \\theta + \\cos \\theta = -\\dfrac{1}{2} \\cdots$ ㉠\\n$\\sin \\theta \\cos \\theta = \\dfrac{a}{2} \\cdots$ ㉡\\n㉠의 양변을 제곱하면\\n$(\\sin \\theta + \\cos \\theta)^2 = \\dfrac{1}{4}$\\n$\\sin^2 \\theta + 2\\sin \\theta \\cos \\theta + \\cos^2 \\theta = \\dfrac{1}{4}$\\n$1 + 2\\sin \\theta \\cos \\theta = \\dfrac{1}{4}$\\n$2\\sin \\theta \\cos \\theta = -\\dfrac{3}{4}$\\n$\\sin \\theta \\cos \\theta = -\\dfrac{3}{8}$\\n이를 ㉡에 대입하면\\n$\\dfrac{a}{2} = -\\dfrac{3}{8} \\implies a = -\\dfrac{3}{4}$\\n따라서 구하는 값은 $-\\dfrac{3}{4}$이다."
  },
  {
    id: 7,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-02",
    standardUnit: "삼각함수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["대소관계"],
    wide: false,
    content: "$a = \\sin 1$, $b = \\cos 1$, $c = \\tan 1$이라 할 때, 세 수의 대소 관계로 옳은 것은?",
    choices: ["$a < b < c$", "$b < a < c$", "$b < c < a$", "$c < a < b$", "$c < b < a$"],
    answer: "②",
    solution: "[키포인트] $1$라디안은 약 $57.3^{\\circ}$이며, $0 < x < \\dfrac{\\pi}{2}$에서 삼각함수의 대소 관계를 이용한다.\\n조건 정리: $a = \\sin 1$, $b = \\cos 1$, $c = \\tan 1$이다.\\n풀이 방향: $1$라디안의 대략적인 크기를 파악하고, 특수각과의 비교를 통해 대소를 판단한다.\\n정석 풀이: $\\dfrac{\\pi}{4} \\approx \\dfrac{3.14}{4} = 0.785$이고, $\\dfrac{\\pi}{3} \\approx \\dfrac{3.14}{3} = 1.047$이므로 $1$라디안은 $\\dfrac{\\pi}{4} < 1 < \\dfrac{\\pi}{3}$ 범위에 있다.\\n$\\dfrac{\\pi}{4} < x < \\dfrac{\\pi}{2}$ 범위에서 $\\cos x < \\sin x < \\tan x$가 성립한다.\\n(참고: $x = \\dfrac{\\pi}{4}$일 때 $\\sin \\dfrac{\\pi}{4} = \\cos \\dfrac{\\pi}{4} = \\dfrac{\\sqrt{2}}{2}$이고, $\\tan \\dfrac{\\pi}{4} = 1$이다. $x > \\dfrac{\\pi}{4}$이면 $\\sin x$는 증가, $\\cos x$는 감소, $\\tan x$는 증가하므로 $\\tan x > 1 > \\sin x$가 된다.)\\n따라서 $\\cos 1 < \\sin 1 < \\tan 1$이므로 $b < a < c$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 8,
    level: "상",
    category: "삼각함수의 그래프",
    originalCategory: "삼각함수의 그래프",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-03",
    standardUnit: "삼각함수의 그래프",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프", "대칭성"],
    wide: false,
    content: "함수 $y = 3\\cos(\\pi x) \\ (0 \\le x < 2)$의 그래프와 직선 $y = 1$이 만나는 두 점의 $x$좌표를 각각 $a, b$라고 할 때, $a+b$의 값을 구하시오. (단, $a < b$)",
    choices: [],
    answer: "2",
    solution: "[키포인트] 삼각함수의 그래프는 선대칭성을 가지므로 교점의 $x$좌표의 합은 대칭축을 이용하여 구할 수 있다.\\n조건 정리: 함수 $y = 3\\cos(\\pi x)$의 그래프와 직선 $y = 1$이 만나는 두 점의 $x$좌표가 $a, b$ ($a < b$)이다.\\n풀이 방향: 코사인 함수의 주기를 구하고, 주어진 범위에서 그래프의 대칭축을 찾아 교점의 평균이 대칭축과 같음을 이용한다.\\n정석 풀이: 함수 $y = 3\\cos(\\pi x)$의 주기는 $\\dfrac{2\\pi}{\\pi} = 2$이다.\\n$0 \\le x < 2$의 범위에서 코사인 함수의 그래프는 $x = 1$에 대하여 좌우 대칭인 형태를 띠며, 최솟값은 $x=1$에서 가진다.\\n방정식 $3\\cos(\\pi x) = 1$, 즉 $\\cos(\\pi x) = \\dfrac{1}{3}$의 두 근 $a, b$ ($a < b$)는 대칭축 $x = 1$을 기준으로 좌우에 같은 거리만큼 떨어져 있다.\\n핵심 확인: 대칭성에 의해 두 근의 중점이 대칭축과 일치하므로 $\\dfrac{a+b}{2} = 1$이 성립한다.\\n$a+b = 2$\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 9,
    level: "중",
    category: "삼각함수의 그래프",
    originalCategory: "삼각함수의 그래프",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-03",
    standardUnit: "삼각함수의 그래프",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["최대최소", "주기"],
    wide: false,
    content: "함수 $y = a\\cos(bx) + c$의 최댓값이 4, 최솟값이 -2이고 주기가 $\\pi$일 때, $a+b+c$의 값을 구하시오. (단, $a>0, b>0$)",
    choices: [],
    answer: "6",
    solution: "[키포인트] 함수 $y = a\\cos(bx)+c$ ($a>0, b>0$)의 최댓값은 $a+c$, 최솟값은 $-a+c$, 주기는 $\\dfrac{2\\pi}{b}$이다.\\n조건 정리: 최댓값이 4, 최솟값이 -2, 주기가 $\\pi$이다. ($a>0, b>0$)\\n풀이 방향: 주기 공식을 이용하여 $b$를 구하고, 최대/최소 공식을 연립하여 $a, c$를 구한다.\\n정석 풀이: 주기가 $\\pi$이므로\\n$\\dfrac{2\\pi}{b} = \\pi \\implies b = 2$\\n최댓값이 4, 최솟값이 -2이므로\\n$a + c = 4 \\cdots$ ㉠\\n$-a + c = -2 \\cdots$ ㉡\\n㉠과 ㉡을 연립하여 더하면\\n$2c = 2 \\implies c = 1$\\n$c=1$을 ㉠에 대입하면 $a = 3$\\n따라서 $a=3, b=2, c=1$이므로\\n$a+b+c = 3+2+1 = 6$\\n따라서 구하는 값은 $6$이다."
  },
  {
    id: 10,
    level: "중",
    category: "삼각함수의 그래프",
    originalCategory: "삼각함수의 그래프",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-03",
    standardUnit: "삼각함수의 그래프",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["이차식의최대최소"],
    wide: false,
    content: "함수 $y = -\\sin^2 x + 2\\cos x + 1$의 최댓값을 $M$, 최솟값을 $m$이라 할 때, $M+m$의 값을 구하시오.",
    choices: [],
    answer: "2",
    solution: "[키포인트] $\\sin^2 x = 1 - \\cos^2 x$를 이용하여 식을 하나의 삼각함수로 통일하고 치환하여 이차함수의 최대, 최소를 구한다.\\n조건 정리: $y = -\\sin^2 x + 2\\cos x + 1$의 최댓값이 $M$, 최솟값이 $m$이다.\\n풀이 방향: $\\cos x = t$로 치환하고 $t$의 범위를 구한 뒤, 이차함수의 표준형으로 변형하여 최대, 최소를 찾는다.\\n정석 풀이: 주어진 함수를 변형하면\\n$y = -(1 - \\cos^2 x) + 2\\cos x + 1 = \\cos^2 x + 2\\cos x$\\n$\\cos x = t$로 치환하면, 실수 전체 집합에서 $-1 \\le t \\le 1$이다.\\n$y = t^2 + 2t = (t+1)^2 - 1$\\n$-1 \\le t \\le 1$ 범위에서 이 이차함수는 축의 방정식이 $t=-1$이므로 구간 내에서 최댓값과 최솟값을 다음과 같이 갖는다.\\n$t=1$일 때, $M = (1+1)^2 - 1 = 3$\\n$t=-1$일 때, $m = (-1+1)^2 - 1 = -1$\\n따라서 $M+m = 3 + (-1) = 2$이다.\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 11,
    level: "중",
    category: "삼각함수의 그래프",
    originalCategory: "삼각함수의 그래프",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-03",
    standardUnit: "삼각함수의 그래프",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["실생활활용"],
    wide: false,
    content: "해수면의 높이를 $h(t) = 5 + 3\\sin \\left( \\dfrac{\\pi}{6} t \\right)$라고 할 때, $0 \\le t \\le 12$에서 해수면의 높이가 6.5 이상이 되는 $t$의 범위를 구하시오.",
    choices: [],
    answer: "1 \\le t \\le 5",
    solution: "[키포인트] 삼각부등식을 세우고 치환을 통해 주어진 범위에서 해를 구한다.\\n조건 정리: $h(t) = 5 + 3\\sin \\left( \\dfrac{\\pi}{6} t \\right)$이고, $0 \\le t \\le 12$에서 $h(t) \\ge 6.5$를 풀어야 한다.\\n풀이 방향: 부등식을 간단히 하여 $\\sin$ 값의 범위를 구하고, 각을 치환하여 $t$의 범위를 확정한다.\\n정석 풀이: $5 + 3\\sin \\left( \\dfrac{\\pi}{6} t \\right) \\ge 6.5$\\n$3\\sin \\left( \\dfrac{\\pi}{6} t \\right) \\ge 1.5$\\n$\\sin \\left( \\dfrac{\\pi}{6} t \\right) \\ge \\dfrac{1}{2}$\\n$\\dfrac{\\pi}{6} t = X$라 치환하면, $0 \\le t \\le 12$이므로 $0 \\le X \\le 2\\pi$이다.\\n$0 \\le X \\le 2\\pi$에서 $\\sin X \\ge \\dfrac{1}{2}$의 해를 구하면\\n$\\dfrac{\\pi}{6} \\le X \\le \\dfrac{5\\pi}{6}$\\n치환한 것을 원래대로 되돌리면\\n$\\dfrac{\\pi}{6} \\le \\dfrac{\\pi}{6} t \\le \\dfrac{5\\pi}{6}$\\n각 변에 $\\dfrac{6}{\\pi}$을 곱하면\\n$1 \\le t \\le 5$\\n따라서 구하는 값은 $1 \\le t \\le 5$이다."
  },
  {
    id: 12,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-02",
    standardUnit: "삼각함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["좌표", "삼각형"],
    wide: false,
    content: "중심이 원점이고 반지름의 길이가 2인 반원 모양의 호를 6등분하는 점을 차례로 $P_1, P_2, P_3, P_4, P_5$라 하고, 각 점에서 $x$축에 내린 수선의 발을 각각 $Q_1, Q_2, Q_3, Q_4, Q_5$라 할 때, $\\overline{P_1Q_1}^2 + \\overline{P_2Q_2}^2 + \\overline{P_3Q_3}^2 + \\overline{P_4Q_4}^2 + \\overline{P_5Q_5}^2$의 값을 구하시오.",
    choices: [],
    answer: "12",
    solution: "[키포인트] 원 위의 점의 좌표는 삼각함수로 표현할 수 있으며, $\\sin^2 \\theta + \\cos^2 \\theta = 1$ 및 대칭성을 이용하여 합을 구한다.\\n조건 정리: 반지름이 2인 반원 호를 6등분한 점 $P_1 \\sim P_5$, 각 점에서 $x$축에 내린 수선의 발 $Q_k$의 제곱합을 구해야 한다.\\n풀이 방향: 중심각을 구하여 각 점의 좌표를 삼각함수로 나타내고, 선분의 길이를 대입하여 식을 계산한다.\\n정석 풀이: 반원의 중심각은 $\\pi$이므로 호를 6등분하면 하나의 중심각의 크기는 $\\dfrac{\\pi}{6}$이다.\\n점 $P_k$의 동경이 나타내는 각은 $\\theta_k = \\dfrac{k\\pi}{6}$ ($k=1, 2, 3, 4, 5$)이다.\\n점 $P_k$의 좌표는 $\\left(2\\cos\\dfrac{k\\pi}{6}, 2\\sin\\dfrac{k\\pi}{6}\\right)$이므로, $x$축에 내린 수선의 길이 $\\overline{P_kQ_k}$는 $y$좌표의 절댓값인 $2\\sin\\dfrac{k\\pi}{6}$이다. ($0 < \\theta_k < \\pi$에서 $\\sin$은 항상 양수이다.)\\n핵심 확인: 구하고자 하는 값은 $\\sum_{k=1}^{5} \\left( 2\\sin\\dfrac{k\\pi}{6} \\right)^2 = 4 \\sum_{k=1}^{5} \\sin^2\\dfrac{k\\pi}{6}$이다.\\n대칭성에 의해\\n$\\sin\\dfrac{5\\pi}{6} = \\sin\\left(\\pi - \\dfrac{\\pi}{6}\\right) = \\sin\\dfrac{\\pi}{6}$\\n$\\sin\\dfrac{4\\pi}{6} = \\sin\\left(\\pi - \\dfrac{2\\pi}{6}\\right) = \\sin\\dfrac{2\\pi}{6}$\\n$\\sin\\dfrac{3\\pi}{6} = \\sin\\dfrac{\\pi}{2} = 1$\\n따라서 주어진 식은\\n$4 \\left( \\sin^2\\dfrac{\\pi}{6} + \\sin^2\\dfrac{2\\pi}{6} + \\sin^2\\dfrac{\\pi}{2} + \\sin^2\\dfrac{2\\pi}{6} + \\sin^2\\dfrac{\\pi}{6} \\right)$\\n$= 4 \\left( 2\\sin^2\\dfrac{\\pi}{6} + 2\\sin^2\\dfrac{\\pi}{3} + 1 \\right)$\\n$= 4 \\left( 2 \\times \\dfrac{1}{4} + 2 \\times \\dfrac{3}{4} + 1 \\right) = 4 \\left( \\dfrac{1}{2} + \\dfrac{3}{2} + 1 \\right) = 4 \\times 3 = 12$\\n따라서 구하는 값은 $12$이다."
  },
  {
    id: 13,
    level: "상",
    category: "삼각함수의 그래프",
    originalCategory: "삼각함수의 그래프",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-03",
    standardUnit: "삼각함수의 그래프",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["실근의개수"],
    wide: false,
    content: "방정식 $\\sin(\\pi x) = \\dfrac{1}{3} x$의 서로 다른 실근의 개수를 구하시오.",
    choices: [],
    answer: "7",
    solution: "[키포인트] 삼각방정식의 서로 다른 실근의 개수는 두 함수 $y = \\sin(\\pi x)$와 $y = \\dfrac{1}{3}x$의 그래프 교점의 개수와 같다.\\n조건 정리: 방정식 $\\sin(\\pi x) = \\dfrac{1}{3}x$가 주어졌다.\\n풀이 방향: 두 그래프를 그리고, 직선이 사인 함수의 최댓값 1을 지나는 순간을 기준으로 교점을 센다.\\n정석 풀이: $y = \\sin(\\pi x)$의 주기는 $\\dfrac{2\\pi}{\\pi} = 2$이고, 최댓값은 1, 최솟값은 -1이다.\\n$y = \\dfrac{1}{3}x$의 그래프는 원점을 지나는 직선이며, $x = 3$일 때 $y = 1$을 지난다.\\n핵심 확인: $x \\ge 0$인 구간에서 교점을 찾아보자.\\n$0 \\le x \\le 3$에서 $y = \\sin(\\pi x)$의 그래프는 주기가 2이므로, 한 주기 반 동안 그려진다.\\n$x=3$일 때 직선은 $(3, 1)$을 지나며, 이때 $\\sin(3\\pi) = 0$이므로 직선이 곡선보다 위에 있게 된다.\\n그래프를 그려 교점을 구체적으로 확인하면:\\n$x=0$에서 원점을 공유한다 (1개).\\n$0 < x < 1$ 구간(위로 볼록)에서 직선과 1번 만난다.\\n$1 < x < 2$ 구간(아래로 볼록)에서 직선과 1번 만난다.\\n$2 < x < 3$ 구간(다시 위로 볼록)에서 직선과 1번 만난다.\\n$x \\ge 3$에서는 $\\dfrac{1}{3}x \\ge 1$이므로 더 이상 교점이 발생하지 않는다.\\n즉, $x > 0$ 범위에서 총 3개의 교점을 갖는다.\\n두 함수 모두 기함수(원점 대칭)이므로 $x < 0$ 범위에서도 대칭적으로 3개의 교점을 갖는다.\\n따라서 총 교점의 개수는 $3(양수) + 3(음수) + 1(원점) = 7$개이다.\\n따라서 구하는 값은 $7$이다."
  },
  {
    id: 14,
    level: "상",
    category: "삼각함수의 그래프",
    originalCategory: "삼각함수의 그래프",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03-03",
    standardUnit: "삼각함수의 그래프",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["삼각부등식"],
    wide: false,
    content: "$0 \\le x < 2\\pi$일 때, 두 부등식 $2\\sin^2 x - \\sin x - 1 > 0$, $\\cos x < 0$을 동시에 만족시키는 $x$의 값의 범위를 구하시오.",
    choices: [],
    answer: "\\dfrac{7\\pi}{6} < x < \\dfrac{3\\pi}{2}",
    solution: "[키포인트] 연립부등식의 해는 각각의 부등식을 풀어 나온 해의 공통부분을 구하는 것이다.\\n조건 정리: $0 \\le x < 2\\pi$에서 $2\\sin^2 x - \\sin x - 1 > 0$과 $\\cos x < 0$을 동시에 만족해야 한다.\\n풀이 방향: 이차부등식을 인수분해하여 $\\sin x$의 범위를 구하고, $\\cos x$의 부호와 결합하여 최종 $x$의 범위를 확정한다.\\n정석 풀이: 첫 번째 부등식 $2\\sin^2 x - \\sin x - 1 > 0$을 인수분해하면\\n$(2\\sin x + 1)(\\sin x - 1) > 0$\\n$\\sin x < -\\dfrac{1}{2}$ 또는 $\\sin x > 1$\\n핵심 확인: 모든 실수 $x$에 대하여 $\\sin x \\le 1$이므로 $\\sin x > 1$인 해는 존재하지 않는다.\\n따라서 $\\sin x < -\\dfrac{1}{2}$이다.\\n$0 \\le x < 2\\pi$ 범위에서 $\\sin x < -\\dfrac{1}{2}$의 해는\\n$\\dfrac{7\\pi}{6} < x < \\dfrac{11\\pi}{6} \\cdots$ ㉠\\n두 번째 부등식 $\\cos x < 0$은 제2, 3사분면의 각을 의미하므로 해당 범위는\\n$\\dfrac{\\pi}{2} < x < \\dfrac{3\\pi}{2} \\cdots$ ㉡\\n㉠과 ㉡의 공통부분을 구하면\\n$\\dfrac{7\\pi}{6} < x < \\dfrac{3\\pi}{2}$\\n따라서 구하는 값은 $\\dfrac{7\\pi}{6} < x < \\dfrac{3\\pi}{2}$이다."
  }
];