window.examTitle = "비상대수삼각함수활용익힘책_고2_유형심화";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 각 $\\theta$와 $7\\theta$를 나타내는 두 동경이 일직선 위에 있고 방향이 반대일 때, 각 $\\theta$의 크기가 될 수 있는 것을 보기에서 모두 고른 것은? (단, $0 < \\theta < \\pi$)\n\n<보기>\nㄱ. $\\frac{\\pi}{6}$\nㄴ. $\\frac{\\pi}{2}$\nㄷ. $\\frac{5\\pi}{6}$",
    choices: [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄴ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    answer: "⑤",
    solution: "[키포인트] 두 동경이 일직선 위에 있고 방향이 반대일 조건을 이용한다.\\n조건 정리: 두 동경이 일직선 위에 있고 방향이 반대이면 두 각의 차가 $(2n+1)\\pi$ ($n$은 정수)이다.\\n정석 풀이: $7\\theta - \\theta = 6\\theta = (2n+1)\\pi$이므로 $\\theta = \\dfrac{2n+1}{6}\\pi$이다.\\n$0 < \\theta < \\pi$이므로 $0 < \\dfrac{2n+1}{6}\\pi < \\pi$에서 $0 < 2n+1 < 6$이다.\\n이를 만족하는 정수 $n$은 $0, 1, 2$이다.\\n$n=0$일 때 $\\theta = \\dfrac{\\pi}{6}$\\n$n=1$일 때 $\\theta = \\dfrac{3\\pi}{6} = \\dfrac{\\pi}{2}$\\n$n=2$일 때 $\\theta = \\dfrac{5\\pi}{6}$\\n보기의 ㄱ, ㄴ, ㄷ 모두 조건을 만족한다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 2,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "둘레의 길이가 $24$인 부채꼴 중에서 그 넓이가 최대일 때의 중심각의 크기를 $A$, 그때의 넓이를 $B$라 하자. $A+B$의 값을 구하시오.",
    choices: [],
    answer: "38",
    solution: "[키포인트] 부채꼴의 둘레의 길이가 주어졌을 때 넓이의 최댓값을 이차함수를 이용하여 구한다.\\n조건 정리: 부채꼴의 반지름을 $r$, 호의 길이를 $l$이라 하면 둘레의 길이는 $2r+l=24$이므로 $l = 24-2r$이다. ($r>0, 24-2r>0$에서 $0 < r < 12$)\\n풀이 방향: 부채꼴의 넓이 $S = \\dfrac{1}{2}rl$에 $l$을 대입하여 $r$에 대한 이차함수의 최댓값을 구한다.\\n정석 풀이: 넓이 $S = \\dfrac{1}{2}r(24-2r) = -r^2 + 12r = -(r-6)^2 + 36$이다.\\n$0 < r < 12$에서 $S$는 $r=6$일 때 최댓값 $36$을 가진다. 따라서 넓이의 최댓값 $B = 36$이다.\\n이때 호의 길이는 $l = 24 - 2(6) = 12$이다.\\n호의 길이 $l = r\\theta$에서 $12 = 6 \\times A$이므로 중심각 $A = 2$이다.\\n따라서 $A+B = 2 + 36 = 38$이다.\\n따라서 구하는 값은 $38$이다."
  },
  {
    id: 3,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "각 $\\theta$가 제2사분면의 각이고 $\\frac{1}{1-\\sin \\theta} + \\frac{1}{1+\\sin \\theta} = \\frac{5}{2}$일 때, $\\frac{\\cos \\theta}{1-\\sin \\theta}$의 값을 구하시오.",
    choices: [],
    answer: "$-\\frac{\\sqrt{5}+1}{2}$",
    solution: "[키포인트] 삼각함수 사이의 관계를 이용하여 식을 간단히 하고 $\\cos\\theta$와 $\\sin\\theta$의 값을 구한다.\\n조건 정리: 제2사분면의 각이므로 $\\sin\\theta > 0$, $\\cos\\theta < 0$이다.\\n풀이 방향: 주어진 식의 좌변을 통분하여 $\\cos\\theta$의 값을 먼저 구한다.\\n정석 풀이: 좌변을 통분하면 $\\dfrac{1+\\sin\\theta + 1-\\sin\\theta}{(1-\\sin\\theta)(1+\\sin\\theta)} = \\dfrac{2}{1-\\sin^2\\theta} = \\dfrac{2}{\\cos^2\\theta}$이다.\\n주어진 식이 $\\dfrac{5}{2}$이므로 $\\dfrac{2}{\\cos^2\\theta} = \\dfrac{5}{2}$에서 $\\cos^2\\theta = \\dfrac{4}{5}$이다.\\n제2사분면의 각이므로 $\\cos\\theta = -\\dfrac{2}{\\sqrt{5}}$이다.\\n이때 $\\sin^2\\theta = 1 - \\cos^2\\theta = 1 - \\dfrac{4}{5} = \\dfrac{1}{5}$이고, $\\sin\\theta > 0$이므로 $\\sin\\theta = \\dfrac{1}{\\sqrt{5}}$이다.\\n구하고자 하는 식에 대입하면 $\\dfrac{\\cos\\theta}{1-\\sin\\theta} = \\dfrac{-\\dfrac{2}{\\sqrt{5}}}{1 - \\dfrac{1}{\\sqrt{5}}} = \\dfrac{-2}{\\sqrt{5}-1}$이다.\\n분모를 유리화하면 $\\dfrac{-2(\\sqrt{5}+1)}{5-1} = \\dfrac{-2(\\sqrt{5}+1)}{4} = -\\dfrac{\\sqrt{5}+1}{2}$이다.\\n따라서 구하는 값은 $-\\dfrac{\\sqrt{5}+1}{2}$이다."
  },
  {
    id: 4,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\sin^2\\frac{\\pi}{12} + \\sin^2\\frac{\\pi}{6} + \\sin^2\\frac{\\pi}{4} + \\sin^2\\frac{\\pi}{3} + \\sin^2\\frac{5\\pi}{12}$의 값을 구하시오.",
    choices: [],
    answer: "2.5",
    solution: "[키포인트] $\\sin\\left(\\dfrac{\\pi}{2}-x\\right) = \\cos x$ 성질을 이용하여 각을 변환하고 제곱의 합을 계산한다.\\n조건 정리: $\\dfrac{5\\pi}{12} = \\dfrac{\\pi}{2} - \\dfrac{\\pi}{12}$이고, $\\dfrac{\\pi}{3} = \\dfrac{\\pi}{2} - \\dfrac{\\pi}{6}$임을 이용한다.\\n정석 풀이: 주어진 식에서 뒤의 두 항을 변환하면 다음과 같다.\\n$\\sin^2\\dfrac{5\\pi}{12} = \\sin^2\\left(\\dfrac{\\pi}{2} - \\dfrac{\\pi}{12}\\right) = \\cos^2\\dfrac{\\pi}{12}$\\n$\\sin^2\\dfrac{\\pi}{3} = \\sin^2\\left(\\dfrac{\\pi}{2} - \\dfrac{\\pi}{6}\\right) = \\cos^2\\dfrac{\\pi}{6}$\\n이를 원래 식에 대입하여 짝지어 더하면 $\\left(\\sin^2\\dfrac{\\pi}{12} + \\cos^2\\dfrac{\\pi}{12}\\right) + \\left(\\sin^2\\dfrac{\\pi}{6} + \\cos^2\\dfrac{\\pi}{6}\\right) + \\sin^2\\dfrac{\\pi}{4}$가 된다.\\n각 괄호 안의 합은 $1$이고, $\\sin\\dfrac{\\pi}{4} = \\dfrac{\\sqrt{2}}{2}$이므로 $\\sin^2\\dfrac{\\pi}{4} = \\dfrac{1}{2}$이다.\\n따라서 전체 합은 $1 + 1 + 0.5 = 2.5$이다.\\n따라서 구하는 값은 $2.5$이다."
  },
  {
    id: 5,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "함수 $f(x) = \\sin ax$의 주기가 함수 $g(x) = |\\tan x|$의 주기와 같을 때, 양수 $a$의 값을 구하시오.",
    choices: [],
    answer: "2",
    solution: "[키포인트] 삼각함수의 주기를 구하는 공식과 절댓값 그래프의 특징을 이용한다.\\n조건 정리: $f(x) = \\sin ax$의 주기는 $\\dfrac{2\\pi}{|a|}$이다. $g(x) = |\\tan x|$는 $\\tan x$의 주기를 그대로 가져가므로 주기가 $\\pi$이다.\\n정석 풀이: $a>0$이므로 $f(x)$의 주기는 $\\dfrac{2\\pi}{a}$이다.\\n두 함수의 주기가 같으므로 $\\dfrac{2\\pi}{a} = \\pi$가 성립한다.\\n정리하면 $a = 2$이다.\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 6,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "함수 $f(x) = \\sin^2 x$에 대하여 $f\\left(\\frac{\\pi}{20}\\right) + f\\left(\\frac{2\\pi}{20}\\right) + \\cdots + f\\left(\\frac{9\\pi}{20}\\right)$의 값을 구하시오.",
    choices: [],
    answer: "4.5",
    solution: "[키포인트] $\\sin^2 x + \\cos^2 x = 1$과 여각 공식을 이용하여 식의 값을 계산한다.\\n조건 정리: $\\sin\\left(\\dfrac{\\pi}{2} - x\\right) = \\cos x$이므로 $\\sin^2\\left(\\dfrac{\\pi}{2} - x\\right) = \\cos^2 x$이다.\\n정석 풀이: $f\\left(\\dfrac{9\\pi}{20}\\right) = \\sin^2\\dfrac{9\\pi}{20} = \\sin^2\\left(\\dfrac{10\\pi}{20} - \\dfrac{\\pi}{20}\\right) = \\sin^2\\left(\\dfrac{\\pi}{2} - \\dfrac{\\pi}{20}\\right) = \\cos^2\\dfrac{\\pi}{20}$이다.\\n이와 같은 방법으로 양끝의 항을 짝지으면 $f\\left(\\dfrac{\\pi}{20}\\right) + f\\left(\\dfrac{9\\pi}{20}\\right) = \\sin^2\\dfrac{\\pi}{20} + \\cos^2\\dfrac{\\pi}{20} = 1$이다.\\n이처럼 $x=\\dfrac{2\\pi}{20}$와 $\\dfrac{8\\pi}{20}$, $\\dfrac{3\\pi}{20}$와 $\\dfrac{7\\pi}{20}$, $\\dfrac{4\\pi}{20}$와 $\\dfrac{6\\pi}{20}$가 각각 짝지어져 합이 1이 되므로 1이 총 4쌍 나온다.\\n가운데 남는 항은 $f\\left(\\dfrac{5\\pi}{20}\\right) = f\\left(\\dfrac{\\pi}{4}\\right) = \\sin^2\\dfrac{\\pi}{4} = \\left(\\dfrac{\\sqrt{2}}{2}\\right)^2 = \\dfrac{1}{2} = 0.5$이다.\\n전체 합은 $1 \\times 4 + 0.5 = 4.5$이다.\\n따라서 구하는 값은 $4.5$이다."
  },
  {
    id: 7,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "$0 \\le x \\le \\pi$일 때, 방정식 $\\cos 3x = \\sin x$의 모든 실근의 합을 구하시오.",
    choices: [],
    answer: "$\\frac{3}{2}\\pi$",
    solution: "[키포인트] 여각 공식을 이용하여 삼각방정식을 $\\cos A = \\cos B$ 꼴로 고치고 해의 일반적인 형태를 통해 모든 실근을 찾는다.\\n조건 정리: $\\sin x = \\cos\\left(\\dfrac{\\pi}{2} - x\\right)$이다.\\n풀이 방향: 주어진 방정식을 $\\cos 3x = \\cos\\left(\\dfrac{\\pi}{2} - x\\right)$로 변형하여 동경의 일치와 대칭성을 이용해 $x$를 구한다.\\n정석 풀이: $\\cos 3x = \\cos\\left(\\dfrac{\\pi}{2} - x\\right)$가 성립하려면 두 각의 동경이 일치하거나 $x$축 대칭이어야 한다.\\n즉, $3x = 2n\\pi \\pm \\left(\\dfrac{\\pi}{2} - x\\right)$ ($n$은 정수)이다.\\n첫째, 동경이 $x$축 대칭인 방향일 때 $3x = 2n\\pi - \\left(\\dfrac{\\pi}{2} - x\\right)$인 경우:\\n$2x = 2n\\pi - \\dfrac{\\pi}{2}$이므로 $x = n\\pi - \\dfrac{\\pi}{4}$이다.\\n$0 \\le x \\le \\pi$인 $x$를 찾으면 $n=1$일 때 $x=\\dfrac{3\\pi}{4}$이다.\\n둘째, 동경이 일치하는 방향일 때 $3x = 2n\\pi + \\left(\\dfrac{\\pi}{2} - x\\right)$인 경우:\\n$4x = 2n\\pi + \\dfrac{\\pi}{2}$이므로 $x = \\dfrac{n\\pi}{2} + \\dfrac{\\pi}{8}$이다.\\n$0 \\le x \\le \\pi$인 $x$를 찾으면 $n=0$일 때 $x=\\dfrac{\\pi}{8}$, $n=1$일 때 $x=\\dfrac{5\\pi}{8}$이다.\\n핵심 확인: 구한 근은 $x=\\dfrac{\\pi}{8}, \\dfrac{5\\pi}{8}, \\dfrac{3\\pi}{4}$이다.\\n모든 실근의 합은 $\\dfrac{\\pi}{8} + \\dfrac{5\\pi}{8} + \\dfrac{6\\pi}{8} = \\dfrac{12\\pi}{8} = \\dfrac{3}{2}\\pi$이다.\\n따라서 구하는 값은 $\\dfrac{3}{2}\\pi$이다."
  },
  {
    id: 8,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "$0 \\le x < 2\\pi$에서 부등식 $2\\cos^2 x + 3\\sin x - 3 < 0$을 만족하는 $x$의 범위가 $0 \\le x < \\alpha$ 또는 $\\beta < x < 2\\pi$일 때, $\\cos(\\alpha+\\beta)$의 값을 구하시오.",
    choices: [],
    answer: "-1",
    solution: "[키포인트] 삼각함수 사이의 관계를 이용하여 $\\sin x$에 대한 이차부등식을 푼다.\\n조건 정리: $\\cos^2 x = 1 - \\sin^2 x$를 대입하여 식을 정리한다.\\n풀이 방향: $\\sin x$의 해의 범위를 찾고, 단위원이나 그래프를 이용하여 $x$의 경계값을 구한다.\\n정석 풀이: 부등식에 대입하면 $2(1-\\sin^2 x) + 3\\sin x - 3 < 0$이다.\\n정리하면 $-2\\sin^2 x + 3\\sin x - 1 < 0$이고, 양변에 $-1$을 곱하면 $2\\sin^2 x - 3\\sin x + 1 > 0$이다.\\n인수분해하면 $(2\\sin x - 1)(\\sin x - 1) > 0$이다.\\n따라서 $\\sin x < \\dfrac{1}{2}$ 또는 $\\sin x > 1$이다.\\n모든 실수 $x$에 대하여 $\\sin x \\le 1$이므로 $\\sin x > 1$은 해가 존재하지 않는다.\\n즉, $\\sin x < \\dfrac{1}{2}$을 만족하는 $x$를 구한다.\\n$0 \\le x < 2\\pi$에서 $\\sin x = \\dfrac{1}{2}$이 되는 값은 $x=\\dfrac{\\pi}{6}, \\dfrac{5\\pi}{6}$이다.\\n부등식을 만족하는 $x$의 범위는 $0 \\le x < \\dfrac{\\pi}{6}$ 또는 $\\dfrac{5\\pi}{6} < x < 2\\pi$이다.\\n조건에서 이 범위가 $0 \\le x < \\alpha$ 또는 $\\beta < x < 2\\pi$와 일치하므로 $\\alpha = \\dfrac{\\pi}{6}$, $\\beta = \\dfrac{5\\pi}{6}$이다.\\n구하고자 하는 값은 $\\cos(\\alpha+\\beta) = \\cos\\left(\\dfrac{\\pi}{6} + \\dfrac{5\\pi}{6}\\right) = \\cos\\pi = -1$이다.\\n따라서 구하는 값은 $-1$이다."
  },
  {
    id: 9,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["도형"],
    wide: false,
    content: "원에 내접하는 사각형 $ABCD$에서 $\\overline{AB}=3, \\overline{BC}=4, \\overline{CD}=3, \\overline{DA}=2$일 때, $\\cos B$의 값을 구하시오.",
    choices: [],
    answer: "$\\frac{1}{3}$",
    solution: "[키포인트] 원에 내접하는 사각형의 마주보는 두 각의 크기의 합이 $180^\\circ$임을 이용하여 코사인법칙을 두 번 적용한다.\\n조건 정리: 원에 내접하는 사각형이므로 $\\angle D = 180^\\circ - B$에서 $\\cos D = -\\cos B$이다.\\n풀이 방향: $\\triangle ABC$와 $\\triangle ADC$에서 공통 변인 $\\overline{AC}$에 대하여 각각 코사인법칙을 적용해 연립한다.\\n정석 풀이: $\\triangle ABC$에서 코사인법칙에 의해 $\\overline{AC}^2 = 3^2 + 4^2 - 2 \\times 3 \\times 4 \\times \\cos B = 25 - 24\\cos B$이다.\\n$\\triangle ADC$에서 코사인법칙에 의해 $\\overline{AC}^2 = 2^2 + 3^2 - 2 \\times 2 \\times 3 \\times \\cos D = 13 - 12\\cos D$이다.\\n$\\cos D = -\\cos B$를 대입하면 $\\overline{AC}^2 = 13 - 12(-\\cos B) = 13 + 12\\cos B$이다.\\n두 $\\overline{AC}^2$의 값이 같으므로 $25 - 24\\cos B = 13 + 12\\cos B$가 성립한다.\\n정리하면 $36\\cos B = 12$이므로 $\\cos B = \\dfrac{1}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{1}{3}$이다."
  },
  {
    id: 10,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "삼각형 $ABC$에서 $(b+c):(c+a):(a+b) = 4:5:6$일 때, $\\sin A$의 값을 구하시오.",
    choices: [],
    answer: "$\\frac{\\sqrt{3}}{2}$",
    solution: "[키포인트] 변들의 합의 비를 이용하여 세 변의 길이의 비를 구하고, 코사인법칙을 적용한다.\\n조건 정리: $(b+c):(c+a):(a+b) = 4:5:6$이므로 상수 $k>0$에 대하여 $b+c=4k, c+a=5k, a+b=6k$이다.\\n풀이 방향: 세 식을 모두 더하여 $a, b, c$의 비율을 찾고 코사인법칙으로 $\\cos A$를 구한 후 $\\sin A$를 찾는다.\\n정석 풀이: 세 식을 변끼리 더하면 $2(a+b+c) = 15k$이므로 $a+b+c = 7.5k$이다.\\n$a = (a+b+c) - (b+c) = 7.5k - 4k = 3.5k$\\n$b = (a+b+c) - (c+a) = 7.5k - 5k = 2.5k$\\n$c = (a+b+c) - (a+b) = 7.5k - 6k = 1.5k$\\n따라서 $a:b:c = 3.5k : 2.5k : 1.5k = 7:5:3$이다.\\n$a=7m, b=5m, c=3m$ ($m>0$)로 놓으면 코사인법칙에 의해 $\\cos A = \\dfrac{b^2+c^2-a^2}{2bc}$이다.\\n대입하면 $\\cos A = \\dfrac{25m^2 + 9m^2 - 49m^2}{2 \\times 5m \\times 3m} = \\dfrac{-15m^2}{30m^2} = -\\dfrac{1}{2}$이다.\\n삼각형의 내각이므로 $\\sin A > 0$이다. $\\sin A = \\sqrt{1 - \\cos^2 A} = \\sqrt{1 - \\left(-\\dfrac{1}{2}\\right)^2} = \\dfrac{\\sqrt{3}}{2}$이다.\\n따라서 구하는 값은 $\\dfrac{\\sqrt{3}}{2}$이다."
  },
  {
    id: 11,
    level: "상",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["도형"],
    wide: false,
    content: "$\\overline{AB}=4, \\overline{AC}=5$이고 넓이가 $5\\sqrt{3}$인 삼각형 $ABC$에서 $\\overline{BC}$의 길이의 최솟값을 구하시오.",
    choices: [],
    answer: "$\\sqrt{21}$",
    solution: "[키포인트] 삼각형의 넓이 공식을 통해 끼인각을 구하고, 코사인법칙으로 대변 길이의 최솟값을 찾는다.\\n조건 정리: 두 변의 길이가 $4, 5$이고 넓이 $S=5\\sqrt{3}$이다. 변 $\\overline{BC}$의 최솟값을 구해야 한다.\\n풀이 방향: 넓이 공식을 통해 $\\sin A$를 구하여 가능한 $\\angle A$의 크기를 모두 찾고, 코사인법칙으로 $\\overline{BC}^2$을 계산하여 언제가 최소인지 판별한다.\\n정석 풀이: 삼각형의 넓이 $S = \\dfrac{1}{2} \\times \\overline{AB} \\times \\overline{AC} \\times \\sin A = \\dfrac{1}{2} \\times 4 \\times 5 \\times \\sin A = 10\\sin A$이다.\\n조건에서 넓이가 $5\\sqrt{3}$이므로 $10\\sin A = 5\\sqrt{3}$에서 $\\sin A = \\dfrac{\\sqrt{3}}{2}$이다.\\n이를 만족하는 $\\angle A$는 $A = 60^\\circ$ 또는 $A = 120^\\circ$이다.\\n코사인법칙에 의해 $\\overline{BC}^2 = 4^2 + 5^2 - 2 \\times 4 \\times 5 \\times \\cos A = 41 - 40\\cos A$이다.\\n첫째, $A = 60^\\circ$일 때 $\\cos A = \\dfrac{1}{2}$이므로 $\\overline{BC}^2 = 41 - 40\\left(\\dfrac{1}{2}\\right) = 21$이다.\\n둘째, $A = 120^\\circ$일 때 $\\cos A = -\\dfrac{1}{2}$이므로 $\\overline{BC}^2 = 41 - 40\\left(-\\dfrac{1}{2}\\right) = 61$이다.\\n핵심 확인: 구하는 것은 $\\overline{BC}$의 길이의 최솟값이므로 $\\overline{BC}^2 = 21$일 때 최소가 된다.\\n$\\overline{BC} > 0$이므로 $\\overline{BC}$의 최솟값은 $\\sqrt{21}$이다.\\n따라서 구하는 값은 $\\sqrt{21}$이다."
  },
  {
    id: 12,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "각 $\\theta$가 제4사분면의 각이고, $\\theta$를 나타내는 동경과 $6\\theta$를 나타내는 동경이 서로 $y$축에 대하여 대칭일 때, 각 $\\theta$의 크기를 구하시오.",
    choices: [],
    answer: "$\\frac{11}{7}\\pi, \\frac{13}{7}\\pi$",
    solution: "[키포인트] 두 동경이 $y$축에 대하여 대칭일 조건을 이용하여 각의 크기를 구한다.\\n조건 정리: 두 동경이 $y$축 대칭이면 두 각의 합이 $(2n+1)\\pi$ ($n$은 정수) 꼴이다.\\n풀이 방향: 대칭 조건으로 $\\theta$의 식을 세우고, 제4사분면의 각 조건을 만족하는 정수 $n$을 찾는다.\\n정석 풀이: $\\theta + 6\\theta = (2n+1)\\pi$이므로 $7\\theta = (2n+1)\\pi$에서 $\\theta = \\dfrac{2n+1}{7}\\pi$이다.\\n$\\theta$가 제4사분면의 각이므로 $\\dfrac{3}{2}\\pi < \\theta < 2\\pi$이다.\\n식을 대입하면 $\\dfrac{3}{2}\\pi < \\dfrac{2n+1}{7}\\pi < 2\\pi$이다.\\n양변을 $\\pi$로 나누고 $7$을 곱하면 $10.5 < 2n+1 < 14$이므로 $9.5 < 2n < 13$이다.\\n이를 만족하는 정수 $n$은 $5, 6$이다.\\n$n=5$일 때 $\\theta = \\dfrac{11}{7}\\pi$이고, $n=6$일 때 $\\theta = \\dfrac{13}{7}\\pi$이다.\\n따라서 구하는 값은 $\\dfrac{11}{7}\\pi, \\dfrac{13}{7}\\pi$이다."
  },
  {
    id: 13,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "그래프"],
    wide: false,
    content: "함수 $f(x) = a \\cos(bx - \\pi) + c$의 그래프가 두 점 $(0, 1), (\\pi, 5)$를 지나고 주기가 $2\\pi$일 때, 양수 $a, b$와 상수 $c$의 합 $a+b+c$를 구하시오.",
    choices: [],
    answer: "6",
    solution: "[키포인트] 코사인함수의 성질을 이용하여 주기 조건과 그래프가 지나는 점을 대입해 미지수를 구한다.\\n조건 정리: 주기가 $2\\pi$이므로 $b$를 구하고, 두 점 $(0, 1)$과 $(\\pi, 5)$를 대입하여 $a, c$에 대한 연립방정식을 세운다.\\n정석 풀이: $f(x) = a \\cos(bx - \\pi) + c$에서 $b>0$이므로 주기는 $\\dfrac{2\\pi}{b}$이다.\\n주기가 $2\\pi$이므로 $\\dfrac{2\\pi}{b} = 2\\pi$에서 $b = 1$이다.\\n따라서 $f(x) = a \\cos(x - \\pi) + c = -a \\cos x + c$이다. (여각 공식: $\\cos(x-\\pi) = -\\cos x$)\\n점 $(0, 1)$을 지나므로 $f(0) = -a \\cos 0 + c = -a + c = 1$이다.\\n점 $(\\pi, 5)$를 지나므로 $f(\\pi) = -a \\cos\\pi + c = a + c = 5$이다.\\n두 식 $-a + c = 1$과 $a + c = 5$를 연립하여 더하면 $2c = 6$이므로 $c = 3$이다.\\n이를 대입하면 $a = 2$이다.\\n따라서 $a+b+c = 2 + 1 + 3 = 6$이다.\\n따라서 구하는 값은 $6$이다."
  },
  {
    id: 14,
    level: "상",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "도형"],
    wide: false,
    content: "반지름의 길이가 $6$, 중심각의 크기가 $\\frac{\\pi}{3}$인 부채꼴 $OAB$가 있다. 호 $AB$ 위의 점 $P$에 대하여 삼각형 $OAP$의 넓이가 $9$일 때, 선분 $AP$의 길이의 제곱인 $\\overline{AP}^2$의 값을 구하시오.",
    choices: [],
    answer: "$72-36\\sqrt{3}$",
    solution: "[키포인트] 부채꼴 내의 삼각형의 넓이 공식을 통해 사잇각을 알아내고, 코사인법칙으로 선분의 길이의 제곱을 구한다.\\n조건 정리: $\\overline{OA}=6$이고 $\\triangle OAP$의 넓이가 $9$이다. 점 $P$는 호 $AB$ 위에 있으므로 $\\overline{OP}$의 길이는 반지름인 $6$이다.\\n풀이 방향: 점 $P$가 호 위에 있으므로 중심각 $\\angle AOP$의 범위를 고려하여 넓이 공식으로 $\\angle AOP$를 구하고, 코사인법칙으로 $\\overline{AP}^2$을 계산한다.\\n정석 풀이: 부채꼴의 반지름이 $6$이므로 $\\overline{OA} = \\overline{OP} = 6$이다.\\n$\\angle AOP = \\alpha$라 하면 $\\triangle OAP$의 넓이 $S = \\dfrac{1}{2} \\times 6 \\times 6 \\times \\sin\\alpha = 18\\sin\\alpha$이다.\\n넓이가 $9$이므로 $18\\sin\\alpha = 9$에서 $\\sin\\alpha = \\dfrac{1}{2}$이다.\\n점 $P$는 중심각의 크기가 $\\dfrac{\\pi}{3}$ ($60^\\circ$)인 호 $AB$ 위에 있으므로 $0 < \\alpha \\le 60^\\circ$이어야 한다.\\n따라서 $\\sin\\alpha = \\dfrac{1}{2}$를 만족하는 각은 $\\alpha = 30^\\circ$ ($\\dfrac{\\pi}{6}$)이다.\\n핵심 확인: $\\triangle OAP$에서 $\\overline{OA}=6, \\overline{OP}=6$이고 끼인각이 $30^\\circ$이므로 코사인법칙을 적용하여 $\\overline{AP}^2$을 구한다.\\n$\\overline{AP}^2 = 6^2 + 6^2 - 2 \\times 6 \\times 6 \\times \\cos 30^\\circ = 36 + 36 - 72 \\times \\dfrac{\\sqrt{3}}{2} = 72 - 36\\sqrt{3}$이다.\\n따라서 구하는 값은 $72-36\\sqrt{3}$이다."
  },
  {
    id: 15,
    level: "상",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "도형"],
    wide: false,
    content: "반지름의 길이가 $5$인 원에 내접하는 삼각형 $ABC$에서 $\\overline{AB}=6, \\overline{AC}=8$일 때, $\\cos A$의 값을 구하시오. (단, 삼각형 $ABC$는 예각삼각형이다.)",
    choices: [],
    answer: "$\\frac{24}{25}$",
    solution: "[키포인트] 외접원의 반지름이 주어진 경우 사인법칙을 통해 변의 길이를 각에 대한 식으로 바꾸고, 코사인법칙과 연립한다.\\n조건 정리: 외접원의 반지름 $R=5$이다. 변 $a$의 길이를 사인법칙으로 나타내고 이를 코사인법칙 식에 대입한다.\\n풀이 방향: $\\dfrac{a}{\\sin A} = 2R$임을 이용해 $a = 10\\sin A$를 코사인법칙에 대입하여 $\\cos A$에 대한 이차방정식을 푼다.\\n정석 풀이: 사인법칙에 의해 $\\dfrac{a}{\\sin A} = 2R = 10$이므로 $a = 10\\sin A$이다.\\n코사인법칙에 의해 $a^2 = 6^2 + 8^2 - 2 \\times 6 \\times 8 \\times \\cos A = 100 - 96\\cos A$이다.\\n$a = 10\\sin A$를 대입하면 $100\\sin^2 A = 100 - 96\\cos A$이다.\\n$\\sin^2 A = 1 - \\cos^2 A$를 대입하여 식을 $\\cos A$에 대해 한 문자로 정리한다.\\n$100(1 - \\cos^2 A) = 100 - 96\\cos A$이므로 $100 - 100\\cos^2 A = 100 - 96\\cos A$이다.\\n정리하면 $100\\cos^2 A - 96\\cos A = 0$이므로 $\\cos A (100\\cos A - 96) = 0$이다.\\n핵심 확인: 삼각형 $ABC$가 예각삼각형이므로 $0^\\circ < A < 90^\\circ$이고, $\\cos A > 0$이다.\\n따라서 $\\cos A = 0$은 해가 될 수 없으므로 $100\\cos A - 96 = 0$에서 $\\cos A = \\dfrac{96}{100} = \\dfrac{24}{25}$이다.\\n따라서 구하는 값은 $\\dfrac{24}{25}$이다."
  },
  {
    id: 16,
    level: "상",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "도형"],
    wide: false,
    content: "삼각형 $ABC$에서 $a=7, b=5, c=3$일 때, $\\sin A$의 값과 삼각형 $ABC$의 내접원의 반지름의 길이 $r$을 각각 구하시오.",
    choices: [],
    answer: "$\\sin A = \\frac{\\sqrt{3}}{2}, r = \\frac{\\sqrt{3}}{2}$",
    solution: "[키포인트] 코사인법칙을 이용해 각을 구하고, 삼각형 넓이 공식을 두 가지 방법으로 적용해 내접원의 반지름을 구한다.\\n조건 정리: 세 변의 길이 $a=7, b=5, c=3$이 주어졌을 때 내접원의 반지름 $r$은 넓이 공식 $S = \\dfrac{1}{2}r(a+b+c)$를 통해 구할 수 있다.\\n풀이 방향: 코사인법칙으로 $\\cos A$를 구한 후 $\\sin A$를 찾는다. 그 다음 $S = \\dfrac{1}{2}bc\\sin A$로 전체 넓이를 구하고 내접원 반지름 공식과 연립한다.\\n정석 풀이: 코사인법칙에 의해 $\\cos A = \\dfrac{b^2+c^2-a^2}{2bc} = \\dfrac{5^2 + 3^2 - 7^2}{2 \\times 5 \\times 3} = \\dfrac{25 + 9 - 49}{30} = -\\dfrac{15}{30} = -\\dfrac{1}{2}$이다.\\n삼각형 내각이므로 $A = 120^\\circ$이고, $\\sin A = \\sin 120^\\circ = \\dfrac{\\sqrt{3}}{2}$이다.\\n삼각형 $ABC$의 넓이 $S$는 $S = \\dfrac{1}{2}bc\\sin A = \\dfrac{1}{2} \\times 5 \\times 3 \\times \\dfrac{\\sqrt{3}}{2} = \\dfrac{15\\sqrt{3}}{4}$이다.\\n핵심 확인: 한편, 내접원의 반지름을 $r$이라 하면 삼각형의 넓이는 $S = \\dfrac{1}{2}r(a+b+c)$와 같다.\\n세 변의 합은 $a+b+c = 7+5+3 = 15$이므로 넓이는 $S = \\dfrac{15}{2}r$이다.\\n따라서 두 넓이 공식의 결과가 같으므로 $\\dfrac{15}{2}r = \\dfrac{15\\sqrt{3}}{4}$이 성립한다.\\n양변을 $\\dfrac{15}{2}$로 나누어 정리하면 $r = \\dfrac{\\sqrt{3}}{2}$이다.\\n따라서 구하는 값은 $\\sin A = \\dfrac{\\sqrt{3}}{2}, r = \\dfrac{\\sqrt{3}}{2}$이다."
  }
];