window.examTitle = "비상대수삼각함수1_고2_유형심화";
window.questionBank = [
  {
    id: 1,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$0 < \\theta < \\pi$인 각 $\\theta$에 대하여 각 $\\theta$를 나타내는 동경과 각 $3\\theta$를 나타내는 동경이 $y$축에 대하여 대칭일 때, 모든 $\\theta$의 값의 합을 구하시오.",
    choices: [],
    answer: "$\\pi$",
    solution: "[키포인트] 두 동경이 $y$축에 대하여 대칭일 조건은 두 각의 합이 $(2n+1)\\pi$임을 이용한다.\\n조건 정리: $0 < \\theta < \\pi$ 범위에서 동경 $\\theta$와 $3\\theta$가 $y$축에 대하여 대칭이다.\\n풀이 방향: 대칭성 공식을 이용해 $\\theta$에 대한 식을 세우고, 조건의 범위에 맞는 정수 $n$을 찾는다.\\n정석 풀이: 두 동경이 $y$축에 대하여 대칭이므로 두 각의 합은 $3\\theta + \\theta = (2n+1)\\pi$ ($n$은 정수)를 만족해야 한다.\\n$4\\theta = (2n+1)\\pi$에서 $\\theta = \\frac{2n+1}{4}\\pi$이다.\\n문제의 조건에서 $0 < \\theta < \\pi$이므로 부등식 $0 < \\frac{2n+1}{4}\\pi < \\pi$가 성립한다.\\n양변을 $\\pi$로 나누면 $0 < \\frac{2n+1}{4} < 1$이다.\\n양변에 $4$를 곱하면 $0 < 2n+1 < 4$가 되고, $1$을 빼면 $-1 < 2n < 3$이다.\\n양변을 $2$로 나누면 $-\\frac{1}{2} < n < \\frac{3}{2}$이다.\\n$n$은 정수이므로 이 부등식을 만족하는 $n$의 값은 $0$과 $1$이다.\\n핵심 확인: $n=0$일 때 $\\theta = \\frac{\\pi}{4}$이고, $n=1$일 때 $\\theta = \\frac{3\\pi}{4}$이며 두 값 모두 주어진 범위를 만족한다.\\n모든 $\\theta$의 값의 합은 $\\frac{\\pi}{4} + \\frac{3\\pi}{4} = \\pi$이다.\\n따라서 구하는 값은 $\\pi$이다."
  },
  {
    id: 2,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "넓이가 $16$인 부채꼴 중에서 둘레의 길이가 최소인 부채꼴의 반지름의 길이와 그때의 중심각의 크기를 각각 구하시오.",
    choices: [],
    answer: "반지름: $4$, 중심각: $2$",
    solution: "[키포인트] 부채꼴의 둘레의 최솟값은 산술평균과 기하평균의 관계를 이용하여 구한다.\\n조건 정리: 부채꼴의 넓이가 $16$이다. 반지름을 $r$, 호의 길이를 $l$, 중심각을 $\\theta$라 하자.\\n풀이 방향: 넓이 공식을 이용해 $l$을 $r$에 대한 식으로 나타내고, 이를 둘레의 길이에 대입한 후 산술평균과 기하평균의 관계를 적용한다.\\n정석 풀이: 부채꼴의 넓이 $S = \\frac{1}{2}rl = 16$에서 $rl = 32$이므로 $l = \\frac{32}{r}$이다. ($r>0$)\\n둘레의 길이 $P = 2r + l = 2r + \\frac{32}{r}$이다.\\n$r>0$이므로 산술평균과 기하평균의 관계에 의하여 $2r + \\frac{32}{r} \\ge 2\\sqrt{2r \\times \\frac{32}{r}} = 2\\sqrt{64} = 16$이 성립한다.\\n핵심 확인: 최솟값을 가질 조건은 등호가 성립할 때이므로 $2r = \\frac{32}{r}$에서 $2r^2 = 32$, $r^2 = 16$이다.\\n$r>0$이므로 반지름의 길이 $r=4$이다.\\n이때 호의 길이는 $l = \\frac{32}{4} = 8$이다.\\n호의 길이 공식 $l = r\\theta$에서 중심각의 크기는 $\\theta = \\frac{l}{r} = \\frac{8}{4} = 2$이다.\\n따라서 구하는 값은 반지름: $4$, 중심각: $2$이다."
  },
  {
    id: 3,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "각 $\\theta$가 제3사분면의 각일 때, $\\sqrt{\\cos^2 \\theta} - \\sqrt{(\\sin \\theta - \\tan \\theta)^2} + | \\sin \\theta + \\cos \\theta |$를 간단히 하시오.",
    choices: [],
    answer: "$-2\\cos \\theta - \\tan \\theta$",
    solution: "[키포인트] 제3사분면에서 삼각함수의 부호를 판별하고 제곱근과 절댓값의 성질을 적용한다.\\n조건 정리: $\\theta$가 제3사분면의 각이므로 $\\sin \\theta < 0$, $\\cos \\theta < 0$, $\\tan \\theta > 0$이다.\\n풀이 방향: 무리식 내부의 부호를 확인하여 양수로 나오도록 부호를 조정한 후 식을 전개한다.\\n정석 풀이: $\\sqrt{\\cos^2 \\theta} = |\\cos \\theta|$이다. $\\cos \\theta < 0$이므로 $-\\cos \\theta$로 나온다.\\n$\\sqrt{(\\sin \\theta - \\tan \\theta)^2} = |\\sin \\theta - \\tan \\theta|$이다.\\n$\\sin \\theta < 0$이고 $\\tan \\theta > 0$이므로 $\\sin \\theta - \\tan \\theta < 0$이다.\\n따라서 음수이므로 부호가 반대로 나와 $-(\\sin \\theta - \\tan \\theta) = -\\sin \\theta + \\tan \\theta$가 된다.\\n$|\\sin \\theta + \\cos \\theta|$에서 $\\sin \\theta$와 $\\cos \\theta$가 모두 음수이므로 $\\sin \\theta + \\cos \\theta < 0$이다.\\n따라서 부호가 반대로 나와 $-(\\sin \\theta + \\cos \\theta) = -\\sin \\theta - \\cos \\theta$가 된다.\\n핵심 확인: 정리한 항들을 본래 식에 대입한다.\\n$(-\\cos \\theta) - (-\\sin \\theta + \\tan \\theta) + (-\\sin \\theta - \\cos \\theta)$\\n$= -\\cos \\theta + \\sin \\theta - \\tan \\theta - \\sin \\theta - \\cos \\theta$\\n$= -2\\cos \\theta - \\tan \\theta$이다.\\n따라서 구하는 값은 $-2\\cos \\theta - \\tan \\theta$이다."
  },
  {
    id: 4,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\pi < \\theta < \\frac{3}{2}\\pi$이고 $\\tan \\theta = \\frac{3}{4}$일 때, $\\frac{1}{\\sin \\theta + \\cos \\theta} + \\frac{1}{\\sin \\theta - \\cos \\theta}$의 값을 구하시오.",
    choices: [],
    answer: "$\\frac{30}{7}$",
    solution: "[키포인트] 삼각함수의 관계를 이용하여 $\\sin \\theta$와 $\\cos \\theta$를 구하고 식에 대입하여 계산한다.\\n조건 정리: $\\theta$는 제3사분면의 각이고, $\\tan \\theta = \\frac{3}{4}$이다.\\n풀이 방향: 구하는 식을 통분하여 간단히 한 후, $\\sin \\theta$와 $\\cos \\theta$의 값을 대입한다.\\n정석 풀이: 주어진 식을 통분하면 다음과 같다.\\n$\\frac{\\sin \\theta - \\cos \\theta + \\sin \\theta + \\cos \\theta}{(\\sin \\theta + \\cos \\theta)(\\sin \\theta - \\cos \\theta)} = \\frac{2\\sin \\theta}{\\sin^2 \\theta - \\cos^2 \\theta}$\\n이제 $\\tan \\theta = \\frac{3}{4}$을 이용하여 다른 삼각함수의 값을 구한다.\\n$1 + \\tan^2 \\theta = \\frac{1}{\\cos^2 \\theta}$이므로 $1 + \\frac{9}{16} = \\frac{25}{16} = \\frac{1}{\\cos^2 \\theta}$이다.\\n$\\cos^2 \\theta = \\frac{16}{25}$이며, 제3사분면에서 $\\cos \\theta < 0$이므로 $\\cos \\theta = -\\frac{4}{5}$이다.\\n$\\sin \\theta = \\tan \\theta \\cos \\theta = \\frac{3}{4} \\times \\left(-\\frac{4}{5}\\right) = -\\frac{3}{5}$이다.\\n핵심 확인: 구한 값을 식에 대입한다.\\n분자는 $2\\sin \\theta = 2 \\times \\left(-\\frac{3}{5}\\right) = -\\frac{6}{5}$이다.\\n분모는 $\\sin^2 \\theta - \\cos^2 \\theta = \\frac{9}{25} - \\frac{16}{25} = -\\frac{7}{25}$이다.\\n따라서 구하는 식의 값은 $\\frac{-6/5}{-7/25} = \\frac{6}{5} \\times \\frac{25}{7} = \\frac{30}{7}$이다.\\n따라서 구하는 값은 $\\frac{30}{7}$이다."
  },
  {
    id: 5,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\sin \\theta + \\cos \\theta = \\frac{\\sqrt{5}}{5}$일 때, $\\sin^3 \\theta + \\cos^3 \\theta$의 값을 구하시오. (단, $\\frac{\\pi}{2} < \\theta < \\pi$)",
    choices: [],
    answer: "$\\frac{7\\sqrt{5}}{25}$",
    solution: "[키포인트] 곱셈공식의 변형을 이용하여 주어진 식의 값을 구한다.\\n조건 정리: $\\sin \\theta + \\cos \\theta = \\frac{\\sqrt{5}}{5}$이고 $\\theta$는 제2사분면의 각이다.\\n풀이 방향: 양변을 제곱하여 $\\sin \\theta \\cos \\theta$의 값을 구한 뒤, 세제곱의 곱셈공식에 대입한다.\\n정석 풀이: 주어진 식의 양변을 제곱하면 $(\\sin \\theta + \\cos \\theta)^2 = \\frac{5}{25} = \\frac{1}{5}$이다.\\n$\\sin^2 \\theta + 2\\sin \\theta \\cos \\theta + \\cos^2 \\theta = \\frac{1}{5}$에서 $1 + 2\\sin \\theta \\cos \\theta = \\frac{1}{5}$이므로 $2\\sin \\theta \\cos \\theta = -\\frac{4}{5}$이다.\\n따라서 $\\sin \\theta \\cos \\theta = -\\frac{2}{5}$이다.\\n핵심 확인: $\\sin^3 \\theta + \\cos^3 \\theta$의 값을 구하는 공식을 적용한다.\\n$\\sin^3 \\theta + \\cos^3 \\theta = (\\sin \\theta + \\cos \\theta)(\\sin^2 \\theta - \\sin \\theta \\cos \\theta + \\cos^2 \\theta)$\\n$= (\\sin \\theta + \\cos \\theta)(1 - \\sin \\theta \\cos \\theta)$이다.\\n구한 값을 대입하면 $\\frac{\\sqrt{5}}{5} \\times \\left(1 - \\left(-\\frac{2}{5}\\right)\\right) = \\frac{\\sqrt{5}}{5} \\times \\frac{7}{5} = \\frac{7\\sqrt{5}}{25}$이다.\\n따라서 구하는 값은 $\\frac{7\\sqrt{5}}{25}$이다."
  },
  {
    id: 6,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수 $f(x) = a \\cos(bx-c) + d$의 주기가 $4\\pi$이고 최댓값이 $5$, 최솟값이 $1$이다. $f(\\pi) = 3$일 때, 상수 $a, b, c, d$의 값을 구하시오. (단, $a>0, b>0, 0 < c < \\pi$)",
    choices: [],
    answer: "",
    solution: ""
  },
  {
    id: 7,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\theta = \\frac{\\pi}{10}$일 때, $\\sin^2 \\theta + \\sin^2 2\\theta + \\sin^2 3\\theta + \\sin^2 4\\theta + \\sin^2 5\\theta$의 값을 구하시오.",
    choices: [],
    answer: "3",
    solution: "[키포인트] 여각 공식 $\\sin\\left(\\frac{\\pi}{2} - x\\right) = \\cos x$를 이용하여 제곱의 합을 대칭적으로 짝지어 계산한다.\\n조건 정리: $\\theta = \\frac{\\pi}{10}$일 때, 주어진 삼각함수의 제곱의 합을 구해야 한다.\\n풀이 방향: $5\\theta = \\frac{\\pi}{2}$임을 파악하고, 각 항을 변환하여 $\\sin^2 x + \\cos^2 x = 1$ 형태로 묶는다.\\n정석 풀이: $\\theta = \\frac{\\pi}{10}$이므로 $5\\theta = \\frac{\\pi}{2}$이다.\\n따라서 $\\sin^2 5\\theta = \\sin^2\\left(\\frac{\\pi}{2}\\right) = 1$이다.\\n$4\\theta = \\frac{\\pi}{2} - \\theta$이므로 $\\sin^2 4\\theta = \\sin^2\\left(\\frac{\\pi}{2} - \\theta\\right) = \\cos^2 \\theta$이다.\\n마찬가지로 $3\\theta = \\frac{\\pi}{2} - 2\\theta$이므로 $\\sin^2 3\\theta = \\sin^2\\left(\\frac{\\pi}{2} - 2\\theta\\right) = \\cos^2 2\\theta$이다.\\n핵심 확인: 변환한 값들을 원래 식에 대입하여 짝을 지어 더한다.\\n주어진 식은 $\\sin^2 \\theta + \\sin^2 2\\theta + \\cos^2 2\\theta + \\cos^2 \\theta + \\sin^2 5\\theta$가 된다.\\n$= (\\sin^2 \\theta + \\cos^2 \\theta) + (\\sin^2 2\\theta + \\cos^2 2\\theta) + \\sin^2 5\\theta$\\n$= 1 + 1 + 1 = 3$이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 8,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\frac{\\pi}{2} < x < \\pi$에서 $2 \\sin^2 x + 5 \\cos x + 1 = 0$의 해를 $\\alpha$라 할 때, $\\tan(\\pi - \\alpha)$의 값을 구하시오.",
    choices: [],
    answer: "$\\sqrt{3}$",
    solution: "[키포인트] 삼각방정식을 풀기 위해 $\\sin^2 x$를 $1 - \\cos^2 x$로 치환하고 인수분해한다.\\n조건 정리: 제2사분면 각에서 $2 \\sin^2 x + 5 \\cos x + 1 = 0$을 만족하는 해 $\\alpha$를 찾는다.\\n풀이 방향: $\\cos x$에 대한 이차방정식을 풀어 $\\cos \\alpha$를 구하고, $\\alpha$값을 결정하여 목표 식에 대입한다.\\n정석 풀이: 방정식에 $\\sin^2 x = 1 - \\cos^2 x$를 대입하면 $2(1 - \\cos^2 x) + 5 \\cos x + 1 = 0$이다.\\n정리하면 $2\\cos^2 x - 5\\cos x - 3 = 0$이다.\\n인수분해하면 $(\\cos x - 3)(2\\cos x + 1) = 0$이다.\\n$\\cos x$의 값은 항상 $-1 \\le \\cos x \\le 1$이므로 $\\cos x = -\\frac{1}{2}$이다.\\n주어진 범위 $\\frac{\\pi}{2} < x < \\pi$에서 $\\cos x = -\\frac{1}{2}$를 만족하는 $x$는 $x = \\pi - \\frac{\\pi}{3} = \\frac{2\\pi}{3}$이다.\\n핵심 확인: $\\alpha = \\frac{2\\pi}{3}$이므로 구하는 식에 대입한다.\\n$\\tan(\\pi - \\alpha) = \\tan\\left(\\pi - \\frac{2\\pi}{3}\\right) = \\tan\\left(\\frac{\\pi}{3}\\right) = \\sqrt{3}$이다.\\n따라서 구하는 값은 $\\sqrt{3}$이다."
  },
  {
    id: 9,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수 $y = a \\cos(bx - c)$의 그래프가 최댓값 $3$, 최솟값 $-3$을 갖고 두 점 $\\left(\\frac{\\pi}{6}, 3\\right)$, $\\left(\\frac{\\pi}{2}, -3\\right)$을 지날 때, $a + b + \\frac{c}{\\pi}$의 값을 구하시오. (단, $a > 0, b > 0, 0 < c < \\pi$)",
    choices: [],
    answer: "6.5",
    solution: "[키포인트] 최댓값과 최솟값을 이용하여 진폭을 구하고, 지나는 두 점을 통해 주기와 평행이동 값을 유추한다.\\n조건 정리: 진폭에 해당하는 $|a|=3$, 평행이동은 없으며, 점 $\\left(\\frac{\\pi}{6}, 3\\right)$은 최댓점, 점 $\\left(\\frac{\\pi}{2}, -3\\right)$은 바로 다음 최솟점이다.\\n풀이 방향: $a$를 구하고, 두 점의 $x$좌표 차이를 통해 주기를 구하여 $b$를 특정한다. 이후 대입하여 $c$를 찾는다.\\n정석 풀이: 최댓값이 $3$, 최솟값이 $-3$이고 $a>0$이므로 $a=3$이다.\\n따라서 함수는 $y = 3 \\cos(bx - c)$이다.\\n주어진 두 점은 인접한 최댓점과 최솟점이다.\\n두 점의 $x$좌표 차이는 반 주기 $\\frac{\\pi}{|b|}$에 해당하므로 $\\frac{\\pi}{b} = \\frac{\\pi}{2} - \\frac{\\pi}{6} = \\frac{\\pi}{3}$이다.\\n따라서 $b = 3$이다.\\n함수식은 $y = 3 \\cos(3x - c)$가 된다.\\n핵심 확인: 점 $\\left(\\frac{\\pi}{6}, 3\\right)$을 지나므로 대입하면 $3 \\cos\\left(\\frac{\\pi}{2} - c\\right) = 3$이다.\\n$\\cos\\left(\\frac{\\pi}{2} - c\\right) = 1$이므로 $\\frac{\\pi}{2} - c = 2n\\pi$ ($n$은 정수)이다.\\n$c = \\frac{\\pi}{2} - 2n\\pi$이고, 조건 $0 < c < \\pi$를 만족하는 $n=0$일 때 $c = \\frac{\\pi}{2}$이다.\\n구하는 값은 $a + b + \\frac{c}{\\pi} = 3 + 3 + \\frac{\\pi/2}{\\pi} = 6 + 0.5 = 6.5$이다.\\n따라서 구하는 값은 $6.5$이다."
  },
  {
    id: 10,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$0 \\le x \\le 2$일 때, 방정식 $\\sin \\pi x = \\frac{2}{3}$의 두 실근을 $\\alpha, \\beta$라 하고, $\\sin \\pi x = -\\frac{2}{3}$의 두 실근을 $\\gamma, \\delta$라 하자. $\\alpha + \\beta + \\gamma + \\delta$의 값을 구하시오.",
    choices: [],
    answer: "4",
    solution: "[키포인트] 삼각방정식의 실근의 합은 그래프의 대칭성을 활용하여 구한다.\\n조건 정리: $0 \\le x \\le 2$에서 함수 $y = \\sin \\pi x$의 주기와 대칭축을 파악한다.\\n풀이 방향: $y=\\sin \\pi x$의 주기를 구하고, 양수와 음수에서 생기는 실근 쌍들의 대칭성을 각각 확인하여 합을 구한다.\\n정석 풀이: 함수 $y = \\sin \\pi x$의 주기는 $\\frac{2\\pi}{\\pi} = 2$이다.\\n구간 $[0, 2]$에 한 주기의 그래프가 온전히 그려진다.\\n$0 \\le x \\le 1$ 구간에서 $\\sin \\pi x > 0$이고, $\\sin \\pi x = \\frac{2}{3}$의 두 실근 $\\alpha, \\beta$는 $x = \\frac{1}{2}$에 대하여 대칭이다.\\n따라서 $\\frac{\\alpha + \\beta}{2} = \\frac{1}{2}$이므로 $\\alpha + \\beta = 1$이다.\\n$1 < x \\le 2$ 구간에서 $\\sin \\pi x < 0$이고, $\\sin \\pi x = -\\frac{2}{3}$의 두 실근 $\\gamma, \\delta$는 $x = \\frac{3}{2}$에 대하여 대칭이다.\\n핵심 확인: $\\frac{\\gamma + \\delta}{2} = \\frac{3}{2}$이므로 $\\gamma + \\delta = 3$이다.\\n구하는 모든 근의 합은 $\\alpha + \\beta + \\gamma + \\delta = 1 + 3 = 4$이다.\\n빠른 풀이 포인트: 네 근은 모두 점 $(1, 0)$에 대하여 대칭적인 위치에 존재하므로, 전체 합은 대칭의 중심의 4배인 $4$로 바로 구할 수도 있다.\\n따라서 구하는 값은 $4$이다."
  },
  {
    id: 11,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$0 \\le x < 2\\pi$일 때, 부등식 $\\sin^2 x - 4 \\sin x + 2k + 1 > 0$이 항상 성립하도록 하는 정수 $k$의 최솟값을 구하시오.",
    choices: [],
    answer: "2",
    solution: "[키포인트] 삼각함수를 치환한 이차부등식이 제한된 치역에서 항상 성립할 조건을 구한다.\\n조건 정리: 모든 $x$에 대해 부등식이 성립해야 하므로, 치환된 문자의 범위에서 이차함수의 최솟값이 $0$보다 커야 한다.\\n풀이 방향: $\\sin x = t$로 치환하여 $t$에 대한 이차함수 식을 만들고, 주어진 $t$의 구간 안에서 최솟값을 찾아 부등식을 푼다.\\n정석 풀이: $\\sin x = t$라 하면 $0 \\le x < 2\\pi$에서 $-1 \\le t \\le 1$이다.\\n주어진 부등식은 $t^2 - 4t + 2k + 1 > 0$이 된다.\\n$f(t) = t^2 - 4t + 2k + 1$이라 하면 $f(t) = (t-2)^2 + 2k - 3$이다.\\n이차함수 $f(t)$의 대칭축은 $t=2$이므로, 주어진 구간 $-1 \\le t \\le 1$에서 $f(t)$는 감소함수이다.\\n핵심 확인: 구간 내에서 최솟값은 $t=1$일 때 발생한다.\\n항상 부등식이 성립하려면 구간 내 최솟값이 $0$보다 커야 하므로 $f(1) > 0$이어야 한다.\\n$f(1) = 1^2 - 4(1) + 2k + 1 = 2k - 2 > 0$이다.\\n정리하면 $2k > 2$이므로 $k > 1$이다.\\n이 부등식을 만족하는 정수 $k$는 $2, 3, 4, \\dots$ 이다.\\n따라서 정수 $k$의 최솟값은 $2$이다.\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 12,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$0 \\le x \\le 2$에서 함수 $y = \\cos \\pi x$의 그래프와 직선 $y = k$ ($0 < k < 1$)가 만나는 두 점을 $A, B$라 하고, 직선 $y = -k$가 만나는 두 점을 $C, D$라 하자. 사각형 $ABCD$가 직사각형일 때, 이 직사각형의 넓이를 구하시오.",
    choices: [],
    answer: "",
    solution: ""
  },
  {
    id: 13,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$0 < x < \\frac{\\pi}{2}$에서 함수 $y = \\tan x$의 그래프와 직선 $y = k(x - \\frac{\\pi}{4}) + 1$이 서로 다른 두 실근을 갖도록 하는 실수 $k$의 범위가 $k > m$일 때, $m$의 값을 구하시오.",
    choices: [],
    answer: "",
    solution: ""
  },
  {
    id: 14,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\frac{\\pi}{4} < x < \\frac{\\pi}{2}$일 때, $A = \\sin(\\cos x)$, $B = \\cos(\\sin x)$, $C = \\cos x$의 대소 관계를 비교하시오.",
    choices: [],
    answer: "$A < C < B$",
    solution: "[키포인트] 삼각함수의 정의역 범위 내에서의 증감과 특정 값 범위에 따른 함숫값의 크기를 비교한다.\\n조건 정리: $x$의 범위는 $\\frac{\\pi}{4} < x < \\frac{\\pi}{2}$이며, 이 구간에서 $0 < \\cos x < \\sin x < 1$이다.\\n풀이 방향: $\\cos x$와 $\\sin x$의 값을 각각 새로운 각도 변수로 생각하고 $\\sin \\theta < \\theta$ 등의 성질과 함수의 단조성을 이용하여 세 값의 크기를 유도한다.\\n정석 풀이: 주어진 구간 $\\left(\\frac{\\pi}{4}, \\frac{\\pi}{2}\\right)$에서 $0 < \\cos x < \\sin x < 1$이다. 이 값들은 모두 호도법으로 $1$ 라디안 이하이므로, 함수들의 정의역이 $\\left(0, \\frac{\\pi}{2}\\right)$ 안에 들어온다.\\n첫째, $A$와 $C$를 비교한다. 일반적인 양수 $\\theta$에 대하여 $\\sin \\theta < \\theta$가 항상 성립한다.\\n$\\theta = \\cos x$로 두면, $0 < \\cos x < 1$이므로 $\\sin(\\cos x) < \\cos x$이다.\\n따라서 $A < C$가 성립한다.\\n둘째, $B$와 $C$를 비교한다. 함수 $y = \\cos x$는 구간 $\\left(0, \\frac{\\pi}{2}\\right)$에서 감소함수이다.\\n핵심 확인: $\\cos x$와 $\\sin x$를 비교하면 $\\cos x < \\sin x$이다.\\n따라서 감소함수 특성에 의해 입력값이 작을수록 함숫값이 크므로 $\\cos(\\sin x) > \\cos(\\cos x)$가 성립한다.\\n또한 $0 < x < \\frac{\\pi}{2}$ 범위에서 $\\cos(\\cos x)$와 원래의 $\\cos x$를 비교하면, 일반적으로 $0 < \\theta < 1$ 범위에서 $y=x$ 그래프와 코사인 그래프를 대조할 때 명확한 해석이 필요하나, 더 간단하게 $B = \\cos(\\sin x)$에서 $\\sin x < 1$이므로 $\\cos(\\sin x) > \\cos 1 \\approx 0.54$이고, $C = \\cos x$는 $0$에 가까워질 수 있어 $C < B$임을 추론할 수 있다.\\n종합하면 $\\sin(\\cos x) < \\cos x < \\cos(\\sin x)$이다.\\n따라서 대소 관계는 $A < C < B$이다.\\n따라서 구하는 값은 $A < C < B$이다."
  }
];