window.examTitle = "비상대수지수로그함수익힘책_고2_유형심화";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수 $y=-2^{x-1}+4$의 그래프에 대한 설명으로 옳은 것은?",
    choices: [
      "정의역은 $x<4$인 실수 전체이다.",
      "치역은 $y>4$인 실수 전체이다.",
      "$x$의 값이 증가하면 $y$의 값도 증가한다.",
      "$x$절편은 $3$이다.",
      "$y$절편은 $4$이다."
    ],
    answer: "④",
    solution: "[키포인트] 지수함수의 대칭과 평행이동에서는 정의역, 치역, 절편을 각각 확인한다.\\n조건 정리: 함수는 $y=-2^{x-1}+4$이고, $2^{x-1}>0$이다.\\n풀이 방향: 정의역과 치역을 먼저 판단하고, $x$절편과 $y$절편을 직접 구한다.\\n정석 풀이: 지수식 $2^{x-1}$은 모든 실수 $x$에서 정의되므로 정의역은 실수 전체이다. 또 $2^{x-1}>0$이므로 $-2^{x-1}<0$이고, 따라서 $y=-2^{x-1}+4<4$이다. 즉 치역은 $y<4$인 실수 전체이다. $x$절편은 $y=0$일 때이므로 $-2^{x-1}+4=0$에서 $2^{x-1}=4=2^2$이다. 따라서 $x-1=2$, $x=3$이다. 그러므로 $x$절편은 $3$이다. $y$절편은 $x=0$일 때 $y=-2^{-1}+4=\\dfrac{7}{2}$이다.\\n따라서 정답은 ④이다."
  },
  {
    id: 2,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 세 수\n$A=\\log_{\\frac12}6,\\quad B=\\log_{\\frac12}8,\\quad C=\\log_2\\dfrac17$\n의 대소를 비교하시오.",
    choices: [],
    answer: "$B<C<A$",
    solution: "[키포인트] 밑이 $\\dfrac{1}{2}$인 로그는 감소함수이고, 밑이 다른 로그는 밑을 통일하여 비교한다.\\n조건 정리: $A$와 $B$는 밑이 $\\dfrac{1}{2}$이고, $C$는 밑이 $2$이다.\\n풀이 방향: $C$도 밑이 $\\dfrac{1}{2}$인 로그로 바꾼 뒤 세 값을 비교한다.\\n정석 풀이: $C=\\log_2\\dfrac{1}{7}=-\\log_2 7$이다. 또 $\\log_{\\frac12}7=\\dfrac{\\log_2 7}{\\log_2 \\frac12}=-\\log_2 7$이므로 $C=\\log_{\\frac12}7$이다. 따라서 세 수는 $A=\\log_{\\frac12}6$, $B=\\log_{\\frac12}8$, $C=\\log_{\\frac12}7$로 볼 수 있다. 밑 $\\dfrac{1}{2}$은 $0$과 $1$ 사이이므로 진수가 클수록 로그값은 작다. 진수의 크기는 $6<7<8$이므로 로그값의 크기는 $\\log_{\\frac12}8<\\log_{\\frac12}7<\\log_{\\frac12}6$이다.\\n따라서 구하는 값은 $B<C<A$이다."
  },
  {
    id: 3,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "방정식\n$27^x=\\dfrac19$\n의 해를 $x=-\\dfrac ab$라 하자. 단, $a,b$는 서로소인 자연수이다. 또 부등식\n$\\log_{\\frac12}(x-1)\\ge -2$\n의 해가 $1<x\\le c$일 때, $a+b+c$의 값을 구하시오.",
    choices: [],
    answer: "10",
    solution: "[키포인트] 지수방정식은 밑을 통일하고, 밑이 $0$과 $1$ 사이인 로그부등식은 부등호 방향에 주의한다.\\n조건 정리: $27=3^3$, $\\dfrac{1}{9}=3^{-2}$이고, 로그부등식에서는 진수 조건 $x-1>0$이 필요하다.\\n풀이 방향: 먼저 지수방정식에서 $a,b$를 구하고, 로그부등식의 해를 구해 $c$를 찾는다.\\n정석 풀이: $27^x=\\dfrac{1}{9}$에서 $(3^3)^x=3^{-2}$이므로 $3^{3x}=3^{-2}$이다. 따라서 $3x=-2$, $x=-\\dfrac{2}{3}$이다. 그러므로 $a=2$, $b=3$이다. 이제 $\\log_{\\frac12}(x-1)\\ge -2$를 푼다. 먼저 진수 조건에서 $x-1>0$이므로 $x>1$이다. 밑 $\\dfrac{1}{2}$은 $0$과 $1$ 사이이므로 $\\log_{\\frac12}(x-1)\\ge -2$는 $x-1\\le \\left(\\dfrac{1}{2}\\right)^{-2}=4$와 같다. 따라서 $x\\le 5$이다. 진수 조건과 함께 정리하면 $1<x\\le 5$이므로 $c=5$이다. 따라서 $a+b+c=2+3+5=10$이다.\\n따라서 구하는 값은 $10$이다."
  },
  {
    id: 4,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "정의역이 $\\{x\\mid a\\le x\\le a+3\\}$인 함수\n$y=2^{x-b}+1$\n의 최솟값이 $3$, 최댓값이 $17$이다. 또한 $a+b=5$일 때, $ab$의 값을 구하시오.",
    choices: [],
    answer: "6",
    solution: "[키포인트] 증가하는 지수함수의 최솟값과 최댓값은 정의역의 양 끝에서 발생한다.\\n조건 정리: 함수 $y=2^{x-b}+1$은 밑이 $2$이므로 증가함수이고, 정의역은 $a\\le x\\le a+3$이다.\\n풀이 방향: 최솟값은 $x=a$, 최댓값은 $x=a+3$에서 나온다는 점을 이용해 식을 세운다.\\n정석 풀이: 최솟값이 $3$이므로 $x=a$를 대입하면 $2^{a-b}+1=3$이다. 따라서 $2^{a-b}=2=2^1$이므로 $a-b=1$이다. 최댓값이 $17$이므로 $x=a+3$을 대입하면 $2^{a+3-b}+1=17$이다. 즉 $2^{a+3-b}=16=2^4$이고 $a+3-b=4$이다. 이는 $a-b=1$과 일치한다. 또한 문제에서 $a+b=5$가 주어졌으므로 $a-b=1$, $a+b=5$를 연립한다. 두 식을 더하면 $2a=6$이므로 $a=3$이고, $b=2$이다. 따라서 $ab=3\\cdot 2=6$이다.\\n따라서 구하는 값은 $6$이다."
  },
  {
    id: 5,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "방정식\n$a^{2x}-13a^x+36=0$\n의 두 근의 차가 $2$일 때, $a>1$인 실수 $a$의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac32$",
    solution: "[키포인트] $a^x$를 치환한 뒤 두 근의 차를 로그의 차로 해석한다.\\n조건 정리: $a>1$이고, $a^x$는 양수이다.\\n풀이 방향: $t=a^x$로 치환해 이차방정식을 풀고, 두 $x$값의 차가 $2$라는 조건을 이용한다.\\n정석 풀이: $t=a^x$라 하면 주어진 방정식은 $t^2-13t+36=0$이다. 인수분해하면 $(t-4)(t-9)=0$이므로 $t=4$ 또는 $t=9$이다. 따라서 $a^x=4$, $a^x=9$에서 두 근은 각각 $\\log_a4$, $\\log_a9$이다. $a>1$이므로 $\\log_a9>\\log_a4$이다. 두 근의 차가 $2$이므로 $\\log_a9-\\log_a4=2$이다. 로그의 성질에 의해 $\\log_a\\dfrac{9}{4}=2$이다. 따라서 $a^2=\\dfrac{9}{4}$이고, $a>1$이므로 $a=\\dfrac{3}{2}$이다.\\n따라서 구하는 값은 $\\dfrac{3}{2}$이다."
  },
  {
    id: 6,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수 $f(x)=2x-1$, $g(x)=x^2-4$에 대하여 부등식\n$\\left(\\frac13\\right)^{f(x)}<\\left(\\frac13\\right)^{g(x)}$\n을 만족시키는 정수 $x$의 개수를 구하시오.",
    choices: [],
    answer: "3",
    solution: "[키포인트] 밑이 $0$과 $1$ 사이인 지수부등식은 지수의 대소 관계가 반대로 바뀐다.\\n조건 정리: $f(x)=2x-1$, $g(x)=x^2-4$이고, 밑은 $\\dfrac{1}{3}$이다.\\n풀이 방향: 밑이 $0$과 $1$ 사이임을 이용하여 $f(x)>g(x)$로 바꾼 뒤 정수해를 센다.\\n정석 풀이: 밑 $\\dfrac{1}{3}$은 $0$과 $1$ 사이이므로 $\\left(\\dfrac{1}{3}\\right)^{f(x)}<\\left(\\dfrac{1}{3}\\right)^{g(x)}$이면 $f(x)>g(x)$이다. 따라서 $2x-1>x^2-4$이다. 정리하면 $0>x^2-2x-3$이므로 $x^2-2x-3<0$이다. 인수분해하면 $(x-3)(x+1)<0$이므로 $-1<x<3$이다. 이 범위를 만족시키는 정수는 $0,1,2$로 모두 $3$개이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 7,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 함수의 그래프 중 함수 $y=3^x$의 그래프를 평행이동하거나 대칭이동하여 포개질 수 없는 것은?",
    choices: [
      "$y=3^{-x}+2$",
      "$y=-3^x+1$",
      "$y=3^{x+2}-4$",
      "$y=\\log_3(x-1)$",
      "$y=-3^{-x}$"
    ],
    answer: "④",
    solution: "[키포인트] 지수함수 그래프의 평행이동과 대칭이동으로는 로그함수 그래프를 만들 수 없다.\\n조건 정리: 기준 그래프는 $y=3^x$이다.\\n풀이 방향: 각 보기가 $y=3^x$의 평행이동 또는 대칭이동으로 얻어지는지 확인한다.\\n정석 풀이: ① $y=3^{-x}+2$는 $y=3^x$를 $y$축에 대하여 대칭이동한 뒤 위로 $2$만큼 평행이동한 그래프이다. ② $y=-3^x+1$은 $x$축에 대하여 대칭이동한 뒤 위로 $1$만큼 평행이동한 그래프이다. ③ $y=3^{x+2}-4$는 왼쪽으로 $2$만큼, 아래로 $4$만큼 평행이동한 그래프이다. ⑤ $y=-3^{-x}$는 $y=3^x$를 $y$축에 대하여 대칭이동한 뒤 $x$축에 대하여 대칭이동한 그래프이다. 그러나 ④ $y=\\log_3(x-1)$은 로그함수 그래프이므로 지수함수 그래프를 평행이동하거나 대칭이동하는 것만으로는 포개질 수 없다.\\n따라서 정답은 ④이다."
  },
  {
    id: 8,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수\n$y=\\log_3(ax),\\quad y=\\log_3\\dfrac{x}{3}$\n의 그래프와 두 직선 $x=2,\\ x=5$로 둘러싸인 도형의 넓이가 $12$일 때, 양수 $a$의 값을 구하시오.",
    choices: [],
    answer: "27",
    solution: "[키포인트] 두 로그함수의 차가 상수이면 그래프 사이의 넓이를 직사각형 넓이로 계산할 수 있다.\\n조건 정리: $a$는 양수이고, 두 직선은 $x=2$, $x=5$이다.\\n풀이 방향: 두 로그함수의 차를 구해 세로 길이를 나타내고, 주어진 넓이로 $a$를 구한다.\\n정석 풀이: 두 함수의 차는 $\\log_3(ax)-\\log_3\\dfrac{x}{3}=\\log_3\\left(ax\\cdot \\dfrac{3}{x}\\right)=\\log_3(3a)$이다. 두 직선 $x=2$, $x=5$ 사이의 가로 길이는 $5-2=3$이다. 넓이가 $12$이므로 $3\\cdot \\log_3(3a)=12$이다. 따라서 $\\log_3(3a)=4$이고, $3a=3^4=81$이다. 그러므로 $a=27$이다.\\n따라서 구하는 값은 $27$이다."
  },
  {
    id: 9,
    level: "상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\n$y=\\log_2(x-a)+\\log_2(b-x)$\n의 최댓값이 $6$이고, 그 최댓값을 갖는 $x$의 값이 $8$이다. 이때 $a+b$의 값을 구하시오.",
    choices: [],
    answer: "16",
    solution: "[키포인트] 로그의 합을 하나의 로그로 합치고, 두 양수의 곱이 최대가 되는 조건을 이용한다.\\n조건 정리: 로그가 정의되려면 $x-a>0$, $b-x>0$이므로 $a<x<b$이다. 최댓값은 $6$이고, 그때의 $x$값은 $8$이다.\\n풀이 방향: $y=\\log_2\\{(x-a)(b-x)\\}$로 바꾼 뒤, 곱 $(x-a)(b-x)$가 최대가 되는 위치와 최대값을 각각 조건으로 세운다.\\n정석 풀이: 로그의 성질에 의해 $y=\\log_2(x-a)+\\log_2(b-x)=\\log_2\\{(x-a)(b-x)\\}$이다. 여기서 $x-a$와 $b-x$는 양수이고, 두 수의 합은 $(x-a)+(b-x)=b-a$로 일정하다. 양수 두 수의 합이 일정할 때 곱은 두 수가 같을 때 최대가 된다. 따라서 $(x-a)(b-x)$가 최대가 되려면 $x-a=b-x$이어야 한다. 이 식을 정리하면 $2x=a+b$이다. 최댓값을 갖는 $x$가 $8$이므로 $2\\cdot 8=a+b$이다. 따라서 $a+b=16$이다. 실제로 이때 로그 안의 최대값은 $\\left(\\dfrac{b-a}{2}\\right)^2$이고, 최댓값 조건 $\\log_2\\left\\{\\left(\\dfrac{b-a}{2}\\right)^2\\right\\}=6$은 $b-a$의 값을 정하는 조건이다. 그러나 문제에서 묻는 것은 $a+b$이므로 최대가 되는 위치 조건만으로 결정된다.\\n핵심 확인: 최댓값이 생기려면 $a<b$이어야 하고, 최댓값을 갖는 점은 정의역 내부의 중점이다. $x=8$이 중점이므로 $a+b=16$이 확정된다.\\n따라서 구하는 값은 $16$이다."
  },
  {
    id: 10,
    level: "상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수 $y=\\log_3 x$의 그래프 위의 점을 $D$라 하자. 두 점\n$A(a,0),\\quad B(b,0)$\n과 $y$축 위의 점\n$C=(0,\\log_3 a)$\n에 대하여 사각형 $ABDC$가 평행사변형이다. $\\overline{AB}=5$일 때, $ab$의 값을 구하시오.",
    choices: [],
    answer: "50",
    solution: "[키포인트] 평행사변형의 좌표 관계와 로그함수 위의 점 조건을 함께 사용한다.\\n조건 정리: $A(a,0)$, $B(b,0)$, $C=(0,\\log_3 a)$이고, 사각형 $ABDC$는 평행사변형이다. 또한 $\\overline{AB}=5$이다. 로그식이 정의되려면 $a>0$이다.\\n풀이 방향: 평행사변형에서 네 번째 꼭짓점 $D$의 좌표를 $A,B,C$로 나타내고, $D$가 $y=\\log_3 x$ 위에 있다는 조건을 적용한다.\\n정석 풀이: 사각형 $ABDC$가 평행사변형이므로 $A$에서 $B$로 가는 벡터와 $C$에서 $D$로 가는 벡터가 같다. 따라서 $D=B+C-A$로 나타낼 수 있다. 좌표를 계산하면 $D=(b,0)+(0,\\log_3 a)-(a,0)=(b-a,\\log_3 a)$이다. 점 $D$가 함수 $y=\\log_3 x$의 그래프 위에 있으므로 $D$의 $y$좌표는 $D$의 $x$좌표에 로그를 취한 값과 같아야 한다. 따라서 $\\log_3 a=\\log_3(b-a)$이다. 로그함수는 일대일대응이므로 $a=b-a$이다. 따라서 $b=2a$이다. 한편 $A(a,0)$, $B(b,0)$은 둘 다 $x$축 위의 점이므로 $\\overline{AB}=|b-a|$이다. $b=2a$이고 $a>0$이므로 $|b-a|=|a|=a$이다. $\\overline{AB}=5$이므로 $a=5$이고, $b=10$이다. 따라서 $ab=5\\cdot 10=50$이다.\\n핵심 확인: $D$의 $x$좌표는 $b-a$이므로 로그함수 위에 있으려면 $b-a>0$이어야 한다. 위 결과에서는 $b-a=5>0$이므로 조건에 맞다.\\n따라서 구하는 값은 $50$이다."
  },
  {
    id: 11,
    level: "상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "방정식\n$(\\log_2 x)^2+k\\log_2 x+m=0$\n의 두 근의 곱이 $64$, 큰 근과 작은 근의 비가 $8$일 때, $4m$의 값을 구하시오.",
    choices: [],
    answer: "27",
    solution: "[키포인트] 실제 근은 $x$값이고, $\\log_2 x$로 치환한 값들의 합과 차를 조건에서 구해야 한다.\\n조건 정리: 주어진 방정식의 두 양수 근을 $\\alpha,\\beta$라 하고 $\\beta>\\alpha$라 두면 $\\alpha\\beta=64$이고 $\\dfrac{\\beta}{\\alpha}=8$이다.\\n풀이 방향: $t=\\log_2 x$로 치환하면 $t$에 대한 이차방정식이 된다. 이때 $x$의 곱과 비를 로그로 바꾸어 두 $t$값의 합과 차를 구한다.\\n정석 풀이: 두 근을 $\\alpha,\beta$라 하면 $\\alpha\\beta=64=2^6$이다. 양변에 $\\log_2$를 취하면 $\\log_2\\alpha+\\log_2\\beta=6$이다. 또 큰 근과 작은 근의 비가 $8$이므로 $\\dfrac{\\beta}{\\alpha}=8=2^3$이다. 양변에 $\\log_2$를 취하면 $\\log_2\\beta-\\log_2\\alpha=3$이다. 이제 $u=\\log_2\\alpha$, $v=\\log_2\\beta$라 두면 $u+v=6$, $v-u=3$이다. 두 식을 풀면 $v=\\dfrac{9}{2}$, $u=\\dfrac{3}{2}$이다. 한편 $t=\\log_2 x$로 치환하면 주어진 방정식은 $t^2+kt+m=0$이다. 이 이차방정식의 두 근은 $\\dfrac{3}{2}$, $\\dfrac{9}{2}$이다. 근과 계수의 관계에 의해 두 근의 곱은 $m$이므로 $m=\\dfrac{3}{2}\\cdot \\dfrac{9}{2}=\\dfrac{27}{4}$이다. 따라서 $4m=27$이다.\\n핵심 확인: 주어진 두 근의 곱과 비는 $x$값의 조건이므로 바로 $t$의 곱과 비로 쓰면 안 된다. 반드시 로그를 취해 $t$값의 합과 차로 바꾸어야 한다.\\n따라서 구하는 값은 $27$이다."
  },
  {
    id: 12,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어떤 세균의 수를 관찰하기 시작한 지 $x$시간 후의 세균 수를 $g(x)$라 하고\n$g(x)=k\\cdot 2^{\\frac xa}$\n라 하자. 관찰 시작 후 $3$시간이 지났을 때 세균의 수는 $10$이고, $11$시간이 지났을 때 세균의 수는 $160$이다. 세균의 수가 $1280$이 되는 것은 관찰 시작 후 몇 시간 뒤인지 구하시오.",
    choices: [],
    answer: "17시간",
    solution: "[키포인트] 지수 증가식에서 두 시점의 비를 이용하면 초기값 없이 증가 배율을 구할 수 있다.\\n조건 정리: $g(x)=k\\cdot 2^{\\frac{x}{a}}$, $g(3)=10$, $g(11)=160$이다.\\n풀이 방향: $g(11)$과 $g(3)$의 비를 이용하여 $a$를 구한 뒤, $g(x)=1280$이 되는 시각을 구한다.\\n정석 풀이: $\\dfrac{g(11)}{g(3)}=\\dfrac{k\\cdot 2^{\\frac{11}{a}}}{k\\cdot 2^{\\frac{3}{a}}}=2^{\\frac{8}{a}}$이다. 실제 값의 비는 $\\dfrac{160}{10}=16=2^4$이다. 따라서 $2^{\\frac{8}{a}}=2^4$이므로 $\\dfrac{8}{a}=4$, $a=2$이다. 이제 $g(3)=10$을 이용하면 $k\\cdot 2^{\\frac{3}{2}}=10$이다. $g(x)=1280$이 되는 시점을 직접 비교하면 $\\dfrac{g(x)}{g(3)}=\\dfrac{1280}{10}=128=2^7$이다. 한편 $\\dfrac{g(x)}{g(3)}=2^{\\frac{x-3}{2}}$이므로 $2^{\\frac{x-3}{2}}=2^7$이다. 따라서 $\\dfrac{x-3}{2}=7$, $x-3=14$, $x=17$이다.\\n따라서 구하는 값은 $17시간$이다."
  },
  {
    id: 13,
    level: "상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "제2사분면에서 함수 $y=8^{-x}$의 그래프 위의 점 $A$를 지나고 $x$축과 평행한 선분을 그어 함수 $y=2^{-x}$의 그래프와 만나는 점을 $B$라 한다. 점 $B$를 지나고 $y$축과 평행한 선분을 그어 함수 $y=8^{-x}$의 그래프와 만나는 점을 $C$라 하고, 점 $C$를 지나고 $x$축과 평행한 선분을 그어 함수 $y=2^{-x}$의 그래프와 만나는 점을 $D$라 할 때,\n$\\dfrac{\\overline{CD}}{\\overline{AB}}$\n의 값을 구하시오.",
    choices: [],
    answer: "3",
    solution: "[키포인트] 같은 높이에서 두 지수함수의 $x$좌표 관계를 구하고, 그 관계가 반복될 때 선분 길이의 비를 계산한다.\\n조건 정리: $8^{-x}=(2^3)^{-x}=2^{-3x}$이므로 함수 $y=8^{-x}$는 $y=2^{-3x}$로 볼 수 있다. 점 $A$는 제2사분면에 있으므로 $A$의 $x$좌표는 음수이다.\\n풀이 방향: 점 $A$의 $x$좌표를 문자로 두고, 수평 이동과 수직 이동을 따라가며 $B,C,D$의 $x$좌표를 차례로 구한다.\\n정석 풀이: 점 $A$의 $x$좌표를 $t$라 하자. 점 $A$는 $y=8^{-x}=2^{-3x}$ 위에 있으므로 $A=(t,2^{-3t})$이다. 점 $B$는 $A$와 같은 $y$좌표를 갖고 $y=2^{-x}$ 위에 있으므로 $2^{-x_B}=2^{-3t}$이다. 따라서 $x_B=3t$이다. 그러므로 수평 선분 $AB$의 길이는 $|3t-t|=2|t|$이다. 다음으로 점 $C$는 점 $B$와 $x$좌표가 같고 $y=8^{-x}$ 위에 있으므로 $C=(3t,8^{-3t})=(3t,2^{-9t})$이다. 점 $D$는 점 $C$와 같은 $y$좌표를 갖고 $y=2^{-x}$ 위에 있으므로 $2^{-x_D}=2^{-9t}$이다. 따라서 $x_D=9t$이다. 그러므로 수평 선분 $CD$의 길이는 $|9t-3t|=6|t|$이다. 따라서 $\\dfrac{\\overline{CD}}{\\overline{AB}}=\\dfrac{6|t|}{2|t|}=3$이다.\\n핵심 확인: $t<0$이지만 선분의 길이는 양수이므로 좌표 차에는 절댓값을 붙여야 한다. 절댓값을 사용하면 점이 제2사분면에 있다는 조건과 관계없이 길이의 비는 $3$으로 일정하다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 14,
    level: "상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "정수 전체의 집합의 두 부분집합\n$A=\\{x\\mid \\log_2(x+5)\\le k\\},$\n$B=\\left\\{x\\mid \\left(\\frac12\\right)^{x^2-5x}\\le 1\\right\\}$\n에 대하여 $n(A\\cap B)=5$를 만족시키는 자연수 $k$의 값을 구하시오.",
    choices: [],
    answer: "3",
    solution: "[키포인트] 로그부등식의 진수 조건, 지수부등식의 단조성, 정수 원소 개수를 모두 함께 확인한다.\\n조건 정리: 전체 집합은 정수 전체의 집합이고, $k$는 자연수이다. 집합 $A$에는 로그의 진수 조건이 필요하고, 집합 $B$에서는 밑이 $\\dfrac{1}{2}$이다.\\n풀이 방향: 먼저 $A$의 정수 범위를 $k$로 나타내고, $B$의 정수 범위를 구한다. 그다음 교집합의 원소 개수가 $5$가 되도록 $k$를 정한다.\\n정석 풀이: 집합 $A$에서 로그가 정의되려면 $x+5>0$이므로 정수 $x$에 대하여 $x\\ge -4$이다. 또한 $\\log_2(x+5)\\le k$이고 밑 $2$는 $1$보다 크므로 $x+5\\le 2^k$이다. 따라서 $A$는 $-4\\le x\\le 2^k-5$인 정수들의 집합이다. 다음으로 집합 $B$를 구한다. $1=\\left(\\dfrac{1}{2}\\right)^0$이고, 밑 $\\dfrac{1}{2}$은 $0$과 $1$ 사이이므로 $\\left(\\dfrac{1}{2}\\right)^{x^2-5x}\\le \\left(\\dfrac{1}{2}\\right)^0$이면 $x^2-5x\\ge 0$이다. 즉 $x(x-5)\\ge 0$이므로 $x\\le 0$ 또는 $x\\ge 5$이다. 이제 $A\\cap B$를 센다. $A$의 왼쪽 범위에서 $x\\le 0$인 정수는 $-4,-3,-2,-1,0$으로 이미 $5$개이다. 교집합의 원소가 정확히 $5$개가 되려면 $x\\ge 5$인 정수가 $A$에 포함되면 안 된다. 즉 $A$의 오른쪽 끝 $2^k-5$가 $5$보다 작아야 한다. 따라서 $2^k-5<5$이고 $2^k<10$이다. 또한 $A$가 왼쪽의 다섯 원소 $-4,-3,-2,-1,0$을 모두 포함하려면 $2^k-5\\ge 0$이어야 하므로 $2^k\\ge 5$이다. 따라서 $5\\le 2^k<10$이다. 자연수 $k$에 대하여 이를 만족하는 값은 $k=3$뿐이다.\\n핵심 확인: $k=2$이면 $2^k-5=-1$이 되어 $0$이 빠지므로 교집합 원소가 $4$개이다. $k=4$이면 $2^k-5=11$이 되어 $5$ 이상의 정수가 추가되므로 원소가 $5$개보다 많아진다. 따라서 $k=3$만 가능하다.\\n따라서 구하는 값은 $3$이다."
  }
];