window.examTitle = "비상대수지수로그_고2_유형";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a>0,\\ b>0$일 때, 다음 식을 간단히 하시오.\\n(1) $(a^2b)^{\\frac13}\\sqrt[3]{ab^2}$\\n(2) $\\sqrt[4]{a^3}\\div \\sqrt[8]{a^2}$\\n(3) $(\\sqrt a-\\sqrt b)(\\sqrt a+\\sqrt b)(a+b)$\\n(4) $(a^{\\frac23}-a^{-\\frac13})\\div a^{\\frac13}$",
    choices: [],
    answer: "(1) $ab$\\n(2) $\\sqrt a$\\n(3) $a^2-b^2$\\n(4) $a^{\\frac13}-a^{-\\frac23}$",
    solution: "[키포인트] 거듭제곱근과 유리수 지수를 지수법칙으로 정리한다.\\n조건 정리: $a>0,\\ b>0$이므로 거듭제곱근을 유리수 지수로 바꾸어 계산할 수 있다.\\n풀이 방향: 각 식을 같은 밑의 거듭제곱 꼴로 바꾼 뒤 지수를 더하거나 뺀다.\\n정석 풀이: (1) $(a^2b)^{\\frac13}\\sqrt[3]{ab^2}=a^{\\frac23}b^{\\frac13}\\cdot a^{\\frac13}b^{\\frac23}=a^{1}b^{1}=ab$이다.\\n(2) $\\sqrt[4]{a^3}\\div \\sqrt[8]{a^2}=a^{\\frac34}\\div a^{\\frac28}=a^{\\frac34-\\frac14}=a^{\\frac12}=\\sqrt a$이다.\\n(3) $(\\sqrt a-\\sqrt b)(\\sqrt a+\\sqrt b)=a-b$이므로 $(a-b)(a+b)=a^2-b^2$이다.\\n(4) $(a^{\\frac23}-a^{-\\frac13})\\div a^{\\frac13}=a^{\\frac23-\\frac13}-a^{-\\frac13-\\frac13}=a^{\\frac13}-a^{-\\frac23}$이다.\\n따라서 구하는 값은 (1) $ab$, (2) $\\sqrt a$, (3) $a^2-b^2$, (4) $a^{\\frac13}-a^{-\\frac23}$이다."
  },
  {
    id: 2,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "부피가 $8\\pi\\sqrt6$인 구의 반지름의 길이가 $\\sqrt[n]{6^m}$일 때, 서로소인 두 자연수 $m,\\ n$에 대하여 $m+n$의 값을 구하시오.",
    choices: [],
    answer: "$3$",
    solution: "[키포인트] 구의 부피 공식으로 반지름을 구한 뒤 유리수 지수로 나타낸다.\\n조건 정리: 구의 부피는 $V=\\dfrac43\\pi r^3$이고, 부피가 $8\\pi\\sqrt6$이다.\\n풀이 방향: 부피 공식에 대입하여 $r^3$을 구하고, $r$을 $\\sqrt[n]{6^m}$ 꼴로 나타낸다.\\n정석 풀이: $\\dfrac43\\pi r^3=8\\pi\\sqrt6$이므로 $r^3=6\\sqrt6=6^{\\frac32}$이다.\\n양변의 세제곱근을 구하면 $r=(6^{\\frac32})^{\\frac13}=6^{\\frac12}=\\sqrt6$이다.\\n따라서 $r=\\sqrt[2]{6^1}$이므로 $m=1,\\ n=2$이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 3,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a>1$일 때, 다음을 만족시키는 자연수 $k$의 값을 구하시오.\\n\\[\\n\\sqrt{a\\sqrt[3]{a^5}}=\\sqrt[6]{a^k}\\n\\]",
    choices: [],
    answer: "$8$",
    solution: "[키포인트] 양변을 모두 $a$의 지수 꼴로 바꾸어 지수를 비교한다.\\n조건 정리: $a>1$이므로 $a^p=a^q$이면 $p=q$이다.\\n풀이 방향: 왼쪽의 거듭제곱근을 유리수 지수로 정리한 뒤 오른쪽의 지수와 비교한다.\\n정석 풀이: 왼쪽은 $\\sqrt{a\\sqrt[3]{a^5}}=\\left(a\\cdot a^{\\frac53}\\right)^{\\frac12}=\\left(a^{\\frac83}\\right)^{\\frac12}=a^{\\frac43}$이다.\\n오른쪽은 $\\sqrt[6]{a^k}=a^{\\frac{k}{6}}$이다.\\n따라서 $a^{\\frac43}=a^{\\frac{k}{6}}$이므로 $\\dfrac43=\\dfrac{k}{6}$이다.\\n양변에 $6$을 곱하면 $k=8$이다.\\n따라서 구하는 값은 $8$이다."
  },
  {
    id: 4,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x>0$이고\\n\\[\\nx^{\\frac12}+x^{-\\frac12}=5\\n\\]\\n일 때, 다음 식의 값을 구하시오.\\n(1) $x+\\dfrac1x$\\n(2) $x^{\\frac32}+x^{-\\frac32}$",
    choices: [],
    answer: "(1) $23$\\n(2) $110$",
    solution: "[키포인트] $t=x^{\\frac12}+x^{-\\frac12}$의 제곱과 세제곱을 이용한다.\\n조건 정리: $x^{\\frac12}+x^{-\\frac12}=5$이다.\\n풀이 방향: 먼저 제곱하여 $x+\\dfrac1x$를 구하고, 세제곱 공식으로 $x^{\\frac32}+x^{-\\frac32}$를 구한다.\\n정석 풀이: 양변을 제곱하면 $(x^{\\frac12}+x^{-\\frac12})^2=x+2+x^{-1}=25$이다.\\n따라서 $x+\\dfrac1x=23$이다.\\n또 $a=x^{\\frac12},\\ b=x^{-\\frac12}$라 하면 $ab=1$이고 $a+b=5$이다.\\n$a^3+b^3=(a+b)^3-3ab(a+b)=5^3-3\\cdot1\\cdot5=125-15=110$이다.\\n따라서 구하는 값은 (1) $23$, (2) $110$이다."
  },
  {
    id: 5,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$2^x=3$일 때,\\n\\[\\n\\frac{2^{3x}+2^{-3x}}{2^x+2^{-x}}\\n\\]\\n의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{73}{9}$",
    solution: "[키포인트] $2^x=3$을 직접 대입하고 역수 지수까지 계산한다.\\n조건 정리: $2^x=3$이므로 $2^{-x}=\\dfrac13$이다.\\n풀이 방향: 분자와 분모를 각각 $3$과 $\\dfrac13$으로 바꾸어 계산한다.\\n정석 풀이: $2^{3x}=(2^x)^3=3^3=27$이고, $2^{-3x}=(2^{-x})^3=\\left(\\dfrac13\\right)^3=\\dfrac1{27}$이다.\\n분자는 $27+\\dfrac1{27}=\\dfrac{730}{27}$이고, 분모는 $3+\\dfrac13=\\dfrac{10}{3}$이다.\\n따라서 $\\dfrac{2^{3x}+2^{-3x}}{2^x+2^{-x}}=\\dfrac{730}{27}\\div\\dfrac{10}{3}=\\dfrac{730}{27}\\cdot\\dfrac3{10}=\\dfrac{73}{9}$이다.\\n따라서 구하는 값은 $\\dfrac{73}{9}$이다."
  },
  {
    id: 6,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 식을 간단히 하시오.\\n(1) $\\log_3 12+\\log_3\\dfrac94-\\log_3 3$\\n(2) $\\dfrac1{\\log_2 5}+\\dfrac1{\\log_4 5}-\\dfrac1{\\log_8 5}$\\n(3) $\\log_2 5\\cdot \\log_5 7\\cdot \\log_7 16$\\n(4) $2^{\\log_2 3\\cdot \\log_3 25}$",
    choices: [],
    answer: "(1) $2$\\n(2) $0$\\n(3) $4$\\n(4) $25$",
    solution: "[키포인트] 로그의 곱셈, 나눗셈, 밑변환 성질을 적용한다.\\n조건 정리: 같은 밑의 로그는 더하고 빼서 하나의 로그로 묶을 수 있고, $\\dfrac1{\\log_a b}=\\log_b a$이다.\\n풀이 방향: 각 식의 로그 성질을 적용하여 계산 가능한 형태로 바꾼다.\\n정석 풀이: (1) $\\log_3 12+\\log_3\\dfrac94-\\log_3 3=\\log_3\\left(12\\cdot\\dfrac94\\div3\\right)=\\log_3 9=2$이다.\\n(2) $\\dfrac1{\\log_2 5}+\\dfrac1{\\log_4 5}-\\dfrac1{\\log_8 5}=\\log_5 2+\\log_5 4-\\log_5 8=\\log_5\\dfrac{2\\cdot4}{8}=\\log_5 1=0$이다.\\n(3) $\\log_2 5\\cdot \\log_5 7\\cdot \\log_7 16=\\log_2 16=4$이다.\\n(4) $\\log_2 3\\cdot \\log_3 25=\\log_2 25$이므로 $2^{\\log_2 25}=25$이다.\\n따라서 구하는 값은 (1) $2$, (2) $0$, (3) $4$, (4) $25$이다."
  },
  {
    id: 7,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 로그가 정의되기 위한 실수 $x$의 값의 범위를 구하시오.\\n(1) $\\log_2(x^2-x-6)$\\n(2) $\\log_{x+2}(5-x)$",
    choices: [],
    answer: "(1) $x<-2$ 또는 $x>3$\\n(2) $-2<x<5,\\ x\\ne -1$",
    solution: "[키포인트] 로그는 진수가 양수이고 밑이 양수이며 밑이 $1$이 아니어야 한다.\\n조건 정리: $\\log_a M$이 정의되려면 $M>0$, $a>0$, $a\\ne1$이다.\\n풀이 방향: 각 로그에서 진수 조건과 밑 조건을 따로 확인한다.\\n정석 풀이: (1) 밑 $2$는 조건을 만족하므로 진수만 확인한다. $x^2-x-6>0$에서 $(x-3)(x+2)>0$이다. 따라서 $x<-2$ 또는 $x>3$이다.\\n(2) $\\log_{x+2}(5-x)$에서 진수 조건은 $5-x>0$이므로 $x<5$이다. 밑 조건은 $x+2>0$이므로 $x>-2$이고, $x+2\\ne1$이므로 $x\\ne-1$이다.\\n세 조건을 모두 만족해야 하므로 $-2<x<5,\\ x\\ne-1$이다.\\n따라서 구하는 범위는 (1) $x<-2$ 또는 $x>3$, (2) $-2<x<5,\\ x\\ne -1$이다."
  },
  {
    id: 8,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log_2 3=a,\\ \\log_2 5=b$일 때, 다음을 $a,\\ b$에 대한 식으로 나타내시오.\\n(1) $\\log_2 45$\\n(2) $\\log_5 12$",
    choices: [],
    answer: "(1) $2a+b$\\n(2) $\\dfrac{2+a}{b}$",
    solution: "[키포인트] 수를 소인수분해한 뒤 주어진 로그 $a,\\ b$로 나타낸다.\\n조건 정리: $\\log_2 3=a$, $\\log_2 5=b$이다.\\n풀이 방향: 로그의 곱셈 성질과 밑변환 공식을 사용한다.\\n정석 풀이: (1) $45=3^2\\cdot5$이므로 $\\log_2 45=\\log_2(3^2\\cdot5)=2\\log_2 3+\\log_2 5=2a+b$이다.\\n(2) 밑변환을 사용하면 $\\log_5 12=\\dfrac{\\log_2 12}{\\log_2 5}$이다. $12=2^2\\cdot3$이므로 $\\log_2 12=2+\\log_2 3=2+a$이다.\\n따라서 $\\log_5 12=\\dfrac{2+a}{b}$이다.\\n따라서 구하는 값은 (1) $2a+b$, (2) $\\dfrac{2+a}{b}$이다."
  },
  {
    id: 9,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$1$이 아닌 양수 $a,\\ b$가\\n\\[\\n\\log_2 a\\cdot \\log_b 16=1\\n\\]\\n을 만족시킬 때,\\n\\[\\n\\log_a b+\\log_b a\\n\\]\\n의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{17}{4}$",
    solution: "[키포인트] 로그를 같은 밑으로 바꾸어 두 로그값의 관계를 찾는다.\\n조건 정리: $\\log_b 16=\\dfrac{\\log_2 16}{\\log_2 b}=\\dfrac4{\\log_2 b}$이다.\\n풀이 방향: $A=\\log_2 a$, $B=\\log_2 b$로 두고 조건식을 단순화한다.\\n정석 풀이: $A=\\log_2 a$, $B=\\log_2 b$라고 하자. 그러면 조건은 $A\\cdot\\dfrac4B=1$이므로 $B=4A$이다.\\n이제 $\\log_a b=\\dfrac{\\log_2 b}{\\log_2 a}=\\dfrac BA=4$이고, $\\log_b a=\\dfrac AB=\\dfrac14$이다.\\n따라서 $\\log_a b+\\log_b a=4+\\dfrac14=\\dfrac{17}{4}$이다.\\n따라서 구하는 값은 $\\dfrac{17}{4}$이다."
  },
  {
    id: 10,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log 2.75=0.4393$임을 이용하여 다음 등식을 만족시키는 $M,\\ N$의 값을 구하시오.\\n(1) $\\log 2750=M$\\n(2) $\\log N=4.4393$",
    choices: [],
    answer: "(1) $M=3.4393$\\n(2) $N=27500$",
    solution: "[키포인트] 상용로그에서 $10$의 거듭제곱 배수는 로그값의 정수 부분을 바꾼다.\\n조건 정리: $\\log 2.75=0.4393$이다.\\n풀이 방향: $2750=2.75\\times10^3$으로 나타내고, 로그값 $4.4393$은 $0.4393+4$로 해석한다.\\n정석 풀이: (1) $2750=2.75\\times10^3$이므로 $\\log 2750=\\log 2.75+\\log 10^3=0.4393+3=3.4393$이다.\\n(2) $\\log N=4.4393=0.4393+4=\\log 2.75+\\log 10^4$이다. 따라서 $N=2.75\\times10^4=27500$이다.\\n따라서 구하는 값은 (1) $M=3.4393$, (2) $N=27500$이다."
  },
  {
    id: 11,
    level: "중상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 회사의 생산량이 전년도에 비해 해마다 $a\\%$씩 증가한다. 내년부터 시작하여 6년 후 생산량이 올해 생산량의 약 $3$배가 되도록 하는 자연수 $a$의 값을 구하시오.\\n단, $\\log 3=0.4771,\\ \\log 1.20=0.0792,\\ \\log 1.21=0.0828$로 계산한다.",
    choices: [],
    answer: "$20$",
    solution: "[키포인트] 해마다 같은 비율로 증가하므로 지수식으로 세우고 로그로 비교한다.\\n조건 정리: 매년 $a\\%$씩 증가하면 1년마다 생산량은 $1+\\dfrac{a}{100}$배가 된다.\\n풀이 방향: 6년 후 약 $3$배가 되어야 하므로 $\\left(1+\\dfrac{a}{100}\\right)^6\\approx3$을 만족하는 자연수 $a$를 찾는다.\\n정석 풀이: 로그를 취하면 $6\\log\\left(1+\\dfrac{a}{100}\\right)\\approx\\log3=0.4771$이다.\\n따라서 $\\log\\left(1+\\dfrac{a}{100}\\right)\\approx\\dfrac{0.4771}{6}\\approx0.0795$이다.\\n주어진 값에서 $\\log1.20=0.0792$, $\\log1.21=0.0828$이므로 $1+\\dfrac{a}{100}$은 $1.20$에 더 가깝다.\\n따라서 $a=20$이다.\\n따라서 구하는 값은 $20$이다."
  },
  {
    id: 12,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "\\[\\n\\sqrt{\\frac n2},\\quad \\sqrt[3]{\\frac n3}\\n\\]\\n이 모두 자연수가 되도록 하는 자연수 $n$의 최솟값을 구하시오.",
    choices: [],
    answer: "$648$",
    solution: "[키포인트] 제곱수 조건과 세제곱수 조건을 동시에 만족하도록 소인수의 지수를 맞춘다.\\n조건 정리: $\\sqrt{\\dfrac n2}$가 자연수이려면 $\\dfrac n2$는 완전제곱수이고, $\\sqrt[3]{\\dfrac n3}$이 자연수이려면 $\\dfrac n3$은 완전세제곱수이다.\\n풀이 방향: $n=2^a3^b$ 꼴에서 필요한 최소 지수를 찾는다.\\n정석 풀이: $\\dfrac n2=2^{a-1}3^b$가 완전제곱수이려면 $a-1$과 $b$가 모두 짝수이어야 한다.\\n또 $\\dfrac n3=2^a3^{b-1}$이 완전세제곱수이려면 $a$와 $b-1$이 모두 $3$의 배수이어야 한다.\\n$a$는 $a-1$이 짝수이고 $a$가 $3$의 배수인 최소 자연수이므로 $a=3$이다.\\n$b$는 $b$가 짝수이고 $b-1$이 $3$의 배수인 최소 자연수이므로 $b=4$이다.\\n따라서 $n=2^3\\cdot3^4=8\\cdot81=648$이다.\\n따라서 구하는 값은 $648$이다."
  },
  {
    id: 13,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "음이 아닌 두 정수 $m,\\ n$에 대하여\\n\\[\\n\\frac12\\log N=m\\log 3+n\\log 5\\n\\]\\n를 만족시키는 모든 자연수 $N$의 값의 합을 구하시오.\\n단, $m,\\ n$은 모두 $0$이 아니고, $1\\le N\\le 225$이다.",
    choices: [],
    answer: "$225$",
    solution: "[키포인트] 로그식의 양변을 하나의 로그로 묶어 $N$의 꼴을 찾는다.\\n조건 정리: $m,\\ n$은 모두 $0$이 아닌 음이 아닌 정수이므로 $m\\ge1$, $n\\ge1$이다.\\n풀이 방향: $\\dfrac12\\log N=\\log 3^m+\\log 5^n$으로 바꾸어 $N$을 표현한다.\\n정석 풀이: 오른쪽은 $m\\log3+n\\log5=\\log(3^m5^n)$이다.\\n따라서 $\\dfrac12\\log N=\\log(3^m5^n)$이고, 양변에 $2$를 곱하면 $\\log N=\\log(3^{2m}5^{2n})$이다.\\n그러므로 $N=3^{2m}5^{2n}$이다. $m\\ge1$, $n\\ge1$이므로 가장 작은 값은 $3^2\\cdot5^2=225$이다.\\n조건 $1\\le N\\le225$를 만족하려면 $N=225$뿐이다.\\n따라서 모든 자연수 $N$의 합은 $225$이다.\\n따라서 구하는 값은 $225$이다."
  },
  {
    id: 14,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "망각 모델이\\n\\[\\n\\log P_0-\\log P_t=c\\log(t+1)\\n\\]\\n로 주어진다고 하자. $P_0$는 처음 기억 상태, $P_t$는 $t$개월 후의 기억 상태이다. 8개월 후의 기억 상태가 2개월 후의 기억 상태의 $\\dfrac1{16}$일 때, 상수 $c$의 값을 구하시오.",
    choices: [],
    answer: "$\\log_3 16$",
    solution: "[키포인트] 두 시점의 식을 각각 세운 뒤 빼서 비율 조건을 이용한다.\\n조건 정리: $8$개월 후의 기억 상태가 $2$개월 후의 기억 상태의 $\\dfrac1{16}$이므로 $P_8=\\dfrac1{16}P_2$이다.\\n풀이 방향: $t=8$과 $t=2$를 각각 대입한 식을 빼면 $P_2$와 $P_8$의 비율만 남는다.\\n정석 풀이: $t=8$일 때 $\\log P_0-\\log P_8=c\\log9$이다.\\n$t=2$일 때 $\\log P_0-\\log P_2=c\\log3$이다.\\n두 식을 빼면 $\\log P_2-\\log P_8=c(\\log9-\\log3)=c\\log3$이다.\\n그런데 $P_8=\\dfrac1{16}P_2$이므로 $\\dfrac{P_2}{P_8}=16$이고, $\\log P_2-\\log P_8=\\log16$이다.\\n따라서 $\\log16=c\\log3$이므로 $c=\\dfrac{\\log16}{\\log3}=\\log_3 16$이다.\\n따라서 구하는 값은 $\\log_3 16$이다."
  },
  {
    id: 1,
    level: "중",
    category: "지수함수와 로그함수",
    originalCategory: "지수함수와 로그함수",
    standardCourse: "대수",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "정의역이 $\\{x\\mid 0\\le x\\le 2\\}$일 때, 다음 함수의 최댓값과 최솟값을 구하시오.\\n(1) $y=3^{x-1}+2$\\n(2) $y=\\log_{\\frac12}(x+2)-1$",
    choices: [],
    answer: "(1) 최댓값 $5$, 최솟값 $\\dfrac73$\\n(2) 최댓값 $-2$, 최솟값 $-3$",
    solution: "[키포인트] 정의역의 양 끝값과 함수의 증가·감소를 이용하여 최댓값과 최솟값을 구한다.\\n조건 정리: 정의역은 $0\\le x\\le2$이다. (1)은 밑이 $3>1$인 지수함수이고, (2)는 밑이 $0<\\dfrac12<1$인 로그함수이다.\\n풀이 방향: (1)은 증가함수이므로 양 끝값을 비교하고, (2)는 감소함수이므로 양 끝값을 비교한다.\\n정석 풀이: (1) $y=3^{x-1}+2$는 $x$가 증가하면 $3^{x-1}$도 증가하므로 증가함수이다. 따라서 최솟값은 $x=0$에서 $3^{-1}+2=\\dfrac13+2=\\dfrac73$이고, 최댓값은 $x=2$에서 $3^1+2=5$이다.\\n(2) $y=\\log_{\\frac12}(x+2)-1$은 밑이 $\\dfrac12$이므로 감소함수이다. 정의역에서 $x+2$는 $2\\le x+2\\le4$이다. 최댓값은 $x=0$에서 $\\log_{\\frac12}2-1=-1-1=-2$이고, 최솟값은 $x=2$에서 $\\log_{\\frac12}4-1=-2-1=-3$이다.\\n따라서 구하는 값은 (1) 최댓값 $5$, 최솟값 $\\dfrac73$, (2) 최댓값 $-2$, 최솟값 $-3$이다."
  },
  {
    id: 2,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\\n\\[\\ny=\\left(\\frac13\\right)^{x+a}+b\\n\\]\\n의 그래프가 직선 $y=2$를 점근선으로 하고, 점 $(-1,5)$를 지날 때, 실수 $a,\\ b$의 값을 구하시오.",
    choices: [],
    answer: "$a=0,\\ b=2$",
    solution: "[키포인트] 지수함수의 수직 평행이동 값은 수평점근선에서 결정된다.\\n조건 정리: $y=\\left(\\dfrac13\\right)^{x+a}+b$의 수평점근선은 $y=b$이다.\\n풀이 방향: 점근선으로 $b$를 먼저 구한 뒤, 지나는 점을 대입하여 $a$를 구한다.\\n정석 풀이: 그래프의 점근선이 직선 $y=2$이므로 $b=2$이다.\\n그래프가 점 $(-1,5)$를 지나므로 $5=\\left(\\dfrac13\\right)^{-1+a}+2$이다. 따라서 $\\left(\\dfrac13\\right)^{a-1}=3$이다.\\n$3=\\left(\\dfrac13\\right)^{-1}$이므로 $a-1=-1$이고, $a=0$이다.\\n따라서 구하는 값은 $a=0$, $b=2$이다."
  },
  {
    id: 3,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\\n\\[\\ny=3\\cdot 2^x-4\\n\\]\\n의 그래프를 $x$축의 방향으로 $2$만큼 평행이동한 후, $y$축에 대하여 대칭이동한 그래프가 점 $(1,k)$를 지날 때, 실수 $k$의 값을 구하시오.",
    choices: [],
    answer: "$-\\dfrac{29}{8}$",
    solution: "[키포인트] 평행이동과 대칭이동을 순서대로 식에 반영한다.\\n조건 정리: 원래 함수는 $f(x)=3\\cdot2^x-4$이다.\\n풀이 방향: 먼저 $x$축의 방향으로 $2$만큼 평행이동한 식을 구하고, 그다음 $y$축 대칭을 적용한다.\\n정석 풀이: $f(x)$의 그래프를 $x$축의 방향으로 $2$만큼 평행이동하면 $y=f(x-2)=3\\cdot2^{x-2}-4$이다.\\n이 그래프를 $y$축에 대하여 대칭이동하면 $x$ 대신 $-x$를 넣어 $y=3\\cdot2^{-x-2}-4$가 된다.\\n이 그래프가 점 $(1,k)$를 지나므로 $k=3\\cdot2^{-3}-4=\\dfrac38-4=-\\dfrac{29}{8}$이다.\\n따라서 구하는 값은 $-\\dfrac{29}{8}$이다."
  },
  {
    id: 4,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수\\n\\[\\ny=\\left(\\frac13\\right)^x,\\qquad y=\\left(\\frac19\\right)^x\\n\\]\\n의 그래프와 직선 $y=9$가 만나는 점을 각각 $A,\\ B$라 하자. 원점 $O$에 대하여 삼각형 $AOB$의 넓이를 구하시오.",
    choices: [],
    answer: "$\\dfrac92$",
    solution: "[키포인트] 직선 $y=9$와 만나는 두 점의 $x$좌표를 구해 삼각형의 밑변과 높이를 구한다.\\n조건 정리: 두 점 $A$, $B$는 모두 직선 $y=9$ 위에 있으므로 두 점의 $y$좌표는 모두 $9$이다.\\n풀이 방향: 각각의 함수에서 $y=9$가 되는 $x$값을 구하면, 두 점 사이의 거리를 밑변으로 볼 수 있다.\\n정석 풀이: $\\left(\\dfrac13\\right)^x=9=3^2$이므로 $3^{-x}=3^2$에서 $x=-2$이다.\\n또 $\\left(\\dfrac19\\right)^x=9$는 $3^{-2x}=3^2$이므로 $-2x=2$, $x=-1$이다.\\n따라서 두 점은 $A(-2,9)$, $B(-1,9)$이다. 두 점 사이의 거리는 $1$이고, 원점에서 직선 $y=9$까지의 거리는 $9$이다.\\n삼각형 $AOB$의 넓이는 $\\dfrac12\\cdot1\\cdot9=\\dfrac92$이다.\\n따라서 구하는 값은 $\\dfrac92$이다."
  },
  {
    id: 5,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 세 수의 대소를 비교하시오.\\n(1) $\\sqrt{0.04},\\ \\sqrt[3]{0.008},\\ \\sqrt[4]{0.0016}$\\n(2) $\\log_2 5,\\ \\log_4 9,\\ 2$",
    choices: [],
    answer: "(1) $\\sqrt{0.04}=\\sqrt[3]{0.008}=\\sqrt[4]{0.0016}$\\n(2) $\\log_4 9<2<\\log_2 5$",
    solution: "[키포인트] 거듭제곱근은 직접 값으로 바꾸고, 로그는 같은 기준으로 비교한다.\\n조건 정리: $0.04=0.2^2$, $0.008=0.2^3$, $0.0016=0.2^4$이다.\\n풀이 방향: (1)은 거듭제곱근 값을 직접 계산하고, (2)는 각 로그값이 어느 정수 사이에 있는지 판단한다.\\n정석 풀이: (1) $\\sqrt{0.04}=0.2$, $\\sqrt[3]{0.008}=0.2$, $\\sqrt[4]{0.0016}=0.2$이다. 따라서 세 수는 모두 같다.\\n(2) $2^2=4<5$이므로 $\\log_2 5>2$이다. 또 $4^1=4<9<16=4^2$이므로 $1<\\log_4 9<2$이다.\\n따라서 $\\log_4 9<2<\\log_2 5$이다.\\n따라서 대소관계는 (1) $\\sqrt{0.04}=\\sqrt[3]{0.008}=\\sqrt[4]{0.0016}$, (2) $\\log_4 9<2<\\log_2 5$이다."
  },
  {
    id: 6,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "오른쪽 그림은 함수 $y=\\log_3 x$의 그래프와 직선 $y=x$를 나타낸 것이다. 함수 $y=\\log_3 x$의 그래프 위의 점 $A$의 $y$좌표가 $2$이고, 점 $A$에서 $x$축에 내린 수선의 발을 $B$라 하자. 점 $B$의 $x$좌표를 $a$라 할 때, $a$의 값을 구하시오.",
    choices: [],
    answer: "$9$",
    solution: "[키포인트] 로그함수 위의 점은 좌표를 로그식에 대입하여 구한다.\\n조건 정리: 점 $A$는 $y=\\log_3 x$ 위에 있고, 점 $A$의 $y$좌표는 $2$이다.\\n풀이 방향: $2=\\log_3 x$를 만족하는 $x$좌표를 구하면, 수선의 발 $B$의 $x$좌표도 같다.\\n정석 풀이: 점 $A$의 좌표를 $(x,2)$라고 하면 $2=\\log_3 x$이다.\\n로그식을 지수식으로 바꾸면 $x=3^2=9$이다.\\n점 $A$에서 $x$축에 내린 수선의 발 $B$는 $A$와 같은 $x$좌표를 가지므로 $a=9$이다.\\n따라서 구하는 값은 $9$이다."
  },
  {
    id: 7,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\\n\\[\\ny=\\log_{\\frac12}(x+2)+k\\n\\]\\n의 그래프가 제3사분면을 지나지 않도록 하는 실수 $k$의 최솟값을 구하시오.",
    choices: [],
    answer: "$1$",
    solution: "[키포인트] 제3사분면을 지나지 않으려면 $x<0$인 구간에서 $y<0$이 되지 않아야 한다.\\n조건 정리: 함수의 정의역은 $x+2>0$이므로 $x>-2$이다. 제3사분면은 $x<0$, $y<0$인 영역이다.\\n풀이 방향: $-2<x<0$에서 $\\log_{\\frac12}(x+2)+k$가 음수가 되지 않도록 $k$의 최솟값을 구한다.\\n정석 풀이: $-2<x<0$이면 $0<x+2<2$이다. 밑이 $\\dfrac12$인 로그함수는 감소함수이므로 $x+2$가 $2$에 가까워질 때 로그값은 $\\log_{\\frac12}2=-1$에 가까워진다.\\n따라서 $-2<x<0$에서 $\\log_{\\frac12}(x+2)$의 값은 $-1$보다 크다.\\n그러므로 $y=\\log_{\\frac12}(x+2)+k$가 제3사분면을 지나지 않으려면 $-1+k\\ge0$에 해당하는 경계가 필요하므로 $k\\ge1$이다.\\n최솟값은 $k=1$이다.\\n따라서 구하는 값은 $1$이다."
  },
  {
    id: 8,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수\\n\\[\\ny=\\log_2 x,\\qquad y=\\log_4 x\\n\\]\\n의 그래프와 직선 $x=k$가 만나는 점을 각각 $A,\\ B$라 하자. $\\overline{AB}=2$일 때, 실수 $k$의 값을 구하시오.\\n단, $k>1$이다.",
    choices: [],
    answer: "$16$",
    solution: "[키포인트] 같은 $x$좌표에서 두 로그함수의 $y$값 차이가 선분 $AB$의 길이이다.\\n조건 정리: 직선 $x=k$에서 두 점의 좌표는 $A(k,\\log_2 k)$, $B(k,\\log_4 k)$이다.\\n풀이 방향: $k>1$이므로 $\\log_2 k>\\log_4 k$이고, 두 값의 차이를 $2$로 둔다.\\n정석 풀이: $\\log_4 k=\\dfrac{\\log_2 k}{\\log_2 4}=\\dfrac12\\log_2 k$이다.\\n따라서 $\\overline{AB}=\\log_2 k-\\log_4 k=\\log_2 k-\\dfrac12\\log_2 k=\\dfrac12\\log_2 k$이다.\\n$\\overline{AB}=2$이므로 $\\dfrac12\\log_2 k=2$이고, $\\log_2 k=4$이다.\\n따라서 $k=2^4=16$이다.\\n따라서 구하는 값은 $16$이다."
  },
  {
    id: 9,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "부등식\\n\\[\\n(2^x-32)\\left(\\left(\\frac13\\right)^x-9\\right)>0\\n\\]\\n을 만족시키는 모든 정수 $x$의 개수를 구하시오.",
    choices: [],
    answer: "$6$",
    solution: "[키포인트] 두 인수의 부호가 같아야 곱이 양수가 된다.\\n조건 정리: $2^x-32=0$에서 $x=5$이고, $\\left(\\dfrac13\\right)^x-9=0$에서 $3^{-x}=3^2$이므로 $x=-2$이다.\\n풀이 방향: 두 인수의 부호가 바뀌는 기준점 $-2$, $5$를 기준으로 구간을 나눈다.\\n정석 풀이: $2^x-32$는 $x>5$일 때 양수, $x<5$일 때 음수이다.\\n$\\left(\\dfrac13\\right)^x-9=3^{-x}-9$는 $x<-2$일 때 양수, $x>-2$일 때 음수이다.\\n두 인수의 곱이 양수가 되려면 둘 다 양수이거나 둘 다 음수이어야 한다. 둘 다 음수인 경우는 $-2<x<5$이다.\\n정수 $x$는 $-1,0,1,2,3,4$로 모두 $6$개이다.\\n따라서 구하는 값은 $6$이다."
  },
  {
    id: 10,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 세균 한 마리가 $t$시간 후에 $a^t$마리로 증식된다고 한다. 세균 $5$마리가 $8$시간 후에 $1280$마리 이상이 되도록 하는 자연수 $a$의 최솟값을 구하시오.",
    choices: [],
    answer: "$2$",
    solution: "[키포인트] 한 마리의 증식량에 처음 세균 수를 곱해 전체 세균 수를 표현한다.\\n조건 정리: 세균 한 마리가 $t$시간 후에 $a^t$마리이므로, 처음 세균이 $5$마리이면 $8$시간 후 세균 수는 $5a^8$이다.\\n풀이 방향: $5a^8\\ge1280$을 만족하는 자연수 $a$의 최솟값을 구한다.\\n정석 풀이: $5a^8\\ge1280$이므로 $a^8\\ge256$이다.\\n$256=2^8$이므로 $a^8\\ge2^8$이다. $a$는 자연수이므로 이를 만족하는 최솟값은 $a=2$이다.\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 11,
    level: "중상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "환경 정화 작업을 통해 어느 하천의 오염 물질을 전년도에 비해 $5\\%$씩 해마다 감소시킨다고 한다. 오염 물질이 현재 오염 물질의 $\\dfrac12$배 이하가 되는 것은 최소 몇 년 후인지 구하시오.\\n단, $\\log 2=0.30,\\ \\log 9.5=0.98$로 계산한다.",
    choices: [],
    answer: "$15$년",
    solution: "[키포인트] 해마다 $5\\%$씩 감소하므로 남은 비율은 매년 $0.95$배가 된다.\\n조건 정리: $n$년 후 오염 물질의 양은 현재의 $(0.95)^n$배이다.\\n풀이 방향: $(0.95)^n\\le\\dfrac12$를 만족하는 최소 자연수 $n$을 로그로 구한다.\\n정석 풀이: $0.95=\\dfrac{9.5}{10}$이므로 $\\log0.95=\\log9.5-1=0.98-1=-0.02$이다.\\n부등식 $(0.95)^n\\le\\dfrac12$의 양변에 상용로그를 취하면 $n\\log0.95\\le\\log\\dfrac12=-\\log2=-0.30$이다.\\n$\\log0.95=-0.02$는 음수이므로 부등호 방향에 주의하여 $n\\ge\\dfrac{-0.30}{-0.02}=15$이다.\\n따라서 최소 $15$년 후이다.\\n따라서 구하는 값은 $15$년이다."
  },
  {
    id: 12,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "점 $P(8,2)$가 함수\\n\\[\\ny=\\log_a(x+b)\\n\\]\\n의 그래프 위에 있다. 이 그래프의 점근선이 직선 $x=-8$일 때,\\n\\[\\n\\log_2 ab\\n\\]\\n의 값을 구하시오. 단, $a>0,\\ a\\ne1,\\ b>0$이다.",
    choices: [],
    answer: "$5$",
    solution: "[키포인트] 로그함수 $y=\\log_a(x+b)$의 점근선은 $x=-b$이다.\\n조건 정리: 점근선이 $x=-8$이므로 $b=8$이다. 점 $P(8,2)$가 그래프 위에 있다.\\n풀이 방향: $b$를 먼저 구하고, 점 $P$를 대입하여 $a$를 구한다.\\n정석 풀이: 점근선 $x=-b$가 $x=-8$이므로 $b=8$이다.\\n점 $P(8,2)$가 그래프 위에 있으므로 $2=\\log_a(8+8)=\\log_a16$이다.\\n따라서 $a^2=16$이다. $a>0$, $a\\ne1$이므로 $a=4$이다.\\n그러므로 $ab=4\\cdot8=32$이고, $\\log_2 ab=\\log_2 32=5$이다.\\n따라서 구하는 값은 $5$이다."
  },
  {
    id: 13,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 전자 기기에서 방출되는 전자파의 양을 $T_0$, 이 전자 기기로부터의 거리가 $y\\text{ cm}$인 지점에서 측정되는 전자파의 양을 $T$라고 하면\\n\\[\\ny=c\\log_2\\frac{T_0}{T}\\n\\]\\n라고 한다. 이 전자 기기로부터의 거리가 $20\\text{ cm}$인 지점에서 측정되는 전자파의 양이 방출되는 전자파의 양의 $\\dfrac14$이라고 할 때, 이 전자 기기로부터의 거리가 $50\\text{ cm}$인 지점에서 측정되는 전자파의 양은 방출되는 전자파의 양의 몇 $\\%$인지 구하시오.",
    choices: [],
    answer: "$\\dfrac{25}{8}\\%$",
    solution: "[키포인트] 주어진 거리와 비율을 이용하여 상수 $c$를 먼저 구한다.\\n조건 정리: $y=c\\log_2\\dfrac{T_0}{T}$이고, $y=20$일 때 $T=\\dfrac14T_0$이다.\\n풀이 방향: 먼저 $c$를 구한 뒤, $y=50$을 대입하여 $T$가 $T_0$의 몇 배인지 구한다.\\n정석 풀이: $T=\\dfrac14T_0$이면 $\\dfrac{T_0}{T}=4$이다. 따라서 $20=c\\log_2 4=2c$이므로 $c=10$이다.\\n이제 $y=50$을 대입하면 $50=10\\log_2\\dfrac{T_0}{T}$이므로 $\\log_2\\dfrac{T_0}{T}=5$이다.\\n따라서 $\\dfrac{T_0}{T}=2^5=32$이고, $T=\\dfrac1{32}T_0$이다.\\n이를 백분율로 나타내면 $\\dfrac1{32}\\times100=\\dfrac{100}{32}=\\dfrac{25}{8}$이다.\\n따라서 구하는 값은 $\\dfrac{25}{8}\\%$이다."
  }
];