window.examTitle = "비상대수삼각함수2_고2_유형변형";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "반지름의 길이가 $6$인 원에 내접하는 삼각형 $\\text{ABC}$에서 $a=6\\sqrt{2}$일 때, $\\cos A$의 값을 구하시오. (단, $0^\\circ < A < 90^\\circ$)",
    choices: [],
    answer: "\\frac{\\sqrt{2}}{2}",
    solution: "[키포인트] 사인법칙: $\\dfrac{a}{\\sin A} = 2R$\\n조건 정리: 외접원의 반지름 $R=6$, 변의 길이 $a=6\\sqrt{2}$, $0^\\circ < A < 90^\\circ$\\n풀이 방향: 사인법칙을 이용하여 $\\sin A$를 구한 후, 삼각함수의 성질을 이용하여 $\\cos A$를 구한다.\\n정석 풀이: 사인법칙에 의해 $\\dfrac{a}{\\sin A} = 2R$이므로 $\\sin A = \\dfrac{a}{2R} = \\dfrac{6\\sqrt{2}}{12} = \\dfrac{\\sqrt{2}}{2}$이다.\\n$0^\\circ < A < 90^\\circ$이므로 $A = 45^\\circ$이다.\\n따라서 $\\cos A = \\cos 45^\\circ = \\dfrac{\\sqrt{2}}{2}$이다.\\n따라서 구하는 값은 $\\dfrac{\\sqrt{2}}{2}$이다."
  },
  {
    id: 2,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "삼각형 $\\text{ABC}$의 둘레의 길이가 $40$이고 $\\sin A + \\sin B + \\sin C = \\frac{5}{2}$일 때, 외접원의 반지름의 길이를 구하시오.",
    choices: [],
    answer: "8",
    solution: "[키포인트] 사인법칙: $\\sin A = \\dfrac{a}{2R}$\\n조건 정리: $a+b+c=40$, $\\sin A + \\sin B + \\sin C = \\dfrac{5}{2}$\\n풀이 방향: 사인법칙을 이용하여 사인 값의 합을 변의 길이의 합으로 변환한다.\\n정석 풀이: 외접원의 반지름을 $R$이라 하면, 사인법칙에 의해 $\\sin A = \\dfrac{a}{2R}$, $\\sin B = \\dfrac{b}{2R}$, $\\sin C = \\dfrac{c}{2R}$이다.\\n주어진 식에 대입하면 $\\dfrac{a}{2R} + \\dfrac{b}{2R} + \\dfrac{c}{2R} = \\dfrac{a+b+c}{2R} = \\dfrac{5}{2}$이다.\\n$a+b+c=40$이므로 $\\dfrac{40}{2R} = \\dfrac{5}{2}$, 즉 $\\dfrac{20}{R} = \\dfrac{5}{2}$이다.\\n$5R = 40$에서 $R = 8$이다.\\n따라서 구하는 값은 $8$이다."
  },
  {
    id: 3,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "원 모양의 연못가에 세 지점 $\\text{A, B, C}$가 있다. 삼각형 $\\text{ABC}$에서 $B=50^\\circ$, $C=85^\\circ$이고 $\\overline{\\text{BC}}=12\\sqrt{2}\\text{m}$일 때, 연못의 넓이를 구하시오.",
    choices: [],
    answer: "144\\pi",
    solution: "[키포인트] 삼각형의 내각의 합과 사인법칙\\n조건 정리: $B=50^\\circ$, $C=85^\\circ$, $a=12\\sqrt{2}$\\n풀이 방향: $\\angle A$를 구한 뒤 사인법칙을 이용하여 외접원의 반지름 $R$을 구하고 넓이를 계산한다.\\n정석 풀이: 삼각형의 세 내각의 크기의 합은 $180^\\circ$이므로 $A = 180^\\circ - (50^\\circ + 85^\\circ) = 45^\\circ$이다.\\n사인법칙에 의해 $\\dfrac{a}{\\sin A} = 2R$이므로 $\\dfrac{12\\sqrt{2}}{\\sin 45^\\circ} = 2R$이다.\\n$2R = \\dfrac{12\\sqrt{2}}{\\dfrac{\\sqrt{2}}{2}} = 24$이므로 $R = 12$이다.\\n연못은 외접원이므로 넓이는 $\\pi \\cdot 12^2 = 144\\pi$이다.\\n따라서 구하는 값은 $144\\pi$이다."
  },
  {
    id: 4,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 등식을 만족시키는 삼각형 $\\text{ABC}$는 어떤 삼각형인지 말하시오.<br />$a \\cos B = b \\cos A$",
    choices: [],
    answer: "a=b인 이등변삼각형",
    solution: "[키포인트] 코사인법칙의 변형식 적용\\n조건 정리: $a \\cos B = b \\cos A$\\n풀이 방향: 코사인법칙을 이용하여 $\\cos A$, $\\cos B$를 변의 길이에 대한 식으로 나타내어 등식에 대입한다.\\n정석 풀이: 코사인법칙에 의해 $\\cos A = \\dfrac{b^2+c^2-a^2}{2bc}$, $\\cos B = \\dfrac{c^2+a^2-b^2}{2ca}$이다.\\n주어진 등식에 대입하면 $a \\cdot \\dfrac{c^2+a^2-b^2}{2ca} = b \\cdot \\dfrac{b^2+c^2-a^2}{2bc}$이다.\\n양변을 정리하면 $\\dfrac{c^2+a^2-b^2}{2c} = \\dfrac{b^2+c^2-a^2}{2c}$이다.\\n양변에 $2c$를 곱하면 $c^2+a^2-b^2 = b^2+c^2-a^2$이 되고, 이를 정리하면 $2a^2 = 2b^2$이다.\\n삼각형의 변의 길이는 양수이므로 $a>0, b>0$에서 $a=b$이다.\\n따라서 구하는 값은 $a=b$인 이등변삼각형이다."
  },
  {
    id: 5,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "삼각형 $\\text{ABC}$에서 $b=4$, $c=6$이고 $\\sin A = \\frac{\\sqrt{3}}{2}$일 때, $a$의 값을 구하시오. (단, $2 < a < 6$)",
    choices: [],
    answer: "2\\sqrt{7}",
    solution: "[키포인트] 삼각함수의 성질과 코사인법칙\\n조건 정리: $b=4$, $c=6$, $\\sin A = \\dfrac{\\sqrt{3}}{2}$, $2 < a < 6$\\n풀이 방향: $\\sin A$를 통해 $\\cos A$의 가능한 값을 모두 찾고, 코사인법칙을 적용하여 범위에 맞는 $a$를 선택한다.\\n정석 풀이: $\\sin^2 A + \\cos^2 A = 1$이므로 $\\cos^2 A = 1 - \\dfrac{3}{4} = \\dfrac{1}{4}$이다.\\n따라서 $\\cos A = \\dfrac{1}{2}$ 또는 $\\cos A = -\\dfrac{1}{2}$이다.\\n코사인법칙 $a^2 = b^2 + c^2 - 2bc \\cos A$를 적용한다.\\n(i) $\\cos A = \\dfrac{1}{2}$일 때: $a^2 = 16 + 36 - 2 \\cdot 4 \\cdot 6 \\cdot \\dfrac{1}{2} = 52 - 24 = 28$이므로 $a = 2\\sqrt{7}$이다.\\n이때 $4 < 28 < 36$이므로 $2 < 2\\sqrt{7} < 6$ 조건을 만족한다.\\n(ii) $\\cos A = -\\dfrac{1}{2}$일 때: $a^2 = 16 + 36 - 2 \\cdot 4 \\cdot 6 \\cdot \\left(-\\dfrac{1}{2}\\right) = 52 + 24 = 76$이므로 $a = 2\\sqrt{19}$이다.\\n이는 $a < 6$ 조건을 만족하지 않는다.\\n따라서 구하는 값은 $2\\sqrt{7}$이다."
  },
  {
    id: 6,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "반지름의 길이가 $\\frac{7\\sqrt{3}}{3}$인 원에 내접하는 삼각형 $\\text{ABC}$에서 $c=7$이고 $a : b = 3 : 8$일 때, $a$의 값을 구하시오. (단, $C < 90^\\circ$)",
    choices: [],
    answer: "3",
    solution: "[키포인트] 사인법칙과 코사인법칙의 복합 활용\\n조건 정리: $R = \\dfrac{7\\sqrt{3}}{3}$, $c=7$, $a:b=3:8$, $C < 90^\\circ$\\n풀이 방향: 사인법칙으로 $\\angle C$를 구한 뒤, 비례상수를 두고 코사인법칙을 사용하여 변의 길이를 구한다.\\n정석 풀이: 사인법칙에 의해 $\\dfrac{c}{\\sin C} = 2R$이므로 $\\dfrac{7}{\\sin C} = \\dfrac{14\\sqrt{3}}{3}$이다.\\n$\\sin C = \\dfrac{21}{14\\sqrt{3}} = \\dfrac{\\sqrt{3}}{2}$이고 $C < 90^\\circ$이므로 $C = 60^\\circ$이다.\\n$a:b = 3:8$이므로 $a = 3k, b = 8k (k>0)$로 놓을 수 있다.\\n코사인법칙에 의해 $c^2 = a^2 + b^2 - 2ab \\cos C$이므로 $49 = 9k^2 + 64k^2 - 2 \\cdot 3k \\cdot 8k \\cdot \\dfrac{1}{2}$이다.\\n$49 = 73k^2 - 24k^2 = 49k^2$에서 $k^2 = 1$이므로 $k=1$이다.\\n따라서 $a = 3k = 3$이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 7,
    level: "상",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\angle C=90^\\circ$인 직각삼각형 $\\text{ABC}$에서 $\\overline{\\text{AC}}=5$, $\\overline{\\text{BC}}=12$이고 선분 $\\text{BC}$를 $2 : 1$로 내분하는 점을 $\\text{P}$라고 하자. $\\angle \\text{BAP}=\\theta$라고 할 때, $\\sin \\theta$의 값을 구하시오.",
    choices: [],
    answer: "\\frac{40\\sqrt{41}}{533}",
    solution: "[키포인트] 삼각형의 넓이 공식을 이용한 삼각비 계산\\n조건 정리: $\\angle C=90^\\circ$, $AC=5$, $BC=12$, $BP:PC=2:1$, $\\angle BAP=\\theta$\\n풀이 방향: 선분들의 길이를 피타고라스 정리로 구한 뒤, 삼각형의 넓이를 두 가지 방법으로 나타내어 $\\sin \\theta$를 찾는다.\\n정석 풀이: 직각삼각형 $ABC$에서 피타고라스 정리에 의해 $AB = \\sqrt{5^2 + 12^2} = 13$이다.\\n점 $P$는 $BC$를 $2:1$로 내분하므로 $BP = 12 \\times \\dfrac{2}{3} = 8$, $PC = 12 \\times \\dfrac{1}{3} = 4$이다.\\n직각삼각형 $APC$에서 피타고라스 정리에 의해 $AP = \\sqrt{AC^2 + PC^2} = \\sqrt{5^2 + 4^2} = \\sqrt{41}$이다.\\n이제 $\\triangle ABP$의 넓이를 구하는 두 가지 방법을 생각한다.\\n첫째, 밑변을 $BP$, 높이를 $AC$로 보면 넓이는 $\\dfrac{1}{2} \\cdot BP \\cdot AC = \\dfrac{1}{2} \\cdot 8 \\cdot 5 = 20$이다.\\n둘째, 두 변 $AB, AP$와 끼인각 $\\theta$를 이용하면 넓이는 $\\dfrac{1}{2} \\cdot AB \\cdot AP \\cdot \\sin \\theta = \\dfrac{1}{2} \\cdot 13 \\cdot \\sqrt{41} \\cdot \\sin \\theta$이다.\\n두 넓이는 같아야 하므로 $\\dfrac{13\\sqrt{41}}{2} \\sin \\theta = 20$이다.\\n정리하면 $\\sin \\theta = \\dfrac{40}{13\\sqrt{41}} = \\dfrac{40\\sqrt{41}}{533}$이다.\\n따라서 구하는 값은 $\\dfrac{40\\sqrt{41}}{533}$이다."
  },
  {
    id: 8,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "삼각형 $\\text{ABC}$에서 $b=4$, $c=5$, $\\cos A = \\frac{1}{5}$일 때, 외접원의 반지름의 길이를 구하시오.",
    choices: [],
    answer: "\\frac{5\\sqrt{22}}{8}",
    solution: "[키포인트] 코사인법칙과 사인법칙의 연계\\n조건 정리: $b=4$, $c=5$, $\\cos A = \\dfrac{1}{5}$\\n풀이 방향: 코사인법칙으로 $a$를 구하고, $\\sin A$를 찾은 뒤 사인법칙으로 외접원 반지름 $R$을 구한다.\\n정석 풀이: 코사인법칙에 의해 $a^2 = b^2 + c^2 - 2bc \\cos A$이다.\\n대입하면 $a^2 = 16 + 25 - 2 \\cdot 4 \\cdot 5 \\cdot \\dfrac{1}{5} = 41 - 8 = 33$이므로 $a = \\sqrt{33}$이다.\\n$\\sin^2 A + \\cos^2 A = 1$이고 삼각형의 내각에 대하여 $\\sin A > 0$이므로 $\\sin^2 A = 1 - \\dfrac{1}{25} = \\dfrac{24}{25}$에서 $\\sin A = \\dfrac{2\\sqrt{6}}{5}$이다.\\n사인법칙에 의해 $2R = \\dfrac{a}{\\sin A} = \\dfrac{\\sqrt{33}}{\\dfrac{2\\sqrt{6}}{5}} = \\dfrac{5\\sqrt{33}}{2\\sqrt{6}} = \\dfrac{5\\sqrt{11}}{2\\sqrt{2}} = \\dfrac{5\\sqrt{22}}{4}$이다.\\n따라서 $R = \\dfrac{5\\sqrt{22}}{8}$이다.\\n따라서 구하는 값은 $\\dfrac{5\\sqrt{22}}{8}$이다."
  },
  {
    id: 9,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "삼각형 $\\text{ABC}$에서 $a=7$, $c=8$, $\\sin(A+C) = \\frac{1}{3}$일 때, 삼각형 $\\text{ABC}$의 넓이를 구하시오.",
    choices: [],
    answer: "\\frac{28}{3}",
    solution: "[키포인트] 삼각형의 내각의 합과 넓이 공식\\n조건 정리: $a=7$, $c=8$, $\\sin(A+C) = \\dfrac{1}{3}$\\n풀이 방향: $A+B+C=\\pi$임을 이용하여 $\\sin(A+C)$를 $\\sin B$로 변환하고 넓이 공식에 대입한다.\\n정석 풀이: 삼각형의 세 내각의 크기의 합은 $\\pi$이므로 $A+B+C = \\pi$에서 $A+C = \\pi - B$이다.\\n따라서 $\\sin(A+C) = \\sin(\\pi - B) = \\sin B = \\dfrac{1}{3}$이다.\\n두 변 $a, c$와 끼인각 $B$를 이용한 삼각형 $ABC$의 넓이는 $\\dfrac{1}{2}ac \\sin B$이다.\\n대입하면 넓이는 $\\dfrac{1}{2} \\cdot 7 \\cdot 8 \\cdot \\dfrac{1}{3} = \\dfrac{28}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{28}{3}$이다."
  },
  {
    id: 10,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "넓이가 $20$인 삼각형 $\\text{ABC}$에서 $b=10$, $\\cos A = \\frac{3}{5}$일 때, $c$의 값을 구하시오.",
    choices: [],
    answer: "5",
    solution: "[키포인트] 삼각형의 넓이 공식의 역산\\n조건 정리: 넓이 $20$, $b=10$, $\\cos A = \\dfrac{3}{5}$\\n풀이 방향: $\\cos A$를 이용하여 $\\sin A$를 구하고, 삼각형의 넓이 공식을 역산하여 변 $c$의 길이를 찾는다.\\n정석 풀이: 삼각형의 내각에 대하여 $\\sin A > 0$이므로 $\\sin^2 A = 1 - \\cos^2 A = 1 - \\dfrac{9}{25} = \\dfrac{16}{25}$에서 $\\sin A = \\dfrac{4}{5}$이다.\\n삼각형의 넓이 공식에 의해 $\\dfrac{1}{2}bc \\sin A = 20$이다.\\n여기에 주어진 값들을 대입하면 $\\dfrac{1}{2} \\cdot 10 \\cdot c \\cdot \\dfrac{4}{5} = 20$이다.\\n식을 정리하면 $4c = 20$이므로 $c = 5$이다.\\n따라서 구하는 값은 $5$이다."
  },
  {
    id: 11,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "삼각형 $\\text{ABC}$에서 $a=5$, $b=6$, $\\cos C = \\frac{1}{5}$일 때, 내접원의 반지름의 길이를 구하시오.",
    choices: [],
    answer: "\\frac{2\\sqrt{6}}{3}",
    solution: "[키포인트] 코사인법칙과 삼각형의 내접원 반지름 공식\\n조건 정리: $a=5$, $b=6$, $\\cos C = \\dfrac{1}{5}$\\n풀이 방향: 코사인법칙으로 변 $c$를 구하고, 넓이 공식을 두 가지 방식으로 활용하여 내접원 반지름을 구한다.\\n정석 풀이: 코사인법칙에 의해 $c^2 = a^2 + b^2 - 2ab \\cos C$이므로 $c^2 = 25 + 36 - 2 \\cdot 5 \\cdot 6 \\cdot \\dfrac{1}{5} = 61 - 12 = 49$이다.\\n변의 길이는 양수이므로 $c = 7$이다.\\n$\\sin C > 0$이므로 $\\sin^2 C = 1 - \\cos^2 C = 1 - \\dfrac{1}{25} = \\dfrac{24}{25}$에서 $\\sin C = \\dfrac{2\\sqrt{6}}{5}$이다.\\n삼각형의 넓이 $S = \\dfrac{1}{2}ab \\sin C = \\dfrac{1}{2} \\cdot 5 \\cdot 6 \\cdot \\dfrac{2\\sqrt{6}}{5} = 6\\sqrt{6}$이다.\\n한편, 내접원의 반지름을 $r$이라 하면 넓이 $S = \\dfrac{1}{2}r(a+b+c)$이므로 $6\\sqrt{6} = \\dfrac{1}{2}r(5+6+7) = 9r$이다.\\n따라서 $r = \\dfrac{6\\sqrt{6}}{9} = \\dfrac{2\\sqrt{6}}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{2\\sqrt{6}}{3}$이다."
  },
  {
    id: 12,
    level: "상",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "한 변의 길이가 $6$인 정육각형 $\\text{ABCDEF}$에서 선분 $\\text{CD}$의 중점을 $\\text{P}$라 하고 $\\angle \\text{EPD}=\\theta$라고 할 때, $\\cos \\theta$의 값을 구하시오.",
    choices: [],
    answer: "\\frac{2\\sqrt{7}}{7}",
    solution: "[키포인트] 정다각형의 성질과 코사인법칙\\n조건 정리: 한 변의 길이가 $6$인 정육각형, $P$는 $CD$의 중점, $\\angle EPD = \\theta$\\n풀이 방향: 삼각형 $EPD$에서 각 변의 길이를 구하고 세 변의 길이에 대해 코사인법칙을 적용하여 $\\cos \\theta$를 찾는다.\\n정석 풀이: 정육각형의 한 내각의 크기는 $\\dfrac{180^\\circ \\times (6-2)}{6} = 120^\\circ$이므로 $\\angle CDE = 120^\\circ$이다.\\n점 $P$가 선분 $CD$의 중점이므로 $DP = 3$이고, 정육각형의 한 변이므로 $DE = 6$이다.\\n삼각형 $EPD$에서 코사인법칙에 의해 $EP^2 = DE^2 + DP^2 - 2 \\cdot DE \\cdot DP \\cdot \\cos 120^\\circ$이다.\\n$\\cos 120^\\circ = -\\dfrac{1}{2}$이므로 $EP^2 = 36 + 9 - 2 \\cdot 6 \\cdot 3 \\cdot \\left(-\\dfrac{1}{2}\\right) = 45 + 18 = 63$이 되어 $EP = 3\\sqrt{7}$이다.\\n이제 삼각형 $EPD$에서 기준각을 $\\theta$($\\angle EPD$)로 하여 코사인법칙을 다시 적용하면, $DE^2 = EP^2 + DP^2 - 2 \\cdot EP \\cdot DP \\cdot \\cos \\theta$이다.\\n$36 = 63 + 9 - 2 \\cdot 3\\sqrt{7} \\cdot 3 \\cdot \\cos \\theta$이므로 정리하면 $18\\sqrt{7} \\cos \\theta = 36$이다.\\n따라서 $\\cos \\theta = \\dfrac{36}{18\\sqrt{7}} = \\dfrac{2}{\\sqrt{7}} = \\dfrac{2\\sqrt{7}}{7}$이다.\\n따라서 구하는 값은 $\\dfrac{2\\sqrt{7}}{7}$이다."
  },
  {
    id: 13,
    level: "상",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\overline{\\text{AB}}=4$, $\\overline{\\text{AC}}=8$인 삼각형 $\\text{ABC}$에서 $\\angle \\text{A}$의 이등분선이 변 $\\text{BC}$와 만나는 점을 $\\text{D}$라 하고, $\\overline{\\text{BC}}=a$라고 하자. $a(\\sin B + \\sin C) = 6\\sqrt{2}$일 때, 삼각형 $\\text{ABD}$의 넓이를 구하시오. (단, $\\angle A < 90^\\circ$)",
    choices: [],
    answer: "\\frac{8\\sqrt{2}}{3}",
    solution: "[키포인트] 각의 이등분선의 성질과 사인법칙, 넓이의 비\\n조건 정리: $AB=4$, $AC=8$, $BC=a$, $a(\\sin B + \\sin C) = 6\\sqrt{2}$, $\\angle A < 90^\\circ$\\n풀이 방향: 사인법칙으로 변의 길이를 매개변수로 변환해 $\\angle A$를 구하고, 넓이를 계산한 뒤 각의 이등분선 성질로 비율을 나눈다.\\n정석 풀이: 외접원의 반지름을 $R$이라 하면, 사인법칙에 의해 $\\sin B = \\dfrac{b}{2R} = \\dfrac{8}{2R}$, $\\sin C = \\dfrac{c}{2R} = \\dfrac{4}{2R}$이다.\\n조건식에 대입하면 $a \\left(\\dfrac{8}{2R} + \\dfrac{4}{2R}\\right) = 6\\sqrt{2}$이므로 $\\dfrac{12a}{2R} = 6\\sqrt{2}$에서 $\\dfrac{a}{2R} = \\dfrac{\\sqrt{2}}{2}$이다.\\n사인법칙에 의해 $\\sin A = \\dfrac{a}{2R}$이므로 $\\sin A = \\dfrac{\\sqrt{2}}{2}$이다.\\n$\\angle A < 90^\\circ$이므로 $A = 45^\\circ$이다.\\n삼각형 $ABC$의 넓이는 $\\dfrac{1}{2}bc \\sin A = \\dfrac{1}{2} \\cdot 8 \\cdot 4 \\cdot \\sin 45^\\circ = 16 \\cdot \\dfrac{\\sqrt{2}}{2} = 8\\sqrt{2}$이다.\\n선분 $AD$는 $\\angle A$의 이등분선이므로 각의 이등분선 정리에 의해 $BD : DC = AB : AC = 4 : 8 = 1 : 2$이다.\\n삼각형 $ABD$와 삼각형 $ADC$는 높이가 같으므로 넓이의 비는 밑변의 비와 같다.\\n따라서 삼각형 $ABD$의 넓이는 전체 넓이의 $\\dfrac{1}{3}$이므로 $\\dfrac{1}{3} \\cdot 8\\sqrt{2} = \\dfrac{8\\sqrt{2}}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{8\\sqrt{2}}{3}$이다."
  },
  {
    id: 14,
    level: "상",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "원에 내접하는 사각형 $\\text{ABCD}$에서 $\\overline{\\text{AB}}=\\overline{\\text{BC}}=4$, $\\overline{\\text{CD}}+\\overline{\\text{DA}}=10$, $\\angle \\text{ADC}=120^\\circ$일 때, 사각형 $\\text{ABCD}$의 넓이를 구하시오.",
    choices: [],
    answer: "25\\sqrt{3}",
    solution: "[키포인트] 원에 내접하는 사각형의 성질과 코사인법칙\\n조건 정리: 원에 내접하는 사각형 $ABCD$, $AB=BC=4$, $CD+DA=10$, $\\angle ADC=120^\\circ$\\n풀이 방향: 원에 내접하는 사각형의 마주보는 대각의 합이 $180^\\circ$임을 이용하여 대각선 $AC$의 길이를 두 가지 방법으로 구하고, 이를 통해 변의 길이의 곱을 찾아 넓이를 구한다.\\n정석 풀이: 원에 내접하는 사각형에서 마주보는 각의 크기의 합은 $180^\\circ$이므로 $\\angle ABC = 180^\\circ - 120^\\circ = 60^\\circ$이다.\\n삼각형 $ABC$에서 코사인법칙에 의해 $AC^2 = AB^2 + BC^2 - 2 \\cdot AB \\cdot BC \\cdot \\cos 60^\\circ = 16 + 16 - 2 \\cdot 4 \\cdot 4 \\cdot \\dfrac{1}{2} = 16$이므로 $AC = 4$이다.\\n삼각형 $ADC$에서 코사인법칙에 의해 $AC^2 = CD^2 + DA^2 - 2 \\cdot CD \\cdot DA \\cdot \\cos 120^\\circ$이므로 $16 = CD^2 + DA^2 + CD \\cdot DA$이다.\\n이 식을 변형하면 $(CD+DA)^2 = CD^2 + DA^2 + 2 \\cdot CD \\cdot DA$이므로, $10^2 = 100 = (CD^2 + DA^2 + CD \\cdot DA) + CD \\cdot DA = 16 + CD \\cdot DA$이다.\\n따라서 $CD \\cdot DA = 84$이다.\\n사각형 $ABCD$의 넓이는 삼각형 $ABC$와 삼각형 $ADC$의 넓이의 합과 같다.\\n$\\triangle ABC = \\dfrac{1}{2} \\cdot 4 \\cdot 4 \\cdot \\sin 60^\\circ = 4\\sqrt{3}$\\n$\\triangle ADC = \\dfrac{1}{2} \\cdot CD \\cdot DA \\cdot \\sin 120^\\circ = \\dfrac{1}{2} \\cdot 84 \\cdot \\dfrac{\\sqrt{3}}{2} = 21\\sqrt{3}$\\n따라서 사각형 $ABCD$의 넓이는 $4\\sqrt{3} + 21\\sqrt{3} = 25\\sqrt{3}$이다.\\n따라서 구하는 값은 $25\\sqrt{3}$이다."
  }
];