window.examTitle = "비상대수삼각함수활용익힘책_고2_유형변형";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 중 각을 나타내는 동경이 나머지 넷과 다른 하나는?",
    choices: [
      "$-420^\\circ$",
      "$300^\\circ$",
      "$\\frac{5}{3}\\pi$",
      "$660^\\circ$",
      "$-\\frac{11}{3}\\pi$"
    ],
    answer: "⑤",
    solution: "[키포인트] 동경의 일반각 표기를 이용하여 각 동경의 위치를 비교한다.\\n조건 정리: 각 동경을 $360^\\circ \\times n + \\alpha$ ($0^\\circ \\le \\alpha < 360^\\circ$) 꼴로 나타낸다.\\n정석 풀이:\\n① $-420^\\circ = 360^\\circ \\times (-2) + 300^\\circ$이므로 동경은 $300^\\circ$와 같다.\\n② $300^\\circ$의 동경은 $300^\\circ$이다.\\n③ $\\dfrac{5}{3}\\pi = 300^\\circ$이므로 동경은 $300^\\circ$와 같다.\\n④ $660^\\circ = 360^\\circ \\times 1 + 300^\\circ$이므로 동경은 $300^\\circ$와 같다.\\n⑤ $-\\dfrac{11}{3}\\pi = -660^\\circ = 360^\\circ \\times (-2) + 60^\\circ$이므로 동경은 $60^\\circ$와 같다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 2,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "중심각의 크기가 $1.5$이고 넓이가 $12$인 부채꼴의 둘레의 길이를 구하시오.",
    choices: [],
    answer: "14",
    solution: "[키포인트] 부채꼴의 넓이 공식 $S = \\dfrac{1}{2}r^2\\theta$와 호의 길이 공식 $l = r\\theta$를 이용한다.\\n조건 정리: 중심각 $\\theta = 1.5$, 넓이 $S = 12$이다.\\n정석 풀이: $S = \\dfrac{1}{2}r^2\\theta$에서 $12 = \\dfrac{1}{2} \\times r^2 \\times 1.5$이다.\\n$0.75 r^2 = 12$이므로 $r^2 = 16$이고, $r > 0$이므로 $r = 4$이다.\\n부채꼴의 호의 길이는 $l = r\\theta = 4 \\times 1.5 = 6$이다.\\n따라서 부채꼴의 둘레의 길이는 $2r + l = 2 \\times 4 + 6 = 14$이다.\\n따라서 구하는 값은 $14$이다."
  },
  {
    id: 3,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "각 $\\theta$가 제4사분면의 각이고 $\\frac{\\sin \\theta}{1+\\cos \\theta} + \\frac{1+\\cos \\theta}{\\sin \\theta} = -4$일 때, $\\sin \\theta$의 값을 구하시오.",
    choices: [],
    answer: "$-\\frac{1}{2}$",
    solution: "[키포인트] 삼각함수 사이의 관계 $\\sin^2\\theta + \\cos^2\\theta = 1$을 이용하여 주어진 식을 간단히 한다.\\n조건 정리: 제4사분면의 각이므로 $\\sin\\theta < 0$, $\\cos\\theta > 0$이다.\\n정석 풀이: 주어진 식의 좌변을 통분하여 정리하면 다음과 같다.\\n$\\dfrac{\\sin^2\\theta + (1+\\cos\\theta)^2}{\\sin\\theta(1+\\cos\\theta)} = \\dfrac{\\sin^2\\theta + 1 + 2\\cos\\theta + \\cos^2\\theta}{\\sin\\theta(1+\\cos\\theta)}$\\n$= \\dfrac{2 + 2\\cos\\theta}{\\sin\\theta(1+\\cos\\theta)} = \\dfrac{2(1+\\cos\\theta)}{\\sin\\theta(1+\\cos\\theta)} = \\dfrac{2}{\\sin\\theta}$\\n조건에서 이 값이 $-4$이므로 $\\dfrac{2}{\\sin\\theta} = -4$이다.\\n정리하면 $\\sin\\theta = -\\dfrac{1}{2}$이다.\\n따라서 구하는 값은 $-\\dfrac{1}{2}$이다."
  },
  {
    id: 4,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 식의 값을 구하시오.\n\n$\\cos\\left(-\\frac{7}{3}\\pi\\right) + \\sin\\frac{11}{6}\\pi + \\tan\\frac{9}{4}\\pi$",
    choices: [],
    answer: "1",
    solution: "[키포인트] 삼각함수의 각의 변환 성질을 이용하여 특수각의 삼각함수 값을 구한다.\\n풀이 방향: 주기성을 이용하여 각을 예각으로 변환한다.\\n정석 풀이: 각 항을 정리하면 다음과 같다.\\n$\\cos\\left(-\\dfrac{7}{3}\\pi\\right) = \\cos\\left(-2\\pi - \\dfrac{\\pi}{3}\\right) = \\cos\\left(-\\dfrac{\\pi}{3}\\right) = \\cos\\dfrac{\\pi}{3} = \\dfrac{1}{2}$\\n$\\sin\\dfrac{11}{6}\\pi = \\sin\\left(2\\pi - \\dfrac{\\pi}{6}\\right) = \\sin\\left(-\\dfrac{\\pi}{6}\\right) = -\\sin\\dfrac{\\pi}{6} = -\\dfrac{1}{2}$\\n$\\tan\\dfrac{9}{4}\\pi = \\tan\\left(2\\pi + \\dfrac{\\pi}{4}\\right) = \\tan\\dfrac{\\pi}{4} = 1$\\n주어진 식에 대입하면 $\\dfrac{1}{2} + \\left(-\\dfrac{1}{2}\\right) + 1 = 1$이다.\\n따라서 구하는 값은 $1$이다."
  },
  {
    id: 5,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "다음 함수 중 주기가 $2\\pi$인 것은?",
    choices: [
      "$f(x) = \\sin 2x$",
      "$f(x) = |\\cos x|$",
      "$f(x) = \\tan x$",
      "$f(x) = \\cos \\frac{x}{2}$",
      "$f(x) = |\\sin \\frac{x}{2}|$"
    ],
    answer: "⑤",
    solution: "[키포인트] 절댓값 기호가 포함된 삼각함수의 주기를 구한다.\\n정석 풀이:\\n① $f(x) = \\sin 2x$의 주기는 $\\dfrac{2\\pi}{2} = \\pi$이다.\\n② $f(x) = |\\cos x|$의 주기는 $\\pi$이다.\\n③ $f(x) = \\tan x$의 주기는 $\\pi$이다.\\n④ $f(x) = \\cos\\dfrac{x}{2}$의 주기는 $\\dfrac{2\\pi}{1/2} = 4\\pi$이다.\\n⑤ $f(x) = \\left|\\sin\\dfrac{x}{2}\\right|$는 $\\sin\\dfrac{x}{2}$의 그래프를 $x$축 위로 접어 올린 것이므로, 기존 주기 $4\\pi$의 절반인 $2\\pi$가 된다.\\n따라서 주기가 $2\\pi$인 것은 ⑤이다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 6,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "객관식",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "다음 보기 중 옳은 것만을 있는 대로 고른 것은?\n\n<보기>\nㄱ. $\\cos 1^\\circ + \\cos 2^\\circ + \\cdots + \\cos 180^\\circ = -1$\nㄴ. $\\sin^2 10^\\circ + \\sin^2 20^\\circ + \\cdots + \\sin^2 80^\\circ + \\sin^2 90^\\circ = 5$\nㄷ. $\\tan 1^\\circ \\times \\tan 2^\\circ \\times \\cdots \\times \\tan 89^\\circ = 1$",
    choices: [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    answer: "⑤",
    solution: "[키포인트] 삼각함수의 대칭성과 여각/보각 공식을 이용하여 식의 값을 계산한다.\\n정석 풀이:\\nㄱ. $\\cos(180^\\circ - x) = -\\cos x$이므로 $\\cos 1^\\circ + \\cos 179^\\circ = 0$이다. 이와 같이 짝지으면 $\\cos 90^\\circ = 0$, $\\cos 180^\\circ = -1$만 남으므로 합은 $-1$이다. (참)\\nㄴ. $\\sin(90^\\circ - x) = \\cos x$이므로 $\\sin^2 80^\\circ = \\cos^2 10^\\circ$이다. 따라서 $\\sin^2 10^\\circ + \\sin^2 80^\\circ = 1$이다. 10부터 80까지 4쌍이 존재하여 4가 되고, $\\sin^2 90^\\circ = 1$이므로 총합은 $5$이다. (참)\\nㄷ. $\\tan(90^\\circ - x) = \\dfrac{1}{\\tan x}$이므로 $\\tan 1^\\circ \\times \\tan 89^\\circ = 1$이다. 44쌍의 곱이 1이고 $\\tan 45^\\circ = 1$이므로 전체 곱은 $1$이다. (참)\\n따라서 옳은 것은 ㄱ, ㄴ, ㄷ이다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 7,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "$0 \\le x < 2\\pi$일 때, 방정식 $\\sin\\left(\\frac{\\pi}{2}+x\\right) - \\cos 2x = 0$의 서로 다른 실근의 개수를 구하시오.",
    choices: [],
    answer: "3",
    solution: "[키포인트] 각의 변환 공식과 배각 공식을 이용하여 삼각방정식을 푼다.\\n조건 정리: $\\sin\\left(\\dfrac{\\pi}{2}+x\\right) = \\cos x$이다.\\n정석 풀이: 주어진 방정식은 $\\cos x - \\cos 2x = 0$이 된다.\\n$\\cos 2x = 2\\cos^2 x - 1$을 대입하면 $\\cos x - (2\\cos^2 x - 1) = 0$이다.\\n정리하면 $2\\cos^2 x - \\cos x - 1 = 0$이고, 인수분해하면 $(2\\cos x + 1)(\\cos x - 1) = 0$이다.\\n따라서 $\\cos x = 1$ 또는 $\\cos x = -\\dfrac{1}{2}$이다.\\n$0 \\le x < 2\\pi$에서 $\\cos x = 1$을 만족하는 $x = 0$이다.\\n$\\cos x = -\\dfrac{1}{2}$을 만족하는 $x = \\dfrac{2}{3}\\pi, \\dfrac{4}{3}\\pi$이다.\\n따라서 실근은 $x = 0, \\dfrac{2}{3}\\pi, \\dfrac{4}{3}\\pi$로 서로 다른 실근의 개수는 $3$개이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 8,
    level: "상",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "$0 \\le x < 2\\pi$에서 부등식 $|\\sin x| > \\frac{\\sqrt{3}}{2}$의 해가 $\\alpha < x < \\beta$ 또는 $\\gamma < x < \\delta$일 때, $\\alpha+\\beta+\\gamma+\\delta$의 값을 구하시오.",
    choices: [],
    answer: "$4\\pi$",
    solution: "[키포인트] 절댓값을 포함한 삼각부등식을 풀고 단위원을 이용하여 해의 범위를 구한다.\\n조건 정리: 부등식 $|\\sin x| > \\dfrac{\\sqrt{3}}{2}$은 $\\sin x > \\dfrac{\\sqrt{3}}{2}$ 또는 $\\sin x < -\\dfrac{\\sqrt{3}}{2}$이다.\\n풀이 방향: $0 \\le x < 2\\pi$ 범위에서 각각의 삼각부등식을 풀어 해의 구간을 찾는다.\\n정석 풀이: $y = \\sin x$의 그래프 또는 단위원을 이용하여 해를 구한다.\\n첫째, $\\sin x > \\dfrac{\\sqrt{3}}{2}$를 만족하는 $x$의 범위는 $\\dfrac{\\pi}{3} < x < \\dfrac{2}{3}\\pi$이다.\\n둘째, $\\sin x < -\\dfrac{\\sqrt{3}}{2}$를 만족하는 $x$의 범위는 $\\dfrac{4}{3}\\pi < x < \\dfrac{5}{3}\\pi$이다.\\n주어진 조건에 의해 해집합이 두 개의 구간으로 나뉘므로, $\\alpha < \\beta < \\gamma < \\delta$라 하면 $\\alpha = \\dfrac{\\pi}{3}$, $\\beta = \\dfrac{2}{3}\\pi$, $\\gamma = \\dfrac{4}{3}\\pi$, $\\delta = \\dfrac{5}{3}\\pi$가 된다.\\n핵심 확인: $\\alpha+\\beta+\\gamma+\\delta = \\dfrac{\\pi}{3} + \\dfrac{2}{3}\\pi + \\dfrac{4}{3}\\pi + \\dfrac{5}{3}\\pi = \\dfrac{12}{3}\\pi = 4\\pi$이다.\\n따라서 구하는 값은 $4\\pi$이다."
  },
  {
    id: 9,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["도형"],
    wide: false,
    content: "삼각형 $ABC$에서 $\\overline{AB}=12$, $\\angle A=45^\\circ$, $\\angle B=75^\\circ$일 때, 삼각형 $ABC$의 외접원의 반지름의 길이를 구하시오.",
    choices: [],
    answer: "$4\\sqrt{3}$",
    solution: "[키포인트] 삼각형의 내각의 합과 사인법칙을 이용하여 외접원의 반지름을 구한다.\\n풀이 방향: $\\angle C$의 크기를 먼저 구한 후, 사인법칙 $\\dfrac{c}{\\sin C} = 2R$을 적용한다.\\n정석 풀이: 삼각형의 세 내각의 크기의 합은 $180^\\circ$이므로 $\\angle C = 180^\\circ - (45^\\circ + 75^\\circ) = 60^\\circ$이다.\\n사인법칙에 의하여 $\\dfrac{\\overline{AB}}{\\sin C} = 2R$ (단, $R$은 외접원의 반지름)이 성립한다.\\n$\\dfrac{12}{\\sin 60^\\circ} = 2R$에서 $\\dfrac{12}{\\dfrac{\\sqrt{3}}{2}} = 2R$이므로 $2R = \\dfrac{24}{\\sqrt{3}} = 8\\sqrt{3}$이다.\\n따라서 $R = 4\\sqrt{3}$이다.\\n따라서 구하는 값은 $4\\sqrt{3}$이다."
  },
  {
    id: 10,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "삼각형 $ABC$에서 $\\sin A : \\sin B : \\sin C = 3:5:7$이고 외접원의 반지름의 길이가 $7$일 때, 가장 긴 변의 길이를 구하시오.",
    choices: [],
    answer: "$7\\sqrt{3}$",
    solution: "[키포인트] 사인법칙에 의한 세 변의 길이의 비와 코사인법칙을 이용하여 변의 길이를 구한다.\\n풀이 방향: 사인법칙에 의해 변의 길이의 비를 구하고, 코사인법칙으로 가장 큰 각의 크기를 찾은 후 다시 사인법칙을 쓴다.\\n정석 풀이: 사인법칙에 의해 $a:b:c = \\sin A : \\sin B : \\sin C = 3:5:7$이다.\\n세 변의 길이를 $a=3k, b=5k, c=7k$ ($k>0$)로 놓으면, 가장 긴 변은 $c$이므로 가장 큰 각은 $C$이다.\\n코사인법칙에 의해 $\\cos C = \\dfrac{(3k)^2 + (5k)^2 - (7k)^2}{2 \\times 3k \\times 5k} = \\dfrac{9k^2 + 25k^2 - 49k^2}{30k^2} = -\\dfrac{1}{2}$이다.\\n따라서 $\\angle C = 120^\\circ$이다.\\n외접원의 반지름이 $7$이므로 사인법칙 $\\dfrac{c}{\\sin C} = 2R$에서 $\\dfrac{c}{\\sin 120^\\circ} = 14$이다.\\n$c = 14 \\times \\dfrac{\\sqrt{3}}{2} = 7\\sqrt{3}$이다.\\n따라서 구하는 값은 $7\\sqrt{3}$이다."
  },
  {
    id: 11,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["도형"],
    wide: false,
    content: "세 변의 길이가 $5, 6, 7$인 삼각형 $ABC$의 넓이를 구하시오.",
    choices: [],
    answer: "$6\\sqrt{6}$",
    solution: "[키포인트] 코사인법칙을 이용하여 한 각의 코사인값을 구하고, 이를 사인값으로 변환하여 넓이를 구한다.\\n풀이 방향: 세 변의 길이가 주어졌으므로 코사인법칙으로 $\\cos C$를 구한다.\\n정석 풀이: $\\triangle ABC$에서 코사인법칙에 의해 $\\cos C = \\dfrac{5^2 + 6^2 - 7^2}{2 \\times 5 \\times 6} = \\dfrac{25 + 36 - 49}{60} = \\dfrac{12}{60} = \\dfrac{1}{5}$이다.\\n$\\sin C > 0$이므로 $\\sin C = \\sqrt{1 - \\cos^2 C} = \\sqrt{1 - \\dfrac{1}{25}} = \\dfrac{2\\sqrt{6}}{5}$이다.\\n따라서 삼각형 $ABC$의 넓이 $S$는 $S = \\dfrac{1}{2}ab\\sin C = \\dfrac{1}{2} \\times 5 \\times 6 \\times \\dfrac{2\\sqrt{6}}{5} = 6\\sqrt{6}$이다.\\n빠른 풀이 포인트: 헤론의 공식을 이용하면 $s = \\dfrac{5+6+7}{2} = 9$이므로 $S = \\sqrt{9(9-5)(9-6)(9-7)} = \\sqrt{9 \\times 4 \\times 3 \\times 2} = 6\\sqrt{6}$이다.\\n따라서 구하는 값은 $6\\sqrt{6}$이다."
  },
  {
    id: 12,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형"],
    wide: false,
    content: "각 $\\theta$가 제3사분면의 각일 때, 각 $\\frac{\\theta}{2}$를 나타내는 동경이 존재할 수 있는 사분면을 모두 구하시오.",
    choices: [],
    answer: "제2사분면, 제4사분면",
    solution: "[키포인트] 동경의 일반각 표기를 이용하여 $\\dfrac{\\theta}{2}$의 존재 범위를 구한다.\\n조건 정리: 각 $\\theta$가 제3사분면의 각이므로 $180^\\circ + 360^\\circ \\times n < \\theta < 270^\\circ + 360^\\circ \\times n$ ($n$은 정수)이다.\\n정석 풀이: 부등식의 각 변을 2로 나누면 $90^\\circ + 180^\\circ \\times n < \\dfrac{\\theta}{2} < 135^\\circ + 180^\\circ \\times n$이다.\\n$n$의 값에 따라 사분면을 확인한다.\\n$n=2k$ (짝수)일 때: $90^\\circ + 360^\\circ \\times k < \\dfrac{\\theta}{2} < 135^\\circ + 360^\\circ \\times k$이므로 제2사분면의 각이다.\\n$n=2k+1$ (홀수)일 때: $270^\\circ + 360^\\circ \\times k < \\dfrac{\\theta}{2} < 315^\\circ + 360^\\circ \\times k$이므로 제4사분면의 각이다.\\n따라서 동경이 존재할 수 있는 사분면은 제2사분면, 제4사분면이다.\\n따라서 구하는 값은 제2사분면, 제4사분면이다."
  },
  {
    id: 13,
    level: "중",
    category: "삼각함수",
    originalCategory: "삼각함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-04",
    standardUnit: "삼각함수",
    standardUnitOrder: 4,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "그래프"],
    wide: false,
    content: "함수 $f(x) = a \\sin bx + c$의 최댓값이 $5$, 최솟값이 $-1$이고 주기가 $4\\pi$일 때, 양수 $a, b$와 상수 $c$에 대하여 $abc$의 값을 구하시오.",
    choices: [],
    answer: "3",
    solution: "[키포인트] 삼각함수의 그래프의 성질을 이용하여 주기, 최댓값, 최솟값을 분석한다.\\n조건 정리: 양수 $a, b$에 대하여 $f(x) = a\\sin bx + c$의 최댓값은 $a+c$, 최솟값은 $-a+c$, 주기는 $\\dfrac{2\\pi}{b}$이다.\\n정석 풀이: 최댓값이 $5$이므로 $a+c = 5$ 이고, 최솟값이 $-1$이므로 $-a+c = -1$ 이다.\\n두 식을 연립하여 더하면 $2c = 4$에서 $c=2$이고, $a=3$이다.\\n주기가 $4\\pi$이므로 $\\dfrac{2\\pi}{b} = 4\\pi$에서 $b = \\dfrac{1}{2}$이다.\\n따라서 $abc = 3 \\times \\dfrac{1}{2} \\times 2 = 3$이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 14,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "도형"],
    wide: false,
    content: "중심각의 크기가 $\\frac{\\pi}{4}$인 부채꼴 $OAB$가 있다. 선분 $OA$를 $3:1$로 내분하는 점을 $P$, 선분 $OB$의 중점을 $Q$라 하자. 삼각형 $OPQ$의 넓이가 $\\frac{3\\sqrt{2}}{2}$일 때, 반지름 $OA$의 길이를 구하시오.",
    choices: [],
    answer: "4",
    solution: "[키포인트] 부채꼴 내부에 생성된 삼각형의 넓이 공식을 이용한다.\\n조건 정리: 반지름의 길이를 $r$이라 하면 $\\overline{OA} = \\overline{OB} = r$이다. $P$는 $OA$의 $3:1$ 내분점이므로 $\\overline{OP} = \\dfrac{3}{4}r$이고, $Q$는 $OB$의 중점이므로 $\\overline{OQ} = \\dfrac{1}{2}r$이다.\\n정석 풀이: 중심각의 크기가 $\\dfrac{\\pi}{4}$이므로 삼각형 $OPQ$의 넓이 $S$는 $S = \\dfrac{1}{2} \\times \\overline{OP} \\times \\overline{OQ} \\times \\sin\\dfrac{\\pi}{4}$이다.\\n대입하면 $S = \\dfrac{1}{2} \\times \\dfrac{3}{4}r \\times \\dfrac{1}{2}r \\times \\dfrac{\\sqrt{2}}{2} = \\dfrac{3\\sqrt{2}}{32}r^2$이다.\\n조건에서 이 넓이가 $\\dfrac{3\\sqrt{2}}{2}$이므로 $\\dfrac{3\\sqrt{2}}{32}r^2 = \\dfrac{3\\sqrt{2}}{2}$이다.\\n양변을 정리하면 $\\dfrac{1}{16}r^2 = 1$이므로 $r^2 = 16$이다.\\n$r>0$이므로 $r=4$이다.\\n따라서 구하는 값은 $4$이다."
  },
  {
    id: 15,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "도형"],
    wide: false,
    content: "지름의 길이가 $10$인 원 위의 점 $P$에 대하여 $\\overline{AP}=8$일 때, $\\angle PAB = \\theta$라 하자. $\\cos 2\\theta$의 값을 구하시오.",
    choices: [],
    answer: "$\\frac{7}{25}$",
    solution: "[키포인트] 지름에 대한 원주각의 성질과 삼각함수의 덧셈정리(배각 공식)를 이용한다.\\n조건 정리: $\\overline{AB}$가 지름이므로 $\\angle APB = 90^\\circ$이다. $\\triangle APB$는 직각삼각형이다.\\n정석 풀이: $\\triangle APB$에서 피타고라스 정리에 의해 $\\overline{BP} = \\sqrt{10^2 - 8^2} = 6$이다.\\n$\\angle PAB = \\theta$이므로 $\\cos\\theta = \\dfrac{\\overline{AP}}{\\overline{AB}} = \\dfrac{8}{10} = \\dfrac{4}{5}$이다.\\n구하고자 하는 값은 $\\cos 2\\theta$이므로 배각 공식에 의해 $\\cos 2\\theta = 2\\cos^2\\theta - 1$이다.\\n대입하면 $\\cos 2\\theta = 2\\left(\\dfrac{4}{5}\\right)^2 - 1 = 2\\left(\\dfrac{16}{25}\\right) - 1 = \\dfrac{32}{25} - \\dfrac{25}{25} = \\dfrac{7}{25}$이다.\\n따라서 구하는 값은 $\\dfrac{7}{25}$이다."
  },
  {
    id: 16,
    level: "중",
    category: "사인법칙과 코사인법칙",
    originalCategory: "사인법칙과 코사인법칙",
    standardCourse: "대수",
    standardUnitKey: "H22-A-05",
    standardUnit: "사인법칙과 코사인법칙",
    standardUnitOrder: 5,
    questionType: "서술형",
    layoutTag: "grid",
    tags: ["서술형", "도형"],
    wide: false,
    content: "삼각형 $ABC$에서 $\\angle A = 120^\\circ$, $b:c = 1:2$이다. 외접원의 반지름의 길이가 $\\sqrt{7}$일 때, 삼각형 $ABC$의 넓이를 구하시오.",
    choices: [],
    answer: "$\\frac{3\\sqrt{3}}{2}$",
    solution: "[키포인트] 코사인법칙으로 세 변의 길이의 비를 절대 길이로 환산하고, 사인법칙으로 상수를 결정한 후 넓이를 구한다.\\n풀이 방향: $b:c=1:2$에서 문자로 길이를 두고 코사인법칙을 써서 $a$를 표현한다.\\n정석 풀이: $b=k$, $c=2k$ ($k>0$)로 놓는다.\\n코사인법칙에 의해 $a^2 = b^2 + c^2 - 2bc\\cos A$이므로 $a^2 = k^2 + 4k^2 - 2(k)(2k)\\cos 120^\\circ = 5k^2 - 4k^2\\left(-\\dfrac{1}{2}\\right) = 7k^2$이다.\\n따라서 $a = \\sqrt{7}k$이다.\\n외접원의 반지름 $R = \\sqrt{7}$이므로 사인법칙에 의해 $\\dfrac{a}{\\sin A} = 2R$에서 $\\dfrac{\\sqrt{7}k}{\\sin 120^\\circ} = 2\\sqrt{7}$이다.\\n$\\dfrac{k}{\\dfrac{\\sqrt{3}}{2}} = 2$이므로 $k = \\sqrt{3}$이다.\\n그러므로 $b = \\sqrt{3}$, $c = 2\\sqrt{3}$이다.\\n삼각형 $ABC$의 넓이는 $\\dfrac{1}{2}bc\\sin A = \\dfrac{1}{2}(\\sqrt{3})(2\\sqrt{3})\\sin 120^\\circ = 3 \\times \\dfrac{\\sqrt{3}}{2} = \\dfrac{3\\sqrt{3}}{2}$이다.\\n따라서 구하는 값은 $\\dfrac{3\\sqrt{3}}{2}$이다."
  }
];