window.examTitle = "비상대수지수로그함수익힘책_고2_유형변형";

window.questionBank = [
  {
    id: 1,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\n$y=2^{x-1}+c$\n의 그래프가 점 $(1,4)$를 지날 때, 이 그래프에 대한 설명으로 옳은 것은?",
    choices: [
      "점근선은 직선 $y=4$이다.",
      "치역은 $y>3$인 실수 전체이다.",
      "$y$절편은 $4$이다.",
      "$x$의 값이 증가하면 $y$의 값은 감소한다.",
      "함수 $y=2^x$의 그래프를 $x$축의 방향으로 $1$만큼, $y$축의 방향으로 $4$만큼 평행이동한 그래프이다."
    ],
    answer: "②",
    solution: "[키포인트] 지수함수의 평행이동에서는 점근선과 치역을 먼저 확인한다.\\n조건 정리: 그래프가 점 $(1,4)$를 지나므로 $x=1$, $y=4$를 대입한다.\\n풀이 방향: 먼저 $c$를 구한 뒤, 그래프의 점근선과 치역을 판단한다.\\n정석 풀이: $4=2^{1-1}+c=1+c$이므로 $c=3$이다. 따라서 함수는 $y=2^{x-1}+3$이다. 지수함수 $2^{x-1}$은 항상 양수이므로 $2^{x-1}>0$이다. 따라서 $y=2^{x-1}+3>3$이므로 치역은 $y>3$인 실수 전체이다. 점근선은 $y=3$이고, $y$절편은 $x=0$을 대입하여 $2^{-1}+3=\\dfrac{7}{2}$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 2,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 세 수의 대소를 비교하시오.\n$\\log_{\\frac13}9,\\quad \\log_3\\dfrac1{27},\\quad \\log_{\\frac13}\\dfrac1{9}$",
    choices: [],
    answer: "$\\log_3\\dfrac1{27}<\\log_{\\frac13}9<\\log_{\\frac13}\\dfrac1{9}$",
    solution: "[키포인트] 로그값을 지수 형태로 바꾸어 각각의 값을 계산한다.\\n조건 정리: 밑이 $\\dfrac{1}{3}$인 로그와 밑이 $3$인 로그가 함께 주어져 있다.\\n풀이 방향: 각 로그값을 직접 계산한 뒤 작은 값부터 배열한다.\\n정석 풀이: $\\log_{\\frac13}9=\\log_{\\frac13}\\left(\\dfrac{1}{3}\\right)^{-2}=-2$이다. 또한 $\\log_3\\dfrac{1}{27}=\\log_3 3^{-3}=-3$이다. 마지막으로 $\\log_{\\frac13}\\dfrac{1}{9}=\\log_{\\frac13}\\left(\\dfrac{1}{3}\\right)^2=2$이다. 따라서 세 값은 $-3$, $-2$, $2$이므로 작은 것부터 쓰면 $\\log_3\\dfrac{1}{27}<\\log_{\\frac13}9<\\log_{\\frac13}\\dfrac{1}{9}$이다.\\n따라서 구하는 값은 $\\log_3\\dfrac{1}{27}<\\log_{\\frac13}9<\\log_{\\frac13}\\dfrac{1}{9}$이다."
  },
  {
    id: 3,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "방정식\n$2^{2x+1}=32$\n의 해를 $a$라 하자. 자연수 $n$에 대하여 부등식\n$\\log_3(n+1)\\le a+1$\n을 만족시키는 $n$의 개수를 구하시오.",
    choices: [],
    answer: "26",
    solution: "[키포인트] 지수방정식으로 $a$를 구한 뒤 로그부등식을 자연수 조건과 함께 처리한다.\\n조건 정리: $32=2^5$이고, $n$은 자연수이다.\\n풀이 방향: 먼저 $2^{2x+1}=32$에서 $a$를 구하고, 그 값을 로그부등식에 대입한다.\\n정석 풀이: $2^{2x+1}=32=2^5$이므로 $2x+1=5$이다. 따라서 $2x=4$, $x=2$이므로 $a=2$이다. 이제 $\\log_3(n+1)\\le a+1$에 $a=2$를 대입하면 $\\log_3(n+1)\\le 3$이다. 밑 $3$은 $1$보다 크므로 $n+1\\le 3^3=27$이다. 따라서 $n\\le 26$이다. $n$은 자연수이므로 가능한 값은 $1,2,3,\\ldots,26$으로 모두 $26$개이다.\\n따라서 구하는 값은 $26$이다."
  },
  {
    id: 4,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "정의역이 $\\{x\\mid 1\\le x\\le 4\\}$인 함수\n$y=2^{x-a}+b$\n의 최솟값이 $\\dfrac72$, 최댓값이 $7$일 때, 실수 $a,b$에 대하여 $ab$의 값을 구하시오.",
    choices: [],
    answer: "6",
    solution: "[키포인트] 밑이 $1$보다 큰 지수함수는 증가함수이므로 구간의 양 끝에서 최솟값과 최댓값이 정해진다.\\n조건 정리: 함수 $y=2^{x-a}+b$는 증가함수이고, 정의역은 $1\\le x\\le 4$이다.\\n풀이 방향: 최솟값은 $x=1$, 최댓값은 $x=4$에서 나온다는 점을 이용하여 두 식을 세운다.\\n정석 풀이: $x=1$에서 최솟값이므로 $2^{1-a}+b=\\dfrac{7}{2}$이다. $x=4$에서 최댓값이므로 $2^{4-a}+b=7$이다. 두 식을 빼면 $2^{4-a}-2^{1-a}=7-\\dfrac{7}{2}=\\dfrac{7}{2}$이다. 여기서 $2^{4-a}=2^{1-a}\\cdot 2^3=8\\cdot 2^{1-a}$이므로 $7\\cdot 2^{1-a}=\\dfrac{7}{2}$이다. 따라서 $2^{1-a}=\\dfrac{1}{2}=2^{-1}$이므로 $1-a=-1$, $a=2$이다. 이제 $2^{1-2}+b=\\dfrac{7}{2}$에서 $\\dfrac{1}{2}+b=\\dfrac{7}{2}$이므로 $b=3$이다. 따라서 $ab=2\\cdot 3=6$이다.\\n따라서 구하는 값은 $6$이다."
  },
  {
    id: 5,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "방정식\n$b^{2x}-7b^x+12=0$\n의 두 근의 차가 $1$일 때, $b>1$인 실수 $b$의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac43$",
    solution: "[키포인트] $b^x$를 하나의 문자로 치환한 뒤 두 근의 차 조건을 로그로 해석한다.\\n조건 정리: $b>1$이고, $b^x$는 양수이다.\\n풀이 방향: $t=b^x$로 치환하여 이차방정식을 풀고, 두 $x$값의 차가 $1$이라는 조건을 이용한다.\\n정석 풀이: $t=b^x$라 하면 주어진 방정식은 $t^2-7t+12=0$이다. 인수분해하면 $(t-3)(t-4)=0$이므로 $t=3$ 또는 $t=4$이다. 따라서 $b^x=3$, $b^x=4$에서 두 근은 각각 $\\log_b3$, $\\log_b4$이다. $b>1$이므로 $\\log_b4>\\log_b3$이다. 두 근의 차가 $1$이므로 $\\log_b4-\\log_b3=1$이다. 로그의 성질을 쓰면 $\\log_b\\dfrac{4}{3}=1$이므로 $b^1=\\dfrac{4}{3}$이다. 따라서 $b=\\dfrac{4}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{4}{3}$이다."
  },
  {
    id: 6,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수 $y=f(x)$의 그래프는 $x$절편이 $-1,3$이고 $y$절편이 $-3$인 이차함수의 그래프이다. 함수 $y=g(x)$의 그래프는 두 점 $(0,-3)$, $(3,0)$을 지나는 직선이다. 이때 부등식\n$\\left(\\frac12\\right)^{f(x)}<\\left(\\frac12\\right)^{g(x)}$\n을 만족시키는 실수 $x$의 값의 범위를 구하시오.",
    choices: [],
    answer: "$x<0\\ 또는\\ x>3$",
    solution: "[키포인트] 밑이 $0$과 $1$ 사이인 지수함수는 감소함수이므로 지수의 대소가 반대로 바뀐다.\\n조건 정리: $f(x)$는 $x$절편이 $-1,3$이고 $y$절편이 $-3$인 이차함수이며, $g(x)$는 두 점 $(0,-3)$, $(3,0)$을 지나는 직선이다.\\n풀이 방향: 먼저 $f(x)$와 $g(x)$를 구한 뒤, 밑이 $\\dfrac{1}{2}$인 지수부등식을 지수끼리 비교한다.\\n정석 풀이: $f(x)=a(x+1)(x-3)$이라 두면 $y$절편이 $-3$이므로 $f(0)=-3a=-3$이다. 따라서 $a=1$이고 $f(x)=x^2-2x-3$이다. 직선 $g(x)$는 $(0,-3)$, $(3,0)$을 지나므로 기울기가 $1$이고 $g(x)=x-3$이다. 밑 $\\dfrac{1}{2}$은 $0$과 $1$ 사이이므로 $\\left(\\dfrac{1}{2}\\right)^{f(x)}<\\left(\\dfrac{1}{2}\\right)^{g(x)}$이면 $f(x)>g(x)$이다. 따라서 $x^2-2x-3>x-3$이고, 정리하면 $x^2-3x>0$이다. 즉 $x(x-3)>0$이므로 $x<0$ 또는 $x>3$이다.\\n따라서 구하는 값은 $x<0\\ 또는\\ x>3$이다."
  },
  {
    id: 7,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 함수의 그래프 중 함수 $y=\\left(\\dfrac12\\right)^x$의 그래프를 평행이동하거나 대칭이동하여 포개질 수 없는 것은?",
    choices: [
      "$y=2^x$",
      "$y=\\left(\\dfrac12\\right)^x+4$",
      "$y=-\\left(\\dfrac12\\right)^x$",
      "$y=\\left(\\dfrac12\\right)^{x-2}$",
      "$y=\\log_2 x$"
    ],
    answer: "⑤",
    solution: "[키포인트] 지수함수 그래프는 평행이동과 대칭이동을 해도 지수함수 형태를 유지한다.\\n조건 정리: 기준 그래프는 $y=\\left(\\dfrac{1}{2}\\right)^x$이다.\\n풀이 방향: 각 보기의 그래프가 지수함수 그래프의 평행이동 또는 대칭이동으로 얻어지는지 확인한다.\\n정석 풀이: ① $y=2^x$는 $2^x=\\left(\\dfrac{1}{2}\\right)^{-x}$이므로 $y=\\left(\\dfrac{1}{2}\\right)^x$를 $y$축에 대하여 대칭이동한 그래프이다. ②는 위로 $4$만큼 평행이동한 그래프이다. ③은 $x$축에 대하여 대칭이동한 그래프이다. ④는 오른쪽으로 $2$만큼 평행이동한 그래프이다. 그러나 ⑤ $y=\\log_2 x$는 로그함수의 그래프이므로 지수함수 그래프를 평행이동하거나 대칭이동하는 것만으로는 포개질 수 없다.\\n따라서 정답은 ⑤이다."
  },
  {
    id: 8,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수\n$y=\\log_2(4x),\\quad y=\\log_2\\dfrac{x}{2}$\n의 그래프와 두 직선 $x=1,\\ x=a$로 둘러싸인 도형의 넓이가 $15$일 때, $a$의 값을 구하시오. 단, $a>1$이다.",
    choices: [],
    answer: "6",
    solution: "[키포인트] 두 로그함수의 차가 상수이면, 두 그래프 사이의 넓이는 직사각형 넓이로 계산된다.\\n조건 정리: 두 직선은 $x=1$, $x=a$이고, $a>1$이다.\\n풀이 방향: 위쪽 함수와 아래쪽 함수의 차를 구한 뒤, 가로 길이와 세로 길이의 곱으로 넓이를 세운다.\\n정석 풀이: 두 함수의 차는 $\\log_2(4x)-\\log_2\\dfrac{x}{2}=\\log_2\\left(4x\\cdot \\dfrac{2}{x}\\right)=\\log_2 8=3$이다. 따라서 두 그래프 사이의 세로 길이는 항상 $3$이다. 두 직선 $x=1$, $x=a$ 사이의 가로 길이는 $a-1$이다. 넓이가 $15$이므로 $3(a-1)=15$이다. 따라서 $a-1=5$, $a=6$이다.\\n따라서 구하는 값은 $6$이다."
  },
  {
    id: 9,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\n$y=\\log_2(x-1)+\\log_2(m-x)$\n의 최댓값이 $6$일 때, 실수 $m$의 값을 구하시오.",
    choices: [],
    answer: "17",
    solution: "[키포인트] 로그의 합을 하나의 로그로 합친 뒤, 이차식의 최댓값을 이용한다.\\n조건 정리: 로그가 정의되려면 $x-1>0$, $m-x>0$이므로 $1<x<m$이다.\\n풀이 방향: 로그의 성질로 $y=\\log_2\\{(x-1)(m-x)\\}$로 바꾸고, 곱 $(x-1)(m-x)$의 최댓값을 구한다.\\n정석 풀이: $y=\\log_2(x-1)+\\log_2(m-x)=\\log_2\\{(x-1)(m-x)\\}$이다. 로그함수 $\\log_2 X$는 증가함수이므로 $y$의 최댓값은 $(x-1)(m-x)$의 최댓값에서 나온다. 두 양수 $x-1$과 $m-x$의 합은 $(x-1)+(m-x)=m-1$로 일정하다. 따라서 곱의 최댓값은 두 수가 같을 때이고, 그 값은 $\\left(\\dfrac{m-1}{2}\\right)^2$이다. 최댓값이 $6$이므로 $\\log_2\\left(\\dfrac{(m-1)^2}{4}\\right)=6$이다. 따라서 $\\dfrac{(m-1)^2}{4}=64$이고 $(m-1)^2=256$이다. 정의역이 존재하려면 $m>1$이므로 $m-1=16$, $m=17$이다.\\n따라서 구하는 값은 $17$이다."
  },
  {
    id: 10,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수 $y=\\log_2 x$의 그래프 위의 점을 $D$라 하자. 두 점\n$A(a,0),\\quad B(10,0)$\n과 $y$축 위의 점\n$C=(0,\\log_2 a)$\n에 대하여 사각형 $ABDC$가 평행사변형일 때, 양수 $a$의 값을 구하시오.",
    choices: [],
    answer: "5",
    solution: "[키포인트] 평행사변형의 좌표 관계를 이용하여 점 $D$의 좌표를 구하고, 로그함수 위의 점 조건을 적용한다.\\n조건 정리: $A(a,0)$, $B(10,0)$, $C=(0,\\log_2 a)$이고, 사각형 $ABDC$는 평행사변형이다.\\n풀이 방향: 평행사변형에서 $D=B+C-A$의 좌표 관계를 이용한 뒤, $D$가 $y=\\log_2 x$ 위에 있음을 대입한다.\\n정석 풀이: 사각형 $ABDC$가 평행사변형이므로 $\\overrightarrow{AD}=\\overrightarrow{BC}$이고, 좌표로는 $D=B+C-A$이다. 따라서 $D=(10,0)+(0,\\log_2 a)-(a,0)=(10-a,\\log_2 a)$이다. 점 $D$가 함수 $y=\\log_2 x$의 그래프 위에 있으므로 $\\log_2 a=\\log_2(10-a)$이다. 로그함수는 일대일대응이므로 $a=10-a$이다. 따라서 $2a=10$, $a=5$이다.\\n따라서 구하는 값은 $5$이다."
  },
  {
    id: 11,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "방정식\n$(\\log_2 x)^2-k\\log_2 x+m=0$\n의 두 양수 근을 $\\alpha,\\beta$라 하자.\n$\\alpha\\beta=256$\n이고, $\\log_2\\alpha$와 $\\log_2\\beta$의 차가 $4$일 때, $k+m$의 값을 구하시오.",
    choices: [],
    answer: "20",
    solution: "[키포인트] $\\log_2 x$를 치환하여 근과 계수의 관계를 이용한다.\\n조건 정리: 두 양수 근을 $\\alpha,\\beta$라 하면 $\\alpha\\beta=256=2^8$이고, $\\log_2\\alpha$와 $\\log_2\\beta$의 차는 $4$이다.\\n풀이 방향: $t=\\log_2 x$로 두면 주어진 방정식은 $t^2-kt+m=0$ 꼴이므로, 두 $t$값의 합과 곱을 구한다.\\n정석 풀이: $s=\\log_2\\alpha$, $r=\\log_2\\beta$라 하자. $\\alpha\\beta=256$이므로 $\\log_2(\\alpha\\beta)=\\log_2 256=8$이다. 따라서 $s+r=8$이다. 또 두 로그값의 차가 $4$이므로 두 수는 합이 $8$이고 차가 $4$인 수이다. 따라서 두 값은 $6$과 $2$이다. 이제 $t=\\log_2 x$로 치환하면 방정식은 $t^2-kt+m=0$이고 두 근이 $6$, $2$이다. 근과 계수의 관계에 의해 $k=6+2=8$, $m=6\\cdot 2=12$이다. 따라서 $k+m=8+12=20$이다.\\n따라서 구하는 값은 $20$이다."
  },
  {
    id: 12,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "배양기에 들어 있는 미생물의 수를 관찰하기 시작한 지 $x$시간 후의 미생물 수를 $f(x)$라 하고\n$f(x)=k\\cdot 3^{\\frac xa}$\n라 하자. 단, $a,k$는 양의 정수이다. 미생물의 수가 처음의 $3$배가 되는 데 $4$시간이 걸린다. 미생물의 수가 처음의 $9$배가 된 시점부터 $243$배가 되는 시점까지 걸리는 시간을 구하시오.",
    choices: [],
    answer: "12시간",
    solution: "[키포인트] 지수 증가식에서 처음의 몇 배가 되는지는 지수 부분으로 판단한다.\\n조건 정리: 처음 미생물 수는 $f(0)=k$이고, $f(x)=k\\cdot 3^{\\frac{x}{a}}$이다.\\n풀이 방향: 처음의 $3$배가 되는 시간을 이용해 $a$를 구한 뒤, $9$배와 $243$배가 되는 시간을 각각 구한다.\\n정석 풀이: 처음의 $3$배가 된다는 것은 $3^{\\frac{x}{a}}=3$이라는 뜻이다. 이때 $x=4$시간이므로 $3^{\\frac{4}{a}}=3^1$이다. 따라서 $\\dfrac{4}{a}=1$이고 $a=4$이다. 처음의 $9$배는 $9=3^2$이므로 $3^{\\frac{x}{4}}=3^2$에서 $\\dfrac{x}{4}=2$, $x=8$이다. 처음의 $243$배는 $243=3^5$이므로 $3^{\\frac{x}{4}}=3^5$에서 $\\dfrac{x}{4}=5$, $x=20$이다. 따라서 처음의 $9$배가 된 시점부터 $243$배가 되는 시점까지 걸리는 시간은 $20-8=12$시간이다.\\n따라서 구하는 값은 $12시간$이다."
  },
  {
    id: 13,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: ["그래프"],
    wide: false,
    content: "오른쪽 그림과 같이 제2사분면에서 함수 $y=9^{-x}$의 그래프 위의 점 $A$를 지나고 $x$축과 평행한 선분을 그어 함수 $y=3^{-x}$의 그래프와 만나는 점을 $B$라 한다. 점 $B$를 지나고 $y$축과 평행한 선분을 그어 함수 $y=9^{-x}$의 그래프와 만나는 점을 $C$라 하고, 점 $C$를 지나고 $x$축과 평행한 선분을 그어 함수 $y=3^{-x}$의 그래프와 만나는 점을 $D$라 할 때,\n$\\dfrac{\\overline{CD}}{\\overline{AB}}$\n의 값을 구하시오.",
    choices: [],
    answer: "2",
    solution: "[키포인트] 같은 $y$좌표를 갖는 두 지수함수 위의 점은 지수의 값을 비교하여 $x$좌표 관계를 구한다.\\n조건 정리: $9^{-x}=3^{-2x}$이므로 두 함수 $y=9^{-x}$와 $y=3^{-x}$의 지수 관계를 이용할 수 있다.\\n풀이 방향: 점 $A$의 $x$좌표를 문자로 두고, 같은 높이에서 만나는 점들의 $x$좌표를 차례로 구한다.\\n정석 풀이: 점 $A$의 $x$좌표를 $t$라 하자. 그러면 $A$는 $y=9^{-x}$ 위의 점이므로 $A=(t,9^{-t})=(t,3^{-2t})$이다. 점 $B$는 $y=3^{-x}$ 위에 있고 $A$와 $y$좌표가 같으므로 $3^{-x_B}=3^{-2t}$이다. 따라서 $x_B=2t$이다. 그러므로 $\\overline{AB}=|2t-t|=|t|$이다. 점 $C$는 $x$좌표가 $2t$이고 $y=9^{-x}$ 위에 있으므로 $C=(2t,9^{-2t})=(2t,3^{-4t})$이다. 점 $D$는 $y=3^{-x}$ 위에 있고 $C$와 $y$좌표가 같으므로 $3^{-x_D}=3^{-4t}$에서 $x_D=4t$이다. 따라서 $\\overline{CD}=|4t-2t|=2|t|$이다. 그러므로 $\\dfrac{\\overline{CD}}{\\overline{AB}}=\\dfrac{2|t|}{|t|}=2$이다.\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 14,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "정수 전체의 집합의 두 부분집합\n$A=\\{x\\mid \\log_2(x+4)\\le k\\},$\n$B=\\left\\{x\\mid \\left(\\frac12\\right)^{x^2-3x}\\le \\left(\\frac12\\right)^4\\right\\}$\n에 대하여 $n(A\\cap B)=4$를 만족시키는 자연수 $k$의 값을 구하시오.",
    choices: [],
    answer: "3",
    solution: "[키포인트] 로그부등식의 진수 조건과 지수부등식의 밑이 $0$과 $1$ 사이인 경우를 함께 처리한다.\\n조건 정리: 전체 집합은 정수 전체의 집합이고, $k$는 자연수이다.\\n풀이 방향: 먼저 집합 $A$, $B$에 속하는 정수의 조건을 각각 구한 뒤, 교집합의 원소 개수가 $4$가 되도록 $k$를 정한다.\\n정석 풀이: 집합 $A$에서 로그가 정의되려면 $x+4>0$이므로 정수 $x$에 대하여 $x\\ge -3$이다. 또 $\\log_2(x+4)\\le k$이고 밑 $2$는 $1$보다 크므로 $x+4\\le 2^k$이다. 따라서 $A$는 $-3\\le x\\le 2^k-4$인 정수의 집합이다. 다음으로 집합 $B$를 구한다. 밑 $\\dfrac{1}{2}$은 $0$과 $1$ 사이이므로 $\\left(\\dfrac{1}{2}\\right)^{x^2-3x}\\le \\left(\\dfrac{1}{2}\\right)^4$이면 $x^2-3x\\ge 4$이다. 즉 $x^2-3x-4\\ge 0$이고, $(x-4)(x+1)\\ge 0$이므로 $x\\le -1$ 또는 $x\\ge 4$이다. 이제 $A\\cap B$를 생각하면 $A$ 안에서 $x\\le -1$인 정수는 $-3,-2,-1$로 $3$개이다. 교집합의 원소가 모두 $4$개가 되려면 $x\\ge 4$인 부분에서 정수가 정확히 $1$개만 더 있어야 한다. 따라서 $4\\le x\\le 2^k-4$에 해당하는 정수가 정확히 $1$개여야 하므로 $2^k-4=4$이다. 따라서 $2^k=8$이고 $k=3$이다.\\n따라서 구하는 값은 $3$이다."
  }
];