window.examTitle = "비상대수지수로그_고2_유형심화";

window.questionBank = [
  {
    id: 1,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a>0,\\ b>0,\\ a\\ne b$일 때, 다음 식을 간단히 하시오.\\n\\[\\n\\frac{a^{\\frac23}-b^{\\frac23}}{a^{\\frac13}-b^{\\frac13}}\\n\\left(a^{\\frac23}-a^{\\frac13}b^{\\frac13}+b^{\\frac23}\\right)\\n\\]",
    choices: [],
    answer: "$a+b$",
    solution: "[키포인트] $a^{\\frac13}$, $b^{\\frac13}$을 하나의 문자처럼 보고 합차 구조를 이용한다.\\n조건 정리: $a>0$, $b>0$, $a\\ne b$이므로 $a^{\\frac13}-b^{\\frac13}\\ne0$이다.\\n풀이 방향: $x=a^{\\frac13}$, $y=b^{\\frac13}$로 두면 식의 구조가 간단해진다.\\n정석 풀이: $x=a^{\\frac13}$, $y=b^{\\frac13}$라고 하자. 그러면 $a^{\\frac23}=x^2$, $b^{\\frac23}=y^2$, $a^{\\frac13}b^{\\frac13}=xy$이다.\\n주어진 식은 $\\dfrac{x^2-y^2}{x-y}(x^2-xy+y^2)$이다.\\n$x^2-y^2=(x-y)(x+y)$이므로 $\\dfrac{x^2-y^2}{x-y}=x+y$이다.\\n따라서 전체 식은 $(x+y)(x^2-xy+y^2)=x^3+y^3$이다.\\n$x^3=a$, $y^3=b$이므로 값은 $a+b$이다.\\n빠른 풀이 포인트: $\\dfrac{u^2-v^2}{u-v}=u+v$, $(u+v)(u^2-uv+v^2)=u^3+v^3$ 구조를 바로 보면 빠르게 정리할 수 있다.\\n따라서 구하는 값은 $a+b$이다."
  },
  {
    id: 2,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "부피가 $48\\pi$인 구의 반지름의 길이가 $\\sqrt[n]{6^m}$일 때, 서로소인 두 자연수 $m,\\ n$에 대하여 $2m+n$의 값을 구하시오.",
    choices: [],
    answer: "$7$",
    solution: "[키포인트] 구의 부피 공식으로 반지름을 구한 뒤 지수 꼴로 나타낸다.\\n조건 정리: 구의 부피는 $V=\\dfrac43\\pi r^3$이고, 부피가 $48\\pi$이다.\\n풀이 방향: 부피 공식에 대입하여 $r^3$을 구하고, 반지름을 $\\sqrt[n]{6^m}$ 꼴로 바꾼다.\\n정석 풀이: $\\dfrac43\\pi r^3=48\\pi$이므로 $r^3=36=6^2$이다.\\n따라서 $r=(6^2)^{\\frac13}=6^{\\frac23}=\\sqrt[3]{6^2}$이다.\\n그러므로 $m=2$, $n=3$이다.\\n구하는 값은 $2m+n=2\\cdot2+3=7$이다.\\n따라서 구하는 값은 $7$이다."
  },
  {
    id: 3,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$a>1$일 때, 다음을 만족시키는 자연수 $k$의 값을 구하시오.\\n\\[\\n\\sqrt[3]{a^2\\sqrt{a^k}}=a^{\\frac52}\\n\\]",
    choices: [],
    answer: "$11$",
    solution: "[키포인트] 거듭제곱근을 유리수 지수로 바꾸고 지수를 비교한다.\\n조건 정리: $a>1$이므로 같은 밑 $a$의 거듭제곱이 같으면 지수가 같다.\\n풀이 방향: 왼쪽을 $a$의 지수 꼴로 정리하여 $\\dfrac52$와 비교한다.\\n정석 풀이: $\\sqrt{a^k}=a^{\\frac{k}{2}}$이므로 $a^2\\sqrt{a^k}=a^2\\cdot a^{\\frac{k}{2}}=a^{2+\\frac{k}{2}}$이다.\\n따라서 $\\sqrt[3]{a^2\\sqrt{a^k}}=\\left(a^{2+\\frac{k}{2}}\\right)^{\\frac13}=a^{\\frac{2+\\frac{k}{2}}{3}}$이다.\\n이 값이 $a^{\\frac52}$와 같으므로 $\\dfrac{2+\\frac{k}{2}}{3}=\\dfrac52$이다.\\n양변에 $3$을 곱하면 $2+\\dfrac{k}{2}=\\dfrac{15}{2}$이고, $\\dfrac{k}{2}=\\dfrac{11}{2}$이다.\\n따라서 $k=11$이다.\\n따라서 구하는 값은 $11$이다."
  },
  {
    id: 4,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$x>0$이고\\n\\[\\nx+\\frac1x=7\\n\\]\\n일 때,\\n\\[\\nx^{\\frac32}+x^{-\\frac32}\\n\\]\\n의 값을 구하시오.",
    choices: [],
    answer: "$18$",
    solution: "[키포인트] $x^{\\frac12}+x^{-\\frac12}$의 값을 먼저 구한 뒤 세제곱 구조를 이용한다.\\n조건 정리: $x>0$이고 $x+\\dfrac1x=7$이다.\\n풀이 방향: $t=x^{\\frac12}+x^{-\\frac12}$로 두면 $t^2=x+2+x^{-1}$이다.\\n정석 풀이: $t=x^{\\frac12}+x^{-\\frac12}$라고 하자. 그러면 $t^2=x+2+x^{-1}=7+2=9$이다.\\n$t>0$이므로 $t=3$이다.\\n이제 $a=x^{\\frac12}$, $b=x^{-\\frac12}$라고 하면 $a+b=3$, $ab=1$이다.\\n구하는 값은 $a^3+b^3$이고, $a^3+b^3=(a+b)^3-3ab(a+b)$이다.\\n따라서 $a^3+b^3=3^3-3\\cdot1\\cdot3=27-9=18$이다.\\n따라서 구하는 값은 $18$이다."
  },
  {
    id: 5,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$2^x+2^{-x}=5$일 때,\\n\\[\\n\\frac{2^{3x}+2^{-3x}}{2^x+2^{-x}}\\n\\]\\n의 값을 구하시오.",
    choices: [],
    answer: "$22$",
    solution: "[키포인트] $a+a^{-1}$의 세제곱 관계를 이용하여 $a^3+a^{-3}$을 구한다.\\n조건 정리: $a=2^x$라고 두면 $a+a^{-1}=5$이다.\\n풀이 방향: $a^3+a^{-3}=(a+a^{-1})^3-3(a+a^{-1})$을 이용한다.\\n정석 풀이: $a=2^x$라 하면 $2^{-x}=a^{-1}$이므로 조건은 $a+a^{-1}=5$이다.\\n$a^3+a^{-3}=(a+a^{-1})^3-3(a+a^{-1})=5^3-3\\cdot5=125-15=110$이다.\\n따라서 주어진 식은 $\\dfrac{a^3+a^{-3}}{a+a^{-1}}=\\dfrac{110}{5}=22$이다.\\n빠른 풀이 포인트: $a^3+b^3=(a+b)^3-3ab(a+b)$에서 $ab=1$임을 바로 쓰면 계산이 짧아진다.\\n따라서 구하는 값은 $22$이다."
  },
  {
    id: 6,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 식의 값을 구하시오.\\n\\[\\n5^{\\log_5 2+\\log_{25}9}\\n\\]",
    choices: [],
    answer: "$6$",
    solution: "[키포인트] 로그의 밑을 맞추어 지수 전체를 하나의 로그로 정리한다.\\n조건 정리: $25=5^2$이므로 $\\log_{25}9=\\dfrac12\\log_5 9$이다.\\n풀이 방향: 지수 부분을 $\\log_5$ 꼴로 통일한 뒤 $5^{\\log_5 A}=A$를 이용한다.\\n정석 풀이: $\\log_{25}9=\\dfrac{\\log_5 9}{\\log_5 25}=\\dfrac12\\log_5 9=\\log_5 3$이다.\\n따라서 지수는 $\\log_5 2+\\log_5 3=\\log_5 6$이다.\\n그러므로 $5^{\\log_5 2+\\log_{25}9}=5^{\\log_5 6}=6$이다.\\n따라서 구하는 값은 $6$이다."
  },
  {
    id: 7,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "다음 식이 정의되기 위한 실수 $x$의 값의 범위를 구하시오.\\n\\[\\n\\log_{x-2}(x^2-5x+6)+\\log_3(7-x)\\n\\]",
    choices: [],
    answer: "$3<x<7$",
    solution: "[키포인트] 로그식이 정의되려면 각 로그의 밑 조건과 진수 조건을 모두 만족해야 한다.\\n조건 정리: $\\log_{x-2}(x^2-5x+6)$에서 밑은 $x-2$이고 진수는 $x^2-5x+6$이다. $\\log_3(7-x)$에서는 진수 $7-x$가 양수이어야 한다.\\n풀이 방향: 첫 번째 로그의 밑 조건, 첫 번째 로그의 진수 조건, 두 번째 로그의 진수 조건을 모두 구해 교집합을 찾는다.\\n정석 풀이: 첫 번째 로그의 밑 조건은 $x-2>0$이고 $x-2\\ne1$이다. 따라서 $x>2$, $x\\ne3$이다.\\n첫 번째 로그의 진수 조건은 $x^2-5x+6>0$이다. 인수분해하면 $(x-2)(x-3)>0$이므로 $x<2$ 또는 $x>3$이다.\\n두 번째 로그의 진수 조건은 $7-x>0$이므로 $x<7$이다.\\n세 조건의 교집합을 구하면 $x>2$, $x\\ne3$, $x<2$ 또는 $x>3$, $x<7$을 모두 만족해야 하므로 $3<x<7$이다.\\n따라서 구하는 범위는 $3<x<7$이다."
  },
  {
    id: 8,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log_2 3=a,\\ \\log_2 5=b$일 때,\\n\\[\\n\\log_{15}90\\n\\]\\n을 $a,\\ b$에 대한 식으로 나타내시오.",
    choices: [],
    answer: "$\\dfrac{1+2a+b}{a+b}$",
    solution: "[키포인트] 밑변환을 이용하여 모든 로그를 밑 $2$로 나타낸다.\\n조건 정리: $\\log_2 3=a$, $\\log_2 5=b$이다.\\n풀이 방향: $\\log_{15}90=\\dfrac{\\log_2 90}{\\log_2 15}$로 바꾼 뒤 소인수분해한다.\\n정석 풀이: $15=3\\cdot5$이므로 $\\log_2 15=\\log_2 3+\\log_2 5=a+b$이다.\\n또 $90=2\\cdot3^2\\cdot5$이므로 $\\log_2 90=\\log_2 2+2\\log_2 3+\log_2 5=1+2a+b$이다.\\n따라서 $\\log_{15}90=\\dfrac{\\log_2 90}{\\log_2 15}=\\dfrac{1+2a+b}{a+b}$이다.\\n따라서 구하는 값은 $\\dfrac{1+2a+b}{a+b}$이다."
  },
  {
    id: 9,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$1$이 아닌 양수 $a,\\ b$가\\n\\[\\n\\log_2 a\\cdot \\log_b 8=1\\n\\]\\n을 만족시킬 때,\\n\\[\\n(\\log_a b)^2+(\\log_b a)^2\\n\\]\\n의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{82}{9}$",
    solution: "[키포인트] 로그를 같은 밑으로 바꾸어 $\\log_a b$와 $\\log_b a$의 관계를 구한다.\\n조건 정리: $\\log_b8=\\dfrac{\\log_2 8}{\\log_2 b}=\\dfrac3{\\log_2 b}$이다.\\n풀이 방향: $A=\\log_2a$, $B=\\log_2b$로 두고 조건을 정리한 뒤 필요한 로그값을 구한다.\\n정석 풀이: $A=\\log_2a$, $B=\\log_2b$라고 하면 조건은 $A\\cdot\\dfrac3B=1$이다. 따라서 $B=3A$이다.\\n그러므로 $\\log_ab=\\dfrac{\\log_2b}{\\log_2a}=\\dfrac BA=3$이다.\\n또 $\\log_ba=\\dfrac AB=\\dfrac13$이다.\\n따라서 $(\\log_ab)^2+(\\log_ba)^2=3^2+\\left(\\dfrac13\\right)^2=9+\\dfrac19=\\dfrac{82}{9}$이다.\\n따라서 구하는 값은 $\\dfrac{82}{9}$이다."
  },
  {
    id: 10,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log 2.4=0.3802$임을 이용하여 다음 등식을 만족시키는 $M,\\ N$의 값을 구하시오.\\n(1) $\\log 0.024=M$\\n(2) $\\log N=3.3802$",
    choices: [],
    answer: "(1) $M=-1.6198$\\n(2) $N=2400$",
    solution: "[키포인트] 상용로그에서 소수점 이동은 로그값에 정수를 더하거나 빼는 것과 같다.\\n조건 정리: $\\log2.4=0.3802$이다.\\n풀이 방향: $0.024=2.4\\times10^{-2}$, $3.3802=0.3802+3$을 이용한다.\\n정석 풀이: (1) $0.024=2.4\\times10^{-2}$이므로 $\\log0.024=\\log2.4+\log10^{-2}=0.3802-2=-1.6198$이다. 따라서 $M=-1.6198$이다.\\n(2) $3.3802=0.3802+3=\\log2.4+\log10^3$이므로 $N=2.4\\times10^3=2400$이다.\\n따라서 구하는 값은 (1) $M=-1.6198$, (2) $N=2400$이다."
  },
  {
    id: 11,
    level: "중상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 제품의 판매량이 해마다 $12\\%$씩 증가한다고 한다. 올해 판매량의 $2$배 이상이 되려면 최소 몇 년이 지나야 하는지 구하시오.\\n단, $\\log 2=0.3010,\\ \\log 1.12=0.0492$로 계산한다.",
    choices: [],
    answer: "$7$년",
    solution: "[키포인트] 매년 $12\\%$ 증가하므로 $1.12^n\\ge2$를 만족하는 최소 자연수 $n$을 구한다.\\n조건 정리: $n$년 후 판매량은 올해 판매량의 $(1.12)^n$배이다.\\n풀이 방향: $(1.12)^n\\ge2$의 양변에 상용로그를 취해 $n$의 범위를 구한다.\\n정석 풀이: $(1.12)^n\\ge2$에서 로그를 취하면 $n\\log1.12\\ge\\log2$이다.\\n주어진 값에 의해 $n\\cdot0.0492\\ge0.3010$이다.\\n따라서 $n\\ge\\dfrac{0.3010}{0.0492}\\approx6.12$이다.\\n$n$은 자연수이므로 최소 $n=7$이다.\\n따라서 구하는 값은 $7$년이다."
  },
  {
    id: 12,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "\\[\\n\\sqrt{\\frac n3},\\quad \\sqrt[3]{\\frac n2}\\n\\]\\n이 모두 자연수가 되도록 하는 자연수 $n$ 중 작은 것부터 두 개를 구하시오.",
    choices: [],
    answer: "$432,\\ 27648$",
    solution: "[키포인트] 제곱수 조건과 세제곱수 조건을 동시에 만족하는 $n$의 형태를 찾는다.\\n조건 정리: $\\sqrt{\\dfrac n3}$이 자연수이려면 $\\dfrac n3$은 완전제곱수이고, $\\sqrt[3]{\\dfrac n2}$가 자연수이려면 $\\dfrac n2$는 완전세제곱수이다.\\n풀이 방향: $n=2^a3^b$ 꼴에서 지수 조건을 만족하는 값을 작은 순서대로 구한다.\\n정석 풀이: $\\dfrac n3=2^a3^{b-1}$이 완전제곱수이므로 $a$는 짝수이고 $b-1$도 짝수이어야 한다.\\n또 $\\dfrac n2=2^{a-1}3^b$이 완전세제곱수이므로 $a-1$은 $3$의 배수이고 $b$도 $3$의 배수이어야 한다.\\n$a$는 짝수이면서 $a-1$이 $3$의 배수인 값이므로 작은 값부터 $a=4,10,\\cdots$이다.\\n$b$는 $3$의 배수이면서 $b-1$이 짝수인 값이므로 작은 값부터 $b=3,9,\\cdots$이다.\\n가장 작은 $n$은 $2^4\\cdot3^3=16\\cdot27=432$이다.\\n그다음 작은 값은 $a$를 다음 값으로 올린 $2^{10}\\cdot3^3=27648$이고, $b$를 올린 $2^4\\cdot3^9$보다 작다.\\n따라서 작은 것부터 두 개는 $432$, $27648$이다.\\n따라서 구하는 값은 $432,\\ 27648$이다."
  },
  {
    id: 13,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "음이 아닌 두 정수 $m,\\ n$에 대하여\\n\\[\\n\\frac12\\log N=m\\log 2+n\\log 3\\n\\]\\n를 만족시키는 모든 자연수 $N$의 값의 합을 구하시오.\\n단, $m,\\ n$은 모두 $0$이 아니고, $1\\le N\\le 900$이다.",
    choices: [],
    answer: "$1080$",
    solution: "[키포인트] 로그식을 하나의 로그로 묶어 $N$의 형태를 찾고 범위 조건을 적용한다.\\n조건 정리: $m,n$은 모두 $0$이 아니므로 $m\\ge1$, $n\\ge1$이다.\\n풀이 방향: 양변에 $2$를 곱해 $N=2^{2m}3^{2n}$ 꼴로 나타낸 뒤 $900$ 이하인 값을 찾는다.\\n정석 풀이: $m\\log2+n\\log3=\\log(2^m3^n)$이므로 $\\dfrac12\\log N=\\log(2^m3^n)$이다.\\n양변에 $2$를 곱하면 $\\log N=\log(2^{2m}3^{2n})$이므로 $N=2^{2m}3^{2n}$이다.\\n$m\\ge1$, $n\\ge1$이므로 가장 작은 값은 $2^2\\cdot3^2=36$이다.\\n$N\\le900$이므로 $2^{2m}3^{2n}\\le900$이다. 가능한 값을 찾으면 $m=1,n=1$일 때 $36$, $m=2,n=1$일 때 $144$, $m=1,n=2$일 때 $324$, $m=2,n=2$일 때 $1296$으로 범위를 넘는다.\\n또 $m=3,n=1$이면 $576$, $m=1,n=3$이면 $2916$으로 범위를 넘는다.\\n따라서 가능한 $N$은 $36,144,324,576$이고, 합은 $36+144+324+576=1080$이다.\\n따라서 구하는 값은 $1080$이다."
  },
  {
    id: 14,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "망각 모델이\\n\\[\\n\\log P_0-\\log P_t=c\\log(t+1)\\n\\]\\n로 주어진다고 하자. 15개월 후의 기억 상태가 3개월 후의 기억 상태의 $\\dfrac18$일 때, 상수 $c$의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac32$",
    solution: "[키포인트] 두 시점의 식을 세운 뒤 빼서 기억 상태의 비율을 이용한다.\\n조건 정리: $15$개월 후의 기억 상태가 $3$개월 후의 기억 상태의 $\\dfrac18$이므로 $P_{15}=\\dfrac18P_3$이다.\\n풀이 방향: $t=15$와 $t=3$을 각각 대입하고 두 식을 빼면 $P_3$와 $P_{15}$의 비율만 남는다.\\n정석 풀이: $t=15$일 때 $\\log P_0-\\log P_{15}=c\\log16$이다.\\n$t=3$일 때 $\\log P_0-\\log P_3=c\\log4$이다.\\n두 식을 빼면 $\\log P_3-\\log P_{15}=c(\\log16-\\log4)=c\\log4$이다.\\n조건 $P_{15}=\\dfrac18P_3$에서 $\\dfrac{P_3}{P_{15}}=8$이므로 $\\log P_3-\\log P_{15}=\\log8$이다.\\n따라서 $\\log8=c\\log4$이다. $8=2^3$, $4=2^2$이므로 $c=\\dfrac{\\log8}{\\log4}=\\dfrac32$이다.\\n따라서 구하는 값은 $\\dfrac32$이다."
  },
    {
    id: 15,
    level: "중상",
    category: "지수함수와 로그함수",
    originalCategory: "지수함수와 로그함수",
    standardCourse: "대수",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "정의역이 $\\{x\\mid -1\\le x\\le 3\\}$일 때, 함수\\n\\[\\ny=\\log_{\\frac13}(x+2)+k\\n\\]\\n의 최댓값이 $4$가 되도록 하는 실수 $k$의 값을 구하고, 이때의 최솟값을 구하시오.",
    choices: [],
    answer: "$k=4$, 최솟값 $4-\\log_3 5$",
    solution: "[키포인트] 밑이 $\\dfrac13$인 로그함수는 감소함수이므로 정의역의 양 끝에서 최댓값과 최솟값이 결정된다.\\n조건 정리: 정의역은 $-1\\le x\\le3$이고, $x+2$의 범위는 $1\\le x+2\\le5$이다.\\n풀이 방향: 함수 $y=\\log_{\\frac13}(x+2)+k$의 증가·감소를 판단한 뒤 최댓값 조건으로 $k$를 구한다.\\n정석 풀이: 밑 $\\dfrac13$은 $0<\\dfrac13<1$이므로 $\\log_{\\frac13}(x+2)$는 감소함수이다.\\n따라서 최댓값은 $x=-1$일 때이고, 이때 $x+2=1$이므로 $y=\\log_{\\frac13}1+k=0+k=k$이다.\\n최댓값이 $4$이므로 $k=4$이다.\\n최솟값은 $x=3$일 때이고, 이때 $x+2=5$이다. 따라서 최솟값은 $\\log_{\\frac13}5+4$이다.\\n$\\log_{\\frac13}5=-\\log_3 5$이므로 최솟값은 $4-\\log_3 5$이다.\\n따라서 구하는 값은 $k=4$, 최솟값 $4-\\log_3 5$이다."
  },
  {
    id: 16,
    level: "중상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\\n\\[\\ny=\\left(\\frac12\\right)^{x-a}+b\\n\\]\\n의 그래프가 직선 $y=-2$를 점근선으로 하고, 점 $(1,6)$과 점 $(3,0)$을 지난다. 이때 $a+b$의 값을 구하시오.",
    choices: [],
    answer: "$2$",
    solution: "[키포인트] 점근선으로 $b$를 구하고, 두 점을 대입하여 $a$를 결정한다.\\n조건 정리: $y=\\left(\\dfrac12\\right)^{x-a}+b$의 수평점근선은 $y=b$이다.\\n풀이 방향: 점근선 $y=-2$에서 $b=-2$를 얻고, 주어진 점 중 하나를 대입해 $a$를 구한다.\\n정석 풀이: 그래프의 점근선이 $y=-2$이므로 $b=-2$이다.\\n점 $(1,6)$을 대입하면 $6=\\left(\\dfrac12\\right)^{1-a}-2$이다. 따라서 $\\left(\\dfrac12\\right)^{1-a}=8$이다.\\n$8=2^3=\\left(\\dfrac12\\right)^{-3}$이므로 $1-a=-3$이고 $a=4$이다.\\n확인하면 점 $(3,0)$에 대하여 $0=\\left(\\dfrac12\\right)^{3-4}-2=2-2=0$이므로 조건에 맞다.\\n따라서 $a+b=4+(-2)=2$이다.\\n따라서 구하는 값은 $2$이다."
  },
  {
    id: 17,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\\n\\[\\ny=2\\cdot 3^x-5\\n\\]\\n의 그래프를 $x$축의 방향으로 $-1$만큼 평행이동한 후, $x$축에 대하여 대칭이동한 그래프가 점 $(2,k)$를 지난다. 이때 $k$의 값을 구하시오.",
    choices: [],
    answer: "$-49$",
    solution: "[키포인트] 평행이동 후 $x$축 대칭은 함수값의 부호를 바꾸는 것으로 처리한다.\\n조건 정리: 원래 함수는 $f(x)=2\\cdot3^x-5$이다.\\n풀이 방향: 먼저 $x$축의 방향으로 $-1$만큼 평행이동한 그래프의 식을 구하고, 그다음 $x$축 대칭을 적용한다.\\n정석 풀이: $x$축의 방향으로 $-1$만큼 평행이동하면 왼쪽으로 $1$만큼 이동하므로 새 함수는 $y=f(x+1)=2\\cdot3^{x+1}-5$이다.\\n이를 $x$축에 대하여 대칭이동하면 함수값의 부호가 바뀌므로 $y=-(2\\cdot3^{x+1}-5)=-2\\cdot3^{x+1}+5$이다.\\n점 $(2,k)$를 지나므로 $k=-2\\cdot3^3+5=-54+5=-49$이다.\\n따라서 구하는 값은 $-49$이다."
  },
  {
    id: 18,
    level: "상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수\\n\\[\\ny=\\left(\\frac12\\right)^x,\\qquad y=\\left(\\frac18\\right)^x\\n\\]\\n의 그래프와 직선 $y=k$가 만나는 점을 각각 $A,\\ B$라 하자. 삼각형 $AOB$의 넓이가 $6$일 때, $k$의 값을 구하시오.\\n단, $k>1$이다.",
    choices: [],
    answer: "$k\\log_2 k=18$을 만족시키는 $1$보다 큰 실수 $k$",
    solution: "[키포인트] 직선 $y=k$ 위에 있는 두 교점의 $x$좌표 차이와 원점까지의 높이로 삼각형의 넓이를 세운다.\\n조건 정리: 두 점 $A$, $B$는 모두 직선 $y=k$ 위에 있고, $k>1$이다. 삼각형 $AOB$의 밑변은 두 점의 $x$좌표 차이이고 높이는 $k$이다.\\n풀이 방향: 각각의 그래프에서 $y=k$가 되는 $x$좌표를 $k$에 대한 식으로 나타낸 뒤 넓이 조건을 세운다.\\n정석 풀이: $y=\\left(\\dfrac12\\right)^x=2^{-x}$이므로 $k=2^{-x}$에서 $\\log_2 k=-x$, 즉 $x=-\\log_2 k$이다.\\n또 $y=\\left(\\dfrac18\\right)^x=2^{-3x}$이므로 $k=2^{-3x}$에서 $\\log_2 k=-3x$, 즉 $x=-\\dfrac13\\log_2 k$이다.\\n따라서 두 점의 $x$좌표 차이는 $\\left|-\\dfrac13\\log_2 k-(-\\log_2 k)\\right|=\\dfrac23\\log_2 k$이다.\\n두 점이 모두 $y=k$ 위에 있으므로 원점에서 직선 $y=k$까지의 높이는 $k$이다.\\n삼각형의 넓이는 $\\dfrac12\\cdot\\dfrac23\\log_2 k\\cdot k=\\dfrac13 k\\log_2 k$이다.\\n이 넓이가 $6$이므로 $\\dfrac13k\\log_2k=6$이고, $k\\log_2k=18$이다.\\n핵심 확인: $k>1$이면 $\\log_2k>0$이므로 밑변 길이와 넓이는 양수로 잘 정해진다.\\n따라서 구하는 값은 $k\\log_2 k=18$을 만족시키는 $1$보다 큰 실수 $k$이다."
  },
  {
    id: 19,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수 $y=\\log_2 x$의 그래프 위의 점 $A$에서 $x$축에 내린 수선의 발을 $B$라 하자. 점 $A$의 $y$좌표가 $3$이고, 직선 $y=x$ 위의 점 $C$가 $B$와 같은 $x$좌표를 가질 때, 점 $C$의 $y$좌표를 구하시오.",
    choices: [],
    answer: "$8$",
    solution: "[키포인트] 로그함수 위의 점의 좌표를 구한 뒤, 직선 $y=x$ 위의 점 조건을 이용한다.\\n조건 정리: 점 $A$는 $y=\\log_2x$ 위에 있고 $y$좌표가 $3$이다. 점 $B$는 $A$에서 $x$축에 내린 수선의 발이므로 $A$와 $B$의 $x$좌표가 같다.\\n풀이 방향: $A$의 $x$좌표를 먼저 구하고, 직선 $y=x$ 위에서 같은 $x$좌표를 갖는 점 $C$의 $y$좌표를 구한다.\\n정석 풀이: 점 $A$의 좌표를 $(x,3)$이라고 하면 $3=\\log_2x$이다. 따라서 $x=2^3=8$이다.\\n그러므로 점 $B$의 $x$좌표도 $8$이다.\\n점 $C$는 직선 $y=x$ 위에 있고 $B$와 같은 $x$좌표를 가지므로 $C$의 $x$좌표는 $8$이다.\\n직선 $y=x$ 위에서는 $y$좌표가 $x$좌표와 같으므로 점 $C$의 $y$좌표는 $8$이다.\\n따라서 구하는 값은 $8$이다."
  },
  {
    id: 20,
    level: "상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\\n\\[\\ny=\\log_{\\frac13}(x+4)+k\\n\\]\\n의 그래프가 제3사분면을 지나지 않도록 하는 실수 \\(k\\)의 최솟값을 구하시오. 또 이때 그래프와 \\(x\\)축이 만나는 점의 \\(x\\)좌표를 구하시오.",
    choices: [],
    answer: "\\[\\nk=\\log_3 4,\\quad x=0\\n\\]",
    solution: "[키포인트] 제3사분면을 지나지 않으려면 $-4<x<0$에서 함수값이 음수가 되지 않아야 한다.\\n조건 정리: 함수 $y=\\log_{\\frac13}(x+4)+k$의 정의역은 $x>-4$이다. 제3사분면은 $x<0$, $y<0$인 영역이다.\\n풀이 방향: $-4<x<0$에서 함수값의 하한을 살펴보고, 그 구간에서 음수가 되지 않도록 하는 최소 $k$를 찾는다.\\n정석 풀이: $-4<x<0$이면 $0<x+4<4$이다. 밑이 $\\dfrac13$인 로그함수는 감소함수이다.\\n$x+4$가 $4$에 가까워질 때 $\\log_{\\frac13}(x+4)$는 $\\log_{\\frac13}4$에 가까워진다.\\n그런데 $\\log_{\\frac13}4=-\\log_3 4$이다. 따라서 $-4<x<0$에서 $\\log_{\\frac13}(x+4)$는 $-\\log_34$보다 크다.\\n그래프가 제3사분면을 지나지 않으려면 $y=\\log_{\\frac13}(x+4)+k$가 $x<0$에서 음수가 되면 안 된다. 경계가 되는 최소값은 $k=\\log_34$이다.\\n이때 함수는 $y=\\log_{\\frac13}(x+4)+\\log_34$이다. $x$축과 만나는 점은 $y=0$을 만족한다.\\n$0=\\log_{\\frac13}(x+4)+\\log_34$이고, $\\log_{\\frac13}(x+4)=-\\log_34=\\log_{\\frac13}4$이다.\\n따라서 $x+4=4$이고 $x=0$이다.\\n핵심 확인: $x=0$은 제3사분면의 내부가 아니라 축 위의 점이므로, 그래프가 제3사분면을 지나지 않는 조건과 모순되지 않는다.\\n따라서 구하는 값은 $k=\\log_3 4$, $x=0$이다."
  },
  {
    id: 21,
    level: "중",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수\\n\\[\\ny=\\log_2 x,\\qquad y=\\log_8 x\\n\\]\\n의 그래프와 직선 $x=k$가 만나는 점을 각각 $A,\\ B$라 하자. $\\overline{AB}=4$일 때, 실수 $k$의 값을 구하시오.\\n단, $k>1$이다.",
    choices: [],
    answer: "$64$",
    solution: "[키포인트] 같은 $x$좌표에서 두 로그함수의 $y$값 차이가 선분 $AB$의 길이이다.\\n조건 정리: 직선 $x=k$와 만나는 두 점은 $A(k,\\log_2k)$, $B(k,\\log_8k)$이다.\\n풀이 방향: $k>1$이므로 $\\log_2k>\\log_8k$이고, 두 값의 차이를 $4$로 둔다.\\n정석 풀이: $\\log_8k=\\dfrac{\\log_2k}{\\log_28}=\\dfrac13\\log_2k$이다.\\n따라서 $\\overline{AB}=\\log_2k-\\log_8k=\\log_2k-\\dfrac13\\log_2k=\\dfrac23\\log_2k$이다.\\n$\\overline{AB}=4$이므로 $\\dfrac23\\log_2k=4$이다.\\n따라서 $\\log_2k=6$이고, $k=2^6=64$이다.\\n따라서 구하는 값은 $64$이다."
  },
  {
    id: 22,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 세균 한 마리가 \\(t\\)시간 후에 \\(a^t\\)마리로 증식된다고 한다. 세균 \\(3\\)마리가 \\(5\\)시간 후에 \\(729\\)마리 이상이 되도록 하는 자연수 \\(a\\)의 최솟값을 구하시오.",
    choices: [],
    answer: "\\[\\n3\\n\\]",
    solution: "[키포인트] 처음 세균 수와 한 마리의 증식량을 곱해 전체 세균 수를 세운다.\\n조건 정리: 한 마리가 $t$시간 후 $a^t$마리로 증식하므로, 처음 $3$마리는 $5$시간 후 $3a^5$마리가 된다.\\n풀이 방향: $3a^5\\ge729$를 만족하는 자연수 $a$의 최솟값을 구한다.\\n정석 풀이: $3a^5\\ge729$이므로 $a^5\\ge243$이다.\\n$243=3^5$이므로 $a^5\\ge3^5$이다.\\n$a$는 자연수이므로 이를 만족하는 최솟값은 $a=3$이다.\\n따라서 구하는 값은 $3$이다."
  },
  {
    id: 23,
    level: "중상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 호수의 오염 물질을 해마다 $8\\%$씩 감소시킨다고 한다. 오염 물질이 현재 오염 물질의 $\\dfrac13$배 이하가 되는 것은 최소 몇 년 후인지 구하시오.\\n단, $\\log 3=0.48,\\ \\log 9.2=0.96$으로 계산한다.",
    choices: [],
    answer: "$12$년",
    solution: "[키포인트] 매년 $8\\%$씩 감소하면 남은 양은 매년 $0.92$배가 된다.\\n조건 정리: $n$년 후 오염 물질의 양은 현재의 $(0.92)^n$배이다.\\n풀이 방향: $(0.92)^n\\le\\dfrac13$을 만족하는 최소 자연수 $n$을 로그로 구한다.\\n정석 풀이: $0.92=\\dfrac{9.2}{10}$이므로 $\\log0.92=\\log9.2-1=0.96-1=-0.04$이다.\\n부등식 $(0.92)^n\\le\\dfrac13$의 양변에 상용로그를 취하면 $n\\log0.92\\le\\log\\dfrac13=-\\log3=-0.48$이다.\\n$\\log0.92=-0.04$는 음수이므로 부등호 방향이 바뀌어 $n\\ge\\dfrac{-0.48}{-0.04}=12$이다.\\n따라서 최소 $12$년 후이다.\\n따라서 구하는 값은 $12$년이다."
  },
  {
    id: 24,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "점 \\(P(12,2)\\)가 함수\\n\\[\\ny=\\log_a(x+b)\\n\\]\\n의 그래프 위에 있다. 이 그래프가 \\(x\\)축과 만나는 점을 \\(A\\), 원점을 \\(O\\)라 하자. \\(\\overline{OA}=3\\)일 때,\\n\\[\\n\\log_2 ab\\n\\]\\n의 값을 구하시오. 단, \\(a>0,\\ a\\ne1,\\ b>0\\)이다.",
    choices: [],
    answer: "\\[\\n4\\n\\]",
    solution: "[키포인트] $x$축과의 교점에서 로그값이 $0$이 되는 조건을 이용한다.\\n조건 정리: 함수 $y=\\log_a(x+b)$의 그래프가 $x$축과 만나는 점을 $A$라 하고, $\\overline{OA}=3$이다.\\n풀이 방향: $x$축 위의 교점에서는 $y=0$이므로 $x+b=1$을 이용하고, 점 $P(12,2)$를 대입하여 $a$, $b$를 구한다.\\n정석 풀이: $x$축과 만나는 점에서는 $0=\\log_a(x+b)$이므로 $x+b=1$이다.\\n또 $\\overline{OA}=3$이고 교점의 $x$좌표가 양수인 경우를 사용하면 $A=(3,0)$이다. 따라서 $3+b=1$이므로 $b=-2$가 되어 $b>0$에 어긋난다.\\n교점이 $A=(-3,0)$이면 $\\overline{OA}=3$이고, $-3+b=1$이므로 $b=4$이다.\\n점 $P(12,2)$가 그래프 위에 있으므로 $2=\\log_a(12+4)=\\log_a16$이다. 따라서 $a^2=16$이고 $a>0$이므로 $a=4$이다.\\n따라서 $ab=4\\cdot4=16$이고 $\\log_2ab=\\log_216=4$이다.\\n따라서 구하는 값은 $4$이다."
  },
  {
    id: 25,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "어느 전자 기기에서 방출되는 전자파의 양을 $T_0$, 이 전자 기기로부터의 거리가 $y\\text{ cm}$인 지점에서 측정되는 전자파의 양을 $T$라고 하면\\n\\[\\ny=c\\log_3\\frac{T_0}{T}\\n\\]\\n라고 한다. 이 전자 기기로부터의 거리가 $30\\text{ cm}$인 지점에서 측정되는 전자파의 양이 방출되는 전자파의 양의 $\\dfrac19$이라고 할 때, 이 전자 기기로부터의 거리가 $75\\text{ cm}$인 지점에서 측정되는 전자파의 양은 방출되는 전자파의 양의 몇 $\\%$ 이하인지 구하시오.",
    choices: [],
    answer: "$\\dfrac{100}{243}\\%$",
    solution: "[키포인트] 거리와 전자파 비율 조건으로 상수 $c$를 먼저 구한다.\\n조건 정리: $y=c\\log_3\\dfrac{T_0}{T}$이고, $y=30$일 때 $T=\\dfrac19T_0$이다.\\n풀이 방향: 주어진 조건을 대입해 $c$를 구한 뒤, $y=75$일 때의 $T/T_0$을 계산한다.\\n정석 풀이: $T=\\dfrac19T_0$이면 $\\dfrac{T_0}{T}=9$이다. 따라서 $30=c\\log_39=2c$이고, $c=15$이다.\\n이제 $y=75$를 대입하면 $75=15\\log_3\\dfrac{T_0}{T}$이다.\\n따라서 $\\log_3\\dfrac{T_0}{T}=5$이고, $\\dfrac{T_0}{T}=3^5=243$이다.\\n그러므로 $T=\\dfrac1{243}T_0$이다. 이를 백분율로 나타내면 $\\dfrac1{243}\\times100=\\dfrac{100}{243}$이다.\\n따라서 구하는 값은 $\\dfrac{100}{243}\\%$이다."
  },
   {
    id: 26,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "자연수 $n$에 대하여\\n\\[\\n\\sqrt[n]{2^6}\\times \\sqrt[3]{4}=2^{\\frac43}\\n\\]\\n일 때, $n$의 값을 구하시오.",
    choices: [],
    answer: "$9$",
    solution: "[키포인트] 거듭제곱근을 유리수 지수로 바꾸어 지수를 비교한다.\\n조건 정리: $\\sqrt[n]{2^6}=2^{\\frac6n}$이고, $\\sqrt[3]{4}=\\sqrt[3]{2^2}=2^{\\frac23}$이다.\\n풀이 방향: 왼쪽을 밑이 $2$인 하나의 거듭제곱으로 정리한 뒤 오른쪽의 지수와 비교한다.\\n정석 풀이: $\\sqrt[n]{2^6}\\times\\sqrt[3]{4}=2^{\\frac6n}\\times2^{\\frac23}=2^{\\frac6n+\\frac23}$이다.\\n이 값이 $2^{\\frac43}$과 같으므로 $\\dfrac6n+\\dfrac23=\\dfrac43$이다.\\n따라서 $\\dfrac6n=\\dfrac43-\\dfrac23=\\dfrac23$이고, $6\\cdot3=2n$이므로 $n=9$이다.\\n따라서 구하는 값은 $9$이다."
  },
  {
    id: 27,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "양수 $a$에 대하여\\n\\[\\na-a^{-1}=3\\n\\]\\n일 때,\\n\\[\\na^3-a^{-3}\\n\\]\\n의 값을 구하시오.",
    choices: [],
    answer: "$36$",
    solution: "[키포인트] $u-v$의 세제곱 공식을 이용하고 $aa^{-1}=1$을 활용한다.\\n조건 정리: $a-a^{-1}=3$이고, $a\\cdot a^{-1}=1$이다.\\n풀이 방향: $u=a$, $v=a^{-1}$로 두고 $u^3-v^3=(u-v)^3+3uv(u-v)$를 이용한다.\\n정석 풀이: $u=a$, $v=a^{-1}$라 하면 $u-v=3$, $uv=1$이다.\\n$u^3-v^3=(u-v)^3+3uv(u-v)$이므로 $a^3-a^{-3}=3^3+3\\cdot1\\cdot3=27+9=36$이다.\\n따라서 구하는 값은 $36$이다."
  },
  {
    id: 28,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "세 양수 $a,\\ b,\\ c$에 대하여\\n\\[\\na^4=2,\\quad b^6=3,\\quad c^9=5\\n\\]\\n일 때, $(a^2bc)^n$이 자연수가 되도록 하는 자연수 $n$의 최솟값을 구하시오.",
    choices: [],
    answer: "$18$",
    solution: "[키포인트] 각 문자를 지수 꼴로 나타낸 뒤 모든 지수의 분모가 없어지도록 $n$을 정한다.\\n조건 정리: $a=2^{\\frac14}$, $b=3^{\\frac16}$, $c=5^{\\frac19}$이다.\\n풀이 방향: $a^2bc$를 소수의 유리수 지수 꼴로 정리한 뒤, $n$을 곱했을 때 지수가 모두 정수가 되는 최소값을 구한다.\\n정석 풀이: $a^2=(2^{\\frac14})^2=2^{\\frac12}$이고, $b=3^{\\frac16}$, $c=5^{\\frac19}$이다.\\n따라서 $(a^2bc)^n=(2^{\\frac12}3^{\\frac16}5^{\\frac19})^n=2^{\\frac n2}3^{\\frac n6}5^{\\frac n9}$이다.\\n이 값이 자연수가 되려면 $\\dfrac n2$, $\\dfrac n6$, $\\dfrac n9$가 모두 정수이어야 한다.\\n따라서 $n$은 $2,6,9$의 공배수이어야 하며, 최소공배수는 $18$이다.\\n따라서 구하는 값은 $18$이다."
  },
  {
    id: 29,
    level: "중",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "반지름의 길이가 $1$인 원을 일정한 비율로 반복하여 축소한다. $2$번 축소한 후의 반지름이 $\\dfrac14$일 때, $5$번 축소한 후의 반지름의 길이는?",
    choices: ["$\\dfrac1{16}$", "$\\dfrac1{32}$", "$\\dfrac1{64}$", "$\\dfrac1{128}$", "$\\dfrac1{256}$"],
    answer: "②",
    solution: "[키포인트] 일정한 비율로 반복 축소되므로 반지름은 등비수열처럼 변한다.\\n조건 정리: 한 번 축소될 때의 비율을 $r$이라 하면 $2$번 축소 후 반지름은 $r^2$이다.\\n풀이 방향: $r^2=\\dfrac14$에서 축소 비율 $r$을 구한 뒤 $5$번 축소 후의 반지름 $r^5$를 계산한다.\\n정석 풀이: 처음 반지름이 $1$이고, $2$번 축소 후의 반지름이 $\\dfrac14$이므로 $r^2=\\dfrac14$이다.\\n축소 비율은 양수이므로 $r=\\dfrac12$이다.\\n따라서 $5$번 축소 후의 반지름은 $r^5=\\left(\\dfrac12\\right)^5=\\dfrac1{32}$이다.\\n따라서 정답은 ②이다."
  },
  {
    id: 30,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "\\[\\n\\log_a 3=2,\\qquad \\log_{27} b=-\\frac13\\n\\]\\n일 때, $a^2b$의 값을 구하시오.",
    choices: [],
    answer: "$1$",
    solution: "[키포인트] 로그식을 지수식으로 바꾸어 $a^2$와 $b$를 각각 구한다.\\n조건 정리: $\\log_a3=2$, $\\log_{27}b=-\\dfrac13$이다.\\n풀이 방향: 첫 번째 식에서 $a^2=3$을 얻고, 두 번째 식에서 $b$를 계산한다.\\n정석 풀이: $\\log_a3=2$이므로 $a^2=3$이다.\\n또 $\\log_{27}b=-\\dfrac13$이므로 $b=27^{-\\frac13}=3^{-1}=\\dfrac13$이다.\\n따라서 $a^2b=3\\cdot\\dfrac13=1$이다.\\n따라서 구하는 값은 $1$이다."
  },
  {
    id: 31,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "객관식",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$\\log 6.18=0.7909$일 때, $\\log x=-2.2091$을 만족시키는 $x$의 값은?",
    choices: ["$0.00618$", "$0.0618$", "$0.618$", "$6.18$", "$61.8$"],
    answer: "①",
    solution: "[키포인트] 상용로그의 정수 부분은 소수점 위치를 결정한다.\\n조건 정리: $\\log6.18=0.7909$이고 $\\log x=-2.2091$이다.\\n풀이 방향: $-2.2091=0.7909-3$으로 나타내어 $x$를 구한다.\\n정석 풀이: $-2.2091=0.7909-3=\\log6.18+\log10^{-3}$이다.\\n따라서 $\\log x=\\log(6.18\\times10^{-3})$이므로 $x=0.00618$이다.\\n보기에서 $0.00618$은 ①이다.\\n따라서 정답은 ①이다."
  },
  {
    id: 32,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "이차방정식\\n\\[\\nx^2-9x+20=0\\n\\]\\n의 두 근이 $\\log_3 a,\\ \\log_3 b$이고 $\\log_3 a<\\log_3 b$일 때,\\n\\[\\n\\log_a b+\\log_3(ab)\\n\\]\\n의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{41}{4}$",
    solution: "[키포인트] 이차방정식의 두 근을 로그값에 대응시킨 뒤 밑변환을 이용한다.\\n조건 정리: $x^2-9x+20=0$의 두 근이 $\\log_3a$, $\\log_3b$이고 $\\log_3a<\\log_3b$이다.\\n풀이 방향: 두 근을 먼저 구해 $a$, $b$를 정하고, 구하는 로그식을 계산한다.\\n정석 풀이: $x^2-9x+20=(x-4)(x-5)$이므로 두 근은 $4$, $5$이다.\\n$\\log_3a<\\log_3b$이므로 $\\log_3a=4$, $\\log_3b=5$이다. 따라서 $a=3^4$, $b=3^5$이다.\\n$\\log_ab=\\dfrac{\\log_3b}{\\log_3a}=\\dfrac54$이다.\\n또 $ab=3^4\\cdot3^5=3^9$이므로 $\\log_3(ab)=9$이다.\\n따라서 $\\log_ab+\log_3(ab)=\\dfrac54+9=\\dfrac{41}{4}$이다.\\n따라서 구하는 값은 $\\dfrac{41}{4}$이다."
  },
  {
    id: 33,
    level: "중상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수\\n\\[\\ny=2^x,\\qquad y=8\\cdot 2^x\\n\\]\\n의 그래프와 두 직선 $y=4,\\ y=32$로 둘러싸인 도형의 넓이를 구하시오.",
    choices: [],
    answer: "$84$",
    solution: "[키포인트] 같은 높이 $y$에서 두 그래프의 $x$좌표 차이를 이용하여 넓이를 구한다.\\n조건 정리: 두 그래프는 $y=2^x$와 $y=8\\cdot2^x=2^{x+3}$이고, $4\\le y\\le32$ 사이의 넓이를 구한다.\\n풀이 방향: $y$를 기준으로 각 그래프의 $x$좌표를 나타내면 두 그래프 사이의 가로 길이가 일정함을 알 수 있다.\\n정석 풀이: $y=2^x$에서 $x=\log_2y$이다.\\n또 $y=8\\cdot2^x=2^{x+3}$이므로 $x=\log_2y-3$이다.\\n따라서 같은 높이 $y$에서 두 그래프 사이의 가로 길이는 $\\log_2y-(\\log_2y-3)=3$이다.\\n세로 길이는 $32-4=28$이므로 둘러싸인 도형의 넓이는 $3\\cdot28=84$이다.\\n따라서 구하는 값은 $84$이다."
  },
  {
    id: 34,
    level: "중상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\\n\\[\\ny=9^x-8\\cdot 3^x+a\\n\\]\\n가 $x=b$에서 최솟값 $1$을 가질 때, $a+b$의 값을 구하시오.",
    choices: [],
    answer: "$17+\\log_3 4$",
    solution: "[키포인트] $3^x$를 치환하여 이차식의 최솟값 문제로 바꾼다.\\n조건 정리: $9^x=(3^x)^2$이므로 $t=3^x$로 둘 수 있고 $t>0$이다.\\n풀이 방향: $y=t^2-8t+a$의 최솟값을 이용하여 $a$와 $b$를 구한다.\\n정석 풀이: $t=3^x$라 하면 $y=t^2-8t+a=(t-4)^2+a-16$이다.\\n최솟값은 $t=4$일 때 $a-16$이다. 문제에서 최솟값이 $1$이므로 $a-16=1$, 즉 $a=17$이다.\\n또 최솟값을 가질 때 $3^x=4$이므로 $b=\\log_34$이다.\\n따라서 $a+b=17+\\log_34$이다.\\n따라서 구하는 값은 $17+\\log_3 4$이다."
  },
  {
    id: 35,
    level: "중",
    category: "지수함수와 로그함수",
    originalCategory: "지수함수와 로그함수",
    standardCourse: "대수",
    standardUnitKey: "",
    standardUnit: "",
    standardUnitOrder: 0,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 함수\\n\\[\\ny=2^x,\\qquad y=\\log_2 x\\n\\]\\n의 그래프 위의 두 점 $A(3,d)$, $B(b,3)$에 대하여 $bd$의 값을 구하시오.",
    choices: [],
    answer: "$64$",
    solution: "[키포인트] 지수함수와 로그함수 위의 점 좌표를 각각 식에 대입한다.\\n조건 정리: 점 $A(3,d)$는 $y=2^x$ 위에 있고, 점 $B(b,3)$은 $y=\\log_2x$ 위에 있다.\\n풀이 방향: $d=2^3$을 구하고, $3=\\log_2b$에서 $b$를 구한다.\\n정석 풀이: $A(3,d)$가 $y=2^x$ 위에 있으므로 $d=2^3=8$이다.\\n또 $B(b,3)$이 $y=\\log_2x$ 위에 있으므로 $3=\\log_2b$이다. 따라서 $b=2^3=8$이다.\\n그러므로 $bd=8\\cdot8=64$이다.\\n따라서 구하는 값은 $64$이다."
  },
  {
    id: 36,
    level: "중상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "함수\\n\\[\\ny=\\log_3(x-a)+b\\n\\]\\n의 그래프가 직선 $x=2$를 점근선으로 하고, 두 점 $(5,3)$, $(29,5)$를 지날 때, $a+b$의 값을 구하시오.",
    choices: [],
    answer: "$4$",
    solution: "[키포인트] 로그함수의 점근선으로 $a$를 구하고, 점을 대입하여 $b$를 구한다.\\n조건 정리: $y=\\log_3(x-a)+b$의 점근선은 $x=a$이다.\\n풀이 방향: 점근선 $x=2$에서 $a=2$를 얻고, 주어진 점을 대입하여 $b$를 확인한다.\\n정석 풀이: 점근선이 $x=2$이므로 $a=2$이다.\\n점 $(5,3)$을 대입하면 $3=\\log_3(5-2)+b=\\log_33+b=1+b$이므로 $b=2$이다.\\n점 $(29,5)$를 확인하면 $5=\\log_3(29-2)+2=\\log_327+2=3+2=5$이므로 조건에 맞다.\\n따라서 $a+b=2+2=4$이다.\\n따라서 구하는 값은 $4$이다."
  },
  {
    id: 37,
    level: "중",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$xyz\\ne0$인 실수 $x,\\ y,\\ z$에 대하여\\n\\[\\n3^x=9^y=\\left(\\frac1{27}\\right)^z\\n\\]\\n이고 공통값이 $81$일 때,\\n\\[\\nx+y+z\\n\\]\\n의 값을 구하시오.",
    choices: [],
    answer: "$\\dfrac{14}{3}$",
    solution: "[키포인트] 공통값 $81$을 이용하여 각각의 지수를 직접 구한다.\\n조건 정리: $81=3^4$이고, $9=3^2$, $\\dfrac1{27}=3^{-3}$이다.\\n풀이 방향: 세 식을 모두 밑이 $3$인 지수식으로 바꾸어 $x$, $y$, $z$를 구한다.\\n정석 풀이: $3^x=81=3^4$이므로 $x=4$이다.\\n$9^y=(3^2)^y=3^{2y}=3^4$이므로 $2y=4$, $y=2$이다.\\n$\\left(\\dfrac1{27}\\right)^z=(3^{-3})^z=3^{-3z}=3^4$이므로 $-3z=4$, $z=-\\dfrac43$이다.\\n따라서 $x+y+z=4+2-\\dfrac43=6-\\dfrac43=\\dfrac{14}{3}$이다.\\n따라서 구하는 값은 $\\dfrac{14}{3}$이다."
  },
  {
    id: 38,
    level: "중상",
    category: "지수함수",
    originalCategory: "지수함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-02",
    standardUnit: "지수함수",
    standardUnitOrder: 2,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "클라이버의 법칙에 따르면 포유류가 하루 필요로 하는 대사량은 몸무게의 $\\dfrac34$제곱에 비례한다고 한다. 어떤 동물 A의 몸무게가 동물 B의 몸무게의 $200$배일 때, A의 대사량은 B의 대사량의 몇 배인지 구하시오.\\n단, $\\log 2=0.30,\\ \\log 5=0.70$으로 계산하고, 소수점 아래 첫째 자리에서 반올림한다.",
    choices: [],
    answer: "$53$배",
    solution: "[키포인트] 몸무게의 비가 $200$배이면 대사량의 비는 $200^{\\frac34}$배이다.\\n조건 정리: 대사량은 몸무게의 $\\dfrac34$제곱에 비례하고, 몸무게의 비는 $200$이다.\\n풀이 방향: $200^{\\frac34}$의 상용로그를 구한 뒤 값을 추정한다.\\n정석 풀이: 대사량의 비는 $200^{\\frac34}$이다.\\n$\\log200=\\log(2\\cdot10^2)=\\log2+2=0.30+2=2.30$이다.\\n따라서 $\\log\\left(200^{\\frac34}\\right)=\\dfrac34\\log200=\\dfrac34\\cdot2.30=1.725$이다.\\n즉 $200^{\\frac34}=10^{1.725}=10\\cdot10^{0.725}$이다. 주어진 값으로 $10^{0.70}=5$이고, $10^{0.725}$는 약 $5.3$이므로 전체 값은 약 $53$이다.\\n따라서 소수점 아래 첫째 자리에서 반올림하면 $53$배이다.\\n따라서 구하는 값은 $53$배이다."
  },
  {
    id: 39,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "$1$이 아닌 서로 다른 두 양수 $a,\\ b$에 대하여\\n\\[\\n\\log_a b=\\log_2 8\\n\\]\\n일 때, 다음 물음에 답하시오.\\n(1) $b$를 $a$에 대한 식으로 나타내시오.\\n(2) $2^x+8^{1-x}$의 최솟값을 구하시오.",
    choices: [],
    answer: "(1) $b=a^3$\\n(2) $\\dfrac{4\\cdot 24^{\\frac14}}{3}$",
    solution: "[키포인트] 로그값을 먼저 정리하고, 지수식의 최솟값은 치환 후 미분 또는 산술적 판단으로 구한다.\\n조건 정리: $\\log_28=3$이므로 $\\log_ab=3$이다.\\n풀이 방향: (1)은 로그의 정의로 바로 바꾸고, (2)는 $t=2^x$로 치환하여 양수 $t$에 대한 함수의 최솟값을 구한다.\\n정석 풀이: (1) $\\log_ab=3$이므로 $b=a^3$이다.\\n(2) $8^{1-x}=8\\cdot8^{-x}=8\\cdot(2^x)^{-3}$이다. $t=2^x$라 하면 $t>0$이고, 식은 $t+\\dfrac8{t^3}$이다.\\n$f(t)=t+\\dfrac8{t^3}$라 두면 $f'(t)=1-\\dfrac{24}{t^4}$이다.\\n최솟값을 가질 때 $f'(t)=0$이므로 $t^4=24$이고 $t=24^{\\frac14}$이다.\\n이때 $\\dfrac8{t^3}=\\dfrac8{24^{\\frac34}}=\\dfrac{8t}{24}=\\dfrac t3$이므로 최솟값은 $t+\\dfrac t3=\\dfrac43t=\\dfrac{4\\cdot24^{\\frac14}}3$이다.\\n따라서 구하는 값은 (1) $b=a^3$, (2) $\\dfrac{4\\cdot 24^{\\frac14}}{3}$이다."
  },
  {
    id: 40,
    level: "중상",
    category: "지수와 로그",
    originalCategory: "지수와 로그",
    standardCourse: "대수",
    standardUnitKey: "H22-A-01",
    standardUnit: "지수와 로그",
    standardUnitOrder: 1,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "\\[\\n1<a<a^{\\frac32}<b<a^2\\n\\]\\n을 만족시키는 실수 $a,\\ b$에 대하여 다음 네 수의 대소를 비교하시오.\\n\\[\\n\\log_b a,\\quad \\log_a b,\\quad \\log_{a^2} b,\\quad \\log_b a^2\\n\\]",
    choices: [],
    answer: "\\[\\n\\log_b a<\\log_{a^2}b<\\log_b a^2<\\log_a b\\n\\]",
    solution: "[키포인트] $b=a^t$로 두고 주어진 조건을 $t$의 범위로 바꾸어 비교한다.\\n조건 정리: $1<a<a^{\\frac32}<b<a^2$이므로 $b=a^t$라고 하면 $\\dfrac32<t<2$이다.\\n풀이 방향: 네 로그값을 모두 $t$에 대한 식으로 바꾼 뒤 대소를 비교한다.\\n정석 풀이: $b=a^t$라고 하면 $\\log_ab=t$이다.\\n$\\log_ba=\\dfrac1t$이고, $\\log_{a^2}b=\\dfrac{\\log_ab}{\\log_aa^2}=\\dfrac t2$이다.\\n또 $\\log_ba^2=\\dfrac{\\log_aa^2}{\\log_ab}=\\dfrac2t$이다.\\n이제 $\\dfrac32<t<2$에서 네 값 $\\dfrac1t$, $\\dfrac t2$, $\\dfrac2t$, $t$를 비교한다.\\n$t>1$이므로 $\\dfrac1t<\\dfrac t2$는 $2<t^2$와 같고, $t>\\sqrt2$이므로 참이다.\\n또 $\\dfrac t2<\\dfrac2t$는 $t^2<4$와 같고, $t<2$이므로 참이다.\\n마지막으로 $\\dfrac2t<t$는 $2<t^2$와 같고, $t>\\sqrt2$이므로 참이다.\\n따라서 $\\dfrac1t<\\dfrac t2<\\dfrac2t<t$이다.\\n즉 $\\log_ba<\\log_{a^2}b<\\log_ba^2<\\log_ab$이다.\\n따라서 대소관계는 $\\log_b a<\\log_{a^2}b<\\log_b a^2<\\log_a b$이다."
  },
  {
    id: 41,
    level: "상",
    category: "로그함수",
    originalCategory: "로그함수",
    standardCourse: "대수",
    standardUnitKey: "H22-A-03",
    standardUnit: "로그함수",
    standardUnitOrder: 3,
    questionType: "단답형",
    layoutTag: "grid",
    tags: [],
    wide: false,
    content: "두 집합\\n\\[\\nA=\\{x\\mid x^2-10x+21\\le0\\},\\n\\]\\n\\[\\nB=\\{x\\mid (\\log_2 x)^2-4\\log_2 x+k\\le0\\}\\n\\]\\n에 대하여 $A\\cap B=\\varnothing$이 되도록 하는 실수 $k$의 값의 범위를 구하시오.",
    choices: [],
    answer: "$k>4$",
    solution: "[키포인트] 집합 $A$의 범위를 구한 뒤 $t=\\log_2x$로 치환하여 집합 $B$와 겹치지 않게 하는 조건을 찾는다.\\n조건 정리: $A$는 이차부등식의 해집합이고, $B$는 $t=\\log_2x$에 대한 이차부등식의 해집합으로 볼 수 있다.\\n풀이 방향: 먼저 $A$를 구하고, $x\\in A$일 때의 $t=\\log_2x$ 범위를 확인한다. 그 범위에서 $B$의 조건식이 성립하지 않아야 한다.\\n정석 풀이: $x^2-10x+21\\le0$에서 $(x-3)(x-7)\\le0$이므로 $3\\le x\\le7$이다. 따라서 $A=\\{x\\mid 3\\le x\\le7\\}$이다.\\n$t=\\log_2x$라고 두면 $x\\in A$일 때 $\\log_23\\le t\\le\\log_27$이다. 이 구간은 $2$를 포함한다. 왜냐하면 $3<4<7$이므로 $\\log_23<2<\\log_27$이기 때문이다.\\n집합 $B$의 조건은 $t^2-4t+k\\le0$이다. $A\\cap B=\\varnothing$이 되려면 $x\\in A$에 대응하는 모든 $t$에 대해 $t^2-4t+k>0$이어야 한다.\\n이차식 $g(t)=t^2-4t+k=(t-2)^2+k-4$는 위로 열린 포물선이고 꼭짓점은 $t=2$이다.\\n$t=2$가 위 구간 안에 있으므로, 해당 구간에서의 최솟값은 $g(2)=k-4$이다.\\n교집합이 공집합이 되려면 최솟값도 양수이어야 하므로 $k-4>0$이다.\\n따라서 $k>4$이다.\\n핵심 확인: $g(t)=0$이 되는 값이 있으면 그 $x$는 $B$에 포함되므로, 공집합 조건에서는 $k=4$가 아니라 $k>4$가 되어야 한다.\\n따라서 구하는 값은 $k>4$이다."
  }
];