window.examTitle = "19_금당고_2학기_기말_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "점의 평행이동과 좌표 차",
    "originalCategory": "도형의 이동",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-12",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 12,
    "subUnitKey": "H15-SA-12-TRANSLATION",
    "subUnit": "평행이동",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "평면좌표",
      "점의 좌표",
      "평행이동",
      "좌표 변화"
    ],
    "wide": false,
    "content": "점 $(7,2)$를 $x$축의 방향으로 $-4$만큼, $y$축의 방향으로 3만큼 평행이동한 점의 좌표를 $(a,b)$라 할 때, $b-a$의 값은? [3.8점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SA_12_TRANSLATION",
    "problemTypeKey": "PT_MOVE_POINT_TRANSLATION",
    "templateKey": "TT_POINT_TRANSLATION_COORD",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f77e282b57ff90df38786cb2f8ba7dd743ef375d9eaa8a30cf062a742315a230"
  },
  {
    "id": 2,
    "level": "중",
    "category": "유리함수 그래프의 점근선",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "그래프",
      "점근선"
    ],
    "wide": false,
    "content": "유리함수 $y=\\dfrac{2x-3}{x-1}$의 그래프의 점근선을 $x=a$, $y=b$라 한다. $a+b$의 값은? [3.8점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_RATIONAL_ASYMPTOTE",
    "templateKey": "TPL_RATIONAL_ASYMPTOTE_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b6952a37d27c11f47bf8af817d317bc390326e512b5c383753983be97816f126"
  },
  {
    "id": 3,
    "level": "중",
    "category": "무리함수의 정의역·치역",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_BASIC",
    "subUnit": "무리함수의 뜻과 계산",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "정의역",
      "치역",
      "최솟값"
    ],
    "wide": false,
    "content": "무리함수 $y=\\sqrt{2x-6}+2$의 그래프의 정의역을 $\\{x\\mid x\\ge a\\}$, 치역을 $\\{y\\mid y\\ge b\\}$라 할 때, $a\\times b$의 값은? [3.8점]",
    "choices": [
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_BASIC",
    "problemTypeKey": "PT_DOMAIN_RANGE_SURJECTIVITY",
    "templateKey": "TPL_FUNCTION_DOMAIN_RANGE_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:813e768c8f1f56f2c0a8159cf1fc0f4bda884660714c3a5e1b4b533c3690c2ee"
  },
  {
    "id": 4,
    "level": "중",
    "category": "부등식 조건을 만족하는 자연수 순서쌍의 개수",
    "originalCategory": "경우의 수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-06",
    "standardUnit": "경우의 수",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "subUnit": "경우의 수의 기본 원리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "자연수",
      "순서쌍",
      "경우의 수",
      "부등식 조건"
    ],
    "wide": false,
    "content": "$x,y$가 자연수일 때, 부등식 $3\\le x+y\\le4$를 만족시키는 순서쌍 $(x,y)$의 개수를 구하시오. [3.8점]",
    "choices": [
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "problemTypeKey": "PT_H1_COUNTING_PRINCIPLE_GENERAL",
    "templateKey": "TPL_H1_COUNTING_DIRECT_CASE",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:0f0d0613c7c3d8c7e5e257c02b269d9c11f9d215234e352d7766178317d03ba9"
  },
  {
    "id": 5,
    "level": "중",
    "category": "서로 다른 두 종류에서 정해진 수를 선택하는 경우",
    "originalCategory": "조합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-08",
    "standardUnit": "조합",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-SB-08-COMBINATION_APPLICATION",
    "subUnit": "조합의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조합",
      "선택",
      "서로 다른 종류",
      "경우의 수"
    ],
    "wide": false,
    "content": "서로 다른 케이크 7개와 서로 다른 음료 5잔 중에서 케이크 2개와 음료 3잔을 택하는 모든 경우의 수를 구하시오. [4점]",
    "choices": [
      "210",
      "220",
      "230",
      "240",
      "250"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|5",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-08-COMBINATION_APPLICATION",
    "problemTypeKey": "PT_COUNTING_SELECTION_DISTRIBUTION",
    "templateKey": "TPL_COMBINATION_SELECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a17f9f71ec921e99420a6413055868a736c100a032d52e358f36d95fb7e1ae20"
  },
  {
    "id": 6,
    "level": "중",
    "category": "남녀를 모두 포함하는 대표 선출",
    "originalCategory": "조합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-08",
    "standardUnit": "조합",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-SB-08-COMBINATION_APPLICATION",
    "subUnit": "조합의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조합",
      "대표 선출",
      "남학생",
      "여학생",
      "포함 조건"
    ],
    "wide": false,
    "content": "남학생 5명과 여학생 5명으로 구성된 동아리에서 대표 4명을 뽑을 때, 남학생과 여학생을 적어도 1명씩 포함하는 모든 경우의 수를 구하시오. [4점]",
    "choices": [
      "198",
      "200",
      "202",
      "204",
      "206"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|6",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-08-COMBINATION_APPLICATION",
    "problemTypeKey": "PT_COUNTING_SELECTION_DISTRIBUTION",
    "templateKey": "TPL_COMBINATION_SELECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f8278e0256be83068df664c99e7dafad427039abbdc40f69e8a179e63ab7bdae"
  },
  {
    "id": 7,
    "level": "중",
    "category": "유리함수와 역함수의 계수 관계",
    "originalCategory": "역함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-INVERSE_FUNCTION",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "역함수",
      "계수",
      "함수 관계"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=\\dfrac{-x+3}{x+a}$, $g(x)=\\dfrac{bx+3}{cx+1}$에 대하여 $g^{-1}(x)=f(x)$일 때, 상수 $a,b,c$에 대하여 $a+b+c$의 값을 구하시오. [4점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|7",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-INVERSE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_COMPOSITION",
    "templateKey": "TPL_INVERSE_IDENTITY_RELATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:86492038ceab9ee93785f9baf3ca013cbea27a45c43125bd0fd96518c2626be9"
  },
  {
    "id": 8,
    "level": "중",
    "category": "유리함수 형태와 분자의 함수값",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "그래프",
      "분자 함수값",
      "원본 그래프"
    ],
    "wide": false,
    "content": "함수 $P(x)$에 대하여 함수 $y=\\dfrac{P(x)}{x-a}$의 그래프가 오른쪽 그림과 같을 때, $-5P(a)$의 값을 구하시오. [4점]",
    "choices": [
      "6",
      "7",
      "8",
      "9",
      "10"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_금당고_2학기_기말_고1_기출/q008_visual.png",
    "visualAsset": "assets/images/19_금당고_2학기_기말_고1_기출/q008_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 1455,
      "y1": 1905,
      "x2": 1670,
      "y2": 2180
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|8",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.94,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_금당고_2학기_기말_고1_기출/q008_visual.png",
      "assetSha256": "sha256:134936f617d4abec09546152578627ca7712bfa63d63c1bda9c53c09473c11da",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
      "sourceQuestionNo": "8",
      "sourcePageNo": 1,
      "sourcePageEvidence": "pages/page_p001.png",
      "sourcePageEvidencePaths": [
        "pages/page_p001.png"
      ],
      "sourceBBox": {
        "x1": 1455,
        "y1": 1905,
        "x2": 1670,
        "y2": 2180
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 215,
      "naturalHeight": 275,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:662019f99d513a1b6ed1aded21da3ccd73db8cefd860eeec355433d51286207e"
  },
  {
    "id": 9,
    "level": "중",
    "category": "직선에 대한 원의 대칭이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-12",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 12,
    "subUnitKey": "H15-SA-12-REFLECTION",
    "subUnit": "대칭이동",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "원의 방정식",
      "대칭이동",
      "직선에 대한 반사"
    ],
    "wide": false,
    "content": "원 $(x-5)^2+(y-1)^2=1$을 직선 $y=x-2$에 대하여 대칭이동한 원의 방정식이 $(x-a)^2+(y-b)^2=c$일 때, 상수 $a,b,c$에 대하여 $a+b+c$의 값을 구하시오. [4점]",
    "choices": [
      "4",
      "5",
      "6",
      "7",
      "8"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|9",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SA_12_REFLECTION",
    "problemTypeKey": "PT_MOVE_CIRCLE_REFLECTION",
    "templateKey": "TT_CIRCLE_REFLECTION_CENTER_RELATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:01d5b99cf6508f230c3ed5e3f8803285f46f45448901b994e24b90758c2971d9"
  },
  {
    "id": 10,
    "level": "중",
    "category": "무리함수 그래프와 직선의 교점 개수",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "직선",
      "교점 개수",
      "매개변수"
    ],
    "wide": false,
    "content": "두 집합 $A=\\{(x,y)\\mid y=\\sqrt{x-3}\\}$, $B=\\{(x,y)\\mid y=x+k\\}$에 대하여 $n(A\\cap B)=1$이 되도록 하는 정수 $k$의 최댓값은? [4점]",
    "choices": [
      "-1",
      "-2",
      "-3",
      "-4",
      "-5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|10",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_INTERSECTION",
    "templateKey": "TPL_FUNCTION_INTERSECTION_TWO_FUNCTIONS",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_INTEGER"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4eb6bdd221172d60b6db289e74f8034cc0ae7d9a4784692bc7427aa62130ed1c"
  },
  {
    "id": 11,
    "level": "중",
    "category": "두 무리함수 그래프의 교점과 거리",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "그래프의 교점",
      "두 점 사이의 거리",
      "대칭성"
    ],
    "wide": false,
    "content": "두 함수 $y=3\\sqrt{x+1}-2$, $x=3\\sqrt{y+1}-2$의 그래프가 두 점에서 만날 때, 이 두 점 사이의 거리를 $a\\sqrt{b}$라 하면 $a+b$의 값을 구하시오. [4점]",
    "choices": [
      "12",
      "13",
      "14",
      "15",
      "16"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|11",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_INTERSECTION",
    "templateKey": "TPL_FUNCTION_INTERSECTION_TWO_FUNCTIONS",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7cc99560294abc2bd5a7d258e5c0696ab35f2cc99b3735e9ce9909cb40d54672"
  },
  {
    "id": 12,
    "level": "중",
    "category": "좌표 조건이 있는 삼각형 둘레 최솟값",
    "originalCategory": "평면좌표",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-09",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-SA-09-COORDINATE_METRIC",
    "subUnit": "좌표와 거리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "평면좌표",
      "직각삼각형",
      "거리",
      "둘레의 최솟값"
    ],
    "wide": false,
    "content": "점 $A(3,4)$와 $y$축 위의 점 $B$, 직선 $y=x$ 위의 점 $C$를 꼭짓점으로 하는 삼각형 $ABC$의 둘레의 길이의 최솟값을 구하시오. [4점]",
    "choices": [
      "6",
      "4\\sqrt{2}",
      "7",
      "5\\sqrt{2}",
      "8"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|12",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-09-COORDINATE_METRIC",
    "problemTypeKey": "PT_COORD_DISTANCE_OPTIMIZATION",
    "templateKey": "TPL_DISTANCE_SUM_MIN",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d1350a0ad69603276edf93766365de55b76d1dcddaea2aeba4cea091bc138f81"
  },
  {
    "id": 13,
    "level": "중",
    "category": "이웃 숫자 제한과 양 끝 자리 조건이 있는 배열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "숫자 배열",
      "이웃 조건",
      "양 끝 자리"
    ],
    "wide": false,
    "content": "숫자 $1,2,3$을 전부 또는 일부 사용하여 같은 숫자가 이웃하지 않도록 다섯 자리 자연수를 만든다. 이때 만의 자리 숫자와 일의 자리 숫자가 같은 경우의 수를 구하시오. [4점]",
    "choices": [
      "14",
      "16",
      "18",
      "20",
      "24"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|13",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:90e90d076a176e5b0dd69d90ca4a493e88f12facd9d2cedd8475e439200c08ab"
  },
  {
    "id": 14,
    "level": "중",
    "category": "이동한 원이 두 직선에 접하는 조건",
    "originalCategory": "원의 방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-11",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 11,
    "subUnitKey": "H15-SA-11-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "원의 방정식",
      "평행이동",
      "접선",
      "접점 조건"
    ],
    "wide": false,
    "content": "원 $(x-a)^2+(y-a)^2=b^2$를 $y$축의 방향으로 $-2$만큼 평행이동한 도형이 직선 $y=x$와 $x$축에 동시에 접할 때, $2a^2-8b$의 값을 구하시오. (단, $a>2$, $b>0$) [4점]",
    "choices": [
      "4",
      "6",
      "8",
      "10",
      "12"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|14",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-11-TANGENT",
    "problemTypeKey": "PT_CIRCLE_TANGENT",
    "templateKey": "TM_TANGENCY_CONDITION",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_POSITIVE",
      "COND_RANGE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:9e0853c4eb254411a93203a51b71aa33f93b8ed9f8e52ba4c9198e85782ada7a"
  },
  {
    "id": 15,
    "level": "중",
    "category": "소수 숫자 포함 조건을 만족하는 비밀번호의 내림차순 순위",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "비밀번호",
      "서로 다른 숫자",
      "소수 포함",
      "순위"
    ],
    "wide": false,
    "content": "1부터 9까지의 자연수 중에서 서로 다른 세 개의 수를 뽑아 세 자리 자연수의 비밀번호를 설정하려고 한다. 비밀번호는 소수가 두 개 이상 포함되도록 하여 가장 큰 자연수부터 차례대로 나열할 때 62번째 오는 비밀번호를 구하시오. [4점]",
    "choices": [
      "675",
      "673",
      "672",
      "657",
      "653"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|15",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_H1_ARRANGEMENT_LEXICOGRAPHIC_RANK",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b7e1d8df43ad1caabf6fdec7067d664f88052ed3ec8cc01a2c23f13531e632fb"
  },
  {
    "id": 16,
    "level": "중",
    "category": "원 안의 정수 격자점으로 사각형을 만드는 경우",
    "originalCategory": "평면좌표",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-09",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 9,
    "subUnitKey": "H15-SA-09-GEOMETRY_APPLICATION",
    "subUnit": "도형의 방정식 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "평면좌표",
      "정수 격자점",
      "원",
      "사각형",
      "경우의 수"
    ],
    "wide": false,
    "content": "다음 조건을 만족시키는 점 $(x,y)$ 중에서 임의로 4개의 점을 택할 때, 만들 수 있는 사각형의 개수는?\n(가) $x,y$는 정수이다.\n(나) $x^2+y^2\\le4$ [4점]",
    "choices": [
      "260",
      "325",
      "395",
      "445",
      "455"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|16",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SA_09_GEOMETRY_APPLICATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:239b36231cee69b329a3f8c35e6fd0b1dc1066dbe17b46f8654572951fec3327"
  },
  {
    "id": 17,
    "level": "중",
    "category": "무리함수 그래프 위 점을 이용한 삼각형 넓이 최솟값",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "그래프 위의 점",
      "삼각형의 넓이",
      "최솟값"
    ],
    "wide": false,
    "content": "두 점 $A(-1,0)$, $B(0,1)$과 곡선 $y=\\sqrt{x}$ 위의 한 점 $P(x,y)$에 대하여 삼각형 $ABP$의 넓이의 최솟값이 $\\dfrac{a}{b}$일 때, $b-a$의 값은? [4.2점]",
    "choices": [
      "5",
      "4",
      "3",
      "2",
      "1"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|17",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_GEOMETRY",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e95472dabbf36ff257583d531bea95cb575260b096c94b2d3c2875c7bf03365b"
  },
  {
    "id": 18,
    "level": "중",
    "category": "역함수 조건과 그래프의 평행이동",
    "originalCategory": "역함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-INVERSE_FUNCTION",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "역함수",
      "그래프",
      "평행이동",
      "계수 조건"
    ],
    "wide": false,
    "content": "함수 $f(x)=\\dfrac{3x+a}{x+b}$가 다음 조건을 만족한다.\n(가) 3이 아닌 모든 실수 $x$에 대하여 $f^{-1}(x)=f(x+5)+5$이다.\n(나) 함수 $y=f^{-1}(x)$의 그래프를 평행이동하면 함수 $y=\\dfrac6x$의 그래프와 일치한다.\n이때 상수 $a,b$에 대하여 $a+b$의 값을 구하시오. [4.2점]",
    "choices": [
      "-28",
      "-26",
      "-24",
      "-22",
      "-20"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|18",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-INVERSE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_GRAPH",
    "templateKey": "TPL_INVERSE_GRAPH_GEOMETRY",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:97e44acdfd0404a26ad55744aae02e57d503b20b9b7d659e50da4cf291585c22"
  },
  {
    "id": 19,
    "level": "중",
    "category": "매개변수 무리함수 그래프의 서로 다른 교점 수",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "매개변수",
      "교점 개수",
      "서로 다른 점"
    ],
    "wide": false,
    "content": "좌표평면 위의 두 곡선 $y=-\\sqrt{kx+2k}+4$, $y=\\sqrt{-kx+2k}-4$에 대하여 두 곡선이 서로 다른 두 점에서 만나지 않도록 하는 $k$의 최댓값은? (단, $k$는 0이 아닌 실수이다.) [4.2점]",
    "choices": [
      "14",
      "16",
      "18",
      "20",
      "24"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "19",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 19,
    "displayNo": "19",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|19",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_INTERSECTION",
    "templateKey": "TPL_FUNCTION_INTERSECTION_TANGENCY_SINGLE",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NONZERO"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:23eb0229772aac56f16bd47cceabb4653caa3a7ad00177101bf1419f0b924667"
  },
  {
    "id": 20,
    "level": "중",
    "category": "평행이동한 삼각형에 내접하는 원",
    "originalCategory": "원의 방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-11",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 11,
    "subUnitKey": "H15-SA-11-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "원의 방정식",
      "내접원",
      "접선",
      "삼각형",
      "평행이동"
    ],
    "wide": false,
    "content": "좌표평면에서 세 점 $O(0,0)$, $A(4,0)$, $B(0,3)$을 꼭짓점으로 하는 삼각형 $OAB$를 평행이동한 도형을 삼각형 $O'A'B'$이라 하자. 점 $A'$의 좌표가 $(9,2)$일 때, 삼각형 $O'A'B'$에 내접하는 원의 방정식이 $x^2+y^2+ax+by+c=0$이다. (단, $a,b,c$는 상수이다.) $\\dfrac{a+b+c}{2}$의 값을 구하시오. [4.2점]",
    "choices": [
      "11",
      "12",
      "13",
      "14",
      "15"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_금당고_2학기_기말_고1_기출/q020_visual.png",
    "visualAsset": "assets/images/19_금당고_2학기_기말_고1_기출/q020_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1375,
      "y1": 1452,
      "x2": 1674,
      "y2": 1645
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "20",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 20,
    "displayNo": "20",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|20",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.94,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_금당고_2학기_기말_고1_기출/q020_visual.png",
      "assetSha256": "sha256:e685f6cf2840dd86e85e4f523732add4f51a3caf2c0085f1603c3fb9f147639a",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
      "sourceQuestionNo": "20",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 1375,
        "y1": 1452,
        "x2": 1674,
        "y2": 1645
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 299,
      "naturalHeight": 193,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-11-CIRCLE_EQUATION",
    "problemTypeKey": "PT_CIRCLE_EQUATION",
    "templateKey": "TM_CIRCLE_INCIRCLE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ce7a62f88468f632602ca8ff4621ed0439f24a52b1e430e6109bb9b1c887bfbe"
  },
  {
    "id": 21,
    "level": "중",
    "category": "유리함수 그래프 위 직사각형 둘레의 최솟값",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "그래프 위의 점",
      "직사각형",
      "둘레의 최솟값"
    ],
    "wide": false,
    "content": "그림과 같이 유리함수 $y=\\dfrac{5}{x-2}+3$의 그래프 위의 점 $P$에서 $x$축과 $y$축에 내린 수선의 발을 각각 $A,B$라 하자. 직사각형 $OAPB$의 네 변의 길이의 합이 최소가 되도록 하는 점 $P$의 좌표를 $(a,b)$라 할 때, $a+b$의 값은? (단, 점 $O$는 원점이고, 점 $P$는 제1사분면 위에 있다.) [10점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_금당고_2학기_기말_고1_기출/q021_visual.png",
    "visualAsset": "assets/images/19_금당고_2학기_기말_고1_기출/q021_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 660,
      "y1": 675,
      "x2": 940,
      "y2": 955
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "서술형1",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 21,
    "displayNo": "서술형1",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|서술형1",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 1,
    "visualAssetConfidence": 0.94,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_금당고_2학기_기말_고1_기출/q021_visual.png",
      "assetSha256": "sha256:e0c48994069fd50eac49da5f4b8432f505dc71e1c1cc229a6b10851e173c3b10",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
      "sourceQuestionNo": "서술형1",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 660,
        "y1": 675,
        "x2": 940,
        "y2": 955
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 280,
      "naturalHeight": 280,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_GEOMETRY",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:22ecbf835deb91a9980bbd82457fcfcb5686f382731d34c20634a91562bce423"
  },
  {
    "id": 22,
    "level": "중",
    "category": "무리함수와 역함수 그래프의 교점 및 거리 최솟값",
    "originalCategory": "역함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_INVERSE",
    "subUnit": "무리함수와 역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "역함수",
      "직선",
      "두 점 사이의 거리",
      "최솟값"
    ],
    "wide": false,
    "content": "함수 $f(x)=-\\sqrt{-x-4}$의 그래프와 그 역함수 $y=f^{-1}(x)$의 그래프가 직선 $y=-x+n$과 만나는 두 점을 각각 $A,B$라 할 때, 선분 $AB$의 길이의 최솟값을 구하시오. (단, $n\\le-4$) [10점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_금당고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_금당고1_2기말.pdf",
    "sourceQuestionNo": "서술형2",
    "sourceArchiveFile": "original/high/h1/2final/19_금당고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 22,
    "displayNo": "서술형2",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816",
    "sourceIdentityKey": "sha256:546135392a1d56734147a198989e11b66c1736492d26e19c1d837816d131f816|서술형2",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_금당고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_INVERSE",
    "problemTypeKey": "PT_INVERSE_GRAPH",
    "templateKey": "TPL_INVERSE_GRAPH_INTERSECTION",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NEGATIVE",
      "COND_RANGE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:49009c35c50563029dc65603b68f76bf3f3e9c65ff4ed890c4b76c5e6f0ca868"
  }
];
