window.examTitle = "19_강남여고_2학기_기말_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "복소수의 성분별 덧셈과 실수부·허수부",
    "originalCategory": "복소수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SA-04-COMPLEX_OPERATION",
    "subUnit": "복소수의 계산",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "복소수",
      "허수단위",
      "실수부",
      "허수부"
    ],
    "wide": false,
    "content": "등식 $(3-i)+(-2+3i)=a+bi$를 만족하는 실수 $a,b$에 대하여 $a+b$의 값은? [2.5점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-04-COMPLEX_OPERATION",
    "problemTypeKey": "PT_H1_COMPLEX_OPERATION",
    "templateKey": "TPL_H1_COMPLEX_COMPONENT_OPERATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d96affd9e6773492d1106b5f20386fae236274145bbdaf228f649da2a9b4876b"
  },
  {
    "id": 2,
    "level": "중",
    "category": "원의 방정식에서 중심·반지름과 좌표 합",
    "originalCategory": "원의 방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-11",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 11,
    "subUnitKey": "H15-SA-11-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "원의 방정식",
      "중심",
      "반지름"
    ],
    "wide": false,
    "content": "방정식 $(x-2)^2+(y-1)^2=9$이 나타내는 원의 중심의 좌표를 $(a,b)$, 반지름을 $r$이라 할 때, 실수 $a,b,r$에 대하여 $a+b+r$의 값은? [2.5점]",
    "choices": [
      "0",
      "1",
      "3",
      "6",
      "12"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-11-CIRCLE_EQUATION",
    "problemTypeKey": "PT_CIRCLE_EQUATION",
    "templateKey": "TM_CIRCLE_CENTER_RADIUS",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d72614466bf79f446addfd055f6926f6c4c45d16d6e74a70fca362019cafc7d0"
  },
  {
    "id": 3,
    "level": "중",
    "category": "두 유한집합의 교집합 원소의 합",
    "originalCategory": "집합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-01",
    "standardUnit": "집합",
    "standardUnitOrder": 1,
    "subUnitKey": "H15-SB-01-SET_OPERATION",
    "subUnit": "집합의 연산",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "집합",
      "교집합",
      "원소의 합"
    ],
    "wide": false,
    "content": "두 집합 $A=\\{1,2,3,4,5,6\\}$, $B=\\{1,3,5,7,9\\}$에 대하여 집합 $A\\cap B$의 모든 원소의 합은? [2.5점]",
    "choices": [
      "3",
      "6",
      "9",
      "12",
      "15"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-01-SET_OPERATION",
    "problemTypeKey": "PT_SET_AGGREGATE",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7e383ada5814d8833617cdfbeda3f99c25ead24b0fa5df808b6a721657b09800"
  },
  {
    "id": 4,
    "level": "중",
    "category": "유리함수 그래프의 평행이동과 점의 좌표",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "평행이동",
      "그래프 위 점"
    ],
    "wide": false,
    "content": "유리함수 $y=-\\dfrac2x$의 그래프를 $x$축의 방향으로 $-3$만큼, $y$축의 방향으로 2만큼 평행이동한 그래프가 점 $(-1,k)$를 지날 때, $k$의 값은? [2.5점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_TRANSFORM",
    "templateKey": "TPL_FUNCTION_GRAPH_TRANSLATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e1a13c95e84bd3df891176d3d202f0232a349509859409c49a123b0fe18efeaf"
  },
  {
    "id": 5,
    "level": "중",
    "category": "일차·이차 연립방정식의 해와 식의 값",
    "originalCategory": "연립방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-07",
    "standardUnit": "여러 가지 방정식",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SA-07-SUBSTITUTION_SYSTEM",
    "subUnit": "치환과 연립방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "연립방정식",
      "이차방정식",
      "해의 대입"
    ],
    "wide": false,
    "content": "연립방정식 $\\begin{cases}y=4x+6\\x^2+y=2\\end{cases}$의 해를 $x=a$, $y=b$라 할 때, $2a-3b$의 값은? [3점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|5",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-07-SUBSTITUTION_SYSTEM",
    "problemTypeKey": "PT_H1_SYSTEM_EQUATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:18376d3bf84fad8ef6b24d4177f37e49f639a3d109fcb68b3f90a7b9cecdd124"
  },
  {
    "id": 6,
    "level": "중",
    "category": "두 유한집합의 원소 개수 차",
    "originalCategory": "집합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-01",
    "standardUnit": "집합",
    "standardUnitOrder": 1,
    "subUnitKey": "H15-SB-01-SET_COUNT",
    "subUnit": "집합의 원소의 개수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "집합",
      "원소의 개수",
      "소수",
      "등차수열"
    ],
    "wide": false,
    "content": "두 집합 $A=\\{x\\mid x=2n+3,\\ n\\text{은 5 이하의 자연수}\\}$, $B=\\{x\\mid x\\text{는 10보다 작은 소수}\\}$에 대하여 $n(A)-n(B)$의 값은? [3점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|6",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-01-SET_COUNT",
    "problemTypeKey": "PT_SET_CARDINALITY",
    "templateKey": "TPL_SET_CARDINALITY_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ffc3b8fd949a4e0f15e51d1f1e9f4b578dba4f00a88468bc3c964c44303ce2c8"
  },
  {
    "id": 7,
    "level": "중",
    "category": "부등식으로 주어진 명제의 충분조건",
    "originalCategory": "명제",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-02",
    "standardUnit": "명제",
    "standardUnitOrder": 2,
    "subUnitKey": "H15-SB-02-NECESSARY_SUFFICIENT",
    "subUnit": "필요조건과 충분조건",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "명제",
      "필요조건",
      "충분조건",
      "부등식"
    ],
    "wide": false,
    "content": "실수 $x$에 대하여 두 조건 $p,q$가 다음과 같다. $p: 2x-10>0$, $q: x\\ge k$. $p$가 $q$이기 위한 충분조건이 되도록 하는 실수 $k$의 최댓값은? [3점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|7",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-02-NECESSARY_SUFFICIENT",
    "problemTypeKey": "PT_NEC_SUFF_RELATION",
    "templateKey": "TPL_NEC_SUFF_RELATION_FUNCTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:6283240d7a2df7e4516e9a3a18b740e372fb9578a8a5e01a500c3f620d1c7e31"
  },
  {
    "id": 8,
    "level": "중",
    "category": "모음이 양 끝에 오는 문자 순열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "문자 배열",
      "모음",
      "양 끝 조건"
    ],
    "wide": false,
    "content": "문자 $f,r,i,e,n,d$ 6개를 일렬로 나열할 때, 양 끝에 모음이 오도록 나열하는 모든 경우의 수는? [3점]",
    "choices": [
      "12",
      "24",
      "36",
      "48",
      "60"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|8",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:48a762dccc424dfe3a5f739b442f4184bf80c50d467ace32c5b7cd81669f1b0c"
  },
  {
    "id": 9,
    "level": "중",
    "category": "서로 다른 일차식으로 나눈 나머지 조건",
    "originalCategory": "나머지정리",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "subUnitKey": "H15-SA-02-REMAINDER_FACTOR",
    "subUnit": "나머지정리와 인수정리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "다항식",
      "나머지정리",
      "계수 조건"
    ],
    "wide": false,
    "content": "다항식 $P(x)=x^3+x^2+2$를 $x-a$, $x+a$로 나누었을 때 나머지를 각각 $R_1,R_2$라 하고 $R_1+R_2=8$이라 하자. $P(x)$를 $x-a^2$으로 나누었을 때 나머지는? (단, $a$는 상수) [3.5점]",
    "choices": [
      "0",
      "2",
      "8",
      "14",
      "16"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|9",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-02-REMAINDER_FACTOR",
    "problemTypeKey": "PT_H1_REMAINDER_THEOREM",
    "templateKey": "TPL_H1_REMAINDER_COMPOSITE_DIVISOR",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4459092ef3697560c7c59f026dba55102f90b946afca630d9ae49534b8eaa4ed"
  },
  {
    "id": 10,
    "level": "중",
    "category": "매개변수 직선족이 지나는 고정점",
    "originalCategory": "직선의 방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-10",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 10,
    "subUnitKey": "H15-SA-10-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "직선의 방정식",
      "평행이동",
      "정점",
      "매개변수"
    ],
    "wide": false,
    "content": "직선 $(k+3)x-2y-8=0$을 $x$축의 방향으로 $-3$만큼 평행이동한 직선이 실수 $k$의 값에 관계없이 항상 지나는 점의 좌표를 $(a,b)$라 할 때, $a+b$의 값은? [3.5점]",
    "choices": [
      "-7",
      "-3",
      "1",
      "5",
      "9"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|10",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-10-LINE_EQUATION",
    "problemTypeKey": "PT_LINE_FAMILY_COMMON_POINT",
    "templateKey": "TPL_LINE_FAMILY_COMMON_POINT_APPLICATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:6a1f4b221f60b0e8fb131de7b06b667ac5a7d7a1bded0ad9d33bc55ed5e2ad7c"
  },
  {
    "id": 11,
    "level": "중",
    "category": "무리식이 정의되어 방정식을 만족하는 조건",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_BASIC",
    "subUnit": "무리함수의 뜻과 계산",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "정의역",
      "방정식",
      "매개변수 범위"
    ],
    "wide": false,
    "content": "집합 $A=\\{x\\mid ax+1=2\\sqrt{-x-2}\\}$에 대하여 $A\\ne\\varnothing$이기 위한 실수 $a$의 값의 범위는? [3.5점]",
    "choices": [
      "$-2\\le a\\le1$",
      "$-2\\le a\\le-\\dfrac12$",
      "$-\\dfrac12\\le a\\le\\dfrac12$",
      "$-\\dfrac12\\le a\\le2$",
      "$\\dfrac12\\le a\\le1$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|11",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_BASIC",
    "problemTypeKey": "PT_DOMAIN_RANGE_SURJECTIVITY",
    "templateKey": "TPL_FUNCTION_DOMAIN_RANGE_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e0e82097f3afc52336ecc7d9a44df8ede4d9d06dee621be2c34de35c01ce4e26"
  },
  {
    "id": 12,
    "level": "중",
    "category": "네 사람의 선물 교환에서 모두 다른 선물을 받는 경우",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "선물 교환",
      "고정점 없는 순열"
    ],
    "wide": false,
    "content": "$A,B,C,D$ 네 사람이 각자 선물을 하나씩 준비하여 상자에 넣고 임의로 하나씩 집었을 때, 네 사람 모두가 서로 다른 사람이 준비한 선물을 집는 경우의 수는? [3.5점]",
    "choices": [
      "6",
      "9",
      "12",
      "15",
      "24"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|12",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:21dc2975b542b6d6a42029b2358cc3e1880f87f368329c27143126027c2289e2"
  },
  {
    "id": 13,
    "level": "중",
    "category": "직육면체의 모서리 길이와 공간대각선으로 겉넓이 구하기",
    "originalCategory": "입체도형",
    "standardCourse": "수학(상)",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "직육면체",
      "모서리 길이",
      "공간대각선",
      "겉넓이"
    ],
    "wide": false,
    "content": "모든 모서리 길이의 합이 20인 직육면체 $ABCD-EFGH$가 있다. $\\overline{AG}=\\sqrt{13}$일 때, 직육면체 $ABCD-EFGH$의 겉넓이는? [4점]",
    "choices": [
      "10",
      "12",
      "14",
      "16",
      "18"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_강남여고_2학기_기말_고1_기출/q013_visual.png",
    "visualAsset": "assets/images/19_강남여고_2학기_기말_고1_기출/q013_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1360,
      "y1": 285,
      "x2": 1715,
      "y2": 525
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|13",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_강남여고_2학기_기말_고1_기출/q013_visual.png",
      "assetSha256": "sha256:3be6dfcf7f443c60ee6822a95990e162789e19ed037b8d280f245c229c449006",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
      "sourceQuestionNo": "13",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 1360,
        "y1": 285,
        "x2": 1715,
        "y2": 525
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 355,
      "naturalHeight": 240,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:64f83beed724f4b0c113b5056c4344d63c2d9975cae2487fe40d7d7ce01be825"
  },
  {
    "id": 14,
    "level": "중",
    "category": "조건을 만족하는 부분집합의 개수 차",
    "originalCategory": "집합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-01",
    "standardUnit": "집합",
    "standardUnitOrder": 1,
    "subUnitKey": "H15-SB-01-SET_COUNT",
    "subUnit": "집합의 원소의 개수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "집합",
      "부분집합",
      "원소의 개수",
      "포함·제외 조건"
    ],
    "wide": false,
    "content": "집합 $A=\\{x\\mid 0\\le x\\le10,\\ x\\text{는 정수}\\}$의 부분집합 중 원소 $0,1$을 포함하는 집합의 개수를 $m$, 원소 $1,2,3$을 포함하지 않는 집합의 개수를 $n$이라 할 때, $m-n$의 값은? [4점]",
    "choices": [
      "64",
      "128",
      "256",
      "512",
      "1024"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|14",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-01-SET_COUNT",
    "problemTypeKey": "PT_SET_CARDINALITY",
    "templateKey": "TPL_SET_CARDINALITY_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d12534b143861f0a8c50caf887026137aaab77fb16d1fe8ad51ef9eda986d59e"
  },
  {
    "id": 15,
    "level": "중",
    "category": "절댓값 등식으로 정의한 명제의 필요·충분조건",
    "originalCategory": "명제",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-02",
    "standardUnit": "명제",
    "standardUnitOrder": 2,
    "subUnitKey": "H15-SB-02-NECESSARY_SUFFICIENT",
    "subUnit": "필요조건과 충분조건",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "명제",
      "필요조건",
      "충분조건",
      "절댓값"
    ],
    "wide": false,
    "content": "두 실수 $a,b$에 대하여 세 조건 $p,q,r$는 다음과 같다.\n$p: |a|+|b|=0$\n$q: a^2-2ab+b^2=0$\n$r: |a+b|=|a-b|$\n옳은 것만을 보기에서 있는 대로 고른 것은? [4점]\n[보기]\nㄱ. $p$는 $q$이기 위한 충분조건이다.\nㄴ. $\\sim p$는 $\\sim r$이기 위한 필요조건이다.\nㄷ. $q$이고 $r$은 $p$이기 위한 필요충분조건이다.",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄴ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|15",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-02-NECESSARY_SUFFICIENT",
    "problemTypeKey": "PT_NEC_SUFF_RELATION",
    "templateKey": "TPL_NEC_SUFF_RELATION_FUNCTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:03aedfded14167e9d2acd4586d265df5a30ad4c50e09b613022ce5776f4b7d69"
  },
  {
    "id": 16,
    "level": "중",
    "category": "유한집합 사이의 고정점 없는 일대일대응 개수",
    "originalCategory": "함수의 개수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "일대일대응",
      "함수의 개수",
      "고정점",
      "유한집합"
    ],
    "wide": false,
    "content": "집합 $A=\\{1,2,3,4\\}$에서 집합 $B=\\{3,4,5,6\\}$으로의 일대일대응 $f$ 중 정의역에 속하는 모든 $x$에 대하여 $f(x)\\ne x$인 것의 개수는? [4점]",
    "choices": [
      "14",
      "16",
      "18",
      "20",
      "22"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|16",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTION_COUNTING",
    "templateKey": "TPL_CONSTRAINED_FUNCTION_COUNT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a28e4e164f82bfab957ff6ac6eeaf3735183d1e02f6a35100524ac0bfbbed17a"
  },
  {
    "id": 17,
    "level": "중",
    "category": "정해진 정의역을 공역으로 보내는 함수의 매개변수",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "함수",
      "정의역",
      "공역",
      "치역 조건",
      "매개변수"
    ],
    "wide": false,
    "content": "함수 $f(x)=\\begin{cases}x+3&(x\\le0)\\x+a&(x>0)\\end{cases}$가 집합 $X=\\{-2,-1,0,1,2\\}$에서 집합 $Y=\\{1,2,3,5,6,7,8\\}$로의 함수가 되도록 하는 정수 $a$의 개수는? [4.5점]",
    "choices": [
      "4",
      "5",
      "6",
      "7",
      "8"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|17",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_DOMAIN_RANGE_SURJECTIVITY",
    "templateKey": "TPL_FUNCTION_DOMAIN_RANGE_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f2d93cc3073dd9711352dda30d68e5f354629776d2e0ee5a95203a1729a6a05b"
  },
  {
    "id": 18,
    "level": "중",
    "category": "함수 그래프와 y=x의 교점 및 역함수 조건",
    "originalCategory": "함수의 그래프",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "함수 그래프",
      "고정점",
      "역함수",
      "교점 조건"
    ],
    "wide": false,
    "content": "그림과 같은 그래프를 갖는 함수 $y=f(x)$가 있다. 함수 $f$는 일대일대응이고 방정식 $f(x)=x$를 만족하는 $x$가 $-2,1$이다. 이때 함수 $f$의 역함수를 $g$라 할 때, 방정식 $(3-x)g(3-x)=g(3-x)f(3-x)$를 만족하는 서로 다른 $x$값의 합은? [4.5점]",
    "choices": [
      "5",
      "7",
      "8",
      "9",
      "11"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_강남여고_2학기_기말_고1_기출/q018_visual.png",
    "visualAsset": "assets/images/19_강남여고_2학기_기말_고1_기출/q018_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 540,
      "y1": 1360,
      "x2": 880,
      "y2": 1745
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|18",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_강남여고_2학기_기말_고1_기출/q018_visual.png",
      "assetSha256": "sha256:1a3a1f88b679fa031423faf2efc72e1da2fa2d4d6c9f19307666c1dcbc033ce1",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
      "sourceQuestionNo": "18",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 540,
        "y1": 1360,
        "x2": 880,
        "y2": 1745
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 340,
      "naturalHeight": 385,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTION_GRAPH_INTERSECTION",
    "templateKey": "TPL_GRAPH_INTERSECTION_COUNT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:04c6c2a2470928a5ba6ebf2a015dc97dffb853faedb66e2554fdd805f6592233"
  },
  {
    "id": 19,
    "level": "중",
    "category": "유리함수 반복 적용의 주기",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "유리함수",
      "반복 적용",
      "주기"
    ],
    "wide": false,
    "content": "그림과 같이 $x$가 적힌 카드를 $A$에 넣었다가 꺼내면 $\\dfrac{x+1}{3x-1}$이 적힌 카드로 변하게 하는 상자가 있다. $\\dfrac12$이 적힌 카드를 $A$상자에 넣은 후 꺼냈다가 다시 변한 카드를 $A$상자에 넣는 과정을 2431번 반복하였다. 마지막으로 꺼낸 카드에 적힌 숫자는? (단, $x\\ne\\dfrac13$인 실수) [4.5점]",
    "choices": [
      "$\\dfrac14$",
      "1",
      "3",
      "5",
      "$9\\dfrac12$"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_강남여고_2학기_기말_고1_기출/q019_visual.png",
    "visualAsset": "assets/images/19_강남여고_2학기_기말_고1_기출/q019_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1405,
      "y1": 245,
      "x2": 1715,
      "y2": 550
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "19",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 19,
    "displayNo": "19",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|19",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_강남여고_2학기_기말_고1_기출/q019_visual.png",
      "assetSha256": "sha256:2b33df87275180afa5833aa5a57f57f5e823ef0f0f4f4e43bacba6e6526947dd",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
      "sourceQuestionNo": "19",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 1405,
        "y1": 245,
        "x2": 1715,
        "y2": 550
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 310,
      "naturalHeight": 305,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_ITERATED_COMPOSITION",
    "templateKey": "TPL_ITERATION_RULE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:61704c551861390e0b346b5317e81a24309fb3ba4e1808c2a3ac966f3f3554f1"
  },
  {
    "id": 20,
    "level": "중",
    "category": "제한된 동전으로 만들 수 있는 경우와 금액 수",
    "originalCategory": "조합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-08",
    "standardUnit": "조합",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-SB-08-COMBINATION_APPLICATION",
    "subUnit": "조합의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조합",
      "동전",
      "중복 제한",
      "금액의 개수"
    ],
    "wide": false,
    "content": "10원짜리 동전 2개, 50원짜리 동전 3개, 100원짜리 동전 2개, 500원짜리 동전 2개가 있다. 이들을 일부 또는 전부 사용하여 지불할 수 있는 경우의 수는 $a$이고, 이들을 일부 또는 전부 사용하여 지불할 수 있는 금액의 수는 $b$이다. $a+b$는? (단, 0원일 지불하는 것은 제외한다.) [4.5점]",
    "choices": [
      "105",
      "128",
      "156",
      "178",
      "205"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "20",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 20,
    "displayNo": "20",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|20",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-08-COMBINATION_APPLICATION",
    "problemTypeKey": "PT_COUNTING_SELECTION_DISTRIBUTION",
    "templateKey": "TPL_H1_SELECTION_CAPACITY_DISTRIBUTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7c3ad8711e12b8db773c90749d8f24f4b23c7c7df5caeffaebadf170989b6f62"
  },
  {
    "id": 21,
    "level": "중",
    "category": "조각함수의 전단사 조건과 매개변수 개수",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조각함수",
      "일대일대응",
      "치역",
      "정수 매개변수"
    ],
    "wide": false,
    "content": "정의역이 실수 전체의 집합 $\\mathbb R$인 함수 $f(x)=\\begin{cases}-\\sqrt{ax+6}+2a&(x\\le-\\dfrac6a)\\dfrac{cx+d}{x+b}&(x>-\\dfrac6a)\\end{cases}$가 다음 조건을 만족시키도록 하는 네 상수 $a,b,c,d$의 모든 순서쌍 $(a,b,c,d)$의 개수는? (단, $a\\ne0$)\n(가) $a,b,c,d$는 모두 $-14$ 이상이고 14 이하인 정수이다.\n(나) 함수 $f(x)$는 $\\mathbb R$에서 $\\mathbb R$로의 일대일대응이다. [5점]",
    "choices": [
      "2",
      "4",
      "6",
      "8",
      "10"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "21",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 21,
    "displayNo": "21",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|21",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_ONE_TO_ONE_BIJECTION",
    "templateKey": "TPL_PIECEWISE_RANGE_STITCH_BIJECTION",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_INTEGER"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:fd7e2809d4b0217af6ce68323987098d2954681a425eb8e79fd653a84c57af37"
  },
  {
    "id": 22,
    "level": "중",
    "category": "비밀번호 순서에서 자리 조건이 있는 순열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "비밀번호",
      "자리 조건",
      "소수",
      "짝수"
    ],
    "wide": false,
    "content": "1부터 9까지의 번호로 여는 자물쇠를 설치하여 번호를 정하려고 한다. 특정한 서로 다른 다섯 개의 숫자를 순서대로 누르면 자물쇠가 열리는데 다음과 같은 두 가지 정보를 이용하려면 최대 몇 번 누르면 열리는가?\n(가) 세 번째 번호는 짝수이다.\n(나) 첫 번째와 다섯 번째 번호는 소수이다. [5점]",
    "choices": [
      "1180",
      "1260",
      "1320",
      "1380",
      "1460"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "22",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 22,
    "displayNo": "22",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|22",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:982e4a50e0a1a6dc79cecebc7dc1ecebeffd9f2c4223d35b78e9695c14649860"
  },
  {
    "id": 23,
    "level": "중",
    "category": "함수 그래프 변환 조건으로 합성함수 역함수 구하기",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "역함수",
      "무리함수",
      "그래프 변환"
    ],
    "wide": false,
    "content": "함수 $y=-\\sqrt{ax}$의 그래프를 $x$축의 방향으로 $b$만큼, $y$축의 방향으로 3만큼 평행이동한 다음 $x$축에 대하여 대칭이동하면 함수 $y=\\sqrt{3x+6}+c$의 그래프와 일치한다. 이때 상수 $a,b,c$에 대하여 $a+b+c$의 값을 구하시오. (단, 풀이과정을 자세히 쓰시오.) [5점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "서술형1",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 23,
    "displayNo": "서술형1",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|서술형1",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_COMPOSITION",
    "templateKey": "TPL_INVERSE_COMPOSITION_FORMULA",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:20b5cd9e843aca8c9fe648de4c8aa308cab012e24da7049e648e018a0a9a480b"
  },
  {
    "id": 24,
    "level": "중",
    "category": "집합의 원소 개수로 대칭차의 개수 구하기",
    "originalCategory": "집합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-01",
    "standardUnit": "집합",
    "standardUnitOrder": 1,
    "subUnitKey": "H15-SB-01-SET_COUNT",
    "subUnit": "집합의 원소의 개수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "집합",
      "교집합",
      "여집합",
      "대칭차"
    ],
    "wide": false,
    "content": "전체집합 $U$의 두 부분집합 $A,B$에 대하여 $n(U)=50$, $n(A\\cap B)=12$, $n(A^c\\cap B^c)=5$일 때, $n((A-B)\\cup(B-A))$의 값을 구하시오. (단, 풀이과정을 자세히 쓰시오.) [7점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "서술형2",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 24,
    "displayNo": "서술형2",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|서술형2",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-01-SET_COUNT",
    "problemTypeKey": "PT_SET_CARDINALITY",
    "templateKey": "TPL_SET_CARDINALITY_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:382376ca6c53d968435cfdfe851cfc70ce689f698658fc3d25abd6e48015de86"
  },
  {
    "id": 25,
    "level": "중",
    "category": "두 특정 인원의 포함·인접 여부에 따른 순열 비율",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "포함 조건",
      "인접 조건",
      "경우의 수"
    ],
    "wide": false,
    "content": "건욱이와 재형이를 포함한 8명 중에서 4명을 뽑아 일렬로 줄을 세우려고 할 때, 건욱이와 재형이가 모두 포함되지 않는 경우의 수를 $a$, 두 사람 중 한 명만 포함된 경우의 수를 $b$, 두 사람이 모두 포함되어 있으며 서로 인접하여 있는 경우의 수를 $c$라 할 때, $\\dfrac{bc}{a}$의 값을 구하시오. (단, 풀이과정을 자세히 쓰시오.) [8점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_강남여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_강남고1_2기말.pdf",
    "sourceQuestionNo": "서술형3",
    "sourceArchiveFile": "original/high/h1/2final/19_강남여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 25,
    "displayNo": "서술형3",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717",
    "sourceIdentityKey": "sha256:de92e55e541bb0d823c9a98a8d2868d8dc33391d3cf99f0c92c7e8f382580717|서술형3",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_강남여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5c38d077373da5553fb4c81c67f86227770d7d521d8e94d201f097f4b9099812"
  }
];
