window.examTitle = "19_팔마고_2학기_기말_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "항등함수와 상수함수의 함수값",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "항등함수",
      "상수함수",
      "함수값"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 정의된 두 함수 $f,g$에 대하여 $f$는 항등함수이고, $g$는 상수함수이다. $f(3)=g(1)$일 때, $f(5)+g(5)$의 값은? [3.8점]",
    "choices": [
      "8",
      "10",
      "12",
      "14",
      "16"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:1310ab580ffbe787b24a5997fcfc63af21a14abfd8b47cc4b039ed998cec84cc"
  },
  {
    "id": 2,
    "level": "중",
    "category": "유한집합 사이의 함수가 아닌 대응",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "함수",
      "정의역",
      "공역",
      "함수의 정의"
    ],
    "wide": false,
    "content": "두 집합 $X=\\{-1,0,1,2\\}$, $Y=\\{0,1,2,3,4\\}$에 대하여 다음 중 $X$에서 $Y$로의 함수가 아닌 것은? [3.9점]",
    "choices": [
      "$y=x^2-1$",
      "$y=x+2$",
      "$y=|2x|$",
      "$y=x^2$",
      "$y=|x|+1$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTION_DEFINITION_JUDGMENT",
    "templateKey": "TPL_FUNCTION_JUDGMENT_MAPPING",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:0df3bf147a0c89d01ae0cd0dbef620240117d5495f3924b1ca7edd8945e5115c"
  },
  {
    "id": 3,
    "level": "중",
    "category": "일차함수와 역함수의 함수값",
    "originalCategory": "역함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-INVERSE_FUNCTION",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "일차함수",
      "역함수",
      "함수값"
    ],
    "wide": false,
    "content": "함수 $f(x)=ax+b$에 대하여 $f(-1)=-7$, $f^{-1}(1)=3$일 때, $a+b$의 값은? [4점]",
    "choices": [
      "-5",
      "-4",
      "-3",
      "-2",
      "-1"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-INVERSE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_VALUE",
    "templateKey": "TPL_INVERSE_VALUE_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:34c7aa75c9b596fb4845adc5ecd4f06cdb94d3fa58a5aa0b2c9a9eab827ad78b"
  },
  {
    "id": 4,
    "level": "중",
    "category": "무리함수의 정의역과 치역",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_BASIC",
    "subUnit": "무리함수의 뜻과 계산",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "정의역",
      "치역"
    ],
    "wide": false,
    "content": "무리함수 $y=-\\sqrt{1-x}-3$의 정의역이 $\\{x\\mid x\\le a\\}$, 치역이 $\\{y\\mid y\\le b\\}$일 때, $a+b$의 값은? [4.1점]",
    "choices": [
      "-5",
      "-4",
      "-3",
      "-2",
      "-1"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_BASIC",
    "problemTypeKey": "PT_DOMAIN_RANGE_SURJECTIVITY",
    "templateKey": "TPL_FUNCTION_DOMAIN_RANGE_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:24cd180a305e2b866eb50a282128be73c3a691a49eb62a2df7e1b022b68c4d5d"
  },
  {
    "id": 5,
    "level": "중",
    "category": "가중합 부등식을 만족하는 자연수 순서쌍의 개수",
    "originalCategory": "경우의 수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-06",
    "standardUnit": "경우의 수",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "subUnit": "경우의 수의 기본 원리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "자연수",
      "순서쌍",
      "부등식",
      "경우의 수"
    ],
    "wide": false,
    "content": "$5x+y+3z\\le15$를 만족시키는 자연수 $x,y,z$의 순서쌍 $(x,y,z)$의 개수를 구하시오. [4.2점]",
    "choices": [
      "11",
      "13",
      "14",
      "15",
      "16"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|5",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "problemTypeKey": "PT_H1_COUNTING_PRINCIPLE_GENERAL",
    "templateKey": "TPL_H1_COUNTING_DIRECT_CASE",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5ba9c4ce81a2cf25fb56a74ad4fba3185664bed1b43f1dcceb4bccdc85d4b2cd"
  },
  {
    "id": 6,
    "level": "중",
    "category": "세 여학생이 연속해 문을 지나는 배열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "일렬 배열",
      "연속 조건",
      "여학생"
    ],
    "wide": false,
    "content": "남학생 4명, 여학생 3명이 한 명씩 출입문을 지날 때, 여학생 3명이 연속적으로 출입문을 지나는 경우의 수를 구하시오. [4.2점]",
    "choices": [
      "360",
      "720",
      "1440",
      "2530",
      "4320"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|6",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:882d824bec0c7d05488aadf80ba11f70ec5f1c1b4ce3658ecc278be88e2f296c"
  },
  {
    "id": 7,
    "level": "중",
    "category": "남학생과 여학생의 최소 인원을 포함하는 대표 선출",
    "originalCategory": "조합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-08",
    "standardUnit": "조합",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-SB-08-COMBINATION_APPLICATION",
    "subUnit": "조합의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조합",
      "대표 선출",
      "포함 조건",
      "남학생",
      "여학생"
    ],
    "wide": false,
    "content": "남학생 3명과 여학생 5명으로 구성된 동아리에서 대표 5명을 뽑을 때, 적어도 남학생 1명과 여학생 2명은 포함하는 모든 경우의 수를 구하시오. [4.2점]",
    "choices": [
      "20",
      "35",
      "40",
      "55",
      "60"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|7",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-08-COMBINATION_APPLICATION",
    "problemTypeKey": "PT_COUNTING_SELECTION_DISTRIBUTION",
    "templateKey": "TPL_COMBINATION_SELECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:490e54307463c438d6d249ad520b85a87913574a842afcbec4aeb6c99e1d95a3"
  },
  {
    "id": 8,
    "level": "중",
    "category": "절댓값을 포함한 일대일함수의 매개변수",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "절댓값",
      "일대일함수",
      "매개변수",
      "최솟값"
    ],
    "wide": false,
    "content": "함수 $f(x)=3x+a|x+2|-1$이 일대일대응이 되도록 하는 정수 $a$의 최솟값은? [4.3점]",
    "choices": [
      "-2",
      "-1",
      "0",
      "1",
      "2"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|8",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_ONE_TO_ONE_BIJECTION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:cb51c84db4d3945d546c70a3e11f6e4dbdd975f9b08cb20eb6a07063c690efd1"
  },
  {
    "id": 9,
    "level": "중",
    "category": "역함수 그래프 도식으로 두 번 합성한 값",
    "originalCategory": "역함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-INVERSE_FUNCTION",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "역함수",
      "그래프",
      "함수값",
      "합성"
    ],
    "wide": false,
    "content": "두 함수 $y=f(x)$와 $y=x$의 그래프가 그림과 같고 함수 $f$의 역함수가 존재할 때, $(f^{-1}\\circ f^{-1})(b)$의 값은? [4.3점]",
    "choices": [
      "a",
      "b",
      "c",
      "d",
      "e"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_팔마고_2학기_기말_고1_기출/q009_visual.png",
    "visualAsset": "assets/images/19_팔마고_2학기_기말_고1_기출/q009_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 340,
      "y1": 340,
      "x2": 740,
      "y2": 730
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|9",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 0.93,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_팔마고_2학기_기말_고1_기출/q009_visual.png",
      "assetSha256": "sha256:02ad0d77c2d02269657f823b96e11a3a847595fdd1fa38c8b0dd5c0e39edc52f",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
      "sourceQuestionNo": "9",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 340,
        "y1": 340,
        "x2": 740,
        "y2": 730
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 400,
      "naturalHeight": 390,
      "cropStatus": "MANUAL_PIXEL_REVIEW_PASS",
      "verdict": "PASS",
      "checks": {
        "CROP_PURITY": true,
        "NO_OTHER_QUESTION_TEXT": true,
        "NO_CHOICES_CONTAMINATION": true,
        "NO_PAGE_BORDER_CONTAMINATION": true,
        "NO_CLIPPING": true,
        "REQUIRED_LABELS_PRESENT": true,
        "QUESTION_SEMANTIC_MATCH": true
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-INVERSE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_COMPOSITION",
    "templateKey": "TPL_INVERSE_COMPOSITION_VALUE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:65dc4ec0ace1b181896cbb0ce660c8dab7b71f3d6ac173d7c94ce07bac4359fe"
  },
  {
    "id": 10,
    "level": "중",
    "category": "유한집합 위 함수의 거듭제곱 반복",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "함수의 반복",
      "유한집합",
      "주기"
    ],
    "wide": false,
    "content": "집합 $X=\\{1,2,3\\}$에 대하여 함수 $f:X\\to X$는 그림과 같다. $f^1(x)=f(x)$, $f^{n+1}(x)=f(f^n(x))\\ (n=1,2,3,\\ldots)$로 정의할 때, $f^{150}(3)-f^{200}(3)$의 값은? [4.4점]",
    "choices": [
      "-2",
      "-1",
      "0",
      "1",
      "2"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_팔마고_2학기_기말_고1_기출/q010_visual.png",
    "visualAsset": "assets/images/19_팔마고_2학기_기말_고1_기출/q010_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 340,
      "y1": 1430,
      "x2": 700,
      "y2": 1740
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|10",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 0.93,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_팔마고_2학기_기말_고1_기출/q010_visual.png",
      "assetSha256": "sha256:536acf342470436335da3d73343713d53b3fc6815a0fe1e037d10824c4db7a87",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
      "sourceQuestionNo": "10",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 340,
        "y1": 1430,
        "x2": 700,
        "y2": 1740
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 360,
      "naturalHeight": 310,
      "cropStatus": "MANUAL_PIXEL_REVIEW_PASS",
      "verdict": "PASS",
      "checks": {
        "CROP_PURITY": true,
        "NO_OTHER_QUESTION_TEXT": true,
        "NO_CHOICES_CONTAMINATION": true,
        "NO_PAGE_BORDER_CONTAMINATION": true,
        "NO_CLIPPING": true,
        "REQUIRED_LABELS_PRESENT": true,
        "QUESTION_SEMANTIC_MATCH": true
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_ITERATED_COMPOSITION",
    "templateKey": "TPL_ITERATION_PERIOD",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b74bda47cc019d0cfad90b782ed1e36bf5387047ae68819ba3f7366eadda983c"
  },
  {
    "id": 11,
    "level": "중",
    "category": "유리함수 그래프의 점근선·치역·사분면 성질",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "점근선",
      "치역",
      "사분면",
      "그래프 성질"
    ],
    "wide": false,
    "content": "함수 $y=\\dfrac{2x+5}{x-1}$에 대한 다음 설명 중 옳지 않은 것은? [4.4점]",
    "choices": [
      "그래프는 점 $(8,3)$을 지난다.",
      "그래프의 점근선의 방정식은 $x=1$, $y=2$이다.",
      "그래프는 제4사분면을 지나지 않는다.",
      "치역은 $y\\ne2$인 실수 전체의 집합이다.",
      "그래프를 평행이동하면 유리함수 $y=\\dfrac{5x+2}{x-1}$의 그래프와 겹쳐진다."
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|11",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_PROPERTIES",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:749b87ade2c8e738b77e027f0d902fee30c6a819dabf06340b545db8874a1c33"
  },
  {
    "id": 12,
    "level": "중",
    "category": "유리함수 그래프에서 유도한 무리함수 그래프의 개형",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "무리함수",
      "그래프",
      "그래프의 개형",
      "평행이동"
    ],
    "wide": false,
    "content": "함수 $y=\\dfrac{bx+c}{x+a}$의 그래프가 그림과 같을 때, 함수 $y=\\sqrt{cx+b}+a$의 그래프의 개형으로 알맞은 것은? (단, $a,b,c$는 상수이다.) [4.5점]",
    "choices": [
      "①",
      "②",
      "③",
      "④",
      "⑤"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/19_팔마고_2학기_기말_고1_기출/q012_visual.png",
    "visualAsset": "assets/images/19_팔마고_2학기_기말_고1_기출/q012_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 905,
      "y1": 1450,
      "x2": 1680,
      "y2": 2280
    },
    "visualAssetStatus": "manual_source_component_composite_pixel_review_pass",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|12",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png",
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.97,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 0.93,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/19_팔마고_2학기_기말_고1_기출/q012_visual.png",
      "assetSha256": "sha256:f972406a3266244fbb359f08685f9bf54a5ddfeac1db8c24521eddc9b21ecc2e",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
      "sourceQuestionNo": "12",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png",
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 905,
        "y1": 1450,
        "x2": 1680,
        "y2": 2280
      },
      "cropGenerator": "source-page-component-composite",
      "pngDecodePass": true,
      "naturalWidth": 775,
      "naturalHeight": 1539,
      "cropStatus": "MANUAL_PIXEL_REVIEW_PASS_SOURCE_COMPONENT_COMPOSITE",
      "verdict": "PASS",
      "checks": {
        "CROP_PURITY": true,
        "NO_OTHER_QUESTION_TEXT": true,
        "NO_CHOICES_CONTAMINATION": true,
        "NO_PAGE_BORDER_CONTAMINATION": true,
        "NO_CLIPPING": true,
        "REQUIRED_LABELS_PRESENT": true,
        "QUESTION_SEMANTIC_MATCH": true,
        "MULTIPAGE_SOURCE_COMPONENTS_VERIFIED": true
      },
      "sourceComponents": [
        {
          "pageNo": 3,
          "path": "pages/page_p003.png",
          "sha256": "sha256:479a0848320e88cd763f3a66bc9b5259943d2e421a920ed66ceef493eb1dd539",
          "bbox": {
            "x1": 905,
            "y1": 1450,
            "x2": 1680,
            "y2": 2280
          },
          "role": "question12 main graph and graph choices 1-2"
        },
        {
          "pageNo": 4,
          "path": "pages/page_p004.png",
          "sha256": "sha256:3f676617599cd7b427f2f164a3ac0dde1e80977ca09171c8cb84be9fcff58b1c",
          "bbox": {
            "x1": 120,
            "y1": 245,
            "x2": 820,
            "y2": 930
          },
          "role": "question12 graph choices 3-5"
        }
      ]
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:9da43c61fd7a845037e0358fb84e815a9793d6b96c5eafcbf50df049b67ad039"
  },
  {
    "id": 13,
    "level": "중",
    "category": "두 고객의 음료·케이크 중복 선택 조건으로 n 구하기",
    "originalCategory": "경우의 수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-06",
    "standardUnit": "경우의 수",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "subUnit": "경우의 수의 기본 원리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "경우의 수",
      "곱의 법칙",
      "서로 다른 선택",
      "매개변수"
    ],
    "wide": false,
    "content": "서로 다른 $n$개의 음료수와 서로 다른 3개의 케이크를 파는 커피숍에서 현민이가 먼저 음료수와 케이크를 하나씩 주문하고 정현이는 현민이와 다른 음료수와 케이크를 하나씩 주문하는 경우의 수는 180이다. 이때, 자연수 $n$의 값은? [4.5점]",
    "choices": [
      "5",
      "6",
      "7",
      "8",
      "9"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|13",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "problemTypeKey": "PT_H1_COUNTING_PRINCIPLE_GENERAL",
    "templateKey": "TPL_H1_COUNTING_DIRECT_CASE",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:461d179b11d4e26ba00327b94668820acb59ef9d9daa7f29c66140f6ce44d339"
  },
  {
    "id": 14,
    "level": "중",
    "category": "제한된 동전으로 지불하는 방법과 금액 수의 차",
    "originalCategory": "조합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-08",
    "standardUnit": "조합",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-SB-08-COMBINATION_APPLICATION",
    "subUnit": "조합의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조합",
      "동전",
      "지불 방법",
      "금액의 개수",
      "중복 제한"
    ],
    "wide": false,
    "content": "100원짜리 동전 4개, 500원짜리 동전 4개, 1000원짜리 지폐 1장이 있을 때, 일부 또는 전부를 사용하여 지불할 수 있는 방법의 수를 $a$, 지불할 수 있는 금액의 수를 $b$라 할 때, $a-b$의 값은? [4.6점]",
    "choices": [
      "15",
      "16",
      "17",
      "18",
      "19"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|14",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-08-COMBINATION_APPLICATION",
    "problemTypeKey": "PT_COUNTING_SELECTION_DISTRIBUTION",
    "templateKey": "TPL_H1_SELECTION_CAPACITY_DISTRIBUTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:69e874ac7ed958a759397cf1596ce9ea148046b7d4de790bdccf58bd9281c0d5"
  },
  {
    "id": 15,
    "level": "중",
    "category": "숫자 선택과 자리 조건으로 3의 배수 만들기",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "세 자리 자연수",
      "숫자 선택",
      "3의 배수"
    ],
    "wide": false,
    "content": "5개의 숫자 $0,2,4,6,8$ 중에서 서로 다른 3개를 택하여 세 자리 자연수를 만들 때, 이 세 자리 자연수 중에서 3의 배수의 개수는? [5.1점]",
    "choices": [
      "20",
      "24",
      "28",
      "32",
      "36"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|15",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:cd022d0f2ad1c913a5c311117424fddd0c5d29b8f595982338ecedd21f4d3dd2"
  },
  {
    "id": 16,
    "level": "중",
    "category": "조각함수의 치역과 일대일 조건으로 함수값 결정",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조각함수",
      "치역",
      "일대일함수",
      "매개변수"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 정의된 함수 $f(x)=\\begin{cases}\\dfrac{x+1}{x-3}&(x>4)\\\\\\sqrt{4-x}+a&(x\\le4)\\end{cases}$가 다음 조건을 만족시킨다.\\n(가) 치역은 $\\{y\\mid y>1\\}$이다.\\n(나) 임의의 두 실수 $x_1,x_2$에 대하여 $f(x_1)=f(x_2)$이면 $x_1=x_2$이다.\\n$f(0)f(k)=14$일 때, 상수 $k$의 값을 구하시오. [5.1점]",
    "choices": [
      "5",
      "7",
      "9",
      "11",
      "13"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|16",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_DOMAIN_RANGE_SURJECTIVITY",
    "templateKey": "TPL_FUNCTION_DOMAIN_RANGE_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ccde4219cdae679cddd87783306fc1aeed98a349c0ff7249e5fd2fc2ae069184"
  },
  {
    "id": 17,
    "level": "중",
    "category": "역함수 조건으로 참인 명제 판단",
    "originalCategory": "역함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-INVERSE_FUNCTION",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "역함수",
      "함수 관계",
      "필요충분 조건",
      "명제"
    ],
    "wide": false,
    "content": "실수 전체의 집합 $\\mathbb R$에서 $\\mathbb R$로의 함수 $f(x)$의 역함수 $f^{-1}(x)$가 존재하고, 임의의 두 실수 $a,b$에 대하여 $f(ab)=f^{-1}(a)\\times f^{-1}(b)$가 성립할 때, 보기에서 옳은 것만을 있는 대로 고른 것은? [5.2점]\\nㄱ. $f(2)=2$이면 $f(1)=3$이다.\\nㄴ. $f^{-1}(a^2)=\\{f(a)\\}^2$이다.\\nㄷ. $f(a)=b$, $f(b)=a$이면 함수 $y=f(x)$의 그래프는 직선 $y=x$와 적어도 한 점에서 만난다.",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄷ",
      "ㄱ, ㄴ",
      "ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|17",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-INVERSE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_PROPERTIES",
    "templateKey": "TPL_INVERSE_PROPERTY_JUDGMENT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f669d404f6937da02d13809756a7b2edf89ddd6c2e5d58a59562e1e913d5d544"
  },
  {
    "id": 18,
    "level": "중",
    "category": "유한집합 위 함수의 대칭·증가 조건을 만족하는 개수",
    "originalCategory": "함수의 개수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유한집합",
      "함수의 개수",
      "증가 조건",
      "대칭 조건"
    ],
    "wide": false,
    "content": "집합 $X=\\{-3,-2,-1,0,1,2,3\\}$에 대하여 함수 $f:X\\to X$ 중 다음 조건을 만족시키는 함수 $f$의 개수를 구하시오.\\n(가) $f(-3)+f(3)=0$\\n(나) $f(-2)<f(-1)<f(0)<f(1)<f(2)$ [5.2점]",
    "choices": [
      "100",
      "116",
      "124",
      "135",
      "147"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|18",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.97,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTION_COUNTING",
    "templateKey": "TPL_MONOTONE_FUNCTION_COUNT",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_INTEGER"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c49235b93c295397640d7ac5b336c0ff09d420ed30445c62ff495a1ce37a7dd4"
  },
  {
    "id": 19,
    "level": "중",
    "category": "매개변수 조각함수의 합성값 관계",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "subjective-2up",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "조각함수",
      "매개변수",
      "방정식"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=x+a$, $g(x)=\\begin{cases}2x+17&(x<a)\\\\x^2&(x\\ge a)\\end{cases}$에 대하여 $(g\\circ f)(2)+(f\\circ g)(3)=63$을 만족시키는 모든 실수 $a$의 값을 구하시오. [7점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "서술형1",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 19,
    "displayNo": "서술형1",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|서술형1",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_COMPOSITION_EVALUATION",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:23a78faf66569e4f874a3efc877ae1fd98ef4bf89924c8b14d137d29b5ae6c16"
  },
  {
    "id": 20,
    "level": "중",
    "category": "유리함수와 무리함수 그래프의 두 교점 조건",
    "originalCategory": "함수의 그래프",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "subjective-2up",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "무리함수",
      "그래프의 교점",
      "매개변수 범위"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=\\dfrac{3x-2}{x-2}$, $g(x)=\\sqrt{x-k}-k$의 그래프가 서로 다른 두 점에서 만나도록 하는 실수 $k$의 값의 범위를 구하시오. [7점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "서술형2",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 20,
    "displayNo": "서술형2",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|서술형2",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_INTERSECTION",
    "templateKey": "TPL_FUNCTION_INTERSECTION_TWO_FUNCTIONS",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:023db70152c15c868968edcd3232773d6a943ee008140bcef0a107c312170198"
  },
  {
    "id": 21,
    "level": "중",
    "category": "짝수 숫자의 자리·인접 제한이 있는 네 자리 수 배열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "subjective-2up",
    "tags": [
      "기출",
      "고1",
      "순열",
      "네 자리 자연수",
      "짝수",
      "자리 조건",
      "인접 조건"
    ],
    "wide": false,
    "content": "6개의 숫자 $1,2,3,4,5,6$ 중 서로 다른 4개를 택해 일렬로 나열하여 네 자리 자연수를 만들려고 한다. 천의 자리의 수는 짝수이고 각 자리의 수 중 짝수끼리는 서로 이웃하지 않는 자연수의 개수를 구하시오. [6점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "19_팔마고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2019_팔마고1_2기말.pdf",
    "sourceQuestionNo": "서술형3",
    "sourceArchiveFile": "original/high/h1/2final/19_팔마고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 21,
    "displayNo": "서술형3",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a",
    "sourceIdentityKey": "sha256:4f5c58c3160beb3d445cc5bf60301a966f340d4a3d593bce7687435657ed007a|서술형3",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\19_팔마고_2학기_기말_고1_기출\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:54dd88d188f9b54ba22981bd3a16747073b87b4e80a47f74f6148f55b4b21bf4"
  }
];
