window.examTitle = "20_매산여고_2학기_기말_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "유한 정의역에서 같은 함수 조건",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "함수의 정의",
      "같은 함수",
      "유한 정의역",
      "계수 조건"
    ],
    "wide": false,
    "content": "정의역이 $\\{1,3\\}$인 두 함수 $f(x)=4x$, $g(x)=ax^2+b$에서 $f=g$가 성립할 때 $2a-b$의 값을 구하여라. [3.5점]",
    "choices": [
      "2",
      "1",
      "0",
      "-1",
      "-2"
    ],
    "answer": "④",
    "solution": "조건을 두 함수에 대입한다.\n$x=1$에서 $4=a+b$이고, $x=3$에서 $12=9a+b$이다.\n두 식을 빼면 $8=8a$이므로 $a=1$이다.\n따라서 $b=3$이고 $2a-b=2-3=-1$이다. 정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTION_EQUALITY",
    "templateKey": "TPL_EQUAL_FUNCTION_FINITE_DOMAIN",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f9f5591c948bd951f856389edc713641359ccfd3c9937b76adba45a24a510d67"
  },
  {
    "id": 2,
    "level": "중",
    "category": "곱셈형 함수방정식과 역함수 성질",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "함수방정식",
      "곱셈형",
      "역함수",
      "참·거짓 판정"
    ],
    "wide": false,
    "content": "함수 $f$에 대하여 역함수 $f^{-1}$가 존재하고, 임의의 실수 $x,y$에 대하여 $f(x+y)=f(x)f(y)$를 만족시킬 때, 다음 보기 중 옳은 것을 모두 구하여라. (단, $f(x)>0$)\n(ㄱ) $f^{-1}(1)=0$\n(ㄴ) $f(1)=2$이면 $f(3)=9$\n(ㄷ) $f^{-1}(4)=1$이면 $16f(-2)=1$ [4.3점]",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "③",
    "solution": "먼저 곱셈 조건에 $x=y=0$을 대입하면 $f(0)=f(0)^2$이다. $f(0)>0$이므로 $f(0)=1$이다.\n**ㄱ.** $f(0)=1$이고 역함수가 있으므로 1의 원상은 0 하나뿐이다. 따라서 $f^{-1}(1)=0$이다. 참.\n**ㄴ.** $f(3)=f(1+1+1)=f(1)^3=2^3=8$이다. 9가 아니므로 거짓.\n**ㄷ.** $f^{-1}(4)=1$은 $f(1)=4$라는 뜻이다. 그러면 $f(2)=f(1)^2=16$이고, $f(2)f(-2)=f(0)=1$에서 $f(-2)=1/16$이다. 따라서 $16f(-2)=1$이고 참이다.\n옳은 것은 ㄱ, ㄷ이므로 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTIONAL_EQUATION",
    "templateKey": "TPL_FUNCTIONAL_EQUATION_MULTIPLICATIVE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:1917dcc9a6f684ff25157ba29dacc4616c7733fcb96bc3a7ad5bd65378d4b0e9"
  },
  {
    "id": 3,
    "level": "중",
    "category": "정의역·치역 포함 조건에서 계수의 최댓값",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "정의역",
      "치역",
      "일차함수",
      "계수의 최댓값"
    ],
    "wide": false,
    "content": "두 집합 $X=\\{x\\mid 1\\le x\\le5\\}$, $Y=\\{y\\mid-2\\le y\\le3\\}$에 대하여 $X$에서 $Y$로의 함수 $f(x)=ax+b$가 $Y\\subset f(X)$를 만족하도록 하는 상수 $a,b$에 대하여 $|a-b|$의 값 중에서 최댓값을 구하여라. [4.2점]",
    "choices": [
      "$\\frac92$",
      "$\\frac{11}2$",
      "$\\frac{13}2$",
      "$\\frac{15}2$",
      "$\\frac{17}2$"
    ],
    "answer": "②",
    "solution": "$f$는 $X$에서 $Y$로 가므로 $f(X)\\subset Y$이다. 조건 $Y\\subset f(X)$도 있으므로 $f(X)=Y=[-2,3]$이다.\\n$x$가 1에서 5까지 변할 때 일차함수의 양 끝 함수값은 $-2,3$이어야 한다.\\n증가하는 경우에는 $a+b=-2$, $5a+b=3$이므로 $a=5/4$, $b=-13/4$이다. 이때 $|a-b|=18/4=9/2$이다.\\n감소하는 경우에는 $a+b=3$, $5a+b=-2$이므로 $a=-5/4$, $b=17/4$이다. 이때 $|a-b|=22/4=11/2$이다.\\n따라서 최댓값은 $11/2$이고 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_DOMAIN_RANGE_SURJECTIVITY",
    "templateKey": "TPL_FUNCTION_DOMAIN_RANGE_EXTREMUM",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5ce353b8f685f585f60ab2da59dedb04caff062e2e8c114b4455479480573b4d"
  },
  {
    "id": 4,
    "level": "하",
    "category": "합성함수 관계에서 함수값 구하기",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "함수값",
      "합성 관계"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=2x+1$, $g(x)=-2x+3$에 대하여 $h\\circ f=g$를 만족시키는 함수 $h(x)$가 존재할 때, $h(1)$의 값을 구하여라. [3.7점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "③",
    "solution": "$f(x)=2x+1$의 역함수는 $f^{-1}(y)=(y-1)/2$이다. $h(f(x))=g(x)$에서 $y=f(x)$로 두면 $h(y)=g(f^{-1}(y))$이다.\n따라서 $h(1)=g(f^{-1}(1))=g(0)=-2\\cdot0+3=3$이다. 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_COMPOSITION_EVALUATION",
    "templateKey": "TPL_COMPOSITION_VALUE_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c216a107d9b5827070a8bc8c1086108e24d69ae3a6154a32f985b7c11db05c2f"
  },
  {
    "id": 5,
    "level": "중",
    "category": "함수의 반복합성과 주기",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "반복합성",
      "함수의 주기",
      "그래프",
      "함숫값"
    ],
    "wide": false,
    "content": "집합 $X=\\{1,2,3,4\\}$에 대하여 함수 $f:X\\to X$가 있다. 함수 $y=f(x)$의 그래프가 그림과 같을 때, $f^1=f$, $f^2=f\\circ f^1$, $f^3=f\\circ f^2$, $\\cdots$, $f^{n+1}=f\\circ f^n$으로 정의하자. $f^{10}(2)+f^{100}(1)-f^{2020}(4)$를 구하여라. [4.1점]",
    "choices": [
      "-1",
      "0",
      "1",
      "2",
      "3"
    ],
    "answer": "⑤",
    "solution": "그림에서 $f(1)=4$, $f(2)=2$, $f(3)=1$, $f(4)=3$이다.\n$2$는 고정점이므로 $f^{10}(2)=2$이다.\n$1\\to4\\to3\\to1$은 길이 3인 순환이다. $100=3\\cdot33+1$이므로 $f^{100}(1)=f(1)=4$이다. 또 $2020=3\\cdot673+1$이므로 $f^{2020}(4)=f(4)=3$이다.\n따라서 $2+4-3=3$이고 정답은 ⑤이다.",
    "image": "assets/images/20_매산여고_2학기_기말_고1_기출/q005_visual.png",
    "visualAsset": "assets/images/20_매산여고_2학기_기말_고1_기출/q005_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 255,
      "y1": 450,
      "x2": 705,
      "y2": 835
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|5",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_매산여고_2학기_기말_고1_기출/q005_visual.png",
      "assetSha256": "sha256:07ff4549ac8ddc0ff5819d7231f1a8555cf2f0c4b2456499c49c4f8f6dcee376",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
      "sourceQuestionNo": "5",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 255,
        "y1": 450,
        "x2": 705,
        "y2": 835
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 450,
      "naturalHeight": 385,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_ITERATED_COMPOSITION",
    "templateKey": "TPL_ITERATION_RULE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:eae460a972d6ad7099a0e4a6f4f4ad6fe437e969800f26f651947abf95b7882f"
  },
  {
    "id": 6,
    "level": "중",
    "category": "역함수와 합성함수 관계에서 함수값 구하기",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "역함수",
      "항등함수",
      "함수값"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 정의된 세 함수 $f,g,h$에 대하여 $f(x)=\\frac12x-3$, $g(x)=3x+1$이고, 합성함수 $g^{-1}\\circ h\\circ f$가 항등함수일 때, $h(0)+h(1)$의 값을 구하여라. [4.4점]",
    "choices": [
      "42",
      "44",
      "46",
      "48",
      "50"
    ],
    "answer": "②",
    "solution": "$g^{-1}\\circ h\\circ f$가 항등함수이므로 양변에 $g$를 합성하면 $h(f(x))=g(x)$이다.\n$f^{-1}(y)=2y+6$이므로 $h(y)=g(f^{-1}(y))=3(2y+6)+1=6y+19$이다.\n따라서 $h(0)=19$, $h(1)=25$이고 합은 44이다. 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|6",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_COMPOSITION",
    "templateKey": "TPL_INVERSE_CONJUGATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:593ef37cf5e59d8599dc6b03dbd1a91132a48ccb6be90b3ce78b92924c01700a"
  },
  {
    "id": 7,
    "level": "중",
    "category": "정의역 제한으로 이차함수의 일대일성 판단",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "일대일함수",
      "역함수 존재",
      "이차함수",
      "정의역 제한"
    ],
    "wide": false,
    "content": "집합 $X=\\{x\\mid x\\ge a\\}$에 대하여 $X$에서 $X$로의 함수 $f(x)=x^2-4x-6$의 역함수가 존재할 때, 상수 $a$의 값을 구하여라. [4.3점]",
    "choices": [
      "-6",
      "-3",
      "0",
      "3",
      "6"
    ],
    "answer": "⑤",
    "solution": "$f(x)=(x-2)^2-10$은 $x=2$를 축으로 하는 포물선이다. $a<2$이면 정의역에 2의 양쪽 값이 들어가므로 $f(2-t)=f(2+t)$인 서로 다른 두 입력이 생겨 일대일이 아니다. 따라서 $a\\ge2$이다.\\n함수가 $X=[a,\\infty)$에서 $X$로 가고 역함수가 존재하려면 치역이 $X$ 전체여야 한다. $a\\ge2$일 때 최솟값은 $f(a)$이므로 $f(a)=a$이다.\\n$(a-2)^2-10=a$를 풀면 $a^2-5a-6=0$, 즉 $(a-6)(a+1)=0$이다. $a\\ge2$를 만족하는 값은 $a=6$이다. 정답은 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|7",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_ONE_TO_ONE_BIJECTION",
    "templateKey": "TPL_QUADRATIC_DOMAIN_BIJECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:31ebb6fabe66507fbb995d614d3b23865bd8f41e78894e052f17f50e2e18cd35"
  },
  {
    "id": 8,
    "level": "중",
    "category": "유리함수 그래프와 무리함수 사분면 관계",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "무리함수",
      "그래프",
      "사분면",
      "매개변수 관계"
    ],
    "wide": false,
    "content": "유리함수 $y=\\frac{bx+c}{x+a}$의 그래프가 그림과 같을 때, 무리함수 $y=a\\sqrt{-x+b}+c$의 그래프가 지나는 사분면을 구하여라. (단, $a,b,c$는 상수) [3.8점]",
    "choices": [
      "제 1사분면",
      "제 3사분면",
      "제 1, 2사분면",
      "제 3, 4사분면",
      "제 1, 3, 4사분면"
    ],
    "answer": "④",
    "solution": "그래프의 수직점근선은 $x=-a$이고 양수 쪽에 있으므로 $a<0$이다. 수평점근선은 $y=b$이고 $x$축 위에 있으므로 $b>0$이다. 그래프의 $y$절편은 수평점근선보다 위에 있어 $c/a>b>0$이다. $a<0$이므로 $c<0$이다.\n무리함수 $y=a\\sqrt{-x+b}+c$의 정의역은 $x\\le b$이다. 제곱근은 0 이상이고 $a,c$가 모두 음수이므로 함수값은 항상 음수이다. 또한 $b>0$이므로 정의역에는 양수와 음수가 모두 있다.\n따라서 그래프는 제3, 제4사분면을 지나며 정답은 ④이다.",
    "image": "assets/images/20_매산여고_2학기_기말_고1_기출/q008_visual.png",
    "visualAsset": "assets/images/20_매산여고_2학기_기말_고1_기출/q008_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 1125,
      "y1": 1570,
      "x2": 1590,
      "y2": 1960
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|8",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_매산여고_2학기_기말_고1_기출/q008_visual.png",
      "assetSha256": "sha256:111dc44cc42f9aae359cab0ff96b620da66a28673c8f5522f2a304fdac526e71",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
      "sourceQuestionNo": "8",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 1125,
        "y1": 1570,
        "x2": 1590,
        "y2": 1960
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 465,
      "naturalHeight": 390,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_QUADRANT",
    "templateKey": "TPL_FUNCTION_QUADRANT_FROM_OTHER_FUNCTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d65b1f199afdd1f0b5674cc8873be96675fbc44147d730985a371804039840e0"
  },
  {
    "id": 9,
    "level": "상",
    "category": "유리함수 그래프의 대칭 직선",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "그래프의 대칭",
      "직선",
      "계수 관계"
    ],
    "wide": false,
    "content": "유리함수 $y=\\frac{3-4x}{2x+1}$의 그래프가 두 직선 $y=ax+b$, $y=cx+d$에 대하여 대칭일 때, $ad-bc$의 값을 구하여라. (단, $a,b,c,d$는 상수이고, $a>c$이다.) [4.0점]",
    "choices": [
      "0",
      "-1",
      "-2",
      "-3",
      "-4"
    ],
    "answer": "⑤",
    "solution": "유리함수를 나누어 쓰면 $y=-2+\\dfrac{7}{2x+1}$이다. 따라서 $(x+1/2)(y+2)=7/2$이다. $X=x+1/2$, $Y=y+2$로 두면 $XY=7/2$이다. 이 식은 $X,Y$를 서로 바꾸어도 변하지 않고, $(X,Y)$를 $(-Y,-X)$로 바꾸어도 곱은 $XY$로 같다. 따라서 두 대칭축은 $Y=X$, $Y=-X$이다. 원래 좌표로는 $y=x-3/2$, $y=-x-5/2$이다.\\n두 기울기 중 큰 값이 $a$이므로 $a=1$, $c=-1$이다. 따라서 $b=-3/2$, $d=-5/2$이고 $ad-bc=1\\cdot(-5/2)-(-3/2)(-1)=-4$이다. 정답은 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|9",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_PROPERTIES",
    "templateKey": "TPL_FUNCTION_GRAPH_SYMMETRY",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:3d32540dd00fb331e95bd67305e6360a47bd5ff1f4e9f856f203dae97f76c7a7"
  },
  {
    "id": 10,
    "level": "중",
    "category": "유리함수의 구간 최댓값과 최솟값",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_APPLICATION",
    "subUnit": "유리함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "점근선",
      "구간",
      "최댓값",
      "최솟값"
    ],
    "wide": false,
    "content": "유리함수 $y=\\frac{ax+b}{x+2}$의 그래프는 점 $(-1,0)$을 지나고, 직선 $y=3$는 이 그래프의 점근선 중 하나이다. $0\\le x\\le4$에서 이 함수의 최솟값을 $m$, 최댓값을 $M$이라 할 때, $m+M$의 값을 구하여라. (단, $a,b$는 상수) [4.0점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "④",
    "solution": "그래프가 $(-1,0)$을 지나므로 $(-a+b)/1=0$, 즉 $b=a$이다. 수평점근선은 $y=a$이므로 $a=3$, 따라서 $b=3$이다.\\n함수는 $f(x)=\\dfrac{3x+3}{x+2}=3-\\dfrac3{x+2}$이다. $0\\le x\\le4$에서 $x+2$가 커질수록 양수 $3/(x+2)$는 작아지므로 $f(x)$는 증가한다.\\n따라서 최솟값은 $f(0)=3/2$, 최댓값은 $f(4)=5/2$이다. $m+M=4$이고 정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|10",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_APPLICATION",
    "problemTypeKey": "PT_FUNCTION_EXTREMUM",
    "templateKey": "TPL_FUNCTION_EXTREMUM_INTERVAL_ENDPOINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4be1e9f21cfa31d2357ccb4c90e59a153e5c631ce96ba730bafd6d064f344aca"
  },
  {
    "id": 11,
    "level": "중",
    "category": "이웃 조건과 양 끝 조건이 있는 순열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "이웃 조건",
      "양 끝 조건",
      "경우의 수"
    ],
    "wide": false,
    "content": "$q,u,e,s,t,i,o,n$의 8개의 문자를 일렬로 나열할 때, $o$와 $e$ 또는 $o$와 $i$가 서로 이웃하고, $t$와 $n$이 양 끝에 오는 모든 경우의 수를 구하여라. [4.1점]",
    "choices": [
      "864",
      "866",
      "868",
      "870",
      "872"
    ],
    "answer": "①",
    "solution": "먼저 양 끝에 $t,n$을 놓는 순서는 $2!$가지이다. 가운데 여섯 자리에 $q,u,e,s,i,o$를 배열하되 $o$가 $e$ 또는 $i$와 이웃해야 한다.\n$o,e$를 한 묶음으로 보면 묶음 내부 순서는 2가지이고, 묶음과 나머지 네 글자의 배열은 $5!$가지이다. 따라서 $o,e$가 이웃하는 배열은 $2\\cdot5!$가지이다. $o,i$도 마찬가지로 $2\\cdot5!$가지이다.\n두 조건을 동시에 만족하면 세 글자가 $eoi$ 또는 $ioe$의 한 묶음이 된다. 이 경우는 $2\\cdot4!$가지이다. 포함배제에 따라 가운데 배열 수는 $2\\cdot5!+2\\cdot5!-2\\cdot4!=432$이다.\n전체는 $2\\cdot432=864$가지이므로 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|11",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a3a2a0641d6a834674b94b1fe6fa3ee22f329abea19749e28304bcdca73299c1"
  },
  {
    "id": 12,
    "level": "상",
    "category": "조각함수의 치역과 일대일 조건",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조각함수",
      "치역",
      "일대일함수",
      "유리함수",
      "무리함수"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 정의된 함수 $f(x)=\\begin{cases}\\dfrac{a-2x}{x-1}&(x>2)\\\\-\\sqrt{2-x}+2a&(x\\le2)\\end{cases}$일 때, 함수 $f$는 다음 조건을 만족시킨다. (단, $a$는 상수)\n(가) 치역은 $\\{y\\mid y<-2\\}$이다.\n(나) 함수 $f$는 일대일함수이다.\n$f(3)f(k)=50$일 때, 상수 $k$의 값을 구하여라. [4.6점]",
    "choices": [
      "-2",
      "-1",
      "0",
      "1",
      "2"
    ],
    "answer": "①",
    "solution": "왼쪽 가지 $x\\le2$의 값은 $-\\sqrt{2-x}+2a$이므로 치역은 $(-\\infty,2a]$이다. 오른쪽 가지는 $x>2$에서 $-2+(a-2)/(x-1)$이다. 전체 치역이 $y<-2$이려면 $a<2$이고, 이 가지의 치역은 $(a-4,-2)$이다.\n일대일이려면 두 가지 치역이 겹치지 않아야 한다. 또 합집합이 $(-\\infty,-2)$ 전체가 되려면 왼쪽 끝 $2a$와 오른쪽 가지의 시작값 $a-4$가 맞닿아야 한다. 따라서 $2a=a-4$, 즉 $a=-4$이다. 이때 치역은 $(-\\infty,-8]\\cup(-8,-2)=(-\\infty,-2)$로 조건을 만족한다.\n$f(3)=(-4-6)/(3-1)=-5$이므로 $f(3)f(k)=50$에서 $f(k)=-10$이다. 오른쪽 가지의 값은 $(-8,-2)$이므로 $k$는 왼쪽 가지에 있고, $-\\sqrt{2-k}-8=-10$에서 $k=-2$이다. 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|12",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_ONE_TO_ONE_BIJECTION",
    "templateKey": "TPL_PIECEWISE_RANGE_STITCH_BIJECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4c386441df864bb160ec323583d99968f9b4071ac38b22034577a1181ddcf039"
  },
  {
    "id": 13,
    "level": "상",
    "category": "유리함수·무리함수의 사분면 조건과 정수 매개변수",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "무리함수",
      "사분면",
      "정수 매개변수"
    ],
    "wide": false,
    "content": "유리함수 $y=\\frac{k}{x-3}+2$의 그래프가 모든 사분면을 지나고, 함수 $y=-\\sqrt{2x+k}+3$의 그래프가 제 1사분면, 제 2사분면, 제 4사분면을 지나도록 하는 정수 $k$의 개수를 구하여라. [4.3점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "②",
    "solution": "$y=\\dfrac{k}{x-3}+2$부터 본다. 모든 사분면을 지나려면 $k>0$이어야 한다. 실제로 $k\\le0$이면 $x<3$에서 $y\\ge2$라서 제3사분면에 들어갈 수 없다. $k>0$이면 오른쪽 가지는 제1사분면을, 왼쪽 가지는 제2사분면을 지난다. 제3사분면으로 들어가려면 $x<0$에서 $2+\\dfrac{k}{x-3}<0$이어야 한다. $y=0$이 되는 점은 $x=3-k/2$이므로 이 경계가 0보다 작아야 한다. 따라서 $k>6$이다. 이때 오른쪽 가지는 $x$가 3보다 조금 큰 곳에서 음수가 되어 제4사분면도 지난다.\\n다음 $y=-\\sqrt{2x+k}+3$이 제1사분면을 지나려면 $x>0$에서 $\\sqrt{2x+k}<3$인 점이 있어야 하므로 $k<9$이다. 제2사분면에는 $-k/2\\le x<0$인 정의역 구간이 있어야 하므로 $k>0$이다. 제4사분면은 $x$를 충분히 크게 잡으면 지난다. 따라서 이 함수의 조건은 $0<k<9$이다.\\n두 조건을 합치면 $6<k<9$이고 정수는 7, 8이다. 개수는 2이므로 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|13",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_QUADRANT",
    "templateKey": "TPL_FUNCTION_QUADRANT_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_INTEGER"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5782020c2148d3e92579f48619c9d757d6635e45c0e5be6c6fb5d131578fa646"
  },
  {
    "id": 14,
    "level": "상",
    "category": "첫째·마지막 조건이 있는 도착 순서",
    "originalCategory": "경우의 수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "도착 순서",
      "첫째·마지막 조건",
      "경우의 수"
    ],
    "wide": false,
    "content": "수학 행사장에는 $A$동아리 학생 2명과 $B$동아리 학생 4명이 각자 집에서 출발하기로 했다. 행사장에 2명 이상이 동시에 도착하는 경우가 없다고 할 때, 처음 또는 마지막에 $B$동아리 학생이 도착하는 모든 경우의 수를 구하여라. [3.6점]",
    "choices": [
      "668",
      "670",
      "672",
      "674",
      "676"
    ],
    "answer": "③",
    "solution": "동시에 도착하는 사람이 없으므로 여섯 학생의 도착 순서를 세면 된다. 전체 순서는 $6!=720$가지이다.\n처음 또는 마지막이 B인 경우의 여집합은 처음과 마지막이 모두 A인 경우이다. 두 A를 양 끝에 놓는 방법은 $2!$가지이고, 네 B를 가운데 놓는 방법은 $4!$가지이다.\n따라서 구하는 수는 $720-2!\\cdot4!=720-48=672$이다. 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|14",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:397c7bf11be1f34efc80cb46bb3604c06606b6db0aa21fd580ef80cb3fca3389"
  },
  {
    "id": 15,
    "level": "중",
    "category": "원 위의 점을 골라 삼각형 분류하기",
    "originalCategory": "조합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-08",
    "standardUnit": "조합",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-SB-08-COMBINATION_BASIC",
    "subUnit": "조합",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조합",
      "원 위의 점",
      "삼각형",
      "각의 분류"
    ],
    "wide": false,
    "content": "다음 그림과 같이 원 위에 있는 12개의 점 중에서 3개의 점을 꼭짓점으로 하여 삼각형을 만들 때, 직각삼각형의 개수를 $a$, 둔각삼각형의 개수를 $b$, 예각삼각형의 개수를 $c$라고 할 때, $a+b-c$의 값을 구하여라. [4.5점]",
    "choices": [
      "130",
      "140",
      "150",
      "160",
      "170"
    ],
    "answer": "②",
    "solution": "전체 삼각형은 $\\binom{12}{3}=220$개이다. 원의 지름 양 끝점을 빗변으로 하는 직각삼각형은 지름 6개마다 나머지 점 10개 중 하나를 고르므로 $a=6\\cdot10=60$개이다.\\n원이 12개의 같은 간격으로 나뉘므로 세 꼭짓점 사이의 간격을 칸 수로 세면 세 수의 합은 12이다. 둔각삼각형은 세 간격 중 하나가 6보다 클 때 생기며, 그런 간격은 하나뿐이다. 시작 꼭짓점을 정하면 큰 간격이 7,8,9,10칸일 수 있다. 7칸이면 나머지 두 양의 간격의 합은 5라 4가지, 이어서 8칸은 3가지, 9칸은 2가지, 10칸은 1가지이다. 따라서 $b=12(4+3+2+1)=120$개이다.\\n예각삼각형 수는 나머지이므로 $c=220-60-120=40$개이다. 따라서 $a+b-c=60+120-40=140$이고 정답은 ②이다.",
    "image": "assets/images/20_매산여고_2학기_기말_고1_기출/q015_visual.png",
    "visualAsset": "assets/images/20_매산여고_2학기_기말_고1_기출/q015_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1235,
      "y1": 440,
      "x2": 1505,
      "y2": 745
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|15",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_매산여고_2학기_기말_고1_기출/q015_visual.png",
      "assetSha256": "sha256:b621dcd1aa7dc3280b79748ce9cc6adcfcd51f58a49b27b020524c0be6227f66",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
      "sourceQuestionNo": "15",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 1235,
        "y1": 440,
        "x2": 1505,
        "y2": 745
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 270,
      "naturalHeight": 305,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-08-COMBINATION_BASIC",
    "problemTypeKey": "PT_COUNTING_SELECTION_DISTRIBUTION",
    "templateKey": "TPL_COMBINATION_SELECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:2d1808e7ecd62ca828424810aae3f600a9d9a7510a2401a1b6e0931ac9e11ab6"
  },
  {
    "id": 16,
    "level": "중",
    "category": "영역 인접 조건이 있는 색칠 경우의 수",
    "originalCategory": "경우의 수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-06",
    "standardUnit": "경우의 수",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "subUnit": "경우의 수의 기본 원리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "경우의 수",
      "색칠",
      "인접 조건",
      "그래프"
    ],
    "wide": false,
    "content": "오른쪽 그림의 4개의 영역 $A,B,C,D$를 서로 다른 4가지 색을 사용하여 칠하려고 한다. 같은 색을 중복하여 사용해도 좋으나 이웃한 영역에는 서로 다른 색을 칠할 때, 색칠한 결과로 나올 수 있는 모든 경우의 수를 구하여라. [4.2점]",
    "choices": [
      "36",
      "48",
      "60",
      "72",
      "84"
    ],
    "answer": "⑤",
    "solution": "그림에서 이웃한 영역은 $A$와 $B$, $B$와 $C$, $C$와 $D$, $D$와 $A$이다. 즉 네 영역의 이웃 관계는 순환한다.\n먼저 $A$의 색은 4가지이다. $B$와 $D$는 각각 $A$와 달라야 하므로 각각 3가지이다.\n$B,D$의 색이 같으면 $C$는 그 색과 달라야 하므로 3가지이다. 이 경우는 $3\\cdot3=9$가지이다. $B,D$의 색이 다르면 $C$는 두 색과 모두 달라야 하므로 2가지이고, 이 경우는 $3\\cdot2\\cdot2=12$가지이다.\n$A$ 색까지 포함하면 $4(9+12)=84$가지이다. 정답은 ⑤이다.",
    "image": "assets/images/20_매산여고_2학기_기말_고1_기출/q016_visual.png",
    "visualAsset": "assets/images/20_매산여고_2학기_기말_고1_기출/q016_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1517,
      "y1": 1305,
      "x2": 1760,
      "y2": 1560
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|16",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_매산여고_2학기_기말_고1_기출/q016_visual.png",
      "assetSha256": "sha256:9db9578d3b3e11f7c968f6458f6cf45deb8260046c0dddb32f9830a794eb7090",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
      "sourceQuestionNo": "16",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 1517,
        "y1": 1305,
        "x2": 1760,
        "y2": 1560
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 243,
      "naturalHeight": 255,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "problemTypeKey": "PT_H1_COUNTING_PRINCIPLE_GENERAL",
    "templateKey": "TPL_H1_COUNTING_GRAPH_PATH_COLOR",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:bd4ea82aceece25bd087834b299eb28bfb74fd71350004ebca251996a2244563"
  },
  {
    "id": 17,
    "level": "중",
    "category": "같은 문자가 있고 인접·양 끝 조건이 있는 순열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "같은 것이 있는 순열",
      "인접 금지",
      "문자 배열",
      "조건부 순열"
    ],
    "wide": false,
    "content": "8개의 $a$와 4개의 $b$를 모두 사용하여 만든 12자리 문자열 중에서 다음 조건을 모두 만족시키는 문자열의 개수를 구하여라. [4.4점]\n(가) $b$는 연속해서 나올 수 없다.\n(나) 첫째 자리의 문자가 $b$이면 마지막 자리의 문자는 $a$이다.",
    "choices": [
      "70",
      "105",
      "140",
      "175",
      "210"
    ],
    "answer": "②",
    "solution": "먼저 여덟 개의 $a$ 사이와 양 끝에 생기는 9개의 자리에 $b$를 하나씩 놓을 수 있다. 연속한 $b$를 막으려면 각 자리에 최대 하나를 놓으므로, 조건 (가)를 만족하는 문자열은 $\\binom94=126$개이다.\n첫째 자리가 $b$인 경우에는 마지막 자리가 $a$여야 하므로 양 끝 자리에 동시에 $b$가 있는 경우만 빼면 된다. 양 끝의 $b$를 놓고 나면 안쪽의 8개 자리 중 서로 이웃하지 않는 두 자리를 고른다. 방법 수는 $\\binom82-7=21$이다.\n따라서 조건을 모두 만족하는 문자열은 $126-21=105$개이다. 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|17",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_IDENTICAL_OBJECT_PERMUTATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:8730d60be1fbb5ed8ad0caf36a0752f469417fb866c5af3114840a57d5563620"
  },
  {
    "id": 18,
    "level": "중",
    "category": "역함수 그래프의 점근선",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "역함수",
      "점근선"
    ],
    "wide": false,
    "content": "함수 $f(x)=\\frac{2-3x}{x-5}$의 역함수를 $f^{-1}(x)$라 할 때, $y=f^{-1}(x)$의 그래프의 두 점근선을 구하여라. [5점]",
    "choices": [],
    "answer": "x=-3, y=5",
    "solution": "역함수 그래프의 식을 구하기 위해 $y=\\dfrac{2-3x}{x-5}$에서 $x,y$를 바꾼다.\n$x=\\dfrac{2-3y}{y-5}$이므로 $x(y-5)=2-3y$이다.\n$xy-5x=2-3y$에서 $y(x+3)=5x+2$이므로 $y=\\dfrac{5x+2}{x+3}$이다.\n분모가 0이 되는 $x=-3$이 수직점근선이고, 분자와 분모의 최고차항 계수 비가 5이므로 수평점근선은 $y=5$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식1",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 18,
    "displayNo": "주관식1",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식1",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_RATIONAL_ASYMPTOTE",
    "templateKey": "TPL_RATIONAL_ASYMPTOTE_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b87d1a14f7d640d558fbd7f4402cdd36c9dc85b7dfdc4811591a39b126e380e8"
  },
  {
    "id": 19,
    "level": "상",
    "category": "일대일 조건과 이웃한 함수값 차가 있는 함수의 개수",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "일대일함수",
      "함수의 개수",
      "함수값 차이",
      "유한집합"
    ],
    "wide": false,
    "content": "집합 $A$가 $A=\\{1,2,3,4,5,6\\}$일 때, $A$에서 $A$로의 함수 중 다음 조건을 모두 만족시키는 함수 $f$의 개수를 구하여라. [5점]\n(가) 정의역 $A$의 두 원소 $m,n$에 대하여 $m\\ne n$이면 $f(m)\\ne f(n)$이다.\n(나) 정의역 $A$의 오직 한 원소 $n$에 대하여 $f(n+1)-f(n)=4$이다.",
    "choices": [],
    "answer": "192",
    "solution": "조건을 만족하는 인접한 입력쌍을 $n,n+1$이라 하자. 함수가 일대일이므로 6개 원소의 순열이다. $f(n+1)-f(n)=4$가 되려면 $(f(n),f(n+1))$은 $(1,5)$ 또는 $(2,6)$ 두 가지이다.\n먼저 조건을 만족하는 $n$을 하나 표시해 세면 $5\\cdot2\\cdot4!=240$가지이다. 단, 한 순열이 조건을 두 번 만족하면 두 번 세었다. 연속한 두 쌍은 값이 4씩 연속 증가해야 하므로 1부터 6 안에서 불가능하다. 서로 겹치지 않는 두 쌍의 위치 선택은 다섯 인접쌍 중 6가지이고, 목표값 쌍 배치는 2가지, 남은 두 함수값 배치는 $2!$가지이다. 따라서 두 조건을 동시에 만족하는 순열은 $6\\cdot2\\cdot2=24$개이다. 세 번 만족하는 경우는 목표값 4개만으로 세 쌍을 만들 수 없어 없다.\n정확히 한 번 만족하는 순열 수는 $240-2\\cdot24=192$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식2",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 19,
    "displayNo": "주관식2",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식2",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTION_COUNTING",
    "templateKey": "TPL_CONSTRAINED_FUNCTION_COUNT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:19ecf95a6a3346717f16f944143f4460a68002c465016fa98a0cd74a772255d5"
  },
  {
    "id": 20,
    "level": "중",
    "category": "순열의 역순위",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_BASIC",
    "subUnit": "순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "사전식 순위",
      "역순위",
      "자연수"
    ],
    "wide": false,
    "content": "5개의 숫자 1, 3, 5, 7, 9를 모두 사용하여 만든 다섯 자리의 자연수를 큰 수부터 차례로 나열할 때, 50번째 수를 $a$라 하고 100번째 수를 $b$라 하자. $a-b$의 값을 구하여라. [6점] (부분점수 있음.)",
    "choices": [],
    "answer": "40176",
    "solution": "첫째 자리를 정하면 나머지 네 숫자는 $4!=24$가지로 배열된다. 큰 수부터 세면 첫째 자리가 9인 수가 1~24번째, 7인 수가 25~48번째, 5인 수가 49~72번째이다.\n따라서 50번째 수는 첫째 자리가 5인 묶음의 두 번째 수이다. 나머지를 내림차순으로 배열하면 처음 두 수는 59731, 59713이므로 $a=59713$이다.\n100번째 수는 첫째 자리가 1인 묶음의 네 번째 수이다. 나머지 9,7,5,3의 내림차순 순열 중 네 번째는 9537이므로 $b=19537$이다.\n따라서 $a-b=59713-19537=40176$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식3",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 20,
    "displayNo": "주관식3",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식3",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-07-PERMUTATION_BASIC",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_H1_ARRANGEMENT_LEXICOGRAPHIC_RANK",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:09a1a26bb7f240418e3d3155f7a4b4bc38de708680a8c1775a74787674527878"
  },
  {
    "id": 21,
    "level": "상",
    "category": "무리함수 그래프 위 점과 삼각형 넓이의 최솟값",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "그래프 위의 점",
      "삼각형 넓이",
      "최솟값"
    ],
    "wide": false,
    "content": "두 점 $A(0,1)$, $B(1,2)$와 곡선 $y=\\sqrt{x}$ 위의 한 점 $P(x,y)$에 대하여 삼각형 $ABP$의 넓이의 최솟값을 구하여라. [7점] (부분점수 있음.)",
    "choices": [],
    "answer": "3/8",
    "solution": "$t=\\sqrt{x}$라 두면 $t\\ge0$, $P=(t^2,t)$이다. 삼각형 넓이는 두 변의 행렬식 절댓값의 절반이다.\n$\\overrightarrow{AB}=(1,1)$, $\\overrightarrow{AP}=(t^2,t-1)$이므로\n$[ABP]=\\dfrac12|1\\cdot(t-1)-1\\cdot t^2|=\\dfrac12(t^2-t+1)$이다.\n$t^2-t+1=(t-1/2)^2+3/4$이므로 최솟값은 $t=1/2$에서 나온다. 따라서 넓이의 최솟값은 $\\dfrac12\\cdot\\dfrac34=\\dfrac38$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식4",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 21,
    "displayNo": "주관식4",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식4",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_EXTREMUM",
    "templateKey": "TPL_FUNCTION_EXTREMUM_DISTANCE_AREA_PERIMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5962f307348139c9a80efe28fa393b0a1a7cdcd42d1bf94cfa461cb7596f92ee"
  },
  {
    "id": 22,
    "level": "상",
    "category": "합성함수의 치역 원소 개수 조건",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "치역",
      "자연수의 개수",
      "최솟값"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=3x+2$, $g(x)=(2x-1)^2$에 대하여 정의역을 $X=\\{x\\mid -a-1<x<a+1\\}$로 하는 합성함수 $f\\circ g$의 치역을 $A$라 하자. $A$의 원소 중 자연수가 300개 이상이 되도록 하는 자연수 $a$의 최솟값을 구하여라. [7점] (부분점수 있음.)",
    "choices": [],
    "answer": "4",
    "solution": "$f(g(x))=3(2x-1)^2+2=12(x-1/2)^2+2$이다. 정의역은 $(-a-1,a+1)$이고 $x=1/2$는 이 안에 있으므로 치역의 최솟값 2는 포함된다.\n왼쪽 끝점 $-a-1$이 꼭짓점 $1/2$에서 더 멀기 때문에 치역은 $[2,12(a+3/2)^2+2)$이다.\n$a=3$이면 치역은 $[2,245)$이므로 자연수 원소는 2부터 244까지, 243개이다. $a=4$이면 치역은 $[2,365)$이므로 2부터 364까지, 363개이다. 따라서 300개 이상을 만드는 가장 작은 자연수는 $a=4$이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식5",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 22,
    "displayNo": "주관식5",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식5",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_COMPOSITE_FUNCTION_ANALYSIS",
    "templateKey": "TPL_COMPOSITE_RANGE",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:8887f2fd2f689ecf877cccdd26db3cacb5664b3d2171364d960d806d5200d943"
  }
];
