window.examTitle = "20_매산여고_2학기_기말_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "유한 정의역에서 같은 함수 조건",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "함수의 정의",
      "같은 함수",
      "유한 정의역",
      "계수 조건"
    ],
    "wide": false,
    "content": "정의역이 $\\{1,3\\}$인 두 함수 $f(x)=4x$, $g(x)=ax^2+b$에서 $f=g$가 성립할 때 $2a-b$의 값을 구하여라. [3.5점]",
    "choices": [
      "2",
      "1",
      "0",
      "-1",
      "-2"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTION_EQUALITY",
    "templateKey": "TPL_EQUAL_FUNCTION_FINITE_DOMAIN",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f9f5591c948bd951f856389edc713641359ccfd3c9937b76adba45a24a510d67"
  },
  {
    "id": 2,
    "level": "중",
    "category": "곱셈형 함수방정식과 역함수 성질",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "함수방정식",
      "곱셈형",
      "역함수",
      "참·거짓 판정"
    ],
    "wide": false,
    "content": "함수 $f$에 대하여 역함수 $f^{-1}$가 존재하고, 임의의 실수 $x,y$에 대하여 $f(x+y)=f(x)f(y)$를 만족시킬 때, 다음 보기 중 옳은 것을 모두 구하여라. (단, $f(x)>0$)\n(ㄱ) $f^{-1}(1)=0$\n(ㄴ) $f(1)=2$이면 $f(3)=9$\n(ㄷ) $f^{-1}(4)=1$이면 $16f(-2)=1$ [4.3점]",
    "choices": [
      "ㄱ",
      "ㄴ",
      "ㄱ, ㄷ",
      "ㄴ, ㄷ",
      "ㄱ, ㄴ, ㄷ"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTIONAL_EQUATION",
    "templateKey": "TPL_FUNCTIONAL_EQUATION_MULTIPLICATIVE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:1917dcc9a6f684ff25157ba29dacc4616c7733fcb96bc3a7ad5bd65378d4b0e9"
  },
  {
    "id": 3,
    "level": "중",
    "category": "정의역·치역 포함 조건에서 계수의 최댓값",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "정의역",
      "치역",
      "일차함수",
      "계수의 최댓값"
    ],
    "wide": false,
    "content": "두 집합 $X=\\{x\\mid 1\\le x\\le5\\}$, $Y=\\{y\\mid-2\\le y\\le3\\}$에 대하여 $X$에서 $Y$로의 함수 $f(x)=ax+b$가 $Y\\subset f(X)$를 만족하도록 하는 상수 $a,b$에 대하여 $|a-b|$의 값 중에서 최댓값을 구하여라. [4.2점]",
    "choices": [
      "$\\frac92$",
      "$\\frac{11}2$",
      "$\\frac{13}2$",
      "$\\frac{15}2$",
      "$\\frac{17}2$"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_DOMAIN_RANGE_SURJECTIVITY",
    "templateKey": "TPL_FUNCTION_DOMAIN_RANGE_EXTREMUM",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5ce353b8f685f585f60ab2da59dedb04caff062e2e8c114b4455479480573b4d"
  },
  {
    "id": 4,
    "level": "하",
    "category": "합성함수 관계에서 함수값 구하기",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "함수값",
      "합성 관계"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=2x+1$, $g(x)=-2x+3$에 대하여 $h\\circ f=g$를 만족시키는 함수 $h(x)$가 존재할 때, $h(1)$의 값을 구하여라. [3.7점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_COMPOSITION_EVALUATION",
    "templateKey": "TPL_COMPOSITION_VALUE_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:c216a107d9b5827070a8bc8c1086108e24d69ae3a6154a32f985b7c11db05c2f"
  },
  {
    "id": 5,
    "level": "중",
    "category": "함수의 반복합성과 주기",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "반복합성",
      "함수의 주기",
      "그래프",
      "함숫값"
    ],
    "wide": false,
    "content": "집합 $X=\\{1,2,3,4\\}$에 대하여 함수 $f:X\\to X$가 있다. 함수 $y=f(x)$의 그래프가 그림과 같을 때, $f^1=f$, $f^2=f\\circ f^1$, $f^3=f\\circ f^2$, $\\cdots$, $f^{n+1}=f\\circ f^n$으로 정의하자. $f^{10}(2)+f^{100}(1)-f^{2020}(4)$를 구하여라. [4.1점]",
    "choices": [
      "-1",
      "0",
      "1",
      "2",
      "3"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/20_매산여고_2학기_기말_고1_기출/q005_visual.png",
    "visualAsset": "assets/images/20_매산여고_2학기_기말_고1_기출/q005_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 255,
      "y1": 450,
      "x2": 705,
      "y2": 835
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|5",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_매산여고_2학기_기말_고1_기출/q005_visual.png",
      "assetSha256": "sha256:07ff4549ac8ddc0ff5819d7231f1a8555cf2f0c4b2456499c49c4f8f6dcee376",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
      "sourceQuestionNo": "5",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 255,
        "y1": 450,
        "x2": 705,
        "y2": 835
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 450,
      "naturalHeight": 385,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_ITERATED_COMPOSITION",
    "templateKey": "TPL_ITERATION_RULE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:eae460a972d6ad7099a0e4a6f4f4ad6fe437e969800f26f651947abf95b7882f"
  },
  {
    "id": 6,
    "level": "중",
    "category": "역함수와 합성함수 관계에서 함수값 구하기",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "역함수",
      "항등함수",
      "함수값"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 정의된 세 함수 $f,g,h$에 대하여 $f(x)=\\frac12x-3$, $g(x)=3x+1$이고, 합성함수 $g^{-1}\\circ h\\circ f$가 항등함수일 때, $h(0)+h(1)$의 값을 구하여라. [4.4점]",
    "choices": [
      "42",
      "44",
      "46",
      "48",
      "50"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|6",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_COMPOSITION",
    "templateKey": "TPL_INVERSE_CONJUGATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:593ef37cf5e59d8599dc6b03dbd1a91132a48ccb6be90b3ce78b92924c01700a"
  },
  {
    "id": 7,
    "level": "중",
    "category": "정의역 제한으로 이차함수의 일대일성 판단",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "일대일함수",
      "역함수 존재",
      "이차함수",
      "정의역 제한"
    ],
    "wide": false,
    "content": "집합 $X=\\{x\\mid x\\ge a\\}$에 대하여 $X$에서 $X$로의 함수 $f(x)=x^2-4x-6$의 역함수가 존재할 때, 상수 $a$의 값을 구하여라. [4.3점]",
    "choices": [
      "-6",
      "-3",
      "0",
      "3",
      "6"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|7",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_ONE_TO_ONE_BIJECTION",
    "templateKey": "TPL_QUADRATIC_DOMAIN_BIJECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:31ebb6fabe66507fbb995d614d3b23865bd8f41e78894e052f17f50e2e18cd35"
  },
  {
    "id": 8,
    "level": "중",
    "category": "유리함수 그래프와 무리함수 사분면 관계",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "무리함수",
      "그래프",
      "사분면",
      "매개변수 관계"
    ],
    "wide": false,
    "content": "유리함수 $y=\\frac{bx+c}{x+a}$의 그래프가 그림과 같을 때, 무리함수 $y=a\\sqrt{-x+b}+c$의 그래프가 지나는 사분면을 구하여라. (단, $a,b,c$는 상수) [3.8점]",
    "choices": [
      "제 1사분면",
      "제 3사분면",
      "제 1, 2사분면",
      "제 3, 4사분면",
      "제 1, 3, 4사분면"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/20_매산여고_2학기_기말_고1_기출/q008_visual.png",
    "visualAsset": "assets/images/20_매산여고_2학기_기말_고1_기출/q008_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 1125,
      "y1": 1570,
      "x2": 1590,
      "y2": 1960
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|8",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_매산여고_2학기_기말_고1_기출/q008_visual.png",
      "assetSha256": "sha256:111dc44cc42f9aae359cab0ff96b620da66a28673c8f5522f2a304fdac526e71",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
      "sourceQuestionNo": "8",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 1125,
        "y1": 1570,
        "x2": 1590,
        "y2": 1960
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 465,
      "naturalHeight": 390,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_QUADRANT",
    "templateKey": "TPL_FUNCTION_QUADRANT_FROM_OTHER_FUNCTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d65b1f199afdd1f0b5674cc8873be96675fbc44147d730985a371804039840e0"
  },
  {
    "id": 9,
    "level": "상",
    "category": "유리함수 그래프의 대칭 직선",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "그래프의 대칭",
      "직선",
      "계수 관계"
    ],
    "wide": false,
    "content": "유리함수 $y=\\frac{3-4x}{2x+1}$의 그래프가 두 직선 $y=ax+b$, $y=cx+d$에 대하여 대칭일 때, $ad-bc$의 값을 구하여라. (단, $a,b,c,d$는 상수이고, $a>c$이다.) [4.0점]",
    "choices": [
      "0",
      "-1",
      "-2",
      "-3",
      "-4"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|9",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_PROPERTIES",
    "templateKey": "TPL_FUNCTION_GRAPH_SYMMETRY",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:3d32540dd00fb331e95bd67305e6360a47bd5ff1f4e9f856f203dae97f76c7a7"
  },
  {
    "id": 10,
    "level": "중",
    "category": "유리함수의 구간 최댓값과 최솟값",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_APPLICATION",
    "subUnit": "유리함수의 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "점근선",
      "구간",
      "최댓값",
      "최솟값"
    ],
    "wide": false,
    "content": "유리함수 $y=\\frac{ax+b}{x+2}$의 그래프는 점 $(-1,0)$을 지나고, 직선 $y=3$는 이 그래프의 점근선 중 하나이다. $0\\le x\\le4$에서 이 함수의 최솟값을 $m$, 최댓값을 $M$이라 할 때, $m+M$의 값을 구하여라. (단, $a,b$는 상수) [4.0점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|10",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_APPLICATION",
    "problemTypeKey": "PT_FUNCTION_EXTREMUM",
    "templateKey": "TPL_FUNCTION_EXTREMUM_INTERVAL_ENDPOINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4be1e9f21cfa31d2357ccb4c90e59a153e5c631ce96ba730bafd6d064f344aca"
  },
  {
    "id": 11,
    "level": "중",
    "category": "이웃 조건과 양 끝 조건이 있는 순열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "이웃 조건",
      "양 끝 조건",
      "경우의 수"
    ],
    "wide": false,
    "content": "$q,u,e,s,t,i,o,n$의 8개의 문자를 일렬로 나열할 때, $o$와 $e$ 또는 $o$와 $i$가 서로 이웃하고, $t$와 $n$이 양 끝에 오는 모든 경우의 수를 구하여라. [4.1점]",
    "choices": [
      "864",
      "866",
      "868",
      "870",
      "872"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|11",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a3a2a0641d6a834674b94b1fe6fa3ee22f329abea19749e28304bcdca73299c1"
  },
  {
    "id": 12,
    "level": "상",
    "category": "조각함수의 치역과 일대일 조건",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조각함수",
      "치역",
      "일대일함수",
      "유리함수",
      "무리함수"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 정의된 함수 $f(x)=\\begin{cases}\\dfrac{a-2x}{x-1}&(x>2)\\\\-\\sqrt{2-x}+2a&(x\\le2)\\end{cases}$일 때, 함수 $f$는 다음 조건을 만족시킨다. (단, $a$는 상수)\n(가) 치역은 $\\{y\\mid y<-2\\}$이다.\n(나) 함수 $f$는 일대일함수이다.\n$f(3)f(k)=50$일 때, 상수 $k$의 값을 구하여라. [4.6점]",
    "choices": [
      "-2",
      "-1",
      "0",
      "1",
      "2"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|12",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_ONE_TO_ONE_BIJECTION",
    "templateKey": "TPL_PIECEWISE_RANGE_STITCH_BIJECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:4c386441df864bb160ec323583d99968f9b4071ac38b22034577a1181ddcf039"
  },
  {
    "id": 13,
    "level": "상",
    "category": "유리함수·무리함수의 사분면 조건과 정수 매개변수",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "무리함수",
      "사분면",
      "정수 매개변수"
    ],
    "wide": false,
    "content": "유리함수 $y=\\frac{k}{x-3}+2$의 그래프가 모든 사분면을 지나고, 함수 $y=-\\sqrt{2x+k}+3$의 그래프가 제 1사분면, 제 2사분면, 제 4사분면을 지나도록 하는 정수 $k$의 개수를 구하여라. [4.3점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|13",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_QUADRANT",
    "templateKey": "TPL_FUNCTION_QUADRANT_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_INTEGER"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5782020c2148d3e92579f48619c9d757d6635e45c0e5be6c6fb5d131578fa646"
  },
  {
    "id": 14,
    "level": "상",
    "category": "첫째·마지막 조건이 있는 도착 순서",
    "originalCategory": "경우의 수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "도착 순서",
      "첫째·마지막 조건",
      "경우의 수"
    ],
    "wide": false,
    "content": "수학 행사장에는 $A$동아리 학생 2명과 $B$동아리 학생 4명이 각자 집에서 출발하기로 했다. 행사장에 2명 이상이 동시에 도착하는 경우가 없다고 할 때, 처음 또는 마지막에 $B$동아리 학생이 도착하는 모든 경우의 수를 구하여라. [3.6점]",
    "choices": [
      "668",
      "670",
      "672",
      "674",
      "676"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|14",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:397c7bf11be1f34efc80cb46bb3604c06606b6db0aa21fd580ef80cb3fca3389"
  },
  {
    "id": 15,
    "level": "중",
    "category": "원 위의 점을 골라 삼각형 분류하기",
    "originalCategory": "조합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-08",
    "standardUnit": "조합",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-SB-08-COMBINATION_BASIC",
    "subUnit": "조합",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조합",
      "원 위의 점",
      "삼각형",
      "각의 분류"
    ],
    "wide": false,
    "content": "다음 그림과 같이 원 위에 있는 12개의 점 중에서 3개의 점을 꼭짓점으로 하여 삼각형을 만들 때, 직각삼각형의 개수를 $a$, 둔각삼각형의 개수를 $b$, 예각삼각형의 개수를 $c$라고 할 때, $a+b-c$의 값을 구하여라. [4.5점]",
    "choices": [
      "130",
      "140",
      "150",
      "160",
      "170"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/20_매산여고_2학기_기말_고1_기출/q015_visual.png",
    "visualAsset": "assets/images/20_매산여고_2학기_기말_고1_기출/q015_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1235,
      "y1": 440,
      "x2": 1505,
      "y2": 745
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|15",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_매산여고_2학기_기말_고1_기출/q015_visual.png",
      "assetSha256": "sha256:b621dcd1aa7dc3280b79748ce9cc6adcfcd51f58a49b27b020524c0be6227f66",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
      "sourceQuestionNo": "15",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 1235,
        "y1": 440,
        "x2": 1505,
        "y2": 745
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 270,
      "naturalHeight": 305,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-08-COMBINATION_BASIC",
    "problemTypeKey": "PT_COUNTING_SELECTION_DISTRIBUTION",
    "templateKey": "TPL_COMBINATION_SELECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:2d1808e7ecd62ca828424810aae3f600a9d9a7510a2401a1b6e0931ac9e11ab6"
  },
  {
    "id": 16,
    "level": "중",
    "category": "영역 인접 조건이 있는 색칠 경우의 수",
    "originalCategory": "경우의 수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-06",
    "standardUnit": "경우의 수",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "subUnit": "경우의 수의 기본 원리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "경우의 수",
      "색칠",
      "인접 조건",
      "그래프"
    ],
    "wide": false,
    "content": "오른쪽 그림의 4개의 영역 $A,B,C,D$를 서로 다른 4가지 색을 사용하여 칠하려고 한다. 같은 색을 중복하여 사용해도 좋으나 이웃한 영역에는 서로 다른 색을 칠할 때, 색칠한 결과로 나올 수 있는 모든 경우의 수를 구하여라. [4.2점]",
    "choices": [
      "36",
      "48",
      "60",
      "72",
      "84"
    ],
    "answer": "",
    "solution": "",
    "image": "assets/images/20_매산여고_2학기_기말_고1_기출/q016_visual.png",
    "visualAsset": "assets/images/20_매산여고_2학기_기말_고1_기출/q016_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "diagram",
    "visualAssetBBoxOnPage": {
      "x1": 1517,
      "y1": 1305,
      "x2": 1760,
      "y2": 1560
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|16",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_매산여고_2학기_기말_고1_기출/q016_visual.png",
      "assetSha256": "sha256:9db9578d3b3e11f7c968f6458f6cf45deb8260046c0dddb32f9830a794eb7090",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
      "sourceQuestionNo": "16",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 1517,
        "y1": 1305,
        "x2": 1760,
        "y2": 1560
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 243,
      "naturalHeight": 255,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "problemTypeKey": "PT_H1_COUNTING_PRINCIPLE_GENERAL",
    "templateKey": "TPL_H1_COUNTING_GRAPH_PATH_COLOR",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:bd4ea82aceece25bd087834b299eb28bfb74fd71350004ebca251996a2244563"
  },
  {
    "id": 17,
    "level": "중",
    "category": "같은 문자가 있고 인접·양 끝 조건이 있는 순열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "같은 것이 있는 순열",
      "인접 금지",
      "문자 배열",
      "조건부 순열"
    ],
    "wide": false,
    "content": "8개의 $a$와 4개의 $b$를 모두 사용하여 만든 12자리 문자열 중에서 다음 조건을 모두 만족시키는 문자열의 개수를 구하여라. [4.4점]\n(가) $b$는 연속해서 나올 수 없다.\n(나) 첫째 자리의 문자가 $b$이면 마지막 자리의 문자는 $a$이다.",
    "choices": [
      "70",
      "105",
      "140",
      "175",
      "210"
    ],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|17",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_IDENTICAL_OBJECT_PERMUTATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:8730d60be1fbb5ed8ad0caf36a0752f469417fb866c5af3114840a57d5563620"
  },
  {
    "id": 18,
    "level": "중",
    "category": "역함수 그래프의 점근선",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "역함수",
      "점근선"
    ],
    "wide": false,
    "content": "함수 $f(x)=\\frac{2-3x}{x-5}$의 역함수를 $f^{-1}(x)$라 할 때, $y=f^{-1}(x)$의 그래프의 두 점근선을 구하여라. [5점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식1",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 18,
    "displayNo": "주관식1",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식1",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_RATIONAL_ASYMPTOTE",
    "templateKey": "TPL_RATIONAL_ASYMPTOTE_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b87d1a14f7d640d558fbd7f4402cdd36c9dc85b7dfdc4811591a39b126e380e8"
  },
  {
    "id": 19,
    "level": "상",
    "category": "일대일 조건과 이웃한 함수값 차가 있는 함수의 개수",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "일대일함수",
      "함수의 개수",
      "함수값 차이",
      "유한집합"
    ],
    "wide": false,
    "content": "집합 $A$가 $A=\\{1,2,3,4,5,6\\}$일 때, $A$에서 $A$로의 함수 중 다음 조건을 모두 만족시키는 함수 $f$의 개수를 구하여라. [5점]\n(가) 정의역 $A$의 두 원소 $m,n$에 대하여 $m\\ne n$이면 $f(m)\\ne f(n)$이다.\n(나) 정의역 $A$의 오직 한 원소 $n$에 대하여 $f(n+1)-f(n)=4$이다.",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식2",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 19,
    "displayNo": "주관식2",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식2",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FUNCTION_COUNTING",
    "templateKey": "TPL_CONSTRAINED_FUNCTION_COUNT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:19ecf95a6a3346717f16f944143f4460a68002c465016fa98a0cd74a772255d5"
  },
  {
    "id": 20,
    "level": "중",
    "category": "순열의 역순위",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_BASIC",
    "subUnit": "순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "subjective-2up",
    "tags": [
      "기출",
      "고1",
      "순열",
      "사전식 순위",
      "역순위",
      "자연수"
    ],
    "wide": false,
    "content": "5개의 숫자 1, 3, 5, 7, 9를 모두 사용하여 만든 다섯 자리의 자연수를 큰 수부터 차례로 나열할 때, 50번째 수를 $a$라 하고 100번째 수를 $b$라 하자. $a-b$의 값을 구하여라. [6점] (부분점수 있음.)",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식3",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 20,
    "displayNo": "주관식3",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식3",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-07-PERMUTATION_BASIC",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_H1_ARRANGEMENT_LEXICOGRAPHIC_RANK",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:09a1a26bb7f240418e3d3155f7a4b4bc38de708680a8c1775a74787674527878"
  },
  {
    "id": 21,
    "level": "상",
    "category": "무리함수 그래프 위 점과 삼각형 넓이의 최솟값",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "subjective-2up",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "그래프 위의 점",
      "삼각형 넓이",
      "최솟값"
    ],
    "wide": false,
    "content": "두 점 $A(0,1)$, $B(1,2)$와 곡선 $y=\\sqrt{x}$ 위의 한 점 $P(x,y)$에 대하여 삼각형 $ABP$의 넓이의 최솟값을 구하여라. [7점] (부분점수 있음.)",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식4",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 21,
    "displayNo": "주관식4",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식4",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_EXTREMUM",
    "templateKey": "TPL_FUNCTION_EXTREMUM_DISTANCE_AREA_PERIMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 4,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:5962f307348139c9a80efe28fa393b0a1a7cdcd42d1bf94cfa461cb7596f92ee"
  },
  {
    "id": 22,
    "level": "상",
    "category": "합성함수의 치역 원소 개수 조건",
    "originalCategory": "합성함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "subjective-2up",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "치역",
      "자연수의 개수",
      "최솟값"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=3x+2$, $g(x)=(2x-1)^2$에 대하여 정의역을 $X=\\{x\\mid -a-1<x<a+1\\}$로 하는 합성함수 $f\\circ g$의 치역을 $A$라 하자. $A$의 원소 중 자연수가 300개 이상이 되도록 하는 자연수 $a$의 최솟값을 구하여라. [7점] (부분점수 있음.)",
    "choices": [],
    "answer": "",
    "solution": "",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_매산여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_매여고1_2기말.pdf",
    "sourceQuestionNo": "주관식5",
    "sourceArchiveFile": "original/high/h1/2final/20_매산여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 22,
    "displayNo": "주관식5",
    "sourcePageNo": 6,
    "pageNo": 6,
    "sourceDocumentSha256": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913",
    "sourceIdentityKey": "sha256:9ecc3f5aac8f4c2cc5454579507ce2f409d2db5366f0c0036b6e213efe4ce913|주관식5",
    "sourceEvidencePath": "pages/page_p006.png",
    "sourcePageEvidencePaths": [
      "pages/page_p006.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_매산여고_2학기_기말_고1_기출\\pages\\page_p006.png",
    "fullPageImageRelPath": "pages/page_p006.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_COMPOSITE_FUNCTION_ANALYSIS",
    "templateKey": "TPL_COMPOSITE_RANGE",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 5,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:8887f2fd2f689ecf877cccdd26db3cacb5664b3d2171364d960d806d5200d943"
  }
];
