window.examTitle = "20_순천여고_2학기_기말_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "순열·조합 기호의 값",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_BASIC",
    "subUnit": "순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "조합",
      "계승",
      "기호의 값"
    ],
    "wide": false,
    "content": "$_{11}P_x=\\dfrac{11!}{7!}$이고, $_8C_0=y$라고 할 때, $xy$의 값은? [3.6점]",
    "choices": [
      "0",
      "4",
      "7",
      "8",
      "11"
    ],
    "answer": "②",
    "solution": "$_{11}P_x=\\dfrac{11!}{(11-x)!}$이다.\n주어진 식과 비교하면 $11-x=7$이므로 $x=4$이다. 또 $y={}_8C_0=1$이다.\n따라서 $xy=4\\cdot1=4$이고 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "1",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 1,
    "displayNo": "1",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|1",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-07-PERMUTATION_BASIC",
    "problemTypeKey": "",
    "templateKey": "",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e7958067982eeeb2ddb033a08daf074d988fd45cd310737281170e980a74d47e"
  },
  {
    "id": 2,
    "level": "중",
    "category": "합성함수가 항등함수인 조건에서 함수값 구하기",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "역함수",
      "항등함수",
      "함수값"
    ],
    "wide": false,
    "content": "함수 $f$가 $f(x)=\\dfrac12x+3$일 때, $(f\\circ g)(x)=x$를 만족시키는 함수 $g$에 대하여 $g(2)$를 구하면? [3.6점]",
    "choices": [
      "-4",
      "-2",
      "0",
      "2",
      "4"
    ],
    "answer": "②",
    "solution": "$f(g(x))=x$이므로\n$\\dfrac12g(x)+3=x$이다.\n양변에서 3을 빼고 2를 곱하면 $g(x)=2x-6$이다.\n따라서 $g(2)=4-6=-2$이고 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "2",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 2,
    "displayNo": "2",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|2",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_COMPOSITION",
    "templateKey": "TPL_INVERSE_COMPOSITION_VALUE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:e785ddb7836da92348b18efe72bcfd983b468aa81b486ac2f0504ee7c9200a37"
  },
  {
    "id": 3,
    "level": "중",
    "category": "서로 다른 숫자를 사용한 두 자리 수와 자리 조건",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "두 자리 자연수",
      "홀수·짝수 조건",
      "경우의 수"
    ],
    "wide": false,
    "content": "0부터 5까지의 정수가 각각 하나씩 적힌 6장의 카드 중에서 2장의 카드를 사용하여 두 자리의 자연수를 만들 때, 십의 자리의 수와 일의 자리의 수의 합이 홀수가 되는 자연수의 개수는? [3.6점]",
    "choices": [
      "5",
      "10",
      "15",
      "20",
      "25"
    ],
    "answer": "③",
    "solution": "십의 자리에는 0을 쓸 수 없으므로 십의 자리 숫자는 1,2,3,4,5이다. 두 자리 수의 자리 숫자 합이 홀수이려면 한 자리는 홀수, 다른 자리는 짝수여야 한다.\n십의 자리가 홀수이면 1,3,5 중 3가지이고, 일의 자리는 짝수 0,2,4 중 3가지이므로 $3\\cdot3=9$가지이다.\n십의 자리가 짝수이면 2,4 중 2가지이고, 일의 자리는 홀수 1,3,5 중 3가지이므로 $2\\cdot3=6$가지이다. 두 경우는 겹치지 않는다.\n따라서 $9+6=15$개이고 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "3",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 3,
    "displayNo": "3",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|3",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a1e97c0107432dde76b52196f845e4a5f27294fab543f52cb74de147e2f0ec06"
  },
  {
    "id": 4,
    "level": "중",
    "category": "유리식 항등식에서 계수 결정",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_BASIC",
    "subUnit": "유리함수의 뜻과 계산",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리식",
      "통분",
      "계수비교",
      "항등식"
    ],
    "wide": false,
    "content": "$x\\ne-2$, $x\\ne1$인 모든 실수 $x$에 대하여 $\\dfrac{x-1}{x+2}-\\dfrac{x-2}{x-1}=\\dfrac{ax+b}{(x+2)(x-1)}$이 성립할 때, $a+b$의 값을 구하면? (단, $a,b$는 상수이다.) [3.6점]",
    "choices": [
      "-3",
      "-1",
      "1",
      "3",
      "5"
    ],
    "answer": "④",
    "solution": "두 분수를 통분하면 분자는\n$(x-1)^2-(x-2)(x+2)$이다.\n이를 계산하면 $x^2-2x+1-(x^2-4)=-2x+5$이므로 $a=-2$, $b=5$이다.\n따라서 $a+b=3$이고 정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "4",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 4,
    "displayNo": "4",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|4",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_BASIC",
    "problemTypeKey": "PT_RATIONAL_EXPRESSION",
    "templateKey": "TPL_RATIONAL_EXPRESSION_IDENTIFICATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:38129ec52b59aac895da9800ae39c40b59f8540792fed6058b97faeaaddd98f9"
  },
  {
    "id": 5,
    "level": "중",
    "category": "합성함수와 역함수의 합성값",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "역함수",
      "함수값",
      "합성 순서"
    ],
    "wide": false,
    "content": "함수 $f,g$가 $f(x)=-4x+7$, $g(x)=2x-1$일 때, $(f\\circ(f\\circ g)^{-1}\\circ f)(2)$의 값을 구하면? [3.6점]",
    "choices": [
      "-2",
      "-1",
      "0",
      "1",
      "2"
    ],
    "answer": "④",
    "solution": "먼저 $f\\circ g$를 구하면\n$(f\\circ g)(x)=-4(2x-1)+7=-8x+11$이다.\n따라서 $(f\\circ g)^{-1}(x)=\\dfrac{11-x}{8}$이다.\n주어진 합성함수에 안쪽부터 대입하면 $f(2)=-1$,\n$(f\\circ g)^{-1}(-1)=\\dfrac{12}{8}=\\dfrac32$,\n$f(\\dfrac32)=-4\\cdot\\dfrac32+7=1$이다.\n정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "5",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 5,
    "displayNo": "5",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|5",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_COMPOSITION",
    "templateKey": "TPL_INVERSE_CONJUGATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:af0d4f7c2ed2a94e06cf44ab5b00fa3ad705a847a8241904e45f69461ba410eb"
  },
  {
    "id": 6,
    "level": "중",
    "category": "점에서 세 점을 택해 삼각형 만들기",
    "originalCategory": "조합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-08",
    "standardUnit": "조합",
    "standardUnitOrder": 8,
    "subUnitKey": "H15-SB-08-COMBINATION_BASIC",
    "subUnit": "조합",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조합",
      "점의 선택",
      "삼각형의 개수",
      "일직선 위 세 점 없음"
    ],
    "wide": false,
    "content": "평면 위에 $n$개의 점이 있다. $n$개의 점 중 어느 3개도 한 직선 위에 있지 않을 때, 이 $n$개의 점들로 만들 수 있는 삼각형의 개수는 120이다. 이때 자연수 $n$의 값은? [3.8점]",
    "choices": [
      "6",
      "7",
      "8",
      "9",
      "10"
    ],
    "answer": "⑤",
    "solution": "세 점 중 어느 세 점도 한 직선 위에 있지 않으므로 세 점을 고를 때마다 삼각형 하나가 만들어진다. 따라서\n${}_nC_3=120$이다.\n${}_{10}C_3=\\dfrac{10\\cdot9\\cdot8}{3\\cdot2\\cdot1}=120$이므로 $n=10$이다. 정답은 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "6",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 6,
    "displayNo": "6",
    "sourcePageNo": 1,
    "pageNo": 1,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|6",
    "sourceEvidencePath": "pages/page_p001.png",
    "sourcePageEvidencePaths": [
      "pages/page_p001.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p001.png",
    "fullPageImageRelPath": "pages/page_p001.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-08-COMBINATION_BASIC",
    "problemTypeKey": "PT_COUNTING_SELECTION_DISTRIBUTION",
    "templateKey": "TPL_COMBINATION_SELECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:ffea630daa7ca51cd4a343720e486d02989081179e21eee1f3bd33bd80e7dc9a"
  },
  {
    "id": 7,
    "level": "중",
    "category": "양 끝 자리 조건이 있는 순열",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_RESTRICTED",
    "subUnit": "조건이 있는 순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "양 끝 조건",
      "성별 구분",
      "경우의 수"
    ],
    "wide": false,
    "content": "남학생 3명과 여학생 2명을 일렬로 세울 때, 남학생 2명이 양 끝에 오도록 세우는 방법의 수는? [3.8점]",
    "choices": [
      "9",
      "18",
      "36",
      "45",
      "54"
    ],
    "answer": "③",
    "solution": "양 끝에 설 남학생 두 명을 순서 있게 고르는 방법은 ${}_3P_2=3\\cdot2=6$가지이다.\n가운데 세 자리는 남은 남학생 한 명과 여학생 두 명을 배열하므로 $3!=6$가지이다.\n따라서 전체 방법의 수는 $6\\cdot6=36$이고 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "7",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 7,
    "displayNo": "7",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|7",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15_SB_07_PERMUTATION_RESTRICTED",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7573f3130bcd84f4363b8d770ee49a377c90d89644bebbe1dd40f761ba1da8da"
  },
  {
    "id": 8,
    "level": "중",
    "category": "일차함수와 역함수 그래프의 교점",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-INVERSE_FUNCTION",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "일차함수",
      "역함수",
      "그래프의 교점",
      "계수"
    ],
    "wide": false,
    "content": "일차함수 $f(x)=ax+b$의 그래프와 역함수 $y=f^{-1}(x)$의 그래프가 점 $(-2,1)$에서 만날 때, 상수 $a,b$에 대하여 $ab$의 값을 구하면? [3.8점]",
    "choices": [
      "-2",
      "-1",
      "0",
      "1",
      "2"
    ],
    "answer": "④",
    "solution": "점 $(-2,1)$이 $y=f(x)$ 위에 있으므로 $f(-2)=1$이다. 또 이 점은 역함수 그래프 위에도 있으므로 $f^{-1}(-2)=1$, 즉 $f(1)=-2$이다.\n따라서\n$-2a+b=1$,\n$a+b=-2$이다.\n첫째 식에서 둘째 식을 빼면 $-3a=3$이므로 $a=-1$이고, $a+b=-2$에서 $b=-1$이다.\n따라서 $ab=1$이고 정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "8",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 8,
    "displayNo": "8",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|8",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-INVERSE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_GRAPH",
    "templateKey": "TPL_INVERSE_GRAPH_INTERSECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:0378dfd61bc46a1d549e538aa8a7407ac67974fd0e7e32924e847d6798da36c2"
  },
  {
    "id": 9,
    "level": "중",
    "category": "그래프에서 합성함수와 역함숫값 구하기",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "합성함수",
      "역함수",
      "그래프",
      "함숫값"
    ],
    "wide": false,
    "content": "오른쪽 그림은 두 함수 $y=f(x)$와 $y=x$의 그래프이다. 이때 $(f\\circ f)^{-1}(1)$의 값을 구하면? [4점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "③",
    "solution": "그래프에서 $f(2)=1$이고 $f(3)=2$임을 읽을 수 있다.\n따라서 $f(f(3))=f(2)=1$이다. 즉 $f\\circ f$의 값이 1이 되는 입력은 3이므로\n$(f\\circ f)^{-1}(1)=3$이다. 정답은 ③이다.",
    "image": "assets/images/20_순천여고_2학기_기말_고1_기출/q009_visual.png",
    "visualAsset": "assets/images/20_순천여고_2학기_기말_고1_기출/q009_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 550,
      "y1": 1730,
      "x2": 930,
      "y2": 2050
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "9",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 9,
    "displayNo": "9",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|9",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_순천여고_2학기_기말_고1_기출/q009_visual.png",
      "assetSha256": "sha256:a7c6733bf8477b1363e00613a6abead7efbb7ecef81b7f91413013b6d65ae720",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
      "sourceQuestionNo": "9",
      "sourcePageNo": 2,
      "sourcePageEvidence": "pages/page_p002.png",
      "sourcePageEvidencePaths": [
        "pages/page_p002.png"
      ],
      "sourceBBox": {
        "x1": 550,
        "y1": 1730,
        "x2": 930,
        "y2": 2050
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 380,
      "naturalHeight": 320,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-COMPOSITE_FUNCTION",
    "problemTypeKey": "PT_INVERSE_COMPOSITION",
    "templateKey": "TPL_INVERSE_COMPOSITION_VALUE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:8ab3379eea81be6283a714ed0c2837770df0e17949f97c129c5d20c6d06f5fc4"
  },
  {
    "id": 10,
    "level": "중",
    "category": "서로 다른 대상의 일대일 배치",
    "originalCategory": "순열",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-07",
    "standardUnit": "순열",
    "standardUnitOrder": 7,
    "subUnitKey": "H15-SB-07-PERMUTATION_BASIC",
    "subUnit": "순열",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "순열",
      "일대일 배치",
      "서로 다른 상자",
      "서로 다른 공"
    ],
    "wide": false,
    "content": "서로 다른 상자 6개에 서로 다른 공 4개를 넣을 때, 각 상자에 많아야 공 1개를 넣는 방법의 수는? [4점]",
    "choices": [
      "15",
      "24",
      "120",
      "240",
      "360"
    ],
    "answer": "⑤",
    "solution": "서로 다른 공 4개를 서로 다른 상자 6개 중 서로 다른 4개에 넣는 것이므로, 상자를 고르는 순서까지 포함해\n${}_6P_4=6\\cdot5\\cdot4\\cdot3=360$가지이다. 정답은 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "10",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 10,
    "displayNo": "10",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|10",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-07-PERMUTATION_BASIC",
    "problemTypeKey": "PT_COUNTING_ARRANGEMENT",
    "templateKey": "TPL_PERMUTATION_STANDARD_CONSTRAINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:13866321b7b1af1754c284703276ea3899c27b0f3cb7f95b688f77de64ec3d72"
  },
  {
    "id": 11,
    "level": "중",
    "category": "무리함수의 구간 최댓값과 최솟값",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "정의역 구간",
      "최솟값",
      "최댓값"
    ],
    "wide": false,
    "content": "$-4\\le x\\le1$에서 무리함수 $y=\\sqrt{-x+a}+2$의 최솟값이 4일 때, 최댓값을 구하면? (단, $a$는 상수이다.) [4점]",
    "choices": [
      "5",
      "6",
      "7",
      "8",
      "9"
    ],
    "answer": "①",
    "solution": "$y=\\sqrt{-x+a}+2$는 정의역에서 $x$가 커질수록 제곱근 안의 값이 작아지므로 감소한다. 따라서 최솟값은 $x=1$에서 나온다.\n$\\sqrt{a-1}+2=4$이므로 $\\sqrt{a-1}=2$, $a=5$이다.\n최댓값은 $x=-4$에서 나오므로 $\\sqrt{4+5}+2=3+2=5$이다. 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "11",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 11,
    "displayNo": "11",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|11",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "low",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_EXTREMUM",
    "templateKey": "TPL_FUNCTION_EXTREMUM_INTERVAL_ENDPOINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:b0a3e27d7a322896832dcf4448515d081ad1739b60701127d6e6803777f146ea"
  },
  {
    "id": 12,
    "level": "중",
    "category": "유리함수 그래프의 사분면 조건과 매개변수",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "그래프",
      "사분면",
      "실수 매개변수"
    ],
    "wide": false,
    "content": "함수 $y=\\dfrac{2x+k-3}{x-1}$의 그래프가 제3사분면을 지나지 않도록 하는 실수 $k$의 최댓값을 구하면? [4점]",
    "choices": [
      "-3",
      "-1",
      "0",
      "1",
      "3"
    ],
    "answer": "⑤",
    "solution": "식의 분자를 $2(x-1)+(k-1)$로 바꾸면\n$y=2+\\dfrac{k-1}{x-1}$이다. 제3사분면을 지나려면 $x<0$인 곳에서 $y<0$이어야 한다.\n$k>3$이면 $x$를 0보다 조금 작은 수로 잡을 때 $y$는 $3-k<0$에 가까워져 음수가 된다. 따라서 이때는 제3사분면을 지난다.\n반대로 $k\\le1$이면 $x<0$에서 분수항이 0 이상이어서 $y\\ge2$이다. $1<k\\le3$이면 $x-1<-1$이므로\n$\\dfrac{k-1}{x-1}>-(k-1)$이고, 따라서 $y>3-k\\ge0$이다.\n그러므로 제3사분면을 지나지 않으려면 $k\\le3$이고, 최댓값은 3이다. 정답은 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "12",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 12,
    "displayNo": "12",
    "sourcePageNo": 2,
    "pageNo": 2,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|12",
    "sourceEvidencePath": "pages/page_p002.png",
    "sourcePageEvidencePaths": [
      "pages/page_p002.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p002.png",
    "fullPageImageRelPath": "pages/page_p002.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_QUADRANT",
    "templateKey": "TPL_FUNCTION_QUADRANT_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:9c5479b2f7f4b47bf96e423cc4fdf751083825f01bf1714e2fd1d91eb41ddd19"
  },
  {
    "id": 13,
    "level": "중",
    "category": "무리함수의 역함수와 정의역 조건",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_INVERSE",
    "subUnit": "무리함수와 역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "역함수",
      "정의역",
      "매개변수"
    ],
    "wide": false,
    "content": "무리함수 $f(x)=\\sqrt{x+a}+2$의 역함수가 $f^{-1}(x)=x^2-4x+7\\;(x\\ge b)$일 때, 상수 $a,b$에 대하여 $b-a$의 값을 구하면? [4점]",
    "choices": [
      "-1",
      "0",
      "1",
      "3",
      "5"
    ],
    "answer": "⑤",
    "solution": "$y=\\sqrt{x+a}+2$의 역함수를 구한다.\n$y-2=\\sqrt{x+a}$이므로 $x=(y-2)^2-a$이다. 따라서\n$f^{-1}(x)=(x-2)^2-a$이고, 역함수의 정의역은 원래 함수의 치역이므로 $x\\ge2$이다.\n주어진 식은 $x^2-4x+7=(x-2)^2+3$이다. 비교하면 $a=-3$, $b=2$이다.\n따라서 $b-a=2-(-3)=5$이고 정답은 ⑤이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "13",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 13,
    "displayNo": "13",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|13",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_INVERSE",
    "problemTypeKey": "PT_INVERSE_VALUE",
    "templateKey": "TPL_INVERSE_FUNCTION_FORM",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:adf155387fd6ddb6f0e3bd3bbd3dfb3bdfe9e6203e6e79a26583a9361349abc2"
  },
  {
    "id": 14,
    "level": "중",
    "category": "두 번 시행한 주사위 결과의 조건부 경우의 수",
    "originalCategory": "경우의 수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-06",
    "standardUnit": "경우의 수",
    "standardUnitOrder": 6,
    "subUnitKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "subUnit": "경우의 수의 기본 원리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "경우의 수",
      "순서쌍",
      "주사위",
      "절댓값 조건"
    ],
    "wide": false,
    "content": "각 면에 1, 2, 3, 4, 5, 6의 숫자가 하나씩 적힌 정육면체 모양의 주사위가 있다. 이 주사위를 두 번 던져서 나오는 눈의 수를 차례대로 $a,b$라 할 때, $|a-b|>1$을 만족시키는 순서쌍 $(a,b)$의 개수는? [4.2점]",
    "choices": [
      "5",
      "10",
      "15",
      "20",
      "25"
    ],
    "answer": "④",
    "solution": "전체 순서쌍은 $6\\cdot6=36$개이다. $|a-b|\\le1$인 경우를 빼면 된다.\n$a=b$인 경우는 6개이다. $|a-b|=1$인 경우는 $(1,2),(2,1),\\ldots,(5,6),(6,5)$로 10개이다.\n따라서 구하는 수는 $36-6-10=20$이고 정답은 ④이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "14",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 14,
    "displayNo": "14",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|14",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-06-COUNTING_PRINCIPLE",
    "problemTypeKey": "PT_H1_COUNTING_PRINCIPLE_GENERAL",
    "templateKey": "TPL_H1_COUNTING_DIRECT_CASE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:21e18ba1c8a8f9fba9ae95a01be27c91a76c21a765ccb8d819a4e1dc3aedb705"
  },
  {
    "id": 15,
    "level": "중",
    "category": "유리함수 그래프와 직선으로 만든 도형의 넓이",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "그래프",
      "직선",
      "수직 조건",
      "삼각형 넓이"
    ],
    "wide": false,
    "content": "그림과 같이 원점을 지나는 직선 $l$과 함수 $y=-\\dfrac3x$의 그래프가 두 점 $P,Q$에서 만난다. 점 $P$를 지나고 $x$축에 수직인 직선과 점 $Q$를 지나고 $y$축에 수직인 직선이 만나는 점을 $R$라 할 때, 삼각형 $PQR$의 넓이를 구하면? [4.2점]",
    "choices": [
      "$\\dfrac32$",
      "4",
      "6",
      "$\\dfrac92$",
      "8"
    ],
    "answer": "③",
    "solution": "직선 $l$의 기울기를 $m$이라 하면 두 교점은 $P=(t,mt)$, $Q=(-t,-mt)$ 꼴이다. 두 점 모두 $y=-3/x$ 위에 있으므로 $mt^2=-3$이다.\n점 $R$은 $P$의 $x$좌표와 $Q$의 $y$좌표를 가지므로 $R=(t,-mt)$이다. 따라서 $RP=2|mt|$, $RQ=2|t|$이고 $\\angle PRQ=90^\\circ$이다.\n삼각형의 넓이는\n$\\dfrac12(2|mt|)(2|t|)=2|m|t^2=2\\cdot3=6$이다. 정답은 ③이다.",
    "image": "assets/images/20_순천여고_2학기_기말_고1_기출/q015_visual.png",
    "visualAsset": "assets/images/20_순천여고_2학기_기말_고1_기출/q015_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 600,
      "y1": 1360,
      "x2": 960,
      "y2": 1700
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "15",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 15,
    "displayNo": "15",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|15",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_순천여고_2학기_기말_고1_기출/q015_visual.png",
      "assetSha256": "sha256:4bbe093d14227a6e64b039aab856b1f7cea5ee67530b8a42ca133149f73a4030",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
      "sourceQuestionNo": "15",
      "sourcePageNo": 3,
      "sourcePageEvidence": "pages/page_p003.png",
      "sourcePageEvidencePaths": [
        "pages/page_p003.png"
      ],
      "sourceBBox": {
        "x1": 600,
        "y1": 1360,
        "x2": 960,
        "y2": 1700
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 360,
      "naturalHeight": 340,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_GEOMETRY",
    "templateKey": "TPL_FUNCTION_GRAPH_GEOMETRY_DERIVATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:863b797806f8f8483386b847bb63b80aafab44ee4d446437cf52c325e0c9b538"
  },
  {
    "id": 16,
    "level": "중",
    "category": "무리함수 그래프 위 두 점의 중점 조건",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "그래프 위의 점",
      "중점",
      "기울기"
    ],
    "wide": false,
    "content": "곡선 $f(x)=\\sqrt{x+2}-1$ 위의 서로 다른 두 점 $P,Q$에 대하여 선분 $PQ$의 중점의 $y$좌표가 1이다. 직선 $PQ$의 기울기를 구하면? [4.2점]",
    "choices": [
      "$-\\dfrac12$",
      "-1",
      "$\\dfrac14$",
      "$\\dfrac12$",
      "2"
    ],
    "answer": "③",
    "solution": "곡선 위 점의 $y$좌표를 각각 $u,v$라 하자. 곡선에서 $x=(y+1)^2-2$이므로 두 점의 중점 $y$좌표 조건은 $u+v=2$이다.\n직선 $PQ$의 기울기는\n$\\dfrac{u-v}{(u+1)^2-(v+1)^2}=\\dfrac{u-v}{(u-v)(u+v+2)}=\\dfrac1{u+v+2}$이다.\n$u+v=2$를 대입하면 기울기는 $\\dfrac14$이고 정답은 ③이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "16",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 16,
    "displayNo": "16",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|16",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_GEOMETRY",
    "templateKey": "TPL_FUNCTION_GRAPH_GEOMETRY_DERIVATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:28dd495f341e008b689a797ffcda3012a67bf08e9c0bf8b035bd942475719d22"
  },
  {
    "id": 17,
    "level": "중",
    "category": "조건이 있는 유한집합의 부분집합 개수",
    "originalCategory": "집합",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-01",
    "standardUnit": "집합",
    "standardUnitOrder": 1,
    "subUnitKey": "H15-SB-01-SET_COUNT",
    "subUnit": "집합의 원소의 개수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "집합",
      "부분집합",
      "원소의 개수",
      "포함 조건"
    ],
    "wide": false,
    "content": "다음 조건을 동시에 만족하는 집합 $\\{1,2,3,4,5,6,7,8\\}$의 부분집합 $A$의 개수는?\n(가) $n(A)=5$\n(나) $1\\in A$이고 $2\\in A$\n(다) $\\{1,5,7\\}\\not\\subset A$ [4.5점]",
    "choices": [
      "9",
      "16",
      "25",
      "36",
      "49"
    ],
    "answer": "②",
    "solution": "**(가), (나)** 원소가 5개이고 1,2를 반드시 포함하므로 나머지 세 원소는 $\\{3,4,5,6,7,8\\}$에서 고른다.\n${}_6C_3=20$가지이다.\n**(다)** 여기서 $\\{1,5,7\\}\\subset A$인 경우를 뺀다. 1은 이미 들어 있으므로 5,7을 고정하고, 남은 한 원소를 $\\{3,4,6,8\\}$에서 고르는 4가지이다.\n따라서 조건을 모두 만족하는 집합은 $20-4=16$개이고 정답은 ②이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "17",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 17,
    "displayNo": "17",
    "sourcePageNo": 3,
    "pageNo": 3,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|17",
    "sourceEvidencePath": "pages/page_p003.png",
    "sourcePageEvidencePaths": [
      "pages/page_p003.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p003.png",
    "fullPageImageRelPath": "pages/page_p003.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-01-SET_COUNT",
    "problemTypeKey": "PT_SET_CARDINALITY",
    "templateKey": "TPL_SET_CARDINALITY_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a31d61aac6660bfc82ab792b2527b397cf11d4057559a40c4cda1679cd11d3d5"
  },
  {
    "id": 18,
    "level": "중",
    "category": "단위근의 거듭제곱 주기",
    "originalCategory": "복소수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SA-04-COMPLEX_OPERATION",
    "subUnit": "복소수의 계산",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "복소수",
      "단위근",
      "거듭제곱",
      "주기"
    ],
    "wide": false,
    "content": "복소수 $z=\\dfrac{i+1}{\\sqrt2}$에 대하여 $f(n)=z^n+(z-\\sqrt2)^n$이라고 할 때, $f(36)$의 값은? (단, $i=\\sqrt{-1}$이다.) [4.5점]",
    "choices": [
      "-2",
      "-1",
      "0",
      "1",
      "2"
    ],
    "answer": "①",
    "solution": "$z=\\dfrac{1+i}{\\sqrt2}$이므로\n$z^2=\\dfrac{(1+i)^2}{2}=i$이고, $z^4=i^2=-1$이다. 따라서 $z^{36}=(z^4)^9=-1$이다.\n또 $w=z-\\sqrt2=\\dfrac{-1+i}{\\sqrt2}$라 하면\n$w^2=\\dfrac{(-1+i)^2}{2}=-i$,\n$w^4=(-i)^2=-1$이다. 따라서 $w^{36}=(w^4)^9=-1$이다.\n그러므로 $f(36)=z^{36}+w^{36}=-1-1=-2$이고 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "18",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 18,
    "displayNo": "18",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|18",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SA-04-COMPLEX_OPERATION",
    "problemTypeKey": "PT_H1_COMPLEX_POWER_ROOT",
    "templateKey": "TPL_H1_COMPLEX_ROOT_OF_UNITY_PERIOD",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:cf88afc501d01579cf1d9e7b34c81b49aecd8d577f91fe316e648cb67baae9d2"
  },
  {
    "id": 19,
    "level": "중",
    "category": "유리함수 그래프와 직선의 교점 존재 조건",
    "originalCategory": "유리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-04",
    "standardUnit": "유리함수",
    "standardUnitOrder": 4,
    "subUnitKey": "H15-SB-04-RATIONAL_GRAPH",
    "subUnit": "유리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "유리함수",
      "직선",
      "교점 조건",
      "매개변수 최댓값"
    ],
    "wide": false,
    "content": "두 집합 $A=\\{(x,y)\\mid y=\\dfrac{x-2}{x+1}\\}$, $B=\\{(x,y)\\mid y=mx+n\\}$에 대하여 실수 $m$의 값에 관계없이 $A\\cap B\\ne\\varnothing$를 만족할 때, 실수 $n$의 최댓값을 구하면? [4.5점]",
    "choices": [
      "-2",
      "-1",
      "1",
      "2",
      "3"
    ],
    "answer": "①",
    "solution": "$t=x+1$이라 두면 $t\\ne0$이고\n$\\dfrac{x-2}{x+1}=1-\\dfrac3t$, $mx+n=m(t-1)+n$이다. 교점은\n$mt^2+(n-m-1)t+3=0$의 실근 $t\\ne0$에 해당한다.\n$m\\ne0$일 때 판별식은\n$\\Delta=(n-m-1)^2-12m=m^2-(2n+10)m+(n-1)^2$이다. 이를 $m$에 대한 이차식으로 보면 $m=n+5$일 때 최솟값은 $-12(n+2)$이다. $n>-2$이면 이 기울기는 0이 아니고 판별식이 음수이므로 교점이 없다. 따라서 모든 기울기에서 교점이 있으려면 $n\\le-2$여야 한다.\n$n=-2$이면 $\\Delta=(m-3)^2\\ge0$이고, 두 근의 곱은 $3/m\\ne0$이므로 $t\\ne0$인 교점이 있다. $m=0$일 때에는 $-3t+3=0$에서 $t=1$을 얻는다. 따라서 모든 $m$에 대해 교점이 존재하고, 가능한 $n$의 최댓값은 $-2$이다. 정답은 ①이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "19",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 19,
    "displayNo": "19",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|19",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-04-RATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_GEOMETRY",
    "templateKey": "TPL_FUNCTION_GRAPH_GEOMETRY_DERIVATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:a00a45f8d72dbdd42893a758e07c02d1c226884d40546225b4ea52ac17bf4664"
  },
  {
    "id": 20,
    "level": "중",
    "category": "두 무리함수 그래프와 직각이등변삼각형 조건",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "subUnit": "무리함수의 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "그래프",
      "직각이등변삼각형",
      "넓이",
      "매개변수"
    ],
    "wide": false,
    "content": "오른쪽 그림과 같이 함수 $y=k\\sqrt{x}\\;(k>1)$의 그래프 위의 점 $A$를 지나고 $x$축, $y$축에 각각 평행한 직선이 함수 $y=\\sqrt{x}$의 그래프와 만나는 점을 각각 $B,C$라 하자. 삼각형 $ABC$가 직각이등변삼각형이고 삼각형 $ABC$의 넓이가 $\\dfrac1{18}$일 때, 상수 $k$를 구하여라? (단, 점 $A$는 제1사분면에 있다.) [4.5점]",
    "choices": [
      "$\\dfrac32$",
      "2",
      "$\\dfrac52$",
      "3",
      "4"
    ],
    "answer": "②",
    "solution": "그림과 같이 $A=(s^2,ks)$라 두면 $s=\\sqrt{x_A}>0$이다. $B$는 높이가 $ks$인 $y=\\sqrt{x}$ 위의 점이므로 $B=(k^2s^2,ks)$이고, $C$는 $x$좌표가 $s^2$인 점이므로 $C=(s^2,s)$이다.\n따라서 $AB=(k^2-1)s^2$, $AC=(k-1)s$이다. 두 선분은 서로 수직이고 삼각형이 이등변이므로\n$(k^2-1)s^2=(k-1)s$이다. $k>1$, $s>0$이므로 $(k+1)s=1$이다.\n공통인 두 직각변의 길이는 $(k-1)s=\\dfrac{k-1}{k+1}$이다. 넓이 조건에서\n$\\dfrac12\\left(\\dfrac{k-1}{k+1}\\right)^2=\\dfrac1{18}$이다. 양변을 정리하면 $\\dfrac{k-1}{k+1}=\\dfrac13$이고 $3k-3=k+1$이므로 $k=2$이다. 정답은 ②이다.",
    "image": "assets/images/20_순천여고_2학기_기말_고1_기출/q020_visual.png",
    "visualAsset": "assets/images/20_순천여고_2학기_기말_고1_기출/q020_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 1385,
      "y1": 205,
      "x2": 1770,
      "y2": 790
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "20",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 20,
    "displayNo": "20",
    "sourcePageNo": 4,
    "pageNo": 4,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|20",
    "sourceEvidencePath": "pages/page_p004.png",
    "sourcePageEvidencePaths": [
      "pages/page_p004.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p004.png",
    "fullPageImageRelPath": "pages/page_p004.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "vision_page",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 0.98,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_순천여고_2학기_기말_고1_기출/q020_visual.png",
      "assetSha256": "sha256:1c0df8cf163baf1ece97d683fc3848e8ba64197700f04ae274501b1a78f61a14",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
      "sourceQuestionNo": "20",
      "sourcePageNo": 4,
      "sourcePageEvidence": "pages/page_p004.png",
      "sourcePageEvidencePaths": [
        "pages/page_p004.png"
      ],
      "sourceBBox": {
        "x1": 1385,
        "y1": 205,
        "x2": 1770,
        "y2": 790
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 385,
      "naturalHeight": 585,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_GRAPH",
    "problemTypeKey": "PT_FUNCTION_GRAPH_GEOMETRY",
    "templateKey": "TPL_FUNCTION_GRAPH_GEOMETRY_DERIVATION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:f8202fcb01ba0b322f11157f16e11e7e18937f9453cec5141ff28eb696e7d895"
  },
  {
    "id": 21,
    "level": "중",
    "category": "무리함수와 역함수 그래프의 교점",
    "originalCategory": "무리함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-05",
    "standardUnit": "무리함수",
    "standardUnitOrder": 5,
    "subUnitKey": "H15-SB-05-IRRATIONAL_INVERSE",
    "subUnit": "무리함수와 역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "무리함수",
      "역함수",
      "그래프",
      "교점 좌표"
    ],
    "wide": false,
    "content": "무리함수 $f(x)=-\\sqrt{2x+a}+b$의 그래프가 다음 그림과 같을 때, 다음을 구하시오. [6점]\n(1) 상수 $a,b$의 값을 각각 구하시오. [2점]\n(2) 무리함수 $f$의 역함수를 $g$라 할 때, 함수 $y=f(x)$와 함수 $y=g(x)$의 만나는 점의 좌표가 $(p,q)$이다. $p+q$의 값을 풀이과정과 함께 서술하시오. [4점]",
    "choices": [],
    "answer": "a=2, b=2; p+q=6−2√7",
    "solution": "**(1)** 그래프의 시작점은 $(-1,2)$이다. 제곱근 안이 0이 되는 곳이 시작점이므로 $2(-1)+a=0$, 따라서 $a=2$이다. 그때 함수값은 $b$이므로 $b=2$이다.\n**(2)** 이제 $f(x)=2-\\sqrt{2x+2}$이고 정의역은 $x\\ge-1$, 치역은 $y\\le2$이다. $y=f(x)$에서 $x,y$를 바꾸어 풀면 역함수는 $f^{-1}(x)=\\dfrac{(2-x)^2}{2}-1$이며 정의역은 $x\\le2$이다.\n두 그래프의 공통점 $(p,q)$는 $q=f(p)$, $p=f(q)$를 만족한다. 따라서\n$2-q=\\sqrt{2p+2}$, $2-p=\\sqrt{2q+2}$이다. 두 식을 제곱하고 빼면\n$(p-q)(4-p-q)=2(p-q)$이다. 만약 $p\\ne q$이면 $p+q=2$이다. 이를 첫째 식에 대입하면 $p^2=2p+2$이므로 $p=1\\pm\\sqrt3$이고, 두 값 중 하나는 2보다 크다. 그런데 공통점의 두 좌표는 모두 역함수의 정의역 조건 때문에 2 이하이므로 모순이다. 따라서 $p=q$이다.\n$p=2-\\sqrt{2p+2}$에서 $p\\le2$이므로 제곱하면 $p^2-6p+2=0$이다. 가능한 값은 $p=3-\\sqrt7$이다.\n따라서 $p+q=2p=6-2\\sqrt7$이다.",
    "image": "assets/images/20_순천여고_2학기_기말_고1_기출/q021_visual.png",
    "visualAsset": "assets/images/20_순천여고_2학기_기말_고1_기출/q021_visual.png",
    "hasVisualAsset": true,
    "visualAssetType": "graph",
    "visualAssetBBoxOnPage": {
      "x1": 615,
      "y1": 285,
      "x2": 970,
      "y2": 650
    },
    "visualAssetStatus": "cropped_from_full_page_bbox",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "서술형1",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 21,
    "displayNo": "서술형1",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|서술형1",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "visual_asset_only",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.96,
    "choicesConfidence": 1,
    "visualAssetConfidence": 0.95,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "visualAssetProvenance": {
      "assetPath": "assets/images/20_순천여고_2학기_기말_고1_기출/q021_visual.png",
      "assetSha256": "sha256:588680a5d89aa241c1550d599c272489007897f0742140ef2893d274c280585e",
      "assetBindingType": "DIRECT",
      "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
      "sourceQuestionNo": "서술형1",
      "sourcePageNo": 5,
      "sourcePageEvidence": "pages/page_p005.png",
      "sourcePageEvidencePaths": [
        "pages/page_p005.png"
      ],
      "sourceBBox": {
        "x1": 615,
        "y1": 285,
        "x2": 970,
        "y2": 650
      },
      "cropGenerator": "scanned_exam_pipeline.py",
      "pngDecodePass": true,
      "naturalWidth": 355,
      "naturalHeight": 365,
      "cropStatus": "CROP_PURITY_REVIEW_REQUIRED",
      "verdict": "PENDING_REVIEW",
      "checks": {
        "CROP_PURITY": false,
        "NO_OTHER_QUESTION_TEXT": false,
        "NO_CHOICES_CONTAMINATION": false,
        "NO_PAGE_BORDER_CONTAMINATION": false,
        "NO_CLIPPING": false,
        "REQUIRED_LABELS_PRESENT": false,
        "QUESTION_SEMANTIC_MATCH": false
      }
    },
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-05-IRRATIONAL_INVERSE",
    "problemTypeKey": "PT_INVERSE_GRAPH",
    "templateKey": "TPL_INVERSE_GRAPH_INTERSECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:7005996cb2c669655427ff765d7451ff33aaa4566c4c2f8d2dda999845c49a75"
  },
  {
    "id": 22,
    "level": "중",
    "category": "조각함수의 치역과 일대일 조건에서 이차함수 결정",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "조각함수",
      "치역",
      "역함수 존재",
      "일대일함수",
      "이차함수"
    ],
    "wide": false,
    "content": "최고차항의 계수가 양수인 이차함수 $f(x)$에 대하여 함수 $g(x)$를 다음과 같이 정의하자.\n$g(x)=\\begin{cases}x-4&(x<-1)\\\\f(x)&(-1\\le x\\le2)\\\\x+2&(x>2)\\end{cases}$\n함수 $g(x)$의 치역이 실수 전체의 집합이고, 함수 $g(x)$의 역함수가 존재할 때, $g(0)=-1$, $g(-1)=4$를 만족하는 $f(x)$를 풀이과정과 함께 서술하시오. [7점]",
    "choices": [],
    "answer": "x^2-4x-1",
    "solution": "$x<-1$에서 $g(x)=x-4$의 치역은 $(-\\infty,-5)$이고, $x>2$에서 $g(x)=x+2$의 치역은 $(4,\\infty)$이다. 따라서 가운데 이차함수는 이 두 구간과 겹치지 않으면서 빠진 값 $[-5,4]$를 모두 만들어야 한다.\n$f(0)=g(0)=-1$이므로 $f(x)=Ax^2+Bx-1$이라 둘 수 있다. $g(-1)=4$이므로 $f(-1)=4$에서 $A-B=5$이다.\n가운데 이차함수는 구간 $[-1,2]$에서 일대일이어야 하므로 그 구간 안에서 방향이 바뀔 수 없다. 만약 증가하면 $f(-1)=4$보다 큰 값도 가져 오른쪽 조각의 치역 $(4,\\infty)$와 겹치므로 일대일이 깨진다. 따라서 가운데에서는 감소하고, 빠진 치역의 왼쪽 끝을 채우려면 $f(2)=-5$이다. 그러므로 $2A+B=-2$이다.\n$A-B=5$, $2A+B=-2$를 풀면 $A=1$, $B=-4$이다. 따라서 $f(x)=x^2-4x-1=(x-2)^2-5$이다. 이 함수는 $[-1,2]$에서 4부터 −5까지 감소하므로 바깥 두 조각과 함께 치역은 실수 전체이고 일대일이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "서술형2",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 22,
    "displayNo": "서술형2",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|서술형2",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_ONE_TO_ONE_BIJECTION",
    "templateKey": "TPL_PIECEWISE_RANGE_STITCH_BIJECTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:bad3b229a5b5abebaf9b08153c720c00bfb641dae0e6748f80f4356f74e732e5"
  },
  {
    "id": 23,
    "level": "중",
    "category": "역함수가 자기 자신인 유한집합의 함수 개수",
    "originalCategory": "함수",
    "standardCourse": "수학(하)",
    "standardUnitKey": "H15-SB-03",
    "standardUnit": "함수",
    "standardUnitOrder": 3,
    "subUnitKey": "H15-SB-03-FUNCTION_RELATION",
    "subUnit": "함수의 뜻과 대응",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "기출",
      "고1",
      "역함수",
      "유한집합",
      "일대일대응",
      "함수의 개수"
    ],
    "wide": false,
    "content": "집합 $X=\\{1,2,3,4,5\\}$에 대하여 $f=f^{-1}$을 만족하는 함수 $f:X\\to X$의 개수를 풀이과정과 함께 서술하시오. [7점]",
    "choices": [],
    "answer": "26",
    "solution": "$f=f^{-1}$이면 $f(f(x))=x$이고 $f$는 집합의 순열이다. 따라서 순열의 순환은 길이 1인 고정점이나 길이 2인 맞바꿈으로만 이루어진다.\n맞바꿈이 0개이면 1가지이다. 1개이면 두 원소를 고르는 ${}_5C_2=10$가지이다. 2개이면 먼저 네 원소를 고르고, 그 네 원소를 두 쌍으로 나누는 방법이 3가지이므로 ${}_5C_4\\cdot3=15$가지이다.\n전체는 $1+10+15=26$개이다.",
    "image": "",
    "visualAsset": "",
    "hasVisualAsset": false,
    "visualAssetType": "none",
    "visualAssetBBoxOnPage": null,
    "visualAssetStatus": "no_visual_asset_required",
    "examId": "20_순천여고_2학기_기말_고1_기출",
    "sourceFile": "D:\\기출\\(4)2기말\\수학(하)\\2020_순여고1_2기말.pdf",
    "sourceQuestionNo": "서술형3",
    "sourceArchiveFile": "original/high/h1/2final/20_순천여고_2학기_기말_고1_기출.js",
    "sourceOrdinal": 23,
    "displayNo": "서술형3",
    "sourcePageNo": 5,
    "pageNo": 5,
    "sourceDocumentSha256": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042",
    "sourceIdentityKey": "sha256:e6d0c524b9e3f595e2557ba6634817485cf756aa52148ad9b1eca3bcb0bf4042|서술형3",
    "sourceEvidencePath": "pages/page_p005.png",
    "sourcePageEvidencePaths": [
      "pages/page_p005.png"
    ],
    "cropPath": "",
    "fullPageImagePath": "C:\\Users\\USER\\.codex\\worktrees\\archive-source-intake-nightly\\AP------\\archive-work\\evidence\\20_순천여고_2학기_기말_고1_기출\\pages\\page_p005.png",
    "fullPageImageRelPath": "pages/page_p005.png",
    "imageStatus": "no_question_crop",
    "contentSource": "vision_page",
    "choicesSource": "not_applicable",
    "answerSource": "not_in_pipeline",
    "solutionSource": "not_in_pipeline",
    "answerStatus": "out_of_scope",
    "solutionStatus": "out_of_scope",
    "extractionStatus": "vision_extracted",
    "reviewStatus": "vision_extracted_pending_answer_solution",
    "reviewReason": [],
    "contentConfidence": 0.98,
    "choicesConfidence": 1,
    "visualAssetConfidence": 1,
    "tagConfidence": "medium",
    "tagStatus": "manual_review",
    "curriculum": "2015",
    "conceptClusterKey": "H15-SB-03-FUNCTION_RELATION",
    "problemTypeKey": "PT_FINITE_BIJECTION",
    "templateKey": "TPL_FINITE_BIJECTION_INVERSE_DEDUCTION",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "low",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "metadataStatus": "SOURCE_FIRST_PASS",
    "metadataReviewRequired": true,
    "sourceMetadataFirstPassSha": "sha256:d2203439ac52162c51005e47e039bac506fd5e22db6b1943637ba5c2e39c063f"
  }
];
