window.examTitle = "비상_공통수학2_도형의이동_중단원학습점검_고1";

window.questionBank = [
  {
    "id": 1,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "평행이동"],
    "wide": false,
    "content": "좌표평면 위의 점 $(5,1)$을 $x$축의 방향으로 $a$만큼, $y$축의 방향으로 $-3$만큼 평행이동한 점의 좌표가 $(7,b)$일 때, 실수 $a$, $b$의 값을 구하시오.",
    "choices": [],
    "answer": "$a=2, b=-2$",
    "solution": "점 $(5,1)$을 $(a,-3)$만큼 평행이동하면 좌표는 $(5+a,1-3)$이다.\n이 점이 $(7,b)$이므로 $5+a=7$, $1-3=b$이다.\n따라서 $a=2$, $b=-2$이다.\n따라서 구하는 값은 $a=2, b=-2$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 2,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "평행이동"],
    "wide": false,
    "content": "다음 방정식이 나타내는 도형을 $x$축의 방향으로 $3$만큼, $y$축의 방향으로 $-2$만큼 평행이동한 도형의 방정식을 구하시오.\\n(1) $y=-\\dfrac{1}{3}x+5$\\n(2) $(x+6)^2+(y-8)^2=7$",
    "choices": [],
    "answer": "⑴ $y=-\\dfrac{1}{3}x+4$, ⑵ $(x+3)^2+(y-6)^2=7$",
    "solution": "도형을 오른쪽으로 $3$만큼, 아래로 $2$만큼 옮기면 옮긴 도형 위의 점 $(x,y)$에 대응하는 원래 점의 좌표는 $(x-3,y+2)$이다.\n(1) 원래 직선의 식에 $x-3$, $y+2$를 대입하면 $y+2=-\\dfrac{1}{3}(x-3)+5$이다.\n이를 정리하면 $y=-\\dfrac{1}{3}x+4$이다.\n(2) 원래 원의 식에 대입하면 $((x-3)+6)^2+((y+2)-8)^2=7$이다.\n따라서 $(x+3)^2+(y-6)^2=7$이다.\n따라서 구하는 방정식은 ⑴ $y=-\\dfrac{1}{3}x+4$, ⑵ $(x+3)^2+(y-6)^2=7$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 3,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "대칭이동"],
    "wide": false,
    "content": "점 $(3,-2)$를 다음 점 또는 직선에 대하여 대칭이동한 점의 좌표를 구하시오.\\n(1) $x$축\\n(2) $y$축\\n(3) 원점\\n(4) 직선 $y=x$",
    "choices": [],
    "answer": "⑴ $(3,2)$, ⑵ $(-3,-2)$, ⑶ $(-3,2)$, ⑷ $(-2,3)$",
    "solution": "점 $(x,y)$를 $x$축에 대하여 대칭이동하면 $(x,-y)$가 되고, $y$축에 대하여 대칭이동하면 $(-x,y)$가 된다. 원점에 대하여 대칭이동하면 $(-x,-y)$가 되며, 직선 $y=x$에 대하여 대칭이동하면 $(y,x)$가 된다.\n이를 점 $(3,-2)$에 적용하면 다음과 같다.\n(1) $x$축 대칭: $(3,-2)\\rightarrow(3,2)$\n(2) $y$축 대칭: $(3,-2)\\rightarrow(-3,-2)$\n(3) 원점 대칭: $(3,-2)\\rightarrow(-3,2)$\n(4) 직선 $y=x$ 대칭: $(3,-2)\\rightarrow(-2,3)$\n따라서 구하는 좌표는 차례로 $(3,2)$, $(-3,-2)$, $(-3,2)$, $(-2,3)$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 4,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "대칭이동"],
    "wide": false,
    "content": "직선 $3x+2y+1=0$을 다음 점 또는 직선에 대하여 대칭이동한 도형의 방정식을 구하시오.\\n(1) $x$축\\n(2) $y$축\\n(3) 원점\\n(4) 직선 $y=x$",
    "choices": [],
    "answer": "⑴ $3x-2y+1=0$, ⑵ $3x-2y-1=0$, ⑶ $3x+2y-1=0$, ⑷ $2x+3y+1=0$",
    "solution": "도형의 방정식에서 대칭이동된 점 $(x,y)$에 대응하는 원래 점의 좌표를 대입한다.\n(1) $x$축 대칭은 $(x,-y)$를 대입하므로 $3x-2y+1=0$이다.\n(2) $y$축 대칭은 $(-x,y)$를 대입하면 $-3x+2y+1=0$이다. 양변에 $-1$을 곱하면 $3x-2y-1=0$이다.\n(3) 원점 대칭은 $(-x,-y)$를 대입하면 $-3x-2y+1=0$이다. 양변에 $-1$을 곱하면 $3x+2y-1=0$이다.\n(4) 직선 $y=x$ 대칭은 좌표를 서로 바꾸어 $3y+2x+1=0$, 즉 $2x+3y+1=0$이다.\n따라서 구하는 방정식은 차례로 $3x-2y+1=0$, $3x-2y-1=0$, $3x+2y-1=0$, $2x+3y+1=0$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 5,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "평행이동"],
    "wide": false,
    "content": "직선 $y=3x+5$를 $x$축의 방향으로 $a$만큼, $y$축의 방향으로 $-3$만큼 평행이동한 도형이 점 $(7,5)$를 지날 때, 실수 $a$의 값을 구하시오.",
    "choices": [],
    "answer": "$6$",
    "solution": "직선 $y=3x+5$를 오른쪽으로 $a$만큼, 아래로 $3$만큼 옮기면 옮긴 직선의 방정식은 $y+3=3(x-a)+5$이다.\n정리하면 $y=3x-3a+2$이다.\n이 직선이 $(7,5)$를 지나므로 $5=3\\cdot7-3a+2=23-3a$이다. 따라서 $3a=18$이고 $a=6$이다.\n따라서 구하는 값은 $6$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 6,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "평행이동"],
    "wide": false,
    "content": "원 $C_1$: $x^2+(y-1)^2=1$을 $x$축의 방향으로 $3$만큼, $y$축의 방향으로 $6$만큼 평행이동한 원을 $C_2$라고 하자. 직선 $l$이 두 원 $C_1$, $C_2$의 넓이를 동시에 이등분할 때, 직선 $l$의 방정식을 구하시오.",
    "choices": [],
    "answer": "$y=2x+1$",
    "solution": "원 $C_1$의 중심은 $(0,1)$이다. 원을 오른쪽으로 $3$만큼, 위로 $6$만큼 평행이동하면 중심은 $(3,7)$이므로 원 $C_2$의 방정식은 $(x-3)^2+(y-7)^2=1$이다.\n원의 넓이를 이등분하는 직선은 그 원의 중심을 지난다. 따라서 두 원의 넓이를 모두 이등분하는 직선 $l$은 두 중심 $(0,1)$, $(3,7)$을 지난다.\n기울기는 $\\dfrac{7-1}{3-0}=2$이므로 $(0,1)$을 지나는 직선은 $y-1=2x$이다.\n따라서 직선 $l$의 방정식은 $y=2x+1$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 7,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "대칭이동", "평행이동"],
    "wide": false,
    "content": "점 $A(-2,3)$을 직선 $y=x$에 대하여 대칭이동한 점을 $B$라 하고, 점 $B$를 $x$축의 방향으로 $2$만큼, $y$축의 방향으로 $a$만큼 평행이동한 점을 $C$라고 하자. 세 점 $A$, $B$, $C$가 한 직선 위에 있을 때, 실수 $a$의 값을 구하시오.",
    "choices": [],
    "answer": "$-2$",
    "solution": "점 $A(-2,3)$을 직선 $y=x$에 대하여 대칭이동하면 좌표를 바꾸므로 $B=(3,-2)$이다. 점 $B$를 오른쪽으로 $2$만큼, 세로로 $a$만큼 옮기면 $C=(5,a-2)$이다.\n세 점이 한 직선 위에 있으므로 기울기 $AB$와 $BC$가 같다.\n$\\dfrac{-2-3}{3-(-2)}=-1$이고, $\\dfrac{(a-2)-(-2)}{5-3}=\\dfrac{a}{2}$이다.\n따라서 $\\dfrac{a}{2}=-1$이므로 $a=-2$이다.\n따라서 구하는 값은 $-2$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 8,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "도형"],
    "wide": false,
    "content": "오른쪽 그림과 같이 원 $x^2+y^2=4$ 위의 두 점 $A(2,0)$, $B(1,\\sqrt{3})$에 대하여 점 $A$를 지나고 직선 $AB$에 수직인 직선이 원과 만나는 점을 $C$라고 하자. 이때 점 $C$의 좌표를 구하시오.",
    "choices": [],
    "answer": "$(-1,-\\sqrt{3})$",
    "image": "assets/images/비상_공통수학2_도형의이동_중단원학습점검_고1/q08.png",
    "solution": "점 $A$와 $B$는 원 위에 있고, 직선 $AC$는 직선 $AB$에 수직이므로 $\\angle BAC=90^\\circ$이다. 원주각이 직각이므로 그 맞은편 현 $BC$는 지름이다.\n원의 중심은 원점이므로 지름 $BC$의 양 끝점은 원점에 대하여 대칭이다. 따라서 $C$는 $B(1,\\sqrt{3})$를 원점에 대하여 대칭이동한 점이다.\n그러므로 $C=(-1,-\\sqrt{3})$이다.\n따라서 구하는 점 $C$의 좌표는 $(-1,-\\sqrt{3})$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 9,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "대칭이동", "원", "접선"],
    "wide": false,
    "content": "직선 $3x+4y+k=0$을 $y$축에 대하여 대칭이동한 직선을 $l$, 원 $(x-2)^2+(y-3)^2=4$를 직선 $y=x$에 대하여 대칭이동한 원을 $C$라고 하자. 원 $C$와 직선 $l$이 한 점에서 만나도록 하는 실수 $k$의 값을 모두 구하시오.",
    "choices": [],
    "answer": "$k=-9$ 또는 $k=11$",
    "solution": "직선 $3x+4y+k=0$을 $y$축에 대하여 대칭이동하면 $x$ 대신 $-x$를 대입하여 $-3x+4y+k=0$을 얻는다. 양변에 $-1$을 곱하면 직선 $l$은 $3x-4y-k=0$이다.\n원 $(x-2)^2+(y-3)^2=4$의 중심 $(2,3)$을 직선 $y=x$에 대하여 대칭이동하면 $(3,2)$가 되므로 원 $C$의 방정식은 $(x-3)^2+(y-2)^2=4$이다. 중심은 $(3,2)$, 반지름은 $2$이다.\n직선 $l$과 원 $C$가 한 점에서 만나려면 중심 $(3,2)$에서 직선 $3x-4y-k=0$까지의 거리가 반지름 $2$와 같아야 한다.\n$\\dfrac{|3\\cdot3-4\\cdot2-k|}{\\sqrt{3^2+(-4)^2}}=2$이므로 $\\dfrac{|1-k|}{5}=2$이다. 따라서 $|1-k|=10$에서 $k=-9$ 또는 $k=11$이다.\n따라서 구하는 값은 $k=-9$ 또는 $k=11$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 10,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "평행이동", "대칭이동"],
    "wide": false,
    "content": "직선 $l: y=ax+4$를 $x$축의 방향으로 $2$만큼, $y$축의 방향으로 $-1$만큼 평행이동한 후, 직선 $y=x$에 대하여 대칭이동한 직선을 $l\u0027$이라고 하자. 두 직선 $l$, $l\u0027$의 교점이 $y$축 위에 있을 때, 실수 $a$의 값을 구하시오.",
    "choices": [],
    "answer": "$-\\dfrac{3}{2}$",
    "solution": "직선 $l:y=ax+4$를 오른쪽으로 $2$만큼, 아래로 $1$만큼 옮기면 $y+1=a(x-2)+4$이므로 $y=ax-2a+3$이다.\n이를 직선 $y=x$에 대하여 대칭이동하면 $x=ay-2a+3$, 즉 $l':x-ay+2a-3=0$이다.\n교점이 $y$축 위에 있으므로 그 점은 원래 직선 $l$의 $y$절편 $(0,4)$이다. 이 점을 $l'$에 대입하면 $-4a+2a-3=0$이므로 $a=-\\dfrac{3}{2}$이다.\n따라서 구하는 값은 $-\\dfrac{3}{2}$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  },
  {
    "id": 11,
    "level": "",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": ["비상교육", "공통수학2", "고1", "도형의 이동", "중단원 학습 점검", "대칭이동"],
    "wide": false,
    "content": "두 점 $A(-2,-2)$, $B(-2,1)$과 $y$축 위의 점 $P$, $\\overline{BQ}=1$인 점 $Q$에 대하여 $\\overline{AP}+\\overline{PQ}$의 값이 최소가 될 때, 삼각형 $APQ$의 넓이를 구하시오.",
    "choices": [],
    "answer": "$\\dfrac{9}{5}$",
    "solution": "점 $A(-2,-2)$를 $y$축에 대하여 대칭이동한 점을 $A'(2,-2)$라고 하자. $P$는 $y$축 위에 있으므로 $\\overline{AP}=\\overline{A'P}$이다.\n삼각부등식에 의해 $\\overline{AP}+\\overline{PQ}=\\overline{A'P}+\\overline{PQ}\\ge\\overline{A'Q}$이다. $Q$는 중심 $B$에서 거리 $1$인 원 위의 점이므로 $\\overline{A'Q}$가 최소가 되려면 $A'$, $Q$, $B$가 한 직선 위에 있고 $Q$가 $B$에서 $A'$ 방향으로 $1$만큼 떨어져야 한다. 따라서 최솟값은 $\\overline{A'B}-1=5-1=4$이다.\n직선 $A'B$의 기울기는 $\\dfrac{1-(-2)}{-2-2}=-\\dfrac{3}{4}$이므로 그 방정식은 $y=-\\dfrac{3}{4}x-\\dfrac{1}{2}$이다. 이 직선과 $y$축의 교점은 $P=(0,-\\dfrac{1}{2})$이다.\n$\\overline{PB}=\\sqrt{(-2)^2+(1+\\dfrac{1}{2})^2}=\\dfrac{5}{2}$이므로 $\\overline{PQ}=\\overline{PB}-\\overline{BQ}=\\dfrac{5}{2}-1=\\dfrac{3}{2}$이다.\n직선 $PQ=A'B$의 방정식은 $3x+4y+2=0$이다. 점 $A(-2,-2)$에서 이 직선까지의 거리는 $\\dfrac{|3(-2)+4(-2)+2|}{\\sqrt{3^2+4^2}}=\\dfrac{12}{5}$이다.\n따라서 삼각형 $APQ$의 넓이는 $\\dfrac{1}{2}\\cdot\\dfrac{3}{2}\\cdot\\dfrac{12}{5}=\\dfrac{9}{5}$이다.\n따라서 구하는 삼각형 $APQ$의 넓이는 $\\dfrac{9}{5}$이다.",
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "rule_inferred",
    "subUnitClassificationDepth": "complete_rule"
  }
];