window.examTitle = "26_금당고_2학기_중간_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "방정식 $x^2+y^2+4x-6y+k^2-4k+8=0$이 나타내는 도형이 원이 되도록 하는 정수 $k$의 개수는? [4.5점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "1",
    "displayNo": "1",
    "sourceOrdinal": 1,
    "sourcePageImage": "1000024890.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 2,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "다음 중 옳은 것은? [4.5점]",
    "choices": [
      "$n(\\{1,2,3\\})\\lt n(\\{4,5,6\\})$",
      "$A=\\{0\\}$이면 $n(A)=0$이다.",
      "$n(\\{\\varnothing\\})-n(\\varnothing)=1$",
      "$n(A)=0$이면 $A=\\{\\varnothing\\}$이다.",
      "$n(\\{55\\})-n(\\{50\\})=5$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "2",
    "displayNo": "2",
    "sourceOrdinal": 2,
    "sourcePageImage": "1000024890.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 3,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "원 $x^2+y^2=13$위의 점 $(-2,3)$에서의 접선이 점 $(a,5)$를 지날 때, $a$의 값은? [4.5점]",
    "choices": [
      "$-3$",
      "$-1$",
      "1",
      "3",
      "10"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "3",
    "displayNo": "3",
    "sourceOrdinal": 3,
    "sourcePageImage": "1000024890.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 4,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "좌표평면 위의 점 $(-2,3)$을 $x$축 방향으로 $a$만큼, $y$축의 방향으로 4만큼 평행이동한 점의 좌표가 $(-1,b)$일 때, $a-b$의 값은? [4.5점]",
    "choices": [
      "$-6$",
      "$-\\dfrac{7}{4}$",
      "$-5$",
      "$\\dfrac{3}{2}$",
      "3"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "4",
    "displayNo": "4",
    "sourceOrdinal": 4,
    "sourcePageImage": "1000024890.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 5,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "원 $(x-3)^2+(y+2)^2=16$을 $y=x$에 대하여 대칭이동한 원의 중심의 좌표가 $(a,b)$이고 반지름의 길이가 $c$일 때, $a-b+c$의 값은? [4.6점]",
    "choices": [
      "$-1$",
      "$-2$",
      "3",
      "5",
      "9"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "5",
    "displayNo": "5",
    "sourceOrdinal": 5,
    "sourcePageImage": "1000024891.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 6,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "한 직선 위에 있지 않은 서로 다른 세 점 $A(5,2)$, $B(2,4)$, $C(-1,-3)$을 꼭짓점으로 하는 삼각형 $ABC$의 무게중심이 $G(a,b)$이다. 이때 $a+b$의 값은? [4.6점]",
    "choices": [
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "6",
    "displayNo": "6",
    "sourceOrdinal": 6,
    "sourcePageImage": "1000024891.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 7,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "점 $(4,a)$를 지나고 직선 $4x+3y-2=0$에 수직인 직선이 점 $(-4,1)$을 지날 때, $a$의 값은? [4.6점]",
    "choices": [
      "$\\dfrac{28}{3}$",
      "$\\dfrac{27}{4}$",
      "$\\dfrac{13}{2}$",
      "7",
      "12"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "7",
    "displayNo": "7",
    "sourceOrdinal": 7,
    "sourcePageImage": "1000024891.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 8,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 집합 $A=\\{a^2-5a,8,12\\}$, $B=\\{6,a+2,2a\\}$에 대하여 $A\\subset B$이고 $B\\subset A$일 때, 상수 $a$의 값은? [4.7점]",
    "choices": [
      "$-1$",
      "1",
      "3",
      "6",
      "8"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "8",
    "displayNo": "8",
    "sourceOrdinal": 8,
    "sourcePageImage": "1000024891.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 9,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 점 $A(-3,-8)$, $B(15,1)$에 대하여 선분 $AB$ 위의 점 $P$가 $5\\overline{AP}=4\\overline{BP}$를 만족시킬 때, 점 $P$의 좌표를 $(p,q)$라 하자. $p+q$의 값은? [4.7점]",
    "choices": [
      "0",
      "1",
      "2",
      "3",
      "4"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "9",
    "displayNo": "9",
    "sourceOrdinal": 9,
    "sourcePageImage": "1000024892.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 10,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "직선 $3x-y-2+k(x+y-6)=0$이 실수 $k$값에 관계없이 항상 점 $P$를 지날 때, 점 $P$와 직선 $3x+4y+3=0$ 사이의 거리를 구하면? [4.7점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "10",
    "displayNo": "10",
    "sourceOrdinal": 10,
    "sourcePageImage": "1000024892.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 11,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 직선 $(k-1)x+y-4=0$, $kx-2y+3=0$이 평행하도록 하는 상수 $k$의 값을 $a$, 수직이 되도록 하는 상수 $k$의 값을 $b$라 할 때, $ab$의 값은? [4.7점] (단, $b\\gt0$)",
    "choices": [
      "$\\dfrac{1}{3}$",
      "$\\dfrac{2}{3}$",
      "1",
      "$\\dfrac{4}{3}$",
      "$\\dfrac{5}{3}$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "11",
    "displayNo": "11",
    "sourceOrdinal": 11,
    "sourcePageImage": "1000024892.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 12,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "직선 $3x-4y+a=0$이 원 $C_1:x^2+y^2-2x-4y+1=0$의 넓이를 이등분한다. 이 직선이 또 다른 원 $C_2:x^2+y^2+bx+cy+d=0$과 서로 다른 두 점 $A,B$에서 만날 때, 선분 $\\overline{AB}$의 길이는 8이다. 원 $C_2$의 중심의 좌표가 $(2,-1)$일 때, 상수 $a,b,c,d$에 대하여 $a+b+c+d$의 값을 구하면? [4.8점]",
    "choices": [
      "$-19$",
      "$-17$",
      "$-15$",
      "$-13$",
      "$-11$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "12",
    "displayNo": "12",
    "sourceOrdinal": 12,
    "sourcePageImage": "1000024893.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 13,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "점 $(-1,1)$에서 원 $x^2+y^2-6x-4y+9=0$에 그은 두 접선의 기울기의 곱은? [4.8점]",
    "choices": [
      "$-\\dfrac{1}{4}$",
      "$-\\dfrac{1}{2}$",
      "$-\\dfrac{3}{4}$",
      "$-1$",
      "$-\\dfrac{5}{4}$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "13",
    "displayNo": "13",
    "sourceOrdinal": 13,
    "sourcePageImage": "1000024893.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 14,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "좌표평면 위에 점 $A(-2,-3)$과 직선 $l:y=x$, 그리고 원 $C:(x-5)^2+(y-4)^2=4$가 있다. 직선 $l$ 위를 움직이는 점 $P$와 원 $C$ 위를 움직이는 점 $Q$에 대하여 $\\overline{AP}+\\overline{PQ}$의 값이 최소가 될 때의 점 $P,Q$를 각각 $P_0,Q_0$라 하자. 삼각형 $AP_0Q_0$의 넓이를 $S$라 할 때, $10S$의 값을 구하면? [4.9점]",
    "choices": [
      "17",
      "19",
      "21",
      "23",
      "25"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "14",
    "displayNo": "14",
    "sourceOrdinal": 14,
    "sourcePageImage": "1000024893.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 15,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "원 $x^2+y^2-4x-6y+3=0$ 위의 두 점 $A(1,0)$, $B(-1,2)$에 대하여 삼각형 $PAB$의 넓이가 최대가 되도록 하는 원 위의 한 점을 $P$라 하자. 점 $P$에서의 접선의 방정식이 $x+ay+b+c\\sqrt{5}=0$일 때, $a+b+c$의 값을 구하면? [4.9점]",
    "choices": [
      "$-6$",
      "$-5$",
      "$-4$",
      "$-3$",
      "$-2$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "15",
    "displayNo": "15",
    "sourceOrdinal": 15,
    "sourcePageImage": "1000024894.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 16,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "집합 $A=\\{x\\mid x$는 100 미만의 홀수인 자연수$\\}$의 부분집합 $B$가 다음 조건을 모두 만족시킨다.\\n&lt;조건&gt;\\n(가) 집합 $B$의 부분집합 중 원소의 개수가 2개 이상인 부분집합의 개수는 2470이다.\\n(나) 집합 $B$의 임의의 서로 다른 두 원소 $x,y$에 대하여 $x+y$는 4의 배수가 아니다.\\n(다) 집합 $B$의 원소 중 가장 작은 원소는 15이다.\\n집합 $B$의 모든 원소의 합을 $S(B)$라 할 때, $S(B)$의 최댓값을 구하면? [5점]",
    "choices": [
      "620",
      "624",
      "628",
      "632",
      "636"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "16",
    "displayNo": "16",
    "sourceOrdinal": 16,
    "sourcePageImage": "1000024894.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 17,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "좌표평면 위에 네 점 $A(0,2)$, $B(1,0)$, $C(3,1)$, $D(2,3)$을 꼭짓점으로 하는 사각형 $ABCD$가 있다. 이 사각형의 내부를 지나는 직선 $l:y=mx+n$이 선분 $AB$와 점 $P$에서 만나고, 선분 $CD$와 점 $Q$에서 만난다. 사각형 $APQD$의 넓이가 사각형 $PBCQ$의 넓이의 2배이고, 선분 $\\overline{PQ}$의 길이가 최소가 될 때, 두 상수 $m,n$에 대하여 $30(m+n)$의 값을 구하면? (단, 점 $P,Q$는 사각형의 꼭짓점이 아니다.) [5점]",
    "choices": [
      "5",
      "10",
      "15",
      "20",
      "25"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "17",
    "displayNo": "17",
    "sourceOrdinal": 17,
    "sourcePageImage": "1000024897.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 18,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "&lt;서·논술형 1&gt;\\n원 $x^2+y^2+4x-2y+1=0$을 $x$축 방향으로 3만큼, $y$축 방향으로 2만큼 평행이동한 후, 직선 $y=x$에 대하여 대칭이동한 원의 중심을 점 $C$라 하자. 직선 $2x+y-9=0$에 수직이고, 점 $C$에서 거리가 $\\sqrt{5}$인 직선을 $l$이라 할 때, 직선 $l$의 $y$절편을 구하는 과정을 풀이와 함께 상세히 서술하시오. (단, 직선 $l$의 $y$절편은 양수이다.) [5점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "서·논술형 1",
    "displayNo": "서·논술형 1",
    "sourceOrdinal": 18,
    "sourcePageImage": "1000024897.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 19,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "&lt;서·논술형 2&gt;\\n집합 $A=\\{1,2,3,4,5,6,7\\}$의 부분집합 $X$에 대하여 $X$의 모든 원소의 합을 $S(X)$라 하자. 집합 $A$의 부분집합 중 가장 큰 원소와 작은 원소의 차이가 4인 모든 부분집합을 $A_1,A_2,\\cdots,A_{10}$이라 할 때, $S(A_1)+S(A_2)+\\cdots+S(A_{10})$의 값을 구하는 과정을 풀이와 함께 상세히 서술하시오. [7점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "서·논술형 2",
    "displayNo": "서·논술형 2",
    "sourceOrdinal": 19,
    "sourcePageImage": "1000024898.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  },
  {
    "id": 20,
    "level": "",
    "category": "",
    "originalCategory": "",
    "standardCourse": "공통수학2",
    "standardUnitKey": "",
    "standardUnit": "",
    "standardUnitOrder": 0,
    "subUnitKey": "",
    "subUnit": "",
    "subUnitConfidence": "",
    "subUnitClassificationDepth": "",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "&lt;서·논술형 3&gt;\\n함수 $$f(x)=\\begin{cases}x^2+2x-14&(x\\lt8)\\\\x^2-13x+106&(x\\ge8)\\end{cases}$$와 양의 실수 $t$에 대하여 중심이 점 $(t,f(t))$이고 반지름의 길이가 $\\sqrt{5}t$인 원 $C$가 있다. 상수 $k$에 대하여 원 $C$가 직선 $2x-y+k=0$과 만나는 서로 다른 점의 개수를 함수 $g(t)$라 할 때, 함수 $g(t)$는 다음 조건을 만족시킨다.\\n&lt;조건&gt;\\n(가) $g(3)=1$\\n(나) $g(4)\\times g(9)=4$\\n$a-2\\lt t\\lt a$인 모든 실수 $t$에 대하여 $g(t)=2$를 만족시키는 실수 $a$의 최댓값을 구하는 과정을 풀이와 함께 상세히 서술하시오. [8점]",
    "choices": [],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "서·논술형 3",
    "displayNo": "서·논술형 3",
    "sourceOrdinal": 20,
    "sourcePageImage": "1000024898.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "not_extracted_by_user_instruction",
    "solutionSource": "not_extracted_by_user_instruction",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_ONLY_PENDING"
  }
];
