window.examTitle = "26_금당고_2학기_중간_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "원이 되기 위한 조건",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "원의 방정식",
      "원이 되기 위한 조건",
      "정수조건"
    ],
    "wide": false,
    "content": "방정식 $x^2+y^2+4x-6y+k^2-4k+8=0$이 나타내는 도형이 원이 되도록 하는 정수 $k$의 개수는? [4.5점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "⑤",
    "solution": "주어진 방정식을 완전제곱식으로 정리한다.\n$x^2+4x=(x+2)^2-4$이고\n$y^2-6y=(y-3)^2-9$이므로\n$(x+2)^2+(y-3)^2=9-(k-2)^2$이다.\n이 식이 원을 나타내려면 반지름의 제곱이 양수여야 하므로\n$9-(k-2)^2>0$이다.\n따라서\n$|k-2|<3$,\n즉 $-1<k<5$이다.\n이 범위의 정수는\n$0,1,2,3,4$의 $5$개이다.\n\n따라서 정답은 ⑤이다.",
    "sourceQuestionNo": "1",
    "displayNo": "1",
    "sourceOrdinal": 1,
    "sourcePageImage": "1000024890.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_CIRCLE_EQUATION",
    "templateKey": "TM_CIRCLE_EXISTENCE_CONDITION",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_INTEGER"
    ],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 2,
    "level": "중",
    "category": "집합의 원소의 개수",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "원소의개수",
      "공집합"
    ],
    "wide": false,
    "content": "다음 중 옳은 것은? [4.5점]",
    "choices": [
      "$n(\\{1,2,3\\})\\lt n(\\{4,5,6\\})$",
      "$A=\\{0\\}$이면 $n(A)=0$이다.",
      "$n(\\{\\varnothing\\})-n(\\varnothing)=1$",
      "$n(A)=0$이면 $A=\\{\\varnothing\\}$이다.",
      "$n(\\{55\\})-n(\\{50\\})=5$"
    ],
    "answer": "③",
    "solution": "각 보기의 집합의 원소의 개수를 확인한다.\n① $\\{1,2,3\\}$과 $\\{4,5,6\\}$의 원소 수는 모두 $3$이므로 거짓이다.\n② $\\{0\\}$은 원소가 $0$인 집합이 아니라, 원소 $0$을 하나 가지는 집합이므로 $n(\\{0\\})=1$이다.\n③ $\\{\\varnothing\\}$은 공집합 $\\varnothing$을 하나의 원소로 가지므로 $n(\\{\\varnothing\\})=1$이고, $n(\\varnothing)=0$이다.\n따라서\n$n(\\{\\varnothing\\})-n(\\varnothing)=1$이므로 참이다.\n④ $n(A)=0$이면 $A=\\varnothing$이다.\n⑤ $n(\\{55\\})=n(\\{50\\})=1$이므로 그 차는 $0$이다.\n\n따라서 정답은 ③이다.",
    "sourceQuestionNo": "2",
    "displayNo": "2",
    "sourceOrdinal": 2,
    "sourcePageImage": "1000024890.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_SET_CARDINALITY",
    "templateKey": "TPL_SET_CARDINALITY_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 3,
    "level": "중",
    "category": "원의 접선",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "원의 방정식",
      "접선",
      "접점"
    ],
    "wide": false,
    "content": "원 $x^2+y^2=13$위의 점 $(-2,3)$에서의 접선이 점 $(a,5)$를 지날 때, $a$의 값은? [4.5점]",
    "choices": [
      "$-3$",
      "$-1$",
      "1",
      "3",
      "10"
    ],
    "answer": "③",
    "solution": "원 $x^2+y^2=13$ 위의 점 $(x_1,y_1)$에서의 접선은\n$xx_1+yy_1=13$으로 나타낼 수 있다.\n점 $(-2,3)$에서의 접선은\n$-2x+3y=13$이다.\n이 직선이 $(a,5)$를 지나므로\n$-2a+3\\cdot5=13$이다.\n따라서\n$-2a=-2$,\n$a=1$이다.\n\n따라서 정답은 ③이다.",
    "sourceQuestionNo": "3",
    "displayNo": "3",
    "sourceOrdinal": 3,
    "sourcePageImage": "1000024890.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_CIRCLE_TANGENT",
    "templateKey": "TM_TANGENT_AT_POINT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 4,
    "level": "하",
    "category": "평행이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "도형의 이동",
      "평행이동",
      "좌표"
    ],
    "wide": false,
    "content": "좌표평면 위의 점 $(-2,3)$을 $x$축 방향으로 $a$만큼, $y$축의 방향으로 4만큼 평행이동한 점의 좌표가 $(-1,b)$일 때, $a-b$의 값은? [4.5점]",
    "choices": [
      "$-6$",
      "$-\\dfrac{7}{4}$",
      "$-5$",
      "$\\dfrac{3}{2}$",
      "3"
    ],
    "answer": "①",
    "solution": "점 $(-2,3)$을 $x$축 방향으로 $a$, $y$축 방향으로 $4$만큼 평행이동하면\n$(-2+a,\\,7)$이 된다.\n이 좌표가 $(-1,b)$와 같으므로\n$-2+a=-1$에서 $a=1$이고,\n$b=7$이다.\n따라서\n$a-b=1-7=-6$이다.\n\n따라서 정답은 ①이다.",
    "sourceQuestionNo": "4",
    "displayNo": "4",
    "sourceOrdinal": 4,
    "sourcePageImage": "1000024890.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_MOVE_POINT_TRANSLATION",
    "templateKey": "TT_POINT_TRANSLATION_COORD",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 1,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 5,
    "level": "하",
    "category": "대칭이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "도형의 이동",
      "대칭이동",
      "원"
    ],
    "wide": false,
    "content": "원 $(x-3)^2+(y+2)^2=16$을 $y=x$에 대하여 대칭이동한 원의 중심의 좌표가 $(a,b)$이고 반지름의 길이가 $c$일 때, $a-b+c$의 값은? [4.6점]",
    "choices": [
      "$-1$",
      "$-2$",
      "3",
      "5",
      "9"
    ],
    "answer": "①",
    "solution": "원 $(x-3)^2+(y+2)^2=16$의 중심은 $(3,-2)$이고 반지름의 길이는 $4$이다.\n직선 $y=x$에 대하여 대칭이동하면 점의 두 좌표가 서로 바뀌므로 중심은\n$(-2,3)$으로 이동한다.\n대칭이동은 길이를 보존하므로 반지름은 그대로 $4$이다.\n따라서\n$a=-2$, $b=3$, $c=4$이고\n$a-b+c=-2-3+4=-1$이다.\n\n따라서 정답은 ①이다.",
    "sourceQuestionNo": "5",
    "displayNo": "5",
    "sourceOrdinal": 5,
    "sourcePageImage": "1000024891.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_MOVE_CIRCLE_REFLECTION",
    "templateKey": "TT_CIRCLE_REFLECTION_CENTER_RELATION",
    "crossConceptKeys": [
      "CC_CIRCLE_CENTER_RADIUS"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 1,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 6,
    "level": "하",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "subUnitKey": "H22-C2-01-GEOMETRY_APPLICATION",
    "subUnit": "도형의 방정식 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "평면좌표",
      "무게중심"
    ],
    "wide": false,
    "content": "한 직선 위에 있지 않은 서로 다른 세 점 $A(5,2)$, $B(2,4)$, $C(-1,-3)$을 꼭짓점으로 하는 삼각형 $ABC$의 무게중심이 $G(a,b)$이다. 이때 $a+b$의 값은? [4.6점]",
    "choices": [
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "answer": "②",
    "solution": "삼각형의 무게중심은 세 꼭짓점의 $x$좌표와 $y$좌표의 평균이다.\n따라서\n$a=\\dfrac{5+2+(-1)}3=2$,\n$b=\\dfrac{2+4+(-3)}3=1$이다.\n그러므로\n$a+b=2+1=3$이다.\n\n따라서 정답은 ②이다.",
    "sourceQuestionNo": "6",
    "displayNo": "6",
    "sourceOrdinal": 6,
    "sourcePageImage": "1000024891.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_COORD_CENTROID",
    "templateKey": "TPL_CENTROID_DIRECT",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 1,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 7,
    "level": "중",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "직선의 방정식",
      "수직",
      "기울기"
    ],
    "wide": false,
    "content": "점 $(4,a)$를 지나고 직선 $4x+3y-2=0$에 수직인 직선이 점 $(-4,1)$을 지날 때, $a$의 값은? [4.6점]",
    "choices": [
      "$\\dfrac{28}{3}$",
      "$\\dfrac{27}{4}$",
      "$\\dfrac{13}{2}$",
      "7",
      "12"
    ],
    "answer": "④",
    "solution": "직선 $4x+3y-2=0$을 $y$에 대하여 정리하면\n$y=-\\dfrac43x+\\dfrac23$이므로 기울기는 $-\\dfrac43$이다.\n이에 수직인 직선의 기울기는 $\\dfrac34$이다.\n구하는 직선은 점 $(-4,1)$을 지나므로\n$y-1=\\dfrac34(x+4)$이다.\n점 $(4,a)$도 이 직선 위에 있으므로\n$a-1=\\dfrac34\\cdot8=6$이다.\n따라서\n$a=7$이다.\n\n따라서 정답은 ④이다.",
    "sourceQuestionNo": "7",
    "displayNo": "7",
    "sourceOrdinal": 7,
    "sourcePageImage": "1000024891.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_LINE_EQUATION",
    "templateKey": "TPL_LINE_PERPENDICULAR",
    "crossConceptKeys": [
      "CC_PERPENDICULAR"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 8,
    "level": "중",
    "category": "서로 같은 집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "집합의상등",
      "매개변수"
    ],
    "wide": false,
    "content": "두 집합 $A=\\{a^2-5a,8,12\\}$, $B=\\{6,a+2,2a\\}$에 대하여 $A\\subset B$이고 $B\\subset A$일 때, 상수 $a$의 값은? [4.7점]",
    "choices": [
      "$-1$",
      "1",
      "3",
      "6",
      "8"
    ],
    "answer": "④",
    "solution": "$A\\subset B$이고 $B\\subset A$이므로 두 집합은 서로 같다.\n즉 $A=B$이다.\n집합 $B$에는 원소 $6$이 있으므로 집합 $A=\\{a^2-5a,8,12\\}$에도 $6$이 있어야 한다.\n$8$과 $12$는 $6$이 아니므로\n$a^2-5a=6$이다.\n$a^2-5a-6=0$,\n$(a-6)(a+1)=0$이므로\n$a=6$ 또는 $a=-1$이다.\n$a=-1$이면\n$A=\\{6,8,12\\}$, $B=\\{6,1,-2\\}$로 두 집합이 같지 않다.\n$a=6$이면\n$A=B=\\{6,8,12\\}$가 된다.\n따라서 $a=6$이다.\n\n따라서 정답은 ④이다.",
    "sourceQuestionNo": "8",
    "displayNo": "8",
    "sourceOrdinal": 8,
    "sourcePageImage": "1000024891.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_SET_EQUALITY",
    "templateKey": "TPL_EQUAL_SET_PARAMETER",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 9,
    "level": "중",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "subUnitKey": "H22-C2-01-GEOMETRY_APPLICATION",
    "subUnit": "도형의 방정식 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "평면좌표",
      "내분점"
    ],
    "wide": false,
    "content": "두 점 $A(-3,-8)$, $B(15,1)$에 대하여 선분 $AB$ 위의 점 $P$가 $5\\overline{AP}=4\\overline{BP}$를 만족시킬 때, 점 $P$의 좌표를 $(p,q)$라 하자. $p+q$의 값은? [4.7점]",
    "choices": [
      "0",
      "1",
      "2",
      "3",
      "4"
    ],
    "answer": "②",
    "solution": "$5\\overline{AP}=4\\overline{BP}$이므로\n$\\overline{AP}:\\overline{PB}=4:5$이다.\n점 $P$는 선분 $AB$를 $4:5$로 내분하므로\n$P=\\left(\\dfrac{5(-3)+4(15)}9,\\dfrac{5(-8)+4(1)}9\\right)$이다.\n따라서\n$P=(5,-4)$이므로\n$p+q=5+(-4)=1$이다.\n\n따라서 정답은 ②이다.",
    "sourceQuestionNo": "9",
    "displayNo": "9",
    "sourceOrdinal": 9,
    "sourcePageImage": "1000024892.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_COORD_SECTION",
    "templateKey": "TPL_SECTION_INTERNAL",
    "crossConceptKeys": [
      "CC_INTERNAL_DIVISION"
    ],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 2,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 10,
    "level": "중",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "직선의 방정식",
      "정점",
      "점과직선의거리"
    ],
    "wide": false,
    "content": "직선 $3x-y-2+k(x+y-6)=0$이 실수 $k$값에 관계없이 항상 점 $P$를 지날 때, 점 $P$와 직선 $3x+4y+3=0$ 사이의 거리를 구하면? [4.7점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "⑤",
    "solution": "직선\n$3x-y-2+k(x+y-6)=0$\n이 모든 실수 $k$에 대하여 한 점 $P$를 지나려면\n$k$가 없는 부분과 $k$의 계수가 되는 부분이 각각 $0$이어야 한다.\n따라서\n$3x-y-2=0$,\n$x+y-6=0$을 연립한다.\n두 식을 더하면\n$4x-8=0$이므로 $x=2$이고,\n$y=4$이다.\n따라서 $P=(2,4)$이다.\n점 $P$에서 직선 $3x+4y+3=0$까지의 거리는\n$\\dfrac{|3\\cdot2+4\\cdot4+3|}{\\sqrt{3^2+4^2}}$\n$=\\dfrac{25}{5}=5$이다.\n\n따라서 정답은 ⑤이다.",
    "sourceQuestionNo": "10",
    "displayNo": "10",
    "sourceOrdinal": 10,
    "sourcePageImage": "1000024892.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_LINE_FAMILY_COMMON_POINT",
    "templateKey": "TPL_LINE_FAMILY_COMMON_POINT_APPLICATION",
    "crossConceptKeys": [
      "CC_POINT_LINE_DISTANCE"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 11,
    "level": "중",
    "category": "두 직선의 위치 관계",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-RELATION",
    "subUnit": "두 직선의 관계",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "직선의 방정식",
      "평행",
      "수직",
      "매개변수"
    ],
    "wide": false,
    "content": "두 직선 $(k-1)x+y-4=0$, $kx-2y+3=0$이 평행하도록 하는 상수 $k$의 값을 $a$, 수직이 되도록 하는 상수 $k$의 값을 $b$라 할 때, $ab$의 값은? [4.7점] (단, $b\\gt0$)",
    "choices": [
      "$\\dfrac{1}{3}$",
      "$\\dfrac{2}{3}$",
      "1",
      "$\\dfrac{4}{3}$",
      "$\\dfrac{5}{3}$"
    ],
    "answer": "④",
    "solution": "첫째 직선\n$(k-1)x+y-4=0$\n의 기울기는 $1-k$이고,\n둘째 직선\n$kx-2y+3=0$\n의 기울기는 $\\dfrac{k}{2}$이다.\n\n두 직선이 평행할 때\n$1-k=\\dfrac{k}{2}$이므로\n$2-2k=k$,\n$k=\\dfrac23$이다.\n따라서 $a=\\dfrac23$이다.\n\n두 직선이 수직일 때 기울기의 곱이 $-1$이므로\n$(1-k)\\dfrac{k}{2}=-1$이다.\n$k-k^2=-2$,\n$k^2-k-2=0$,\n$(k-2)(k+1)=0$이므로\n$k=2$ 또는 $k=-1$이다.\n$b>0$이므로 $b=2$이다.\n\n따라서\n$ab=\\dfrac23\\cdot2=\\dfrac43$이다.\n\n따라서 정답은 ④이다.",
    "sourceQuestionNo": "11",
    "displayNo": "11",
    "sourceOrdinal": 11,
    "sourcePageImage": "1000024892.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_LINE_RELATION",
    "templateKey": "TPL_RELATION_PARALLEL_PERP_COMBINED",
    "crossConceptKeys": [
      "CC_PARALLEL_LINES",
      "CC_PERPENDICULAR"
    ],
    "conditionKeys": [
      "COND_POSITIVE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 12,
    "level": "상",
    "category": "원과 직선의 위치 관계",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-INTERSECTION",
    "subUnit": "원과 직선·원의 관계",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "원의 방정식",
      "현의길이",
      "점과직선의거리",
      "중심"
    ],
    "wide": false,
    "content": "직선 $3x-4y+a=0$이 원 $C_1:x^2+y^2-2x-4y+1=0$의 넓이를 이등분한다. 이 직선이 또 다른 원 $C_2:x^2+y^2+bx+cy+d=0$과 서로 다른 두 점 $A,B$에서 만날 때, 선분 $\\overline{AB}$의 길이는 8이다. 원 $C_2$의 중심의 좌표가 $(2,-1)$일 때, 상수 $a,b,c,d$에 대하여 $a+b+c+d$의 값을 구하면? [4.8점]",
    "choices": [
      "$-19$",
      "$-17$",
      "$-15$",
      "$-13$",
      "$-11$"
    ],
    "answer": "②",
    "solution": "먼저 원 $C_1$의 중심을 구한다.\n$x^2+y^2-2x-4y+1=0$을 완전제곱식으로 정리하면\n$(x-1)^2+(y-2)^2=4$이므로 중심은 $(1,2)$이다.\n직선 $3x-4y+a=0$이 원의 넓이를 이등분하려면 원의 중심을 지나야 한다.\n따라서\n$3\\cdot1-4\\cdot2+a=0$에서\n$a=5$이다.\n\n원 $C_2:x^2+y^2+bx+cy+d=0$의 중심이 $(2,-1)$이므로\n$-\\dfrac b2=2$, $-\\dfrac c2=-1$이다.\n따라서\n$b=-4$, $c=2$이다.\n그러면\n$(x-2)^2+(y+1)^2=5-d$이므로 반지름의 제곱은 $5-d$이다.\n\n직선은 $3x-4y+5=0$이고,\n원 $C_2$의 중심 $(2,-1)$에서 이 직선까지의 거리는\n$\\dfrac{|3\\cdot2-4(-1)+5|}{5}=3$이다.\n현 $AB$의 길이가 $8$이므로 반쪽 길이는 $4$이다.\n중심에서 현에 내린 수선은 현을 이등분하므로\n$r^2=3^2+4^2=25$이다.\n따라서\n$5-d=25$에서 $d=-20$이다.\n\n그러므로\n$a+b+c+d=5-4+2-20=-17$이다.\n\n따라서 정답은 ②이다.",
    "sourceQuestionNo": "12",
    "displayNo": "12",
    "sourceOrdinal": 12,
    "sourcePageImage": "1000024893.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_CIRCLE_LINE_RELATION",
    "templateKey": "TM_CIRCLE_CHORD_LENGTH",
    "crossConceptKeys": [
      "CC_CIRCLE_CENTER_RADIUS",
      "CC_POINT_LINE_DISTANCE"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 13,
    "level": "중",
    "category": "원의 접선",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "원의 방정식",
      "접선",
      "기울기"
    ],
    "wide": false,
    "content": "점 $(-1,1)$에서 원 $x^2+y^2-6x-4y+9=0$에 그은 두 접선의 기울기의 곱은? [4.8점]",
    "choices": [
      "$-\\dfrac{1}{4}$",
      "$-\\dfrac{1}{2}$",
      "$-\\dfrac{3}{4}$",
      "$-1$",
      "$-\\dfrac{5}{4}$"
    ],
    "answer": "①",
    "solution": "점 $(-1,1)$을 지나는 기울기 $m$인 직선을\n$y-1=m(x+1)$이라 하자.\n이를 일반형으로 쓰면\n$mx-y+m+1=0$이다.\n\n주어진 원을 표준형으로 고치면\n$(x-3)^2+(y-2)^2=4$이므로 중심은 $(3,2)$이고 반지름은 $2$이다.\n직선이 원에 접하려면 중심에서 직선까지의 거리가 $2$여야 한다.\n따라서\n$\\dfrac{|3m-2+m+1|}{\\sqrt{m^2+1}}=2$이다.\n즉\n$\\dfrac{|4m-1|}{\\sqrt{m^2+1}}=2$이고,\n양변을 제곱하면\n$(4m-1)^2=4(m^2+1)$이다.\n정리하면\n$12m^2-8m-3=0$이다.\n\n두 접선의 기울기를 $m_1,m_2$라 하면 근과 계수의 관계에 의해\n$m_1m_2=\\dfrac{-3}{12}=-\\dfrac14$이다.\n\n따라서 정답은 ①이다.",
    "sourceQuestionNo": "13",
    "displayNo": "13",
    "sourceOrdinal": 13,
    "sourcePageImage": "1000024893.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_CIRCLE_TANGENT",
    "templateKey": "TM_TANGENT_TWO_SLOPES",
    "crossConceptKeys": [
      "CC_SLOPE"
    ],
    "conditionKeys": [],
    "integrationPattern": "NONE",
    "difficultyBucket": 3,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 14,
    "level": "상",
    "category": "대칭이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "도형의 이동",
      "대칭이동",
      "최단거리",
      "원의방정식",
      "넓이"
    ],
    "wide": false,
    "content": "좌표평면 위에 점 $A(-2,-3)$과 직선 $l:y=x$, 그리고 원 $C:(x-5)^2+(y-4)^2=4$가 있다. 직선 $l$ 위를 움직이는 점 $P$와 원 $C$ 위를 움직이는 점 $Q$에 대하여 $\\overline{AP}+\\overline{PQ}$의 값이 최소가 될 때의 점 $P,Q$를 각각 $P_0,Q_0$라 하자. 삼각형 $AP_0Q_0$의 넓이를 $S$라 할 때, $10S$의 값을 구하면? [4.9점]",
    "choices": [
      "17",
      "19",
      "21",
      "23",
      "25"
    ],
    "answer": "③",
    "solution": "직선 $y=x$에 대하여 점 $A(-2,-3)$을 대칭이동한 점을 $A'$라 하면\n$A'=(-3,-2)$이다.\n점 $P$가 $y=x$ 위에 있으므로\n$AP=A'P$이다.\n\n원의 중심을 $C=(5,4)$라 하자.\n먼저 원 바깥에 있는 점 $P$를 생각하면, 고정된 $P$에서 $PQ$가 최소가 되는 점 $Q$는 $C,P,Q$가 한 직선 위에 있고\n$PQ=PC-2$가 되도록 잡은 점이다.\n따라서\n$AP+PQ=A'P+PC-2\\ge A'C-2$이다.\n$A'C=\\sqrt{8^2+6^2}=10$이므로\n$AP+PQ\\ge8$이다.\n\n선분 $A'C$와 $y=x$의 교점을 구하면\n$A'C$의 방정식은\n$y=\\dfrac34x+\\dfrac14$이고,\n$y=x$와의 교점은 $P_0=(1,1)$이다.\n이때\n$CP_0=5>2$이므로 $P_0$는 실제로 원의 바깥에 있고\n$AP_0+P_0Q_0=8$을 만들 수 있다.\n\n또 $y=x$와 원이 만나는 두 점 중 작은 $x$좌표는\n$\\dfrac{9-\\sqrt7}{2}>3$이다.\n원 내부의 $P=(t,t)$는 이 값보다 큰 범위에 있고, 그 범위에서는 $AP>8$이므로 원 내부에서는 위의 값 $8$보다 작게 만들 수 없다.\n따라서 최솟값을 만드는 점은 $P_0=(1,1)$이다.\n\n$C$에서 $P_0$ 방향의 벡터는 $(-4,-3)$이고 그 길이는 $5$이다.\n반지름이 $2$이므로\n$Q_0=C+\\dfrac25(-4,-3)=\\left(\\dfrac{17}{5},\\dfrac{14}{5}\\right)$이다.\n\n$\\overrightarrow{AP_0}=(3,4)$,\n$\\overrightarrow{AQ_0}=\\left(\\dfrac{27}{5},\\dfrac{29}{5}\\right)$이므로\n삼각형 $AP_0Q_0$의 넓이는\n$\\dfrac12\\left|3\\cdot\\dfrac{29}{5}-4\\cdot\\dfrac{27}{5}\\right|=\\dfrac{21}{10}$이다.\n따라서\n$10S=21$이다.\n\n따라서 정답은 ③이다.",
    "sourceQuestionNo": "14",
    "displayNo": "14",
    "sourceOrdinal": 14,
    "sourcePageImage": "1000024893.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_MOVE_REFLECTION_SHORTEST",
    "templateKey": "TT_SHORTEST_WITH_POSITION",
    "crossConceptKeys": [
      "CC_CIRCLE_CENTER_RADIUS"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 15,
    "level": "상",
    "category": "원의 접선",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "원의 방정식",
      "접선",
      "삼각형넓이",
      "최댓값"
    ],
    "wide": false,
    "content": "원 $x^2+y^2-4x-6y+3=0$ 위의 두 점 $A(1,0)$, $B(-1,2)$에 대하여 삼각형 $PAB$의 넓이가 최대가 되도록 하는 원 위의 한 점을 $P$라 하자. 점 $P$에서의 접선의 방정식이 $x+ay+b+c\\sqrt{5}=0$일 때, $a+b+c$의 값을 구하면? [4.9점]",
    "choices": [
      "$-6$",
      "$-5$",
      "$-4$",
      "$-3$",
      "$-2$"
    ],
    "answer": "①",
    "solution": "삼각형 $PAB$에서 밑변 $AB$는 고정되어 있으므로 넓이를 최대로 하려면 점 $P$와 직선 $AB$ 사이의 거리가 최대가 되어야 한다.\n두 점 $A(1,0)$, $B(-1,2)$를 지나는 직선은\n$x+y-1=0$이다.\n\n주어진 원을 표준형으로 정리하면\n$(x-2)^2+(y-3)^2=10$이므로 중심은 $C=(2,3)$이고 반지름은 $\\sqrt{10}$이다.\n중심 $C$는 직선 $x+y-1=0$의 양의 쪽에 있으므로, 직선에서 가장 멀리 떨어진 원 위의 점은 중심에서 법선벡터 $(1,1)$ 방향으로 반지름만큼 이동한 점이다.\n단위 법선벡터가 $\\dfrac1{\\sqrt2}(1,1)$이므로 이동량은\n$\\sqrt{10}\\cdot\\dfrac1{\\sqrt2}(1,1)=(\\sqrt5,\\sqrt5)$이다.\n따라서\n$P=(2+\\sqrt5,\\,3+\\sqrt5)$이다.\n\n원 위의 점 $P$에서의 접선은 반지름 $CP$에 수직이다.\n원의 중심형을 이용하면\n$\\sqrt5(x-2)+\\sqrt5(y-3)=10$이고,\n정리하면\n$x+y-5-2\\sqrt5=0$이다.\n이를\n$x+ay+b+c\\sqrt5=0$과 비교하면\n$a=1$, $b=-5$, $c=-2$이다.\n따라서\n$a+b+c=1-5-2=-6$이다.\n\n따라서 정답은 ①이다.",
    "sourceQuestionNo": "15",
    "displayNo": "15",
    "sourceOrdinal": 15,
    "sourcePageImage": "1000024894.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_CIRCLE_TANGENT",
    "templateKey": "TM_TANGENT_AT_POINT",
    "crossConceptKeys": [
      "CC_POINT_LINE_DISTANCE"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 16,
    "level": "상",
    "category": "집합의 원소의 합의 최대·최소",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "집합",
      "부분집합",
      "원소의합",
      "최댓값",
      "나머지조건"
    ],
    "wide": false,
    "content": "집합 $A=\\{x\\mid x$는 100 미만의 홀수인 자연수$\\}$의 부분집합 $B$가 다음 조건을 모두 만족시킨다.\\n&lt;조건&gt;\\n(가) 집합 $B$의 부분집합 중 원소의 개수가 2개 이상인 부분집합의 개수는 247이다.\\n(나) 집합 $B$의 임의의 서로 다른 두 원소 $x,y$에 대하여 $x+y$는 4의 배수가 아니다.\\n(다) 집합 $B$의 원소 중 가장 작은 원소는 15이다.\\n집합 $B$의 모든 원소의 합을 $S(B)$라 할 때, $S(B)$의 최댓값을 구하면? [5점]",
    "choices": [
      "620",
      "624",
      "628",
      "632",
      "636"
    ],
    "answer": "②",
    "solution": "집합 $B$의 원소의 개수를 $n$이라 하자.\n원소가 $n$개인 집합의 부분집합은 모두 $2^n$개이다.\n이 중 원소가 $0$개인 공집합 $1$개와 원소가 $1$개인 부분집합 $n$개를 제외한 개수가 $247$이므로\n$2^n-n-1=247$이다.\n$n=8$일 때\n$256-8-1=247$이므로\n$B$의 원소는 $8$개이다.\n\n가장 작은 원소가 $15$이므로 $15\\in B$이다.\n$15$는 $4$로 나눈 나머지가 $3$이다.\n서로 다른 두 원소의 합이 $4$의 배수가 되면 안 되므로, $B$에 $4$로 나눈 나머지가 $1$인 수가 하나라도 있으면 $15$와의 합이 $4$의 배수가 되어 조건에 어긋난다.\n따라서 $B$의 모든 원소는 $4$로 나눈 나머지가 $3$인 홀수여야 한다.\n\n합을 최대로 하려면 가장 작은 원소 $15$를 반드시 포함하고, 나머지 $7$개는 $100$ 미만에서 $4$로 나눈 나머지가 $3$인 수 중 가장 큰 것부터 고른다.\n따라서\n$B=\\{15,75,79,83,87,91,95,99\\}$로 잡을 때 합이 최대이다.\n이때\n$S(B)=15+75+79+83+87+91+95+99=624$이다.\n\n따라서 정답은 ②이다.",
    "sourceQuestionNo": "16",
    "displayNo": "16",
    "sourceOrdinal": 16,
    "sourcePageImage": "1000024894.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_SET_EXTREMUM",
    "templateKey": "TPL_SET_SUM_EXTREMUM",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_NATURAL_NUMBER",
      "COND_RANGE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 17,
    "level": "상",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "subUnitKey": "H22-C2-01-GEOMETRY_APPLICATION",
    "subUnit": "도형의 방정식 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "객관식",
      "평면좌표",
      "사각형넓이",
      "거리최솟값",
      "직선의방정식"
    ],
    "wide": false,
    "content": "좌표평면 위에 네 점 $A(0,2)$, $B(1,0)$, $C(3,1)$, $D(2,3)$을 꼭짓점으로 하는 사각형 $ABCD$가 있다. 이 사각형의 내부를 지나는 직선 $l:y=mx+n$이 선분 $AB$와 점 $P$에서 만나고, 선분 $CD$와 점 $Q$에서 만난다. 사각형 $APQD$의 넓이가 사각형 $PBCQ$의 넓이의 2배이고, 선분 $\\overline{PQ}$의 길이가 최소가 될 때, 두 상수 $m,n$에 대하여 $30(m+n)$의 값을 구하면? (단, 점 $P,Q$는 사각형의 꼭짓점이 아니다.) [5점]",
    "choices": [
      "5",
      "10",
      "15",
      "20",
      "25"
    ],
    "answer": "⑤",
    "solution": "점 $P$가 선분 $AB$ 위에 있으므로\n$P=A+s(B-A)=(s,\\,2-2s)$\n로 두고,\n점 $Q$가 선분 $CD$ 위에 있으므로\n$Q=D+t(C-D)=(2+t,\\,3-2t)$\n로 두자.\n점 $P,Q$가 꼭짓점이 아니므로 $0<s,t<1$이다.\n\n사각형 $ABCD$의 넓이는 좌표를 이용하면 $5$이다.\n$APQD:PBCQ=2:1$이므로\n$APQD$의 넓이는 $\\dfrac{10}{3}$이다.\n좌표를 이용하여 사각형 $APQD$의 넓이를 계산하면\n$\\dfrac52(s+t)$이므로\n$\\dfrac52(s+t)=\\dfrac{10}{3}$,\n즉\n$s+t=\\dfrac43$이다.\n\n이제\n$PQ^2=(2+t-s)^2+(1-2t+2s)^2$이다.\n$d=s-t$라 두면\n$PQ^2=(2-d)^2+(1+2d)^2$\n$=5+5d^2$이다.\n따라서 $PQ$가 최소가 되려면 $d=0$, 즉 $s=t$이어야 한다.\n$s+t=\\dfrac43$이므로\n$s=t=\\dfrac23$이다.\n\n따라서\n$P=\\left(\\dfrac23,\\dfrac23\\right)$,\n$Q=\\left(\\dfrac83,\\dfrac53\\right)$이다.\n직선 $PQ$의 기울기는\n$m=\\dfrac{\\frac53-\\frac23}{\\frac83-\\frac23}$\n$=\\dfrac12$이다.\n$P$를 $y=mx+n$에 대입하면\n$\\dfrac23=\\dfrac12\\cdot\\dfrac23+n$이므로\n$n=\\dfrac13$이다.\n따라서\n$30(m+n)=30\\left(\\dfrac12+\\dfrac13\\right)=25$이다.\n\n따라서 정답은 ⑤이다.",
    "sourceQuestionNo": "17",
    "displayNo": "17",
    "sourceOrdinal": 17,
    "sourcePageImage": "1000024897.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_COORD_DISTANCE_OPTIMIZATION",
    "templateKey": "TPL_DISTANCE_SQSUM_MIN",
    "crossConceptKeys": [
      "CC_LINE_EQUATION"
    ],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 5,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 18,
    "level": "중",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형",
      "도형의 이동",
      "평행이동",
      "대칭이동",
      "점과직선의거리"
    ],
    "wide": false,
    "content": "&lt;서·논술형 1&gt;\\n원 $x^2+y^2+4x-2y+1=0$을 $x$축 방향으로 3만큼, $y$축 방향으로 2만큼 평행이동한 후, 직선 $y=x$에 대하여 대칭이동한 원의 중심을 점 $C$라 하자. 직선 $2x+y-9=0$에 수직이고, 점 $C$에서 거리가 $\\sqrt{5}$인 직선을 $l$이라 할 때, 직선 $l$의 $y$절편을 구하는 과정을 풀이와 함께 상세히 서술하시오. (단, 직선 $l$의 $y$절편은 양수이다.) [5점]",
    "choices": [],
    "answer": "2",
    "solution": "먼저 원의 중심을 구한다.\n$x^2+y^2+4x-2y+1=0$을 완전제곱식으로 정리하면\n$(x+2)^2+(y-1)^2=4$이므로 원의 중심은 $(-2,1)$이다.\n\n이 원을 $x$축 방향으로 $3$, $y$축 방향으로 $2$만큼 평행이동하면 중심은\n$(1,3)$이 된다.\n이 점을 직선 $y=x$에 대하여 대칭이동하면 두 좌표가 서로 바뀌므로\n$C=(3,1)$이다.\n\n직선 $2x+y-9=0$의 기울기는 $-2$이므로 이에 수직인 직선 $l$의 기울기는 $\\dfrac12$이다.\n따라서 $l$을\n$x-2y+c=0$\n이라 둘 수 있다.\n점 $C=(3,1)$에서 이 직선까지의 거리가 $\\sqrt5$이므로\n$\\dfrac{|3-2+c|}{\\sqrt{1^2+(-2)^2}}=\\sqrt5$이다.\n따라서\n$\\dfrac{|c+1|}{\\sqrt5}=\\sqrt5$,\n$|c+1|=5$이다.\n그러므로\n$c=4$ 또는 $c=-6$이다.\n\n직선의 $y$절편은 $x=0$일 때 $y=\\dfrac c2$이다.\n문제에서 $y$절편이 양수라고 했으므로 $c=4$이고,\n$y$절편은 $2$이다.\n\n따라서 구하는 값은 $2$이다.",
    "sourceQuestionNo": "서·논술형 1",
    "displayNo": "서·논술형 1",
    "sourceOrdinal": 18,
    "sourcePageImage": "1000024897.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_MOVE_COMPOSITE",
    "templateKey": "TT_COMPOSITE_CIRCLE",
    "crossConceptKeys": [
      "CC_POINT_LINE_DISTANCE",
      "CC_PERPENDICULAR"
    ],
    "conditionKeys": [
      "COND_POSITIVE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 3,
    "difficultyConfidence": "medium",
    "difficultyBoundaryFlag": "B34",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 19,
    "level": "상",
    "category": "집합의 원소의 합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형",
      "집합",
      "부분집합",
      "원소의합",
      "경우분류"
    ],
    "wide": false,
    "content": "&lt;서·논술형 2&gt;\\n집합 $A=\\{1,2,3,4,5,6,7\\}$의 부분집합 $X$에 대하여 $X$의 모든 원소의 합을 $S(X)$라 하자. 집합 $A$의 부분집합 중 가장 큰 원소와 작은 원소의 차이가 4인 모든 부분집합을 $A_1,A_2,\\cdots,A_n$이라 할 때, $S(A_1)+S(A_2)+\\cdots+S(A_n)$의 값을 구하는 과정을 풀이와 함께 상세히 서술하시오. [7점]",
    "choices": [],
    "answer": "336",
    "solution": "가장 작은 원소와 가장 큰 원소의 차이가 $4$이므로 가능한 양 끝 원소는\n$(1,5)$, $(2,6)$, $(3,7)$의 세 경우이다.\n\n가장 작은 원소가 $i$, 가장 큰 원소가 $i+4$인 경우를 생각하자.\n두 끝 원소 $i$, $i+4$는 반드시 포함되고,\n그 사이의 세 원소 $i+1,i+2,i+3$은 각각 포함하거나 포함하지 않을 수 있다.\n따라서 한 쌍의 끝점마다 $2^3=8$개의 부분집합이 생긴다.\n그러므로 전체 부분집합의 개수는\n$n=3\\cdot8=24$이다.\n\n이제 한 끝점 쌍 $(i,i+4)$에 해당하는 $8$개 부분집합의 원소 합을 모두 더한다.\n두 끝 원소는 $8$개 부분집합에 모두 들어가므로 기여하는 합은\n$8\\{i+(i+4)\\}=16i+32$이다.\n중간의 세 원소는 각각 절반인 $4$개 부분집합에 들어가므로 기여하는 합은\n$4\\{(i+1)+(i+2)+(i+3)\\}=12i+24$이다.\n따라서 한 끝점 쌍에서의 합은\n$28i+56$이다.\n\n$i=1,2,3$에 대하여 모두 더하면\n$(28+56)+(56+56)+(84+56)=336$이다.\n\n따라서 구하는 값은 $336$이다.",
    "sourceQuestionNo": "서·논술형 2",
    "displayNo": "서·논술형 2",
    "sourceOrdinal": 19,
    "sourcePageImage": "1000024898.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_SET_AGGREGATE",
    "templateKey": "TPL_SUBSET_SUM_AGGREGATE",
    "crossConceptKeys": [],
    "conditionKeys": [],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 4,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  },
  {
    "id": 20,
    "level": "상",
    "category": "원과 직선의 위치 관계",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-INTERSECTION",
    "subUnit": "원과 직선·원의 관계",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형",
      "원의 방정식",
      "원과직선",
      "교점개수",
      "구간",
      "매개변수"
    ],
    "wide": false,
    "content": "&lt;서·논술형 3&gt;\\n함수 $$f(x)=\\begin{cases}x^2+2x-14&(x\\lt8)\\\\x^2-13x+106&(x\\ge8)\\end{cases}$$와 양의 실수 $t$에 대하여 중심이 점 $(t,f(t))$이고 반지름의 길이가 $\\sqrt{5}t$인 원 $C$가 있다. 상수 $k$에 대하여 원 $C$가 직선 $2x-y+k=0$과 만나는 서로 다른 점의 개수를 함수 $g(t)$라 할 때, 함수 $g(t)$는 다음 조건을 만족시킨다.\\n&lt;조건&gt;\\n(가) $g(3)=1$\\n(나) $g(4)\\times g(9)=4$\\n$a-2\\lt t\\lt a$인 모든 실수 $t$에 대하여 $g(t)=2$를 만족시키는 실수 $a$의 최댓값을 구하는 과정을 풀이와 함께 상세히 서술하시오. [8점]",
    "choices": [],
    "answer": "12",
    "solution": "원 $C$의 중심은 $(t,f(t))$이고 반지름은 $\\sqrt5t$이다.\n중심에서 직선 $2x-y+k=0$까지의 거리는\n$\\dfrac{|2t-f(t)+k|}{\\sqrt5}$이다.\n따라서 이 거리가 반지름보다 작으면 $g(t)=2$, 같으면 $g(t)=1$, 크면 $g(t)=0$이다.\n\n먼저 $g(3)=1$을 이용한다.\n$3<8$이므로\n$f(3)=3^2+2\\cdot3-14=1$이다.\n따라서\n$\\dfrac{|6-1+k|}{\\sqrt5}=3\\sqrt5$이고\n$|k+5|=15$이므로\n$k=10$ 또는 $k=-20$이다.\n\n조건 $g(4)\\times g(9)=4$에서 각 값은 교점의 개수이므로\n$g(4)=g(9)=2$이어야 한다.\n$k=-20$이면 $t=4$에서 중심과 직선 사이의 거리가 반지름보다 커서 $g(4)=0$이 되므로 제외된다.\n따라서\n$k=10$이다.\n\n$0<t<8$에서는\n$2t-f(t)+10=24-t^2$이므로\n$g(t)=2$의 조건은\n$|24-t^2|<5t$이다.\n이를 풀면\n$3<t<8$이다.\n\n$t\\ge8$에서는\n$2t-f(t)+10=-t^2+15t-96$이므로\n$g(t)=2$의 조건은\n$|-t^2+15t-96|<5t$이다.\n이를 풀면\n$8<t<12$이다.\n따라서\n$g(t)=2$인 구간은\n$(3,8)\\cup(8,12)$이다.\n\n길이가 $2$인 열린구간 $(a-2,a)$가 이 집합에 완전히 포함되어야 한다.\n가능한 가장 오른쪽 구간은 $(10,12)$이므로\n$a$의 최댓값은 $12$이다.\n\n따라서 구하는 값은 $12$이다.",
    "sourceQuestionNo": "서·논술형 3",
    "displayNo": "서·논술형 3",
    "sourceOrdinal": 20,
    "sourcePageImage": "1000024898.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "independent_solve",
    "solutionSource": "independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "READY_FOR_REVIEW",
    "problemTypeKey": "PT_CIRCLE_LINE_RELATION",
    "templateKey": "TM_CIRCLE_INTERSECTION_COUNT",
    "crossConceptKeys": [],
    "conditionKeys": [
      "COND_POSITIVE",
      "COND_RANGE"
    ],
    "integrationPattern": "SEQUENTIAL",
    "difficultyBucket": 5,
    "difficultyConfidence": "high",
    "difficultyBoundaryFlag": "NONE",
    "legacyLevelCompatibility": "NORMAL",
    "curriculum": "2022",
    "tagConfidence": "high",
    "tagStatus": "reviewed_pass"
  }
];
