window.examTitle = "26_매산여고_2학기_중간_고1_기출";
window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 집합\\n$A=\\{4,7,13\\}$, $B=\\{2,7,11\\}$\\n에 대하여 집합 $A-B$의 모든 원소의 합을 구하면? [3.4점]",
    "choices": [
      "17",
      "13",
      "11",
      "7",
      "4"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "1",
    "displayNo": "1",
    "sourceOrdinal": 1,
    "sourcePageImage": "1000024905.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 2,
    "level": "하",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "subUnitKey": "H22-C2-01-COORDINATE_METRIC",
    "subUnit": "평면좌표와 거리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "세 점 $A(-3,5)$, $B(4,a)$, $C(b,-10)$를 꼭짓점으로 하는 삼각형 $ABC$의 무게중심이 $G(2,-1)$일 때, 실수 $a,b$에 대하여 $a+b$의 값을 구하면? [3.4점]",
    "choices": [
      "6",
      "7",
      "8",
      "9",
      "10"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "2",
    "displayNo": "2",
    "sourceOrdinal": 2,
    "sourcePageImage": "1000024905.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 3,
    "level": "하",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "subUnitKey": "H22-C2-01-COORDINATE_METRIC",
    "subUnit": "평면좌표와 거리",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 점 $A(1,a)$, $B(b,-1)$에 대하여 선분 $AB$를 $2:1$로 내분하는 점을 $P(5,1)$라 하자. $3a-2b$의 값을 구하면? (단, $a,b$는 상수) [3.5점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "3",
    "displayNo": "3",
    "sourceOrdinal": 3,
    "sourcePageImage": "1000024905.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 4,
    "level": "하",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 점 $(3,5)$, $(1,-1)$을 지나는 직선의 방정식을 $y=ax+b$라 할 때, $3a+b$의 값을 구하면? (단, $a,b$는 상수) [3.6점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "4",
    "displayNo": "4",
    "sourceOrdinal": 4,
    "sourcePageImage": "1000024906.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 5,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "집합 $A=\\{\\varnothing,1,\\{2\\},\\{1,2\\}\\}$에 대하여 다음 <보기>중 옳은 것을 있는 대로 모두 고른 것은? [3.7점]<br><div class=\"note-box\"><div style=\"text-align:center;font-weight:600;margin-bottom:4px;\">&lt;보기&gt;</div>ㄱ. $\\varnothing\\in A$<br>ㄴ. $\\{1\\}\\in A$<br>ㄷ. $\\{2\\}\\subset A$<br>ㄹ. $\\{\\varnothing,1\\}\\subset A$</div>",
    "choices": [
      "ㄱ, ㄴ",
      "ㄱ, ㄹ",
      "ㄴ, ㄷ",
      "ㄱ, ㄷ, ㄹ",
      "ㄴ, ㄷ, ㄹ"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "5",
    "displayNo": "5",
    "sourceOrdinal": 5,
    "sourcePageImage": "1000024906.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 6,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 집합 $A=\\{1,2,3,a\\}$, $B=\\{2,4,6\\}$에 대하여 집합 $X=\\{x+y\\mid x\\in A,\\ y\\in B\\}$라 할 때, $n(X)=8$이 되도록 하는 자연수 $a$의 최댓값을 구하면? (단, $a\\notin\\{1,2,3\\}$이다.) [3.7점]",
    "choices": [
      "8",
      "7",
      "6",
      "5",
      "4"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "6",
    "displayNo": "6",
    "sourceOrdinal": 6,
    "sourcePageImage": "1000024906.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 7,
    "level": "중",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "원 $x^2+y^2+6x+ky+2=0$이 $y$축에 접하고 중심이 제3사분면 위에 있을 때, 상수 $k$의 값을 구하면? [3.8점]",
    "choices": [
      "$\\sqrt2$",
      "$2\\sqrt2$",
      "$3\\sqrt2$",
      "$4\\sqrt2$",
      "$5\\sqrt2$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "7",
    "displayNo": "7",
    "sourceOrdinal": 7,
    "sourcePageImage": "1000024908.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 8,
    "level": "중",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "subUnitKey": "H22-C2-01-GEOMETRY_APPLICATION",
    "subUnit": "도형의 방정식 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 점 $A(1,3)$, $B(5,1)$과 $x$축 위의 점 $C$에 대하여 삼각형 $ABC$의 둘레의 길이에 대한 최솟값을 구하면? [3.9점]",
    "choices": [
      "$2\\sqrt5+2\\sqrt2$",
      "$2\\sqrt5+3\\sqrt2$",
      "$2\\sqrt5+4\\sqrt2$",
      "$3\\sqrt5+2\\sqrt2$",
      "$3\\sqrt5+3\\sqrt2$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "8",
    "displayNo": "8",
    "sourceOrdinal": 8,
    "sourcePageImage": "1000024908.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 9,
    "level": "중",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "점 $(1,-3)$에서 원 $(x-2)^2+(y-1)^2=4$에 그은 두 접선의 기울기의 합을 구하면? [4.0점]",
    "choices": [
      "$-\\dfrac83$",
      "$-\\dfrac53$",
      "$-\\dfrac23$",
      "$\\dfrac13$",
      "$\\dfrac43$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "9",
    "displayNo": "9",
    "sourceOrdinal": 9,
    "sourcePageImage": "1000024908.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 10,
    "level": "중",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "원 $(x-3)^2+y^2=4$를 $x$축의 방향으로 $k$만큼 평행이동하면 직선 $3x+4y-8=0$과 접할 때, 양수 $k$의 값을 구하면? [4.0점]",
    "choices": [
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "10",
    "displayNo": "10",
    "sourceOrdinal": 10,
    "sourcePageImage": "1000024909.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 11,
    "level": "중",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "어느 학급의 학생 32명 중 스마트폰 게임을 좋아하는 학생이 17명, 컴퓨터 게임을 좋아하는 학생이 20명이다. 두 게임을 모두 좋아하지 않는 학생이 적어도 3명 이상일 때, 두 게임을 모두 좋아하는 학생 수의 최댓값과 최솟값의 합을 구하면? [4.1점]",
    "choices": [
      "21",
      "22",
      "23",
      "24",
      "25"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "11",
    "displayNo": "11",
    "sourceOrdinal": 11,
    "sourcePageImage": "1000024909.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 12,
    "level": "중",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "도형"
    ],
    "wide": false,
    "content": "아래 그림과 같이 원 $x^2+y^2=36$을 접어서 점 $(3,0)$에서 $x$축에 접하도록 하였다. 선분 $AB$의 길이를 구하면? [4.1점]",
    "image": "assets/images/26_매산여고_2학기_중간_고1_기출/q12.svg",
    "choices": [
      "$4\\sqrt6$",
      "$\\sqrt{97}$",
      "$7\\sqrt2$",
      "$3\\sqrt{11}$",
      "10"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "12",
    "displayNo": "12",
    "sourceOrdinal": 12,
    "sourcePageImage": "1000024909.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 13,
    "level": "상",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "세 집합 $A$, $B$, $C$가 다음 <조건>을 만족시킨다.<br><div class=\"note-box\"><div style=\"text-align:center;font-weight:600;margin-bottom:4px;\">&lt;조건&gt;</div>(가) $n(A\\cup B)=n(A)+n(B)$<br>(나) $n((A\\cup C)\\cap(B\\cup C))=3\\times n(B-C)$</div>$n(B\\cup C)=16$일 때, $n(C)$의 값을 구하면? [4.2점]",
    "choices": [
      "4",
      "8",
      "12",
      "16",
      "20"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "13",
    "displayNo": "13",
    "sourceOrdinal": 13,
    "sourcePageImage": "1000024910.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 14,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "세 직선 $l:x-2y+2=0$, $m:2x+y-1=0$, $n:3x-y+11=0$으로 둘러싸인 삼각형의 외접원의 방정식이 있다. 이 외접원의 넓이를 구하면? [4.2점]",
    "choices": [
      "$6\\pi$",
      "$7\\pi$",
      "$8\\pi$",
      "$9\\pi$",
      "$10\\pi$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "14",
    "displayNo": "14",
    "sourceOrdinal": 14,
    "sourcePageImage": "1000024910.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 15,
    "level": "상",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "두 자연수 $k$, $m(k\\ge m)$에 대하여 전체집합 $U=\\{x\\mid x$는 $k$ 이하의 자연수$\\}$의 두 부분집합 $A=\\{x\\mid x$는 $m$의 약수$\\}$, $B$가 다음 <조건>을 만족시킨다.<br><div class=\"note-box\"><div style=\"text-align:center;font-weight:600;margin-bottom:4px;\">&lt;조건&gt;</div>(가) $B-A=\\{3,8\\}$, $n(A\\cup B^c)=8$<br>(나) 집합 $A$의 모든 원소의 합과 집합 $B$의 모든 원소의 합은 서로 같다.</div>집합 $A^c\\cap B^c$의 모든 원소의 합을 구하면? [4.3점]",
    "choices": [
      "24",
      "25",
      "26",
      "27",
      "28"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "15",
    "displayNo": "15",
    "sourceOrdinal": 15,
    "sourcePageImage": "1000024910.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 16,
    "level": "상",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "집합 $X=\\{1,2,3,4,5,6,7,8,9,10\\}$이 있다. 다음 <조건>을 만족시키는 집합 $X$의 두 부분집합 $A$, $B$에 대하여 집합 $B-A$의 모든 원소의 합의 최솟값을 구하면? [4.3점]<br><div class=\"note-box\"><div style=\"text-align:center;font-weight:600;margin-bottom:4px;\">&lt;조건&gt;</div>(가) $n(A\\cap B)=2$, $n(B-A)=3$<br>(나) $p\\in A\\cap B$이면 $\\dfrac{p+1}{2}\\in B-A$이다.<br>(다) $q\\in B-A$이면 $q+4\\in A$이다.</div>",
    "choices": [
      "6",
      "7",
      "8",
      "9",
      "10"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "16",
    "displayNo": "16",
    "sourceOrdinal": 16,
    "sourcePageImage": "1000024910.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 17,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-CIRCLE_EQUATION",
    "subUnit": "원의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "원 $(x-4)^2+(y+1)^2=4$위의 점 $P$와 두 점 $A(0,5)$, $B(-4,9)$에 대하여 $\\overline{AP}^2+\\overline{BP}^2$의 최솟값을 구하면? [4.4점]",
    "choices": [
      "144",
      "143",
      "142",
      "141",
      "140"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "17",
    "displayNo": "17",
    "sourceOrdinal": 17,
    "sourcePageImage": "1000024911.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 18,
    "level": "상",
    "category": "원의 방정식",
    "originalCategory": "원의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-03",
    "standardUnit": "원의 방정식",
    "standardUnitOrder": 3,
    "subUnitKey": "H22-C2-03-TANGENT",
    "subUnit": "원과 접선",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [],
    "wide": false,
    "content": "좌표평면에서 중심이 $(3,4)$이고 반지름의 길이가 1인 원과 직선 $y=mx(m>0)$가 서로 다른 두 점 $A,B$에서 만난다. 두 점 $A,B$에서 각각 이 원에 접하는 두 직선이 서로 수직이 되도록 하는 모든 실수 $m$의 값의 곱을 구하면? [4.4점]",
    "choices": [
      "$\\dfrac{39}{17}$",
      "$\\dfrac{37}{17}$",
      "$\\dfrac{35}{17}$",
      "$\\dfrac{33}{17}$",
      "$\\dfrac{31}{17}$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "18",
    "displayNo": "18",
    "sourceOrdinal": 18,
    "sourcePageImage": "1000024911.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 19,
    "level": "상",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "도형"
    ],
    "wide": false,
    "content": "그림과 같이 제 2사분면 위의 점 $P$에서 만나고 기울기가 양수인 서로 다른 두 직선 $l$, $m$에 대하여 직선 $l$이 $y$축, $x$축과 만나는 점을 각각 $A$, $B$라 하고, 직선 $m$이 $y$축, $x$축과 만나는 점을 각각 $C$, $D$라 할 때, $\\overline{OC}=3\\overline{OA}$이다. 직선 $l$의 기울기가 $\\dfrac13$이고, 사각형 $PDOA$의 넓이와 삼각형 $PCB$의 넓이가 모두 6일 때, 점 $P$의 $x$좌표와 $y$좌표의 곱을 구하면? (단, $O$는 원점이다.) [4.5점]",
    "image": "assets/images/26_매산여고_2학기_중간_고1_기출/q19.svg",
    "choices": [
      "$-\\dfrac{20}{7}$",
      "$-\\dfrac{22}{7}$",
      "$-\\dfrac{24}{7}$",
      "$-\\dfrac{26}{7}$",
      "$-\\dfrac{29}{7}$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "19",
    "displayNo": "19",
    "sourceOrdinal": 19,
    "sourcePageImage": "1000024912.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 20,
    "level": "상",
    "category": "도형의 이동",
    "originalCategory": "도형의 이동",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-04",
    "standardUnit": "도형의 이동",
    "standardUnitOrder": 4,
    "subUnitKey": "H22-C2-04-CORE",
    "subUnit": "도형의 이동 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "객관식",
    "layoutTag": "grid",
    "tags": [
      "도형"
    ],
    "wide": false,
    "content": "아래 그림과 같이 좌표평면 위에 제 1사분면의 점 $A$와 $y$축 위의 점 $B$에 대하여 $\\overline{AB}=\\overline{AO}=\\sqrt5$인 이등변삼각형 $OAB$가 있다. 점 $A$를 직선 $y=x$에 대하여 대칭이동한 점을 $C$라 하면 점 $C$는 직선 $y=2x$ 위의 점이다. 선분 $AB$가 두 직선 $y=x$, $y=2x$와 만나는 점을 각각 $D$, $E$라 할 때, 삼각형 $ODE$의 외접원의 둘레의 길이를 구하면? (단, $O$는 원점이다.) [4.5점]",
    "image": "assets/images/26_매산여고_2학기_중간_고1_기출/q20.svg",
    "choices": [
      "$\\dfrac{\\sqrt2}{3}\\pi$",
      "$\\dfrac{2\\sqrt2}{3}\\pi$",
      "$\\sqrt2\\pi$",
      "$\\dfrac{4\\sqrt2}{3}\\pi$",
      "$\\dfrac{5\\sqrt2}{3}\\pi$"
    ],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "20",
    "displayNo": "20",
    "sourceOrdinal": 20,
    "sourcePageImage": "1000024912.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "uploaded_page_image",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 21,
    "level": "상",
    "category": "집합",
    "originalCategory": "집합",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-05",
    "standardUnit": "집합",
    "standardUnitOrder": 5,
    "subUnitKey": "H22-C2-05-CORE",
    "subUnit": "집합 핵심 개념",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형"
    ],
    "wide": false,
    "content": "[주관식1 (서술형)] [6점](부분점수 있음)\\n두 집합 $A=\\{a,b\\}$, $B=\\{a,b,c,d,e,f\\}$에 대하여 $A\\cup X=X$, $B\\cap X=X$를 만족시키고, $X\\ne A$이며 $X\\ne B$인 집합 $X$의 개수를 구하려고 한다. 다음을 구하는 풀이과정과 답을 자세히 서술하시오. [6점](부분점수 있음.)\\n(1) 조건 $A\\cup X=X$, $B\\cap X=X$를 이용하여 두 집합 $A$, $B$와 집합 $X$ 사이의 포함 관계를 기호 $\\subset$를 사용하여 나타내시오. [2점](부분점수 없음.)\\n(2) (1)의 포함 관계를 만족시키는 집합 $X$의 개수를 구하는 풀이과정과 답을 자세히 서술하시오. [2점](부분점수 없음.)\\n(3) 조건 $X\\ne A$이며 $X\\ne B$를 만족시키는 집합 $X$의 개수를 구하는 풀이과정과 답을 자세히 서술하시오. [2점](부분점수 없음.)",
    "choices": [],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "주관식1",
    "displayNo": "주관식1",
    "sourceOrdinal": 21,
    "sourcePageImage": "1000024913.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 22,
    "level": "상",
    "category": "직선의 방정식",
    "originalCategory": "직선의 방정식",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-02",
    "standardUnit": "직선의 방정식",
    "standardUnitOrder": 2,
    "subUnitKey": "H22-C2-02-LINE_EQUATION",
    "subUnit": "직선의 방정식",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형"
    ],
    "wide": false,
    "content": "[주관식2 (서술형)] [7점](부분점수 있음)\\n세 점 $A(0,6)$, $B(3,0)$, $C(-4,0)$에 대하여 점 $P(a,b)$는 직선 $AB$위에 있다. 원점 $O$를 지나고 직선 $OP$와 수직인 직선이 직선 $AC$와 만나는 점을 $Q$라 할 때, 삼각형 $COQ$의 넓이가 24가 되도록 하는 모든 실수 $a$의 값의 합을 구하는 풀이 과정과 답을 자세히 서술하시오. (단, $ab\\ne0$)",
    "choices": [],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "주관식2",
    "displayNo": "주관식2",
    "sourceOrdinal": 22,
    "sourcePageImage": "1000024913.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  },
  {
    "id": 23,
    "level": "상",
    "category": "평면좌표",
    "originalCategory": "평면좌표",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-01",
    "standardUnit": "평면좌표",
    "standardUnitOrder": 1,
    "subUnitKey": "H22-C2-01-GEOMETRY_APPLICATION",
    "subUnit": "도형의 방정식 활용",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "서술형"
    ],
    "wide": false,
    "content": "[주관식3 (서술형)] [7점](부분점수 있음)\\n좌표평면 위의 세 점 $A$, $B$, $C$에 대하여 두 점 $A$, $B$의 좌표는 각각 $(0,a)$, $(4,0)$이고, 삼각형 $ABC$는 $\\overline{AC}=\\overline{BC}$인 직각이등변삼각형이다. $-2\\le a\\le2$일 때, 선분 $\\overline{OC}$의 길이의 최댓값과 최솟값을 구하는 풀이 과정과 답을 자세히 서술하시오.",
    "choices": [],
    "answer": "",
    "solution": "",
    "sourceQuestionNo": "주관식3",
    "displayNo": "주관식3",
    "sourceOrdinal": 23,
    "sourcePageImage": "1000024914.jpg",
    "contentSource": "uploaded_page_image",
    "choicesSource": "not_applicable",
    "answerSource": "pending_independent_solve",
    "solutionSource": "pending_independent_solution",
    "extractionStatus": "SOURCE_TEXT_EXTRACTED",
    "reviewStatus": "SOURCE_STAGE_ONLY"
  }
];
