window.examTitle = "23_왕운중_1학기_중간_중3_기출";

window.questionBank = [
  {
    "id": 1,
    "level": "중",
    "category": "제곱근의 성질",
    "originalCategory": "제곱근의 성질",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 계산이 옳지 않은 것은? [3점]",
    "choices": [
      "① $\\sqrt{24}=4\\sqrt{6}$",
      "② $\\sqrt{45}=3\\sqrt{5}$",
      "③ $-\\sqrt{8}=-2\\sqrt{2}$",
      "④ $\\sqrt{\\frac{1}{2}}\\sqrt{14}=\\sqrt{7}$",
      "⑤ $\\sqrt{3}\\sqrt{10}=\\sqrt{30}$"
    ],
    "answer": "①",
    "solution": "[키포인트] $\\sqrt{a^2b} = a\\sqrt{b}$임을 이용한다.\\n1단계: $\\sqrt{24} = \\sqrt{2^2 \\times 6} = 2\\sqrt{6}$이다.\\n2단계: $2\\sqrt{6} \\neq 4\\sqrt{6}$이므로 ①번은 옳지 않다.\\n∴ 정답: ①"
  },
  {
    "id": 2,
    "level": "중",
    "category": "다항식의 전개",
    "originalCategory": "다항식의 전개",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "content": "$(a+1)(3a-4)$를 전개했을 때 $a$의 계수를 $M$, 상수항을 $N$이라고 하자. $M+N$의 값은? [3점]",
    "choices": ["① -5", "② -4", "③ -3", "④ -2", "⑤ -1"],
    "answer": "①",
    "solution": "[키포인트] 분배법칙을 이용하여 다항식을 전개한다.\\n1단계: $(a+1)(3a-4) = 3a^2 - 4a + 3a - 4 = 3a^2 - a - 4$이다.\\n2단계: $a$의 계수 $M = -1$, 상수항 $N = -4$이다.\\n3단계: $M+N = -1 + (-4) = -5$이다.\\n∴ 정답: ①"
  },
  {
    "id": 3,
    "level": "중",
    "category": "실수의 분류",
    "originalCategory": "실수의 분류",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 표의 수 중 무리수의 개수를 구하면? [3점]\\n\\n$\\sqrt{16}, \\quad \\sqrt{\\frac{4}{9}}, \\quad \\sqrt{10}, \\quad 1-\\sqrt{(-2)^2}, \\quad 0.0\\dot{2}, \\quad \\sqrt{6.4}$",
    "choices": ["① 1개", "② 2개", "③ 3개", "④ 4개", "⑤ 5개"],
    "answer": "②",
    "solution": "[키포인트] 근호가 있다고 해서 모두 무리수인 것은 아니다.\\n1단계: $\\sqrt{16}=4$, $\\sqrt{\\frac{4}{9}}=\\frac{2}{3}$, $1-2=-1$, $0.0\\dot{2}=\\frac{2}{90}$은 모두 유리수이다.\\n2단계: $\\sqrt{10}$과 $\\sqrt{6.4}$는 근호를 벗길 수 없으므로 무리수이다.\\n∴ 정답: ②"
  },
  {
    "id": 4,
    "level": "중",
    "category": "완전제곱식",
    "originalCategory": "완전제곱식",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "content": "이차식 $x^2+3x+k$가 완전제곱식이 되도록 하는 상수 $k$의 값을 구하면? [3점]",
    "choices": ["① $\\frac{1}{4}$", "② $\\frac{3}{2}$", "③ $\\frac{9}{4}$", "④ 6", "⑤ 9"],
    "answer": "③",
    "solution": "[키포인트] $x^2+px+q$가 완전제곱식이 되려면 $q = (\\frac{p}{2})^2$이어야 한다.\\n1단계: $k = (\\frac{3}{2})^2 = \\frac{9}{4}$이다.\\n∴ 정답: ③"
  },
  {
    "id": 5,
    "level": "중",
    "category": "제곱근표",
    "originalCategory": "제곱근표",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "[5-6] 아래의 제곱근표를 이용하여 물음에 답하시오.\\n\\n<table class='question-table'><tr><th>수</th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th></tr><tr><td>3.2</td><td>1.789</td><td>1.792</td><td>1.794</td><td>1.797</td><td>1.800</td><td>1.803</td></tr><tr><td>3.3</td><td>1.817</td><td>1.819</td><td>1.822</td><td>1.825</td><td>1.828</td><td>1.830</td></tr><tr><td>33</td><td>5.745</td><td>5.753</td><td>5.762</td><td>5.771</td><td>5.779</td><td>5.788</td></tr></table>\\n\\n5. $\\sqrt{3.25}$의 어림한 값은? (제곱근표 이용) [3점]",
    "choices": ["① 1.800", "② 1.803", "③ 1.806", "④ 1.828", "⑤ 1.830"],
    "answer": "②",
    "solution": "[키포인트] 제곱근표 읽는 법을 숙지한다.\\n1단계: 세로 줄 3.2와 가로 줄 5가 만나는 값을 찾으면 1.803이다.\\n∴ 정답: ②"
  },
  {
    "id": 6,
    "level": "중",
    "category": "제곱근표의 응용",
    "originalCategory": "제곱근표의 응용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\sqrt{0.334}$의 어림한 값은? (제곱근표 이용) [4점]",
    "choices": ["① 0.1800", "② 0.1828", "③ 0.5692", "④ 0.5779", "⑤ 0.5788"],
    "answer": "④",
    "solution": "[키포인트] $\\sqrt{0.01a} = 0.1\\sqrt{a}$임을 이용한다.\\n1단계: $\\sqrt{0.334} = \\sqrt{\\frac{33.4}{100}} = \\frac{\\sqrt{33.4}}{10}$이다.\\n2단계: 표에서 $\\sqrt{33.4} = 5.779$이므로 $0.5779$이다.\\n∴ 정답: ④"
  },
  {
    "id": 7,
    "level": "중",
    "category": "실수의 대소관계",
    "originalCategory": "실수의 대소관계",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "두 실수의 대소관계가 옳지 않은 것은? [4점]",
    "choices": [
      "① $\\sqrt{5^2} < 6$",
      "② $\\sqrt{\\frac{1}{6}} < \\sqrt{\\frac{1}{2}}$",
      "③ $3\\sqrt{2} < 2\\sqrt{5}$",
      "④ $\\sqrt{\\frac{1}{2}} < \\frac{1}{2}$",
      "⑤ $\\sqrt{11} < 2\\sqrt{3}$"
    ],
    "answer": "④",
    "solution": "[키포인트] 양변을 제곱하여 비교하거나 근호 안으로 숫자를 넣어 비교한다.\\n1단계: ④의 양변을 제곱하면 $\\frac{1}{2}$과 $\\frac{1}{4}$이다.\\n2단계: $\\frac{1}{2} > \\frac{1}{4}$이므로 부등호 방향이 반대이다.\\n∴ 정답: ④"
  },
  {
    "id": 8,
    "level": "중",
    "category": "인수분해 활용",
    "originalCategory": "인수분해 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "content": "$11.2 \\times 2.9 + 11.2 \\times 2.1$을 계산하면? [4점]",
    "choices": ["① 55", "② 56", "③ 57", "④ 58", "⑤ 59"],
    "answer": "②",
    "solution": "[키포인트] 공통인수로 묶어 계산한다.\\n1단계: $11.2(2.9 + 2.1) = 11.2 \\times 5 = 56$이다.\\n∴ 정답: ②"
  },
  {
    "id": 9,
    "level": "중",
    "category": "무리수와 수직선",
    "originalCategory": "무리수와 수직선",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "아래 그림은 한 눈금의 길이가 1인 모눈종이 위에 두 정사각형 $ABCD, EFGH$와 수직선을 그린 것이다. 점 $A$와 $E$를 중심으로 반지름을 각각 $\\overline{AB}, \\overline{EF}$로 하는 원을 그려 수직선과 만나는 점을 $P, Q$라고 할 때, $P, Q$에 대응하는 수를 바르게 구한 것은? [4점]\\n\\n<svg width='200' height='120' viewBox='0 0 200 120'><defs><pattern id='grid' width='10' height='10' patternUnits='userSpaceOnUse'><path d='M 10 0 L 0 0 0 10' fill='none' stroke='lightgray' stroke-width='0.5'/></pattern></defs><rect width='200' height='120' fill='url(#grid)'/><line x1='10' y1='100' x2='190' y2='100' stroke='black' stroke-width='1.2'/><path d='M40,100 L70,90 L60,60 L30,70 Z' fill='none' stroke='black'/><path d='M110,100 L130,120 L150,100 L130,80 Z' fill='none' stroke='black'/><circle cx='40' cy='100' r='31.6' fill='none' stroke='blue' stroke-dasharray='2' clip-path='inset(0 0 20 0)'/><circle cx='130' cy='100' r='28.3' fill='none' stroke='red' stroke-dasharray='2' clip-path='inset(0 0 20 0)'/><text x='35' y='110' font-size='10'>A(-3)</text><text x='125' y='110' font-size='10'>E(2)</text><text x='68' y='110' font-size='10'>P</text><text x='155' y='110' font-size='10'>Q</text></svg>",
    "choices": [
      "① $P: -3-\\sqrt{10}, Q: 2+2\\sqrt{2}$",
      "send: $P: -3+\\sqrt{10}, Q: 2+\\sqrt{2}$",
      "③ $P: -3+\\sqrt{10}, Q: 2-2\\sqrt{2}$",
      "④ $P: -3+\\sqrt{10}, Q: 2+2\\sqrt{2}$",
      "⑤ $P: \\sqrt{10}, Q: 2\\sqrt{2}$"
    ],
    "answer": "④",
    "solution": "[키포인트] 피타고라스 정리를 이용해 빗변의 길이를 구한다.\\n1단계: $\\overline{AB} = \\sqrt{3^2+1^2} = \\sqrt{10}$이다.\\n2단계: $P$는 $-3$에서 오른쪽으로 $\\sqrt{10}$만큼 갔으므로 $-3+\\sqrt{10}$이다.\\n3단계: $\\overline{EF} = \\sqrt{2^2+2^2} = \\sqrt{8} = 2\\sqrt{2}$이다. $Q$는 $2$에서 오른쪽으로 갔으므로 $2+2\\sqrt{2}$이다.\\n∴ 정답: ④"
  },
  {
    "id": 10,
    "level": "중",
    "category": "다항식의 인수분해",
    "originalCategory": "다항식의 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "content": "다항식 $6x^2-x-2$를 인수분해하였을 때, 일차식인 두 인수의 합을 구하면? [4점]",
    "choices": ["① $5x-1$", "② $5x$", "③ $5x+1$", "④ $7x-1$", "⑤ $7x+1$"],
    "answer": "①",
    "solution": "[키포인트] 대각선 인수분해법을 이용한다.\\n1단계: $6x^2-x-2 = (2x+1)(3x-2)$이다.\\n2단계: $(2x+1) + (3x-2) = 5x-1$이다.\\n∴ 정답: ①"
  },
  {
    "id": 11,
    "level": "중",
    "category": "완전제곱식",
    "originalCategory": "완전제곱식",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "content": "다음 중 완전제곱식이 아닌 것은? [4점]",
    "choices": [
      "① $a^2+8a+16$",
      "② $x^2-12x+36$",
      "③ $4x^2+4x+1$",
      "④ $9x^2+12xy+4y^2$",
      "⑤ $a^2+10a+20$"
    ],
    "answer": "⑤",
    "solution": "[키포인트] 상수항이 (일차항계수/2)²인지 확인한다.\\n1단계: ⑤는 $(\\frac{10}{2})^2 = 25$여야 완전제곱식이 된다.\\n∴ 정답: ⑤"
  },
  {
    "id": 12,
    "level": "중",
    "category": "제곱근의 계산",
    "originalCategory": "제곱근의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 식을 간단히 하면? [4점]\\n\\n$$3\\sqrt{10} \\div 2\\sqrt{21} \\times \\sqrt{6}$$",
    "choices": [
      "① $\\frac{\\sqrt{35}}{14}$",
      "② $\\frac{\\sqrt{30}}{7}$",
      "③ $\\frac{2\\sqrt{15}}{7}$",
      "④ $\\frac{3\\sqrt{35}}{14}$",
      "⑤ $\\frac{3\\sqrt{35}}{7}$"
    ],
    "answer": "⑤",
    "solution": "[키포인트] 나눗셈을 곱셈으로 고쳐 계산한다.\\n1단계: $\\frac{3\\sqrt{10} \\times \\sqrt{6}}{2\\sqrt{21}} = \\frac{3\\sqrt{60}}{2\\sqrt{21}} = \\frac{6\\sqrt{15}}{2\\sqrt{21}}$이다.\\n2단계: $\\frac{3\\sqrt{5}}{\\sqrt{7}} = \\frac{3\\sqrt{35}}{7}$이다.\\n∴ 정답: ⑤"
  },
  {
    "id": 13,
    "level": "중",
    "category": "실수의 분류",
    "originalCategory": "실수의 분류",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 <보기> 중에서 옳은 것을 모두 고른 것은? [4점]\\n\\n<table class='question-table'><tr><td>ㄱ. 제곱근 5는 $\\pm\\sqrt{5}$이다.<br>ㄴ. $\\sqrt{9}$의 제곱근은 무리수이다.<br>ㄷ. 실수에서 무리수가 아닌 수는 모두 유리수이다.</td></tr></table>",
    "choices": ["① ㄱ", "② ㄴ", "③ ㄷ", "④ ㄱ, ㄷ", "⑤ ㄴ, ㄷ"],
    "answer": "⑤",
    "solution": "[키포인트] 실수의 체계를 정확히 이해한다.\\n1단계: ㄱ은 $\\sqrt{5}$이므로 틀리다.\\n2단계: ㄴ은 3의 제곱근 $\\pm\\sqrt{3}$이므로 맞다.\\n3단계: ㄷ은 실수의 정의상 맞다.\\n∴ 정답: ⑤"
  },
  {
    "id": 14,
    "level": "중",
    "category": "제곱근의 활용",
    "originalCategory": "제곱근의 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$x = \\frac{1}{5-2\\sqrt{6}}, y = \\frac{\\sqrt{6}-2}{\\sqrt{6}+2}$ 일 때, $x+y$의 값은? [4점]",
    "choices": ["① $10-2\\sqrt{6}$", "② $4\\sqrt{6}$", "③ 10", "④ $5+4\\sqrt{6}$", "⑤ 15"],
    "answer": "③",
    "solution": "[키포인트] 분모를 유리화한 후 합을 구한다.\\n1단계: $x = 5+2\\sqrt{6}$, $y = \\frac{(\\sqrt{6}-2)^2}{2} = 5-2\\sqrt{6}$이다.\\n2단계: $x+y = 10$이다.\\n∴ 정답: ③"
  },
  {
    "id": 15,
    "level": "중",
    "category": "제곱근의 실생활 활용",
    "originalCategory": "제곱근의 실생활 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "태풍의 반지름의 길이를 $R$ km라고 할 때, 폭풍우의 지속 시간을 $\\frac{\\sqrt{R^3}}{\\sqrt{54}}$시간이라고 한다. 반지름이 24 km일 때, 폭풍우의 지속 시간은? [4점]",
    "choices": ["① 8시간", "② $8\\sqrt{2}$시간", "③ 16시간", "④ $16\\sqrt{2}$시간", "⑤ 32시간"],
    "answer": "③",
    "solution": "[키포인트] 주어진 식에 값을 대입하여 간단히 한다.\\n1단계: $\\frac{\\sqrt{24^3}}{\\sqrt{54}} = \\sqrt{\\frac{24 \\times 24 \\times 24}{54}} = \\sqrt{256}$이다.\\n2단계: 16시간이다.\\n∴ 정답: ③"
  },
  {
    "id": 16,
    "level": "중",
    "category": "제곱근의 연쇄 계산",
    "originalCategory": "제곱근의 연쇄 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 식을 간단히 하면? [5점]\\n\\n$$\\frac{1}{\\sqrt{2}} \\times \\frac{2}{\\sqrt{6}} \\times \\frac{3}{2\\sqrt{3}} \\times \\frac{4}{2\\sqrt{5}} \\times \\cdots \\times \\frac{10}{\\sqrt{110}}$$",
    "choices": [
      "① $\\frac{\\sqrt{11}}{5}$",
      "② $\\frac{\\sqrt{11}}{10}$",
      "③ $\\frac{\\sqrt{11}}{11}$",
      "④ $\\frac{\\sqrt{110}}{10}$",
      "⑤ $\\frac{\\sqrt{110}}{11}$"
    ],
    "answer": "③",
    "solution": "[키포인트] 규칙을 찾아 약분한다.\\n1단계: 모든 항을 루트 안으로 넣으면 $\\sqrt{\\frac{1}{2} \\times \\frac{4}{6} \\times \\frac{9}{12} \\cdots}$ 형태가 된다.\\n2단계: $\\sqrt{\\frac{1}{11}} = \\frac{\\sqrt{11}}{11}$이 남는다.\\n∴ 정답: ③"
  },
  {
    "id": 17,
    "level": "중",
    "category": "제곱근의 성질",
    "originalCategory": "제곱근의 성질",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$3\\sqrt{a+10} = \\sqrt{81}$ 이고 $\\frac{\\sqrt{20+b}}{\\sqrt{3}} = 2\\sqrt{2}$ 일 때, $a+b$의 값은? [5점]",
    "choices": ["① 3", "② 6", "③ 9", "④ 12", "⑤ 15"],
    "answer": "①",
    "solution": "[키포인트] 방정식의 양변을 제곱하여 근호를 제거한다.\\n1단계: $3\\sqrt{a+10}=9$에서 $a+10=9$, $a=-1$이다.\\n2단계: $\\frac{20+b}{3}=8$에서 $b=4$이다.\\n3단계: $a+b=3$이다.\\n∴ 정답: ①"
  },
  {
    "id": 18,
    "level": "중",
    "category": "인수분해의 이해",
    "originalCategory": "인수분해의 이해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "content": "$x^2+kx-6 = (x+a)(x+b)$일 때, $k$가 될 수 있는 수를 모두 곱하면? (단, $a, b$는 정수) [5점]",
    "choices": ["① -25", "② -5", "③ 5", "④ 25", "⑤ 100"],
    "answer": "④",
    "solution": "[키포인트] 곱이 -6인 두 정수쌍을 모두 찾는다.\\n1단계: $(1,-6), (-1,6), (2,-3), (-2,3)$이 있다.\\n2단계: $k$는 $-5, 5, -1, 1$이 가능하며 곱은 25이다.\\n∴ 정답: ④"
  },
  {
    "id": 19,
    "level": "중",
    "category": "인수분해와 소수",
    "originalCategory": "인수분해와 소수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "content": "자연수 $n$에 대하여 $2n^2+11n-6$이 소수일 때, 이 소수를 구하면? [5점]",
    "choices": ["① 3", "② 5", "③ 7", "④ 11", "⑤ 13"],
    "answer": "③",
    "solution": "[키포인트] 소수는 1과 자기 자신만을 인수로 갖는다.\\n1단계: $(2n-1)(n+6)$으로 인수분해된다.\\n2단계: $2n-1=1$이어야 하므로 $n=1$이고, 대입하면 7이다.\\n∴ 정답: ③"
  },
  {
    "id": 20,
    "level": "중",
    "category": "인수분해의 응용",
    "originalCategory": "인수분해의 응용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "content": "다항식 $px^2+(2n+1)x+q$가 인수분해 되도록 하는 자연수 $n$의 최댓값은? (단, $p, q$는 소수이고 $p < q < 20$) [5점]",
    "choices": ["① 10", "② 19", "③ 20", "④ 38", "⑤ 39"],
    "answer": "②",
    "solution": "[키포인트] 인수분해 공식을 이용해 항의 계수 관계를 파악한다.\\n1단계: $pq+1 = 2n+1$이므로 $pq=2n$이다.\\n2단계: $p$는 반드시 2여야 하고 최대 소수 $q=19$일 때 $n=19$이다.\\n∴ 정답: ②"
  },
  {
    "id": 21,
    "level": "중",
    "category": "제곱근의 성질",
    "originalCategory": "제곱근의 성질",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "[서술형 1] $\\sqrt{6}$의 정수부분을 $a$, 소수부분을 $b$라 할 때, $a, b$를 각각 구하고, $\\frac{a}{b}$의 값을 구하는 과정을 서술하시오. [4점]",
    "answer": "$a=2, b=\\sqrt{6}-2, \\quad \\sqrt{6}+2$",
    "solution": "[키포인트] 정수부분을 먼저 구한 뒤 원래 수에서 뺀다.\\n1단계: $2 < \\sqrt{6} < 3$이므로 $a=2, b=\\sqrt{6}-2$이다.\\n2단계: $\\frac{2}{\\sqrt{6}-2} = \\sqrt{6}+2$이다."
  },
  {
    "id": 22,
    "level": "중",
    "category": "인수분해의 활용",
    "originalCategory": "인수분해의 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈과 인수분해",
    "standardUnitOrder": 2,
    "tags": ["서술형2"],
    "content": "[서술형 2] 하은이는 상수항을 잘못 보아 $(x+1)(x-5)$로, 정민이는 $x$의 계수를 잘못 보아 $(x-3)(x+4)$로 인수분해 하였다. 원래의 이차식을 구하고 바르게 인수분해 하시오. [5점]",
    "answer": "$x^2-4x-12 = (x-6)(x+2)$",
    "solution": "[키포인트] 각각 바르게 본 항을 찾아 조합한다.\\n1단계: 하은이는 $x$계수 -4를, 정민이는 상수항 -12를 바르게 보았다.\\n2단계: 원래 식은 $x^2-4x-12$이고 인수분해하면 $(x-6)(x+2)$이다."
  },
  {
    "id": 23,
    "level": "중",
    "category": "무리수의 기하학적 응용",
    "originalCategory": "무리수의 기하학적 응용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "[서술형 3] 정사각형 $A, B, C$의 넓이가 각각 25, $B$, 2일 때, 직사각형 $D$의 넓이를 구하시오. [5점]\\n\\n<svg width='160' height='100' viewBox='0 0 160 100'><rect x='10' y='10' width='50' height='50' fill='none' stroke='black'/><rect x='60' y='10' width='36' height='36' fill='none' stroke='black'/><rect x='96' y='10' width='14' height='14' fill='none' stroke='black'/><rect x='60' y='46' width='50' height='14' fill='none' stroke='black'/><text x='30' y='40' font-size='10'>A</text><text x='75' y='30' font-size='10'>B</text><text x='102' y='22' font-size='10'>C</text><text x='85' y='58' font-size='10'>D</text></svg>",
    "answer": "$5\\sqrt{2}-4$",
    "solution": "[키포인트] 각 변의 길이를 제곱근으로 표현한다.\\n1단계: $A$변은 5, $C$변은 $\\sqrt{2}$이다.\\n2단계: $D$가로는 $5-2\\sqrt{2}$, 높이는 $\\sqrt{2}$이다.\\n3단계: 넓이는 $5\\sqrt{2}-4$이다."
  },
  {
    "id": 24,
    "level": "중",
    "category": "제곱근의 급수 계산",
    "originalCategory": "제곱근의 급수 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "tags": ["서술형4"],
    "content": "[서술형 4] $f(n) = \\sqrt{n+1} + \\sqrt{n}$일 때, $3 < \\sum_{k=1}^{n} \\frac{1}{f(k)} < 10$을 만족하는 자연수 $n$의 개수를 구하시오. [6점]",
    "answer": "104개",
    "solution": "[키포인트] 유리화를 통해 연쇄 소거를 이용한다.\\n1단계: $\\sum = \\sqrt{n+1}-1$이다.\\n2단계: $4 < \\sqrt{n+1} < 11$에서 $15 < n < 120$이므로 104개이다."
  }
];