window.examTitle = "비상 공통수학2 함수 중단원학습점검 고1";

window.questionBank = [
  {
    "id": "qid_v1_893cc1738f1bd043c854420fe7fceab97b5b0ddc906e5d5a07a4fe79a73ee5f7",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_BASIC",
    "subUnit": "함수의 뜻과 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "함수",
      "정의역",
      "공역",
      "치역"
    ],
    "wide": false,
    "content": "오른쪽 그림의 대응은 집합 $X$에서 집합 $Y$로의 함수이다. 이 함수의 정의역, 공역, 치역을 구하시오.",
    "choices": [],
    "answer": "정의역: $\\{-1,0,1,2\\}$, 공역: $\\{0,1,2,3\\}$, 치역: $\\{0,1,3\\}$",
    "solution": "정의역은 집합 $X$의 원소 전체이므로 $\\{-1,0,1,2\\}$이다.\n공역은 집합 $Y$의 원소 전체이므로 $\\{0,1,2,3\\}$이다.\n치역은 실제로 대응되는 값들이므로 화살표가 향하는 원소 $0,1,3$이다.\n따라서 정의역은 $\\{-1,0,1,2\\}$, 공역은 $\\{0,1,2,3\\}$, 치역은 $\\{0,1,3\\}$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "image": "assets/images/비상_공통수학2_함수_중단원학습점검_고1/q01_function-mapping.png"
  },
  {
    "id": "qid_v1_b73c5abd0928cc28b3dc54486963a9a86caf6cfab2c2884753acbdc5af6ea1ca",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_BASIC",
    "subUnit": "함수의 뜻과 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "함수",
      "일대일함수",
      "항등함수",
      "상수함수"
    ],
    "wide": false,
    "content": "다음 보기 중 일대일함수, 항등함수, 상수함수인 것을 각각 찾으시오.\n보기\nㄱ. $y=-4$\nㄴ. $y=x$\nㄷ. $y=5x+7$\nㄹ. $y=x^2$",
    "choices": [],
    "answer": "일대일함수: ㄴ, ㄷ; 항등함수: ㄴ; 상수함수: ㄱ",
    "solution": "일대일함수는 서로 다른 입력값이 서로 다른 함숫값에 대응하는 함수이다. $y=x$와 $y=5x+7$은 기울기가 0이 아니므로 일대일함수이고, $y=x^2$는 $f(1)=f(-1)$이므로 일대일함수가 아니다.\n항등함수는 $f(x)=x$인 함수이므로 ㄴ이다.\n상수함수는 함숫값이 항상 같은 함수이므로 $y=-4$인 ㄱ이다.\n따라서 일대일함수는 ㄴ, ㄷ이고, 항등함수는 ㄴ, 상수함수는 ㄱ이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  },
  {
    "id": "qid_v1_2ca0c3d366c326346d789a24859d56cd39efaddc9d5e0c543fca405fde8899c5",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_COMPOSITION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "합성함수"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=2x^2-1$, $g(x)=x-3$에 대하여 다음을 구하시오.\n⑴ $(f\\circ f)(1)$\n⑵ $(g\\circ g)(0)$\n⑶ $(f\\circ g)(x)$\n⑷ $(g\\circ f)(x)$",
    "choices": [],
    "answer": "⑴ 1, ⑵ -6, ⑶ $2x^2-12x+17$, ⑷ $2x^2-4$",
    "solution": "⑴ $f(1)=2-1=1$이므로 $(f\\circ f)(1)=f(f(1))=f(1)=1$이다.\n⑵ $g(0)=-3$이므로 $(g\\circ g)(0)=g(-3)=-6$이다.\n⑶ $(f\\circ g)(x)=f(g(x))=2(x-3)^2-1=2x^2-12x+17$이다.\n⑷ $(g\\circ f)(x)=g(f(x))=(2x^2-1)-3=2x^2-4$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  },
  {
    "id": "qid_v1_196674a6d7e17be88c800d835681176d14184688b69d9180efdf9bb5f1e44503",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_INVERSE",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "역함수"
    ],
    "wide": false,
    "content": "다음 함수의 역함수를 구하시오.\n⑴ $y=5x+2$\n⑵ $y=-\\dfrac{1}{3}x+6$",
    "choices": [],
    "answer": "⑴ $y=\\frac15x-\\frac25$, ⑵ $y=-3x+18$",
    "solution": "⑴ $y=5x+2$에서 $x$와 $y$를 바꾸면 $x=5y+2$이다. 이를 $y$에 대하여 풀면 $5y=x-2$, $y=\\dfrac15x-\\dfrac25$이다. 따라서 $y=5x+2$의 역함수는 $y=\\dfrac15x-\\dfrac25$이다.\n⑵ $y=-\\dfrac13x+6$에서 $x$와 $y$를 바꾸면 $x=-\\dfrac13y+6$이다. 이를 $y$에 대하여 풀면 $y=-3x+18$이다. 따라서 역함수는 $y=-3x+18$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  },
  {
    "id": "qid_v1_0fc90031820098a588f4adc8b5d385a3382db1c64c87020be284b9d8939edcb5",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_BASIC",
    "subUnit": "함수의 뜻과 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "일대일대응",
      "역함수"
    ],
    "wide": false,
    "content": "실수 전체의 집합에서 정의된 함수\n$f(x)=\\begin{cases}3x-1&(x\\ge0)\\\\(a+2)x-1&(x<0)\\end{cases}$\n이 일대일대응이 되도록 하는 실수 $a$의 값의 범위를 구하시오.",
    "choices": [],
    "answer": "$a>-2$",
    "solution": "$x\\ge0$에서 $f(x)=3x-1$의 값의 범위는 $[-1,\\infty)$이다. 따라서 $x<0$인 부분의 함숫값은 서로 겹치지 않으면서 이 범위에 빠진 값인 $(-\\infty,-1)$ 전체를 가져야 한다.\n$x<0$에서 $f(x)=(a+2)x-1$이다. 이 부분의 값의 범위가 $(-\\infty,-1)$가 되려면 기울기가 양수여야 한다.\n$a+2>0$이므로 $a>-2$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  },
  {
    "id": "qid_v1_e604b684b6d8bb1e5a1a66a4a2ed5f257ecdf0814096eeb4f8bb676490907e98",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_COMPOSITION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "합성함수"
    ],
    "wide": false,
    "content": "두 함수 $g(x)=2x+1$, $h(x)=4x+7$이 다음을 만족시킬 때, $x$에 대한 일차함수 $f$를 각각 구하시오.\n⑴ $g\\circ f=h$\n⑵ $f\\circ g=h$",
    "choices": [],
    "answer": "⑴ $f(x)=2x+3$, ⑵ $f(x)=2x+5$",
    "solution": "⑴ $g(f(x))=h(x)$이므로 $2f(x)+1=4x+7$이다. 따라서 $f(x)=2x+3$이다.\n⑵ $f(g(x))=h(x)$이므로 $f(2x+1)=4x+7$이다. $t=2x+1$로 놓으면 $x=\\dfrac12t-\\dfrac12$이므로\n$f(t)=4(\\dfrac12t-\\dfrac12)+7=2t+5$이다. 따라서 $f(x)=2x+5$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  },
  {
    "id": "qid_v1_1548e9a28ce9c3b2eb294478cf9df3836064c5e6631394fe1b36aec735e85a21",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_COMPOSITION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "합성함수",
      "역함수"
    ],
    "wide": false,
    "content": "아래 그림과 같은 두 함수 $f$, $g$에 대하여 다음을 구하시오.\n⑴ $(f\\circ g)^{-1}(3)$\n⑵ $(f^{-1}\\circ g^{-1}\\circ f)(2)$",
    "choices": [],
    "answer": "⑴ 3, ⑵ 4",
    "solution": "그림에서 $f(2)=4$, $f(3)=2$, $f(4)=3$이고, $g(2)=2$, $g(3)=4$, $g(4)=3$이다.\n⑴ $f\\circ g$는 $2\\mapsto4$, $3\\mapsto3$, $4\\mapsto2$로 대응한다. 따라서 $(f\\circ g)^{-1}(3)=3$이다.\n⑵ $f(2)=4$, $g^{-1}(4)=3$, $f^{-1}(3)=4$이므로 $(f^{-1}\\circ g^{-1}\\circ f)(2)=4$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "image": "assets/images/비상_공통수학2_함수_중단원학습점검_고1/q07_composition-mappings.png"
  },
  {
    "id": "qid_v1_7a3405a0cf5e0947c7da4632f566e1f18f2f499779a274b3ae5aaae75a6b8de4",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_INVERSE",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "역함수"
    ],
    "wide": false,
    "content": "함수 $f(x)=ax+b$가\n$f(1)=2,\\quad f^{-1}(3)=2$\n를 만족시킬 때, 실수 $a$, $b$의 값을 구하시오.",
    "choices": [],
    "answer": "$a=1$, $b=1$",
    "solution": "$f(1)=2$이므로 $a+b=2$이다.\n또 $f^{-1}(3)=2$이면 $f(2)=3$이므로 $2a+b=3$이다.\n두 식을 빼면 $a=1$이고, $a+b=2$에 대입하면 $b=1$이다.\n따라서 $a=1$, $b=1$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  },
  {
    "id": "qid_v1_97f325507b56da54b91b498fb3691cc9c1014fb068ea07d2b59ba1ee6de3c6c4",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_COMPOSITION",
    "subUnit": "합성함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "합성함수",
      "역함수"
    ],
    "wide": false,
    "content": "두 함수 $f(x)=2x+4$, $g(x)=3x-1$에 대하여 $(f^{-1}\\circ g)(a)=2$를 만족시키는 실수 $a$의 값을 구하시오.",
    "choices": [],
    "answer": "$a=3$",
    "solution": "$(f^{-1}\\circ g)(a)=2$이므로 $f^{-1}(g(a))=2$이다. 양변에 $f$를 적용하면 $g(a)=f(2)$이다.\n$f(2)=2\\cdot2+4=8$이고 $g(a)=3a-1$이므로 $3a-1=8$이다.\n따라서 $a=3$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  },
  {
    "id": "qid_v1_e9b4daecfcbef0f887313b8cc4946787400fd5da88e68967aa02c06c8a47d4e2",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_INVERSE",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "서술형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "역함수"
    ],
    "wide": false,
    "content": "오른쪽 그림은 직선 $y=x$와 함수 $y=f(x)$의 그래프를 나타낸 것이다. 함수 $f$의 역함수가 존재할 때, 다음을 구하시오.\n(단, 모든 점선은 $x$축 또는 $y$축에 평행하다.)\n⑴ $f(c)$\n⑵ $(f\\circ f)(c)$\n⑶ $f^{-1}(d)$",
    "choices": [],
    "answer": "⑴ $b$, ⑵ $a$, ⑶ $e$",
    "solution": "그림에서 $x=c$일 때 $y=f(x)$의 값은 $b$이므로 $f(c)=b$이다.\n따라서 $(f\\circ f)(c)=f(f(c))=f(b)$이다. 그림에서 $x=b$일 때 $f(b)=a$이므로 $(f\\circ f)(c)=a$이다.\n또 $f^{-1}(d)$는 $f(x)=d$를 만족하는 $x$이다. 그림의 점선과 $y=f(x)$의 교점을 읽으면 $x=e$이므로 $f^{-1}(d)=e$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN",
    "image": "assets/images/비상_공통수학2_함수_중단원학습점검_고1/q10_inverse-function-graph.png"
  },
  {
    "id": "qid_v1_65c553a9ae9cdd494df708a45d414e574d8f53c03ef2c7d90db8decdbe78eb8a",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_BASIC",
    "subUnit": "함수의 뜻과 그래프",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "일대일대응"
    ],
    "wide": false,
    "content": "두 집합\n$X=\\{x|-2\\le x\\le2\\}$, $Y=\\{y|-1\\le y\\le3\\}$\n에 대하여 $X$에서 $Y$로의 함수 $f(x)=ax+b$가 일대일대응이 되도록 하는 실수 $a$, $b$에 대하여 $ab$의 값을 모두 구하시오.",
    "choices": [],
    "answer": "$ab=-1$ 또는 $1$",
    "solution": "$X=[-2,2]$, $Y=[-1,3]$이다. 일차함수 $f(x)=ax+b$가 $X$에서 $Y$로의 일대일대응이 되려면 양 끝점의 함숫값이 $-1$과 $3$이어야 한다.\n증가하는 경우에는 $f(-2)=-1$, $f(2)=3$이므로 $-2a+b=-1$, $2a+b=3$이다. 따라서 $a=1$, $b=1$이고 $ab=1$이다.\n감소하는 경우에는 $f(-2)=3$, $f(2)=-1$이므로 $-2a+b=3$, $2a+b=-1$이다. 따라서 $a=-1$, $b=1$이고 $ab=-1$이다.\n따라서 $ab$의 값은 $-1$ 또는 $1$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  },
  {
    "id": "qid_v1_03217249a2e569b40540be5aa0132ae6854ff539dd2fb3376ed57385fd456c2f",
    "level": "",
    "category": "함수",
    "originalCategory": "함수와 그래프",
    "standardCourse": "공통수학2",
    "standardUnitKey": "H22-C2-07",
    "standardUnit": "함수",
    "standardUnitOrder": 7,
    "subUnitKey": "H22-C2-07-FUNCTION_INVERSE",
    "subUnit": "역함수",
    "subUnitConfidence": "candidate_evidence",
    "subUnitClassificationDepth": "complete_candidate",
    "questionType": "단답형",
    "layoutTag": "grid",
    "tags": [
      "비상교육",
      "교과서",
      "고1",
      "공통수학2",
      "함수와 그래프",
      "함수",
      "중단원학습점검",
      "역함수"
    ],
    "wide": false,
    "content": "함수 $f(x)=ax+2$에 대하여 $f=f^{-1}$가 성립할 때, $f(1)$을 구하시오.(단, $a$는 실수)",
    "choices": [],
    "answer": "$f(1)=1$",
    "solution": "$f=f^{-1}$이면 $f(f(x))=x$이다. $f(x)=ax+2$를 대입하면\n$f(f(x))=a(ax+2)+2=a^2x+2a+2$이다.\n따라서 $a^2x+2a+2=x$가 모든 실수 $x$에 대하여 성립하므로 $a^2=1$이고 $2a+2=0$이다. 이로부터 $a=-1$이다.\n그러므로 $f(1)=-1+2=1$이다.",
    "difficultyBucket": "UNKNOWN",
    "difficultyConfidence": "UNKNOWN",
    "difficultyBoundaryFlag": "UNKNOWN",
    "legacyLevelCompatibility": "UNKNOWN"
  }
];
